# These are supported funding model platforms

github: [zarfld]
custom: ['https://www.paypal.com/donate/?business=YJFUYJK44JFX6&no_recurring=0&item_name=Supporting+the+LinuxCnc_PokeysLibComp+project%21+Your+sponsorship+helps+us+continue+to+develop+and+maintain+this+project.&currency_code=EUR']
