var dir_1886a74e293404880fd08fa136172a21 =
[
    [ "Examples", "dir_321868c59f41304d499de5eacba96d65.html", "dir_321868c59f41304d499de5eacba96d65" ],
    [ "hid-libusb.c", "hid-libusb_8c.html", "hid-libusb_8c" ],
    [ "hid-mac.c", "hid-mac_8c.html", "hid-mac_8c" ],
    [ "hid.c", "hid_8c.html", "hid_8c" ],
    [ "hidapi.h", "hidapi_8h.html", "hidapi_8h" ],
    [ "PoKeysLib.h", "PoKeysLib_8h.html", "PoKeysLib_8h" ],
    [ "PoKeysLib1Wire.c", "PoKeysLib1Wire_8c.html", "PoKeysLib1Wire_8c" ],
    [ "PoKeysLib_global.h", "PoKeysLib__global_8h.html", "PoKeysLib__global_8h" ],
    [ "PoKeysLibCAN.c", "PoKeysLibCAN_8c.html", "PoKeysLibCAN_8c" ],
    [ "PoKeysLibCore.c", "PoKeysLibCore_8c.html", "PoKeysLibCore_8c" ],
    [ "PoKeysLibCore.h", "PoKeysLibCore_8h.html", "PoKeysLibCore_8h" ],
    [ "PoKeysLibCoreSockets.c", "PoKeysLibCoreSockets_8c.html", "PoKeysLibCoreSockets_8c" ],
    [ "PoKeysLibCoreSockets.h", "PoKeysLibCoreSockets_8h.html", "PoKeysLibCoreSockets_8h" ],
    [ "PoKeysLibDeviceData.c", "PoKeysLibDeviceData_8c.html", "PoKeysLibDeviceData_8c" ],
    [ "PoKeysLibDevicePoKeys57Industrial.c", "PoKeysLibDevicePoKeys57Industrial_8c.html", "PoKeysLibDevicePoKeys57Industrial_8c" ],
    [ "PoKeysLibDevicePoKeys57Industrial.h", "PoKeysLibDevicePoKeys57Industrial_8h.html", "PoKeysLibDevicePoKeys57Industrial_8h" ],
    [ "PoKeysLibEasySensors.c", "PoKeysLibEasySensors_8c.html", "PoKeysLibEasySensors_8c" ],
    [ "PoKeysLibEncoders.c", "PoKeysLibEncoders_8c.html", "PoKeysLibEncoders_8c" ],
    [ "PoKeysLibFailsafe.c", "PoKeysLibFailsafe_8c.html", "PoKeysLibFailsafe_8c" ],
    [ "PoKeysLibFastUSB.c", "PoKeysLibFastUSB_8c.html", null ],
    [ "PoKeysLibI2C.c", "PoKeysLibI2C_8c.html", "PoKeysLibI2C_8c" ],
    [ "PoKeysLibIO.c", "PoKeysLibIO_8c.html", "PoKeysLibIO_8c" ],
    [ "PoKeysLibLCD.c", "PoKeysLibLCD_8c.html", "PoKeysLibLCD_8c" ],
    [ "PoKeysLibMatrixKB.c", "PoKeysLibMatrixKB_8c.html", "PoKeysLibMatrixKB_8c" ],
    [ "PoKeysLibMatrixLED.c", "PoKeysLibMatrixLED_8c.html", "PoKeysLibMatrixLED_8c" ],
    [ "PoKeysLibPoIL.c", "PoKeysLibPoIL_8c.html", "PoKeysLibPoIL_8c" ],
    [ "PoKeysLibPoNET.c", "PoKeysLibPoNET_8c.html", "PoKeysLibPoNET_8c" ],
    [ "PoKeysLibPulseEngine_v2.c", "PoKeysLibPulseEngine__v2_8c.html", "PoKeysLibPulseEngine__v2_8c" ],
    [ "PoKeysLibRTC.c", "PoKeysLibRTC_8c.html", "PoKeysLibRTC_8c" ],
    [ "PoKeysLibSPI.c", "PoKeysLibSPI_8c.html", "PoKeysLibSPI_8c" ],
    [ "PoKeysLibUART.c", "PoKeysLibUART_8c.html", "PoKeysLibUART_8c" ],
    [ "PoKeysLibWS2812.c", "PoKeysLibWS2812_8c.html", "PoKeysLibWS2812_8c" ]
];