LinuxCNC PoKeysLib-Comp: PoKeys Homing Component
PoKeys Homing Component
LinuxCNC HAL component for managing homing sequences via PoKeys PulseEngine v2.
Files
file pokeys_homecomp.c
HAL component for managing homing sequence and state logic using PoKeys PulseEngine v2.
Data Structures
struct __comp_state
PoKeys component state.
struct one_joint_home_data_t
HAL pin structure for managing homing state per joint.
struct home_local_data
Lokale Datenstruktur für einen Joint zur Homing-Verwaltung.
struct all_joints_home_data_t
Containerstruktur für alle HAL-Pin-Sätze pro Joint.
struct one_sequence_home_data_t
Repräsentiert eine einzelne Homing-Sequenz mit einer Gruppe von Achsen (Joints).
struct all_sequences_home_data_t
Struktur zur Verwaltung aller Homing-Sequenzen.
class home_state_t
Internal state representation for the homing state machine of one joint.
Macros
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
Extra setup function.
#define TRUE (1)
#define FALSE (0)
#define true (1)
#define false (0)
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#define fperiod (period * 1e-9)
#define is_module (*__comp_inst->is_module)
#define STR(s) #s
#define XSTR(s) STR(s)
#define HOME_DELAY 0.100
Length of delay between homing motions - this is intended to ensure that all motion has ceased and switch bouncing has ended. We might want to make this user adjustable, but for now it's a constant. It is in seconds.
Enumerations
enum home_sequence_state_t {
HOME_SEQUENCE_IDLE = 0 , HOME_SEQUENCE_START , HOME_SEQUENCE_DO_ONE_JOINT , HOME_SEQUENCE_DO_ONE_SEQUENCE ,
HOME_SEQUENCE_START_JOINTS , HOME_SEQUENCE_WAIT_JOINTS , HOME_SEQUENCE_IDLE = 0 , HOME_SEQUENCE_START ,
HOME_SEQUENCE_DO_ONE_JOINT , HOME_SEQUENCE_DO_ONE_SEQUENCE , HOME_SEQUENCE_START_JOINTS , HOME_SEQUENCE_WAIT_JOINTS ,
HOME_SEQUENCE_IDLE = 0 , HOME_SEQUENCE_START , HOME_SEQUENCE_DO_ONE_JOINT , HOME_SEQUENCE_DO_ONE_SEQUENCE ,
HOME_SEQUENCE_START_JOINTS , HOME_SEQUENCE_WAIT_JOINTS
}
State of the homing sequence.
enum pokeys_home_state_t {
PK_PEAxisState_axSTOPPED = 0 , PK_PEAxisState_axREADY = 1 , PK_PEAxisState_axRUNNING = 2 , PEAxisStateEx_axReadyToFinalizeHoming = 3 ,
PEAxisStateEx_axReadyToArmEncoder = 4 , PK_PEAxisState_axHOMING_RESETTING = 8 , PK_PEAxisState_axHOMING_BACKING_OFF = 9 , PK_PEAxisState_axHOME = 10 ,
PK_PEAxisState_axHOMINGSTART = 11 , PK_PEAxisState_axHOMINGSEARCH = 12 , PK_PEAxisState_axHOMINGBACK = 13 , PK_PEAxisState_axPROBED = 14 ,
PK_PEAxisState_axPROBESTART = 15 , PK_PEAxisState_axPROBESEARCH = 16 , PEAxisStateEx_HOMINGARMENCODER = 17 , PEAxisStateEx_HOMINGWaitFINALMOVE = 18 ,
PEAxisStateEx_HOMINGFINALMOVE = 19 , PK_PEAxisState_axERROR = 20 , PK_PEAxisState_axLIMIT = 30 , PK_PEAxisState_axSTOPPED = 0 ,
PK_PEAxisState_axREADY = 1 , PK_PEAxisState_axRUNNING = 2 , PEAxisStateEx_axReadyToFinalizeHoming = 3 , PEAxisStateEx_axReadyToArmEncoder = 4 ,
PK_PEAxisState_axHOMING_RESETTING = 8 , PK_PEAxisState_axHOMING_BACKING_OFF = 9 , PK_PEAxisState_axHOME = 10 , PK_PEAxisState_axHOMINGSTART = 11 ,
PK_PEAxisState_axHOMINGSEARCH = 12 , PK_PEAxisState_axHOMINGBACK = 13 , PK_PEAxisState_axPROBED = 14 , PK_PEAxisState_axPROBESTART = 15 ,
PK_PEAxisState_axPROBESEARCH = 16 , PEAxisStateEx_HOMINGARMENCODER = 17 , PEAxisStateEx_HOMINGWaitFINALMOVE = 18 , PEAxisStateEx_HOMINGFINALMOVE = 19 ,
PK_PEAxisState_axERROR = 20 , PK_PEAxisState_axLIMIT = 30
}
Enumeration of the homing state of pokeys component.
enum pokeys_home_command_t {
PK_PEAxisCommand_axIDLE = 0 , PK_PEAxisCommand_axHOMINGSTART = 1 , PK_PEAxisCommand_axARMENCODER = 2 , PK_PEAxisCommand_axHOMINGWAITFINALMOVE = 3 ,
PK_PEAxisCommand_axHOMINGFINALMOVE = 4 , PK_PEAxisCommand_axHOMINGCANCEL = 5 , PK_PEAxisCommand_axHOMINGFINALIZE = 6 , PK_PEAxisCommand_axIDLE = 0 ,
PK_PEAxisCommand_axHOMINGSTART = 1 , PK_PEAxisCommand_axARMENCODER = 2 , PK_PEAxisCommand_axHOMINGWAITFINALMOVE = 3 , PK_PEAxisCommand_axHOMINGFINALMOVE = 4 ,
PK_PEAxisCommand_axHOMINGCANCEL = 5 , PK_PEAxisCommand_axHOMINGFINALIZE = 6
}
Commands to the pulse engine.
enum local_home_state_t {
HOME_IDLE = 0 , HOME_START , HOME_UNLOCK , HOME_UNLOCK_WAIT ,
HOME_INITIAL_BACKOFF_START , HOME_INITIAL_BACKOFF_WAIT , HOME_INITIAL_SEARCH_START , HOME_INITIAL_SEARCH_WAIT ,
HOME_SET_COARSE_POSITION , HOME_FINAL_BACKOFF_START , HOME_FINAL_BACKOFF_WAIT , HOME_RISE_SEARCH_START ,
HOME_RISE_SEARCH_WAIT , HOME_FALL_SEARCH_START , HOME_FALL_SEARCH_WAIT , HOME_SET_SWITCH_POSITION ,
HOME_INDEX_ONLY_START , HOME_INDEX_SEARCH_START , HOME_INDEX_SEARCH_WAIT , HOME_SET_INDEX_POSITION ,
HOME_FINAL_MOVE_START , HOME_FINAL_MOVE_WAIT , HOME_LOCK , HOME_LOCK_WAIT ,
HOME_FINISHED , HOME_ABORT , HOME_IDLE = 0 , HOME_START ,
HOME_UNLOCK , HOME_UNLOCK_WAIT , HOME_INITIAL_BACKOFF_START , HOME_INITIAL_BACKOFF_WAIT ,
HOME_INITIAL_SEARCH_START , HOME_INITIAL_SEARCH_WAIT , HOME_SET_COARSE_POSITION , HOME_FINAL_BACKOFF_START ,
HOME_FINAL_BACKOFF_WAIT , HOME_RISE_SEARCH_START , HOME_RISE_SEARCH_WAIT , HOME_FALL_SEARCH_START ,
HOME_FALL_SEARCH_WAIT , HOME_SET_SWITCH_POSITION , HOME_INDEX_ONLY_START , HOME_INDEX_SEARCH_START ,
HOME_INDEX_SEARCH_WAIT , HOME_SET_INDEX_POSITION , HOME_FINAL_MOVE_START , HOME_FINAL_MOVE_WAIT ,
HOME_LOCK , HOME_LOCK_WAIT , HOME_FINISHED , HOME_ABORT
}
State machine for the homing process.
Functions
int rtapi_app_main (void)
void rtapi_app_exit (void)
RTAPI_MP_STRING (home_parms, "Example home parms")
void homeMotFunctions (void(*pSetRotaryUnlock)(int, int), int(*pGetRotaryIsUnlocked)(int))
Initialisiert Funktionen für das Homing von rotatorischen Achsen.
int homing_init (int id, double servo_period, int n_joints, int n_extrajoints, emcmot_joint_t *pjoints)
Initialisiert die Homing-Datenstrukturen für alle Achsen.
bool get_sequence_homed (int seq)
Prüft, ob alle Achsen einer Homing-Sequenz erfolgreich ge-homed wurden.
bool get_sequence_homing (int seq)
Prüft, ob in einer Homing-Sequenz derzeit noch mindestens eine Achse homed.
bool get_sequence_synchronized_state (int seq, int desired_state)
int pokeys_1joint_state_machine (int joint_num)
void do_home_sequence (int seq)
Starts the homing process for all joints in a homing sequence.
void check_home_sequence (int seq)
Checks the homing state of a joint sequence and advances to the next if needed.
bool get_allhomed ()
Gibt an, ob alle Achsen erfolgreich ge-homed wurden.
bool get_homed (int jno)
bool get_home_is_idle (int jno)
Prüft, ob der Home-State einer Achse auf IDLE steht.
bool get_home_is_synchronized (int jno)
Prüft, ob die Achse synchronisiert homed wurde.
bool get_home_needs_unlock_first (int jno)
Prüft, ob die Achse vor dem Homing entsperrt werden muss.
int get_home_sequence (int jno)
bool get_homing (int jno)
bool get_homing_at_index_search_wait (int jno)
bool get_homing_is_active ()
Gibt zurück, ob der Homing-Vorgang aktuell aktiv ist.
bool get_index_enable (int jno)
void read_homing_in_pins (int njoints)
Liest aktuelle Homing-relevante Zustände von den HAL-Input-Pins ein.
void write_homing_out_pins (int njoints)
Schreibt aktuelle Homing-Zustände in die verbundenen HAL-Output-Pins.
void do_home_all (void)
void do_home_joint (int jno)
Initiates and manages the homing process for a given joint or sequence.
Variables
struct __comp_state * __comp_state::_next
hal_bit_t * __comp_state::is_module
struct __comp_state * __comp_first_inst = 0
struct __comp_state * __comp_last_inst = 0
const char *const PEv2_AxisCommand_Names []
const char *const local_home_state_names []
hal_bit_t * one_joint_home_data_t::home_sw
hal_bit_t * one_joint_home_data_t::homing
hal_bit_t * one_joint_home_data_t::homed
hal_bit_t * one_joint_home_data_t::index_enable
hal_s32_t * one_joint_home_data_t::home_state
hal_u32_t * one_joint_home_data_t::PEv2_AxesState
Current state of the PulseEngine for this joint.
hal_u32_t * one_joint_home_data_t::PEv2_AxesCommand
Command output to the PulseEngine for this joint.
bool home_local_data::home_sw
bool home_local_data::homing
bool home_local_data::homed
bool home_local_data::index_enable
local_home_state_t home_local_data::home_state
pokeys_home_state_t home_local_data::PEv2_AxesState
Local copy of the current PulseEngine state for this joint.
pokeys_home_command_t home_local_data::PEv2_AxesCommand
Local command to the PulseEngine for this joint.
double home_local_data::offset
double home_local_data::home
double home_local_data::home_final_vel
double home_local_data::home_search_vel
double home_local_data::home_latch_vel
int home_local_data::home_flags
int home_local_data::home_sequence
bool home_local_data::volatile_home
int home_local_data::pause_timer
bool home_local_data::home_is_synchronized
bool home_local_data::joint_in_sequence
one_joint_home_data_t all_joints_home_data_t::jhd [EMCMOT_MAX_JOINTS]
int one_sequence_home_data_t::home_sequence
bool one_sequence_home_data_t::homing
bool one_sequence_home_data_t::homed
int one_sequence_home_data_t::joints_in_sequence
int one_sequence_home_data_t::joint_ids [EMCMOT_MAX_JOINTS]
bool one_sequence_home_data_t::is_last
int one_sequence_home_data_t::next_sequence
local_home_state_t one_sequence_home_data_t::home_state
one_sequence_home_data_t all_sequences_home_data_t::shd [EMCMOT_MAX_JOINTS]
int all_sequences_home_data_t::sequence_count
int all_sequences_home_data_t::min_sequence
int all_sequences_home_data_t::max_sequence
int all_sequences_home_data_t::current_sequence
int get_sequence_synchronized_state_seq_memory = 0
int get_sequence_synchronized_state_memory = 0
int get_sequence_synchronized_PEv2_AxesState_memory [8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
int get_sequence_synchronized_state_PEv2_ready_in_sequence_memory = 0
bool Homing_ArmEncodereDone [8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
Homing state machine handler for a single PoKeys-controlled joint.
int jsm_AxesState_memory [8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
int jsm_home_state_memory [8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
bool home_sw_active_memory [8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
bool get_homed_memory [8]
Prüft, ob eine Achse erfolgreich ge-homed wurde.
int get_home_sequence_memory [8]
Gibt die Homing-Sequenznummer der angegebenen Achse zurück.
bool get_homing_memory [8]
Gibt zurück, ob eine Achse aktuell im Homing-Vorgang ist.
bool get_homing_at_index_search_wait_memory [8]
Prüft, ob der Index-Suchmodus beim Homing aktiv ist.
bool get_index_enable_memory [8]
Gibt zurück, ob der Index-Enable-Status für eine Achse gesetzt ist.
int dhs_homed_count_memory = 0
Executes the homing sequence state machine for multiple CNC joints.
int dhs_joints_in_sequence_memory = 0
int homed_memory [8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
Detailed Description
LinuxCNC HAL component for managing homing sequences via PoKeys PulseEngine v2.
This module implements a finite state machine for handling homing commands and statuses for each axis controlled by a PoKeys device. It communicates via HAL pins and interacts with PulseEngine v2 state and command structures.
The component is suitable for synchronized multi-axis homing and integrates tightly with other components like pokeys.comp.
Macro Definition Documentation
EXTRA_CLEANUP
EXTRA_CLEANUP () static void extra_cleanup(void)
Definition at line 251 of file pokeys_homecomp.c.
EXTRA_SETUP
EXTRA_SETUP () static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
Extra setup function.
Parameters
home_parms
Returns
0 on success, -1 on failure
Definition at line 249 of file pokeys_homecomp.c.
FALSE
#define FALSE (0)
Definition at line 203 of file pokeys_homecomp.c.
false
#define false (0)
Definition at line 207 of file pokeys_homecomp.c.
fperiod
#define fperiod (period * 1e-9)
Definition at line 253 of file pokeys_homecomp.c.
FUNCTION
#define FUNCTION (name) static void name(struct __comp_state *__comp_inst, long period)
Definition at line 247 of file pokeys_homecomp.c.
HOME_DELAY
#define HOME_DELAY 0.100
Length of delay between homing motions - this is intended to ensure that all motion has ceased and switch bouncing has ended. We might want to make this user adjustable, but for now it's a constant. It is in seconds.
Definition at line 303 of file pokeys_homecomp.c.
is_module
#define is_module (*__comp_inst->is_module)
Definition at line 255 of file pokeys_homecomp.c.
STR
#define STR (s) #s
Definition at line 267 of file pokeys_homecomp.c.
TRUE
#define TRUE (1)
Definition at line 201 of file pokeys_homecomp.c.
true
#define true (1)
Definition at line 205 of file pokeys_homecomp.c.
XSTR
#define XSTR (s) STR(s)
Definition at line 268 of file pokeys_homecomp.c.
Enumeration Type Documentation
home_sequence_state_t
enum home_sequence_state_t
State of the homing sequence.
Parameters
joint_num
Returns
1 if at least one joint is homing
Enumerator
HOME_SEQUENCE_IDLE
HOME_SEQUENCE_START
HOME_SEQUENCE_DO_ONE_JOINT
HOME_SEQUENCE_DO_ONE_SEQUENCE
HOME_SEQUENCE_START_JOINTS
HOME_SEQUENCE_WAIT_JOINTS
HOME_SEQUENCE_IDLE
HOME_SEQUENCE_START
HOME_SEQUENCE_DO_ONE_JOINT
HOME_SEQUENCE_DO_ONE_SEQUENCE
HOME_SEQUENCE_START_JOINTS
HOME_SEQUENCE_WAIT_JOINTS
HOME_SEQUENCE_IDLE
HOME_SEQUENCE_START
HOME_SEQUENCE_DO_ONE_JOINT
HOME_SEQUENCE_DO_ONE_SEQUENCE
HOME_SEQUENCE_START_JOINTS
HOME_SEQUENCE_WAIT_JOINTS
Definition at line 321 of file pokeys_homecomp.c.
local_home_state_t
enum local_home_state_t
State machine for the homing process.
Parameters
joint_num
Returns
1 if at least one joint is homing
Enumerator
HOME_IDLE
HOME_START
HOME_UNLOCK
HOME_UNLOCK_WAIT
HOME_INITIAL_BACKOFF_START
HOME_INITIAL_BACKOFF_WAIT
HOME_INITIAL_SEARCH_START
HOME_INITIAL_SEARCH_WAIT
HOME_SET_COARSE_POSITION
HOME_FINAL_BACKOFF_START
HOME_FINAL_BACKOFF_WAIT
HOME_RISE_SEARCH_START
HOME_RISE_SEARCH_WAIT
HOME_FALL_SEARCH_START
HOME_FALL_SEARCH_WAIT
HOME_SET_SWITCH_POSITION
HOME_INDEX_ONLY_START
HOME_INDEX_SEARCH_START
HOME_INDEX_SEARCH_WAIT
HOME_SET_INDEX_POSITION
HOME_FINAL_MOVE_START
HOME_FINAL_MOVE_WAIT
HOME_LOCK
HOME_LOCK_WAIT
HOME_FINISHED
HOME_ABORT
HOME_IDLE
HOME_START
HOME_UNLOCK
HOME_UNLOCK_WAIT
HOME_INITIAL_BACKOFF_START
HOME_INITIAL_BACKOFF_WAIT
HOME_INITIAL_SEARCH_START
HOME_INITIAL_SEARCH_WAIT
HOME_SET_COARSE_POSITION
HOME_FINAL_BACKOFF_START
HOME_FINAL_BACKOFF_WAIT
HOME_RISE_SEARCH_START
HOME_RISE_SEARCH_WAIT
HOME_FALL_SEARCH_START
HOME_FALL_SEARCH_WAIT
HOME_SET_SWITCH_POSITION
HOME_INDEX_ONLY_START
HOME_INDEX_SEARCH_START
HOME_INDEX_SEARCH_WAIT
HOME_SET_INDEX_POSITION
HOME_FINAL_MOVE_START
HOME_FINAL_MOVE_WAIT
HOME_LOCK
HOME_LOCK_WAIT
HOME_FINISHED
HOME_ABORT
Definition at line 375 of file pokeys_homecomp.c.
pokeys_home_command_t
enum pokeys_home_command_t
Commands to the pulse engine.
Parameters
joint_num
Returns
1 if at least one joint is homing
Enumerator
PK_PEAxisCommand_axIDLE
PK_PEAxisCommand_axHOMINGSTART
PK_PEAxisCommand_axARMENCODER
PK_PEAxisCommand_axHOMINGWAITFINALMOVE
PK_PEAxisCommand_axHOMINGFINALMOVE
PK_PEAxisCommand_axHOMINGCANCEL
PK_PEAxisCommand_axHOMINGFINALIZE
PK_PEAxisCommand_axIDLE
PK_PEAxisCommand_axHOMINGSTART
PK_PEAxisCommand_axARMENCODER
PK_PEAxisCommand_axHOMINGWAITFINALMOVE
PK_PEAxisCommand_axHOMINGFINALMOVE
PK_PEAxisCommand_axHOMINGCANCEL
PK_PEAxisCommand_axHOMINGFINALIZE
Definition at line 360 of file pokeys_homecomp.c.
pokeys_home_state_t
enum pokeys_home_state_t
Enumeration of the homing state of pokeys component.
Enumerator
PK_PEAxisState_axSTOPPED
PK_PEAxisState_axREADY
PK_PEAxisState_axRUNNING
PEAxisStateEx_axReadyToFinalizeHoming
PEAxisStateEx_axReadyToArmEncoder
PK_PEAxisState_axHOMING_RESETTING
PK_PEAxisState_axHOMING_BACKING_OFF
PK_PEAxisState_axHOME
PK_PEAxisState_axHOMINGSTART
PK_PEAxisState_axHOMINGSEARCH
PK_PEAxisState_axHOMINGBACK
PK_PEAxisState_axPROBED
PK_PEAxisState_axPROBESTART
PK_PEAxisState_axPROBESEARCH
PEAxisStateEx_HOMINGARMENCODER
PEAxisStateEx_HOMINGWaitFINALMOVE
PEAxisStateEx_HOMINGFINALMOVE
PK_PEAxisState_axERROR
PK_PEAxisState_axLIMIT
PK_PEAxisState_axSTOPPED
PK_PEAxisState_axREADY
PK_PEAxisState_axRUNNING
PEAxisStateEx_axReadyToFinalizeHoming
PEAxisStateEx_axReadyToArmEncoder
PK_PEAxisState_axHOMING_RESETTING
PK_PEAxisState_axHOMING_BACKING_OFF
PK_PEAxisState_axHOME
PK_PEAxisState_axHOMINGSTART
PK_PEAxisState_axHOMINGSEARCH
PK_PEAxisState_axHOMINGBACK
PK_PEAxisState_axPROBED
PK_PEAxisState_axPROBESTART
PK_PEAxisState_axPROBESEARCH
PEAxisStateEx_HOMINGARMENCODER
PEAxisStateEx_HOMINGWaitFINALMOVE
PEAxisStateEx_HOMINGFINALMOVE
PK_PEAxisState_axERROR
PK_PEAxisState_axLIMIT
Definition at line 328 of file pokeys_homecomp.c.
Function Documentation
check_home_sequence()
void check_home_sequence (int seq)
Checks the homing state of a joint sequence and advances to the next if needed.
This function evaluates the status flags (homed, homing, home_state) for the current sequence. If the sequence is marked as completed (homed), and it is the last sequence, the homing process is finished. Otherwise, it continues with the next sequence via do_home_sequence().
If the sequence is in homing progress (homing) and all joints report as homed, the state is updated accordingly. It also resets the state if no joints report homing anymore.
Parameters
seq The index of the homing sequence to check.
Definition at line 2127 of file pokeys_homecomp.c.
do_home_all()
void do_home_all (void)
Definition at line 2494 of file pokeys_homecomp.c.
References get_homing_is_active(), and rtapi_print_msg().
do_home_joint()
void do_home_joint (int jno)
Initiates and manages the homing process for a given joint or sequence.
This function determines the current AxesState of the specified joint and issues appropriate commands (e.g. HOMINGSTART, IDLE, HOMINGFINALIZE) to the PoKeys Pulse Engine. If a sequence of joints is being homed together (home_sequence < 0), it checks if all involved joints are ready or finished before advancing the sequence.
If jno is negative, it attempts to start the homing sequence at index 0.
Parameters
jno Joint number to home; if negative, the first sequence is used.
Definition at line 2540 of file pokeys_homecomp.c.
References rtapi_print_msg().
do_home_sequence()
void do_home_sequence (int seq)
Starts the homing process for all joints in a homing sequence.
This function iterates over all joints in the specified sequence seq, resets their homing flags, initializes them to HOME_START, and sends the PK_PEAxisCommand_axHOMINGSTART command to the PoKeys Pulse Engine if the current state allows it (i.e., STOPPED or READY). All joints in the sequence are marked as part of the active sequence via joint_in_sequence = 1.
Parameters
seq Index of the sequence to start.
Definition at line 2054 of file pokeys_homecomp.c.
get_allhomed()
bool get_allhomed (void)
Gibt an, ob alle Achsen erfolgreich ge-homed wurden.
Diese Funktion gibt den globalen Zustand allhomed zurück, der in der Homing-Logik aktualisiert wird, sobald alle Achsen ihre Homing-Sequenz erfolgreich abgeschlossen haben.
Hinweis: Der ursprünglich implementierte Prüfdurchlauf über alle Achsen ist derzeit auskommentiert, die Funktion verlässt sich auf den zentral verwalteten Zustand allhomed.
Returns
true (1), wenn alle Achsen ge-homed sind, sonst false (0).
Definition at line 2188 of file pokeys_homecomp.c.
Referenced by do_homing().
get_home_is_idle()
bool get_home_is_idle (int jno)
Prüft, ob der Home-State einer Achse auf IDLE steht.
Diese Funktion gibt zurück, ob sich die angegebene Achse aktuell im Zustand HOME_IDLE befindet, also kein aktiver Homing-Vorgang läuft.
Parameters
jno Die Joint-Nummer (Achse), die geprüft werden soll.
Returns
true (1), wenn sich die Achse im Zustand HOME_IDLE befindet, sonst false (0).
Definition at line 2240 of file pokeys_homecomp.c.
get_home_is_synchronized()
bool get_home_is_synchronized (int jno)
Prüft, ob die Achse synchronisiert homed wurde.
Diese Funktion gibt zurück, ob der Homing-Vorgang für die angegebene Achse im Rahmen einer synchronisierten Sequenz erfolgte.
Parameters
jno Die Joint-Nummer (Achse), für die der Synchronisationsstatus abgefragt werden soll.
Returns
true (1), wenn die Achse synchronisiert homed wurde, sonst false (0).
Definition at line 2256 of file pokeys_homecomp.c.
get_home_needs_unlock_first()
bool get_home_needs_unlock_first (int jno)
Prüft, ob die Achse vor dem Homing entsperrt werden muss.
Diese Funktion überprüft, ob das HOME_UNLOCK_FIRST-Flag im home_flags-Feld der angegebenen Achse gesetzt ist. Falls ja, muss die Achse vor dem Start des Homing-Vorgangs entriegelt oder bewegt werden (z. B. um einen Endschalter zu verlassen).
Parameters
jno Die Joint-Nummer (Achse), für die geprüft werden soll.
Returns
true (1), wenn die Achse zuerst "unlocked" werden muss, sonst false (0).
Definition at line 2273 of file pokeys_homecomp.c.
get_home_sequence()
int get_home_sequence (int jno)
Definition at line 2290 of file pokeys_homecomp.c.
References get_home_sequence_memory.
get_homed()
bool get_homed (int jno)
Definition at line 2221 of file pokeys_homecomp.c.
get_homing()
bool get_homing (int jno)
Definition at line 2310 of file pokeys_homecomp.c.
get_homing_at_index_search_wait()
bool get_homing_at_index_search_wait (int jno)
Definition at line 2334 of file pokeys_homecomp.c.
References get_homing_at_index_search_wait_memory, HOME_INDEX_SEARCH_WAIT, and rtapi_print_msg().
get_homing_is_active()
bool get_homing_is_active (void)
Gibt zurück, ob der Homing-Vorgang aktuell aktiv ist.
Diese Funktion liefert den Status des homing_active-Flags. Zusätzlich gibt sie eine Debug-Nachricht aus, wenn sich der Status seit dem letzten Aufruf geändert hat.
Returns
true, wenn das System gerade eine Homing-Sequenz ausführt, sonst false.
Definition at line 2358 of file pokeys_homecomp.c.
Referenced by do_home_all().
get_index_enable()
bool get_index_enable (int jno)
Definition at line 2379 of file pokeys_homecomp.c.
References get_index_enable_memory.
get_sequence_homed()
bool get_sequence_homed (int seq)
Prüft, ob alle Achsen einer Homing-Sequenz erfolgreich ge-homed wurden.
Diese Funktion iteriert über alle Achsen der gegebenen Sequenz und überprüft das homed-Flag. Nur wenn alle Achsen in der Sequenz als homed markiert sind, wird true zurückgegeben. Andernfalls erfolgt ein vorzeitiger Abbruch mit false.
Parameters
seq Die Indexnummer der Homing-Sequenz.
Returns
true (1), wenn alle Achsen der Sequenz ge-homed sind, sonst false (0).
Definition at line 888 of file pokeys_homecomp.c.
get_sequence_homing()
bool get_sequence_homing (int seq)
Prüft, ob in einer Homing-Sequenz derzeit noch mindestens eine Achse homed.
Diese Funktion durchläuft alle Achsen in der angegebenen Sequenz und prüft, ob für mindestens eine Achse das Flag homing aktiv ist. Sie wird z. B. in der Zustandsmaschine verwendet, um festzustellen, ob eine Sequenz noch läuft oder abgeschlossen ist.
Parameters
seq Die Indexnummer der Homing-Sequenz.
Returns
true (1), wenn mindestens eine Achse in der Sequenz noch homed, sonst false (0).
Definition at line 915 of file pokeys_homecomp.c.
get_sequence_synchronized_state()
bool get_sequence_synchronized_state (int seq, int desired_state)
Definition at line 933 of file pokeys_homecomp.c.
References get_sequence_synchronized_state_memory, get_sequence_synchronized_state_seq_memory, and rtapi_print_msg().
homeMotFunctions()
void homeMotFunctions (void(*)(int, int) pSetRotaryUnlock, int(*)(int) pGetRotaryIsUnlocked)
Initialisiert Funktionen für das Homing von rotatorischen Achsen.
Diese Funktion dient als Schnittstelle zur Übergabe von Funktionen für das Entsperren und Abfragen von Rotary-Achsen (z. B. Drehachsen mit mechanischer Verriegelung). Derzeit ist sie als Platzhalter implementiert und enthält keine Logik.
Parameters
pSetRotaryUnlock Funktionszeiger, der eine Achse und einen Status übergibt, um die Achse zu entsperren. Signature: void func(int joint, int unlock)
pGetRotaryIsUnlocked Funktionszeiger zur Abfrage, ob eine Achse entsperrt ist. Signature: int func(int joint) (Rückgabewert: 1 = entsperrt)
Definition at line 742 of file pokeys_homecomp.c.
homing_init()
int homing_init (int id, double servo_period, int n_joints, int n_extrajoints, emcmot_joint_t * pjoints)
Initialisiert die Homing-Datenstrukturen für alle Achsen.
Diese Funktion wird beim Start des Homing-Subsystems aufgerufen und setzt alle Zustände und Parameter der Homing-Finite-State-Machine auf definierte Anfangswerte.
Dabei wird auch der Ausgangszustand der PEv2-Achsenkommunikation gesetzt:
PEv2_AxesState = PK_PEAxisState_axSTOPPED
PEv2_AxesCommand = PK_PEAxisCommand_axIDLE
Parameters
id HAL-Komponenten-ID
servo_period Servoperiode in Sekunden
n_joints Anzahl der konfigurierten Achsen
n_extrajoints Zusätzliche Achsen (z. B. Spindel)
pjoints Pointer auf die emcmot_joint_t-Struktur aller Achsen
Returns
0 bei Erfolg, sonst Fehlercode von makepins()
Definition at line 836 of file pokeys_homecomp.c.
pokeys_1joint_state_machine()
int pokeys_1joint_state_machine (int joint_num)
switch to directly map PEv2_AxesState to home_state as transitions are done during pokeys homing, and status changes just report
switch to analyz homestate
nothing to do
This state is called after the machine has made a low speed pass to determine the limit switch location. It sets index-enable, which tells the encoder driver to reset its counter to zero and clear the enable when the next index pulse arrives.
set the index enable
PEAxisStateEx_HOMINGARMENCODERThis state is called after the machine has found the home switch and "armed" the encoder counter to reset on the next index pulse. It continues at low speed until an index pulse is detected, at which point it sets the final home position. If the move ends or hits a limit before an index pulse occurs, the home is aborted.
has an index pulse arrived yet? encoder driver clears enable when it does
set the index position
waits until all Joints in Sequence are Ready, then
is the joint already moving?
yes, reset delay, wait until joint stops
has delay timed out?
no, update timer and wait some more
is the joint already moving?
yes, reset delay, wait until joint stops
has delay timed out?
no, update timer and wait some more
Definition at line 1060 of file pokeys_homecomp.c.
read_homing_in_pins()
void read_homing_in_pins (int njoints)
Liest aktuelle Homing-relevante Zustände von den HAL-Input-Pins ein.
Diese Funktion aktualisiert die internen Homing-Datenstrukturen (H[jno]) mit Werten, die über die HAL-Eingabepins zur Verfügung gestellt werden. Typischerweise geschieht dies einmal pro Servo-Zyklus.
Sie liest folgende Werte ein:
home_sw (Home-Schalter-Zustand)
index_enable (Aktivierung des Indexsignals)
PEv2_AxesState (aktueller Achsstatus der PulseEngine v2)
Es wird ein Logeintrag erzeugt, wenn sich der Achsstatus im Vergleich zum letzten bekannten Zustand verändert hat.
Parameters
njoints Anzahl der konfigurierten Achsen (Joints).
Definition at line 2406 of file pokeys_homecomp.c.
rtapi_app_exit()
void rtapi_app_exit (void)
Definition at line 242 of file pokeys_homecomp.c.
References hal_exit().
rtapi_app_main()
int rtapi_app_main (void)
Definition at line 228 of file pokeys_homecomp.c.
RTAPI_MP_STRING()
RTAPI_MP_STRING (home_parms , "Example home parms")
write_homing_out_pins()
void write_homing_out_pins (int njoints)
Schreibt aktuelle Homing-Zustände in die verbundenen HAL-Output-Pins.
Diese Funktion überträgt den internen Zustand (H[jno]) jeder Achse auf die zugehörigen HAL-Ausgabepins, die in joint_home_data->jhd[jno] gespeichert sind. Sie wird typischerweise einmal pro Servo-Zyklus aufgerufen.
Zusätzlich wird ein Logeintrag geschrieben, wenn sich der PEv2_AxesCommand für eine Achse ändert.
Parameters
njoints Anzahl der konfigurierten Achsen (Joints).
Definition at line 2449 of file pokeys_homecomp.c.
Variable Documentation
__comp_first_inst
struct __comp_state* __comp_first_inst = 0
Definition at line 196 of file pokeys_homecomp.c.
__comp_last_inst
struct __comp_state * __comp_last_inst = 0
Definition at line 196 of file pokeys_homecomp.c.
_next
struct __comp_state * __comp_state::_next
Definition at line 193 of file pokeys_homecomp.c.
current_sequence
int all_sequences_home_data_t::current_sequence
Definition at line 661 of file pokeys_homecomp.c.
dhs_homed_count_memory
int dhs_homed_count_memory = 0
Executes the homing sequence state machine for multiple CNC joints.
This function handles joint homing by advancing the global sequence_state and controlling individual joints via PEv2_AxesCommand.
Detailed Behavior:
Depending on the current sequence_state, this function:
Selects joints involved in the current homing sequence.
Updates joint status flags (H[*].home_state, H[*].homed, H[*].homing).
Issues homing commands (PEv2_AxesCommand) based on the feedback from PEv2_AxesState.
Manages index-enable logic (H[*].index_enable) and sequence transitions.
Relevant State Variables:
sequence_state: Controls global sequence flow.
H[*].home_state: Individual joint homing state (HOME_START, etc.).
H[*].homed: Indicates joint has completed homing.
H[*].homing: Indicates joint homing is active.
H[*].PEv2_AxesState: Current PoKeys Pulse Engine axis state.
H[*].PEv2_AxesCommand: Commands sent to the PoKeys Pulse Engine.
H[*].index_enable: Controls position indexing during homing.
State Machine (<tt>sequence_state</tt>) Overview:
PlantUML Interaction Diagram:
State Variables & Commands:
Variable Description
H[*].home_state Individual joint homing state
H[*].homed Set to 1 when joint homing is completed
H[*].homing Set to 1 during active homing
H[*].PEv2_AxesState Axis state reported from PoKeys Pulse Engine
H[*].PEv2_AxesCommand Axis command sent to PoKeys Pulse Engine
H[*].index_enable Controls encoder indexing during homing
Axis State Transitions (<tt>PEv2_AxesState</tt> → <tt>PEv2_AxesCommand</tt>):
PEv2_AxesState Resulting Command (PEv2_AxesCommand)
axSTOPPED, axREADY, axRUNNING axHOMINGSTART
axERROR axHOMINGCANCEL
axHOME (final state) axIDLE
axReadyToFinalizeHoming axHOMINGFINALIZE
axReadyToArmEncoder axARMENCODER
axHOMINGARMENCODER axHOMINGWAITFINALMOVE
axHOMINGWaitFINALMOVE axHOMINGFINALMOVE
axHOMINGFINALMOVE axIDLE
Note
All transitions are logged via rtapi_print_msg for detailed debugging.
Definition at line 2866 of file pokeys_homecomp.c.
dhs_joints_in_sequence_memory
int dhs_joints_in_sequence_memory = 0
Definition at line 2867 of file pokeys_homecomp.c.
get_home_sequence_memory
int get_home_sequence_memory[8]
Gibt die Homing-Sequenznummer der angegebenen Achse zurück.
Diese Funktion liefert den aktuellen Wert der home_sequence-Eigenschaft der Achse mit der angegebenen Joint-Nummer. Die Homing-Sequenz definiert, ob eine Achse einzeln oder gemeinsam mit anderen Achsen referenziert wird.
Parameters
jno Die Joint-Nummer (Achse), deren Homing-Sequenz abgefragt werden soll.
Returns
Die Homing-Sequenznummer dieser Achse (negativ = gruppiert, positiv = einzeln).
Definition at line 2289 of file pokeys_homecomp.c.
Referenced by get_home_sequence().
get_homed_memory
bool get_homed_memory[8]
Prüft, ob eine Achse erfolgreich ge-homed wurde.
Gibt true zurück, wenn der Homing-Vorgang für die angegebene Achse abgeschlossen wurde und die Achse als "ge-homed" markiert ist. Optional wird eine Debug-Ausgabe generiert.
Parameters
jno Die Joint-Nummer (Achse), die geprüft werden soll.
Returns
true (1), wenn die Achse ge-homed ist, sonst false (0).
Definition at line 2220 of file pokeys_homecomp.c.
get_homing_at_index_search_wait_memory
bool get_homing_at_index_search_wait_memory[8]
Prüft, ob der Index-Suchmodus beim Homing aktiv ist.
Diese Funktion gibt zurück, ob für die angegebene Achse (jno) das Flag index_enable gesetzt ist. Dies weist typischerweise darauf hin, dass sich die Achse im Homing-Abschnitt zur Index-Suche befindet.
Parameters
jno Die Joint-Nummer (Achse), deren Status abgefragt werden soll.
Returns
true, wenn index_enable gesetzt ist, sonst false.
Definition at line 2333 of file pokeys_homecomp.c.
Referenced by get_homing_at_index_search_wait().
get_homing_memory
bool get_homing_memory[8]
Gibt zurück, ob eine Achse aktuell im Homing-Vorgang ist.
Diese Funktion liest das homing-Flag aus der joint_home_data Struktur für die angegebene Achse und gibt zurück, ob Homing aktiv ist.
Parameters
jno Die Joint-Nummer (Achse), deren Homing-Status abgefragt werden soll.
Returns
true, wenn sich die Achse im Homing-Prozess befindet, sonst false.
Definition at line 2309 of file pokeys_homecomp.c.
get_index_enable_memory
bool get_index_enable_memory[8]
Gibt zurück, ob der Index-Enable-Status für eine Achse gesetzt ist.
Diese Funktion prüft, ob das Indexsignal für die angegebene Achse (Joint) aktuell aktiviert ist. Dies kann im Homing-Prozess verwendet werden, um zu erkennen, ob die Achse auf ein Index-Event wartet oder dieses verwendet.
Parameters
jno Joint-Nummer der Achse.
Returns
true, wenn Index aktiviert ist, sonst false.
Definition at line 2378 of file pokeys_homecomp.c.
Referenced by get_index_enable().
get_sequence_synchronized_PEv2_AxesState_memory
int get_sequence_synchronized_PEv2_AxesState_memory[8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
Definition at line 931 of file pokeys_homecomp.c.
get_sequence_synchronized_state_memory
int get_sequence_synchronized_state_memory = 0
Definition at line 930 of file pokeys_homecomp.c.
Referenced by get_sequence_synchronized_state().
get_sequence_synchronized_state_PEv2_ready_in_sequence_memory
int get_sequence_synchronized_state_PEv2_ready_in_sequence_memory = 0
Definition at line 932 of file pokeys_homecomp.c.
get_sequence_synchronized_state_seq_memory
int get_sequence_synchronized_state_seq_memory = 0
Definition at line 929 of file pokeys_homecomp.c.
Referenced by get_sequence_synchronized_state().
home
double home_local_data::home
Definition at line 581 of file pokeys_homecomp.c.
home_final_vel
double home_local_data::home_final_vel
Definition at line 582 of file pokeys_homecomp.c.
home_flags
int home_local_data::home_flags
Definition at line 585 of file pokeys_homecomp.c.
home_is_synchronized
bool home_local_data::home_is_synchronized
Definition at line 590 of file pokeys_homecomp.c.
home_latch_vel
double home_local_data::home_latch_vel
Definition at line 584 of file pokeys_homecomp.c.
home_search_vel
double home_local_data::home_search_vel
Definition at line 583 of file pokeys_homecomp.c.
home_sequence [1/2]
int home_local_data::home_sequence
Definition at line 586 of file pokeys_homecomp.c.
home_sequence [2/2]
int one_sequence_home_data_t::home_sequence
Definition at line 625 of file pokeys_homecomp.c.
home_state [1/3]
hal_s32_t * one_joint_home_data_t::home_state
Definition at line 488 of file pokeys_homecomp.c.
home_state [2/3]
local_home_state_t home_local_data::home_state
Definition at line 545 of file pokeys_homecomp.c.
home_state [3/3]
local_home_state_t one_sequence_home_data_t::home_state
Definition at line 635 of file pokeys_homecomp.c.
home_sw [1/2]
hal_bit_t * one_joint_home_data_t::home_sw
Definition at line 483 of file pokeys_homecomp.c.
home_sw [2/2]
bool home_local_data::home_sw
Definition at line 541 of file pokeys_homecomp.c.
home_sw_active_memory
bool home_sw_active_memory[8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
Definition at line 1054 of file pokeys_homecomp.c.
homed [1/3]
hal_bit_t * one_joint_home_data_t::homed
Definition at line 485 of file pokeys_homecomp.c.
homed [2/3]
bool home_local_data::homed
Definition at line 543 of file pokeys_homecomp.c.
homed [3/3]
bool one_sequence_home_data_t::homed
Definition at line 627 of file pokeys_homecomp.c.
homed_memory
int homed_memory[8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
Definition at line 2868 of file pokeys_homecomp.c.
homing [1/3]
hal_bit_t * one_joint_home_data_t::homing
Definition at line 484 of file pokeys_homecomp.c.
homing [2/3]
bool home_local_data::homing
Definition at line 542 of file pokeys_homecomp.c.
homing [3/3]
bool one_sequence_home_data_t::homing
Definition at line 626 of file pokeys_homecomp.c.
Homing_ArmEncodereDone
bool Homing_ArmEncodereDone[8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
Homing state machine handler for a single PoKeys-controlled joint.
This function implements the homing logic for a single joint, using feedback from the PoKeys Pulse Engine v2 axis state. It maps internal PoKeys axis states to LinuxCNC-style homing state transitions and drives the associated joint’s homing process forward.
The function updates H[joint_num].home_state, homed, and homing flags, and manages synchronization of multiple joints within the same home_sequence.
The homing states follow the Pulse Engine v2 sequence and extend it with LinuxCNC-style behaviors (e.g. index-enable logic, homing-finalize handoff).
This function synchronizes the internal PoKeys Pulse Engine v2 homing state (PEv2_AxesState) with the LinuxCNC-side home_state and commands the corresponding PEv2_AxesCommand when needed.
Parameters
joint_num Index of the joint to process.
Returns
1 if homing is active for the joint, 0 otherwise.
Definition at line 1051 of file pokeys_homecomp.c.
index_enable [1/2]
hal_bit_t * one_joint_home_data_t::index_enable
Definition at line 486 of file pokeys_homecomp.c.
index_enable [2/2]
bool home_local_data::index_enable
Definition at line 544 of file pokeys_homecomp.c.
is_last
bool one_sequence_home_data_t::is_last
Definition at line 632 of file pokeys_homecomp.c.
is_module
hal_bit_t* __comp_state::is_module
Definition at line 194 of file pokeys_homecomp.c.
jhd
one_joint_home_data_t all_joints_home_data_t::jhd[EMCMOT_MAX_JOINTS]
Definition at line 605 of file pokeys_homecomp.c.
joint_ids
int one_sequence_home_data_t::joint_ids[EMCMOT_MAX_JOINTS]
Definition at line 630 of file pokeys_homecomp.c.
joint_in_sequence
bool home_local_data::joint_in_sequence
Definition at line 592 of file pokeys_homecomp.c.
joints_in_sequence
int one_sequence_home_data_t::joints_in_sequence
Definition at line 629 of file pokeys_homecomp.c.
jsm_AxesState_memory
int jsm_AxesState_memory[8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
Definition at line 1052 of file pokeys_homecomp.c.
jsm_home_state_memory
int jsm_home_state_memory[8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
Definition at line 1053 of file pokeys_homecomp.c.
local_home_state_names
const char* const local_home_state_names[]
Initial value:
= { [HOME_IDLE] = "HOME_IDLE",
                                               [HOME_START] = "HOME_START",
                                               [HOME_UNLOCK] = "HOME_UNLOCK",
                                               [HOME_UNLOCK_WAIT] = "HOME_UNLOCK_WAIT",
                                               [HOME_INITIAL_BACKOFF_START] = "HOME_INITIAL_BACKOFF_START",
                                               [HOME_INITIAL_BACKOFF_WAIT] = "HOME_INITIAL_BACKOFF_WAIT",
                                               [HOME_INITIAL_SEARCH_START] = "HOME_INITIAL_SEARCH_START",
                                               [HOME_INITIAL_SEARCH_WAIT] = "HOME_INITIAL_SEARCH_WAIT",
                                               [HOME_SET_COARSE_POSITION] = "HOME_SET_COARSE_POSITION",
                                               [HOME_FINAL_BACKOFF_START] = "HOME_FINAL_BACKOFF_START",
                                               [HOME_FINAL_BACKOFF_WAIT] = "HOME_FINAL_BACKOFF_WAIT",
                                               [HOME_RISE_SEARCH_START] = "HOME_RISE_SEARCH_START",
                                               [HOME_RISE_SEARCH_WAIT] = "HOME_RISE_SEARCH_WAIT",
                                               [HOME_FALL_SEARCH_START] = "HOME_FALL_SEARCH_START",
                                               [HOME_FALL_SEARCH_WAIT] = "HOME_FALL_SEARCH_WAIT",
                                               [HOME_SET_SWITCH_POSITION] = "HOME_SET_SWITCH_POSITION",
                                               [HOME_INDEX_ONLY_START] = "HOME_INDEX_ONLY_START",
                                               [HOME_INDEX_SEARCH_START] = "HOME_INDEX_SEARCH_START",
                                               [HOME_INDEX_SEARCH_WAIT] = "HOME_INDEX_SEARCH_WAIT",
                                               [HOME_SET_INDEX_POSITION] = "HOME_SET_INDEX_POSITION",
                                               [HOME_FINAL_MOVE_START] = "HOME_FINAL_MOVE_START",
                                               [HOME_FINAL_MOVE_WAIT] = "HOME_FINAL_MOVE_WAIT",
                                               [HOME_LOCK] = "HOME_LOCK",
                                               [HOME_LOCK_WAIT] = "HOME_LOCK_WAIT",
                                               [HOME_FINISHED] = "HOME_FINISHED",
                                               [HOME_ABORT] = "HOME_ABORT" }
Definition at line 408 of file pokeys_homecomp.c.
max_sequence
int all_sequences_home_data_t::max_sequence
Definition at line 659 of file pokeys_homecomp.c.
min_sequence
int all_sequences_home_data_t::min_sequence
Definition at line 658 of file pokeys_homecomp.c.
next_sequence
int one_sequence_home_data_t::next_sequence
Definition at line 633 of file pokeys_homecomp.c.
offset
double home_local_data::offset
Definition at line 580 of file pokeys_homecomp.c.
pause_timer
int home_local_data::pause_timer
Definition at line 589 of file pokeys_homecomp.c.
PEv2_AxesCommand [1/2]
hal_u32_t * one_joint_home_data_t::PEv2_AxesCommand
Command output to the PulseEngine for this joint.
Pointer to the HAL pin used to issue commands to the PulseEngine, typically named pokeys_homecomp.N.PEv2_AxesCommand for joint N.
The value corresponds to an entry in the ePoKeysPECmd enum, such as PE_CMD_NONE, PE_CMD_HOME, PE_CMD_ENABLE, etc.
This value is evaluated by the PulseEngine logic (e.g., in PoKeysCompPulseEngine_v2) and triggers state changes such as starting the homing sequence.
Note
Only written by pokeys_homecomp, and typically connected to the corresponding PEv2.axis.N.command pin in the PulseEngine component.
See also
ePoKeysPECmd
PEv2_AxesState
PoKeysCompPulseEngine_v2
Definition at line 526 of file pokeys_homecomp.c.
PEv2_AxesCommand [2/2]
pokeys_home_command_t home_local_data::PEv2_AxesCommand
Local command to the PulseEngine for this joint.
This variable holds the next command to be issued to the PulseEngine (e.g., PE_CMD_HOME, PE_CMD_NONE, etc.) and will be written to the corresponding HAL pin PEv2_AxesCommand during write_homing_out_pins.
It corresponds to the ePoKeysPECmd enumeration.
See also
one_joint_home_data_t::PEv2_AxesCommand
ePoKeysPECmd
Definition at line 577 of file pokeys_homecomp.c.
PEv2_AxesState [1/2]
hal_u32_t * one_joint_home_data_t::PEv2_AxesState
Current state of the PulseEngine for this joint.
Pointer to the HAL pin exported by the PulseEngine HAL component, typically named like pokeys.PEv2.axis.N.state, where N is the joint number.
The value corresponds to an entry in the ePoKeysPEState enum, such as PE_STATE_IDLE, PE_STATE_HOMING, etc.
Used by pokeys_homecomp to react to motion state changes during the homing sequence.
See also
ePoKeysPEState
PoKeysCompPulseEngine_v2
Definition at line 505 of file pokeys_homecomp.c.
PEv2_AxesState [2/2]
pokeys_home_state_t home_local_data::PEv2_AxesState
Local copy of the current PulseEngine state for this joint.
This variable mirrors the value read from the HAL pin PEv2_AxesState (e.g., pokeys_homecomp.N.PEv2_AxesState) and represents the current state of the PulseEngine for this joint.
It corresponds to the ePoKeysPEState enumeration.
Updated in read_homing_in_pins and used for state machine transitions.
See also
one_joint_home_data_t::PEv2_AxesState
ePoKeysPEState
Definition at line 562 of file pokeys_homecomp.c.
PEv2_AxisCommand_Names
const char* const PEv2_AxisCommand_Names[]
Initial value:
= {
    [PK_PEAxisCommand_axIDLE] = "PK_PEAxisCommand_axIDLE", [PK_PEAxisCommand_axHOMINGSTART] = "PK_PEAxisCommand_axHOMINGSTART", [PK_PEAxisCommand_axARMENCODER] = "PK_PEAxisCommand_axARMENCODER", [PK_PEAxisCommand_axHOMINGWAITFINALMOVE] = "PK_PEAxisCommand_axHOMINGWAITFINALMOVE", [PK_PEAxisCommand_axHOMINGFINALMOVE] = "PK_PEAxisCommand_axHOMINGFINALMOVE", [PK_PEAxisCommand_axHOMINGCANCEL] = "PK_PEAxisCommand_axHOMINGCANCEL", [PK_PEAxisCommand_axHOMINGFINALIZE] = "PK_PEAxisCommand_axHOMINGFINALIZE"
}
Definition at line 404 of file pokeys_homecomp.c.
sequence_count
int all_sequences_home_data_t::sequence_count
Definition at line 656 of file pokeys_homecomp.c.
shd
one_sequence_home_data_t all_sequences_home_data_t::shd[EMCMOT_MAX_JOINTS]
Definition at line 655 of file pokeys_homecomp.c.
volatile_home
bool home_local_data::volatile_home
Definition at line 587 of file pokeys_homecomp.c.