LinuxCNC PoKeysLib-Comp: HAL Component: pokeys
HAL Component: pokeys
Main HAL component that integrates PoKeys devices into LinuxCNC.
Files
file PoKeysComp.h
Main header file for the PoKeys HAL component in LinuxCNC.
Data Structures
class PoKeysHALComponent
Represents a single PoKeys device and its runtime state.
struct one_adcout_data_t
struct one_adcin_data_t
struct one_digiIO_data_t
struct all_IO_data_t
struct one_encoder_data_t
Structure representing a single encoder channel with HAL and PoKeys configuration.
struct all_encoder_data_t
Structure representing all encoder channels and debug output for the PoKeys HAL component.
struct one_PoNET_data_t
Structure holding HAL parameters and pin references for one PoNET device.
struct one_kbd48CNCButton_data_t
Represents a single button and LED pair on the kbd48CNC PoNET module.
struct all_PoNET_data_t
Contains all PoNET-related data for communication with PoKeys devices.
struct PEv2_data_t
State machine transitions for homing logic.
Enumerations
enum ePK_EncoderOptions {
PK_ENCODER_OPTION_ENABLE = (1 << 0) , PK_ENCODER_OPTION_4X_SAMPLING = (1 << 1) , PK_ENCODER_OPTION_2X_SAMPLING = (1 << 2) , PK_ENCODER_OPTION_KEYMAP_DIR_A = (1 << 4) ,
PK_ENCODER_OPTION_MACRO_DIR_A = (1 << 5) , PK_ENCODER_OPTION_KEYMAP_DIR_B = (1 << 6) , PK_ENCODER_OPTION_MACRO_DIR_B = (1 << 7)
}
Bitfield definitions for encoder options (used with command 0x11, byte 4).
enum ePK_FastEncoderOptions {
PK_FASTENCODER_CONF_CFG1 = (0x01) , PK_FASTENCODER_CONF_CFG2 = (0x10) , PK_FASTENCODER_DISABLE_4X_SAMPLING = (1 << 4) , PK_FASTENCODER_INVERT_E1 = (1 << 5) ,
PK_FASTENCODER_INVERT_E2 = (1 << 6) , PK_FASTENCODER_INVERT_E3 = (1 << 7)
}
enum ePK_UltraFastEncoderOptions { PK_UFENCODER_INVERT_DIRECTION = (1 << 0) , PK_UFENCODER_SIGNAL_MODE = (1 << 1) , PK_UFENCODER_ENABLE_4X_SAMPLING = (1 << 2) }
enum PoKeysHALComponent::pokeys_homing_algorithm_t
pokeys_homing_algorithm_t
enum pokeys_axis_state_ext_t {
PEAxisStateEx_axReadyToFinalizeHoming = 3 , PEAxisStateEx_axReadyToArmEncoder = 4 , PEAxisStateEx_HOMINGARMENCODER = 17 , PEAxisStateEx_HOMINGWaitFINALMOVE = 18 ,
PEAxisStateEx_HOMINGFINALMOVE = 19
}
Extended PoKeys Pulse Engine axis states used for homing synchronization.
enum pokeys_home_status_t {
PK_Homing_axIDLE = 0 , PK_Homing_axHOMINGSTART = 1 , PK_Homing_axARMENCODER = 2 , PK_Homing_axHOMINGWaitFinalMove = 3 ,
PK_Homing_axHOMINGFinalMove = 4 , PK_Homing_axHOMINGCancel = 5 , PK_Homing_axHOMINGFinalize = 6
}
Internal homing state machine used by the PoKeys HAL component to coordinate LinuxCNC-style homing sequences in conjunction with PoKeys Pulse Engine v2.
enum PoKeysHALComponent::pokeys_home_command_t
Homing command for the axis.
Functions
int PKEncoder_export_pins (char *prefix, long extra_arg, int id, int njoints, all_encoder_data_t *Encoder_data)
Exports HAL encoder pins for the PoKeys device.
int PKEncoder_export_params (char *prefix, long extra_arg, int id, int njoints)
Exports HAL parameters related to encoder configuration.
void PKEncoder_Update (sPoKeysDevice *dev)
Updates encoder data from the PoKeys device and writes values to HAL pins.
void PKEncoder_Setup (sPoKeysDevice *dev)
Placeholder function to perform encoder-specific setup actions.
void PKEncoder_ReadIniFile (sPoKeysDevice *dev)
Reads encoder-related settings from the INI configuration file.
void PKEncoder_WriteIniFile (sPoKeysDevice *dev)
Writes encoder-related configuration to the INI file.
void PKPoExtBus_Update (sPoKeysDevice *dev)
Updates the PoExtBus data from and to the PoKeys device.
void PKPoExtBus_Setup (sPoKeysDevice *dev)
Initializes or configures the PoExtBus interface on the PoKeys device.
int PKPoNet_export_pins (char *prefix, long extra_arg, int id, int njoints, all_PoNET_data_t *poNET_data, sPoKeysDevice *dev)
Exports HAL pins and parameters for PoNET modules and optionally kbd48CNC devices.
void PKPoNet_Update (sPoKeysDevice *dev)
Updates the state of the connected PoNET modules, specifically kbd48CNC.
void PKPoNet_Setup (sPoKeysDevice *dev)
Initializes or configures PoNET-related settings for the given device.
int PKPEv2_export_pins (char *prefix, long extra_arg, int comp_id, PEv2_data_t *Pev2_data, sPoKeysDevice *dev)
Export HAL pins and parameters for the PoKeys Pulse Engine v2 (PEv2).
bool Get_BitOfByte (uint8_t in_Byte, int Bit_Id)
Retrieves the value of a specific bit in a byte.
uint8_t Set_BitOfByte (uint8_t in_Byte, int Bit_Id, bool value)
Sets or clears a specific bit in a byte.
void Read_digin_LimitHome_Pins (sPoKeysDevice *dev, int i)
Reads and updates the HAL pin states for limit and home switches for a specific axis.
int32_t PEv2_StatusGet (sPoKeysDevice *dev)
Retrieves and processes the current status of the PoKeys Pulse Engine v2 (PEv2).
int32_t PEv2_Status2Get (sPoKeysDevice *dev)
Reads and updates the state of dedicated limit and home inputs from the PoKeys Pulse Engine v2.
int32_t PEv2_ExternalOutputsSet (sPoKeysDevice *dev)
Sets the state of external relay and open-collector outputs on the PoKeys device.
int32_t PEv2_PulseEngineSetup (sPoKeysDevice *dev)
Configures and applies Pulse Engine v2 settings to the PoKeys device.
int32_t PEv2_AdditionalParametersGet (sPoKeysDevice *dev)
Reads additional Pulse Engine v2 parameters from the PoKeys device.
int32_t PEv2_AdditionalParametersSet (sPoKeysDevice *dev)
Updates and sets additional Pulse Engine v2 parameters, such as the emergency input pin.
int PoKeysHALComponent::PKIO_export_pins (char *prefix, long extra_arg, int id, all_IO_data_t *Io_data, sPoKeysDevice *dev)
Export HAL pins and parameters for PoKeys analog and digital I/O.
void PoKeysHALComponent::PKIO_Update (sPoKeysDevice *dev)
Updates PoKeys I/O states from and to hardware.
void PoKeysHALComponent::PKIO_Setup (sPoKeysDevice *dev)
Initializes the PoKeys digital and analog I/O configuration.
void PoKeysHALComponent::PKIO_ReadIniFile (sPoKeysDevice *dev)
Reads and applies I/O configuration values for the PoKeys device from the INI file.
void PoKeysHALComponent::PKIO_WriteIniFile (sPoKeysDevice *dev)
Writes the current PoKeys I/O configuration to the INI file.
int32_t PoKeysHALComponent::PEv2_HomingStateSyncedTrigger (sPoKeysDevice *dev, int seq, pokeys_home_status_t RequiredState, pokeys_home_status_t NextState)
Triggers a synchronized homing state transition for all axes in a given homing sequence.
int32_t PoKeysHALComponent::PEv2_AxisConfigurationSet (sPoKeysDevice *dev, int AxisId)
Set the axis configuration of the PoKeys device.
int PoKeysHALComponent::PEv2_PulseEngineSetup (sPoKeysDevice *dev)
Configures the PulseEngine v2 using current settings.
void PoKeysHALComponent::PKPEv2_Setup (sPoKeysDevice *dev)
Applies INI-based configuration to PulseEngine and IO.
void PoKeysHALComponent::PKPEv2_Update (sPoKeysDevice *dev, bool HAL_Machine_On)
Updates PulseEngine feedback and status.
Variables
hal_u32_t * one_adcout_data_t::deb_out
hal_u32_t * one_adcout_data_t::deb_setval
hal_float_t * one_adcout_data_t::value
hal_bit_t * one_adcout_data_t::enable
hal_float_t one_adcout_data_t::offset
hal_float_t one_adcout_data_t::scale
hal_float_t one_adcout_data_t::high_limit
hal_float_t one_adcout_data_t::low_limit
hal_float_t one_adcout_data_t::max_v
hal_u32_t one_adcout_data_t::PinId
hal_float_t * one_adcin_data_t::value_raw
hal_float_t * one_adcin_data_t::value
hal_float_t one_adcin_data_t::scale
hal_float_t one_adcin_data_t::offset
hal_bit_t * one_digiIO_data_t::digin_in
hal_bit_t * one_digiIO_data_t::digin_in_not
hal_bit_t * one_digiIO_data_t::digout_out
hal_bit_t one_digiIO_data_t::digin_invert
hal_bit_t one_digiIO_data_t::digout_invert
hal_u32_t * one_digiIO_data_t::counter_value
hal_u32_t one_digiIO_data_t::PinFunction
bool one_digiIO_data_t::DigitalValueSet_ignore
one_adcout_data_t all_IO_data_t::adcout [6]
hal_u32_t all_IO_data_t::adcout_pwm_period
hal_u32_t * all_IO_data_t::adcout_deb_outv
one_adcin_data_t all_IO_data_t::adcin [7]
one_digiIO_data_t all_IO_data_t::Pin [55]
hal_u32_t * all_IO_data_t::deb_out
Detailed Description
Main HAL component that integrates PoKeys devices into LinuxCNC.
HAL interface for PoKeys devices and PulseEngine integration.
Handles HAL lifecycle, device discovery, data polling, and pin creation. Supports digital/analog I/O, encoders, counters, analog outputs, and watchdog logic.
This group contains all functions, structures, and definitions related to the PoKeys HAL component for LinuxCNC.
Enumeration Type Documentation
ePK_EncoderOptions
enum ePK_EncoderOptions
Bitfield definitions for encoder options (used with command 0x11, byte 4).
These options control sampling modes, key/macro mapping and enabling for PoKeys encoders.
Enumerator
PK_ENCODER_OPTION_ENABLE
Enable encoder.
PK_ENCODER_OPTION_4X_SAMPLING
Enable 4x sampling (default is 1x)
PK_ENCODER_OPTION_2X_SAMPLING
Enable 2x sampling (default is 1x)
PK_ENCODER_OPTION_KEYMAP_DIR_A
Direct key mapping for direction A.
PK_ENCODER_OPTION_MACRO_DIR_A
Map to macro for direction A.
PK_ENCODER_OPTION_KEYMAP_DIR_B
Direct key mapping for direction B.
PK_ENCODER_OPTION_MACRO_DIR_B
Map to macro for direction B.
Definition at line 377 of file PoKeysComp.h.
ePK_FastEncoderOptions
enum ePK_FastEncoderOptions
Enumerator
PK_FASTENCODER_CONF_CFG1
PK_FASTENCODER_CONF_CFG2
PK_FASTENCODER_DISABLE_4X_SAMPLING
PK_FASTENCODER_INVERT_E1
PK_FASTENCODER_INVERT_E2
PK_FASTENCODER_INVERT_E3
Definition at line 388 of file PoKeysComp.h.
ePK_UltraFastEncoderOptions
enum ePK_UltraFastEncoderOptions
Enumerator
PK_UFENCODER_INVERT_DIRECTION
PK_UFENCODER_SIGNAL_MODE
PK_UFENCODER_ENABLE_4X_SAMPLING
Definition at line 390 of file PoKeysComp.h.
pokeys_axis_state_ext_t
enum pokeys_axis_state_ext_t
Extended PoKeys Pulse Engine axis states used for homing synchronization.
These states are not part of the original PoKeysLib ePK_PEAxisState enum, but are introduced to support additional homing steps required by LinuxCNC-style sequences.
They are used internally by the HAL component to track the progress of encoder arming and synchronized final moves after PoKeys has reached PK_PEAxisState_axHOME.
Note
These states are assigned IDs that continue beyond the original PoKeysLib enum values.
Enumerator
PEAxisStateEx_axReadyToFinalizeHoming
Axis has finished (pokeys)homing sequence.
PEAxisStateEx_axReadyToArmEncoder
Axis is ready to arm the encoder after PoKeys internal homing is complete. This state is used to synchronize with other axes in the same homing sequence.
PEAxisStateEx_HOMINGARMENCODER
Axis is preparing to reset encoder position to zero. Sent after PoKeys internal homing is done, just before PK_PEAxisCommand_axARMENCODER.
PEAxisStateEx_HOMINGWaitFINALMOVE
Axis is waiting for all other joints in the sequence to be ready before executing the final move to the home position.
PEAxisStateEx_HOMINGFINALMOVE
Axis is currently performing the final coordinated move to its home position.
Definition at line 843 of file PoKeysComp.h.
pokeys_home_command_t
enum pokeys_home_command_t
Homing command for the axis.
Definition at line 930 of file PoKeysComp.h.
pokeys_home_status_t
enum pokeys_home_status_t
Internal homing state machine used by the PoKeys HAL component to coordinate LinuxCNC-style homing sequences in conjunction with PoKeys Pulse Engine v2.
These states are used for synchronized transitions between multiple joints via PEv2_HomingStateSyncedTrigger(). They do not reflect the PoKeysLib AxesState, but a separate synchronization FSM maintained inside the HAL component.
Enumerator
PK_Homing_axIDLE
Axis is idle and not part of a current homing sequence.
PK_Homing_axHOMINGSTART
Homing procedure has been initiated (e.g., via PK_PEAxisCommand_axHOMINGSTART). PoKeys internal homing starts here.
PK_Homing_axARMENCODER
Encoder arming phase: Axis resets its position to the configured zero point. This usually happens after the PoKeys homing sequence has completed.
PK_Homing_axHOMINGWaitFinalMove
Axis waits for all other joints in the same sequence to reach this state before it triggers a synchronized final move to the home position.
PK_Homing_axHOMINGFinalMove
Axis executes the final coordinated move to its home position (absolute).
PK_Homing_axHOMINGCancel
Homing procedure has been aborted.
PK_Homing_axHOMINGFinalize
Internal PoKeys homing procedure has completed. This is typically the last state before encoder arming or final move is triggered.
Note
Despite the name, this is not the final state of the entire LinuxCNC homing sequence.
Definition at line 883 of file PoKeysComp.h.
pokeys_homing_algorithm_t
enum pokeys_homing_algorithm_t
pokeys_homing_algorithm_t
Definition at line 820 of file PoKeysComp.h.
Function Documentation
Get_BitOfByte()
bool Get_BitOfByte (uint8_t in_Byte, int Bit_Id)
Retrieves the value of a specific bit in a byte.
Extracts the value of the bit at the specified position from the input byte.
Parameters
in_Byte The input byte to read from.
Bit_Id The bit position to read (07).
Returns
true if the bit at position Bit_Id is set (1), false if it is clear (0).
Note
Bit positions outside the range 07 are not checked and may cause undefined behavior.
Definition at line 797 of file PokeysCompPulsEngine_base.c.
Referenced by PEv2_Status2Get().
PEv2_AdditionalParametersGet()
int32_t PEv2_AdditionalParametersGet (sPoKeysDevice * dev)
Reads additional Pulse Engine v2 parameters from the PoKeys device.
This function retrieves the current additional configuration of the Pulse Engine v2, such as the emergency stop input pin, using PK_PEv2_AdditionalParametersGet(). If the configuration is successfully read and either ApplyIniSettings is false or no HAL configuration is specified for the emergency pin, the value is stored in PEv2_data->PEv2_digin_Emergency_Pin after adjusting the index.
This allows later logic to determine whether the emergency input pin should be configured or left unchanged.
Parameters
dev Pointer to the PoKeys device structure.
Return values
PK_OK on success (currently not explicitly returned consider adding return PK_OK;)
error code if PK_PEv2_AdditionalParametersGet() fails (also not currently returned)
Note
Includes a short delay via usleep() if ULAPI is defined to accommodate userspace execution timing.
See also
PK_PEv2_AdditionalParametersGet
PEv2_AdditionalParametersSet
Definition at line 1710 of file PokeysCompPulsEngine_base.c.
References ApplyIniSettings, dev, sPoKeysPEv2::EmergencyInputPin, sPoKeysDevice::PEv2, PEv2_data, PEv2_data_t::PEv2_digin_Emergency_Pin, PK_OK, PK_PEv2_AdditionalParametersGet(), RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), and sleepdur.
Referenced by PoKeysHALComponent::PKPEv2_Setup().
PEv2_AdditionalParametersSet()
int32_t PEv2_AdditionalParametersSet (sPoKeysDevice * dev)
Updates and sets additional Pulse Engine v2 parameters, such as the emergency input pin.
This function checks whether Pulse Engine v2 additional parameters (e.g., the emergency stop input pin) need to be updated on the PoKeys device, and if so, applies the new configuration. It reads the current configuration using PK_PEv2_AdditionalParametersGet() and compares it with the desired values defined in PEv2_data. If discrepancies are found and ApplyIniSettings is true, the values are updated on the device using PK_PEv2_AdditionalParametersSet() and saved via PK_SaveConfiguration().
If the emergency input pin is mapped to a regular PoKeys pin (ID >= 9), it also ensures that the corresponding pin function is correctly set to PK_PinCap_digitalInput.
Parameters
dev Pointer to the PoKeys device structure.
Return values
PK_OK on successful update or no change needed.
error code (e.g., PK_ERR_*) if a communication or configuration error occurred.
Note
The function includes retry logic and short delays (usleep) if ULAPI is defined, ensuring compatibility with non-realtime environments.
See also
PK_PEv2_AdditionalParametersGet
PK_PEv2_AdditionalParametersSet
PK_SaveConfiguration
Definition at line 1751 of file PokeysCompPulsEngine_base.c.
References ApplyIniSettings, dev, doSetup, sPoKeysPEv2::EmergencyInputPin, IO_data, sPoKeysDevice::PEv2, PEv2_data, PEv2_data_t::PEv2_digin_Emergency_Pin, all_IO_data_t::Pin, one_digiIO_data_t::PinFunction, PK_OK, PK_PEv2_AdditionalParametersGet(), PK_PEv2_AdditionalParametersSet(), PK_PinCap_digitalInput, PK_SaveConfiguration(), RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), and sleepdur.
Referenced by PoKeysHALComponent::PKPEv2_Setup().
PEv2_AxisConfigurationSet()
int32_t PEv2_AxisConfigurationSet (sPoKeysDevice * dev, int AxisId)
Set the axis configuration of the PoKeys device.
Definition at line 2296 of file PokeysCompPulsEngine_base.c.
References ApplyIniSettings, sPoKeysPEv2::AxesConfig, sPoKeysPEv2::AxesSwitchConfig, sPoKeysPEv2::AxisEnableOutputPins, dev, doSetup, sPoKeysPEv2::FilterHomeSwitch, sPoKeysPEv2::FilterLimitMSwitch, sPoKeysPEv2::FilterLimitPSwitch, sPoKeysPEv2::FilterProbeInput, sPoKeysPEv2::HomeBackOffDistance, sPoKeysPEv2::HomingAlgorithm, sPoKeysPEv2::HomingReturnSpeed, sPoKeysPEv2::HomingSpeed, sPoKeysPEv2::InvertAxisEnable, IO_data, sPoKeysPEv2::MaxAcceleration, sPoKeysPEv2::MaxDecceleration, sPoKeysPEv2::MaxSpeed, sPoKeysPEv2::MPGjogDivider, sPoKeysPEv2::MPGjogEncoder, sPoKeysPEv2::MPGjogMultiplier, sPoKeysDevice::PEv2, PEv2_data_t::PEv2_ArmPosition, PEv2_data_t::PEv2_AxesConfig, PEv2_data_t::PEv2_AxesSwitchConfig, PoKeysHALComponent::PEv2_AxisConfigurationGet(), PEv2_data_t::PEv2_AxisEnabled, PEv2_data_t::PEv2_AxisEnabledMasked, PEv2_data_t::PEv2_AxisInternalPlanner, PEv2_data_t::PEv2_AxisInverted, PEv2_data_t::PEv2_AxisInvertedHome, PEv2_data_t::PEv2_AxisPositionMode, PEv2_data_t::PEv2_AxisSoftLimitEnabled, PEv2_data, PEv2_data_t::PEv2_digin_Home_Enabled, PEv2_data_t::PEv2_digin_Home_Filter, PEv2_data_t::PEv2_digin_Home_invert, PEv2_data_t::PEv2_digin_Home_OnLimitN, PEv2_data_t::PEv2_digin_Home_OnLimitP, PEv2_data_t::PEv2_digin_Home_Pin, PEv2_data_t::PEv2_digin_LimitN_Enabled, PEv2_data_t::PEv2_digin_LimitN_Filter, PEv2_data_t::PEv2_digin_LimitN_invert, PEv2_data_t::PEv2_digin_LimitN_Pin, PEv2_data_t::PEv2_digin_LimitP_Enabled, PEv2_data_t::PEv2_digin_LimitP_Filter, PEv2_data_t::PEv2_digin_LimitP_invert, PEv2_data_t::PEv2_digin_LimitP_Pin, PEv2_data_t::PEv2_digin_Probe_Filter, PEv2_data_t::PEv2_digin_SoftLimit_PosMax, PEv2_data_t::PEv2_digin_SoftLimit_PosMin, PEv2_data_t::PEv2_digout_AxisEnable_invert, PEv2_data_t::PEv2_digout_AxisEnable_Pin, PEv2_data_t::PEv2_HomeAlg_OnHome_ArmEncoder, PEv2_data_t::PEv2_HomeAlg_OnHome_ReducedSpeed, PEv2_data_t::PEv2_HomeAlg_OnHome_RevDirection, PEv2_data_t::PEv2_HomeAlg_OnHome_Stop, PEv2_data_t::PEv2_HomeAlg_OutHome_ArmEncoder, PEv2_data_t::PEv2_HomeAlg_OutHome_ReducedSpeed, PEv2_data_t::PEv2_HomeAlg_OutHome_RevDirection, PEv2_data_t::PEv2_HomeAlg_OutHome_Stop, PEv2_data_t::PEv2_HomeBackOffDistance, PEv2_data_t::PEv2_HomePosition, PEv2_data_t::PEv2_HomingAlgorithm, PEv2_data_t::PEv2_HomingReturnSpeed, PEv2_data_t::PEv2_HomingSpeed, PEv2_data_t::PEv2_MaxAcceleration, PEv2_data_t::PEv2_MaxDecceleration, PEv2_data_t::PEv2_MaxSpeed, PEv2_data_t::PEv2_MPGjogDivider, PEv2_data_t::PEv2_MPGjogEncoder, PEv2_data_t::PEv2_MPGjogMultiplier, PEv2_data_t::PEv2_PositionOffset, PEv2_data_t::PEv2_PositionScale, PEv2_data_t::PEv2_SoftLimitMaximum, PEv2_data_t::PEv2_SoftLimitMinimum, PEv2_data_t::PEv2_stepgen_HOME, PEv2_data_t::PEv2_stepgen_HOME_LATCH_VEL, PEv2_data_t::PEv2_stepgen_HOME_OFFSET, PEv2_data_t::PEv2_stepgen_HOME_SEARCH_VEL, PEv2_data_t::PEv2_stepgen_MAX_LIMIT, PEv2_data_t::PEv2_stepgen_MIN_LIMIT, PEv2_data_t::PEv2_stepgen_STEP_SCALE, PEv2_data_t::PEv2_stepgen_STEPGEN_MAXACCEL, PEv2_data_t::PEv2_stepgen_STEPGEN_MAXVEL, PEv2_data_t::PEv2_ZeroPosition, all_IO_data_t::Pin, one_digiIO_data_t::PinFunction, sPoKeysPEv2::PinHomeSwitch, sPoKeysPEv2::PinLimitMSwitch, sPoKeysPEv2::PinLimitPSwitch, Pins_DigitalValueSet_ignore, PK_OK, PK_PEv2_AxisConfigurationSet(), PK_PEv2Homing_OnHomeArmEncoder, PK_PEv2Homing_OnHomeReducedSpeed, PK_PEv2Homing_OnHomeReverseDirection, PK_PEv2Homing_OnHomeStop, PK_PEv2Homing_OutHomeArmEncoder, PK_PEv2Homing_OutHomeReducedSpeed, PK_PEv2Homing_OutHomeReverseDirection, PK_PEv2Homing_OutHomeStop, PK_PinCap_digitalInput, PK_PinCap_digitalOutput, PK_SaveConfiguration(), posMode, RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), Set_BitOfByte(), sleepdur, sPoKeysPEv2::SoftLimitMaximum, and sPoKeysPEv2::SoftLimitMinimum.
Referenced by PoKeysHALComponent::PKPEv2_Setup().
PEv2_ExternalOutputsSet()
int32_t PEv2_ExternalOutputsSet (sPoKeysDevice * dev)
Sets the state of external relay and open-collector outputs on the PoKeys device.
This function configures the external relay and open-collector (OC) outputs available on Pulse Engine v2capable PoKeys devices (if extended I/O is enabled).
The function first reads the current output states from the device using PK_PEv2_ExternalOutputsGet() and stores them in the corresponding HAL pin values.
Then, the desired output states are composed based on the values of HAL pins:
PEv2_digout_ExternalRelay_out[] for relay outputs
PEv2_digout_ExternalOC_out[] for OC outputs
Bitwise packing of the 8-bit outputs is done using Set_BitOfByte(), following the hardware-specific wiring pattern described in the code comment.
If the target states differ from the current values on the device, the new states are set using PK_PEv2_ExternalOutputsSet(). The operation is retried once in case of failure.
Parameters
dev Pointer to the PoKeys device structure.
Returns
PK_OK on success or the error code returned by PK_PEv2_ExternalOutputsGet() or PK_PEv2_ExternalOutputsSet().
Note
Requires PEv2_PG_extended_io to be enabled for output access.
Uses Set_BitOfByte() to construct byte values from individual output bits.
Applies delays using usleep() if compiled with ULAPI.
See also
PK_PEv2_ExternalOutputsGet
PK_PEv2_ExternalOutputsSet
Set_BitOfByte
Definition at line 1290 of file PokeysCompPulsEngine_base.c.
References dev, sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceType, external_oc_memory, external_relay_memory, sPoKeysPEv2::ExternalOCOutputs, sPoKeysPEv2::ExternalRelayOutputs, sPoKeysDevice::PEv2, PEv2_data, PEv2_data_t::PEv2_digout_ExternalOC_out, PEv2_data_t::PEv2_digout_ExternalRelay_out, PEv2_data_t::PEv2_ExternalOCOutputs, PEv2_data_t::PEv2_ExternalRelayOutputs, PEv2_data_t::PEv2_PG_extended_io, PK_DeviceID_PoKeys57CNC, PK_DeviceID_PoKeys57CNCpro4x25, PK_OK, PK_PEv2_ExternalOutputsGet(), PK_PEv2_ExternalOutputsSet(), RTAPI_MSG_ERR, RTAPI_MSG_INFO, rtapi_print_msg(), Set_BitOfByte(), and sleepdur.
PEv2_HomingStateSyncedTrigger()
int32_t PEv2_HomingStateSyncedTrigger (sPoKeysDevice * dev, int seq, pokeys_home_status_t RequiredState, pokeys_home_status_t NextState)
Triggers a synchronized homing state transition for all axes in a given homing sequence.
This function checks whether all axes assigned to a given homing sequence have reached a specific required homing state. If all are ready, it transitions them to the specified next homing state and optionally triggers PoKeys Pulse Engine homing actions (e.g., start, finalize, encoder arm, etc.).
The function supports transitions through key homing states like:
PK_Homing_axHOMINGSTART: Initializes homing for the sequence and sets the start mask.
PK_Homing_axARMENCODER: Sets the axis position to zero before the final move.
PK_Homing_axHOMINGFinalMove: Triggers a position move to the final home position.
PK_Homing_axHOMINGFinalize: Completes the homing procedure and ensures Pulse Engine state is correct.
If any axis is not ready (i.e., not in the required state), the function aborts early.
Parameters
[in] dev Pointer to the PoKeys device structure.
[in] seq The homing sequence number to process.
[in] RequiredState The required state that all joints in the sequence must currently be in.
[in] NextState The homing state to transition to for all joints in the sequence.
Returns
int32_t
0 if the transition was successfully triggered.
1 if any joint in the sequence is not in the required state or an error occurs.
Note
The function sets internal flags and masks used by the Pulse Engine API. Certain transitions involve setting configuration bits or triggering motion commands.
Definition at line 1878 of file PokeysCompPulsEngine_base.c.
References ActState_Memory, NextState_Memory, PEv2_data, PEv2_data_t::PEv2_home_sequence, PEv2_data_t::PEv2_HomingStatus, PEv2_data_t::PEv2_nrOfAxes, RequiredState_Memory, RTAPI_MSG_ERR, and rtapi_print_msg().
PEv2_PulseEngineSetup() [1/2]
int32_t PEv2_PulseEngineSetup (sPoKeysDevice * dev)
Configures and applies Pulse Engine v2 settings to the PoKeys device.
This function checks and sets multiple Pulse Engine configuration parameters based on both the current device state (dev->PEv2) and user-defined or default settings stored in PEv2_data. These include:
Number of enabled axes
Charge pump enable state
Step/dir signal swap
Extended I/O usage
Emergency switch polarity
Axis enabled mask
The function determines whether an update to the configuration is needed (doSetup), and if so, calls PK_PEv2_PulseEngineSetup() to apply it. Upon success, it persists the changes with PK_SaveConfiguration().
Additionally, the function sets some device-specific defaults for supported PoKeys device types, such as PoKeys57CNC and PoKeys57U.
Parameters
dev Pointer to the PoKeys device structure.
Return values
PK_OK on success (via PK_PEv2_PulseEngineSetup internally)
other error codes returned by PK_PEv2_PulseEngineSetup() or PK_SaveConfiguration() on failure
Note
Adds delays via usleep() when compiled in user-space (ULAPI) to ensure communication timing.
Internally modifies PEv2_data->PEv2_PulseGeneratorType using Set_BitOfByte() helper for bit flags.
See also
PK_PEv2_PulseEngineSetup
PK_SaveConfiguration
PEv2_AdditionalParametersSet
Set_BitOfByte
Definition at line 1579 of file PokeysCompPulsEngine_base.c.
References sPoKeysPEv2::AxisEnabledStatesMask, sPoKeysPEv2::ChargePumpEnabled, dev, sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceType, doSetup, sPoKeysPEv2::EmergencySwitchPolarity, sPoKeysPEv2::info, sPoKeysPEv2info::nrOfAxes, sPoKeysDevice::PEv2, PEv2_data_t::PEv2_AxisEnabledStatesMask, PEv2_data_t::PEv2_ChargePumpEnabled, PEv2_data, PEv2_data_t::PEv2_digin_Emergency_invert, PEv2_data_t::PEv2_PG_extended_io, PEv2_data_t::PEv2_PG_swap_stepdir, PEv2_data_t::PEv2_PulseEngineEnabled, PEv2_data_t::PEv2_PulseGeneratorType, PK_DeviceID_57E, PK_DeviceID_57U, PK_DeviceID_PoKeys57CNC, PK_DeviceID_PoKeys57CNCdb25, PK_DeviceID_PoKeys57CNCpro4x25, PK_OK, PK_PEv2_PulseEngineSetup(), PK_SaveConfiguration(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysPEv2::PulseGeneratorType, RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), Set_BitOfByte(), and sleepdur.
PEv2_PulseEngineSetup() [2/2]
int PEv2_PulseEngineSetup (sPoKeysDevice * dev)
Configures the PulseEngine v2 using current settings.
Referenced by PoKeysHALComponent::PKPEv2_Setup().
PEv2_Status2Get()
int32_t PEv2_Status2Get (sPoKeysDevice * dev)
Reads and updates the state of dedicated limit and home inputs from the PoKeys Pulse Engine v2.
This function queries the PoKeys device for the current status of the dedicated negative limit switches, positive limit switches, and home switches using PK_PEv2_Status2Get().
For each axis, it checks whether a dedicated pin is assigned for each type of input. If not, it uses software inversion settings and enable flags to update the appropriate HAL pins (input, inverted input, and dedicated input).
This function supports both dedicated hardware lines and virtual assignments via HAL. Bitwise decoding is done using Get_BitOfByte() per axis and input type.
Parameters
dev Pointer to the PoKeys device structure.
Returns
PK_OK on success, or error code from PK_PEv2_Status2Get() on failure.
Note
If ULAPI is defined, a usleep() delay is applied after reading the status.
See also
PK_PEv2_Status2Get
Get_BitOfByte
PEv2_data->PEv2_digin_LimitN_*
PEv2_data->PEv2_digin_LimitP_*
PEv2_data->PEv2_digin_Home_*
Definition at line 1071 of file PokeysCompPulsEngine_base.c.
References bm_DedicatedHomeInputs, bm_DedicatedLimitNInputs, bm_DedicatedLimitPInputs, bm_HomeStatus, bm_LimitStatusN, bm_LimitStatusP, sPoKeysPEv2::DedicatedHomeInputs, sPoKeysPEv2::DedicatedLimitNInputs, sPoKeysPEv2::DedicatedLimitPInputs, dev, one_digiIO_data_t::digin_in, one_digiIO_data_t::digin_in_not, Get_BitOfByte(), i, IO_data, sPoKeysDevice::PEv2, PEv2_data_t::PEv2_AxesState, PEv2_data, PEv2_data_t::PEv2_digin_Home_DedicatedInput, PEv2_data_t::PEv2_digin_Home_Enabled, PEv2_data_t::PEv2_digin_Home_in, PEv2_data_t::PEv2_digin_Home_in_not, PEv2_data_t::PEv2_digin_Home_invert, PEv2_data_t::PEv2_digin_Home_Pin, PEv2_data_t::PEv2_digin_LimitN_DedicatedInput, PEv2_data_t::PEv2_digin_LimitN_Enabled, PEv2_data_t::PEv2_digin_LimitN_in, PEv2_data_t::PEv2_digin_LimitN_in_not, PEv2_data_t::PEv2_digin_LimitN_invert, PEv2_data_t::PEv2_digin_LimitN_Pin, PEv2_data_t::PEv2_digin_LimitP_DedicatedInput, PEv2_data_t::PEv2_digin_LimitP_Enabled, PEv2_data_t::PEv2_digin_LimitP_in, PEv2_data_t::PEv2_digin_LimitP_in_not, PEv2_data_t::PEv2_digin_LimitP_invert, PEv2_data_t::PEv2_digin_LimitP_Pin, PEv2_data_t::PEv2_nrOfAxes, all_IO_data_t::Pin, PK_OK, PK_PEAxisState_axSTOPPED, PK_PEv2_Status2Get(), RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), and sleepdur.
Referenced by PoKeysHALComponent::PKPEv2_Update().
PEv2_StatusGet()
int32_t PEv2_StatusGet (sPoKeysDevice * dev)
Retrieves and processes the current status of the PoKeys Pulse Engine v2 (PEv2).
This function calls PK_PEv2_StatusGet() to read current state and configuration values from the PoKeys Pulse Engine v2 and updates the corresponding HAL pins and internal variables accordingly.
It processes:
General engine configuration (number of axes, max frequency, buffer depth, etc.)
Engine status flags (enabled, activated, charge pump, generator type)
Axis enable mask and limit override
Current engine state (running, stopped, homing, probing, etc.)
Emergency input polarity and status
Depending on the machine power state (HAL_Machine_On), the function also sets PEv2_PulseEngineStateSetup accordingly.
Special behavior:
If the state is peHOME and homing is active, Homing_active will be reset.
In case of peSTOP_EMERGENCY, emergency input pins are explicitly set.
Parameters
dev Pointer to the PoKeys device structure.
Returns
PK_OK on success or the error code from PK_PEv2_StatusGet() on failure.
Note
Updates several HAL pins and internal flags like Homing_active.
Applies sleep delay if ULAPI is defined.
See also
PK_PEv2_StatusGet
PEv2_data
ePoKeysPEState
Definition at line 896 of file PokeysCompPulsEngine_base.c.
References ApplyIniSettings, sPoKeysPEv2::AxisEnabledStatesMask, bm_ErrorStatus, bm_HomeStatus, bm_LimitStatusN, bm_LimitStatusP, bm_ProbeStatus, sPoKeysPEv2info::bufferDepth, sPoKeysPEv2::ChargePumpEnabled, dev, sPoKeysPEv2::EmergencySwitchPolarity, sPoKeysPEv2::ErrorInputStatus, HAL_Machine_On, sPoKeysPEv2::HomeStatus, Homing_active, sPoKeysPEv2::info, sPoKeysPEv2::LimitOverride, sPoKeysPEv2::LimitStatusN, sPoKeysPEv2::LimitStatusP, sPoKeysPEv2info::maxPulseFrequency, sPoKeysPEv2::MiscInputStatus, sPoKeysPEv2info::nrOfAxes, sPoKeysDevice::PEv2, PEv2_data_t::PEv2_AxisEnabledStatesMask, PEv2_data_t::PEv2_bufferDepth, PEv2_data_t::PEv2_ChargePumpEnabled, PEv2_data, PEv2_data_t::PEv2_deb_estop, PEv2_data_t::PEv2_deb_out, PEv2_data_t::PEv2_digin_Emergency_in, PEv2_data_t::PEv2_digin_Emergency_in_not, PEv2_data_t::PEv2_digin_Emergency_invert, PEv2_data_t::PEv2_LimitOverride, PEv2_data_t::PEv2_maxPulseFrequency, PEv2_data_t::PEv2_MiscInputStatus, PEv2_data_t::PEv2_nrOfAxes, PEv2_data_t::PEv2_PulseEngineActivated, PEv2_data_t::PEv2_PulseEngineEnabled, PEv2_data_t::PEv2_PulseEngineState, PEv2_data_t::PEv2_PulseEngineStateSetup, PEv2_data_t::PEv2_PulseGeneratorType, PEv2_data_t::PEv2_slotTiming, PK_OK, PK_PEState_peBUFFER, PK_PEState_peHOME, PK_PEState_peHOMING, PK_PEState_peHYBRIDPROBE_COMPLETE, PK_PEState_peHYBRIDPROBE_STOPPING, PK_PEState_peINTERNAL, PK_PEState_peJOGGING, PK_PEState_pePROBE, PK_PEState_pePROBECOMPLETE, PK_PEState_pePROBEERROR, PK_PEState_peRUNNING, PK_PEState_peSTOP_EMERGENCY, PK_PEState_peSTOP_LIMIT, PK_PEState_peSTOPPED, PK_PEState_peSTOPPING, PK_PEv2_StatusGet(), sPoKeysPEv2::ProbeStatus, sPoKeysPEv2::PulseEngineActivated, sPoKeysPEv2::PulseEngineEnabled, sPoKeysPEv2::PulseEngineState, sPoKeysPEv2::PulseGeneratorType, RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), sleepdur, and sPoKeysPEv2info::slotTiming.
Referenced by PoKeysHALComponent::PKPEv2_Update().
PKEncoder_export_params()
int PKEncoder_export_params (char * prefix, long extra_arg, int id, int njoints)
Exports HAL parameters related to encoder configuration.
This function registers additional HAL parameters for each encoder channel, such as scale factor and PoKeys-specific encoder settings like pin assignments and options. These parameters allow runtime configuration and status feedback.
For each encoder (up to njoints), the following HAL parameters are created:
encoder.N.scale (float, rw): Scale factor used to convert counts to position units
Encoders.N.encoderOptions (u32, rw): Bitmask defining encoder behavior
Encoders.N.channelApin (u32, rw): Assigned PoKeys pin for channel A
Encoders.N.channelBpin (u32, rw): Assigned PoKeys pin for channel B
Parameters
[in] prefix HAL prefix string used for naming the exported parameters
[in] extra_arg Reserved, not used
[in] id HAL component ID
[in] njoints Number of encoders (typically equal to number of joints)
Returns
0 on success, or a negative HAL error code on failure
Note
This function should be called during component initialization, after memory allocation for encoder_data has been completed.
See also
PKEncoder_export_pins()
one_encoder_data_t
Definition at line 185 of file PoKeysCompEncoders.c.
References RTAPI_MSG_DBG, and rtapi_print_msg().
PKEncoder_export_pins()
int PKEncoder_export_pins (char * prefix, long extra_arg, int id, int njoints, all_encoder_data_t * Encoder_data)
Exports HAL encoder pins for the PoKeys device.
This function creates and registers all necessary HAL pins for a specified number of encoders based on the given joint count. It assigns pointers to the internal encoder_data structure for later use during runtime updates.
The following HAL pins are exported per encoder channel:
encoder.N.count (s32, output): Current encoder count
encoder.N.position (float, output): Calculated position
encoder.N.velocity (float, output): Calculated velocity
encoder.N.reset (bit, input): Resets encoder count
encoder.N.index-enable (bit, input): Enables index pulse processing
Additionally, the following debug pin is exported:
encoder.deb.out (s32, output): Debug value for diagnostics
If Encoder_data is NULL, memory is allocated via hal_malloc.
Parameters
[in] prefix HAL prefix string used for naming the exported pins
[in] extra_arg Reserved, not used
[in] id HAL component ID
[in] njoints Number of encoders (typically equal to number of joints)
[in] Encoder_data Pointer to encoder data structure (can be NULL to auto-allocate)
Returns
0 on success, or negative HAL error code on failure
Note
This function must be called during HAL component initialization.
See also
PKENC_Update()
one_encoder_data_t
all_encoder_data_t
Definition at line 88 of file PoKeysCompEncoders.c.
References RTAPI_MSG_DBG, and rtapi_print_msg().
PKEncoder_ReadIniFile()
void PKEncoder_ReadIniFile (sPoKeysDevice * dev)
Reads encoder-related settings from the INI configuration file.
This function is intended to load encoder configuration values (e.g., scale, pin assignments, inversion flags, or other options) from an INI file section, typically used for persisting user-defined settings between sessions.
Currently, this function is a placeholder and does not perform any operation.
You may extend it to:
Load encoder scale factors
Load encoder pin mappings (channel A/B)
Load encoder mode or options
Parameters
[in,out] dev Pointer to the initialized PoKeys device structure
Reads encoder-related settings from the INI configuration file.
This function is responsible for reading user-defined encoder settings from the INI section [POKEYS] and populating the HAL parameters accordingly. It supports all encoder types available on PoKeys devices: basic encoders, fast encoders, and ultra-fast encoders.
The values are not written back to the device here, but merely loaded into the HAL parameter structures so they can later be written using PK_EncoderConfigurationSet().
The HAL parameter structure encoder_data is filled with values retrieved from the INI using keys that match the HAL parameter naming convention for consistency.
Supported parameters:
Basic encoders (encoder[#]):
scale, enable, x4_sampling, x2_sampling
keymap_dirA, macro_dirA, keymap_dirB, macro_dirB
channelApin, channelBpin
Fast encoders:
encoderFastEnable, alternativeconfig, disable_4x_sampling
FastEncodersInvert[0..2]
Ultra-fast encoder:
UltraFastEncoderOptions_INVERT_DIRECTION
UltraFastEncoderOptions_SIGNAL_MODE
UltraFastEncoderOptions_ENABLE_4X_SAMPLING
UltraFastEncoderFilter
INI section used: [POKEYS] Keys must be named according to the HAL parameter names.
Note
Only parameters explicitly listed in the INI file will be overwritten; otherwise, defaults apply.
The encoder reset-on-index option is not yet supported in the PoKeysLib API (see protocol limitations).
Example INI keys:
encoder.0.scale, encoder.0.enable, encoder.0.x4_sampling, etc.
FastEncodersInvert0, encoderFastEnable, alternativeconfig
UltraFastEncoderOptions_ENABLE_4X_SAMPLING, UltraFastEncoderFilter
Parameters
dev Pointer to the PoKeys device structure.
See also
PK_EncoderConfigurationSet
PK_EncoderConfigurationGet
all_encoder_data_t
sPoKeysDevice
ini_read_float
ini_read_int
Definition at line 954 of file PoKeysCompEncoders.c.
References dev, i, sPoKeysDevice_Info::iBasicEncoderCount, and sPoKeysDevice::info.
Referenced by pokeys_read_ini().
PKEncoder_Setup()
void PKEncoder_Setup (sPoKeysDevice * dev)
Placeholder function to perform encoder-specific setup actions.
This function is intended to configure encoder-related parameters or device settings before starting regular encoder operation. Currently, it is not implemented.
You may extend this function to:
Configure encoder sampling modes (1x, 2x, 4x)
Assign pins for channel A/B
Set scaling or filtering options
Apply configuration stored from INI
Parameters
[in,out] dev Pointer to the initialized PoKeys device structure
Placeholder function to perform encoder-specific setup actions.
This function manages encoder settings for all supported encoder types:
Basic encoders (PoKeys standard inputs)
Fast encoders (3x special dual-input configurations)
Ultra-fast encoder (1x high-speed input pair)
For each encoder type, the following logic is applied:
If ApplyIniSettings == false: configuration is read from the device and written to HAL parameters.
If ApplyIniSettings == true: configuration is read from HAL parameters and applied to the device.
Basic Encoder Fields:
encoderOptions: Enable, sampling mode (1x/2x/4x), key mapping, macro mapping
channelApin, channelBpin: Pin assignment
Fast Encoder Fields:
FastEncodersConfiguration: Configuration set (CFG1 or CFG2)
FastEncodersOptions: Inversion bits, disable 4x sampling
HAL parameters: encoderFastEnable, alternativeconfig, disable_4x_sampling, FastEncodersInvert[]
Ultra-Fast Encoder Fields:
UltraFastEncoderConfiguration: Enable
UltraFastEncoderOptions: Direction invert, signal mode, 4x sampling
UltraFastEncoderFilter: Digital filter setting
Note
Configuration is only written to the PoKeys device if differences are detected.
Final application of settings is triggered via PK_EncoderConfigurationSet() only if needed.
Warning
Index reset for the ultra-fast encoder (byte 5 of command 0x1C) is currently not supported in the PoKeysLib API (PK_EncoderConfigurationSet() and PK_EncoderConfigurationGet()). This feature cannot be enabled or read back until the API is extended accordingly.
Parameters
dev Pointer to the PoKeys device structure (must be connected and initialized).
See also
PK_EncoderConfigurationGet
PK_EncoderConfigurationSet
sPoKeysDevice
all_encoder_data_t
Definition at line 576 of file PoKeysCompEncoders.c.
References dev, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice::info, sPoKeysDevice_Info::iUltraFastEncoders, PK_EncoderConfigurationGet(), PK_OK, RTAPI_MSG_ERR, and rtapi_print_msg().
Referenced by pokeys_read_ini().
PKEncoder_Update()
void PKEncoder_Update (sPoKeysDevice * dev)
Updates encoder data from the PoKeys device and writes values to HAL pins.
This function retrieves encoder values (basic and ultra-fast) from the PoKeys device and updates the corresponding HAL pins for count and position. It also checks if the encoder should be reset (based on HAL reset pin or during initialization). If reset is requested, it sets the encoder value on the device to zero.
The following values are updated for each encoder:
encoder.#.count the raw encoder count value
encoder.#.position the scaled position based on count and scale parameter
encoder.#.velocity currently not set (placeholder)
If reset pin is high or this is the first update (initEncodersDone == false), the encoder is reset on the device using PK_EncoderValuesSet().
Debug values are written to encoder_data->encoder_deb_out to help trace progress or hangs.
Parameters
[in,out] dev Pointer to the initialized PoKeys device structure
Note
The function supports both basic and ultra-fast encoders. Fast encoders are not handled in the current implementation (commented out).
See also
PK_EncoderValuesGet()
PK_EncoderValuesSet()
one_encoder_data_t
Updates encoder data from the PoKeys device and writes values to HAL pins.
This function is called periodically to:
Retrieve encoder counts from the PoKeys device via PK_EncoderValuesGet()
Update corresponding HAL output pins:
count: raw encoder value
position: scaled encoder value (count * scale)
Perform reset operations when one of the following conditions is met:
HAL pin reset is set to TRUE
HAL pin index-enable is set to TRUE (LinuxCNC-style homing)
The component is being initialized (initEncodersDone == false)
When any reset condition is met, the corresponding encoder value is set to zero, and PK_EncoderValuesSet() is used to push the updated values to the PoKeys device.
The index-enable pin is automatically cleared after use to prevent repeated resets.
Ultra-fast encoders (if present) are also updated and reset in the same pass.
Debug status values are written to encoder_deb_out for traceability.
Parameters
dev Pointer to the PoKeys device structure.
Note
Uses usleep() if compiled with ULAPI to avoid overloading the USB bus.
All encoders are reset once at startup before the first completed update.
This logic does not currently include fast encoders unless they are mapped as basic/ultra-fast.
See also
PK_EncoderValuesGet
PK_EncoderValuesSet
one_encoder_data_t
Definition at line 422 of file PoKeysCompEncoders.c.
References dev, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice::info, RTAPI_MSG_DBG, and rtapi_print_msg().
Referenced by pokeys_update().
PKEncoder_WriteIniFile()
void PKEncoder_WriteIniFile (sPoKeysDevice * dev)
Writes encoder-related configuration to the INI file.
This function is intended to save current encoder configuration values (e.g., scale, pin assignments, inversion flags, or other options) into an INI file section. This enables restoring consistent settings across restarts or deployments.
Currently, this function is a placeholder and does not perform any operation.
You may extend it to:
Write encoder scale factors
Write encoder pin mappings (channel A/B)
Write encoder options or flags
Parameters
[in] dev Pointer to the initialized PoKeys device structure
Definition at line 1023 of file PoKeysCompEncoders.c.
Referenced by pokeys_write_ini().
PKIO_export_pins()
int PKIO_export_pins (char * prefix, long extra_arg, int id, all_IO_data_t * Io_data, sPoKeysDevice * dev)
Export HAL pins and parameters for PoKeys analog and digital I/O.
This function creates and registers HAL pins and parameters for all supported analog outputs, analog inputs, digital I/O, and counters based on the device capabilities and configuration. It binds the relevant fields in the provided all_IO_data_t structure to HAL pins using the specified prefix.
Parameters
prefix The prefix string for naming HAL pins (typically the HAL component name).
extra_arg Unused extra argument (reserved for future use or callback compatibility).
id The HAL component ID.
Io_data Pointer to the I/O data structure containing HAL pin references. If NULL, a new structure is allocated via hal_malloc.
dev Pointer to the PoKeys device structure with hardware capabilities.
Returns
Zero on success, or a negative error code if HAL pin/parameter creation fails.
Note
If Io_data is NULL, this function allocates and initializes a new I/O data block and assigns it to the static global pointer IO_data.
See also
all_IO_data_t
one_adcout_data_t
one_adcin_data_t
one_digiIO_data_t
Definition at line 81 of file PoKeysCompIO.c.
References all_IO_data_t::adcin, all_IO_data_t::adcout, all_IO_data_t::adcout_deb_outv, all_IO_data_t::adcout_pwm_period, one_digiIO_data_t::counter_value, one_adcout_data_t::deb_out, all_IO_data_t::deb_out, one_adcout_data_t::deb_setval, dev, one_digiIO_data_t::digin_in, one_digiIO_data_t::digin_in_not, one_digiIO_data_t::digin_invert, one_digiIO_data_t::DigitalValueSet_ignore, one_digiIO_data_t::digout_invert, one_digiIO_data_t::digout_out, one_adcout_data_t::enable, HAL_IN, hal_malloc(), HAL_OUT, hal_param_bit_newf(), hal_param_float_newf(), hal_param_u32_newf(), hal_pin_bit_newf(), hal_pin_float_newf(), hal_pin_u32_newf(), HAL_RO, HAL_RW, one_adcout_data_t::high_limit, sPoKeysDevice::info, IO_data, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPWMCount, one_adcout_data_t::low_limit, one_adcout_data_t::max_v, one_adcout_data_t::offset, one_adcin_data_t::offset, all_IO_data_t::Pin, one_digiIO_data_t::PinFunction, one_adcout_data_t::PinId, PK_AllPinCap_digitalCounter, PK_AllPinCap_digitalInput, PK_AllPinCap_digitalOutput, PK_CheckPinCapability(), RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), one_adcout_data_t::scale, one_adcin_data_t::scale, one_adcout_data_t::value, one_adcin_data_t::value, and one_adcin_data_t::value_raw.
PKIO_ReadIniFile()
void PKIO_ReadIniFile (sPoKeysDevice * dev)
Reads and applies I/O configuration values for the PoKeys device from the INI file.
This function loads pin functions, input/output inversion flags, analog input/output scale and offset values, voltage limits, and PWM period from the [POKEYS] section of the HAL component's INI configuration.
It covers:
Digital pin function and inversion flags:
Pin_<n>_Function
DigIn_<n>_invert
DigOut_<n>_invert
Analog output (PWM) settings:
AdcOut_<n>_offset, AdcOut_<n>_scale
AdcOut_<n>_high_limit, AdcOut_<n>_low_limit, AdcOut_<n>_max_v
AdcOut_<n>_enable
Global PWM period setting:
AdcOut_PWM_Period
Analog input scale and offset values:
AdcIn_<n>_scale, AdcIn_<n>_offset
Parameters
dev Pointer to the PoKeys device structure (sPoKeysDevice) used to determine the number of digital and analog pins.
Note
The global IO_data pointer must point to a valid all_IO_data_t structure before calling this function.
Defaults are applied if keys are missing: digital pins get 0, analog input scale defaults to 1, offset to 0.
The function assumes the corresponding HAL pins and parameters were already created.
See also
all_IO_data_t
ini_read_int()
ini_read_float()
Definition at line 931 of file PoKeysCompIO.c.
References all_IO_data_t::adcin, all_IO_data_t::adcout, all_IO_data_t::adcout_pwm_period, dev, one_digiIO_data_t::digin_invert, one_digiIO_data_t::digout_invert, one_adcout_data_t::enable, one_adcout_data_t::high_limit, i, sPoKeysDevice::info, ini_read_float(), ini_read_int(), IO_data, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPWMCount, one_adcout_data_t::low_limit, one_adcout_data_t::max_v, one_adcin_data_t::offset, all_IO_data_t::Pin, one_digiIO_data_t::PinFunction, RTAPI_MSG_ERR, rtapi_print_msg(), one_adcout_data_t::scale, and one_adcin_data_t::scale.
Referenced by pokeys_read_ini().
PKIO_Setup()
void PKIO_Setup (sPoKeysDevice * dev)
Initializes the PoKeys digital and analog I/O configuration.
This function configures the I/O pins and PWM settings of the PoKeys device based on either previously applied settings or the current device state.
It performs the following actions:
Reads the current pin configuration from the device via PK_PinConfigurationGet().
For each pin:
Sets the pin function and inversion flags (input/output polarity) based on ApplyIniSettings.
Compares and updates the pin configuration if changes are detected.
Applies updated pin configuration to the device via PK_PinConfigurationSet() if needed.
For devices with PWM outputs:
Retrieves PWM configuration using PK_PWMConfigurationGet().
Applies period, channel enablement, and value settings (scale, offset, limits).
Calls PK_PWMConfigurationSet() if PWM configuration changes were detected.
Parameters
dev Pointer to the PoKeys device structure (sPoKeysDevice).
Note
The global IO_data structure must be initialized before calling this function.
PWM scaling and voltage limits are normalized and defaulted if not set.
The last PWM period is forcibly set to 2500 if not specified.
This function is typically called during HAL component initialization.
See also
ApplyIniSettings
PK_PinConfigurationGet()
PK_PinConfigurationSet()
PK_PWMConfigurationGet()
PK_PWMConfigurationSet()
all_IO_data_t
Definition at line 709 of file PoKeysCompIO.c.
References all_IO_data_t::adcout, all_IO_data_t::adcout_deb_outv, all_IO_data_t::adcout_pwm_period, ApplyIniSettings, dev, sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceTypeID, one_digiIO_data_t::digin_invert, one_digiIO_data_t::digout_invert, one_adcout_data_t::high_limit, i, sPoKeysDevice::info, IO_data, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPWMCount, one_adcout_data_t::low_limit, one_adcout_data_t::max_v, one_adcout_data_t::offset, all_IO_data_t::Pin, sPoKeysPinData::PinFunction, one_digiIO_data_t::PinFunction, one_adcout_data_t::PinId, sPoKeysDevice::Pins, PK_DeviceID_PoKeys57CNC, PK_OK, PK_PinCap_digitalInput, PK_PinCap_digitalOutput, PK_PinCap_invertPin, PK_PinConfigurationGet(), PK_PinConfigurationSet(), PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysPWM::PWMpinIDs, RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), one_adcout_data_t::scale, and sleepdur.
Referenced by pokeys_read_ini().
PKIO_Update()
void PKIO_Update (sPoKeysDevice * dev)
Updates PoKeys I/O states from and to hardware.
This function performs periodic synchronization between the PoKeys hardware device and the corresponding LinuxCNC HAL pins. It:
Retrieves current pin configuration, digital I/O states, analog input values, digital counters, and PWM settings from the device.
Updates internal HAL structures (IO_data) with the retrieved values.
Writes analog and digital output values from HAL back to the device if enabled.
Handles logic such as scaling, clamping, and PWM duty calculation.
Optionally reconfigures PWM period or enables/disables channels when values change.
Parameters
dev Pointer to the sPoKeysDevice structure representing the connected PoKeys device.
Note
The static pointer IO_data must be initialized with valid memory prior to calling this function.
The function uses sleepdur (if compiled with ULAPI) to avoid overrunning communication.
This function combines the following device interactions:
PK_PinConfigurationGet()
PK_DigitalIOGet() / PK_DigitalIOSet()
PK_AnalogIOGet()
PK_DigitalCounterGet()
PK_PWMConfigurationGet() / PK_PWMConfigurationSet() / PK_PWMUpdate()
See also
PKIO_export_pins()
sPoKeysDevice
all_IO_data_t
Definition at line 309 of file PoKeysCompIO.c.
References all_IO_data_t::adcin, all_IO_data_t::adcout, all_IO_data_t::adcout_deb_outv, all_IO_data_t::adcout_pwm_period, sPoKeysPinData::AnalogValue, all_IO_data_t::deb_out, dev, sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceTypeID, digin_in, digin_in_not, one_digiIO_data_t::digin_in_not, sPoKeysPinData::DigitalCounterAvailable, sPoKeysPinData::DigitalCounterValue, sPoKeysPinData::DigitalValueGet, sPoKeysPinData::DigitalValueSet, one_digiIO_data_t::DigitalValueSet_ignore, one_adcout_data_t::high_limit, i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice::info, IO_data, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPWMCount, one_adcout_data_t::low_limit, one_adcout_data_t::max_v, one_adcout_data_t::offset, one_adcin_data_t::offset, all_IO_data_t::Pin, sPoKeysPinData::PinFunction, one_adcout_data_t::PinId, sPoKeysDevice::Pins, PK_AllPinCap_digitalCounter, PK_AllPinCap_digitalInput, PK_AllPinCap_digitalOutput, PK_AnalogIOGet(), PK_CheckPinCapability(), PK_DeviceID_PoKeys57CNC, PK_DigitalCounterGet(), PK_DigitalIOGet(), PK_DigitalIOSet(), PK_OK, PK_PinCap_analogInput, PK_PinCap_analogOutput, PK_PinCap_digitalCounter, PK_PinCap_digitalInput, PK_PinCap_digitalOutput, PK_PinConfigurationGet(), PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), PK_PWMUpdate(), sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysPWM::PWMpinIDs, RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), one_adcout_data_t::scale, one_adcin_data_t::scale, sleepdur, one_adcin_data_t::value, and one_adcin_data_t::value_raw.
Referenced by pokeys_update().
PKIO_WriteIniFile()
void PKIO_WriteIniFile (sPoKeysDevice * dev)
Writes the current PoKeys I/O configuration to the INI file.
This function saves all relevant I/O parameters from the current HAL state (IO_data) into the [POKEYS] section of the INI file for later reuse. This includes:
Digital pin configuration:
Pin_<n>_Function
DigIn_<n>_invert
DigOut_<n>_invert
Analog output (PWM) configuration:
AdcOut_<n>_offset, AdcOut_<n>_scale
AdcOut_<n>_high_limit, AdcOut_<n>_low_limit, AdcOut_<n>_max_v
AdcOut_<n>_enable
Global PWM period:
AdcOut_PWM_Period
Analog input scale and offset:
AdcIn_<n>_scale, AdcIn_<n>_offset
Parameters
dev Pointer to the PoKeys device structure (sPoKeysDevice), used to determine pin and channel counts.
Note
The global IO_data pointer must point to a valid all_IO_data_t structure before calling this function.
This function is the counterpart to PKIO_ReadIniFile(), and is used for persisting configuration across restarts.
See also
all_IO_data_t
PKIO_ReadIniFile()
ini_write_int()
ini_write_float()
Definition at line 1020 of file PoKeysCompIO.c.
References all_IO_data_t::adcin, all_IO_data_t::adcout, all_IO_data_t::adcout_pwm_period, dev, one_digiIO_data_t::digin_invert, one_digiIO_data_t::digout_invert, one_adcout_data_t::enable, one_adcout_data_t::high_limit, i, sPoKeysDevice::info, ini_write_float(), ini_write_int(), IO_data, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPWMCount, one_adcout_data_t::low_limit, one_adcout_data_t::max_v, one_adcout_data_t::offset, one_adcin_data_t::offset, all_IO_data_t::Pin, one_digiIO_data_t::PinFunction, one_adcout_data_t::scale, and one_adcin_data_t::scale.
Referenced by pokeys_write_ini().
PKPEv2_export_pins()
int PKPEv2_export_pins (char * prefix, long extra_arg, int comp_id, PEv2_data_t * Pev2_data, sPoKeysDevice * dev)
Export HAL pins and parameters for the PoKeys Pulse Engine v2 (PEv2).
This function creates and registers all necessary HAL pins and parameters for the PoKeys PEv2 device, based on the provided device configuration. It exposes runtime data and control paths for each axis (up to 8) and global system states. If PEv2_data is NULL, a new memory block is allocated via hal_malloc. If dev is NULL, an error is reported.
The exported pins include:
Debugging outputs (deb_out, deb_estop, axis-specific diagnostics)
Motion control feedback and command pins (joint-pos-cmd, joint-vel-cmd, etc.)
Axis configuration and position parameters (limits, offsets, scaling, etc.)
Pulse engine state, mode, and configuration
Homing, probing, and limit switch digital input states
Emergency stop and external output controls
Encoder feedback and stepgen configuration values
MPG jogging and switch logic masks
This function is typically called during component initialization to ensure all data structures are properly linked to LinuxCNC's HAL framework.
Parameters
prefix The HAL instance name prefix (e.g., "pokeys").
extra_arg Unused (reserved for future use).
comp_id The HAL component ID.
Pev2_data Pointer to PEv2 data structure. If NULL, it is allocated.
dev Pointer to the PoKeys device descriptor.
Returns
0 on success, or negative error code if HAL pin/param creation fails.
Definition at line 75 of file PokeysCompPulsEngine_base.c.
PKPEv2_Setup()
void PKPEv2_Setup (sPoKeysDevice * dev)
Applies INI-based configuration to PulseEngine and IO.
Applies configuration to the PoKeys Pulse Engine v2 during initialization.
This function sets up the Pulse Engine v2 (PEv2) based on either the INI file settings or the current runtime state of the PoKeys device. It handles the initialization and configuration of:
Pulse Engine core settings (enabled state, charge pump, generator type)
Digital I/O pin configuration (probe and emergency output)
Axis-specific settings (enabled flags, motion planner modes, limits, homing behavior)
Additional parameters such as emergency polarity and runtime-reported status
If ApplyIniSettings is true, the function applies the values from the PEv2_data structure (populated by PKPEv2_ReadIniFile) to the device using PEv2_PulseEngineSetup() and related calls. Otherwise, it reads the current device configuration back into PEv2_data using PK_PEv2_StatusGet(), PK_PEv2_Status2Get(), and PEv2_AdditionalParametersGet().
The probe pin is configured as a digital input if specified. The emergency output pin is also set as a digital output and added to the ignore list for value setting, as it is not directly configured by the PoKeys firmware.
Finally, for each axis, either PEv2_AxisConfigurationSet() or PEv2_AxisConfigurationGet() is called, depending on whether settings are to be applied or queried.
Parameters
dev Pointer to the PoKeys device structure. This must be initialized and connected.
Note
This function should be called after reading the INI file and before enabling motion control. It ensures the hardware is properly configured to match the desired logical setup.
Definition at line 1508 of file PoKeysCompPulseEngine_v2.c.
References ApplyIniSettings, sPoKeysPEv2::ChargePumpEnabled, dev, sPoKeysPEv2::EmergencySwitchPolarity, i, sPoKeysPEv2::info, IO_data, sPoKeysPEv2info::nrOfAxes, sPoKeysDevice::PEv2, PEv2_AdditionalParametersGet(), PEv2_AdditionalParametersSet(), PoKeysHALComponent::PEv2_AxisConfigurationGet(), PoKeysHALComponent::PEv2_AxisConfigurationSet(), PEv2_data_t::PEv2_AxisEnabled, PEv2_data_t::PEv2_ChargePumpEnabled, PEv2_data, PEv2_data_t::PEv2_digin_Emergency_invert, PEv2_data_t::PEv2_digin_Probe_Pin, PEv2_data_t::PEv2_digout_Emergency_Pin, PEv2_data_t::PEv2_PulseEngineEnabled, PoKeysHALComponent::PEv2_PulseEngineSetup(), PEv2_data_t::PEv2_PulseGeneratorType, all_IO_data_t::Pin, one_digiIO_data_t::PinFunction, Pins_DigitalValueSet_ignore, PK_OK, PK_PEv2_Status2Get(), PK_PEv2_StatusGet(), PK_PinCap_digitalInput, PK_PinCap_digitalOutput, sPoKeysPEv2::PulseEngineEnabled, sPoKeysPEv2::PulseGeneratorType, RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), and sleepdur.
Referenced by pokeys_read_ini().
PKPEv2_Update()
void PKPEv2_Update (sPoKeysDevice * dev, bool HAL_Machine_On)
Updates PulseEngine feedback and status.
Main update routine for the PoKeys Pulse Engine v2.
This function handles the real-time synchronization between the HAL component and the PoKeys device by reading the current state of each axis, evaluating homing, probing, motion commands, and updating control and feedback variables.
It performs the following key tasks:
Applies INI-based initialization settings if enabled
Reads status and diagnostics from the Pulse Engine
Handles homing sequences, including sub-states and transitions
Computes and sets reference positions and speeds based on command inputs
Switches between velocity and position control modes depending on motion state
Sends motion and state commands to the Pulse Engine
Updates feedback pins (e.g., position, limit switches, emergency stop)
The function evaluates each axis state in a loop and decides the proper action such as triggering homing sequences or changing the control mode. It also reacts to emergency stop states and ensures correct feedback even during homing.
Parameters
dev Pointer to the PoKeys device structure.
HAL_Machine_On Flag indicating if the HAL machine is enabled (i.e., in operation).
Evaluate the current axis state and react accordingly.
This state machine reads the current axis state from the PoKeys device and sets internal homing flags, position feedback, and diagnostics. It is part of the homing and motion logic.
Transitions depend on feedback from the Pulse Engine (PEv2) regarding the real-time state of the axis.
Parameters
i Axis index.
See also
PK_PEAxisState_ax*
Dispatch and trigger actions based on axis command.
This command-state machine interprets the current command assigned to a PoKeys axis and initiates necessary transitions, such as homing start, arming encoder, waiting for final move, or canceling homing.
PEv2_HomingStateSyncedTrigger() is used to synchronize actions across multiple axes sharing the same sequence.
Parameters
i Axis index
See also
PK_PEAxisCommand_ax*
PEv2_HomingStateSyncedTrigger
Trigger synchronized homing start based on AxisCommand change.
This logic checks whether the commanded state of an axis (PEv2_AxesCommand[i]) has changed to a homing start state (PK_PEAxisCommand_axHOMINGSTART) and if the axis is in a valid initial state (STOPPED, READY, or already in HOME).
When this transition is detected, PEv2_HomingStateSyncedTrigger() is called to initiate homing for all axes that belong to the same homing sequence (PEv2_home_sequence[i]).
This ensures that all axes in the same synchronized group start homing together.
Note
The full mask-based coordination across axes in the same sequence is currently commented out, but PEv2_HomingStateSyncedTrigger() still ensures the correct trigger propagation for synchronization.
See also
PEv2_HomingStateSyncedTrigger()
PEv2_AxesCommand
PEv2_home_sequence
Triggers homing finalization for all axes in the same synchronized homing sequence.
If an axis is currently in the axHOME state and receives the axHOMINGFinalize command, this indicates that the homing process for that axis has completed, and it's time to finalize the homing sequence for all axes that share the same PEv2_home_sequence.
The function PEv2_HomingStateSyncedTrigger() is used to propagate the axHOMINGFinalize trigger to all other axes within the same sequence, ensuring that all axes complete the homing procedure in a synchronized way.
Note
The actual condition that all axes have truly completed homing (allhomed) is commented out here, so finalization may currently rely only on the trigger signal without verifying the readiness of all involved axes.
See also
PEv2_HomingStateSyncedTrigger()
PEv2_AxesCommand
PEv2_home_sequence
PK_PEAxisState_axHOME
PK_PEAxisCommand_axHOMINGFinalize
Definition at line 260 of file PoKeysCompPulseEngine_v2.c.
References ApplyIniSettings, bm_DedicatedHomeInputs, bm_DedicatedLimitNInputs, bm_DedicatedLimitPInputs, bm_ErrorStatus, bm_HomeStatus, bm_LimitStatusN, bm_LimitStatusP, bm_ProbeStatus, dev, sPoKeysDevice::PEv2, PEv2_deb_out, PEv2_digin_Probed_in, PEv2_params_ApplyIniSettings, PEv2_Status2Get(), PEv2_StatusGet(), PK_OK, sPoKeysPEv2::ProbeStatus, RTAPI_MSG_DBG, RTAPI_MSG_ERR, and rtapi_print_msg().
Referenced by pokeys_update().
PKPoExtBus_Setup()
void PKPoExtBus_Setup (sPoKeysDevice * dev)
Initializes or configures the PoExtBus interface on the PoKeys device.
This function is intended to set up the PoExtBus (PoKeys Extension Bus), which allows communication with external modules such as I/O expanders or shift registers.
Currently, this function is a placeholder and does not perform any operation.
You may extend it to:
Configure the PoExtBus timing or mode
Initialize attached modules (e.g., HCT595 shift registers, PoExtBusOC16)
Load module-specific configuration from the INI file
Parameters
[in] dev Pointer to the initialized PoKeys device structure
Definition at line 331 of file PoKeysCompPoExtBus.c.
Referenced by pokeys_read_ini().
PKPoExtBus_Update()
void PKPoExtBus_Update (sPoKeysDevice * dev)
Updates the PoExtBus data from and to the PoKeys device.
This function synchronizes the state of the PoExtBus (PoKeys Extension Bus), which supports digital input and output via external shift registers or I/O expanders.
It performs the following steps:
Reads the current state from the PoKeys device using PK_PoExtBusGet()
Updates the PoExtBus_digin_in and PoExtBus_digin_in_not HAL pins for all bus channels
Reads desired digital output values from PoExtBus_digout_out HAL pins
Applies optional inversion logic for outputs
Compares desired vs actual state (PoExtBus_DataSet vs PoExtBus_DataGet)
If there are changes, updates the PoKeys device using PK_PoExtBusSet()
Debug values are stored in PoExtBus_deb_out for diagnostics.
Parameters
[in,out] dev Pointer to the initialized PoKeys device structure
Definition at line 230 of file PoKeysCompPoExtBus.c.
References i, RTAPI_MSG_DBG, and rtapi_print_msg().
Referenced by pokeys_update().
PKPoNet_export_pins()
int PKPoNet_export_pins (char * prefix, long extra_arg, int id, int njoints, all_PoNET_data_t * poNET_data, sPoKeysDevice * dev)
Exports HAL pins and parameters for PoNET modules and optionally kbd48CNC devices.
This function initializes and exports all relevant HAL pins and parameters for PoNET modules connected to a PoKeys device. It dynamically allocates memory for internal state (if needed) and assigns module metadata (ID, type, size, options) and I/O channels as HAL pins.
Additionally, if a kbd48CNC module is detected, it exports button and LED pins for up to 48 keys and sets up backlight brightness and control pins.
The function supports up to 16 PoNET modules with up to 16 I/O channels each.
Parameters
prefix The string prefix for the HAL pin and parameter names (e.g. "pokeys").
extra_arg Reserved extra argument, unused.
id Unique HAL component ID used for pin/parameter creation.
njoints Number of PoNET modules expected or to be scanned.
poNET_data Pointer to an existing all_PoNET_data_t structure or NULL to auto-allocate.
dev Pointer to the PoKeys device structure. Must not be NULL.
Returns
0 on success, negative value on failure (e.g. malloc failure, pin export error).
Note
This function uses PK_PoNETGetModuleSettings() to query each module slot (015) and only exports pins for detected and valid modules.
Memory allocation for PoNet_data->kbd48CNCio[] elements is done on demand.
Requires dev->info.iPoNET > 0 (i.e., PoNET support available on the device).
Definition at line 50 of file PoKeysCompPoNet.c.
References dev, sPoKeysDevice::info, sPoKeysDevice_Info::iPoNET, RTAPI_MSG_DBG, RTAPI_MSG_ERR, RTAPI_MSG_WARN, and rtapi_print_msg().
PKPoNet_Setup()
void PKPoNet_Setup (sPoKeysDevice * dev)
Initializes or configures PoNET-related settings for the given device.
This function is a placeholder for any future setup logic required for PoNET modules. Currently, it does not perform any operations.
Parameters
dev Pointer to the sPoKeysDevice structure representing the connected PoKeys device.
Note
Intended to be called during component initialization or device setup. Can be expanded to handle default configurations, pre-allocations, or hardware checks.
Definition at line 541 of file PoKeysCompPoNet.c.
Referenced by pokeys_read_ini().
PKPoNet_Update()
void PKPoNet_Update (sPoKeysDevice * dev)
Updates the state of the connected PoNET modules, specifically kbd48CNC.
This function performs a full update cycle for the kbd48CNC device connected via PoNET, including:
Fetching module settings and light (backlight) values
Reading key/button states from the device
Reflecting input state into HAL pins
Updating LED states based on HAL input
Writing updated status information back to the module
The function contains debug outputs and a deb_out pin to trace execution and states. It supports fault handling and retries for communication with the device.
Parameters
dev Pointer to the sPoKeysDevice structure, representing the connected PoKeys device.
Note
This function only performs actions if kbd48CNC_available is non-zero, indicating that a kbd48CNC PoNET module has been detected.
The kbd48CNC buttons are processed in a remapped ID order using a 4-group offset scheme, to match hardware layout with software index logic.
Warning
This function assumes that PoNet_data has already been initialized and populated by PKPoNet_export_pins(). If not, behavior is undefined.
Definition at line 296 of file PoKeysCompPoNet.c.
Referenced by pokeys_update().
Read_digin_LimitHome_Pins()
void Read_digin_LimitHome_Pins (sPoKeysDevice * dev, int i)
Reads and updates the HAL pin states for limit and home switches for a specific axis.
This function reads the current status of the limit+ (P), limit- (N), and home switches for a given axis (index i) from the bit-mapped status variables. These are typically obtained from PK_PEv2_StatusGet() or related functions.
The values are interpreted according to the pin configuration:
If a specific pin is assigned (e.g., PEv2_digin_LimitP_Pin[i] > 0), the status is read from the bitfield and written into the HAL pins.
If no pin is assigned but the feature is enabled, the values will be updated elsewhere, e.g., from dedicated inputs handled in PEv2_Status2Get().
Inversion is respected based on the .invert[] configuration for each signal type.
Parameters
dev Pointer to the PoKeys device instance.
i Index of the axis (joint) to process.
Note
This function does not call PK_PEv2_StatusGet() directly; it expects that the relevant bitfield values have already been populated.
See also
PEv2_Status2Get()
PK_PEv2_StatusGet()
Definition at line 835 of file PokeysCompPulsEngine_base.c.
References bm_ProbeStatus, dev, i, sPoKeysDevice::PEv2, PEv2_data, PEv2_data_t::PEv2_digin_Home_Enabled, PEv2_data_t::PEv2_digin_Home_Pin, PEv2_data_t::PEv2_digin_LimitN_Enabled, PEv2_data_t::PEv2_digin_LimitN_Pin, PEv2_data_t::PEv2_digin_LimitP_Enabled, PEv2_data_t::PEv2_digin_LimitP_Pin, and sPoKeysPEv2::ProbeStatus.
Set_BitOfByte()
uint8_t Set_BitOfByte (uint8_t in_Byte, int Bit_Id, bool value)
Sets or clears a specific bit in a byte.
Modifies the input byte by setting or clearing the bit at the specified position, depending on the value of the value parameter.
Parameters
in_Byte The original byte to be modified.
Bit_Id The bit position to modify (07).
value If true, the bit is set to 1; if false, the bit is cleared to 0.
Returns
The modified byte with the specified bit updated.
Note
Bit positions outside the range 07 are not checked and may cause undefined behavior.
Definition at line 817 of file PokeysCompPulsEngine_base.c.
Referenced by PoKeysHALComponent::PEv2_AxisConfigurationSet(), PEv2_ExternalOutputsSet(), and PEv2_PulseEngineSetup().
Variable Documentation
adcin
all_IO_data_t::adcin
Array of analog input channel data structures, indexed from 0 to 6.
Definition at line 204 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Update(), and PoKeysHALComponent::PKIO_WriteIniFile().
adcout
all_IO_data_t::adcout
Array of analog output channel data structures (DAC or PWM outputs), indexed from 0 to 5.
Definition at line 200 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), PoKeysHALComponent::PKIO_Update(), and PoKeysHALComponent::PKIO_WriteIniFile().
adcout_deb_outv
all_IO_data_t::adcout_deb_outv
Pointer to a HAL u32 pin that exposes the current analog output debug value (optional).
Definition at line 202 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_Setup(), and PoKeysHALComponent::PKIO_Update().
adcout_pwm_period
all_IO_data_t::adcout_pwm_period
PWM period in microseconds for analog output channels operating in PWM mode.
Definition at line 201 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), PoKeysHALComponent::PKIO_Update(), and PoKeysHALComponent::PKIO_WriteIniFile().
counter_value
one_digiIO_data_t::counter_value
Pointer to the HAL pin representing a simple counter value, incremented on rising edges.
Definition at line 165 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins().
deb_out [1/2]
one_adcout_data_t::deb_out
Pointer to the HAL pin for the debounced output value (u32).
Definition at line 88 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins().
deb_out [2/2]
all_IO_data_t::deb_out
Optional debug pointer for tracking output state of digital pins or other debugging information.
Definition at line 208 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), and PoKeysHALComponent::PKIO_Update().
deb_setval
one_adcout_data_t::deb_setval
Pointer to the HAL pin used to set the debounced output value (u32).
Definition at line 89 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins().
digin_in
one_digiIO_data_t::digin_in
Pointer to the HAL pin representing the current digital input signal (non-inverted).
Definition at line 159 of file PoKeysComp.h.
Referenced by PEv2_Status2Get(), and PoKeysHALComponent::PKIO_export_pins().
digin_in_not
one_digiIO_data_t::digin_in_not
Pointer to the HAL pin representing the inverted digital input signal.
Definition at line 160 of file PoKeysComp.h.
Referenced by PEv2_Status2Get(), PoKeysHALComponent::PKIO_export_pins(), and PoKeysHALComponent::PKIO_Update().
digin_invert
one_digiIO_data_t::digin_invert
Inversion flag for the input signal. If true, the input logic is interpreted as inverted.
Definition at line 162 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), and PoKeysHALComponent::PKIO_WriteIniFile().
DigitalValueSet_ignore
one_digiIO_data_t::DigitalValueSet_ignore
Flag to indicate that output value should not be updated in this cycle (typically set during initial configuration).
Definition at line 169 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), and PoKeysHALComponent::PKIO_Update().
digout_invert
one_digiIO_data_t::digout_invert
Inversion flag for the output signal. If true, the output logic is inverted before being sent to hardware.
Definition at line 163 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), and PoKeysHALComponent::PKIO_WriteIniFile().
digout_out
one_digiIO_data_t::digout_out
Pointer to the HAL pin representing the output signal sent to the digital output pin.
Definition at line 161 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins().
enable
one_adcout_data_t::enable
Pointer to the HAL pin enabling or disabling the output channel (bit).
Definition at line 91 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), and PoKeysHALComponent::PKIO_WriteIniFile().
high_limit
one_adcout_data_t::high_limit
Upper limit for the analog output value (float).
Definition at line 94 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), PoKeysHALComponent::PKIO_Update(), and PoKeysHALComponent::PKIO_WriteIniFile().
low_limit
one_adcout_data_t::low_limit
Lower limit for the analog output value (float).
Definition at line 95 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), PoKeysHALComponent::PKIO_Update(), and PoKeysHALComponent::PKIO_WriteIniFile().
max_v
one_adcout_data_t::max_v
Maximum physical output value supported by the hardware (float).
Definition at line 96 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), PoKeysHALComponent::PKIO_Update(), and PoKeysHALComponent::PKIO_WriteIniFile().
offset [1/2]
one_adcout_data_t::offset
Software offset added to the analog output value (float).
Definition at line 92 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_Setup(), PoKeysHALComponent::PKIO_Update(), and PoKeysHALComponent::PKIO_WriteIniFile().
offset [2/2]
one_adcin_data_t::offset
Offset applied after scaling the raw input value (float).
Definition at line 124 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Update(), and PoKeysHALComponent::PKIO_WriteIniFile().
Pin
all_IO_data_t::Pin
Array of digital input/output channel data structures, indexed from 0 to 54. Each entry corresponds to a physical I/O pin on the PoKeys device.
Definition at line 206 of file PoKeysComp.h.
Referenced by PEv2_AdditionalParametersSet(), PoKeysHALComponent::PEv2_AxisConfigurationSet(), PEv2_Status2Get(), PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), PoKeysHALComponent::PKIO_Update(), PoKeysHALComponent::PKIO_WriteIniFile(), and PoKeysHALComponent::PKPEv2_Setup().
PinFunction
one_digiIO_data_t::PinFunction
The current function assigned to the pin, e.g., digital input, output, or other capabilities (matches PoKeys API definitions).
Definition at line 167 of file PoKeysComp.h.
Referenced by PEv2_AdditionalParametersSet(), PoKeysHALComponent::PEv2_AxisConfigurationSet(), PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), PoKeysHALComponent::PKIO_WriteIniFile(), and PoKeysHALComponent::PKPEv2_Setup().
PinId
one_adcout_data_t::PinId
Identifier of the physical PoKeys pin associated with this analog output (u32).
Definition at line 97 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_Setup(), and PoKeysHALComponent::PKIO_Update().
scale [1/2]
one_adcout_data_t::scale
Scaling factor applied to the analog output value (float).
Definition at line 93 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), PoKeysHALComponent::PKIO_Update(), and PoKeysHALComponent::PKIO_WriteIniFile().
scale [2/2]
one_adcin_data_t::scale
Scaling factor applied to the raw input value (float). Useful for converting ADC values to physical units.
Definition at line 123 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Update(), and PoKeysHALComponent::PKIO_WriteIniFile().
value [1/2]
one_adcout_data_t::value
Pointer to the HAL pin holding the final analog output value (float).
Definition at line 90 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins().
value [2/2]
one_adcin_data_t::value
Pointer to the HAL pin for the processed analog input value (float), after applying scale and offset.
Definition at line 122 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), and PoKeysHALComponent::PKIO_Update().
value_raw
one_adcin_data_t::value_raw
Pointer to the HAL pin for the raw analog input value (float), as read from the PoKeys device.
Definition at line 121 of file PoKeysComp.h.
Referenced by PoKeysHALComponent::PKIO_export_pins(), and PoKeysHALComponent::PKIO_Update().