LinuxCNC PoKeysLib-Comp: Axis-level state, config, and homing integration
Axis-level state, config, and homing integration
Functions
int32_t PoKeysHALComponent::PEv2_AxisConfigurationGet (sPoKeysDevice *dev, int AxisId)
Retrieves and parses the axis configuration from the PoKeys Pulse Engine v2.
Detailed Description
Function Documentation
PEv2_AxisConfigurationGet()
int32_t PEv2_AxisConfigurationGet (sPoKeysDevice * dev, int AxisId)
Retrieves and parses the axis configuration from the PoKeys Pulse Engine v2.
This function calls PK_PEv2_AxisConfigurationGet() to read the configuration for the specified axis and updates the corresponding PEv2_data fields based on the retrieved information. It interprets the bitmask flags for axis behavior and switch configuration, and conditionally applies values from the device into PEv2_data, unless ApplyIniSettings is true (in which case values are preserved).
Additionally, this function populates numerous auxiliary parameters such as speeds, filters, soft limits, stepgen scaling, homing algorithm configuration, MPG settings, and enable outputs.
Parameters
dev Pointer to the PoKeys device structure.
AxisId The index of the axis to retrieve configuration for.
Returns
PK_OK (0) on success, or an error code if PK_PEv2_AxisConfigurationGet() fails.
Note
Only fields that are unset (i.e., zero or false) in PEv2_data will be overwritten, unless ApplyIniSettings == false, in which case full sync from device is performed.
See also
PK_PEv2_AxisConfigurationGet
Definition at line 2109 of file PokeysCompPulsEngine_base.c.
References ApplyIniSettings, sPoKeysPEv2::AxesConfig, sPoKeysPEv2::AxesSwitchConfig, sPoKeysPEv2::AxisEnableOutputPins, dev, sPoKeysPEv2::FilterHomeSwitch, sPoKeysPEv2::FilterLimitMSwitch, sPoKeysPEv2::FilterLimitPSwitch, sPoKeysPEv2::FilterProbeInput, sPoKeysPEv2::HomeBackOffDistance, sPoKeysPEv2::HomingAlgorithm, sPoKeysPEv2::HomingReturnSpeed, sPoKeysPEv2::HomingSpeed, sPoKeysPEv2::InvertAxisEnable, sPoKeysPEv2::MaxAcceleration, sPoKeysPEv2::MaxDecceleration, sPoKeysPEv2::MaxSpeed, sPoKeysPEv2::MPGjogDivider, sPoKeysPEv2::MPGjogEncoder, sPoKeysPEv2::MPGjogMultiplier, sPoKeysPEv2::param1, sPoKeysDevice::PEv2, PEv2_data_t::PEv2_AxesConfig, PEv2_data_t::PEv2_AxesSwitchConfig, PEv2_data_t::PEv2_AxisEnabled, PEv2_data_t::PEv2_AxisEnabledMasked, PEv2_data_t::PEv2_AxisInternalPlanner, PEv2_data_t::PEv2_AxisInverted, PEv2_data_t::PEv2_AxisInvertedHome, PEv2_data_t::PEv2_AxisPositionMode, PEv2_data_t::PEv2_AxisSoftLimitEnabled, PEv2_data, PEv2_data_t::PEv2_digin_Home_Enabled, PEv2_data_t::PEv2_digin_Home_Filter, PEv2_data_t::PEv2_digin_Home_invert, PEv2_data_t::PEv2_digin_Home_Offset, PEv2_data_t::PEv2_digin_Home_OnLimitN, PEv2_data_t::PEv2_digin_Home_OnLimitP, PEv2_data_t::PEv2_digin_Home_Pin, PEv2_data_t::PEv2_digin_LimitN_Enabled, PEv2_data_t::PEv2_digin_LimitN_Filter, PEv2_data_t::PEv2_digin_LimitN_invert, PEv2_data_t::PEv2_digin_LimitN_Pin, PEv2_data_t::PEv2_digin_LimitP_Enabled, PEv2_data_t::PEv2_digin_LimitP_Filter, PEv2_data_t::PEv2_digin_LimitP_invert, PEv2_data_t::PEv2_digin_LimitP_Pin, PEv2_data_t::PEv2_digin_Probe_Filter, PEv2_data_t::PEv2_digout_AxisEnable_invert, PEv2_data_t::PEv2_digout_AxisEnable_Pin, PEv2_data_t::PEv2_HomeBackOffDistance, PEv2_data_t::PEv2_HomingAlgorithm, PEv2_data_t::PEv2_HomingReturnSpeed, PEv2_data_t::PEv2_HomingSpeed, PEv2_data_t::PEv2_MaxAcceleration, PEv2_data_t::PEv2_MaxDecceleration, PEv2_data_t::PEv2_MaxSpeed, PEv2_data_t::PEv2_MPGjogDivider, PEv2_data_t::PEv2_MPGjogEncoder, PEv2_data_t::PEv2_MPGjogMultiplier, PEv2_data_t::PEv2_SoftLimitMaximum, PEv2_data_t::PEv2_SoftLimitMinimum, PEv2_data_t::PEv2_stepgen_HOME_LATCH_VEL, PEv2_data_t::PEv2_stepgen_HOME_OFFSET, PEv2_data_t::PEv2_stepgen_HOME_SEARCH_VEL, PEv2_data_t::PEv2_stepgen_STEP_SCALE, PEv2_data_t::PEv2_stepgen_STEPGEN_MAXACCEL, PEv2_data_t::PEv2_stepgen_STEPGEN_MAXVEL, sPoKeysPEv2::PinHomeSwitch, sPoKeysPEv2::PinLimitMSwitch, sPoKeysPEv2::PinLimitPSwitch, PK_AC_ENABLED, PK_AC_ENABLED_MASKED, PK_AC_INTERNAL_PLANNER, PK_AC_INVERTED, PK_AC_INVERTED_HOME, PK_AC_POSITION_MODE, PK_AC_SOFT_LIMIT_ENABLED, PK_ASO_SWITCH_COMBINED_LN_H, PK_ASO_SWITCH_COMBINED_LP_H, PK_ASO_SWITCH_HOME, PK_ASO_SWITCH_INVERT_HOME, PK_ASO_SWITCH_INVERT_LIMIT_N, PK_ASO_SWITCH_INVERT_LIMIT_P, PK_ASO_SWITCH_LIMIT_N, PK_ASO_SWITCH_LIMIT_P, PK_OK, PK_PEv2_AxisConfigurationGet(), RTAPI_MSG_DBG, RTAPI_MSG_ERR, rtapi_print_msg(), sPoKeysPEv2::SoftLimitMaximum, and sPoKeysPEv2::SoftLimitMinimum.
Referenced by PoKeysHALComponent::PEv2_AxisConfigurationSet(), and PoKeysHALComponent::PKPEv2_Setup().