LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/experimental/pokeys_async.c File Reference
pokeys_async.c File Reference
#include "rtapi.h"
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "stdio.h"
#include "rtapi_math64.h"
#include "PoKeysLibHal.h"
#include <math.h>
#include <unistd.h>
#include <stdlib.h>
Data Structures
struct __comp_state
PoKeys component state.
struct rt_motion_data_t
struct async_command_t
struct async_command_queue_t
struct device_status_cache_t
Macros
#define M_PI 3.14159265358979323846
#define TRUE (1)
#define FALSE (0)
#define true (1)
#define false (0)
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#define fperiod (period * 1e-9)
#define in(i) (*(__comp_inst->in[i]))
#define ain(i) (*(__comp_inst->ain[i]))
#define err (*__comp_inst->err)
#define devSerial (0+*__comp_inst->devSerial)
#define alive (*__comp_inst->alive)
#define FOR_ALL_INSTS() struct __comp_state *__comp_inst; for(__comp_inst = __comp_first_inst; __comp_inst; __comp_inst = __comp_inst->_next)
#define MAX_ASYNC_COMMANDS 32
Enumerations
enum async_cmd_type_t {
CMD_MOVE_PV , CMD_HOME_START , CMD_PROBE_START , CMD_EMERGENCY_STOP ,
CMD_EXTERNAL_OUTPUT_SET
}
Functions
int PK_PEv2_PulseEngineMovePVAsync (sPoKeysDevice *device)
int PK_PEv2_HomingStartAsync (sPoKeysDevice *device)
int PK_PEv2_ExternalOutputsSetAsync (sPoKeysDevice *device)
int PK_PEv2_StatusGetAsync (sPoKeysDevice *device)
int rtapi_app_main (void)
void rtapi_app_exit (void)
int __comp_parse_count (int *argc, char **argv)
int __comp_parse_names (int *argc, char **argv)
int main (int argc_, char **argv_)
int export_pev2_hal_pins (struct __comp_state *inst, char *prefix, int comp_id)
sPoKeysDevice * TryConnectToDevice (uint32_t intSerial)
Variables
struct __comp_state * __comp_first_inst =0
struct __comp_state * __comp_last_inst =0
uint32_t device_id = 0
char * names [16] = {0,}
int argc =0
char ** argv =0
sPoKeysDevice * dev =0
int i =0
Macro Definition Documentation
ain
#define ain (i) (*(__comp_inst->ain[i]))
Definition at line 362 of file pokeys_async.c.
alive
#define alive (*__comp_inst->alive)
Definition at line 368 of file pokeys_async.c.
devSerial
#define devSerial (0+*__comp_inst->devSerial)
Definition at line 366 of file pokeys_async.c.
err
#define err (*__comp_inst->err)
Definition at line 364 of file pokeys_async.c.
EXTRA_CLEANUP
#define EXTRA_CLEANUP () static void extra_cleanup(void)
Definition at line 356 of file pokeys_async.c.
EXTRA_SETUP
#define EXTRA_SETUP () static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
Definition at line 354 of file pokeys_async.c.
FALSE
#define FALSE (0)
Definition at line 148 of file pokeys_async.c.
false
#define false (0)
Definition at line 152 of file pokeys_async.c.
FOR_ALL_INSTS
#define FOR_ALL_INSTS () struct __comp_state *__comp_inst; for(__comp_inst = __comp_first_inst; __comp_inst; __comp_inst = __comp_inst->_next)
Definition at line 370 of file pokeys_async.c.
fperiod
#define fperiod (period * 1e-9)
Definition at line 358 of file pokeys_async.c.
FUNCTION
#define FUNCTION (name) static void name(struct __comp_state *__comp_inst, long period)
Definition at line 352 of file pokeys_async.c.
in
#define in (i) (*(__comp_inst->in[i]))
Definition at line 360 of file pokeys_async.c.
M_PI
#define M_PI 3.14159265358979323846
Definition at line 18 of file pokeys_async.c.
MAX_ASYNC_COMMANDS
#define MAX_ASYNC_COMMANDS 32
Definition at line 404 of file pokeys_async.c.
TRUE
#define TRUE (1)
Definition at line 146 of file pokeys_async.c.
true
#define true (1)
Definition at line 150 of file pokeys_async.c.
Enumeration Type Documentation
async_cmd_type_t
enum async_cmd_type_t
Enumerator
CMD_MOVE_PV
CMD_HOME_START
CMD_PROBE_START
CMD_EMERGENCY_STOP
CMD_EXTERNAL_OUTPUT_SET
Definition at line 387 of file pokeys_async.c.
Function Documentation
__comp_parse_count()
int __comp_parse_count (int * argc, char ** argv)
Definition at line 289 of file pokeys_async.c.
References argc, argv, and i.
Referenced by main().
__comp_parse_names()
int __comp_parse_names (int * argc, char ** argv)
Definition at line 309 of file pokeys_async.c.
References argc, argv, i, and names.
Referenced by main().
export_pev2_hal_pins()
int export_pev2_hal_pins (struct __comp_state * inst, char * prefix, int comp_id)
Definition at line 503 of file pokeys_async.c.
main()
int main (int argc_, char ** argv_)
Definition at line 334 of file pokeys_async.c.
References __comp_parse_count(), __comp_parse_names(), argc, argv, rtapi_app_exit(), rtapi_app_main(), RTAPI_MSG_ERR, rtapi_print_msg(), and user_mainloop().
PK_PEv2_ExternalOutputsSetAsync()
int PK_PEv2_ExternalOutputsSetAsync (sPoKeysDevice * device)
Definition at line 263 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsyncWithPayload(), sPoKeysPEv2::ExternalOCOutputs, sPoKeysPEv2::ExternalRelayOutputs, sPoKeysDevice::PEv2, PEV2_CMD_SET_OUTPUTS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_PEv2_HomingStartAsync()
int PK_PEv2_HomingStartAsync (sPoKeysDevice * device)
Definition at line 252 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsyncWithPayload(), sPoKeysPEv2::param2, sPoKeysDevice::PEv2, PEV2_CMD_START_HOMING, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_PEv2_PulseEngineMovePVAsync()
int PK_PEv2_PulseEngineMovePVAsync (sPoKeysDevice * device)
Definition at line 222 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsyncWithPayload(), i, sPoKeysPEv2::param2, sPoKeysDevice::PEv2, PEV2_CMD_MOVE_PV, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ReferencePositionSpeed, sPoKeysPEv2::ReferenceVelocityPV, and SendRequestAsync().
PK_PEv2_StatusGetAsync()
int PK_PEv2_StatusGetAsync (sPoKeysDevice * device)
Definition at line 107 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsync(), PEV2_CMD_GET_STATUS, PK_CMD_PULSE_ENGINE_V2, and PK_ERR_NOT_CONNECTED.
Referenced by PK_EmergencyStopAllAsync().
rtapi_app_exit()
void rtapi_app_exit (void)
Definition at line 283 of file pokeys_async.c.
References hal_exit().
Referenced by main().
rtapi_app_main()
int rtapi_app_main (void)
Definition at line 221 of file pokeys_async.c.
References i.
Referenced by main().
TryConnectToDevice()
sPoKeysDevice * TryConnectToDevice (uint32_t intSerial)
Definition at line 697 of file pokeys_async.c.
References RTAPI_MSG_DBG, and rtapi_print_msg().
Variable Documentation
__comp_first_inst
struct __comp_state* __comp_first_inst =0
Definition at line 139 of file pokeys_async.c.
__comp_last_inst
struct __comp_state * __comp_last_inst =0
Definition at line 139 of file pokeys_async.c.
argc
int argc =0
Definition at line 333 of file pokeys_async.c.
Referenced by __comp_parse_count(), __comp_parse_names(), and main().
argv
char** argv =0
Definition at line 333 of file pokeys_async.c.
Referenced by __comp_parse_count(), __comp_parse_names(), and main().
dev
sPoKeysDevice* dev =0
Definition at line 689 of file pokeys_async.c.
device_id
uint32_t device_id = 0
Definition at line 141 of file pokeys_async.c.
Referenced by get_pokeys_ini_path().
i
int i =0
Definition at line 690 of file pokeys_async.c.
Referenced by __comp_parse_count(), __comp_parse_names(), and rtapi_app_main().
names
char* names[16] = {0,}
Definition at line 219 of file pokeys_async.c.
Referenced by __comp_parse_names().