LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeyslib/PoKeysLibPoIL.c File Reference
PoKeysLibPoIL.c File Reference
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
Functions
void PK_ParsePoILStateResponse (sPoKeysDevice *device)
int32_t PK_PoILGetState (sPoKeysDevice *device)
int32_t PK_PoILSetCoreState (sPoKeysDevice *device, uint16_t state)
int32_t PK_PoILSetMasterEnable (sPoKeysDevice *device, uint8_t masterEnable)
int32_t PK_PoILResetCore (sPoKeysDevice *device)
int32_t PK_PoILSetDebugMode (sPoKeysDevice *device, uint8_t debugMode, uint16_t breakpoint)
int32_t PK_PoILReadMemory (sPoKeysDevice *device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t *dest)
int32_t PK_PoILWriteMemory (sPoKeysDevice *device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t *src)
int32_t PK_PoILReadSharedSlot (sPoKeysDevice *device, uint16_t firstSlotID, uint16_t slotsNum, int *dest)
int32_t PK_PoILWriteSharedSlot (sPoKeysDevice *device, uint16_t firstSlotID, uint16_t slotsNum, int32_t *src)
int32_t PK_PoILEraseMemory (sPoKeysDevice *device, uint8_t memoryType)
int32_t PK_PoILChunkReadMemory (sPoKeysDevice *device, uint8_t *dest)
int32_t PK_PoILChunkReadMemoryInternalAddress (sPoKeysDevice *device, uint8_t *dest)
int32_t PK_PoILTaskStatus (sPoKeysDevice *device)
Function Documentation
PK_ParsePoILStateResponse()
void PK_ParsePoILStateResponse (sPoKeysDevice * device)
Definition at line 24 of file PoKeysLibPoIL.c.
References sPoILinfo::CodeMemorySize, sPoILStatus::CoreDebugBreakpoint, sPoILStatus::CoreDebugMode, sPoILStatus::CoreState, sPoILStatus::currentTask, sPoILinfo::DataMemorySize, sPoILStatus::dataStack, sPoILStatus::ExceptionDescription, sPoILStatus::ExceptionLocation, sPoILStatus::ExceptionPC, sPoILStatus::functionStack, sPoILStatus::info, sPoILStatus::MasterEnable, sPoILStatus::PC, sPoKeysDevice::PoIL, sPoKeysDevice::response, sPoILStack::stackPtr, sPoILStatus::STATUS, sPoILStatus::taskCount, sPoILinfo::Version, and sPoILStatus::W.
Referenced by PK_PoILGetState(), PK_PoILResetCore(), PK_PoILSetCoreState(), PK_PoILSetDebugMode(), and PK_PoILSetMasterEnable().
PK_PoILChunkReadMemory()
int32_t PK_PoILChunkReadMemory (sPoKeysDevice * device, uint8_t * dest)
Read preconfigured memory monitor chunks.
Definition at line 263 of file PoKeysLibPoIL.c.
PK_PoILChunkReadMemoryInternalAddress()
int32_t PK_PoILChunkReadMemoryInternalAddress (sPoKeysDevice * device, uint8_t * dest)
Read monitor chunks using internal addresses.
Definition at line 288 of file PoKeysLibPoIL.c.
PK_PoILEraseMemory()
int32_t PK_PoILEraseMemory (sPoKeysDevice * device, uint8_t memoryType)
Erase the selected interpreter memory.
Definition at line 253 of file PoKeysLibPoIL.c.
PK_PoILGetState()
int32_t PK_PoILGetState (sPoKeysDevice * device)
Retrieve PoIL interpreter state from the device.
Sends a PK_CMD_POIL_OPERATIONS request with subcommand 0 and updates the ::sPoIL structure of device with the returned data.
Definition at line 55 of file PoKeysLibPoIL.c.
PK_PoILReadMemory()
int32_t PK_PoILReadMemory (sPoKeysDevice * device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t * dest)
Read interpreter memory.
Reads size bytes from memory type memoryType starting at address into dest.
Definition at line 118 of file PoKeysLibPoIL.c.
PK_PoILReadSharedSlot()
int32_t PK_PoILReadSharedSlot (sPoKeysDevice * device, uint16_t firstSlotID, uint16_t slotsNum, int32_t * dest)
Read interpreter shared variable slots.
Definition at line 194 of file PoKeysLibPoIL.c.
PK_PoILResetCore()
int32_t PK_PoILResetCore (sPoKeysDevice * device)
Reset the interpreter core.
Definition at line 94 of file PoKeysLibPoIL.c.
PK_PoILSetCoreState()
int32_t PK_PoILSetCoreState (sPoKeysDevice * device, uint16_t state)
Change the interpreter core state.
The state parameter selects the desired run state of the interpreter.
Definition at line 70 of file PoKeysLibPoIL.c.
PK_PoILSetDebugMode()
int32_t PK_PoILSetDebugMode (sPoKeysDevice * device, uint8_t debugMode, uint16_t breakpoint)
Configure debug mode and optional breakpoint.
Definition at line 106 of file PoKeysLibPoIL.c.
PK_PoILSetMasterEnable()
int32_t PK_PoILSetMasterEnable (sPoKeysDevice * device, uint8_t masterEnable)
Enable or disable interpreter execution.
When masterEnable is zero the interpreter is halted; any other value resumes normal execution.
Definition at line 82 of file PoKeysLibPoIL.c.
PK_PoILTaskStatus()
int32_t PK_PoILTaskStatus (sPoKeysDevice * device)
Retrieve status information for all interpreter tasks.
Definition at line 311 of file PoKeysLibPoIL.c.
PK_PoILWriteMemory()
int32_t PK_PoILWriteMemory (sPoKeysDevice * device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t * src)
Write interpreter memory.
Writes size bytes to memory type memoryType starting at address from src.
Definition at line 147 of file PoKeysLibPoIL.c.
Referenced by PK_PoILWriteMemory().
PK_PoILWriteSharedSlot()
int32_t PK_PoILWriteSharedSlot (sPoKeysDevice * device, uint16_t firstSlotID, uint16_t slotsNum, int32_t * src)
Write interpreter shared variable slots.
Definition at line 223 of file PoKeysLibPoIL.c.