LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibPulseEngine_v2.c File Reference
PoKeysLibPulseEngine_v2.c File Reference
Pulse engine v2 control functions (command 0x85).
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
Functions
void PK_PEv2_DecodeStatus (sPoKeysDevice *device)
int32_t PK_PEv2_StatusGet (sPoKeysDevice *device)
Retrieve pulse engine status.
int32_t PK_PEv2_Status2Get (sPoKeysDevice *device)
Obtain extended status information.
int32_t PK_PEv2_PulseEngineSetup (sPoKeysDevice *device)
Configure the pulse engine parameters.
int32_t PK_PEv2_AdditionalParametersGet (sPoKeysDevice *device)
Read miscellaneous pulse engine parameters.
int32_t PK_PEv2_AdditionalParametersSet (sPoKeysDevice *device)
Configure miscellaneous pulse engine options.
int32_t PK_PEv2_AxisConfigurationGet (sPoKeysDevice *device)
Retrieve configuration for one axis.
int32_t PK_PEv2_AxisConfigurationSet (sPoKeysDevice *device)
Send configuration data for one axis.
int32_t PK_PEv2_PositionSet (sPoKeysDevice *device)
Set current axis positions.
int32_t PK_PEv2_PulseEngineStateSet (sPoKeysDevice *device)
Change the operating state of the pulse engine.
int32_t PK_PEv2_PulseEngineMove (sPoKeysDevice *device)
Execute a move using reference positions or speeds.
int32_t PK_PEv2_PulseEngineMovePV (sPoKeysDevice *device)
Perform a move in position/velocity mode.
int32_t PK_PEv2_ExternalOutputsGet (sPoKeysDevice *device)
Read the state of external outputs.
int32_t PK_PEv2_ExternalOutputsSet (sPoKeysDevice *device)
Update relay and open-collector outputs.
int32_t PK_PEv2_BufferFill (sPoKeysDevice *device)
Send a portion of the motion buffer (8-bit variant).
int32_t PK_PEv2_BufferFill_16 (sPoKeysDevice *device)
Send 16-bit motion buffer entries.
int32_t PK_PEv2_BufferFillLarge (sPoKeysDevice *device)
Transfer a large block of 8-bit motion data.
int32_t PK_PEv2_BufferFillLarge_16 (sPoKeysDevice *device)
Large transfer of 16-bit motion data.
int32_t PK_PEv2_BufferClear (sPoKeysDevice *device)
Clear the motion buffer in the device.
int32_t PK_PEv2_PulseEngineReboot (sPoKeysDevice *device)
Reboot the pulse engine firmware.
int32_t PK_PEv2_HomingStart (sPoKeysDevice *device)
Begin the homing sequence.
int32_t PK_PEv2_HomingFinish (sPoKeysDevice *device)
Finish the homing procedure.
int32_t PK_PEv2_ProbingStart (sPoKeysDevice *device)
Start a probing move.
int32_t PK_PEv2_ProbingHybridStart (sPoKeysDevice *device)
Start probing with an external controller.
int32_t PK_PEv2_ProbingFinish (sPoKeysDevice *device)
Complete the probing cycle and read the result.
int32_t PK_PEv2_ProbingFinishSimple (sPoKeysDevice *device)
Finish probing without changing engine state.
int32_t PK_PEv2_ThreadingPrepareForTrigger (sPoKeysDevice *device)
Prepare the spindle threading trigger.
int32_t PK_PEv2_ThreadingForceTriggerReady (sPoKeysDevice *device)
Force trigger ready state.
int32_t PK_PEv2_ThreadingTrigger (sPoKeysDevice *device)
Arm the threading trigger.
int32_t PK_PEv2_ThreadingRelease (sPoKeysDevice *device)
Release the threading trigger.
int32_t PK_PEv2_ThreadingCancel (sPoKeysDevice *device)
Cancel a prepared threading operation.
int32_t PK_PEv2_ThreadingStatusGet (sPoKeysDevice *device)
Query the status of a threading operation.
int32_t PK_PEv2_ThreadingSetup (sPoKeysDevice *device, uint8_t sensorMode, uint16_t ticksPerRevolution, uint16_t tagetSpindleRPM, uint16_t filterGainSpeed, uint16_t filterGainPosition)
Configure spindle threading parameters.
int32_t PK_PEv2_BacklashCompensationSettings_Get (sPoKeysDevice *device)
Retrieve backlash compensation parameters.
int32_t PK_PEv2_BacklashCompensationSettings_Set (sPoKeysDevice *device)
Write backlash compensation parameters.
int32_t PK_PEv2_SyncedPWMSetup (sPoKeysDevice *device, uint8_t enabled, uint8_t srcAxis, uint8_t dstPWMChannel)
Configure synchronized PWM output.
int32_t PK_PEv2_SyncOutputsSetup (sPoKeysDevice *device)
Configure synchronized digital outputs.
int32_t PK_PoStep_ConfigurationGet (sPoKeysDevice *device)
Get configuration for external PoStep drivers.
int32_t PK_PoStep_ConfigurationSet (sPoKeysDevice *device)
Configure external PoStep drivers.
int32_t PK_PoStep_StatusGet (sPoKeysDevice *device)
Read status information from PoStep drivers.
int32_t PK_PoStep_DriverConfigurationGet (sPoKeysDevice *device)
Read PoStep driver current and mode settings.
int32_t PK_PoStep_DriverConfigurationSet (sPoKeysDevice *device)
Write PoStep driver current and mode parameters.
int32_t PK_PEv2_InternalDriversConfigurationGet (sPoKeysDevice *device)
Read configuration of internal motor drivers.
int32_t PK_PEv2_InternalDriversConfigurationSet (sPoKeysDevice *device)
Set configuration of internal motor drivers.
Detailed Description
Pulse engine v2 control functions (command 0x85).
Provides motion control, homing and threading operations via the PK_CMD_PULSE_ENGINE_V2 command set.
Definition in file PoKeysLibPulseEngine_v2.c.
Function Documentation
PK_PEv2_AdditionalParametersGet()
int32_t PK_PEv2_AdditionalParametersGet (sPoKeysDevice * device)
Read miscellaneous pulse engine parameters.
Executes PEV2_CMD_CONFIGURE_MISC (0x06) with param3=1. The emergency input pin is returned in byte 8 of the response and stored in PEv2.EmergencyInputPin.
Parameters
device Target device.
Returns
PK_OK on success or communication error code.
Definition at line 184 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::EmergencyInputPin, sPoKeysDevice::PEv2, PEV2_CMD_CONFIGURE_MISC, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by PEv2_AdditionalParametersGet(), and PEv2_AdditionalParametersSet().
PK_PEv2_AdditionalParametersSet()
int32_t PK_PEv2_AdditionalParametersSet (sPoKeysDevice * device)
Configure miscellaneous pulse engine options.
Uses command PEV2_CMD_CONFIGURE_MISC (0x06) with param1=1. Byte 8 of the request carries the emergency input pin number.
Parameters
device Target device.
Returns
PK_OK on success, otherwise error code.
Definition at line 206 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::EmergencyInputPin, sPoKeysDevice::PEv2, PEV2_CMD_CONFIGURE_MISC, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
Referenced by PEv2_AdditionalParametersSet().
PK_PEv2_AxisConfigurationGet()
int32_t PK_PEv2_AxisConfigurationGet (sPoKeysDevice * device)
Retrieve configuration for one axis.
Issues PEV2_CMD_GET_AXIS_CONFIGURATION (0x10). param1 selects the axis and the response returns a 44 byte block describing limits, speeds and filter options which is copied into the PEv2 structure.
Parameters
device PoKeys device instance (uses PEv2.param1).
Returns
PK_OK on success or error code on failure.
Definition at line 230 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxesConfig, sPoKeysPEv2::AxesSwitchConfig, sPoKeysPEv2::AxisEnableOutputPins, sPoKeysPEv2::AxisSignalOptions, CreateRequest(), sPoKeysPEv2::FilterHomeSwitch, sPoKeysPEv2::FilterLimitMSwitch, sPoKeysPEv2::FilterLimitPSwitch, sPoKeysPEv2::FilterProbeInput, sPoKeysPEv2::HomeBackOffDistance, sPoKeysPEv2::HomingAlgorithm, sPoKeysPEv2::HomingReturnSpeed, sPoKeysPEv2::HomingSpeed, sPoKeysPEv2::InvertAxisEnable, sPoKeysPEv2::MaxAcceleration, sPoKeysPEv2::MaxDecceleration, sPoKeysPEv2::MaxSpeed, sPoKeysPEv2::MPGjogDivider, sPoKeysPEv2::MPGjogEncoder, sPoKeysPEv2::MPGjogMultiplier, sPoKeysPEv2::param1, sPoKeysDevice::PEv2, PEV2_CMD_GET_AXIS_CONFIGURATION, sPoKeysPEv2::PinHomeSwitch, sPoKeysPEv2::PinLimitMSwitch, sPoKeysPEv2::PinLimitPSwitch, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysPEv2::SoftLimitMaximum, and sPoKeysPEv2::SoftLimitMinimum.
Referenced by PoKeysHALComponent::PEv2_AxisConfigurationGet().
PK_PEv2_AxisConfigurationSet()
int32_t PK_PEv2_AxisConfigurationSet (sPoKeysDevice * device)
Send configuration data for one axis.
Command PEV2_CMD_SET_AXIS_CONFIGURATION (0x11) writes the same structure returned by PK_PEv2_AxisConfigurationGet. param1 selects the axis and bytes 8 onward contain the configuration fields such as limits and motion parameters.
Parameters
device PoKeys device instance.
Returns
PK_OK on success or error code on failure.
Definition at line 294 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxesConfig, sPoKeysPEv2::AxesSwitchConfig, sPoKeysPEv2::AxisEnableOutputPins, sPoKeysPEv2::AxisSignalOptions, CreateRequest(), sPoKeysPEv2::FilterHomeSwitch, sPoKeysPEv2::FilterLimitMSwitch, sPoKeysPEv2::FilterLimitPSwitch, sPoKeysPEv2::FilterProbeInput, sPoKeysPEv2::HomeBackOffDistance, sPoKeysPEv2::HomingAlgorithm, sPoKeysPEv2::HomingReturnSpeed, sPoKeysPEv2::HomingSpeed, sPoKeysPEv2::InvertAxisEnable, sPoKeysPEv2::MaxAcceleration, sPoKeysPEv2::MaxDecceleration, sPoKeysPEv2::MaxSpeed, sPoKeysPEv2::MPGjogDivider, sPoKeysPEv2::MPGjogEncoder, sPoKeysPEv2::MPGjogMultiplier, sPoKeysPEv2::param1, sPoKeysDevice::PEv2, PEV2_CMD_SET_AXIS_CONFIGURATION, sPoKeysPEv2::PinHomeSwitch, sPoKeysPEv2::PinLimitMSwitch, sPoKeysPEv2::PinLimitPSwitch, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, sPoKeysDevice::request, SendRequest(), sPoKeysPEv2::SoftLimitMaximum, and sPoKeysPEv2::SoftLimitMinimum.
Referenced by PoKeysHALComponent::PEv2_AxisConfigurationSet().
PK_PEv2_BacklashCompensationSettings_Get()
int32_t PK_PEv2_BacklashCompensationSettings_Get (sPoKeysDevice * device)
Retrieve backlash compensation parameters.
Sends PEV2_CMD_GET_BACKLASH_SETTINGS (0x40) and parses the backlash width, acceleration and register values for each axis from the response bytes.
Parameters
device Target device.
Returns
PK_OK on success or communication error.
Definition at line 1055 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::BacklashAcceleration, sPoKeysPEv2::BacklashCompensationEnabled, sPoKeysPEv2::BacklashCompensationMaxSpeed, sPoKeysPEv2::BacklashRegister, sPoKeysPEv2::BacklashWidth, CreateRequest(), i, sPoKeysDevice::PEv2, PEV2_CMD_GET_BACKLASH_SETTINGS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_BacklashCompensationSettings_Set()
int32_t PK_PEv2_BacklashCompensationSettings_Set (sPoKeysDevice * device)
Write backlash compensation parameters.
Command PEV2_CMD_SET_BACKLASH_SETTINGS (0x41) sends the same structure as returned by the getter to configure backlash for each axis.
Parameters
device Target device with values stored in the PEv2 structure.
Returns
PK_OK on success or error code.
Definition at line 1089 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::BacklashAcceleration, sPoKeysPEv2::BacklashCompensationEnabled, sPoKeysPEv2::BacklashCompensationMaxSpeed, sPoKeysPEv2::BacklashWidth, CreateRequest(), i, sPoKeysDevice::PEv2, PEV2_CMD_SET_BACKLASH_SETTINGS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_BufferClear()
int32_t PK_PEv2_BufferClear (sPoKeysDevice * device)
Clear the motion buffer in the device.
Command PEV2_CMD_CLEAR_BUFFER (0xF0) resets the internal motion queue.
Parameters
device Target device.
Returns
Result of SendRequest.
Definition at line 650 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PEV2_CMD_CLEAR_BUFFER, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_BufferFill()
int32_t PK_PEv2_BufferFill (sPoKeysDevice * device)
Send a portion of the motion buffer (8-bit variant).
Uses command PEV2_CMD_FILL_BUFFER_8BIT (0xFF). param1 holds the number of entries to copy and param2 carries the enable mask. Up to 56 bytes of motion data are placed in bytes 8-63. The response returns the number of accepted entries in byte 2 and refreshes engine status via PK_PEv2_DecodeStatus.
Parameters
device PoKeys device containing the new buffer.
Returns
PK_OK when successful or a communication error.
Definition at line 527 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PEV2_CMD_FILL_BUFFER_8BIT, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_BufferFill_16()
int32_t PK_PEv2_BufferFill_16 (sPoKeysDevice * device)
Send 16-bit motion buffer entries.
Identical to PK_PEv2_BufferFill but uses the 16-bit buffer command ID 0xFE. Payload layout and response are the same as in the 8-bit version.
Parameters
device PoKeys device containing the new data.
Returns
PK_OK on success or a transfer error.
Definition at line 558 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_BufferFillLarge()
int32_t PK_PEv2_BufferFillLarge (sPoKeysDevice * device)
Transfer a large block of 8-bit motion data.
Uses the multipart packet command PK_CMD_MULTIPART_PACKET with subcommand 0xFF. param2 specifies entry count and param3 the axis enable mask. The payload contains 448 bytes of buffer data stored in multiPartData.
Parameters
device Target device.
Returns
PK_OK on success or error code from transfer.
Definition at line 590 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysDevice::multiPartData, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest_multiPart().
PK_PEv2_BufferFillLarge_16()
int32_t PK_PEv2_BufferFillLarge_16 (sPoKeysDevice * device)
Large transfer of 16-bit motion data.
Same as PK_PEv2_BufferFillLarge but using subcommand 0xFE for 16-bit entries.
Parameters
device Target device.
Returns
PK_OK on success or communication error.
Definition at line 620 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysDevice::multiPartData, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest_multiPart().
PK_PEv2_DecodeStatus()
void PK_PEv2_DecodeStatus (sPoKeysDevice * device)
Definition at line 33 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxesState, sPoKeysPEv2::AxisEnabledStatesMask, sPoKeysPEv2info::bufferDepth, sPoKeysPEv2::ChargePumpEnabled, sPoKeysPEv2::CurrentPosition, sPoKeysPEv2::EmergencySwitchPolarity, sPoKeysPEv2::ErrorInputStatus, sPoKeysPEv2::HomeStatus, i, sPoKeysPEv2::info, sPoKeysPEv2::LimitOverride, sPoKeysPEv2::LimitStatusN, sPoKeysPEv2::LimitStatusP, sPoKeysPEv2info::maxPulseFrequency, sPoKeysPEv2::MiscInputStatus, sPoKeysPEv2info::nrOfAxes, sPoKeysDevice::PEv2, sPoKeysPEv2::PulseEngineActivated, sPoKeysPEv2::PulseEngineEnabled, sPoKeysPEv2::PulseEngineState, sPoKeysPEv2::PulseGeneratorType, sPoKeysDevice::response, sPoKeysPEv2info::slotTiming, and sPoKeysPEv2::SoftLimitStatus.
PK_PEv2_ExternalOutputsGet()
int32_t PK_PEv2_ExternalOutputsGet (sPoKeysDevice * device)
Read the state of external outputs.
Using PEV2_CMD_SET_OUTPUTS (0x04) with param3=1 the device returns relay and open-collector output states in bytes 3 and 4 of the response which are stored in the PEv2 structure.
Parameters
device Target device.
Returns
PK_OK when data is read successfully, otherwise error code from SendRequest.
Definition at line 481 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::ExternalOCOutputs, sPoKeysPEv2::ExternalRelayOutputs, sPoKeysDevice::PEv2, PEV2_CMD_SET_OUTPUTS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by PEv2_ExternalOutputsSet().
PK_PEv2_ExternalOutputsSet()
int32_t PK_PEv2_ExternalOutputsSet (sPoKeysDevice * device)
Update relay and open-collector outputs.
Command PEV2_CMD_SET_OUTPUTS (0x04) uses param1 for relay outputs and param2 for open-collector outputs.
Parameters
device Device with desired output states stored in the PEv2 structure.
Returns
Result of SendRequest.
Definition at line 505 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::ExternalOCOutputs, sPoKeysPEv2::ExternalRelayOutputs, sPoKeysDevice::PEv2, PEV2_CMD_SET_OUTPUTS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
Referenced by PEv2_ExternalOutputsSet().
PK_PEv2_HomingFinish()
int32_t PK_PEv2_HomingFinish (sPoKeysDevice * device)
Finish the homing procedure.
Sends PEV2_CMD_FINISH_HOMING (0x22). param1 sets the new engine state after homing and param2 should be 1 as required by the protocol.
Parameters
device PoKeys device instance.
Returns
Result of SendRequest.
Definition at line 717 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PEV2_CMD_FINISH_HOMING, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineStateSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_HomingStart()
int32_t PK_PEv2_HomingStart (sPoKeysDevice * device)
Begin the homing sequence.
Command PEV2_CMD_START_HOMING (0x21). param1 holds the axis mask and bytes 8-39 carry home offset values for each axis.
Parameters
device Target device with offsets stored in PEv2.HomeOffsets.
Returns
Result of SendRequest.
Definition at line 688 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::HomeOffsets, sPoKeysPEv2::HomingStartMaskSetup, i, sPoKeysDevice::PEv2, PEV2_CMD_START_HOMING, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_InternalDriversConfigurationGet()
int32_t PK_PEv2_InternalDriversConfigurationGet (sPoKeysDevice * device)
Read configuration of internal motor drivers.
Command PEV2_CMD_GET_INTERNAL_DRIVERS (0x18) returns step mode and current settings for four integrated drivers.
Parameters
device Target device.
Returns
PK_OK on success or error code.
Definition at line 1395 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::InternalDriverCurrentConfig, sPoKeysPEv2::InternalDriverStepConfig, sPoKeysDevice::PEv2, PEV2_CMD_GET_INTERNAL_DRIVERS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_InternalDriversConfigurationSet()
int32_t PK_PEv2_InternalDriversConfigurationSet (sPoKeysDevice * device)
Set configuration of internal motor drivers.
Uses PEV2_CMD_SET_INTERNAL_DRIVERS (0x19) with step and current settings for the four integrated drivers placed in the request payload.
Parameters
device Device providing new settings via PEv2 fields.
Returns
Result of SendRequest.
Definition at line 1424 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::InternalDriverCurrentConfig, sPoKeysPEv2::InternalDriverStepConfig, sPoKeysDevice::PEv2, PEV2_CMD_SET_INTERNAL_DRIVERS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PositionSet()
int32_t PK_PEv2_PositionSet (sPoKeysDevice * device)
Set current axis positions.
Command PEV2_CMD_SET_AXIS_POSITION (0x03) updates the internal position registers. param2 is a bit mask selecting which axes are affected and bytes 8-39 carry the new 32-bit positions for all axes.
Parameters
device Device containing the new positions in PEv2.PositionSetup.
Returns
PK_OK on success or error code on failure.
Definition at line 359 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::param2, sPoKeysDevice::PEv2, PEV2_CMD_SET_AXIS_POSITION, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, sPoKeysPEv2::PositionSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ProbingFinish()
int32_t PK_PEv2_ProbingFinish (sPoKeysDevice * device)
Complete the probing cycle and read the result.
Command PEV2_CMD_FINISH_PROBING (0x24) returns the probe position in bytes 8-39 and status bits in byte 40. The engine state is also reset to STOPPED.
Parameters
device Device receiving the probe result.
Returns
PK_OK when the response is valid or an error code.
Definition at line 801 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysDevice::PEv2, PEV2_CMD_FINISH_PROBING, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysPEv2::ProbePosition, sPoKeysPEv2::ProbeStatus, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_ProbingFinishSimple()
int32_t PK_PEv2_ProbingFinishSimple (sPoKeysDevice * device)
Finish probing without changing engine state.
Uses PEV2_CMD_FINISH_PROBING (0x24) with param1=1. The probe result is returned like in PK_PEv2_ProbingFinish but the engine state is not reset.
Parameters
device Device receiving the result.
Returns
PK_OK if successful or error code.
Definition at line 835 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysDevice::PEv2, PEV2_CMD_FINISH_PROBING, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysPEv2::ProbePosition, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_ProbingHybridStart()
int32_t PK_PEv2_ProbingHybridStart (sPoKeysDevice * device)
Start probing with an external controller.
Uses PEV2_CMD_START_PROBING with param2=1 for the hybrid probing mode. Only the probe input number and polarity are sent in bytes 44-45.
Parameters
device Device configured for probing.
Returns
Result of SendRequest.
Definition at line 777 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PEV2_CMD_START_PROBING, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ProbeInput, sPoKeysPEv2::ProbeInputPolarity, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ProbingStart()
int32_t PK_PEv2_ProbingStart (sPoKeysDevice * device)
Start a probing move.
Command PEV2_CMD_START_PROBING (0x23) uses param1 as axis selection mask. Bytes 8-39 hold maximum probe positions, byte 40 holds probe speed and bytes 44-45 define probe input and polarity.
Parameters
device Device configured with probe parameters.
Returns
Result of SendRequest.
Definition at line 743 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysDevice::PEv2, PEV2_CMD_START_PROBING, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ProbeInput, sPoKeysPEv2::ProbeInputPolarity, sPoKeysPEv2::ProbeMaxPosition, sPoKeysPEv2::ProbeSpeed, sPoKeysPEv2::ProbeStartMaskSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineMove()
int32_t PK_PEv2_PulseEngineMove (sPoKeysDevice * device)
Execute a move using reference positions or speeds.
Command PEV2_CMD_MOVE (0x20) accepts eight 32-bit position or speed values located in bytes 8-39 of the request. The values are taken from PEv2.ReferencePositionSpeed.
Parameters
device Active PoKeys device.
Returns
Result of SendRequest.
Definition at line 410 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysDevice::PEv2, PEV2_CMD_MOVE, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ReferencePositionSpeed, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineMovePV()
int32_t PK_PEv2_PulseEngineMovePV (sPoKeysDevice * device)
Perform a move in position/velocity mode.
Uses command PEV2_CMD_MOVE_PV (0x25). In addition to the 32-bit reference positions, bytes 40-55 of the request include 16-bit velocity ratios derived from ReferenceVelocityPV. param2 carries the enable mask.
Parameters
device Active PoKeys device.
Returns
PK_OK or error from SendRequest.
Definition at line 442 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::param2, sPoKeysDevice::PEv2, PEV2_CMD_MOVE_PV, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ReferencePositionSpeed, sPoKeysPEv2::ReferenceVelocityPV, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineReboot()
int32_t PK_PEv2_PulseEngineReboot (sPoKeysDevice * device)
Reboot the pulse engine firmware.
Issues PEV2_CMD_REBOOT (0x05).
Parameters
device Target device.
Returns
Result of SendRequest.
Definition at line 668 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PEV2_CMD_REBOOT, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineSetup()
int32_t PK_PEv2_PulseEngineSetup (sPoKeysDevice * device)
Configure the pulse engine parameters.
Uses command PEV2_CMD_SETUP (0x01). The request payload contains enable flags, buffer size and emergency switch polarity in bytes 8-13.
Parameters
device Pointer to the PoKeys device.
Returns
PK_OK on success or an error code on failure.
Definition at line 154 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxisEnabledStatesMask, sPoKeysPEv2::ChargePumpEnabled, CreateRequest(), sPoKeysPEv2::EmergencySwitchPolarity, sPoKeysDevice::PEv2, PEV2_CMD_SETUP, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineBufferSize, sPoKeysPEv2::PulseEngineEnabled, sPoKeysPEv2::PulseGeneratorType, sPoKeysDevice::request, and SendRequest().
Referenced by PEv2_PulseEngineSetup().
PK_PEv2_PulseEngineStateSet()
int32_t PK_PEv2_PulseEngineStateSet (sPoKeysDevice * device)
Change the operating state of the pulse engine.
Sends PEV2_CMD_SET_STATE (0x02). Parameters specify the desired engine state, limit override flag and axis enable mask which are placed in param1, param2 and param3.
Parameters
device Pointer to a PoKeys device with setup values stored in the PEv2 structure.
Returns
PK_OK on success or error code.
Definition at line 389 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxisEnabledMask, CreateRequest(), sPoKeysPEv2::LimitOverrideSetup, sPoKeysDevice::PEv2, PEV2_CMD_SET_STATE, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineStateSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_Status2Get()
int32_t PK_PEv2_Status2Get (sPoKeysDevice * device)
Obtain extended status information.
Executes command PEV2_CMD_GET_STATUS2 (0x08) of PK_CMD_PULSE_ENGINE_V2. The response provides the count of dedicated limit and home inputs which is stored in sPoKeysPEv2.
Parameters
device Target device.
Returns
PK_OK on success or an error code from communication.
Definition at line 130 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::DedicatedHomeInputs, sPoKeysPEv2::DedicatedLimitNInputs, sPoKeysPEv2::DedicatedLimitPInputs, sPoKeysDevice::PEv2, PEV2_CMD_GET_STATUS2, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by PEv2_Status2Get(), and PoKeysHALComponent::PKPEv2_Setup().
PK_PEv2_StatusGet()
int32_t PK_PEv2_StatusGet (sPoKeysDevice * device)
Retrieve pulse engine status.
Sends command PEV2_CMD_GET_STATUS (0x00) under PK_CMD_PULSE_ENGINE_V2. param1 is used as a handshake value and the response updates the sPoKeysPEv2 status structure with axis states, current position and engine info.
Parameters
device Pointer to the PoKeys device.
Returns
PK_OK when successful, error code otherwise.
Definition at line 90 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PEV2_CMD_GET_STATUS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineActivated, sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, and SendRequest().
Referenced by PEv2_StatusGet(), PoKeysHALComponent::PKPEv2_ReadIniFile(), and PoKeysHALComponent::PKPEv2_Setup().
PK_PEv2_SyncedPWMSetup()
int32_t PK_PEv2_SyncedPWMSetup (sPoKeysDevice * device, uint8_t enabled, uint8_t srcAxis, uint8_t dstPWMChannel)
Configure synchronized PWM output.
Command PEV2_CMD_SETUP_SYNCED_PWM (0x0A). The request enables or disables synchronized PWM generation based on an axis position.
Parameters
device Target device.
enabled Non-zero to enable feature.
srcAxis Source axis index (0-based).
dstPWMChannel PWM output channel.
Returns
PK_OK on success or error code.
Definition at line 1123 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PEV2_CMD_SETUP_SYNCED_PWM, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_SyncOutputsSetup()
int32_t PK_PEv2_SyncOutputsSetup (sPoKeysDevice * device)
Configure synchronized digital outputs.
Command PEV2_CMD_SETUP_SYNCED_DIGITAL (0x0B) maps a group of outputs to follow the position of an axis.
Parameters
device Device with mapping information stored in SyncFastOutputsMapping and axis ID in SyncFastOutputsAxisID.
Returns
PK_OK on success or error code.
Definition at line 1147 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PEV2_CMD_SETUP_SYNCED_DIGITAL, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), sPoKeysPEv2::SyncFastOutputsAxisID, and sPoKeysPEv2::SyncFastOutputsMapping.
PK_PEv2_ThreadingCancel()
int32_t PK_PEv2_ThreadingCancel (sPoKeysDevice * device)
Cancel a prepared threading operation.
Command PEV2_CMD_CANCEL_THREADING (0x34) clears any pending trigger preparation.
Parameters
device PoKeys device.
Returns
Result of SendRequest.
Definition at line 954 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PEV2_CMD_CANCEL_THREADING, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingForceTriggerReady()
int32_t PK_PEv2_ThreadingForceTriggerReady (sPoKeysDevice * device)
Force trigger ready state.
Command PEV2_CMD_FORCE_TRIGGER_READY (0x31) immediately sets the trigger as ready for threading.
Parameters
device PoKeys device.
Returns
PK_OK on success or error code.
Definition at line 888 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PEV2_CMD_FORCE_TRIGGER_READY, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingPrepareForTrigger()
int32_t PK_PEv2_ThreadingPrepareForTrigger (sPoKeysDevice * device)
Prepare the spindle threading trigger.
Executes PEV2_CMD_PREPARE_TRIGGER (0x30) which readies the device for the next threading operation.
Parameters
device Target device.
Returns
PK_OK on success or error code from communication.
Definition at line 866 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PEV2_CMD_PREPARE_TRIGGER, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingRelease()
int32_t PK_PEv2_ThreadingRelease (sPoKeysDevice * device)
Release the threading trigger.
Sends PEV2_CMD_RELEASE_TRIGGER (0x33) which aborts waiting for the spindle index.
Parameters
device Target device.
Returns
Result of SendRequest.
Definition at line 932 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PEV2_CMD_RELEASE_TRIGGER, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingSetup()
int32_t PK_PEv2_ThreadingSetup (sPoKeysDevice * device, uint8_t sensorMode, uint16_t ticksPerRevolution, uint16_t tagetSpindleRPM, uint16_t filterGainSpeed, uint16_t filterGainPosition)
Configure spindle threading parameters.
Uses PEV2_CMD_SET_THREADING_PARAMS (0x36). The request provides sensor mode and filter settings in the payload while TriggerIngnoredAxisMask is stored in byte 20.
Parameters
device Target device.
sensorMode Sensor mode selector.
ticksPerRevolution Encoder ticks per spindle revolution.
tagetSpindleRPM Desired spindle speed.
filterGainSpeed Speed filter gain.
filterGainPosition Position filter gain.
Returns
PK_OK on success or error code.
Definition at line 1025 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PEV2_CMD_SET_THREADING_PARAMS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), and sPoKeysPEv2::TriggerIngnoredAxisMask.
PK_PEv2_ThreadingStatusGet()
int32_t PK_PEv2_ThreadingStatusGet (sPoKeysDevice * device)
Query the status of a threading operation.
Sends PEV2_CMD_GET_THREADING_STATUS (0x35) which returns various trigger flags along with spindle diagnostic data in the response bytes 8-63.
Parameters
device Target device.
Returns
PK_OK on success or error code.
Definition at line 977 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::DebugValues, i, sPoKeysDevice::PEv2, PEV2_CMD_GET_THREADING_STATUS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysPEv2::spindleIndexCounter, sPoKeysPEv2::SpindlePositionError, sPoKeysPEv2::SpindleRPM, sPoKeysPEv2::SpindleSpeedEstimate, sPoKeysPEv2::TriggerActive, sPoKeysPEv2::TriggerIngnoredAxisMask, sPoKeysPEv2::TriggerPending, sPoKeysPEv2::TriggerPrepared, and sPoKeysPEv2::TriggerPreparing.
PK_PEv2_ThreadingTrigger()
int32_t PK_PEv2_ThreadingTrigger (sPoKeysDevice * device)
Arm the threading trigger.
Executes PEV2_CMD_ARM_TRIGGER (0x32) which waits for the configured spindle index before executing motion.
Parameters
device Target device.
Returns
PK_OK if the command is sent successfully.
Definition at line 910 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PEV2_CMD_ARM_TRIGGER, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PoStep_ConfigurationGet()
int32_t PK_PoStep_ConfigurationGet (sPoKeysDevice * device)
Get configuration for external PoStep drivers.
Command PEV2_CMD_SETUP_DRIVER_COMM (0x50) retrieves driver type, I2C address and update flags for each axis.
Parameters
device Target device.
Returns
PK_OK on success or communication error.
Definition at line 1170 of file PoKeysLibPulseEngine_v2.c.
References sPoPoStepDriverConfig::AddressI2C, CreateRequest(), sPoKeysPoStepInterface::drivers, sPoPoStepDriverConfig::DriverType, sPoKeysPoStepInterface::EnablePoStepCommunication, i, PEV2_CMD_SETUP_DRIVER_COMM, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), and sPoPoStepDriverConfig::UpdateConfig.
Referenced by Config_PoStep().
PK_PoStep_ConfigurationSet()
int32_t PK_PoStep_ConfigurationSet (sPoKeysDevice * device)
Configure external PoStep drivers.
Sends PEV2_CMD_SETUP_DRIVER_COMM (0x50) with param1=0x10 followed by driver type, address and update flags for each axis.
Parameters
device Device holding configuration in PoSteps.
Returns
PK_OK on success or error code.
Definition at line 1203 of file PoKeysLibPulseEngine_v2.c.
References sPoPoStepDriverConfig::AddressI2C, CreateRequest(), sPoKeysPoStepInterface::drivers, sPoPoStepDriverConfig::DriverType, sPoKeysPoStepInterface::EnablePoStepCommunication, i, PEV2_CMD_SETUP_DRIVER_COMM, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), and sPoPoStepDriverConfig::UpdateConfig.
PK_PoStep_DriverConfigurationGet()
int32_t PK_PoStep_DriverConfigurationGet (sPoKeysDevice * device)
Read PoStep driver current and mode settings.
Uses commands PEV2_CMD_DRIVER_CURRENT_PARAMS (0x52) and PEV2_CMD_DRIVER_MODE_PARAMS (0x53) to obtain current limits, driver mode, microstepping and temperature limits.
Parameters
device Target device.
Returns
PK_OK on success or communication error.
Definition at line 1280 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoPoStepDriverConfig::Current_FS, sPoPoStepDriverConfig::Current_Idle, sPoPoStepDriverConfig::Current_Overheat, sPoPoStepDriverConfig::DriverMode, sPoKeysPoStepInterface::drivers, i, PEV2_CMD_DRIVER_CURRENT_PARAMS, PEV2_CMD_DRIVER_MODE_PARAMS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoPoStepDriverConfig::StepMode, and sPoPoStepDriverConfig::TemperatureLimit.
Referenced by Config_PoStep().
PK_PoStep_DriverConfigurationSet()
int32_t PK_PoStep_DriverConfigurationSet (sPoKeysDevice * device)
Write PoStep driver current and mode parameters.
Sends PEV2_CMD_DRIVER_CURRENT_PARAMS and PEV2_CMD_DRIVER_MODE_PARAMS with param1=0x10 to update driver settings for all axes.
Parameters
device Device containing new driver parameters.
Returns
PK_OK on success or error code.
Definition at line 1329 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoPoStepDriverConfig::Current_FS, sPoPoStepDriverConfig::Current_Idle, sPoPoStepDriverConfig::Current_Overheat, sPoPoStepDriverConfig::DriverMode, sPoKeysPoStepInterface::drivers, i, PEV2_CMD_DRIVER_CURRENT_PARAMS, PEV2_CMD_DRIVER_MODE_PARAMS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoPoStepDriverConfig::StepMode, and sPoPoStepDriverConfig::TemperatureLimit.
PK_PoStep_StatusGet()
int32_t PK_PoStep_StatusGet (sPoKeysDevice * device)
Read status information from PoStep drivers.
Executes PEV2_CMD_GET_DRIVER_STATUS (0x51) which returns voltage, temperature and diagnostic bits for each driver.
Parameters
device Target device.
Returns
PK_OK or error code.
Definition at line 1244 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPoStepInterface::drivers, sPoPoStepDriverConfig::DriverStatus, sPoPoStepDriverConfig::FaultStatus, i, sPoPoStepDriverConfig::InputStatus, PEV2_CMD_GET_DRIVER_STATUS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoPoStepDriverConfig::SupplyVoltage, sPoPoStepDriverConfig::Temperature, and sPoPoStepDriverConfig::UpdateState.
Referenced by Update_PoStep().