LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/pokeyslib/PoKeysLibEasySensors.c File Reference
PoKeysLibEasySensors.c File Reference
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
Functions
int32_t PK_EasySensorsSetupGet (sPoKeysDevice *device)
int32_t PK_EasySensorsSetupSet (sPoKeysDevice *device)
int32_t PK_EasySensorsValueGetAll (sPoKeysDevice *device)
int32_t PK_SL_EasySensorValueGet (sPoKeysDevice *device, uint8_t index)
Function Documentation
PK_EasySensorsSetupGet()
int32_t PK_EasySensorsSetupGet (sPoKeysDevice * device)
Retrieve EasySensors configuration from the device.
Each EasySensor present on the device is queried and the information is stored in the sPoKeysDevice structure. Sensor type, reading ID, refresh period, failsafe configuration and the unique sensor identifier are updated for every entry in the EasySensors array.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 24 of file PoKeysLibEasySensors.c.
References CreateRequest(), sPoKeysDevice::EasySensors, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysEasySensor::sensorFailsafeConfig, sPoKeysEasySensor::sensorID, sPoKeysEasySensor::sensorReadingID, sPoKeysEasySensor::sensorRefreshPeriod, sPoKeysEasySensor::sensorType, and sPoKeysEasySensor::sensorValue.
PK_EasySensorsSetupSet()
int32_t PK_EasySensorsSetupSet (sPoKeysDevice * device)
Send EasySensors configuration to the device.
The function iterates through the EasySensors array of the provided device structure and writes each sensor's configuration back to the device.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 54 of file PoKeysLibEasySensors.c.
References CreateRequest(), sPoKeysDevice::EasySensors, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), sPoKeysEasySensor::sensorFailsafeConfig, sPoKeysEasySensor::sensorID, sPoKeysEasySensor::sensorReadingID, sPoKeysEasySensor::sensorRefreshPeriod, and sPoKeysEasySensor::sensorType.
PK_EasySensorsValueGetAll()
int32_t PK_EasySensorsValueGetAll (sPoKeysDevice * device)
Read values of all EasySensors from the device.
Sensor values are read in batches and stored together with status flags in the EasySensors array of the target device.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 83 of file PoKeysLibEasySensors.c.
References CreateRequest(), sPoKeysDevice::EasySensors, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysEasySensor::sensorOKstatus, and sPoKeysEasySensor::sensorValue.
PK_SL_EasySensorValueGet()
int32_t PK_SL_EasySensorValueGet (sPoKeysDevice * device, uint8_t index)
Return the last acquired value of the selected EasySensor.
This helper performs no communication with the device and simply returns the cached value stored in the sPoKeysDevice structure.
Parameters
device Pointer to an initialized device structure.
index Zero-based EasySensor index.
Returns
Current sensor value or 0 if the parameters are invalid.
Definition at line 117 of file PoKeysLibEasySensors.c.
References sPoKeysDevice::EasySensors, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, and sPoKeysEasySensor::sensorValue.