LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibSPI.c File Reference
PoKeysLibSPI.c File Reference
SPI communication helpers (command 0xE5).
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
Functions
int32_t PK_SPIConfigure (sPoKeysDevice *device, uint8_t prescaler, uint8_t frameFormat)
Configure the SPI interface of a PoKeys device (command 0xE5/0x01).
int32_t PK_SPIWrite (sPoKeysDevice *device, uint8_t *buffer, uint8_t iDataLength, uint8_t pinCS)
Transmit data over the SPI interface (command 0xE5/0x10).
int32_t PK_SPIRead (sPoKeysDevice *device, uint8_t *buffer, uint8_t iDataLength)
Receive data from the SPI interface (command 0xE5/0x20).
Detailed Description
SPI communication helpers (command 0xE5).
Provides basic configuration and data transfer routines for the SPI interface on PoKeys devices.
Definition in file PoKeysLibSPI.c.
Function Documentation
PK_SPIConfigure()
int32_t PK_SPIConfigure (sPoKeysDevice * device, uint8_t prescaler, uint8_t frameFormat)
Configure the SPI interface of a PoKeys device (command 0xE5/0x01).
Issues PK_CMD_SPI_COMMUNICATION with subcommand 0x01 to set the SPI clock prescaler and frame format.
Parameters
device Pointer to an initialised device structure.
prescaler SPI clock prescaler value sent to the device.
frameFormat Frame configuration (mode, bit length etc.).
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 44 of file PoKeysLibSPI.c.
References CreateRequest(), PK_CMD_SPI_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_SPIRead()
int32_t PK_SPIRead (sPoKeysDevice * device, uint8_t * buffer, uint8_t iDataLength)
Receive data from the SPI interface (command 0xE5/0x20).
Issues a read request for the specified number of bytes. The returned values are copied into the provided buffer on success.
Parameters
device Pointer to an initialised PoKeys device structure.
buffer Destination buffer for the received bytes.
iDataLength Number of bytes to read (maximum 55).
Returns
PK_OK if the data was read successfully, otherwise a negative ::PK_ERR code.
Definition at line 97 of file PoKeysLibSPI.c.
References CreateRequest(), i, PK_CMD_SPI_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_SPIWrite()
int32_t PK_SPIWrite (sPoKeysDevice * device, uint8_t * buffer, uint8_t iDataLength, uint8_t pinCS)
Transmit data over the SPI interface (command 0xE5/0x10).
Sends a block of up to 55 bytes to the selected chip on the PoKeys device. The chip select line is asserted automatically by the device.
Parameters
device Pointer to an initialised PoKeys device structure.
buffer Data buffer containing bytes to transmit.
iDataLength Number of bytes to send (max 55).
pinCS Chip select pin identifier on the PoKeys device.
Returns
PK_OK on success or a negative ::PK_ERR code when the transfer fails.
Definition at line 67 of file PoKeysLibSPI.c.
References CreateRequest(), i, PK_CMD_SPI_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().