LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibAsync.h File Reference
PoKeysLibAsync.h File Reference
#include "PoKeysLibHal.h"
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
Data Structures
struct async_transaction_t
struct mailbox_entry_t
Macros
#define MAX_TRANSACTIONS 64
Typedefs
typedef int(* pokeys_response_parser_t) (sPoKeysDevice *dev, const uint8_t *response)
Enumerations
enum transaction_status_t { TRANSACTION_PENDING = 0 , TRANSACTION_COMPLETED = 1 , TRANSACTION_TIMEOUT = 2 , TRANSACTION_FAILED = 3 }
enum pokeys_command_t {
PK_CMD_READ_DEVICE_DATA = 0x00 , PK_CMD_RESERVED_01 = 0x01 , PK_CMD_SET_USER_ID = 0x02 , PK_CMD_READ_USER_ID_LOCK = 0x03 ,
PK_CMD_READ_BUILD_DATE = 0x04 , PK_CMD_GET_SYSTEM_LOAD_STATUS = 0x05 , PK_CMD_DEVICE_NAME = 0x06 , PK_CMD_CONFIGURE_USB = 0x07 ,
PK_CMD_DELAYED_STARTUP_CFG = 0x08 , PK_CMD_PPM_DECODER_CFG = 0x09 , PK_CMD_SESSION_SETTINGS = 0x0A , PK_CMD_MISC_USB_CONFIGURATION = 0x0B ,
PK_CMD_IO_SETTINGS_SET = 0x10 , PK_CMD_ENCODER_SETTINGS_SET = 0x11 , PK_CMD_ENCODER_KEYMAP_A_SET = 0x12 , PK_CMD_ENCODER_KEYMAP_B_SET = 0x13 ,
PK_CMD_GET_PIN_FUNCTION = 0x15 , PK_CMD_ENCODER_SETTINGS_GET = 0x16 , PK_CMD_ENCODER_KEYMAP_A_GET = 0x17 , PK_CMD_ENCODER_KEYMAP_B_GET = 0x18 ,
PK_CMD_ENCODER_RAW_VALUE_GET = 0x19 , PK_CMD_ENCODER_RAW_VALUE_RESET = 0x1A , PK_CMD_CONNECTION_PIN_STATUS = 0x1B , PK_CMD_ULTRAFAST_ENCODER_ENABLE = 0x1C ,
PK_CMD_DIGITAL_COUNTERS_RESET = 0x1D , PK_CMD_ADDITIONAL_PIN_SETTINGS = 0x1E , PK_CMD_GET_PIN_CAPABILITIES = 0x1F , PK_CMD_KEY_ASSOCIATION_SET = 0x20 ,
PK_CMD_PIN_TYPEMATIC_DELAY = 0x21 , PK_CMD_PIN_REPEAT_RATE = 0x22 , PK_CMD_KEY_ASSOCIATION_GET = 0x25 , PK_CMD_DIGITAL_INPUTS_GET = 0x30 ,
PK_CMD_DIGITAL_INPUTS_BLOCK_I = 0x31 , PK_CMD_DIGITAL_INPUTS_BLOCK_II = 0x32 , PK_CMD_ANALOG_INPUT_GET = 0x35 , PK_CMD_ANALOG_INPUT_BLOCK_4X8 = 0x36 ,
PK_CMD_ANALOG_INPUT_BLOCK_3X10 = 0x37 , PK_CMD_ANALOG_RC_FILTER_GET = 0x38 , PK_CMD_ANALOG_RC_FILTER_SET = 0x39 , PK_CMD_ANALOG_INPUTS_GET_ALL = 0x3A ,
PK_CMD_FULL_IO = 0x3F , PK_CMD_DIGITAL_OUTPUTS_SET = 0x40 , PK_CMD_ANALOG_OUTPUTS_SET = 0x41 , PK_CMD_DIGITAL_OUTPUT_BLOCK_I_SET = 0x42 ,
PK_CMD_DIGITAL_OUTPUT_BLOCK_II_SET = 0x43 , PK_CMD_MCS_SYSTEM = 0x4A , PK_CMD_WS2812_CONTROL = 0x4B , PK_CMD_SIMPLE_PULSE_GENERATOR = 0x4C ,
PK_CMD_CONFIGURATION_SAVE = 0x50 , PK_CMD_CONFIGURATION_SAVE_LOCK = 0x51 , PK_CMD_CONFIGURATION_RESET_UNLOCK = 0x52 , PK_CMD_JOYSTICK_CFG_GET = 0x60 ,
PK_CMD_JOYSTICK_UPBTN_GET = 0x61 , PK_CMD_JOYSTICK_CFG_SET = 0x65 , PK_CMD_JOYSTICK_UPBTN_SET = 0x66 , PK_CMD_JOYSTICK_ANALOG_TO_DIGITAL = 0x6A ,
PK_CMD_SENSORS_SETUP_56 = 0x70 , PK_CMD_DASHBOARD_ITEMS_SETUP = 0x71 , PK_CMD_WEB_USERS_SETUP = 0x72 , PK_CMD_WEB_SETTINGS_SETUP = 0x73 ,
PK_CMD_READ_ALL_SENSORS = 0x74 , PK_CMD_SENSORS_SETUP_57 = 0x76 , PK_CMD_SENSOR_VALUES_READ_57 = 0x77 , PK_CMD_DASHBOARD_ITEMS_SETUP_57 = 0x78 ,
PK_CMD_SIMPLE_SENSOR_CFG = 0x79 , PK_CMD_PULSE_ENGINE_DEPRECATED = 0x80 , PK_CMD_FAILSAFE_SETTINGS = 0x81 , PK_CMD_POIL_COMMANDS = 0x82 ,
PK_CMD_RTC_SETTINGS = 0x83 , PK_CMD_SYSTEM_LOG_OPS = 0x84 , PK_CMD_PULSE_ENGINE_V2 = 0x85 , PK_CMD_CAN_OPERATIONS = 0x86 ,
PK_CMD_UNLOCK_OPTION = 0x8F , PK_CMD_MACRO_CREATE = 0x90 , PK_CMD_MACRO_MODIFY = 0x91 , PK_CMD_MACRO_DELETE = 0x92 ,
PK_CMD_MACRO_SAVE_TO_FLASH = 0x93 , PK_CMD_MACRO_RENAME = 0x94 , PK_CMD_MACRO_TRANSFER = 0x95 , PK_CMD_MACRO_LENGTH_GET = 0x96 ,
PK_CMD_MACRO_NAME_GET = 0x97 , PK_CMD_MACRO_KEYS_GET = 0x98 , PK_CMD_MACRO_FREE_SPACE_GET = 0x99 , PK_CMD_MACRO_ACTIVE_GET = 0x9A ,
PK_CMD_RTMODE_SETUP = 0xA0 , PK_CMD_RTMODE_PACKET_IO = 0xA1 , PK_CMD_UDP_BINARY_REALTIME_CFG = 0xA2 , PK_CMD_MULTIPART_PACKET = 0xB0 ,
PK_CMD_PIN_CONFIGURATION = 0xC0 , PK_CMD_PIN_KEY_MAPPING = 0xC1 , PK_CMD_PIN_KEY_CODES = 0xC2 , PK_CMD_PIN_KEY_MODIFIERS = 0xC3 ,
PK_CMD_ENCODER_OPTION_SET = 0xC4 , PK_CMD_ENCODER_CHANNELS_SET = 0xC5 , PK_CMD_ENCODER_KEYMAP_A_SET2 = 0xC6 , PK_CMD_ENCODER_KEYMAP_B_SET2 = 0xC7 ,
PK_CMD_MATRIX_KEYBOARD_CFG = 0xCA , PK_CMD_PWM_CONFIGURATION = 0xCB , PK_CMD_DEVICE_STATUS_GET = 0xCC , PK_CMD_DEVICE_LOAD_STATUS = 0x86 ,
PK_CMD_DEVICE_ERROR_STATUS = 0x87 , PK_CMD_ENCODER_LONG_RAW_VALUES_GET = 0xCD , PK_CMD_FAST_ENCODERS_SET = 0xCE , PK_CMD_TICK_COUNTER_GET = 0xCF ,
PK_CMD_LCD_CONFIGURATION = 0xD0 , PK_CMD_LCD_OPERATION = 0xD1 , PK_CMD_MATRIX_LED_CONFIGURATION = 0xD5 , PK_CMD_MATRIX_LED_UPDATE = 0xD6 ,
PK_CMD_TRIGGERED_INPUT_SETTINGS = 0xD7 , PK_CMD_DIGITAL_COUNTERS_VALUES = 0xD8 , PK_CMD_DIGITAL_COUNTERS_DIRECTION = 0xD9 , PK_CMD_AUX_BUS_SETTINGS = 0xDA ,
PK_CMD_I2C_COMMUNICATION = 0xDB , PK_CMD_ONEWIRE_COMMUNICATION = 0xDC , PK_CMD_POI2C_COMMUNICATION = 0xDD , PK_CMD_UART_COMMUNICATION = 0xDE ,
PK_CMD_NETWORK_SETTINGS = 0xE0 , PK_CMD_SECURITY_STATUS_GET = 0xE1 , PK_CMD_USER_AUTHORISE = 0xE2 , PK_CMD_USER_PASSWORD_SET = 0xE3 ,
PK_CMD_MODBUS_SETTINGS = 0xE4 , PK_CMD_SPI_COMMUNICATION = 0xE5 , PK_CMD_CAN_NODE_COMMANDS = 0xE6 , PK_CMD_COSM_SETTINGS = 0xEF ,
PK_CMD_REBOOT_SYSTEM = 0xF3 , PK_CMD_BOOT_CLEAR_MEMORY = 0xF0 , PK_CMD_BOOT_BLOCK_OPTIONS = 0xF1 , PK_CMD_BOOT_TRANSFER_BLOCK = 0xF2 ,
PK_CMD_BOOT_START_APP = 0xF3 , PK_CMD_BOOT_CALC_AND_SAVE_CRC = 0xF5 , PK_CMD_BOOT_CLEAR_USER_SETTINGS = 0xF6 , PK_CMD_BOOT_CUSTOM_COMMAND1 = 0xFA ,
PK_CMD_BOOT_OEM_COMMAND = 0xFB , PK_CMD_BOOT_OEM_PARAMETERS = 0xFD
}
enum PEv2_command_t {
PEV2_CMD_GET_STATUS = 0x00 , PEV2_CMD_SETUP = 0x01 , PEV2_CMD_SET_STATE = 0x02 , PEV2_CMD_SET_AXIS_POSITION = 0x03 ,
PEV2_CMD_SET_OUTPUTS = 0x04 , PEV2_CMD_REBOOT = 0x05 , PEV2_CMD_CONFIGURE_MISC = 0x06 , PEV2_CMD_GET_STATUS2 = 0x08 ,
PEV2_CMD_SETUP_SYNCED_PWM = 0x0A , PEV2_CMD_SETUP_SYNCED_DIGITAL = 0x0B , PEV2_CMD_GET_AXIS_CONFIGURATION = 0x10 , PEV2_CMD_SET_AXIS_CONFIGURATION = 0x11 ,
PEV2_CMD_GET_INTERNAL_DRIVERS = 0x18 , PEV2_CMD_SET_INTERNAL_DRIVERS = 0x19 , PEV2_CMD_MOVE = 0x20 , PEV2_CMD_START_HOMING = 0x21 ,
PEV2_CMD_FINISH_HOMING = 0x22 , PEV2_CMD_START_PROBING = 0x23 , PEV2_CMD_FINISH_PROBING = 0x24 , PEV2_CMD_MOVE_PV = 0x25 ,
PEV2_CMD_PREPARE_TRIGGER = 0x30 , PEV2_CMD_FORCE_TRIGGER_READY = 0x31 , PEV2_CMD_ARM_TRIGGER = 0x32 , PEV2_CMD_RELEASE_TRIGGER = 0x33 ,
PEV2_CMD_CANCEL_THREADING = 0x34 , PEV2_CMD_GET_THREADING_STATUS = 0x35 , PEV2_CMD_SET_THREADING_PARAMS = 0x36 , PEV2_CMD_GET_ENCODER_TEST_RESULTS = 0x37 ,
PEV2_CMD_GET_BACKLASH_SETTINGS = 0x40 , PEV2_CMD_SET_BACKLASH_SETTINGS = 0x41 , PEV2_CMD_SETUP_DRIVER_COMM = 0x50 , PEV2_CMD_GET_DRIVER_STATUS = 0x51 ,
PEV2_CMD_DRIVER_CURRENT_PARAMS = 0x52 , PEV2_CMD_DRIVER_MODE_PARAMS = 0x53 , PEV2_CMD_GET_DRIVER_VERSIONS = 0x54 , PEV2_CMD_SMART_CFG_GET = 0x90 ,
PEV2_CMD_SMART_CFG_SET = 0x91 , PEV2_CMD_SMART_COUNTERS_RESET = 0x92 , PEV2_CMD_SMART_STATUS = 0x95 , PEV2_CMD_SMART_ENCODERS = 0x96 ,
PEV2_CMD_CLEAR_BUFFER = 0xF0 , PEV2_CMD_TRANSFER_RAW = 0xE0 , PEV2_CMD_FILL_BUFFER_8BIT = 0xFF , PEV2_CMD_OUTPUT_ENABLE = 0xFF
}
enum PoCAN_command_t {
POCAN_CMD_STATUS = 0x00 , POCAN_CMD_ENABLE = 0x01 , POCAN_CMD_CONFIGURE = 0x02 , POCAN_CMD_DEVICE_IDENTIFICATION = 0x10 ,
POCAN_CMD_CONFIGURATION_READ = 0x11 , POCAN_CMD_CONFIGURATION_WRITE = 0x12 , POCAN_CMD_CONFIGURATION_SAVE = 0x13
}
enum PoCAN_DeviceType_T {
POCAN_DEVICE_PORELAY8 = 0x01 , POCAN_DEVICE_POCAN15I = 0x02 , POCAN_DEVICE_POCAN_LIN = 0x03 , POCAN_DEVICE_POCAN15TRIAC = 0x04 ,
POCAN_DEVICE_KBD48CNC = 0x05 , POCAN_DEVICE_POCAN4TRIAC = 0x06
}
enum PoNET_operations_t {
PONET_OP_GET_STATUS = 0x00 , PONET_OP_GET_MODULE_SETTINGS = 0x10 , PONET_OP_GET_FIRMWARE_VERSION = 0x11 , PONET_OP_SET_MODULE_SETTINGS = 0x15 ,
PONET_OP_CLEAR_MODULE_SETTINGS = 0x20 , PONET_OP_REINITIALIZE = 0x21 , PONET_OP_REINIT_AND_CLEAR = 0x25 , PONET_OP_DEVICE_DISCOVERY = 0x30 ,
PONET_OP_CHECK_FOR_DEVICES = 0x40 , PONET_OP_GET_MODULE_DATA = 0x50 , PONET_OP_SET_MODULE_DATA = 0x55 , PONET_OP_GET_LIGHT_SENSOR = 0x60 ,
PONET_OP_SET_PWM_VALUE = 0x70 , PONET_OP_START_BOOTLOADER = 0xF0 , PONET_OP_START_PROGRAMMING = 0xF1 , PONET_OP_TRANSFER_FIRMWARE_PART = 0xF2 ,
PONET_OP_FINISH_FIRMWARE_TRANSFER = 0xF3 , PONET_OP_EXIT_BOOTLOADER = 0xF4 , PONET_OP_ACTIVATE_BOOTLOADER = 0xF5
}
Functions
int CreateRequestAsync (sPoKeysDevice *dev, pokeys_command_t cmd, const uint8_t *params, size_t params_len, void *target_ptr, size_t target_size, int(*parser_func)(sPoKeysDevice *dev, const uint8_t *response))
int CreateRequestAsyncWithPayload (sPoKeysDevice *device, pokeys_command_t cmd, const uint8_t *params, size_t params_len, const void *payload, size_t payload_size, pokeys_response_parser_t parser_func)
Prepares an asynchronous PoKeys request with optional payload data after header.
int SendRequestAsync (sPoKeysDevice *dev, uint8_t request_id)
Sends an asynchronous request that was prepared earlier.
int PK_ReceiveAndDispatch (sPoKeysDevice *dev)
Receives UDP packets and dispatches them to the correct async transaction.
void PK_TimeoutAndRetryCheck (sPoKeysDevice *dev, uint64_t timeout_us)
Enhanced timeout and retry check with exponential backoff and error recovery.
int PK_PEv2_StatusGetAsync (sPoKeysDevice *device)
int PK_PEv2_Status2GetAsync (sPoKeysDevice *device)
int PK_PEv2_PulseEngineSetupAsync (sPoKeysDevice *device)
int PK_PEv2_AdditionalParametersGetAsync (sPoKeysDevice *device)
int PK_PEv2_AdditionalParametersSetAsync (sPoKeysDevice *device)
int PK_PEv2_AxisConfigurationGetAsync (sPoKeysDevice *device)
int PK_PEv2_AxisConfigurationSetAsync (sPoKeysDevice *device)
int PK_PEv2_PulseEngineMovePVAsync (sPoKeysDevice *device)
int PK_PEv2_HomingStartAsync (sPoKeysDevice *device)
int PK_PEv2_ExternalOutputsSetAsync (sPoKeysDevice *device)
int PK_EncoderRawValueResetAsync (sPoKeysDevice *device, uint32_t encoderMask)
Reset encoder raw values asynchronously (command 0x1A).
int PK_EncoderSingleResetAsync (sPoKeysDevice *device, uint8_t encoderIndex)
Reset a single encoder's raw value asynchronously.
int PK_EncoderAllResetAsync (sPoKeysDevice *device)
Reset all encoders' raw values asynchronously.
int PK_SPIConfigureAsync (sPoKeysDevice *device, uint8_t prescaler, uint8_t frameFormat)
Configure the SPI interface asynchronously (command 0xE5/0x01).
int PK_SPIWriteAsync (sPoKeysDevice *device, const uint8_t *buffer, uint8_t dataLength, uint8_t pinCS)
Write data to SPI bus asynchronously (command 0xE5/0x02).
int PK_SPIReadAsync (sPoKeysDevice *device, uint8_t *buffer, uint8_t dataLength)
Read data from SPI bus asynchronously (command 0xE5/0x03).
int PK_SPITransferAsync (sPoKeysDevice *device, const uint8_t *txBuffer, uint8_t *rxBuffer, uint8_t dataLength, uint8_t pinCS)
Perform SPI write/read transaction asynchronously (command 0xE5/0x04).
int PK_DeviceAliveCheckAsync (sPoKeysDevice *device)
Check if device is alive/responsive (async)
int PK_DeviceLoadStatusAsync (sPoKeysDevice *device)
Get device load status (async)
int PK_DeviceErrorStatusAsync (sPoKeysDevice *device)
Get device error status (async)
int PK_DeviceErrorResetAsync (sPoKeysDevice *device)
Reset device error counters (async)
int PK_DeviceStatusFullAsync (sPoKeysDevice *device)
Comprehensive device status check (async)
int PK_DeviceConnectionQualityAsync (sPoKeysDevice *device, uint8_t *quality)
Check connection quality metrics (async)
int PK_DeviceConnectionFailureAsync (sPoKeysDevice *device)
Handle communication failure (for retry logic)
int PK_PWMConfigurationGetAsync (sPoKeysDevice *device)
Starts async request to get PWM configuration (CMD 0xCB, param1=0)
int PK_PWMConfigurationSetAsync (sPoKeysDevice *device)
Starts async command to configure PWM duty cycle and period (CMD 0xCB).
int PK_PWMUpdateAsync (sPoKeysDevice *device)
Starts async command to update PWM values only (CMD 0xCB, param1=1, param2=1).
int PK_PWMConfigurationSetDirectlyAsync (sPoKeysDevice *device, uint32_t PWMperiod, uint8_t *enabledChannels)
Set PWM configuration directly with specified parameters (async)
int PK_PWMUpdateDirectlyAsync (sPoKeysDevice *device, uint32_t *dutyCycles)
Update PWM duty cycles directly (async)
int PK_PWMSetSingleChannelAsync (sPoKeysDevice *device, uint8_t channel, uint32_t dutyCycle)
Set single PWM channel duty cycle (async)
int PK_PWMGetPinAssignmentsAsync (sPoKeysDevice *device)
Get PWM pin assignments (async)
int PK_DigitalOutputSetSingleAsync (sPoKeysDevice *device, uint8_t pinIndex, uint8_t value)
Set a single digital output pin (async)
int PK_DigitalInputGetSingleAsync (sPoKeysDevice *device, uint8_t pinIndex)
Get a single digital input pin state (async)
int PK_DigitalOutputToggleAsync (sPoKeysDevice *device, uint8_t pinIndex)
Toggle a digital output pin (async)
int PK_AnalogIOGetAsync (sPoKeysDevice *device)
Starts async request for analog inputs (CMD 0x3A, param1=1).
int PK_AnalogRCFilterGetAsync (sPoKeysDevice *device)
Starts async request for RC analog filter value (CMD 0x38).
int PK_AnalogRCFilterSetAsync (sPoKeysDevice *device)
Starts async command to set RC analog filter (CMD 0x39).
int PK_DigitalIOGetAsync (sPoKeysDevice *device)
Asynchronously requests digital IO input values.
int PK_DigitalIOSetGetAsync (sPoKeysDevice *device)
Combined Set and Get digital IO in one async call.
int PK_DigitalCounterGetAsync (sPoKeysDevice *device)
Starts async request to get digital counter values (CMD 0xD8).
int PK_DigitalCounterClearAsync (sPoKeysDevice *device)
Starts async request to clear digital counters (CMD 0x1D).
int PK_DigitalCounterParse (sPoKeysDevice *device, const uint8_t *response)
Parser for digital counter values (CMD 0xD8).
int PK_PinConfigurationGetAsync (sPoKeysDevice *device)
int PK_PinConfigurationSetAsync (sPoKeysDevice *device)
Sets all pin configuration fields asynchronously.
int PK_DigitalOutputSetMultipleAsync (sPoKeysDevice *device, const uint8_t *pinList, const uint8_t *valueList, uint8_t count)
Set multiple digital outputs in a single efficient operation (async)
int PK_DigitalCounterGetSelectedAsync (sPoKeysDevice *device, const uint8_t *pinList, uint8_t count)
Get digital counter values for specific pins only (async)
int PK_PWMUpdateSelectedChannelsAsync (sPoKeysDevice *device, uint8_t channelMask, const uint32_t *dutyCycles)
Set PWM duty cycles for selected channels only (async)
int PK_SystemStatusGetAllAsync (sPoKeysDevice *device)
Get comprehensive system status in one operation (async)
int PK_IOUpdateCycleAsync (sPoKeysDevice *device)
Perform complete IO update cycle (async)
int PK_EmergencyStopAllAsync (sPoKeysDevice *device)
Emergency stop all motion and outputs (async)
int PK_CommunicationTestAsync (sPoKeysDevice *device, uint8_t testCount)
Test device communication and RT timing (async)
int PK_PoNETGetPoNETStatusAsync (sPoKeysDevice *device)
int PK_PoNETGetModuleSettingsAsync (sPoKeysDevice *device)
int PK_PoNETGetModuleStatusRequestAsync (sPoKeysDevice *device)
int PK_PoNETGetModuleStatusAsync (sPoKeysDevice *device)
int PK_PoNETSetModuleStatusAsync (sPoKeysDevice *device)
int PK_PoNETSetModulePWMAsync (sPoKeysDevice *device)
int PK_PoNETGetModuleLightRequestAsync (sPoKeysDevice *device)
int PK_PoNETGetModuleLightAsync (sPoKeysDevice *device)
int PK_PoNETKbd48CNCUpdateCycleAsync (sPoKeysDevice *device)
int PK_PoNETKbd48CNCLEDSetPatternAsync (sPoKeysDevice *device, uint8_t pattern[6])
int PK_PoNETKbd48CNCBrightnessSetAsync (sPoKeysDevice *device, uint8_t brightness)
int PK_PoNETDeviceDiscoveryAsync (sPoKeysDevice *device)
int PK_PoNETModuleReinitializeAsync (sPoKeysDevice *device, uint8_t moduleID)
Macro Definition Documentation
MAX_TRANSACTIONS
#define MAX_TRANSACTIONS 64
Definition at line 9 of file PoKeysLibAsync.h.
Typedef Documentation
pokeys_response_parser_t
typedef int(* pokeys_response_parser_t) (sPoKeysDevice *dev, const uint8_t *response)
Definition at line 281 of file PoKeysLibAsync.h.
Enumeration Type Documentation
PEv2_command_t
enum PEv2_command_t
Enumerator
PEV2_CMD_GET_STATUS
PEV2_CMD_SETUP
PEV2_CMD_SET_STATE
PEV2_CMD_SET_AXIS_POSITION
PEV2_CMD_SET_OUTPUTS
PEV2_CMD_REBOOT
PEV2_CMD_CONFIGURE_MISC
PEV2_CMD_GET_STATUS2
PEV2_CMD_SETUP_SYNCED_PWM
PEV2_CMD_SETUP_SYNCED_DIGITAL
PEV2_CMD_GET_AXIS_CONFIGURATION
PEV2_CMD_SET_AXIS_CONFIGURATION
PEV2_CMD_GET_INTERNAL_DRIVERS
PEV2_CMD_SET_INTERNAL_DRIVERS
PEV2_CMD_MOVE
PEV2_CMD_START_HOMING
PEV2_CMD_FINISH_HOMING
PEV2_CMD_START_PROBING
PEV2_CMD_FINISH_PROBING
PEV2_CMD_MOVE_PV
PEV2_CMD_PREPARE_TRIGGER
PEV2_CMD_FORCE_TRIGGER_READY
PEV2_CMD_ARM_TRIGGER
PEV2_CMD_RELEASE_TRIGGER
PEV2_CMD_CANCEL_THREADING
PEV2_CMD_GET_THREADING_STATUS
PEV2_CMD_SET_THREADING_PARAMS
PEV2_CMD_GET_ENCODER_TEST_RESULTS
PEV2_CMD_GET_BACKLASH_SETTINGS
PEV2_CMD_SET_BACKLASH_SETTINGS
PEV2_CMD_SETUP_DRIVER_COMM
PEV2_CMD_GET_DRIVER_STATUS
PEV2_CMD_DRIVER_CURRENT_PARAMS
PEV2_CMD_DRIVER_MODE_PARAMS
PEV2_CMD_GET_DRIVER_VERSIONS
PEV2_CMD_SMART_CFG_GET
PEV2_CMD_SMART_CFG_SET
PEV2_CMD_SMART_COUNTERS_RESET
PEV2_CMD_SMART_STATUS
PEV2_CMD_SMART_ENCODERS
PEV2_CMD_CLEAR_BUFFER
PEV2_CMD_TRANSFER_RAW
PEV2_CMD_FILL_BUFFER_8BIT
PEV2_CMD_OUTPUT_ENABLE
Definition at line 173 of file PoKeysLibAsync.h.
PoCAN_command_t
enum PoCAN_command_t
Enumerator
POCAN_CMD_STATUS
POCAN_CMD_ENABLE
POCAN_CMD_CONFIGURE
POCAN_CMD_DEVICE_IDENTIFICATION
POCAN_CMD_CONFIGURATION_READ
POCAN_CMD_CONFIGURATION_WRITE
POCAN_CMD_CONFIGURATION_SAVE
Definition at line 236 of file PoKeysLibAsync.h.
PoCAN_DeviceType_T
enum PoCAN_DeviceType_T
Enumerator
POCAN_DEVICE_PORELAY8
POCAN_DEVICE_POCAN15I
POCAN_DEVICE_POCAN_LIN
POCAN_DEVICE_POCAN15TRIAC
POCAN_DEVICE_KBD48CNC
POCAN_DEVICE_POCAN4TRIAC
Definition at line 249 of file PoKeysLibAsync.h.
pokeys_command_t
enum pokeys_command_t
Enumerator
PK_CMD_READ_DEVICE_DATA
PK_CMD_RESERVED_01
PK_CMD_SET_USER_ID
PK_CMD_READ_USER_ID_LOCK
PK_CMD_READ_BUILD_DATE
PK_CMD_GET_SYSTEM_LOAD_STATUS
PK_CMD_DEVICE_NAME
PK_CMD_CONFIGURE_USB
PK_CMD_DELAYED_STARTUP_CFG
PK_CMD_PPM_DECODER_CFG
PK_CMD_SESSION_SETTINGS
PK_CMD_MISC_USB_CONFIGURATION
PK_CMD_IO_SETTINGS_SET
PK_CMD_ENCODER_SETTINGS_SET
PK_CMD_ENCODER_KEYMAP_A_SET
PK_CMD_ENCODER_KEYMAP_B_SET
PK_CMD_GET_PIN_FUNCTION
PK_CMD_ENCODER_SETTINGS_GET
PK_CMD_ENCODER_KEYMAP_A_GET
PK_CMD_ENCODER_KEYMAP_B_GET
PK_CMD_ENCODER_RAW_VALUE_GET
PK_CMD_ENCODER_RAW_VALUE_RESET
PK_CMD_CONNECTION_PIN_STATUS
PK_CMD_ULTRAFAST_ENCODER_ENABLE
PK_CMD_DIGITAL_COUNTERS_RESET
PK_CMD_ADDITIONAL_PIN_SETTINGS
PK_CMD_GET_PIN_CAPABILITIES
PK_CMD_KEY_ASSOCIATION_SET
PK_CMD_PIN_TYPEMATIC_DELAY
PK_CMD_PIN_REPEAT_RATE
PK_CMD_KEY_ASSOCIATION_GET
PK_CMD_DIGITAL_INPUTS_GET
PK_CMD_DIGITAL_INPUTS_BLOCK_I
PK_CMD_DIGITAL_INPUTS_BLOCK_II
PK_CMD_ANALOG_INPUT_GET
PK_CMD_ANALOG_INPUT_BLOCK_4X8
PK_CMD_ANALOG_INPUT_BLOCK_3X10
PK_CMD_ANALOG_RC_FILTER_GET
PK_CMD_ANALOG_RC_FILTER_SET
PK_CMD_ANALOG_INPUTS_GET_ALL
PK_CMD_FULL_IO
PK_CMD_DIGITAL_OUTPUTS_SET
PK_CMD_ANALOG_OUTPUTS_SET
PK_CMD_DIGITAL_OUTPUT_BLOCK_I_SET
PK_CMD_DIGITAL_OUTPUT_BLOCK_II_SET
PK_CMD_MCS_SYSTEM
PK_CMD_WS2812_CONTROL
PK_CMD_SIMPLE_PULSE_GENERATOR
PK_CMD_CONFIGURATION_SAVE
PK_CMD_CONFIGURATION_SAVE_LOCK
PK_CMD_CONFIGURATION_RESET_UNLOCK
PK_CMD_JOYSTICK_CFG_GET
PK_CMD_JOYSTICK_UPBTN_GET
PK_CMD_JOYSTICK_CFG_SET
PK_CMD_JOYSTICK_UPBTN_SET
PK_CMD_JOYSTICK_ANALOG_TO_DIGITAL
PK_CMD_SENSORS_SETUP_56
PK_CMD_DASHBOARD_ITEMS_SETUP
PK_CMD_WEB_USERS_SETUP
PK_CMD_WEB_SETTINGS_SETUP
PK_CMD_READ_ALL_SENSORS
PK_CMD_SENSORS_SETUP_57
PK_CMD_SENSOR_VALUES_READ_57
PK_CMD_DASHBOARD_ITEMS_SETUP_57
PK_CMD_SIMPLE_SENSOR_CFG
PK_CMD_PULSE_ENGINE_DEPRECATED
PK_CMD_FAILSAFE_SETTINGS
PK_CMD_POIL_COMMANDS
PK_CMD_RTC_SETTINGS
PK_CMD_SYSTEM_LOG_OPS
PK_CMD_PULSE_ENGINE_V2
PK_CMD_CAN_OPERATIONS
PK_CMD_UNLOCK_OPTION
PK_CMD_MACRO_CREATE
PK_CMD_MACRO_MODIFY
PK_CMD_MACRO_DELETE
PK_CMD_MACRO_SAVE_TO_FLASH
PK_CMD_MACRO_RENAME
PK_CMD_MACRO_TRANSFER
PK_CMD_MACRO_LENGTH_GET
PK_CMD_MACRO_NAME_GET
PK_CMD_MACRO_KEYS_GET
PK_CMD_MACRO_FREE_SPACE_GET
PK_CMD_MACRO_ACTIVE_GET
PK_CMD_RTMODE_SETUP
PK_CMD_RTMODE_PACKET_IO
PK_CMD_UDP_BINARY_REALTIME_CFG
PK_CMD_MULTIPART_PACKET
PK_CMD_PIN_CONFIGURATION
PK_CMD_PIN_KEY_MAPPING
PK_CMD_PIN_KEY_CODES
PK_CMD_PIN_KEY_MODIFIERS
PK_CMD_ENCODER_OPTION_SET
PK_CMD_ENCODER_CHANNELS_SET
PK_CMD_ENCODER_KEYMAP_A_SET2
PK_CMD_ENCODER_KEYMAP_B_SET2
PK_CMD_MATRIX_KEYBOARD_CFG
PK_CMD_PWM_CONFIGURATION
PK_CMD_DEVICE_STATUS_GET
PK_CMD_DEVICE_LOAD_STATUS
PK_CMD_DEVICE_ERROR_STATUS
PK_CMD_ENCODER_LONG_RAW_VALUES_GET
PK_CMD_FAST_ENCODERS_SET
PK_CMD_TICK_COUNTER_GET
PK_CMD_LCD_CONFIGURATION
PK_CMD_LCD_OPERATION
PK_CMD_MATRIX_LED_CONFIGURATION
PK_CMD_MATRIX_LED_UPDATE
PK_CMD_TRIGGERED_INPUT_SETTINGS
PK_CMD_DIGITAL_COUNTERS_VALUES
PK_CMD_DIGITAL_COUNTERS_DIRECTION
PK_CMD_AUX_BUS_SETTINGS
PK_CMD_I2C_COMMUNICATION
PK_CMD_ONEWIRE_COMMUNICATION
PK_CMD_POI2C_COMMUNICATION
PK_CMD_UART_COMMUNICATION
PK_CMD_NETWORK_SETTINGS
PK_CMD_SECURITY_STATUS_GET
PK_CMD_USER_AUTHORISE
PK_CMD_USER_PASSWORD_SET
PK_CMD_MODBUS_SETTINGS
PK_CMD_SPI_COMMUNICATION
PK_CMD_CAN_NODE_COMMANDS
PK_CMD_COSM_SETTINGS
PK_CMD_REBOOT_SYSTEM
PK_CMD_BOOT_CLEAR_MEMORY
PK_CMD_BOOT_BLOCK_OPTIONS
PK_CMD_BOOT_TRANSFER_BLOCK
PK_CMD_BOOT_START_APP
PK_CMD_BOOT_CALC_AND_SAVE_CRC
PK_CMD_BOOT_CLEAR_USER_SETTINGS
PK_CMD_BOOT_CUSTOM_COMMAND1
PK_CMD_BOOT_OEM_COMMAND
PK_CMD_BOOT_OEM_PARAMETERS
Definition at line 18 of file PoKeysLibAsync.h.
PoNET_operations_t
enum PoNET_operations_t
Enumerator
PONET_OP_GET_STATUS
PONET_OP_GET_MODULE_SETTINGS
PONET_OP_GET_FIRMWARE_VERSION
PONET_OP_SET_MODULE_SETTINGS
PONET_OP_CLEAR_MODULE_SETTINGS
PONET_OP_REINITIALIZE
PONET_OP_REINIT_AND_CLEAR
PONET_OP_DEVICE_DISCOVERY
PONET_OP_CHECK_FOR_DEVICES
PONET_OP_GET_MODULE_DATA
PONET_OP_SET_MODULE_DATA
PONET_OP_GET_LIGHT_SENSOR
PONET_OP_SET_PWM_VALUE
PONET_OP_START_BOOTLOADER
PONET_OP_START_PROGRAMMING
PONET_OP_TRANSFER_FIRMWARE_PART
PONET_OP_FINISH_FIRMWARE_TRANSFER
PONET_OP_EXIT_BOOTLOADER
PONET_OP_ACTIVATE_BOOTLOADER
Definition at line 259 of file PoKeysLibAsync.h.
transaction_status_t
enum transaction_status_t
Enumerator
TRANSACTION_PENDING
TRANSACTION_COMPLETED
TRANSACTION_TIMEOUT
TRANSACTION_FAILED
Definition at line 11 of file PoKeysLibAsync.h.
Function Documentation
CreateRequestAsync()
int CreateRequestAsync (sPoKeysDevice * dev, pokeys_command_t cmd, const uint8_t * params, size_t params_len, void * target_ptr, size_t target_size, int(*)(sPoKeysDevice *dev, const uint8_t *response) parser_func)
CreateRequestAsyncWithPayload()
int CreateRequestAsyncWithPayload (sPoKeysDevice * device, pokeys_command_t cmd, const uint8_t * params, size_t params_len, const void * payload, size_t payload_size, pokeys_response_parser_t parser_func)
Prepares an asynchronous PoKeys request with optional payload data after header.
Parameters
device Pointer to PoKeys device
cmd PoKeys command ID (e.g., 0xC4, 0xC5, 0xCE, etc.)
params Optional pointer to up to 4 parameter bytes (NULL if none)
params_len Length of params (max 4 bytes)
payload Optional pointer to payload (e.g., encoder options) to copy starting at byte 8
payload_size Size of payload (must fit into remaining packet space)
parser_func Optional parser function for response (NULL for write-only operations)
Returns
Request ID on success, negative error code on failure
Definition at line 152 of file PoKeysLibAsync.c.
References async_transaction_t::command_sent, i, next_request_id(), async_transaction_t::request_buffer, async_transaction_t::request_id, async_transaction_t::response_parser, async_transaction_t::retries_left, async_transaction_t::status, async_transaction_t::target_ptr, async_transaction_t::target_size, async_transaction_t::timestamp_sent, transaction_alloc(), and TRANSACTION_PENDING.
Referenced by PK_1WireWriteReadStartAsync(), PK_1WireWriteReadStartExAsync(), PK_CANConfigureAsync(), PK_CANRegisterFilterAsync(), PK_CANWriteAsync(), PK_COSMSettingsSetAsync(), PK_EasySensorsSetupSetAsync(), PK_EncoderConfigurationSetAsync(), PK_EncoderValuesSetAsync(), PK_FailsafeSettingsSetAsync(), PK_I2CWriteAndReadStartAsync(), PK_I2CWriteStartAsync(), PK_LCDSetCustomCharactersAsync(), PK_LCDUpdateAsync(), PK_MatrixKBConfigurationSetAsync(), PK_MatrixLEDUpdateAsync(), PK_PEv2_AdditionalParametersSetAsync(), PK_PEv2_AxisConfigurationSetAsync(), PK_PEv2_ExternalOutputsSetAsync(), PK_PEv2_HomingStartAsync(), PK_PEv2_PulseEngineMovePVAsync(), PK_PEv2_PulseEngineSetupAsync(), PK_PoNETSetModuleStatusAsync(), PK_SPITransferAsync(), PK_SPIWriteAsync(), PK_UARTConfigureAsync(), PK_UARTWriteAsync(), PK_UserAuthoriseAsync(), and PK_UserPasswordSetAsync().
PK_AnalogIOGetAsync()
int PK_AnalogIOGetAsync (sPoKeysDevice * device)
Starts async request for analog inputs (CMD 0x3A, param1=1).
Definition at line 516 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice::info, PK_AnalogIOParse(), PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.
Referenced by PK_IOUpdateCycleAsync().
PK_AnalogRCFilterGetAsync()
int PK_AnalogRCFilterGetAsync (sPoKeysDevice * device)
Starts async request for RC analog filter value (CMD 0x38).
Definition at line 543 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice::info, PK_AnalogRCFilterParse(), PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.
PK_AnalogRCFilterSetAsync()
int PK_AnalogRCFilterSetAsync (sPoKeysDevice * device)
Starts async command to set RC analog filter (CMD 0x39).
Definition at line 553 of file PoKeysLibIOAsync.c.
References sPoKeysOtherPeripherals::AnalogRCFilter, CreateRequestAsync(), sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice::info, sPoKeysDevice::otherPeripherals, PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.
PK_CommunicationTestAsync()
int PK_CommunicationTestAsync (sPoKeysDevice * device, uint8_t testCount)
Test device communication and RT timing (async)
Performs communication test by sending ping commands and measuring response times. Useful for RT system validation.
Parameters
device Target device handle
testCount Number of ping tests to perform
Returns
PK_OK on success, error code on failure
Definition at line 265 of file PoKeysLibAdvancedRTAsync.c.
References i, PK_DeviceAliveCheckAsync(), PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, and PK_OK.
PK_DeviceAliveCheckAsync()
int PK_DeviceAliveCheckAsync (sPoKeysDevice * device)
Check if device is alive/responsive (async)
Sends a simple ping command to verify device connectivity. Critical for LinuxCNC HAL to detect communication failures.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 88 of file PoKeysLibDeviceStatusAsync.c.
References CreateRequestAsync(), PK_CMD_READ_DEVICE_DATA, and PK_ERR_NOT_CONNECTED.
Referenced by PK_CommunicationTestAsync(), PK_DeviceStatusFullAsync(), and PK_SystemStatusGetAllAsync().
PK_DeviceConnectionFailureAsync()
int PK_DeviceConnectionFailureAsync (sPoKeysDevice * device)
Handle communication failure (for retry logic)
Should be called when async communication fails to update connection monitoring counters.
Parameters
device Target device handle
Returns
PK_OK always
Definition at line 241 of file PoKeysLibDeviceStatusAsync.c.
References PK_ERR_NOT_CONNECTED.
PK_DeviceConnectionQualityAsync()
int PK_DeviceConnectionQualityAsync (sPoKeysDevice * device, uint8_t * quality)
Check connection quality metrics (async)
Evaluates connection stability based on response times and error rates. Provides quality metrics for adaptive behavior in LinuxCNC.
Parameters
device Target device handle
quality Output pointer for quality percentage (0-100)
Returns
PK_OK on success, error code on failure
Definition at line 199 of file PoKeysLibDeviceStatusAsync.c.
References PK_ERR_GENERIC.
PK_DeviceErrorResetAsync()
int PK_DeviceErrorResetAsync (sPoKeysDevice * device)
Reset device error counters (async)
Clears accumulated error counters and flags. Useful for recovering from transient communication issues.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 146 of file PoKeysLibDeviceStatusAsync.c.
References CreateRequestAsync(), PK_CMD_DEVICE_ERROR_STATUS, and PK_ERR_NOT_CONNECTED.
PK_DeviceErrorStatusAsync()
int PK_DeviceErrorStatusAsync (sPoKeysDevice * device)
Get device error status (async)
Retrieves error flags, communication error count, and last error code. Essential for diagnostic information in LinuxCNC applications.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 128 of file PoKeysLibDeviceStatusAsync.c.
References CreateRequestAsync(), PK_CMD_DEVICE_ERROR_STATUS, and PK_ERR_NOT_CONNECTED.
Referenced by PK_DeviceStatusFullAsync(), and PK_SystemStatusGetAllAsync().
PK_DeviceLoadStatusAsync()
int PK_DeviceLoadStatusAsync (sPoKeysDevice * device)
Get device load status (async)
Retrieves CPU load, USB load, network load, temperature and buffer load. Important for monitoring device performance in real-time applications.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 107 of file PoKeysLibDeviceStatusAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iLoadStatus, sPoKeysDevice::info, PK_CMD_DEVICE_LOAD_STATUS, PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.
Referenced by PK_DeviceStatusFullAsync(), and PK_SystemStatusGetAllAsync().
PK_DeviceStatusFullAsync()
int PK_DeviceStatusFullAsync (sPoKeysDevice * device)
Comprehensive device status check (async)
Combines alive check, load status, and error status into a single efficient monitoring function. Ideal for periodic HAL monitoring.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 166 of file PoKeysLibDeviceStatusAsync.c.
References sPoKeysDevice_Info::iLoadStatus, sPoKeysDevice::info, PK_DeviceAliveCheckAsync(), PK_DeviceErrorStatusAsync(), PK_DeviceLoadStatusAsync(), PK_ERR_NOT_CONNECTED, and PK_OK.
PK_DigitalCounterClearAsync()
int PK_DigitalCounterClearAsync (sPoKeysDevice * device)
Starts async request to clear digital counters (CMD 0x1D).
Definition at line 607 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), and PK_ERR_NOT_CONNECTED.
PK_DigitalCounterGetAsync()
int PK_DigitalCounterGetAsync (sPoKeysDevice * device)
Starts async request to get digital counter values (CMD 0xD8).
Definition at line 588 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, PK_DigitalCounterParse(), PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_IsCounterAvailable(), and PK_OK.
Referenced by PK_IOUpdateCycleAsync().
PK_DigitalCounterGetSelectedAsync()
int PK_DigitalCounterGetSelectedAsync (sPoKeysDevice * device, const uint8_t * pinList, uint8_t count)
Get digital counter values for specific pins only (async)
More efficient than reading all counters when only specific ones are needed.
Parameters
device Target device handle
pinList Array of pin numbers to read
count Number of pins to read
Returns
PK_OK on success, error code on failure
Definition at line 54 of file PoKeysLibAdvancedRTAsync.c.
PK_DigitalCounterParse()
int PK_DigitalCounterParse (sPoKeysDevice * device, const uint8_t * response)
Parser for digital counter values (CMD 0xD8).
Definition at line 572 of file PoKeysLibIOAsync.c.
References sPoKeysPinData::DigitalCounterValue, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice::info, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_ERR_NOT_SUPPORTED, PK_IsCounterAvailable(), PK_OK, and sPoKeysDevice::request.
Referenced by PK_DigitalCounterGetAsync().
PK_DigitalInputGetSingleAsync()
int PK_DigitalInputGetSingleAsync (sPoKeysDevice * device, uint8_t pinIndex)
Get a single digital input pin state (async)
Reads all digital inputs but provides callback for single pin monitoring.
Parameters
device Target device handle
pinIndex Pin number to monitor
Returns
PK_OK on success, error code on failure
Definition at line 888 of file PoKeysLibIOAsync.c.
References sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, PK_DigitalIOGetAsync(), PK_ERR_GENERIC, and PK_ERR_NOT_CONNECTED.
PK_DigitalIOGetAsync()
int PK_DigitalIOGetAsync (sPoKeysDevice * device)
Asynchronously requests digital IO input values.
Definition at line 465 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), PK_DigitalIOGetParse(), and PK_ERR_NOT_CONNECTED.
PK_DigitalIOSetGetAsync()
int PK_DigitalIOSetGetAsync (sPoKeysDevice * device)
Combined Set and Get digital IO in one async call.
Definition at line 474 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysPinData::DigitalValueSet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_DigitalIOGetParse(), PK_ERR_NOT_CONNECTED, sPoKeysPinData::preventUpdate, and sPoKeysDevice::request.
Referenced by PK_EmergencyStopAllAsync(), and PK_IOUpdateCycleAsync().
PK_DigitalOutputSetMultipleAsync()
int PK_DigitalOutputSetMultipleAsync (sPoKeysDevice * device, const uint8_t * pinList, const uint8_t * valueList, uint8_t count)
Set multiple digital outputs in a single efficient operation (async)
Updates only specified pins without affecting others. More efficient than updating all pins when only a few need changes.
Parameters
device Target device handle
pinList Array of pin numbers to update
valueList Array of values corresponding to pins
count Number of pins to update
Returns
PK_OK on success, error code on failure
Definition at line 27 of file PoKeysLibAdvancedRTAsync.c.
PK_DigitalOutputSetSingleAsync()
int PK_DigitalOutputSetSingleAsync (sPoKeysDevice * device, uint8_t pinIndex, uint8_t value)
Set a single digital output pin (async)
Convenience function to set individual digital output without affecting others. Useful for discrete control operations.
Parameters
device Target device handle
pinIndex Pin number (0-based)
value Output state (0 or 1)
Returns
PK_OK on success, error code on failure
Definition at line 868 of file PoKeysLibIOAsync.c.
References sPoKeysPinData::DigitalValueSet, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_DigitalIOSetGetAsync(), PK_ERR_GENERIC, and PK_ERR_NOT_CONNECTED.
PK_DigitalOutputToggleAsync()
int PK_DigitalOutputToggleAsync (sPoKeysDevice * device, uint8_t pinIndex)
Toggle a digital output pin (async)
Convenience function to toggle the state of a digital output pin.
Parameters
device Target device handle
pinIndex Pin number (0-based)
Returns
PK_OK on success, error code on failure
Definition at line 905 of file PoKeysLibIOAsync.c.
References sPoKeysPinData::DigitalValueSet, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_DigitalIOSetGetAsync(), PK_ERR_GENERIC, and PK_ERR_NOT_CONNECTED.
PK_EmergencyStopAllAsync()
int PK_EmergencyStopAllAsync (sPoKeysDevice * device)
Emergency stop all motion and outputs (async)
Immediately stops all motion, disables PWM outputs, and sets all digital outputs to safe state. Critical for emergency situations.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 223 of file PoKeysLibAdvancedRTAsync.c.
References sPoKeysPinData::DigitalValueSet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPulseEnginev2, sPoKeysDevice::PEv2, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_DigitalIOSetGetAsync(), PK_ERR_NOT_CONNECTED, PK_OK, PK_PEv2_StatusGetAsync(), PK_PinCap_digitalOutput, PK_PWMUpdateAsync(), sPoKeysPEv2::PulseEngineState, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, and sPoKeysPWM::PWMenabledChannels.
PK_EncoderAllResetAsync()
int PK_EncoderAllResetAsync (sPoKeysDevice * device)
Reset all encoders' raw values asynchronously.
Convenience wrapper for resetting all available encoders.
Parameters
device Pointer to PoKeys device structure
Returns
PK_OK on success, error code on failure
Definition at line 617 of file PoKeysLibEncodersAsync.c.
References i, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice::info, PK_EncoderRawValueResetAsync(), and PK_ERR_NOT_CONNECTED.
PK_EncoderRawValueResetAsync()
int PK_EncoderRawValueResetAsync (sPoKeysDevice * device, uint32_t encoderMask)
Reset encoder raw values asynchronously (command 0x1A).
This function implements the missing encoder reset functionality that exists in the PoKeys protocol but was not previously implemented. This is critical for LinuxCNC compatibility where encoder reset is commonly needed.
Parameters
device Pointer to PoKeys device structure
encoderMask Bitmask specifying which encoders to reset (bit 0 = encoder 0, etc.)
Returns
PK_OK on success, error code on failure
Definition at line 574 of file PoKeysLibEncodersAsync.c.
References CreateRequestAsync(), PK_CMD_ENCODER_RAW_VALUE_RESET, and PK_ERR_NOT_CONNECTED.
Referenced by PK_EncoderAllResetAsync(), and PK_EncoderSingleResetAsync().
PK_EncoderSingleResetAsync()
int PK_EncoderSingleResetAsync (sPoKeysDevice * device, uint8_t encoderIndex)
Reset a single encoder's raw value asynchronously.
Convenience wrapper for resetting a single encoder.
Parameters
device Pointer to PoKeys device structure
encoderIndex Index of encoder to reset (0-based)
Returns
PK_OK on success, error code on failure
Definition at line 600 of file PoKeysLibEncodersAsync.c.
References sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice::info, PK_EncoderRawValueResetAsync(), PK_ERR_GENERIC, and PK_ERR_NOT_CONNECTED.
PK_IOUpdateCycleAsync()
int PK_IOUpdateCycleAsync (sPoKeysDevice * device)
Perform complete IO update cycle (async)
Combines all common IO operations into a single efficient batch:
Digital IO set/get
Analog input reading
PWM updates
Counter reading
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 173 of file PoKeysLibAdvancedRTAsync.c.
References i, sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice::info, PK_AnalogIOGetAsync(), PK_DigitalCounterGetAsync(), PK_DigitalIOSetGetAsync(), PK_EncoderValuesGetAsync(), PK_ERR_NOT_CONNECTED, PK_OK, PK_PWMUpdateAsync(), sPoKeysDevice::PWM, and sPoKeysPWM::PWMenabledChannels.
PK_PEv2_AdditionalParametersGetAsync()
int PK_PEv2_AdditionalParametersGetAsync (sPoKeysDevice * device)
Definition at line 152 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsync(), PEV2_CMD_CONFIGURE_MISC, PK_CMD_PULSE_ENGINE_V2, and PK_ERR_NOT_CONNECTED.
PK_PEv2_AdditionalParametersSetAsync()
int PK_PEv2_AdditionalParametersSetAsync (sPoKeysDevice * device)
Definition at line 162 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsyncWithPayload(), sPoKeysPEv2::EmergencyInputPin, sPoKeysDevice::PEv2, PEV2_CMD_CONFIGURE_MISC, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_PEv2_AxisConfigurationGetAsync()
int PK_PEv2_AxisConfigurationGetAsync (sPoKeysDevice * device)
Definition at line 173 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsync(), sPoKeysPEv2::param1, sPoKeysDevice::PEv2, PEV2_CMD_GET_AXIS_CONFIGURATION, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, and PK_ERR_PARAMETER.
PK_PEv2_AxisConfigurationSetAsync()
int PK_PEv2_AxisConfigurationSetAsync (sPoKeysDevice * device)
Definition at line 184 of file PoKeysLibPulseEngine_v2Async.c.
References sPoKeysPEv2::AxesConfig, sPoKeysPEv2::AxesSwitchConfig, sPoKeysPEv2::AxisEnableOutputPins, sPoKeysPEv2::AxisSignalOptions, CreateRequestAsyncWithPayload(), sPoKeysPEv2::FilterHomeSwitch, sPoKeysPEv2::FilterLimitMSwitch, sPoKeysPEv2::FilterLimitPSwitch, sPoKeysPEv2::FilterProbeInput, sPoKeysPEv2::HomeBackOffDistance, sPoKeysPEv2::HomingAlgorithm, sPoKeysPEv2::HomingReturnSpeed, sPoKeysPEv2::HomingSpeed, sPoKeysPEv2::InvertAxisEnable, sPoKeysPEv2::MaxAcceleration, sPoKeysPEv2::MaxDecceleration, sPoKeysPEv2::MaxSpeed, sPoKeysPEv2::MPGjogDivider, sPoKeysPEv2::MPGjogEncoder, sPoKeysPEv2::MPGjogMultiplier, sPoKeysPEv2::param1, sPoKeysDevice::PEv2, PEV2_CMD_SET_AXIS_CONFIGURATION, sPoKeysPEv2::PinHomeSwitch, sPoKeysPEv2::PinLimitMSwitch, sPoKeysPEv2::PinLimitPSwitch, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, SendRequestAsync(), sPoKeysPEv2::SoftLimitMaximum, and sPoKeysPEv2::SoftLimitMinimum.
PK_PEv2_ExternalOutputsSetAsync()
int PK_PEv2_ExternalOutputsSetAsync (sPoKeysDevice * device)
Definition at line 263 of file PoKeysLibPulseEngine_v2Async.c.
PK_PEv2_HomingStartAsync()
int PK_PEv2_HomingStartAsync (sPoKeysDevice * device)
Definition at line 252 of file PoKeysLibPulseEngine_v2Async.c.
PK_PEv2_PulseEngineMovePVAsync()
int PK_PEv2_PulseEngineMovePVAsync (sPoKeysDevice * device)
Definition at line 222 of file PoKeysLibPulseEngine_v2Async.c.
PK_PEv2_PulseEngineSetupAsync()
int PK_PEv2_PulseEngineSetupAsync (sPoKeysDevice * device)
Definition at line 134 of file PoKeysLibPulseEngine_v2Async.c.
References sPoKeysPEv2::AxisEnabledStatesMask, sPoKeysPEv2::ChargePumpEnabled, CreateRequestAsyncWithPayload(), sPoKeysPEv2::EmergencySwitchPolarity, sPoKeysDevice::PEv2, PEV2_CMD_SETUP, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineBufferSize, sPoKeysPEv2::PulseEngineEnabled, sPoKeysPEv2::PulseGeneratorType, and SendRequestAsync().
PK_PEv2_Status2GetAsync()
int PK_PEv2_Status2GetAsync (sPoKeysDevice * device)
Definition at line 124 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsync(), PEV2_CMD_GET_STATUS2, PK_CMD_PULSE_ENGINE_V2, and PK_ERR_NOT_CONNECTED.
PK_PEv2_StatusGetAsync()
int PK_PEv2_StatusGetAsync (sPoKeysDevice * device)
Definition at line 107 of file PoKeysLibPulseEngine_v2Async.c.
PK_PinConfigurationGetAsync()
int PK_PinConfigurationGetAsync (sPoKeysDevice * device)
Definition at line 291 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iTriggeredKeyMapping, PK_ERR_NOT_CONNECTED, PK_OK, PK_ParsePinFunctionsResponse(), PK_PinCounterConfigurationParse(), PK_PinKeyMappingCodesParse(), PK_PinKeyMappingModifiersParse(), PK_PinKeyMappingTypeParse(), PK_PinTriggeredDownKeyCodeParse(), PK_PinTriggeredDownKeyModifierParse(), PK_PinTriggeredUpKeyCodeParse(), and PK_PinTriggeredUpKeyModifierParse().
PK_PinConfigurationSetAsync()
int PK_PinConfigurationSetAsync (sPoKeysDevice * device)
Sets all pin configuration fields asynchronously.
Definition at line 342 of file PoKeysLibIOAsync.c.
References sPoKeysPinData::CounterOptions, CreateRequestAsync(), sPoKeysPinData::DigitalValueSet, sPoKeysPinData::downKeyCodeMacroID, sPoKeysPinData::downKeyModifier, i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iTriggeredKeyMapping, sPoKeysPinData::KeyCodeMacroID, sPoKeysPinData::KeyModifier, sPoKeysPinData::MappingType, sPoKeysPinData::PinCap_invertPin, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_OK, PK_PinCap_digitalInput, PK_PinCap_digitalOutput, PK_PinCap_invertPin, PK_PinCap_triggeredInput, sPoKeysPinData::upKeyCodeMacroID, and sPoKeysPinData::upKeyModifier.
PK_PoNETDeviceDiscoveryAsync()
int PK_PoNETDeviceDiscoveryAsync (sPoKeysDevice * device)
Definition at line 87 of file PoKeysLibPoNETAsyncEnhanced.c.
References CreateRequestAsync(), PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_DEVICE_DISCOVERY, and SendRequestAsync().
PK_PoNETGetModuleLightAsync()
int PK_PoNETGetModuleLightAsync (sPoKeysDevice * device)
Definition at line 127 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_GET_LIGHT_SENSOR, and sPoKeysDevice::PoNETmodule.
Referenced by PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETGetModuleLightRequestAsync()
int PK_PoNETGetModuleLightRequestAsync (sPoKeysDevice * device)
Definition at line 116 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_GET_LIGHT_SENSOR, sPoKeysDevice::PoNETmodule, and SendRequestAsync().
Referenced by PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETGetModuleSettingsAsync()
int PK_PoNETGetModuleSettingsAsync (sPoKeysDevice * device)
Definition at line 57 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_GET_MODULE_SETTINGS, and sPoKeysDevice::PoNETmodule.
Referenced by PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETGetModuleStatusAsync()
int PK_PoNETGetModuleStatusAsync (sPoKeysDevice * device)
Definition at line 80 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, and PONET_OP_GET_MODULE_DATA.
Referenced by PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETGetModuleStatusRequestAsync()
int PK_PoNETGetModuleStatusRequestAsync (sPoKeysDevice * device)
Definition at line 69 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_GET_MODULE_DATA, sPoKeysDevice::PoNETmodule, and SendRequestAsync().
Referenced by PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETGetPoNETStatusAsync()
int PK_PoNETGetPoNETStatusAsync (sPoKeysDevice * device)
Definition at line 46 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, and PONET_OP_GET_STATUS.
PK_PoNETKbd48CNCBrightnessSetAsync()
int PK_PoNETKbd48CNCBrightnessSetAsync (sPoKeysDevice * device, uint8_t brightness)
Definition at line 75 of file PoKeysLibPoNETAsyncEnhanced.c.
References PK_ERR_NOT_CONNECTED, PK_PoNETSetModulePWMAsync(), sPoKeysDevice::PoNETmodule, and sPoNETmodule::PWMduty.
PK_PoNETKbd48CNCLEDSetPatternAsync()
int PK_PoNETKbd48CNCLEDSetPatternAsync (sPoKeysDevice * device, uint8_t pattern[6])
Definition at line 63 of file PoKeysLibPoNETAsyncEnhanced.c.
References PK_ERR_GENERIC, PK_PoNETSetModuleStatusAsync(), sPoKeysDevice::PoNETmodule, and sPoNETmodule::statusOut.
PK_PoNETKbd48CNCUpdateCycleAsync()
int PK_PoNETKbd48CNCUpdateCycleAsync (sPoKeysDevice * device)
Definition at line 18 of file PoKeysLibPoNETAsyncEnhanced.c.
References PK_ERR_NOT_CONNECTED, PK_OK, PK_PoNETGetModuleLightAsync(), PK_PoNETGetModuleLightRequestAsync(), PK_PoNETGetModuleSettingsAsync(), PK_PoNETGetModuleStatusAsync(), PK_PoNETGetModuleStatusRequestAsync(), PK_PoNETSetModulePWMAsync(), and PK_PoNETSetModuleStatusAsync().
PK_PoNETModuleReinitializeAsync()
int PK_PoNETModuleReinitializeAsync (sPoKeysDevice * device, uint8_t moduleID)
Definition at line 99 of file PoKeysLibPoNETAsyncEnhanced.c.
References CreateRequestAsync(), PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_REINITIALIZE, and SendRequestAsync().
PK_PoNETSetModulePWMAsync()
int PK_PoNETSetModulePWMAsync (sPoKeysDevice * device)
Definition at line 104 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_SET_PWM_VALUE, sPoKeysDevice::PoNETmodule, sPoNETmodule::PWMduty, and SendRequestAsync().
Referenced by PK_PoNETKbd48CNCBrightnessSetAsync(), and PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETSetModuleStatusAsync()
int PK_PoNETSetModuleStatusAsync (sPoKeysDevice * device)
Definition at line 91 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsyncWithPayload(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_SET_MODULE_DATA, sPoKeysDevice::PoNETmodule, SendRequestAsync(), and sPoNETmodule::statusOut.
Referenced by PK_PoNETKbd48CNCLEDSetPatternAsync(), and PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PWMConfigurationGetAsync()
int PK_PWMConfigurationGetAsync (sPoKeysDevice * device)
Starts async request to get PWM configuration (CMD 0xCB, param1=0)
Starts async request to get PWM configuration (CMD 0xCB, param1=0)
Retrieves current PWM period, enabled channels, and duty cycles. Essential for reading back current PWM state in LinuxCNC.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 670 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), PK_ERR_NOT_CONNECTED, and PK_PWMConfigurationParse().
PK_PWMConfigurationSetAsync()
int PK_PWMConfigurationSetAsync (sPoKeysDevice * device)
Starts async command to configure PWM duty cycle and period (CMD 0xCB).
Starts async command to configure PWM duty cycle and period (CMD 0xCB).
Configures PWM period and enabled channels. This is typically done during initialization and when changing PWM frequency.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 615 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), hal_adcout_t::enable, hal_adcout_getscaledvalue(), hal_float_t, sPoKeysPWM::max_Voltage, PK_ERR_NOT_CONNECTED, sPoKeysDevice::PWM, sPoKeysPWM::PWManalogOutputs, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
PK_PWMConfigurationSetDirectlyAsync()
int PK_PWMConfigurationSetDirectlyAsync (sPoKeysDevice * device, uint32_t PWMperiod, uint8_t * enabledChannels)
Set PWM configuration directly with specified parameters (async)
Directly configures PWM with given period and enabled channels without using device structure values. Useful for direct control applications.
Parameters
device Target device handle
PWMperiod PWM period value
enabledChannels Array of 6 enabled channel flags (1=enabled, 0=disabled)
Returns
PK_OK on success, error code on failure
Set PWM configuration directly with specified parameters (async)
Convenience function to set PWM period and enabled channels in one call. Useful for initialization sequences.
Parameters
device Target device handle
PWMperiod PWM period in clock ticks
enabledChannels Array of 6 enabled channel flags
Returns
PK_OK on success, error code on failure
Definition at line 719 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), i, sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_ERR_GENERIC, PK_ERR_NOT_SUPPORTED, PK_ERR_PARAMETER, PK_PWMConfigurationSetAsync(), sPoKeysDevice::PWM, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
PK_PWMGetPinAssignmentsAsync()
int PK_PWMGetPinAssignmentsAsync (sPoKeysDevice * device)
Get PWM pin assignments (async)
Retrieves which pins are assigned to PWM outputs. Important for LinuxCNC pin mapping and diagnostics.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Retrieves which physical pins are assigned to PWM channels. Important for LinuxCNC configuration and diagnostics.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 851 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_FillPWMPinNumbers(), PK_OK, and PK_PWMPinAssignmentsParse().
PK_PWMSetSingleChannelAsync()
int PK_PWMSetSingleChannelAsync (sPoKeysDevice * device, uint8_t channel, uint32_t dutyCycle)
Set single PWM channel duty cycle (async)
Updates a single PWM channel without affecting others. Optimized for individual channel control.
Parameters
device Target device handle
channel PWM channel (0-5)
dutyCycle Duty cycle value
Returns
PK_OK on success, error code on failure
Updates a single PWM channel without affecting others. Efficient for applications that need to update individual channels.
Parameters
device Target device handle
channel PWM channel number (0-5)
dutyCycle Duty cycle value
Returns
PK_OK on success, error code on failure
Definition at line 795 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_CMD_PWM_CONFIGURATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_PARAMETER, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
PK_PWMUpdateAsync()
int PK_PWMUpdateAsync (sPoKeysDevice * device)
Starts async command to update PWM values only (CMD 0xCB, param1=1, param2=1).
Starts async command to update PWM values only (CMD 0xCB, param1=1, param2=1).
Updates duty cycles for all PWM channels without changing period. This is the most frequently used PWM function for real-time control.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 680 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), hal_adcout_t::enable, hal_adcout_getscaledvalue(), hal_float_t, sPoKeysPWM::max_Voltage, PK_ERR_NOT_CONNECTED, sPoKeysDevice::PWM, sPoKeysPWM::PWManalogOutputs, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
Referenced by PK_EmergencyStopAllAsync(), and PK_IOUpdateCycleAsync().
PK_PWMUpdateDirectlyAsync()
int PK_PWMUpdateDirectlyAsync (sPoKeysDevice * device, uint32_t * dutyCycles)
Update PWM duty cycles directly (async)
Updates PWM duty cycles with provided values without using device structure. Efficient for real-time PWM control applications.
Parameters
device Target device handle
dutyCycles Array of 6 duty cycle values
Returns
PK_OK on success, error code on failure
Convenience function to update duty cycles from an array. Frequently used in LinuxCNC HAL for real-time PWM updates.
Parameters
device Target device handle
dutyCycles Array of 6 duty cycle values
Returns
PK_OK on success, error code on failure
Definition at line 755 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), i, sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_ERR_GENERIC, PK_ERR_NOT_SUPPORTED, PK_ERR_PARAMETER, PK_PWMUpdateAsync(), sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
PK_PWMUpdateSelectedChannelsAsync()
int PK_PWMUpdateSelectedChannelsAsync (sPoKeysDevice * device, uint8_t channelMask, const uint32_t * dutyCycles)
Set PWM duty cycles for selected channels only (async)
Updates only specified PWM channels without affecting others. Efficient for applications that don't use all 6 PWM channels.
Parameters
device Target device handle
channelMask Bitmask of channels to update (bit 0 = channel 0, etc.)
dutyCycles Array of duty cycle values for enabled channels
Returns
PK_OK on success, error code on failure
Definition at line 83 of file PoKeysLibAdvancedRTAsync.c.
References CreateRequestAsync(), PK_CMD_PWM_CONFIGURATION, PK_ERR_GENERIC, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, and sPoKeysPWM::PWMperiod.
PK_ReceiveAndDispatch()
int PK_ReceiveAndDispatch (sPoKeysDevice * dev)
Receives UDP packets and dispatches them to the correct async transaction.
Parameters
dev Pointer to the PoKeys device structure.
Returns
Number of responses processed, or 0 if none.
Definition at line 251 of file PoKeysLibAsync.c.
PK_SPIConfigureAsync()
int PK_SPIConfigureAsync (sPoKeysDevice * device, uint8_t prescaler, uint8_t frameFormat)
Configure the SPI interface asynchronously (command 0xE5/0x01).
Non-blocking version of PK_SPIConfigure that schedules the request using the async framework.
Parameters
device Pointer to an initialised device structure.
prescaler SPI clock prescaler value.
frameFormat Frame configuration (mode, bit length etc.).
Returns
Request ID on success or negative error code on failure.
Definition at line 27 of file PoKeysLibSPIAsync.c.
References CreateRequestAsync(), PK_CMD_SPI_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_SPIReadAsync()
int PK_SPIReadAsync (sPoKeysDevice * device, uint8_t * buffer, uint8_t dataLength)
Read data from SPI bus asynchronously (command 0xE5/0x03).
Non-blocking version of PK_SPIRead that schedules the read operation. The response data will be available in the device response buffer after PK_ReceiveAndDispatch processes the reply.
Parameters
device Pointer to device structure.
buffer Buffer to receive data (can be NULL for async operation).
dataLength Number of bytes to read.
Returns
Request ID on success or negative error code on failure.
Definition at line 80 of file PoKeysLibSPIAsync.c.
References CreateRequestAsync(), PK_CMD_SPI_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_SPITransferAsync()
int PK_SPITransferAsync (sPoKeysDevice * device, const uint8_t * txBuffer, uint8_t * rxBuffer, uint8_t dataLength, uint8_t pinCS)
Perform SPI write/read transaction asynchronously (command 0xE5/0x04).
Combined write/read operation that transmits data while simultaneously receiving data from the SPI device. This is useful for SPI devices that continuously clock out data during transactions.
Parameters
device Pointer to device structure.
txBuffer Buffer containing data to transmit.
rxBuffer Buffer to receive data (can be NULL for async operation).
dataLength Number of bytes to transfer.
pinCS Chip select pin number.
Returns
Request ID on success or negative error code on failure.
Definition at line 109 of file PoKeysLibSPIAsync.c.
References CreateRequestAsyncWithPayload(), PK_CMD_SPI_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_SPIWriteAsync()
int PK_SPIWriteAsync (sPoKeysDevice * device, const uint8_t * buffer, uint8_t dataLength, uint8_t pinCS)
Write data to SPI bus asynchronously (command 0xE5/0x02).
Non-blocking version of PK_SPIWrite that schedules the write operation using the async framework.
Parameters
device Pointer to device structure.
buffer Data buffer to transmit.
dataLength Number of bytes to transmit (max 54).
pinCS Chip select pin number.
Returns
Request ID on success or negative error code on failure.
Definition at line 53 of file PoKeysLibSPIAsync.c.
References CreateRequestAsyncWithPayload(), PK_CMD_SPI_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_SystemStatusGetAllAsync()
int PK_SystemStatusGetAllAsync (sPoKeysDevice * device)
Get comprehensive system status in one operation (async)
Combines device status, load monitoring, and connection health into a single efficient async operation for system monitoring.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 132 of file PoKeysLibAdvancedRTAsync.c.
References sPoKeysDevice_Info::iLoadStatus, sPoKeysDevice::info, PK_DeviceAliveCheckAsync(), PK_DeviceDataGetAsync(), PK_DeviceErrorStatusAsync(), PK_DeviceLoadStatusAsync(), PK_ERR_NOT_CONNECTED, and PK_OK.
PK_TimeoutAndRetryCheck()
void PK_TimeoutAndRetryCheck (sPoKeysDevice * dev, uint64_t timeout_us)
Enhanced timeout and retry check with exponential backoff and error recovery.
This implementation provides:
Exponential backoff for retries
Better error tracking and recovery
RT-safe operation with minimal overhead
Parameters
dev Pointer to the PoKeys device structure.
timeout_us Base timeout threshold in microseconds per attempt.
Definition at line 313 of file PoKeysLibAsync.c.
SendRequestAsync()
int SendRequestAsync (sPoKeysDevice * dev, uint8_t request_id)
Sends an asynchronous request that was prepared earlier.
Parameters
dev Pointer to the PoKeys device structure.
request_id Request ID of the transaction to send.
Returns
0 on success, negative error code on failure.
Definition at line 219 of file PoKeysLibAsync.c.
References dev, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, get_current_time_us(), async_transaction_t::request_buffer, RTAPI_MSG_ERR, rtapi_print_msg(), async_transaction_t::timestamp_sent, and transaction_find().
Referenced by PK_1WireBusScanContinueAsync(), PK_1WireBusScanStartAsync(), PK_1WireBusScanStopAsync(), PK_1WireStatusSetAsync(), PK_1WireWriteReadStartAsync(), PK_1WireWriteReadStartExAsync(), PK_CANConfigureAsync(), PK_CANFlushAsync(), PK_CANRegisterFilterAsync(), PK_CANWriteAsync(), PK_COSMSettingsSetAsync(), PK_EasySensorsSetupSetAsync(), PK_FailsafeSettingsSetAsync(), PK_I2CBusScanStartAsync(), PK_I2CReadStartAsync(), PK_I2CSetStatusAsync(), PK_I2CWriteAndReadStartAsync(), PK_I2CWriteStartAsync(), PK_LCDConfigurationSetAsync(), PK_LCDSetCustomCharactersAsync(), PK_LCDUpdateAsync(), PK_MatrixKBConfigurationSetAsync(), PK_MatrixLEDConfigurationSetAsync(), PK_MatrixLEDUpdateAsync(), PK_PEv2_AdditionalParametersSetAsync(), PK_PEv2_AxisConfigurationSetAsync(), PK_PEv2_ExternalOutputsSetAsync(), PK_PEv2_HomingStartAsync(), PK_PEv2_PulseEngineMovePVAsync(), PK_PEv2_PulseEngineSetupAsync(), PK_PoNETDeviceDiscoveryAsync(), PK_PoNETGetModuleLightRequestAsync(), PK_PoNETGetModuleStatusRequestAsync(), PK_PoNETModuleReinitializeAsync(), PK_PoNETSetModulePWMAsync(), PK_PoNETSetModuleStatusAsync(), PK_RTCGetAsync(), PK_SPIConfigureAsync(), PK_SPIReadAsync(), PK_SPITransferAsync(), PK_SPIWriteAsync(), PK_UARTConfigureAsync(), PK_UARTWriteAsync(), PK_UserPasswordSetAsync(), and PK_WS2812_UpdateAsync().