LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeyslib/PoKeysLib.h File Reference
PoKeysLib.h File Reference
#include "stdint.h"
Data Structures
struct sPoKeys_PinCapabilities
struct sPoKeysDevice_Info
PoKeys device information (HAL compatible version)
struct sPoKeysPEv2info
struct sPoKeysPEv2
struct sPoPoStepDriverConfig
struct sPoKeysPoStepInterface
struct sPoKeysDevice_Data
struct sPoKeysPinData
struct sPoKeysEncoder
struct sPoKeysPWM
struct sMatrixKeyboard
struct sPoKeysLCD
struct sPoKeysMatrixLED
struct sPoNETmodule
struct sPoILinfo
struct sPoILStack
struct sPoILmemoryChunk
struct sPoILTask
struct sPoILStatus
struct sPoKeysEasySensor
struct sPoKeysCustomSensorUnit
struct sPoKeysRTC
struct sPoKeysCANmsg
struct sPoKeysNetworkDeviceSummary
struct sPoKeysNetworkDeviceInfo
struct sPoKeysOtherPeripherals
struct sPoKeysFailsafeSettings
struct sPoKeysDevice
Macros
#define USE_STD_INT
#define POKEYSDECL
#define ALIGN_TEST(x)
Typedefs
typedef signed char int8_t
typedef short int16_t
typedef int int32_t
typedef unsigned char uint8_t
typedef unsigned short uint16_t
typedef unsigned int uint32_t
typedef long long int64_t
typedef unsigned long long uint64_t
Enumerations
enum ePK_PinCap {
PK_PinCap_pinRestricted = 0 , PK_PinCap_reserved = 1 , PK_PinCap_digitalInput = 2 , PK_PinCap_digitalOutput = 4 ,
PK_PinCap_analogInput = 8 , PK_PinCap_analogOutput = 16 , PK_PinCap_triggeredInput = 32 , PK_PinCap_digitalCounter = 64 ,
PK_PinCap_invertPin = 128 , PK_PinCap_pinRestricted = 0 , PK_PinCap_reserved = 1 , PK_PinCap_digitalInput = 2 ,
PK_PinCap_digitalOutput = 4 , PK_PinCap_analogInput = 8 , PK_PinCap_analogOutput = 16 , PK_PinCap_triggeredInput = 32 ,
PK_PinCap_digitalCounter = 64 , PK_PinCap_invertPin = 128 , PK_PinCap_pinRestricted = 0 , PK_PinCap_reserved = 1 ,
PK_PinCap_digitalInput = 2 , PK_PinCap_digitalOutput = 4 , PK_PinCap_analogInput = 8 , PK_PinCap_analogOutput = 16 ,
PK_PinCap_triggeredInput = 32 , PK_PinCap_digitalCounter = 64 , PK_PinCap_invertPin = 128 , PK_PinCap_pinRestricted = 0 ,
PK_PinCap_reserved = 1 , PK_PinCap_digitalInput = 2 , PK_PinCap_digitalOutput = 4 , PK_PinCap_analogInput = 8 ,
PK_PinCap_analogOutput = 16 , PK_PinCap_triggeredInput = 32 , PK_PinCap_digitalCounter = 64 , PK_PinCap_invertPin = 128
}
enum ePK_AllPinCap {
PK_AllPinCap_digitalInput = 1 , PK_AllPinCap_digitalOutput , PK_AllPinCap_analogInput , PK_AllPinCap_MFanalogInput ,
PK_AllPinCap_analogOutput , PK_AllPinCap_keyboardMapping , PK_AllPinCap_triggeredInput , PK_AllPinCap_digitalCounter ,
PK_AllPinCap_PWMOut , PK_AllPinCap_fastEncoder1A , PK_AllPinCap_fastEncoder1B , PK_AllPinCap_fastEncoder1I ,
PK_AllPinCap_fastEncoder2A , PK_AllPinCap_fastEncoder2B , PK_AllPinCap_fastEncoder2I , PK_AllPinCap_fastEncoder3A ,
PK_AllPinCap_fastEncoder3B , PK_AllPinCap_fastEncoder3I , PK_AllPinCap_ultraFastEncoderA , PK_AllPinCap_ultraFastEncoderB ,
PK_AllPinCap_ultraFastEncoderI , PK_AllPinCap_LCD_E , PK_AllPinCap_LCD_RW , PK_AllPinCap_LCD_RS ,
PK_AllPinCap_LCD_D4 , PK_AllPinCap_LCD_D5 , PK_AllPinCap_LCD_D6 , PK_AllPinCap_LCD_D7 ,
PK_AllPinCap_digitalInput = 1 , PK_AllPinCap_digitalOutput , PK_AllPinCap_analogInput , PK_AllPinCap_MFanalogInput ,
PK_AllPinCap_analogOutput , PK_AllPinCap_keyboardMapping , PK_AllPinCap_triggeredInput , PK_AllPinCap_digitalCounter ,
PK_AllPinCap_PWMOut , PK_AllPinCap_fastEncoder1A , PK_AllPinCap_fastEncoder1B , PK_AllPinCap_fastEncoder1I ,
PK_AllPinCap_fastEncoder2A , PK_AllPinCap_fastEncoder2B , PK_AllPinCap_fastEncoder2I , PK_AllPinCap_fastEncoder3A ,
PK_AllPinCap_fastEncoder3B , PK_AllPinCap_fastEncoder3I , PK_AllPinCap_ultraFastEncoderA , PK_AllPinCap_ultraFastEncoderB ,
PK_AllPinCap_ultraFastEncoderI , PK_AllPinCap_LCD_E , PK_AllPinCap_LCD_RW , PK_AllPinCap_LCD_RS ,
PK_AllPinCap_LCD_D4 , PK_AllPinCap_LCD_D5 , PK_AllPinCap_LCD_D6 , PK_AllPinCap_LCD_D7 ,
PK_AllPinCap_digitalInput = 1 , PK_AllPinCap_digitalOutput , PK_AllPinCap_analogInput , PK_AllPinCap_MFanalogInput ,
PK_AllPinCap_analogOutput , PK_AllPinCap_keyboardMapping , PK_AllPinCap_triggeredInput , PK_AllPinCap_digitalCounter ,
PK_AllPinCap_PWMOut , PK_AllPinCap_fastEncoder1A , PK_AllPinCap_fastEncoder1B , PK_AllPinCap_fastEncoder1I ,
PK_AllPinCap_fastEncoder2A , PK_AllPinCap_fastEncoder2B , PK_AllPinCap_fastEncoder2I , PK_AllPinCap_fastEncoder3A ,
PK_AllPinCap_fastEncoder3B , PK_AllPinCap_fastEncoder3I , PK_AllPinCap_ultraFastEncoderA , PK_AllPinCap_ultraFastEncoderB ,
PK_AllPinCap_ultraFastEncoderI , PK_AllPinCap_LCD_E , PK_AllPinCap_LCD_RW , PK_AllPinCap_LCD_RS ,
PK_AllPinCap_LCD_D4 , PK_AllPinCap_LCD_D5 , PK_AllPinCap_LCD_D6 , PK_AllPinCap_LCD_D7 ,
PK_AllPinCap_digitalInput = 1 , PK_AllPinCap_digitalOutput , PK_AllPinCap_analogInput , PK_AllPinCap_MFanalogInput ,
PK_AllPinCap_analogOutput , PK_AllPinCap_keyboardMapping , PK_AllPinCap_triggeredInput , PK_AllPinCap_digitalCounter ,
PK_AllPinCap_PWMOut , PK_AllPinCap_fastEncoder1A , PK_AllPinCap_fastEncoder1B , PK_AllPinCap_fastEncoder1I ,
PK_AllPinCap_fastEncoder2A , PK_AllPinCap_fastEncoder2B , PK_AllPinCap_fastEncoder2I , PK_AllPinCap_fastEncoder3A ,
PK_AllPinCap_fastEncoder3B , PK_AllPinCap_fastEncoder3I , PK_AllPinCap_ultraFastEncoderA , PK_AllPinCap_ultraFastEncoderB ,
PK_AllPinCap_ultraFastEncoderI , PK_AllPinCap_LCD_E , PK_AllPinCap_LCD_RW , PK_AllPinCap_LCD_RS ,
PK_AllPinCap_LCD_D4 , PK_AllPinCap_LCD_D5 , PK_AllPinCap_LCD_D6 , PK_AllPinCap_LCD_D7
}
enum ePK_DeviceTypeMask {
PK_DeviceMask_Bootloader = (1<<0) , PK_DeviceMask_Bootloader55 = (1<<1) , PK_DeviceMask_Bootloader56 = (1<<2) , PK_DeviceMask_Bootloader56U = (1<<3) ,
PK_DeviceMask_Bootloader56E = (1<<4) , PK_DeviceMask_Bootloader58 = (1<<5) , PK_DeviceMask_55 = (1<<10) , PK_DeviceMask_55v1 = (1<<11) ,
PK_DeviceMask_55v2 = (1<<12) , PK_DeviceMask_55v3 = (1<<13) , PK_DeviceMask_56 = (1<<14) , PK_DeviceMask_56U = (1<<15) ,
PK_DeviceMask_56E = (1<<16) , PK_DeviceMask_27 = (1<<17) , PK_DeviceMask_27U = (1<<18) , PK_DeviceMask_27E = (1<<19) ,
PK_DeviceMask_57 = (1<<20) , PK_DeviceMask_57U = (1<<24) , PK_DeviceMask_57E = (1<<25) , PK_DeviceMask_57CNC = (1<<26) ,
PK_DeviceMask_57CNCdb25 = (1<<27) , PK_DeviceMask_57Utest = (1<<28) , PK_DeviceMask_57CNCpro4x25 = (1<<29) , PK_DeviceMask_58 = (1<<21) ,
PK_DeviceMask_PoPLC58 = (1<<22) , PK_DeviceMask_PoKeys16RF = (1<<23) , PK_DeviceMask_Bootloader = (1<<0) , PK_DeviceMask_Bootloader55 = (1<<1) ,
PK_DeviceMask_Bootloader56 = (1<<2) , PK_DeviceMask_Bootloader56U = (1<<3) , PK_DeviceMask_Bootloader56E = (1<<4) , PK_DeviceMask_Bootloader58 = (1<<5) ,
PK_DeviceMask_55 = (1<<10) , PK_DeviceMask_55v1 = (1<<11) , PK_DeviceMask_55v2 = (1<<12) , PK_DeviceMask_55v3 = (1<<13) ,
PK_DeviceMask_56 = (1<<14) , PK_DeviceMask_56U = (1<<15) , PK_DeviceMask_56E = (1<<16) , PK_DeviceMask_27 = (1<<17) ,
PK_DeviceMask_27U = (1<<18) , PK_DeviceMask_27E = (1<<19) , PK_DeviceMask_57 = (1<<20) , PK_DeviceMask_57U = (1<<24) ,
PK_DeviceMask_57E = (1<<25) , PK_DeviceMask_57CNC = (1<<26) , PK_DeviceMask_57CNCdb25 = (1<<27) , PK_DeviceMask_57Utest = (1<<28) ,
PK_DeviceMask_57CNCpro4x25 = (1<<29) , PK_DeviceMask_58 = (1<<21) , PK_DeviceMask_PoPLC58 = (1<<22) , PK_DeviceMask_PoKeys16RF = (1<<23) ,
PK_DeviceMask_Bootloader = (1<<0) , PK_DeviceMask_Bootloader55 = (1<<1) , PK_DeviceMask_Bootloader56 = (1<<2) , PK_DeviceMask_Bootloader56U = (1<<3) ,
PK_DeviceMask_Bootloader56E = (1<<4) , PK_DeviceMask_Bootloader58 = (1<<5) , PK_DeviceMask_55 = (1<<10) , PK_DeviceMask_55v1 = (1<<11) ,
PK_DeviceMask_55v2 = (1<<12) , PK_DeviceMask_55v3 = (1<<13) , PK_DeviceMask_56 = (1<<14) , PK_DeviceMask_56U = (1<<15) ,
PK_DeviceMask_56E = (1<<16) , PK_DeviceMask_27 = (1<<17) , PK_DeviceMask_27U = (1<<18) , PK_DeviceMask_27E = (1<<19) ,
PK_DeviceMask_57 = (1<<20) , PK_DeviceMask_57U = (1<<24) , PK_DeviceMask_57E = (1<<25) , PK_DeviceMask_57CNC = (1<<26) ,
PK_DeviceMask_57CNCdb25 = (1<<27) , PK_DeviceMask_57Utest = (1<<28) , PK_DeviceMask_57CNCpro4x25 = (1<<29) , PK_DeviceMask_58 = (1<<21) ,
PK_DeviceMask_PoPLC58 = (1<<22) , PK_DeviceMask_PoKeys16RF = (1<<23) , PK_DeviceMask_Bootloader = (1<<0) , PK_DeviceMask_Bootloader55 = (1<<1) ,
PK_DeviceMask_Bootloader56 = (1<<2) , PK_DeviceMask_Bootloader56U = (1<<3) , PK_DeviceMask_Bootloader56E = (1<<4) , PK_DeviceMask_Bootloader58 = (1<<5) ,
PK_DeviceMask_55 = (1<<10) , PK_DeviceMask_55v1 = (1<<11) , PK_DeviceMask_55v2 = (1<<12) , PK_DeviceMask_55v3 = (1<<13) ,
PK_DeviceMask_56 = (1<<14) , PK_DeviceMask_56U = (1<<15) , PK_DeviceMask_56E = (1<<16) , PK_DeviceMask_27 = (1<<17) ,
PK_DeviceMask_27U = (1<<18) , PK_DeviceMask_27E = (1<<19) , PK_DeviceMask_57 = (1<<20) , PK_DeviceMask_57U = (1<<24) ,
PK_DeviceMask_57E = (1<<25) , PK_DeviceMask_57CNC = (1<<26) , PK_DeviceMask_57CNCdb25 = (1<<27) , PK_DeviceMask_57Utest = (1<<28) ,
PK_DeviceMask_57CNCpro4x25 = (1<<29) , PK_DeviceMask_58 = (1<<21) , PK_DeviceMask_PoPLC58 = (1<<22) , PK_DeviceMask_PoKeys16RF = (1<<23)
}
enum ePK_DeviceTypeID {
PK_DeviceID_Bootloader55 = 3 , PK_DeviceID_Bootloader56U = 15 , PK_DeviceID_Bootloader56E = 16 , PK_DeviceID_Bootloader58 = 41 ,
PK_DeviceID_55v1 = 0 , PK_DeviceID_55v2 = 1 , PK_DeviceID_55v3 = 2 , PK_DeviceID_56U = 10 ,
PK_DeviceID_56E = 11 , PK_DeviceID_27U = 20 , PK_DeviceID_27E = 21 , PK_DeviceID_57U = 30 ,
PK_DeviceID_57E = 31 , PK_DeviceID_PoKeys57CNC = 32 , PK_DeviceID_PoKeys57CNCpro4x25 = 33 , PK_DeviceID_PoKeys57CNCdb25 = 38 ,
PK_DeviceID_PoKeys57Utest = 39 , PK_DeviceID_LiniTester = 43 , PK_DeviceID_57U_v0 = 28 , PK_DeviceID_57E_v0 = 29 ,
PK_DeviceID_58EU = 40 , PK_DeviceID_PoPLC58 = 50 , PK_DeviceID_OEM1 = 100 , PK_DeviceID_SerialReader = 101 ,
PK_DeviceID_X15_02_24 = 102 , PK_DeviceID_Bootloader55 = 3 , PK_DeviceID_Bootloader56U = 15 , PK_DeviceID_Bootloader56E = 16 ,
PK_DeviceID_Bootloader58 = 41 , PK_DeviceID_55v1 = 0 , PK_DeviceID_55v2 = 1 , PK_DeviceID_55v3 = 2 ,
PK_DeviceID_56U = 10 , PK_DeviceID_56E = 11 , PK_DeviceID_27U = 20 , PK_DeviceID_27E = 21 ,
PK_DeviceID_57U = 30 , PK_DeviceID_57E = 31 , PK_DeviceID_PoKeys57CNC = 32 , PK_DeviceID_PoKeys57CNCpro4x25 = 33 ,
PK_DeviceID_PoKeys57CNCdb25 = 38 , PK_DeviceID_PoKeys57Utest = 39 , PK_DeviceID_LiniTester = 43 , PK_DeviceID_57U_v0 = 28 ,
PK_DeviceID_57E_v0 = 29 , PK_DeviceID_58EU = 40 , PK_DeviceID_PoPLC58 = 50 , PK_DeviceID_OEM1 = 100 ,
PK_DeviceID_SerialReader = 101 , PK_DeviceID_X15_02_24 = 102 , PK_DeviceID_Bootloader55 = 3 , PK_DeviceID_Bootloader56U = 15 ,
PK_DeviceID_Bootloader56E = 16 , PK_DeviceID_Bootloader58 = 41 , PK_DeviceID_55v1 = 0 , PK_DeviceID_55v2 = 1 ,
PK_DeviceID_55v3 = 2 , PK_DeviceID_56U = 10 , PK_DeviceID_56E = 11 , PK_DeviceID_27U = 20 ,
PK_DeviceID_27E = 21 , PK_DeviceID_57U = 30 , PK_DeviceID_57E = 31 , PK_DeviceID_PoKeys57CNC = 32 ,
PK_DeviceID_PoKeys57CNCpro4x25 = 33 , PK_DeviceID_PoKeys57CNCdb25 = 38 , PK_DeviceID_PoKeys57Utest = 39 , PK_DeviceID_LiniTester = 43 ,
PK_DeviceID_57U_v0 = 28 , PK_DeviceID_57E_v0 = 29 , PK_DeviceID_58EU = 40 , PK_DeviceID_PoPLC58 = 50 ,
PK_DeviceID_OEM1 = 100 , PK_DeviceID_SerialReader = 101 , PK_DeviceID_X15_02_24 = 102 , PK_DeviceID_Bootloader55 = 3 ,
PK_DeviceID_Bootloader56U = 15 , PK_DeviceID_Bootloader56E = 16 , PK_DeviceID_Bootloader58 = 41 , PK_DeviceID_55v1 = 0 ,
PK_DeviceID_55v2 = 1 , PK_DeviceID_55v3 = 2 , PK_DeviceID_56U = 10 , PK_DeviceID_56E = 11 ,
PK_DeviceID_27U = 20 , PK_DeviceID_27E = 21 , PK_DeviceID_57U = 30 , PK_DeviceID_57E = 31 ,
PK_DeviceID_PoKeys57CNC = 32 , PK_DeviceID_PoKeys57CNCpro4x25 = 33 , PK_DeviceID_PoKeys57CNCdb25 = 38 , PK_DeviceID_PoKeys57Utest = 39 ,
PK_DeviceID_LiniTester = 43 , PK_DeviceID_57U_v0 = 28 , PK_DeviceID_57E_v0 = 29 , PK_DeviceID_58EU = 40 ,
PK_DeviceID_PoPLC58 = 50 , PK_DeviceID_OEM1 = 100 , PK_DeviceID_SerialReader = 101 , PK_DeviceID_X15_02_24 = 102
}
enum ePK_DeviceConnectionType {
PK_DeviceType_USBDevice = 0 , PK_DeviceType_NetworkDevice = 1 , PK_DeviceType_FastUSBDevice = 2 , PK_DeviceType_USBDevice = 0 ,
PK_DeviceType_NetworkDevice = 1 , PK_DeviceType_FastUSBDevice = 2 , PK_DeviceType_USBDevice = 0 , PK_DeviceType_NetworkDevice = 1 ,
PK_DeviceType_FastUSBDevice = 2 , PK_DeviceType_USBDevice = 0 , PK_DeviceType_NetworkDevice = 1 , PK_DeviceType_FastUSBDevice = 2
}
enum ePK_DeviceConnectionParam {
PK_ConnectionParam_TCP = 0 , PK_ConnectionParam_UDP = 1 , PK_ConnectionParam_TCP = 0 , PK_ConnectionParam_UDP = 1 ,
PK_ConnectionParam_TCP = 0 , PK_ConnectionParam_UDP = 1 , PK_ConnectionParam_TCP = 0 , PK_ConnectionParam_UDP = 1
}
enum ePK_PEState {
PK_PEState_peSTOPPED = 0 , PK_PEState_peINTERNAL = 1 , PK_PEState_peBUFFER = 2 , PK_PEState_peRUNNING = 3 ,
PK_PEState_peJOGGING = 10 , PK_PEState_peSTOPPING = 11 , PK_PEState_peHOME = 20 , PK_PEState_peHOMING = 21 ,
PK_PEState_pePROBECOMPLETE = 30 , PK_PEState_pePROBE = 31 , PK_PEState_pePROBEERROR = 32 , PK_PEState_peHYBRIDPROBE_STOPPING = 40 ,
PK_PEState_peHYBRIDPROBE_COMPLETE = 41 , PK_PEState_peSTOP_LIMIT = 100 , PK_PEState_peSTOP_EMERGENCY = 101 , PK_PEState_peSTOPPED = 0 ,
PK_PEState_peINTERNAL = 1 , PK_PEState_peBUFFER = 2 , PK_PEState_peRUNNING = 3 , PK_PEState_peJOGGING = 10 ,
PK_PEState_peSTOPPING = 11 , PK_PEState_peHOME = 20 , PK_PEState_peHOMING = 21 , PK_PEState_pePROBECOMPLETE = 30 ,
PK_PEState_pePROBE = 31 , PK_PEState_pePROBEERROR = 32 , PK_PEState_peHYBRIDPROBE_STOPPING = 40 , PK_PEState_peHYBRIDPROBE_COMPLETE = 41 ,
PK_PEState_peSTOP_LIMIT = 100 , PK_PEState_peSTOP_EMERGENCY = 101 , PK_PEState_peSTOPPED = 0 , PK_PEState_peINTERNAL = 1 ,
PK_PEState_peBUFFER = 2 , PK_PEState_peRUNNING = 3 , PK_PEState_peJOGGING = 10 , PK_PEState_peSTOPPING = 11 ,
PK_PEState_peHOME = 20 , PK_PEState_peHOMING = 21 , PK_PEState_pePROBECOMPLETE = 30 , PK_PEState_pePROBE = 31 ,
PK_PEState_pePROBEERROR = 32 , PK_PEState_peHYBRIDPROBE_STOPPING = 40 , PK_PEState_peHYBRIDPROBE_COMPLETE = 41 , PK_PEState_peSTOP_LIMIT = 100 ,
PK_PEState_peSTOP_EMERGENCY = 101 , PK_PEState_peSTOPPED = 0 , PK_PEState_peINTERNAL = 1 , PK_PEState_peBUFFER = 2 ,
PK_PEState_peRUNNING = 3 , PK_PEState_peJOGGING = 10 , PK_PEState_peSTOPPING = 11 , PK_PEState_peHOME = 20 ,
PK_PEState_peHOMING = 21 , PK_PEState_pePROBECOMPLETE = 30 , PK_PEState_pePROBE = 31 , PK_PEState_pePROBEERROR = 32 ,
PK_PEState_peHYBRIDPROBE_STOPPING = 40 , PK_PEState_peHYBRIDPROBE_COMPLETE = 41 , PK_PEState_peSTOP_LIMIT = 100 , PK_PEState_peSTOP_EMERGENCY = 101
}
enum ePK_PEAxisState {
PK_PEAxisState_axSTOPPED = 0 , PK_PEAxisState_axREADY = 1 , PK_PEAxisState_axRUNNING = 2 , PK_PEAxisState_axHOMING_RESETTING = 8 ,
PK_PEAxisState_axHOMING_BACKING_OFF = 9 , PK_PEAxisState_axHOME = 10 , PK_PEAxisState_axHOMINGSTART = 11 , PK_PEAxisState_axHOMINGSEARCH = 12 ,
PK_PEAxisState_axHOMINGBACK = 13 , PK_PEAxisState_axPROBED = 14 , PK_PEAxisState_axPROBESTART = 15 , PK_PEAxisState_axPROBESEARCH = 16 ,
PK_PEAxisState_axERROR = 20 , PK_PEAxisState_axLIMIT = 30 , PK_PEAxisState_axSTOPPED = 0 , PK_PEAxisState_axREADY = 1 ,
PK_PEAxisState_axRUNNING = 2 , PK_PEAxisState_axHOMING_RESETTING = 8 , PK_PEAxisState_axHOMING_BACKING_OFF = 9 , PK_PEAxisState_axHOME = 10 ,
PK_PEAxisState_axHOMINGSTART = 11 , PK_PEAxisState_axHOMINGSEARCH = 12 , PK_PEAxisState_axHOMINGBACK = 13 , PK_PEAxisState_axPROBED = 14 ,
PK_PEAxisState_axPROBESTART = 15 , PK_PEAxisState_axPROBESEARCH = 16 , PK_PEAxisState_axERROR = 20 , PK_PEAxisState_axLIMIT = 30 ,
PK_PEAxisState_axSTOPPED = 0 , PK_PEAxisState_axREADY = 1 , PK_PEAxisState_axRUNNING = 2 , PK_PEAxisState_axHOMING_RESETTING = 8 ,
PK_PEAxisState_axHOMING_BACKING_OFF = 9 , PK_PEAxisState_axHOME = 10 , PK_PEAxisState_axHOMINGSTART = 11 , PK_PEAxisState_axHOMINGSEARCH = 12 ,
PK_PEAxisState_axHOMINGBACK = 13 , PK_PEAxisState_axPROBED = 14 , PK_PEAxisState_axPROBESTART = 15 , PK_PEAxisState_axPROBESEARCH = 16 ,
PK_PEAxisState_axERROR = 20 , PK_PEAxisState_axLIMIT = 30 , PK_PEAxisState_axSTOPPED = 0 , PK_PEAxisState_axREADY = 1 ,
PK_PEAxisState_axRUNNING = 2 , PK_PEAxisState_axHOMING_RESETTING = 8 , PK_PEAxisState_axHOMING_BACKING_OFF = 9 , PK_PEAxisState_axHOME = 10 ,
PK_PEAxisState_axHOMINGSTART = 11 , PK_PEAxisState_axHOMINGSEARCH = 12 , PK_PEAxisState_axHOMINGBACK = 13 , PK_PEAxisState_axPROBED = 14 ,
PK_PEAxisState_axPROBESTART = 15 , PK_PEAxisState_axPROBESEARCH = 16 , PK_PEAxisState_axERROR = 20 , PK_PEAxisState_axLIMIT = 30
}
enum ePK_PEv2_AxisConfig {
PK_AC_ENABLED = (1 << 0) , PK_AC_INVERTED = (1 << 1) , PK_AC_INTERNAL_PLANNER = (1 << 2) , PK_AC_POSITION_MODE = (1 << 3) ,
PK_AC_INVERTED_HOME = (1 << 4) , PK_AC_SOFT_LIMIT_ENABLED = (1 << 5) , PK_AC_FAST_OUTPUT = (1 << 6) , PK_AC_ENABLED_MASKED = (1 << 7) ,
PK_AC_ENABLED = (1 << 0) , PK_AC_INVERTED = (1 << 1) , PK_AC_INTERNAL_PLANNER = (1 << 2) , PK_AC_POSITION_MODE = (1 << 3) ,
PK_AC_INVERTED_HOME = (1 << 4) , PK_AC_SOFT_LIMIT_ENABLED = (1 << 5) , PK_AC_FAST_OUTPUT = (1 << 6) , PK_AC_ENABLED_MASKED = (1 << 7) ,
PK_AC_ENABLED = (1 << 0) , PK_AC_INVERTED = (1 << 1) , PK_AC_INTERNAL_PLANNER = (1 << 2) , PK_AC_POSITION_MODE = (1 << 3) ,
PK_AC_INVERTED_HOME = (1 << 4) , PK_AC_SOFT_LIMIT_ENABLED = (1 << 5) , PK_AC_FAST_OUTPUT = (1 << 6) , PK_AC_ENABLED_MASKED = (1 << 7) ,
PK_AC_ENABLED = (1 << 0) , PK_AC_INVERTED = (1 << 1) , PK_AC_INTERNAL_PLANNER = (1 << 2) , PK_AC_POSITION_MODE = (1 << 3) ,
PK_AC_INVERTED_HOME = (1 << 4) , PK_AC_SOFT_LIMIT_ENABLED = (1 << 5) , PK_AC_FAST_OUTPUT = (1 << 6) , PK_AC_ENABLED_MASKED = (1 << 7)
}
enum ePK_PEv2_AxisSwitchOptions {
PK_ASO_SWITCH_LIMIT_N = (1 << 0) , PK_ASO_SWITCH_LIMIT_P = (1 << 1) , PK_ASO_SWITCH_HOME = (1 << 2) , PK_ASO_SWITCH_COMBINED_LN_H = (1 << 3) ,
PK_ASO_SWITCH_COMBINED_LP_H = (1 << 4) , PK_ASO_SWITCH_INVERT_LIMIT_N = (1 << 5) , PK_ASO_SWITCH_INVERT_LIMIT_P = (1 << 6) , PK_ASO_SWITCH_INVERT_HOME = (1 << 7) ,
PK_ASO_SWITCH_LIMIT_N = (1 << 0) , PK_ASO_SWITCH_LIMIT_P = (1 << 1) , PK_ASO_SWITCH_HOME = (1 << 2) , PK_ASO_SWITCH_COMBINED_LN_H = (1 << 3) ,
PK_ASO_SWITCH_COMBINED_LP_H = (1 << 4) , PK_ASO_SWITCH_INVERT_LIMIT_N = (1 << 5) , PK_ASO_SWITCH_INVERT_LIMIT_P = (1 << 6) , PK_ASO_SWITCH_INVERT_HOME = (1 << 7) ,
PK_ASO_SWITCH_LIMIT_N = (1 << 0) , PK_ASO_SWITCH_LIMIT_P = (1 << 1) , PK_ASO_SWITCH_HOME = (1 << 2) , PK_ASO_SWITCH_COMBINED_LN_H = (1 << 3) ,
PK_ASO_SWITCH_COMBINED_LP_H = (1 << 4) , PK_ASO_SWITCH_INVERT_LIMIT_N = (1 << 5) , PK_ASO_SWITCH_INVERT_LIMIT_P = (1 << 6) , PK_ASO_SWITCH_INVERT_HOME = (1 << 7) ,
PK_ASO_SWITCH_LIMIT_N = (1 << 0) , PK_ASO_SWITCH_LIMIT_P = (1 << 1) , PK_ASO_SWITCH_HOME = (1 << 2) , PK_ASO_SWITCH_COMBINED_LN_H = (1 << 3) ,
PK_ASO_SWITCH_COMBINED_LP_H = (1 << 4) , PK_ASO_SWITCH_INVERT_LIMIT_N = (1 << 5) , PK_ASO_SWITCH_INVERT_LIMIT_P = (1 << 6) , PK_ASO_SWITCH_INVERT_HOME = (1 << 7)
}
enum ePK_PEv2_AxisSignalOptions {
PK_ASO_INVERT_STEP = (1 << 0) , PK_ASO_INVERT_DIRECTION = (1 << 1) , PK_ASO_INVERT_STEP = (1 << 0) , PK_ASO_INVERT_DIRECTION = (1 << 1) ,
PK_ASO_INVERT_STEP = (1 << 0) , PK_ASO_INVERT_DIRECTION = (1 << 1) , PK_ASO_INVERT_STEP = (1 << 0) , PK_ASO_INVERT_DIRECTION = (1 << 1)
}
enum ePK_RETURN_CODES {
PK_OK = 0 , PK_ERR_GENERIC = -1 , PK_ERR_NOT_CONNECTED = -5 , PK_ERR_TRANSFER = -10 ,
PK_ERR_PARAMETER = -20 , PK_ERR_NOT_SUPPORTED = -30 , PK_ERR_CANNOT_CLAIM_USB = -100 , PK_ERR_CANNOT_CONNECT = -101 ,
PK_OK = 0 , PK_ERR_GENERIC = -1 , PK_ERR_NOT_CONNECTED = -5 , PK_ERR_TRANSFER = -10 ,
PK_ERR_PARAMETER = -20 , PK_ERR_NOT_SUPPORTED = -30 , PK_ERR_CANNOT_CLAIM_USB = -100 , PK_ERR_CANNOT_CONNECT = -101 ,
PK_OK = 0 , PK_ERR_GENERIC = -1 , PK_ERR_NOT_CONNECTED = -5 , PK_ERR_TRANSFER = -10 ,
PK_ERR_PARAMETER = -20 , PK_ERR_NOT_SUPPORTED = -30 , PK_ERR_CANNOT_CLAIM_USB = -100 , PK_ERR_CANNOT_CONNECT = -101 ,
PK_OK = 0 , PK_ERR_GENERIC = -1 , PK_ERR_NOT_CONNECTED = -5 , PK_ERR_TRANSFER = -10 ,
PK_ERR_PARAMETER = -20 , PK_ERR_NOT_SUPPORTED = -30 , PK_ERR_CANNOT_CLAIM_USB = -100 , PK_ERR_CANNOT_CONNECT = -101
}
enum ePK_I2C_STATUS {
PK_I2C_STAT_ERR = 0 , PK_I2C_STAT_OK = 1 , PK_I2C_STAT_COMPLETE = 1 , PK_I2C_STAT_IN_PROGRESS = 0x10 ,
PK_I2C_STAT_ERR = 0 , PK_I2C_STAT_OK = 1 , PK_I2C_STAT_COMPLETE = 1 , PK_I2C_STAT_IN_PROGRESS = 0x10 ,
PK_I2C_STAT_ERR = 0 , PK_I2C_STAT_OK = 1 , PK_I2C_STAT_COMPLETE = 1 , PK_I2C_STAT_IN_PROGRESS = 0x10 ,
PK_I2C_STAT_ERR = 0 , PK_I2C_STAT_OK = 1 , PK_I2C_STAT_COMPLETE = 1 , PK_I2C_STAT_IN_PROGRESS = 0x10
}
enum ePK_LCD_MODE {
PK_LCD_MODE_DIRECT = 0 , PK_LCD_MODE_BUFFERED = 1 , PK_LCD_MODE_DIRECT = 0 , PK_LCD_MODE_BUFFERED = 1 ,
PK_LCD_MODE_DIRECT = 0 , PK_LCD_MODE_BUFFERED = 1 , PK_LCD_MODE_DIRECT = 0 , PK_LCD_MODE_BUFFERED = 1
}
Functions
POKEYSDECL int32_t PK_EnumerateUSBDevices (void)
Enumerate PoKeys USB devices.
POKEYSDECL int32_t PK_EnumerateFastUSBDevices (void)
POKEYSDECL int32_t PK_EnumerateNetworkDevices (sPoKeysNetworkDeviceSummary *devices, uint32_t timeout)
Convenience wrapper for discovering all network attached PoKeys devices.
POKEYSDECL int32_t PK_SearchNetworkDevices (sPoKeysNetworkDeviceSummary *devices, uint32_t timeout, uint32_t serialNumberToFind)
Broadcasts a discovery request and collects responses from PoKeys devices.
POKEYSDECL void PK_SetEthernetRetryCountAndTimeout (sPoKeysDevice *device, uint32_t sendRetries, uint32_t readRetries, uint32_t timeout)
POKEYSDECL sPoKeysDevice * PK_ConnectToDevice (uint32_t deviceIndex)
POKEYSDECL sPoKeysDevice * PK_ConnectToDeviceWSerial (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
POKEYSDECL sPoKeysDevice * PK_ConnectToDeviceWSerial_UDP (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
POKEYSDECL sPoKeysDevice * PK_ConnectToPoKeysDevice (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
POKEYSDECL sPoKeysDevice * PK_ConnectToNetworkDevice (sPoKeysNetworkDeviceSummary *device)
POKEYSDECL void PK_DisconnectDevice (sPoKeysDevice *device)
POKEYSDECL int32_t PK_GetCurrentDeviceConnectionType (sPoKeysDevice *device)
Obtain the active connection type for a device.
POKEYSDECL int32_t PK_SaveConfiguration (sPoKeysDevice *device)
Save current configuration to device flash (command 0x50).
POKEYSDECL int32_t PK_ClearConfiguration (sPoKeysDevice *device)
Reset configuration in device flash (command 0x52).
POKEYSDECL int32_t PK_CustomRequest (sPoKeysDevice *device, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Send an arbitrary request to the connected device.
POKEYSDECL int32_t PK_GetDebugValues (sPoKeysDevice *device, int32_t *buffer)
Read internal debug registers (command 0xBB).
POKEYSDECL int32_t PK_SetFastUSBEnableStatus (sPoKeysDevice *device, uint32_t newState)
Enable or disable the fast USB interface (command 0x07).
POKEYSDECL int32_t PK_GetFastUSBEnableStatus (sPoKeysDevice *device, uint32_t *state)
Query fast USB interface status (command 0x07/10).
POKEYSDECL int32_t PK_DeviceNameSet (sPoKeysDevice *device)
Write the device name string (command 0x06/0x01).
POKEYSDECL int32_t PK_CheckPinCapability (sPoKeysDevice *device, uint32_t pin, ePK_AllPinCap cap)
Wrapper for PK_CheckPinCapabilityByTypeID() using a device handle.
POKEYSDECL int32_t PK_CheckPinCapabilityByDevice (uint64_t deviceTypeMask, uint32_t pin, ePK_AllPinCap cap)
Determine if a device class supports a pin capability.
POKEYSDECL int32_t PK_CheckPinCapabilityByTypeID (uint64_t deviceID, uint32_t pin, ePK_AllPinCap cap)
Check capability for a specific device type ID.
POKEYSDECL void PK_CloneDeviceStructure (sPoKeysDevice *original, sPoKeysDevice *destination)
POKEYSDECL void PK_ReleaseDeviceStructure (sPoKeysDevice *device)
POKEYSDECL int32_t PK_DeviceDataGet (sPoKeysDevice *device)
Read device identification and feature set.
POKEYSDECL int32_t PK_DeviceActivation (sPoKeysDevice *device)
Send activation code to the device (command 0x8F/0x01).
POKEYSDECL int32_t PK_DeviceActivationClear (sPoKeysDevice *device)
Clear activation settings (command 0x8F/0xFF).
POKEYSDECL int32_t PK_ReadDeviceLog (sPoKeysDevice *device, uint16_t *logBuffer, int32_t *logEntries)
Retrieve entries from the device event log (command 0x84).
POKEYSDECL int32_t PK_NetworkConfigurationSet (sPoKeysDevice *device)
Write Ethernet configuration block (command 0xE0/10).
POKEYSDECL int32_t PK_PinConfigurationGet (sPoKeysDevice *device)
Read pin configuration from the device (command 0xC0).
POKEYSDECL int32_t PK_PinConfigurationSet (sPoKeysDevice *device)
Write pin configuration to the device (command 0xC0).
POKEYSDECL int32_t PK_EncoderConfigurationGet (sPoKeysDevice *device)
Retrieve encoder configuration from the device.
POKEYSDECL int32_t PK_EncoderConfigurationSet (sPoKeysDevice *device)
Send encoder configuration to the PoKeys device.
POKEYSDECL int32_t PK_EncoderValuesGet (sPoKeysDevice *device)
Read current encoder values from the PoKeys device.
POKEYSDECL int32_t PK_EncoderValuesSet (sPoKeysDevice *device)
Write encoder values to the PoKeys device.
POKEYSDECL int32_t PK_DigitalIOSet (sPoKeysDevice *device)
Set digital output states (command 0xCC/1).
POKEYSDECL int32_t PK_DigitalIOGet (sPoKeysDevice *device)
Read digital input states (command 0xCC/0).
POKEYSDECL int32_t PK_DigitalIOSetGet (sPoKeysDevice *device)
Atomically set digital outputs and read inputs (command 0xCC).
POKEYSDECL int32_t PK_DigitalIOSetSingle (sPoKeysDevice *device, uint8_t pinID, uint8_t pinValue)
Set a single digital output (command 0x40).
POKEYSDECL int32_t PK_DigitalIOGetSingle (sPoKeysDevice *device, uint8_t pinID, uint8_t *pinValue)
Read a single digital pin state (command 0x30).
POKEYSDECL int32_t PK_PoExtBusSet (sPoKeysDevice *device)
POKEYSDECL int32_t PK_PoExtBusGet (sPoKeysDevice *device)
POKEYSDECL int32_t PK_DigitalCounterGet (sPoKeysDevice *device)
Read values of all digital counters (command 0xD8).
POKEYSDECL int32_t PK_DigitalCounterClear (sPoKeysDevice *device)
Reset all digital counters (command 0x1D).
POKEYSDECL int32_t PK_IsCounterAvailable (sPoKeysDevice *device, uint8_t pinID)
Check if a pin supports a counter (command 0xC0/0x01).
POKEYSDECL int32_t PK_IsCounterAvailableByDevice (uint32_t deviceTypeMask, uint8_t pinID)
Check counter support for a device type.
POKEYSDECL int32_t PK_IsCounterAvailableByTypeID (uint32_t deviceTypeID, uint8_t pinID)
Check counter availability by device ID.
POKEYSDECL int32_t PK_AnalogIOGet (sPoKeysDevice *device)
Read all analog input channels (command 0x3A/1).
POKEYSDECL int32_t PK_AnalogIOGetAsArray (sPoKeysDevice *device, uint32_t *buffer)
Retrieve analog inputs into an array.
POKEYSDECL int32_t PK_AnalogRCFilterGet (sPoKeysDevice *device)
Read the analog RC filter setting (command 0x38/0).
POKEYSDECL int32_t PK_AnalogRCFilterSet (sPoKeysDevice *device)
Configure the analog RC filter (command 0x39/0).
POKEYSDECL int32_t PK_MatrixKBConfigurationGet (sPoKeysDevice *device)
POKEYSDECL int32_t PK_MatrixKBConfigurationSet (sPoKeysDevice *device)
POKEYSDECL int32_t PK_MatrixKBStatusGet (sPoKeysDevice *device)
POKEYSDECL int32_t PK_PWMConfigurationSet (sPoKeysDevice *device)
POKEYSDECL int32_t PK_PWMUpdate (sPoKeysDevice *device)
POKEYSDECL int32_t PK_PWMConfigurationGet (sPoKeysDevice *device)
POKEYSDECL int32_t PK_PWMConfigurationSetDirectly (sPoKeysDevice *device, uint32_t PWMperiod, uint8_t *enabledChannels)
POKEYSDECL int32_t PK_PWMUpdateDirectly (sPoKeysDevice *device, uint32_t *dutyCycles)
POKEYSDECL int32_t PK_LCDConfigurationGet (sPoKeysDevice *device)
Retrieve LCD configuration from the device.
POKEYSDECL int32_t PK_LCDConfigurationSet (sPoKeysDevice *device)
Write LCD configuration to the device.
POKEYSDECL int32_t PK_LCDUpdate (sPoKeysDevice *device)
Update LCD display using buffered lines.
POKEYSDECL int32_t PK_LCDSetCustomCharacters (sPoKeysDevice *device)
Upload custom character patterns to the LCD.
POKEYSDECL int32_t PK_LCDChangeMode (sPoKeysDevice *device, uint8_t mode)
Switch LCD operating mode.
POKEYSDECL int32_t PK_LCDInit (sPoKeysDevice *device)
Initialise the LCD controller.
POKEYSDECL int32_t PK_LCDClear (sPoKeysDevice *device)
Clear the LCD display.
POKEYSDECL int32_t PK_LCDMoveCursor (sPoKeysDevice *device, uint8_t row, uint8_t column)
Move the LCD cursor to a specific position.
POKEYSDECL int32_t PK_LCDPrint (sPoKeysDevice *device, uint8_t *text, uint8_t textLen)
Print a string on the LCD.
POKEYSDECL int32_t PK_LCDPutChar (sPoKeysDevice *device, uint8_t character)
Output a single character on the LCD.
POKEYSDECL int32_t PK_LCDEntryModeSet (sPoKeysDevice *device, uint8_t cursorMoveDirection, uint8_t displayShift)
Configure the LCD entry mode register.
POKEYSDECL int32_t PK_LCDDisplayOnOffControl (sPoKeysDevice *device, uint8_t displayOnOff, uint8_t cursorOnOff, uint8_t cursorBlinking)
Control LCD display, cursor and blinking.
POKEYSDECL int32_t PK_MatrixLEDConfigurationSet (sPoKeysDevice *device)
POKEYSDECL int32_t PK_MatrixLEDConfigurationGet (sPoKeysDevice *device)
POKEYSDECL int32_t PK_MatrixLEDUpdate (sPoKeysDevice *device)
POKEYSDECL int32_t PK_PEv2_StatusGet (sPoKeysDevice *device)
Retrieve pulse engine status.
POKEYSDECL int32_t PK_PEv2_Status2Get (sPoKeysDevice *device)
Obtain extended status information.
POKEYSDECL int32_t PK_PEv2_PulseEngineSetup (sPoKeysDevice *device)
Configure the pulse engine parameters.
POKEYSDECL int32_t PK_PEv2_AdditionalParametersGet (sPoKeysDevice *device)
Read miscellaneous pulse engine parameters.
POKEYSDECL int32_t PK_PEv2_AdditionalParametersSet (sPoKeysDevice *device)
Configure miscellaneous pulse engine options.
POKEYSDECL int32_t PK_PEv2_AxisConfigurationGet (sPoKeysDevice *device)
Retrieve configuration for one axis.
POKEYSDECL int32_t PK_PEv2_AxisConfigurationSet (sPoKeysDevice *device)
Send configuration data for one axis.
POKEYSDECL int32_t PK_PEv2_PositionSet (sPoKeysDevice *device)
Set current axis positions.
POKEYSDECL int32_t PK_PEv2_PulseEngineStateSet (sPoKeysDevice *device)
Change the operating state of the pulse engine.
POKEYSDECL int32_t PK_PEv2_PulseEngineMove (sPoKeysDevice *device)
Execute a move using reference positions or speeds.
POKEYSDECL int32_t PK_PEv2_PulseEngineMovePV (sPoKeysDevice *device)
Perform a move in position/velocity mode.
POKEYSDECL int32_t PK_PEv2_ExternalOutputsGet (sPoKeysDevice *device)
Read the state of external outputs.
POKEYSDECL int32_t PK_PEv2_ExternalOutputsSet (sPoKeysDevice *device)
Update relay and open-collector outputs.
POKEYSDECL int32_t PK_PEv2_BufferFill (sPoKeysDevice *device)
Send a portion of the motion buffer (8-bit variant).
POKEYSDECL int32_t PK_PEv2_BufferFill_16 (sPoKeysDevice *device)
Send 16-bit motion buffer entries.
POKEYSDECL int32_t PK_PEv2_BufferFillLarge (sPoKeysDevice *device)
Transfer a large block of 8-bit motion data.
POKEYSDECL int32_t PK_PEv2_BufferFillLarge_16 (sPoKeysDevice *device)
Large transfer of 16-bit motion data.
POKEYSDECL int32_t PK_PEv2_BufferClear (sPoKeysDevice *device)
Clear the motion buffer in the device.
POKEYSDECL int32_t PK_PEv2_PulseEngineReboot (sPoKeysDevice *device)
Reboot the pulse engine firmware.
POKEYSDECL int32_t PK_PEv2_HomingStart (sPoKeysDevice *device)
Begin the homing sequence.
POKEYSDECL int32_t PK_PEv2_HomingFinish (sPoKeysDevice *device)
Finish the homing procedure.
POKEYSDECL int32_t PK_PEv2_ProbingStart (sPoKeysDevice *device)
Start a probing move.
POKEYSDECL int32_t PK_PEv2_ProbingHybridStart (sPoKeysDevice *device)
Start probing with an external controller.
POKEYSDECL int32_t PK_PEv2_ProbingFinish (sPoKeysDevice *device)
Complete the probing cycle and read the result.
POKEYSDECL int32_t PK_PEv2_ProbingFinishSimple (sPoKeysDevice *device)
Finish probing without changing engine state.
POKEYSDECL int32_t PK_PEv2_SyncedPWMSetup (sPoKeysDevice *device, uint8_t enabled, uint8_t srcAxis, uint8_t dstPWMChannel)
Configure synchronized PWM output.
POKEYSDECL int32_t PK_PEv2_SyncOutputsSetup (sPoKeysDevice *device)
Configure synchronized digital outputs.
POKEYSDECL int32_t PK_PEv2_InternalDriversConfigurationGet (sPoKeysDevice *device)
Read configuration of internal motor drivers.
POKEYSDECL int32_t PK_PEv2_InternalDriversConfigurationSet (sPoKeysDevice *device)
Set configuration of internal motor drivers.
POKEYSDECL int32_t PK_PEv2_ThreadingPrepareForTrigger (sPoKeysDevice *device)
Prepare the spindle threading trigger.
POKEYSDECL int32_t PK_PEv2_ThreadingForceTriggerReady (sPoKeysDevice *device)
Force trigger ready state.
POKEYSDECL int32_t PK_PEv2_ThreadingTrigger (sPoKeysDevice *device)
Arm the threading trigger.
POKEYSDECL int32_t PK_PEv2_ThreadingRelease (sPoKeysDevice *device)
Release the threading trigger.
POKEYSDECL int32_t PK_PEv2_ThreadingStatusGet (sPoKeysDevice *device)
Query the status of a threading operation.
POKEYSDECL int32_t PK_PEv2_ThreadingCancel (sPoKeysDevice *device)
Cancel a prepared threading operation.
POKEYSDECL int32_t PK_PEv2_ThreadingSetup (sPoKeysDevice *device, uint8_t sensorMode, uint16_t ticksPerRevolution, uint16_t tagetSpindleRPM, uint16_t filterGainSpeed, uint16_t filterGainPosition)
Configure spindle threading parameters.
POKEYSDECL int32_t PK_PEv2_BacklashCompensationSettings_Get (sPoKeysDevice *device)
Retrieve backlash compensation parameters.
POKEYSDECL int32_t PK_PEv2_BacklashCompensationSettings_Set (sPoKeysDevice *device)
Write backlash compensation parameters.
POKEYSDECL int32_t PK_PoStep_ConfigurationGet (sPoKeysDevice *device)
Get configuration for external PoStep drivers.
POKEYSDECL int32_t PK_PoStep_ConfigurationSet (sPoKeysDevice *device)
Configure external PoStep drivers.
POKEYSDECL int32_t PK_PoStep_StatusGet (sPoKeysDevice *device)
Read status information from PoStep drivers.
POKEYSDECL int32_t PK_PoStep_DriverConfigurationGet (sPoKeysDevice *device)
Read PoStep driver current and mode settings.
POKEYSDECL int32_t PK_PoStep_DriverConfigurationSet (sPoKeysDevice *device)
Write PoStep driver current and mode parameters.
POKEYSDECL int32_t PK_I2CSetStatus (sPoKeysDevice *device, uint8_t activated)
Enable or disable the I\2C interface (command 0xDB/0x01).
POKEYSDECL int32_t PK_I2CGetStatus (sPoKeysDevice *device, uint8_t *activated)
Query whether the I\2C bus is enabled (command 0xDB/0x02).
POKEYSDECL int32_t PK_I2CWriteStart (sPoKeysDevice *device, uint8_t address, uint8_t *buffer, uint8_t iDataLength)
Initiate an I\2C write transaction (command 0xDB/0x10).
POKEYSDECL int32_t PK_I2CWriteAndReadStart (sPoKeysDevice *device, uint8_t address, uint8_t *buffer, uint8_t iDataLengthWrite, uint8_t iDataLengthRead)
Write data and queue a subsequent read (command 0xDB/0x10).
POKEYSDECL int32_t PK_I2CWriteStatusGet (sPoKeysDevice *device, uint8_t *status)
Retrieve the status of the last I\2C write operation (command 0xDB/0x11).
POKEYSDECL int32_t PK_I2CReadStart (sPoKeysDevice *device, uint8_t address, uint8_t iDataLength)
Initiate an I\2C read transaction (command 0xDB/0x20).
POKEYSDECL int32_t PK_I2CReadStatusGet (sPoKeysDevice *device, uint8_t *status, uint8_t *iReadBytes, uint8_t *buffer, uint8_t iMaxBufferLength)
Obtain the result of an I\2C read command (command 0xDB/0x21).
POKEYSDECL int32_t PK_I2CBusScanStart (sPoKeysDevice *device)
Begin scanning the I\2C bus for devices (command 0xDB/0x30).
POKEYSDECL int32_t PK_I2CBusScanGetResults (sPoKeysDevice *device, uint8_t *status, uint8_t *presentDevices, uint8_t iMaxDevices)
Obtain the results of an I\2C bus scan (command 0xDB/0x31).
POKEYSDECL int32_t PK_PoNETGetPoNETStatus (sPoKeysDevice *device)
Read overall PoNET bus status.
POKEYSDECL int32_t PK_PoNETGetModuleSettings (sPoKeysDevice *device)
Retrieve basic information about the selected PoNET module.
POKEYSDECL int32_t PK_PoNETGetModuleStatusRequest (sPoKeysDevice *device)
Request status bytes from the PoNET module.
POKEYSDECL int32_t PK_PoNETGetModuleStatus (sPoKeysDevice *device)
Obtain previously requested module status bytes.
POKEYSDECL int32_t PK_PoNETSetModuleStatus (sPoKeysDevice *device)
Write output status bytes to the PoNET module.
POKEYSDECL int32_t PK_PoNETSetModulePWM (sPoKeysDevice *device)
Set the PWM duty cycle of a PoNET module.
POKEYSDECL int32_t PK_PoNETGetModuleLightRequest (sPoKeysDevice *device)
Request the current value of the module's light sensor.
POKEYSDECL int32_t PK_PoNETGetModuleLight (sPoKeysDevice *device)
Read the light sensor value previously requested.
POKEYSDECL int32_t PK_1WireStatusSet (sPoKeysDevice *device, uint8_t activated)
Enable or disable the 1-wire bus.
POKEYSDECL int32_t PK_1WireStatusGet (sPoKeysDevice *device, uint8_t *activated)
Query the 1-wire activation status.
POKEYSDECL int32_t PK_1WireWriteReadStart (sPoKeysDevice *device, uint8_t WriteCount, uint8_t ReadCount, uint8_t *data)
Start a reset/write/read transaction on the 1-wire bus.
POKEYSDECL int32_t PK_1WireWriteReadStartEx (sPoKeysDevice *device, uint8_t pinID, uint8_t WriteCount, uint8_t ReadCount, uint8_t *data)
Start a 1-wire transaction on a specific pin.
POKEYSDECL int32_t PK_1WireReadStatusGet (sPoKeysDevice *device, uint8_t *readStatus, uint8_t *ReadCount, uint8_t *data)
Retrieve data from the previous 1-wire read operation.
POKEYSDECL int32_t PK_1WireBusScanStart (sPoKeysDevice *device, uint8_t pinID)
Begin scanning the 1-wire bus for devices.
POKEYSDECL int32_t PK_1WireBusScanGetResults (sPoKeysDevice *device, uint8_t *operationStatus, uint8_t *scanResult, uint8_t *deviceROM)
Obtain status and results of a 1-wire bus scan.
POKEYSDECL int32_t PK_1WireBusScanContinue (sPoKeysDevice *device)
Continue a previously started 1-wire bus scan.
POKEYSDECL int32_t PK_1WireBusScanStop (sPoKeysDevice *device)
Stop an ongoing 1-wire bus scan.
POKEYSDECL int32_t PK_EasySensorsSetupGet (sPoKeysDevice *device)
Read EasySensors configuration for all channels (command 0x76).
POKEYSDECL int32_t PK_EasySensorsSetupSet (sPoKeysDevice *device)
Write EasySensors configuration (command 0x76 write).
POKEYSDECL int32_t PK_EasySensorsValueGetAll (sPoKeysDevice *device)
Read all EasySensor values (command 0x77).
POKEYSDECL int32_t PK_FailsafeSettingsGet (sPoKeysDevice *device)
Read failsafe configuration from the device (command 0x81).
POKEYSDECL int32_t PK_FailsafeSettingsSet (sPoKeysDevice *device)
Write failsafe configuration to the device (command 0x81).
POKEYSDECL int32_t PK_SPIConfigure (sPoKeysDevice *device, uint8_t prescaler, uint8_t frameFormat)
Configure the SPI interface of a PoKeys device (command 0xE5/0x01).
POKEYSDECL int32_t PK_SPIWrite (sPoKeysDevice *device, uint8_t *buffer, uint8_t iDataLength, uint8_t pinCS)
Transmit data over the SPI interface (command 0xE5/0x10).
POKEYSDECL int32_t PK_SPIRead (sPoKeysDevice *device, uint8_t *buffer, uint8_t iDataLength)
Receive data from the SPI interface (command 0xE5/0x20).
POKEYSDECL int32_t PK_PoILGetState (sPoKeysDevice *device)
POKEYSDECL int32_t PK_PoILSetCoreState (sPoKeysDevice *device, uint16_t state)
POKEYSDECL int32_t PK_PoILSetMasterEnable (sPoKeysDevice *device, uint8_t masterEnable)
POKEYSDECL int32_t PK_PoILResetCore (sPoKeysDevice *device)
POKEYSDECL int32_t PK_PoILSetDebugMode (sPoKeysDevice *device, uint8_t debugMode, uint16_t breakpoint)
POKEYSDECL int32_t PK_PoILReadMemory (sPoKeysDevice *device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t *dest)
POKEYSDECL int32_t PK_PoILWriteMemory (sPoKeysDevice *device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t *src)
POKEYSDECL int32_t PK_PoILEraseMemory (sPoKeysDevice *device, uint8_t memoryType)
POKEYSDECL int32_t PK_PoILChunkReadMemory (sPoKeysDevice *device, uint8_t *dest)
POKEYSDECL int32_t PK_PoILChunkReadMemoryInternalAddress (sPoKeysDevice *device, uint8_t *dest)
POKEYSDECL int32_t PK_PoILReadSharedSlot (sPoKeysDevice *device, uint16_t firstSlotID, uint16_t slotsNum, int32_t *dest)
POKEYSDECL int32_t PK_PoILWriteSharedSlot (sPoKeysDevice *device, uint16_t firstSlotID, uint16_t slotsNum, int32_t *src)
POKEYSDECL int32_t PK_PoILTaskStatus (sPoKeysDevice *device)
POKEYSDECL int32_t PK_RTCGet (sPoKeysDevice *device)
Read the real-time clock values (command 0x83/0x00).
POKEYSDECL int32_t PK_RTCSet (sPoKeysDevice *device)
Set the real-time clock (command 0x83/0x10).
POKEYSDECL int32_t PK_UARTConfigure (sPoKeysDevice *device, uint32_t baudrate, uint8_t format, uint8_t interfaceID)
Configure a UART interface (command 0xDE/0x10).
POKEYSDECL int32_t PK_UARTWrite (sPoKeysDevice *device, uint8_t interfaceID, uint8_t *dataPtr, uint32_t dataWriteLen)
Write data to the UART interface (command 0xDE/0x20).
POKEYSDECL int32_t PK_UARTRead (sPoKeysDevice *device, uint8_t interfaceID, uint8_t *dataPtr, uint8_t *dataReadLen)
Read data from a UART interface (command 0xDE/0x30).
POKEYSDECL int32_t PK_CANConfigure (sPoKeysDevice *device, uint32_t bitrate)
Configure the CAN interface (subcommand 0x01).
POKEYSDECL int32_t PK_CANRegisterFilter (sPoKeysDevice *device, uint8_t format, uint32_t CANid)
Register a CAN filter (subcommand 0x10).
POKEYSDECL int32_t PK_CANWrite (sPoKeysDevice *device, sPoKeysCANmsg *msg)
Transmit a CAN message (subcommand 0x20).
POKEYSDECL int32_t PK_CANRead (sPoKeysDevice *device, sPoKeysCANmsg *msg, uint8_t *status)
Receive one CAN message (subcommand 0x31).
POKEYSDECL int32_t PK_CANFlush (sPoKeysDevice *device)
Flush the CAN receive queue (subcommand 0x32).
POKEYSDECL int32_t PK_WS2812_Update (sPoKeysDevice *device, uint16_t LEDcount, uint8_t updateFlag)
POKEYSDECL int32_t PK_WS2812_SendLEDdata (sPoKeysDevice *device, uint32_t *LEDdata, uint16_t startLED, uint8_t LEDcount)
POKEYSDECL void PK_SL_SetPinFunction (sPoKeysDevice *device, uint8_t pin, uint8_t function)
POKEYSDECL uint8_t PK_SL_GetPinFunction (sPoKeysDevice *device, uint8_t pin)
POKEYSDECL void PK_SL_DigitalOutputSet (sPoKeysDevice *device, uint8_t pin, uint8_t value)
POKEYSDECL uint8_t PK_SL_DigitalInputGet (sPoKeysDevice *device, uint8_t pin)
POKEYSDECL uint32_t PK_SL_AnalogInputGet (sPoKeysDevice *device, uint8_t pin)
POKEYSDECL uint32_t PK_SL_EncoderValueGet (sPoKeysDevice *device, uint8_t index)
POKEYSDECL int32_t PK_SL_EasySensorValueGet (sPoKeysDevice *device, uint8_t index)
Return cached sensor value.
POKEYSDECL uint32_t PK_SL_PWMConfig (sPoKeysDevice *device, uint8_t index)
POKEYSDECL int32_t PK_SL_PWM_SetPeriod (sPoKeysDevice *device, uint32_t PWMperiod)
POKEYSDECL int32_t PK_SL_PWM_SetChannelEnabled (sPoKeysDevice *device, uint8_t channel, uint8_t enabled, uint32_t defaultDuty)
POKEYSDECL int32_t PK_SL_PWM_SetDuty (sPoKeysDevice *device, uint8_t channel, uint32_t duty)
POKEYSDECL int32_t PK_OEM_Martelli_SetMode (sPoKeysDevice *device, uint8_t mode)
POKEYSDECL int32_t PK_OEM_Martelli_SetThreshold (sPoKeysDevice *device, uint32_t threshold)
POKEYSDECL int32_t PK_OEM_Martelli_SetRate (sPoKeysDevice *device, uint32_t rate)
Variables
int32_t LastRetryCount
int32_t LastWaitCount
Macro Definition Documentation
ALIGN_TEST
#define ALIGN_TEST (x)
Definition at line 62 of file PoKeysLib.h.
POKEYSDECL
#define POKEYSDECL
Definition at line 49 of file PoKeysLib.h.
USE_STD_INT
#define USE_STD_INT
Definition at line 23 of file PoKeysLib.h.
Typedef Documentation
int16_t
typedef short int16_t
Definition at line 31 of file PoKeysLib.h.
int32_t
typedef int int32_t
Definition at line 32 of file PoKeysLib.h.
int64_t
typedef long long int64_t
Definition at line 38 of file PoKeysLib.h.
int8_t
typedef signed char int8_t
Definition at line 30 of file PoKeysLib.h.
uint16_t
typedef unsigned short uint16_t
Definition at line 35 of file PoKeysLib.h.
uint32_t
typedef unsigned int uint32_t
Definition at line 36 of file PoKeysLib.h.
uint64_t
typedef unsigned long long uint64_t
Definition at line 39 of file PoKeysLib.h.
uint8_t
typedef unsigned char uint8_t
Definition at line 34 of file PoKeysLib.h.
Enumeration Type Documentation
ePK_AllPinCap
enum ePK_AllPinCap
Enumerator
PK_AllPinCap_digitalInput
PK_AllPinCap_digitalOutput
PK_AllPinCap_analogInput
PK_AllPinCap_MFanalogInput
PK_AllPinCap_analogOutput
PK_AllPinCap_keyboardMapping
PK_AllPinCap_triggeredInput
PK_AllPinCap_digitalCounter
PK_AllPinCap_PWMOut
PK_AllPinCap_fastEncoder1A
PK_AllPinCap_fastEncoder1B
PK_AllPinCap_fastEncoder1I
PK_AllPinCap_fastEncoder2A
PK_AllPinCap_fastEncoder2B
PK_AllPinCap_fastEncoder2I
PK_AllPinCap_fastEncoder3A
PK_AllPinCap_fastEncoder3B
PK_AllPinCap_fastEncoder3I
PK_AllPinCap_ultraFastEncoderA
PK_AllPinCap_ultraFastEncoderB
PK_AllPinCap_ultraFastEncoderI
PK_AllPinCap_LCD_E
PK_AllPinCap_LCD_RW
PK_AllPinCap_LCD_RS
PK_AllPinCap_LCD_D4
PK_AllPinCap_LCD_D5
PK_AllPinCap_LCD_D6
PK_AllPinCap_LCD_D7
PK_AllPinCap_digitalInput
PK_AllPinCap_digitalOutput
PK_AllPinCap_analogInput
PK_AllPinCap_MFanalogInput
PK_AllPinCap_analogOutput
PK_AllPinCap_keyboardMapping
PK_AllPinCap_triggeredInput
PK_AllPinCap_digitalCounter
PK_AllPinCap_PWMOut
PK_AllPinCap_fastEncoder1A
PK_AllPinCap_fastEncoder1B
PK_AllPinCap_fastEncoder1I
PK_AllPinCap_fastEncoder2A
PK_AllPinCap_fastEncoder2B
PK_AllPinCap_fastEncoder2I
PK_AllPinCap_fastEncoder3A
PK_AllPinCap_fastEncoder3B
PK_AllPinCap_fastEncoder3I
PK_AllPinCap_ultraFastEncoderA
PK_AllPinCap_ultraFastEncoderB
PK_AllPinCap_ultraFastEncoderI
PK_AllPinCap_LCD_E
PK_AllPinCap_LCD_RW
PK_AllPinCap_LCD_RS
PK_AllPinCap_LCD_D4
PK_AllPinCap_LCD_D5
PK_AllPinCap_LCD_D6
PK_AllPinCap_LCD_D7
PK_AllPinCap_digitalInput
PK_AllPinCap_digitalOutput
PK_AllPinCap_analogInput
PK_AllPinCap_MFanalogInput
PK_AllPinCap_analogOutput
PK_AllPinCap_keyboardMapping
PK_AllPinCap_triggeredInput
PK_AllPinCap_digitalCounter
PK_AllPinCap_PWMOut
PK_AllPinCap_fastEncoder1A
PK_AllPinCap_fastEncoder1B
PK_AllPinCap_fastEncoder1I
PK_AllPinCap_fastEncoder2A
PK_AllPinCap_fastEncoder2B
PK_AllPinCap_fastEncoder2I
PK_AllPinCap_fastEncoder3A
PK_AllPinCap_fastEncoder3B
PK_AllPinCap_fastEncoder3I
PK_AllPinCap_ultraFastEncoderA
PK_AllPinCap_ultraFastEncoderB
PK_AllPinCap_ultraFastEncoderI
PK_AllPinCap_LCD_E
PK_AllPinCap_LCD_RW
PK_AllPinCap_LCD_RS
PK_AllPinCap_LCD_D4
PK_AllPinCap_LCD_D5
PK_AllPinCap_LCD_D6
PK_AllPinCap_LCD_D7
PK_AllPinCap_digitalInput
PK_AllPinCap_digitalOutput
PK_AllPinCap_analogInput
PK_AllPinCap_MFanalogInput
PK_AllPinCap_analogOutput
PK_AllPinCap_keyboardMapping
PK_AllPinCap_triggeredInput
PK_AllPinCap_digitalCounter
PK_AllPinCap_PWMOut
PK_AllPinCap_fastEncoder1A
PK_AllPinCap_fastEncoder1B
PK_AllPinCap_fastEncoder1I
PK_AllPinCap_fastEncoder2A
PK_AllPinCap_fastEncoder2B
PK_AllPinCap_fastEncoder2I
PK_AllPinCap_fastEncoder3A
PK_AllPinCap_fastEncoder3B
PK_AllPinCap_fastEncoder3I
PK_AllPinCap_ultraFastEncoderA
PK_AllPinCap_ultraFastEncoderB
PK_AllPinCap_ultraFastEncoderI
PK_AllPinCap_LCD_E
PK_AllPinCap_LCD_RW
PK_AllPinCap_LCD_RS
PK_AllPinCap_LCD_D4
PK_AllPinCap_LCD_D5
PK_AllPinCap_LCD_D6
PK_AllPinCap_LCD_D7
Definition at line 88 of file PoKeysLib.h.
ePK_DeviceConnectionParam
enum ePK_DeviceConnectionParam
Enumerator
PK_ConnectionParam_TCP
PK_ConnectionParam_UDP
PK_ConnectionParam_TCP
PK_ConnectionParam_UDP
PK_ConnectionParam_TCP
PK_ConnectionParam_UDP
PK_ConnectionParam_TCP
PK_ConnectionParam_UDP
Definition at line 214 of file PoKeysLib.h.
ePK_DeviceConnectionType
enum ePK_DeviceConnectionType
Enumerator
PK_DeviceType_USBDevice
PK_DeviceType_NetworkDevice
PK_DeviceType_FastUSBDevice
PK_DeviceType_USBDevice
PK_DeviceType_NetworkDevice
PK_DeviceType_FastUSBDevice
PK_DeviceType_USBDevice
PK_DeviceType_NetworkDevice
PK_DeviceType_FastUSBDevice
PK_DeviceType_USBDevice
PK_DeviceType_NetworkDevice
PK_DeviceType_FastUSBDevice
Definition at line 207 of file PoKeysLib.h.
ePK_DeviceTypeID
enum ePK_DeviceTypeID
Enumerator
PK_DeviceID_Bootloader55
PK_DeviceID_Bootloader56U
PK_DeviceID_Bootloader56E
PK_DeviceID_Bootloader58
PK_DeviceID_55v1
PK_DeviceID_55v2
PK_DeviceID_55v3
PK_DeviceID_56U
PK_DeviceID_56E
PK_DeviceID_27U
PK_DeviceID_27E
PK_DeviceID_57U
PK_DeviceID_57E
PK_DeviceID_PoKeys57CNC
PK_DeviceID_PoKeys57CNCpro4x25
PK_DeviceID_PoKeys57CNCdb25
PK_DeviceID_PoKeys57Utest
PK_DeviceID_LiniTester
PK_DeviceID_57U_v0
PK_DeviceID_57E_v0
PK_DeviceID_58EU
PK_DeviceID_PoPLC58
PK_DeviceID_OEM1
PK_DeviceID_SerialReader
PK_DeviceID_X15_02_24
PK_DeviceID_Bootloader55
PK_DeviceID_Bootloader56U
PK_DeviceID_Bootloader56E
PK_DeviceID_Bootloader58
PK_DeviceID_55v1
PK_DeviceID_55v2
PK_DeviceID_55v3
PK_DeviceID_56U
PK_DeviceID_56E
PK_DeviceID_27U
PK_DeviceID_27E
PK_DeviceID_57U
PK_DeviceID_57E
PK_DeviceID_PoKeys57CNC
PK_DeviceID_PoKeys57CNCpro4x25
PK_DeviceID_PoKeys57CNCdb25
PK_DeviceID_PoKeys57Utest
PK_DeviceID_LiniTester
PK_DeviceID_57U_v0
PK_DeviceID_57E_v0
PK_DeviceID_58EU
PK_DeviceID_PoPLC58
PK_DeviceID_OEM1
PK_DeviceID_SerialReader
PK_DeviceID_X15_02_24
PK_DeviceID_Bootloader55
PK_DeviceID_Bootloader56U
PK_DeviceID_Bootloader56E
PK_DeviceID_Bootloader58
PK_DeviceID_55v1
PK_DeviceID_55v2
PK_DeviceID_55v3
PK_DeviceID_56U
PK_DeviceID_56E
PK_DeviceID_27U
PK_DeviceID_27E
PK_DeviceID_57U
PK_DeviceID_57E
PK_DeviceID_PoKeys57CNC
PK_DeviceID_PoKeys57CNCpro4x25
PK_DeviceID_PoKeys57CNCdb25
PK_DeviceID_PoKeys57Utest
PK_DeviceID_LiniTester
PK_DeviceID_57U_v0
PK_DeviceID_57E_v0
PK_DeviceID_58EU
PK_DeviceID_PoPLC58
PK_DeviceID_OEM1
PK_DeviceID_SerialReader
PK_DeviceID_X15_02_24
PK_DeviceID_Bootloader55
PK_DeviceID_Bootloader56U
PK_DeviceID_Bootloader56E
PK_DeviceID_Bootloader58
PK_DeviceID_55v1
PK_DeviceID_55v2
PK_DeviceID_55v3
PK_DeviceID_56U
PK_DeviceID_56E
PK_DeviceID_27U
PK_DeviceID_27E
PK_DeviceID_57U
PK_DeviceID_57E
PK_DeviceID_PoKeys57CNC
PK_DeviceID_PoKeys57CNCpro4x25
PK_DeviceID_PoKeys57CNCdb25
PK_DeviceID_PoKeys57Utest
PK_DeviceID_LiniTester
PK_DeviceID_57U_v0
PK_DeviceID_57E_v0
PK_DeviceID_58EU
PK_DeviceID_PoPLC58
PK_DeviceID_OEM1
PK_DeviceID_SerialReader
PK_DeviceID_X15_02_24
Definition at line 158 of file PoKeysLib.h.
ePK_DeviceTypeMask
enum ePK_DeviceTypeMask
Enumerator
PK_DeviceMask_Bootloader
PK_DeviceMask_Bootloader55
PK_DeviceMask_Bootloader56
PK_DeviceMask_Bootloader56U
PK_DeviceMask_Bootloader56E
PK_DeviceMask_Bootloader58
PK_DeviceMask_55
PK_DeviceMask_55v1
PK_DeviceMask_55v2
PK_DeviceMask_55v3
PK_DeviceMask_56
PK_DeviceMask_56U
PK_DeviceMask_56E
PK_DeviceMask_27
PK_DeviceMask_27U
PK_DeviceMask_27E
PK_DeviceMask_57
PK_DeviceMask_57U
PK_DeviceMask_57E
PK_DeviceMask_57CNC
PK_DeviceMask_57CNCdb25
PK_DeviceMask_57Utest
PK_DeviceMask_57CNCpro4x25
PK_DeviceMask_58
PK_DeviceMask_PoPLC58
PK_DeviceMask_PoKeys16RF
PK_DeviceMask_Bootloader
PK_DeviceMask_Bootloader55
PK_DeviceMask_Bootloader56
PK_DeviceMask_Bootloader56U
PK_DeviceMask_Bootloader56E
PK_DeviceMask_Bootloader58
PK_DeviceMask_55
PK_DeviceMask_55v1
PK_DeviceMask_55v2
PK_DeviceMask_55v3
PK_DeviceMask_56
PK_DeviceMask_56U
PK_DeviceMask_56E
PK_DeviceMask_27
PK_DeviceMask_27U
PK_DeviceMask_27E
PK_DeviceMask_57
PK_DeviceMask_57U
PK_DeviceMask_57E
PK_DeviceMask_57CNC
PK_DeviceMask_57CNCdb25
PK_DeviceMask_57Utest
PK_DeviceMask_57CNCpro4x25
PK_DeviceMask_58
PK_DeviceMask_PoPLC58
PK_DeviceMask_PoKeys16RF
PK_DeviceMask_Bootloader
PK_DeviceMask_Bootloader55
PK_DeviceMask_Bootloader56
PK_DeviceMask_Bootloader56U
PK_DeviceMask_Bootloader56E
PK_DeviceMask_Bootloader58
PK_DeviceMask_55
PK_DeviceMask_55v1
PK_DeviceMask_55v2
PK_DeviceMask_55v3
PK_DeviceMask_56
PK_DeviceMask_56U
PK_DeviceMask_56E
PK_DeviceMask_27
PK_DeviceMask_27U
PK_DeviceMask_27E
PK_DeviceMask_57
PK_DeviceMask_57U
PK_DeviceMask_57E
PK_DeviceMask_57CNC
PK_DeviceMask_57CNCdb25
PK_DeviceMask_57Utest
PK_DeviceMask_57CNCpro4x25
PK_DeviceMask_58
PK_DeviceMask_PoPLC58
PK_DeviceMask_PoKeys16RF
PK_DeviceMask_Bootloader
PK_DeviceMask_Bootloader55
PK_DeviceMask_Bootloader56
PK_DeviceMask_Bootloader56U
PK_DeviceMask_Bootloader56E
PK_DeviceMask_Bootloader58
PK_DeviceMask_55
PK_DeviceMask_55v1
PK_DeviceMask_55v2
PK_DeviceMask_55v3
PK_DeviceMask_56
PK_DeviceMask_56U
PK_DeviceMask_56E
PK_DeviceMask_27
PK_DeviceMask_27U
PK_DeviceMask_27E
PK_DeviceMask_57
PK_DeviceMask_57U
PK_DeviceMask_57E
PK_DeviceMask_57CNC
PK_DeviceMask_57CNCdb25
PK_DeviceMask_57Utest
PK_DeviceMask_57CNCpro4x25
PK_DeviceMask_58
PK_DeviceMask_PoPLC58
PK_DeviceMask_PoKeys16RF
Definition at line 121 of file PoKeysLib.h.
ePK_I2C_STATUS
enum ePK_I2C_STATUS
Enumerator
PK_I2C_STAT_ERR
PK_I2C_STAT_OK
PK_I2C_STAT_COMPLETE
PK_I2C_STAT_IN_PROGRESS
PK_I2C_STAT_ERR
PK_I2C_STAT_OK
PK_I2C_STAT_COMPLETE
PK_I2C_STAT_IN_PROGRESS
PK_I2C_STAT_ERR
PK_I2C_STAT_OK
PK_I2C_STAT_COMPLETE
PK_I2C_STAT_IN_PROGRESS
PK_I2C_STAT_ERR
PK_I2C_STAT_OK
PK_I2C_STAT_COMPLETE
PK_I2C_STAT_IN_PROGRESS
Definition at line 311 of file PoKeysLib.h.
ePK_LCD_MODE
enum ePK_LCD_MODE
Enumerator
PK_LCD_MODE_DIRECT
PK_LCD_MODE_BUFFERED
PK_LCD_MODE_DIRECT
PK_LCD_MODE_BUFFERED
PK_LCD_MODE_DIRECT
PK_LCD_MODE_BUFFERED
PK_LCD_MODE_DIRECT
PK_LCD_MODE_BUFFERED
Definition at line 319 of file PoKeysLib.h.
ePK_PEAxisState
enum ePK_PEAxisState
Enumerator
PK_PEAxisState_axSTOPPED
PK_PEAxisState_axREADY
PK_PEAxisState_axRUNNING
PK_PEAxisState_axHOMING_RESETTING
PK_PEAxisState_axHOMING_BACKING_OFF
PK_PEAxisState_axHOME
PK_PEAxisState_axHOMINGSTART
PK_PEAxisState_axHOMINGSEARCH
PK_PEAxisState_axHOMINGBACK
PK_PEAxisState_axPROBED
PK_PEAxisState_axPROBESTART
PK_PEAxisState_axPROBESEARCH
PK_PEAxisState_axERROR
PK_PEAxisState_axLIMIT
PK_PEAxisState_axSTOPPED
PK_PEAxisState_axREADY
PK_PEAxisState_axRUNNING
PK_PEAxisState_axHOMING_RESETTING
PK_PEAxisState_axHOMING_BACKING_OFF
PK_PEAxisState_axHOME
PK_PEAxisState_axHOMINGSTART
PK_PEAxisState_axHOMINGSEARCH
PK_PEAxisState_axHOMINGBACK
PK_PEAxisState_axPROBED
PK_PEAxisState_axPROBESTART
PK_PEAxisState_axPROBESEARCH
PK_PEAxisState_axERROR
PK_PEAxisState_axLIMIT
PK_PEAxisState_axSTOPPED
PK_PEAxisState_axREADY
PK_PEAxisState_axRUNNING
PK_PEAxisState_axHOMING_RESETTING
PK_PEAxisState_axHOMING_BACKING_OFF
PK_PEAxisState_axHOME
PK_PEAxisState_axHOMINGSTART
PK_PEAxisState_axHOMINGSEARCH
PK_PEAxisState_axHOMINGBACK
PK_PEAxisState_axPROBED
PK_PEAxisState_axPROBESTART
PK_PEAxisState_axPROBESEARCH
PK_PEAxisState_axERROR
PK_PEAxisState_axLIMIT
PK_PEAxisState_axSTOPPED
PK_PEAxisState_axREADY
PK_PEAxisState_axRUNNING
PK_PEAxisState_axHOMING_RESETTING
PK_PEAxisState_axHOMING_BACKING_OFF
PK_PEAxisState_axHOME
PK_PEAxisState_axHOMINGSTART
PK_PEAxisState_axHOMINGSEARCH
PK_PEAxisState_axHOMINGBACK
PK_PEAxisState_axPROBED
PK_PEAxisState_axPROBESTART
PK_PEAxisState_axPROBESEARCH
PK_PEAxisState_axERROR
PK_PEAxisState_axLIMIT
Definition at line 246 of file PoKeysLib.h.
ePK_PEState
enum ePK_PEState
Enumerator
PK_PEState_peSTOPPED
PK_PEState_peINTERNAL
PK_PEState_peBUFFER
PK_PEState_peRUNNING
PK_PEState_peJOGGING
PK_PEState_peSTOPPING
PK_PEState_peHOME
PK_PEState_peHOMING
PK_PEState_pePROBECOMPLETE
PK_PEState_pePROBE
PK_PEState_pePROBEERROR
PK_PEState_peHYBRIDPROBE_STOPPING
PK_PEState_peHYBRIDPROBE_COMPLETE
PK_PEState_peSTOP_LIMIT
PK_PEState_peSTOP_EMERGENCY
PK_PEState_peSTOPPED
PK_PEState_peINTERNAL
PK_PEState_peBUFFER
PK_PEState_peRUNNING
PK_PEState_peJOGGING
PK_PEState_peSTOPPING
PK_PEState_peHOME
PK_PEState_peHOMING
PK_PEState_pePROBECOMPLETE
PK_PEState_pePROBE
PK_PEState_pePROBEERROR
PK_PEState_peHYBRIDPROBE_STOPPING
PK_PEState_peHYBRIDPROBE_COMPLETE
PK_PEState_peSTOP_LIMIT
PK_PEState_peSTOP_EMERGENCY
PK_PEState_peSTOPPED
PK_PEState_peINTERNAL
PK_PEState_peBUFFER
PK_PEState_peRUNNING
PK_PEState_peJOGGING
PK_PEState_peSTOPPING
PK_PEState_peHOME
PK_PEState_peHOMING
PK_PEState_pePROBECOMPLETE
PK_PEState_pePROBE
PK_PEState_pePROBEERROR
PK_PEState_peHYBRIDPROBE_STOPPING
PK_PEState_peHYBRIDPROBE_COMPLETE
PK_PEState_peSTOP_LIMIT
PK_PEState_peSTOP_EMERGENCY
PK_PEState_peSTOPPED
PK_PEState_peINTERNAL
PK_PEState_peBUFFER
PK_PEState_peRUNNING
PK_PEState_peJOGGING
PK_PEState_peSTOPPING
PK_PEState_peHOME
PK_PEState_peHOMING
PK_PEState_pePROBECOMPLETE
PK_PEState_pePROBE
PK_PEState_pePROBEERROR
PK_PEState_peHYBRIDPROBE_STOPPING
PK_PEState_peHYBRIDPROBE_COMPLETE
PK_PEState_peSTOP_LIMIT
PK_PEState_peSTOP_EMERGENCY
Definition at line 221 of file PoKeysLib.h.
ePK_PEv2_AxisConfig
enum ePK_PEv2_AxisConfig
Enumerator
PK_AC_ENABLED
PK_AC_INVERTED
PK_AC_INTERNAL_PLANNER
PK_AC_POSITION_MODE
PK_AC_INVERTED_HOME
PK_AC_SOFT_LIMIT_ENABLED
PK_AC_FAST_OUTPUT
PK_AC_ENABLED_MASKED
PK_AC_ENABLED
PK_AC_INVERTED
PK_AC_INTERNAL_PLANNER
PK_AC_POSITION_MODE
PK_AC_INVERTED_HOME
PK_AC_SOFT_LIMIT_ENABLED
PK_AC_FAST_OUTPUT
PK_AC_ENABLED_MASKED
PK_AC_ENABLED
PK_AC_INVERTED
PK_AC_INTERNAL_PLANNER
PK_AC_POSITION_MODE
PK_AC_INVERTED_HOME
PK_AC_SOFT_LIMIT_ENABLED
PK_AC_FAST_OUTPUT
PK_AC_ENABLED_MASKED
PK_AC_ENABLED
PK_AC_INVERTED
PK_AC_INTERNAL_PLANNER
PK_AC_POSITION_MODE
PK_AC_INVERTED_HOME
PK_AC_SOFT_LIMIT_ENABLED
PK_AC_FAST_OUTPUT
PK_AC_ENABLED_MASKED
Definition at line 267 of file PoKeysLib.h.
ePK_PEv2_AxisSignalOptions
enum ePK_PEv2_AxisSignalOptions
Enumerator
PK_ASO_INVERT_STEP
PK_ASO_INVERT_DIRECTION
PK_ASO_INVERT_STEP
PK_ASO_INVERT_DIRECTION
PK_ASO_INVERT_STEP
PK_ASO_INVERT_DIRECTION
PK_ASO_INVERT_STEP
PK_ASO_INVERT_DIRECTION
Definition at line 291 of file PoKeysLib.h.
ePK_PEv2_AxisSwitchOptions
enum ePK_PEv2_AxisSwitchOptions
Enumerator
PK_ASO_SWITCH_LIMIT_N
PK_ASO_SWITCH_LIMIT_P
PK_ASO_SWITCH_HOME
PK_ASO_SWITCH_COMBINED_LN_H
PK_ASO_SWITCH_COMBINED_LP_H
PK_ASO_SWITCH_INVERT_LIMIT_N
PK_ASO_SWITCH_INVERT_LIMIT_P
PK_ASO_SWITCH_INVERT_HOME
PK_ASO_SWITCH_LIMIT_N
PK_ASO_SWITCH_LIMIT_P
PK_ASO_SWITCH_HOME
PK_ASO_SWITCH_COMBINED_LN_H
PK_ASO_SWITCH_COMBINED_LP_H
PK_ASO_SWITCH_INVERT_LIMIT_N
PK_ASO_SWITCH_INVERT_LIMIT_P
PK_ASO_SWITCH_INVERT_HOME
PK_ASO_SWITCH_LIMIT_N
PK_ASO_SWITCH_LIMIT_P
PK_ASO_SWITCH_HOME
PK_ASO_SWITCH_COMBINED_LN_H
PK_ASO_SWITCH_COMBINED_LP_H
PK_ASO_SWITCH_INVERT_LIMIT_N
PK_ASO_SWITCH_INVERT_LIMIT_P
PK_ASO_SWITCH_INVERT_HOME
PK_ASO_SWITCH_LIMIT_N
PK_ASO_SWITCH_LIMIT_P
PK_ASO_SWITCH_HOME
PK_ASO_SWITCH_COMBINED_LN_H
PK_ASO_SWITCH_COMBINED_LP_H
PK_ASO_SWITCH_INVERT_LIMIT_N
PK_ASO_SWITCH_INVERT_LIMIT_P
PK_ASO_SWITCH_INVERT_HOME
Definition at line 279 of file PoKeysLib.h.
ePK_PinCap
enum ePK_PinCap
Enumerator
PK_PinCap_pinRestricted
PK_PinCap_reserved
PK_PinCap_digitalInput
PK_PinCap_digitalOutput
PK_PinCap_analogInput
PK_PinCap_analogOutput
PK_PinCap_triggeredInput
PK_PinCap_digitalCounter
PK_PinCap_invertPin
PK_PinCap_pinRestricted
PK_PinCap_reserved
PK_PinCap_digitalInput
PK_PinCap_digitalOutput
PK_PinCap_analogInput
PK_PinCap_analogOutput
PK_PinCap_triggeredInput
PK_PinCap_digitalCounter
PK_PinCap_invertPin
PK_PinCap_pinRestricted
PK_PinCap_reserved
PK_PinCap_digitalInput
PK_PinCap_digitalOutput
PK_PinCap_analogInput
PK_PinCap_analogOutput
PK_PinCap_triggeredInput
PK_PinCap_digitalCounter
PK_PinCap_invertPin
PK_PinCap_pinRestricted
PK_PinCap_reserved
PK_PinCap_digitalInput
PK_PinCap_digitalOutput
PK_PinCap_analogInput
PK_PinCap_analogOutput
PK_PinCap_triggeredInput
PK_PinCap_digitalCounter
PK_PinCap_invertPin
Definition at line 72 of file PoKeysLib.h.
ePK_RETURN_CODES
enum ePK_RETURN_CODES
Enumerator
PK_OK
PK_ERR_GENERIC
PK_ERR_NOT_CONNECTED
PK_ERR_TRANSFER
PK_ERR_PARAMETER
PK_ERR_NOT_SUPPORTED
PK_ERR_CANNOT_CLAIM_USB
PK_ERR_CANNOT_CONNECT
PK_OK
PK_ERR_GENERIC
PK_ERR_NOT_CONNECTED
PK_ERR_TRANSFER
PK_ERR_PARAMETER
PK_ERR_NOT_SUPPORTED
PK_ERR_CANNOT_CLAIM_USB
PK_ERR_CANNOT_CONNECT
PK_OK
PK_ERR_GENERIC
PK_ERR_NOT_CONNECTED
PK_ERR_TRANSFER
PK_ERR_PARAMETER
PK_ERR_NOT_SUPPORTED
PK_ERR_CANNOT_CLAIM_USB
PK_ERR_CANNOT_CONNECT
PK_OK
PK_ERR_GENERIC
PK_ERR_NOT_CONNECTED
PK_ERR_TRANSFER
PK_ERR_PARAMETER
PK_ERR_NOT_SUPPORTED
PK_ERR_CANNOT_CLAIM_USB
PK_ERR_CANNOT_CONNECT
Definition at line 299 of file PoKeysLib.h.
Function Documentation
PK_1WireBusScanContinue()
POKEYSDECL int32_t PK_1WireBusScanContinue (sPoKeysDevice * device)
Continue a previously started 1-wire bus scan.
Sends command 0xDC/0x22.
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or an error from SendRequest.
Definition at line 129 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireBusScanGetResults()
POKEYSDECL int32_t PK_1WireBusScanGetResults (sPoKeysDevice * device, uint8_t * operationStatus, uint8_t * scanResult, uint8_t * deviceROM)
Obtain status and results of a 1-wire bus scan.
Command 0xDC/0x21 returns the current scanning state and the discovered device ROM code when available.
Parameters
device Pointer to an opened PoKeys device.
operationStatus Receives operation status byte.
scanResult Receives scan progress flags.
deviceROM Buffer for the 8 byte device ROM.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 113 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_1WireBusScanStart()
POKEYSDECL int32_t PK_1WireBusScanStart (sPoKeysDevice * device, uint8_t pinID)
Begin scanning the 1-wire bus for devices.
Issues command 0xDC/0x20 with the selected pin ID.
Parameters
device Pointer to an opened PoKeys device.
pinID PoKeys pin used for the scan.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or an error from SendRequest.
Definition at line 105 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireBusScanStop()
POKEYSDECL int32_t PK_1WireBusScanStop (sPoKeysDevice * device)
Stop an ongoing 1-wire bus scan.
Uses command 0xDC/0x23 to terminate the scan procedure.
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or an error from SendRequest.
Definition at line 138 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireReadStatusGet()
POKEYSDECL int32_t PK_1WireReadStatusGet (sPoKeysDevice * device, uint8_t * readStatus, uint8_t * ReadCount, uint8_t * data)
Retrieve data from the previous 1-wire read operation.
Sends command 0xDC/0x11 to obtain the read status and any returned bytes.
Parameters
device Pointer to an opened PoKeys device.
readStatus Operation status: 1 when data is available.
ReadCount Receives the number of bytes returned.
data Buffer that receives the read bytes (up to 16).
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL, PK_ERR_TRANSFER on communication failure or PK_ERR_PARAMETER if the returned byte count is invalid.
Definition at line 59 of file PoKeysLib1Wire.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_1WireStatusGet()
POKEYSDECL int32_t PK_1WireStatusGet (sPoKeysDevice * device, uint8_t * activated)
Query the 1-wire activation status.
Sends command 0xDC/0x11 which returns the current activation state in the response.
Parameters
device Pointer to an opened PoKeys device.
activated Destination for the activation flag (1 when enabled).
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 32 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_1WireStatusSet()
POKEYSDECL int32_t PK_1WireStatusSet (sPoKeysDevice * device, uint8_t activated)
Enable or disable the 1-wire bus.
Issues command 0xDC with operation code 0x01 to enable or 0x00 to disable the bus as defined in the protocol specification ("1-wire settings and communication").
Parameters
device Pointer to an opened PoKeys device.
activated Non-zero to activate the bus, zero to deactivate.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED when device is NULL or an error returned by SendRequest (for example PK_ERR_TRANSFER).
Definition at line 24 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireWriteReadStart()
POKEYSDECL int32_t PK_1WireWriteReadStart (sPoKeysDevice * device, uint8_t WriteCount, uint8_t ReadCount, uint8_t * data)
Start a reset/write/read transaction on the 1-wire bus.
Executes command 0xDC/0x10 ("Start Reset, Write and Read process"). Up to 16 bytes may be written and read in a single transaction.
Parameters
device Pointer to an opened PoKeys device.
WriteCount Number of bytes to write (clamped to 16).
ReadCount Number of bytes to read (clamped to 16).
data Buffer containing bytes to write.
Returns
PK_OK when the command is sent successfully, PK_ERR_NOT_CONNECTED if device is NULL or an error from SendRequest.
Definition at line 43 of file PoKeysLib1Wire.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireWriteReadStartEx()
POKEYSDECL int32_t PK_1WireWriteReadStartEx (sPoKeysDevice * device, uint8_t pinID, uint8_t WriteCount, uint8_t ReadCount, uint8_t * data)
Start a 1-wire transaction on a specific pin.
Same as PK_1WireWriteReadStart() but allows selecting the 1-wire pin. Uses command 0xDC/0x10 with the pin ID in the third parameter byte.
Parameters
device Pointer to an opened PoKeys device.
pinID PoKeys pin used for 1-wire communication.
WriteCount Number of bytes to write (clamped to 16).
ReadCount Number of bytes to read (clamped to 16).
data Buffer of bytes to send.
Returns
PK_OK when the command is sent, PK_ERR_NOT_CONNECTED if device is NULL or an error from SendRequest.
Definition at line 88 of file PoKeysLib1Wire.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_AnalogIOGet()
POKEYSDECL int32_t PK_AnalogIOGet (sPoKeysDevice * device)
Read all analog input channels (command 0x3A/1).
Updates the values in device->AnalogInput and the corresponding pin structures.
Parameters
device Pointer to an opened device.
Returns
PK_OK on success or a ::PK_ERR code.
Definition at line 483 of file PoKeysLibIO.c.
References sPoKeysPinData::AnalogValue, CreateRequest(), i, sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice::info, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by PoKeysHALComponent::PKIO_Update().
PK_AnalogIOGetAsArray()
POKEYSDECL int32_t PK_AnalogIOGetAsArray (sPoKeysDevice * device, uint32_t * buffer)
Retrieve analog inputs into an array.
Wrapper around PK_AnalogIOGet() that copies the values into buffer when the read succeeds.
Parameters
device Pointer to an opened device.
buffer Destination array with at least seven elements.
Returns
PK_OK on success or a ::PK_ERR code.
Definition at line 502 of file PoKeysLibIO.c.
References sPoKeysPinData::AnalogValue, i, sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice::info, sPoKeysDevice::Pins, PK_AnalogIOGet(), PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, and PK_OK.
PK_AnalogRCFilterGet()
POKEYSDECL int32_t PK_AnalogRCFilterGet (sPoKeysDevice * device)
Read the analog RC filter setting (command 0x38/0).
Parameters
device Pointer to an opened device.
Returns
PK_OK on success or a ::PK_ERR code.
Definition at line 522 of file PoKeysLibIO.c.
References sPoKeysOtherPeripherals::AnalogRCFilter, CreateRequest(), sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice::info, sPoKeysDevice::otherPeripherals, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_AnalogRCFilterSet()
POKEYSDECL int32_t PK_AnalogRCFilterSet (sPoKeysDevice * device)
Configure the analog RC filter (command 0x39/0).
Parameters
device Pointer to an opened device.
Returns
PK_OK on success or a ::PK_ERR code.
Definition at line 536 of file PoKeysLibIO.c.
References sPoKeysOtherPeripherals::AnalogRCFilter, CreateRequest(), sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice::info, sPoKeysDevice::otherPeripherals, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_CANConfigure()
POKEYSDECL int32_t PK_CANConfigure (sPoKeysDevice * device, uint32_t bitrate)
Configure the CAN interface (subcommand 0x01).
Sends PK_CMD_CAN_OPERATIONS with subcommand 0x01 to enable the CAN controller and set the desired bitrate.
Parameters
device Pointer to an opened PoKeys device.
bitrate CAN bus bitrate in bits per second.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 23 of file PoKeysLibCAN.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_CANFlush()
POKEYSDECL int32_t PK_CANFlush (sPoKeysDevice * device)
Flush the CAN receive queue (subcommand 0x32).
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 71 of file PoKeysLibCAN.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_CANRead()
POKEYSDECL int32_t PK_CANRead (sPoKeysDevice * device, sPoKeysCANmsg * msg, uint8_t * status)
Receive one CAN message (subcommand 0x31).
The returned status byte indicates message availability. When non-zero, the received message is stored in msg.
Parameters
device Pointer to an opened PoKeys device.
msg Buffer for the received message.
status Receives 1 if a message was read.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 56 of file PoKeysLibCAN.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_CANRegisterFilter()
POKEYSDECL int32_t PK_CANRegisterFilter (sPoKeysDevice * device, uint8_t format, uint32_t CANid)
Register a CAN filter (subcommand 0x10).
The filter selects which CAN identifiers are received by the device.
Parameters
device Pointer to an opened PoKeys device.
format Identifier format: 0 for standard, 1 for extended.
CANid Identifier value to filter for.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 34 of file PoKeysLibCAN.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_CANWrite()
POKEYSDECL int32_t PK_CANWrite (sPoKeysDevice * device, sPoKeysCANmsg * msg)
Transmit a CAN message (subcommand 0x20).
The message contents are taken from msg and sent to the device.
Parameters
device Pointer to an opened PoKeys device.
msg CAN message to send.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 45 of file PoKeysLibCAN.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_CheckPinCapability()
POKEYSDECL int32_t PK_CheckPinCapability (sPoKeysDevice * device, unsigned int pin, ePK_AllPinCap cap)
Wrapper for PK_CheckPinCapabilityByTypeID() using a device handle.
Parameters
device PoKeys device structure.
pin Pin index (0 based).
cap Capability identifier.
Returns
1 if supported, 0 otherwise or negative on error.
Definition at line 1318 of file PoKeysLibDeviceData.c.
References sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceType, PK_CheckPinCapabilityByTypeID(), and PK_ERR_NOT_CONNECTED.
Referenced by PoKeysHALComponent::PKIO_export_pins(), and PoKeysHALComponent::PKIO_Update().
PK_CheckPinCapabilityByDevice()
POKEYSDECL int32_t PK_CheckPinCapabilityByDevice (uint64_t deviceTypeMask, uint32_t pin, ePK_AllPinCap cap)
Determine if a device class supports a pin capability.
Looks through the static capability table to check whether the given pin on any device matching deviceTypeMask implements capability cap.
Parameters
deviceTypeMask Combination of PK_DeviceMask_* bits.
pin Pin index (0 based).
cap Capability identifier.
Returns
1 if supported, otherwise 0.
Definition at line 1158 of file PoKeysLibDeviceData.c.
References sPoKeys_PinCapabilities::additionalCheck, sPoKeys_PinCapabilities::cap, sPoKeys_PinCapabilities::devTypes, pinCaps, sPoKeys_PinCapabilities::pinEnd, sPoKeys_PinCapabilities::pinStart, PK_AllPinCap_digitalCounter, PK_AllPinCap_fastEncoder1I, PK_AllPinCap_fastEncoder2A, PK_AllPinCap_fastEncoder2B, PK_AllPinCap_fastEncoder2I, PK_AllPinCap_fastEncoder3I, PK_DeviceMask_56, and PK_IsCounterAvailableByDevice().
PK_CheckPinCapabilityByTypeID()
POKEYSDECL int32_t PK_CheckPinCapabilityByTypeID (uint64_t deviceID, uint32_t pin, ePK_AllPinCap cap)
Check capability for a specific device type ID.
Searches the capability tables for the given deviceID and reports if pin implements capability cap.
Parameters
deviceID Device type identifier (e.g. PK_DeviceID_57E).
pin Pin index (0 based).
cap Capability identifier.
Returns
1 if supported, otherwise 0.
Definition at line 1198 of file PoKeysLibDeviceData.c.
References sPoKeys_PinCapabilities::additionalCheck, sPoKeys_PinCapabilities::cap, deviceDesc, sPoKeys_PinCapabilities::devTypes, pinCaps, sPoKeys_PinCapabilities::pinEnd, sPoKeys_PinCapabilities::pinStart, PK_AllPinCap_digitalCounter, PK_AllPinCap_fastEncoder1I, PK_AllPinCap_fastEncoder2A, PK_AllPinCap_fastEncoder2B, PK_AllPinCap_fastEncoder2I, PK_AllPinCap_fastEncoder3I, PK_DeviceID_27E, PK_DeviceID_27U, PK_DeviceID_55v1, PK_DeviceID_55v2, PK_DeviceID_55v3, PK_DeviceID_56E, PK_DeviceID_56U, PK_DeviceID_57E, PK_DeviceID_57E_v0, PK_DeviceID_57U, PK_DeviceID_57U_v0, PK_DeviceID_58EU, PK_DeviceID_OEM1, PK_DeviceID_PoKeys57CNC, PK_DeviceID_PoKeys57CNCdb25, PK_DeviceID_PoKeys57CNCpro4x25, PK_DeviceID_PoPLC58, PK_DeviceMask_27, PK_DeviceMask_55, PK_DeviceMask_56, PK_DeviceMask_56E, PK_DeviceMask_56U, PK_DeviceMask_57, PK_DeviceMask_57E, PK_DeviceMask_57U, PK_DeviceMask_58, PK_DeviceMask_PoPLC58, and PK_IsCounterAvailableByDevice().
PK_ClearConfiguration()
POKEYSDECL int32_t PK_ClearConfiguration (sPoKeysDevice * device)
Reset configuration in device flash (command 0x52).
Erases stored settings, reverting the device to defaults on next reboot.
Parameters
device Device to operate on.
Returns
PK_OK on success or PK_ERR_TRANSFER otherwise.
Definition at line 1148 of file PoKeysLibDeviceData.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_CloneDeviceStructure()
POKEYSDECL void PK_CloneDeviceStructure (sPoKeysDevice * original, sPoKeysDevice * destination)
Definition at line 228 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, sPoKeysDevice::DeviceData, sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice::LCD, sPoKeysDevice::matrixKB, sPoKeysDevice::MatrixLED, sPoKeysDevice::netDeviceData, sPoKeysDevice::Pins, sPoKeysDevice::PoExtBusData, sPoKeysDevice::PoIL, sPoKeysDevice::PoNETmodule, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysPWM::PWMpinIDs, sPoKeysDevice::requestID, sPoKeysDevice::RTC, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
PK_ConnectToDevice()
POKEYSDECL sPoKeysDevice * PK_ConnectToDevice (uint32_t deviceIndex)
Definition at line 312 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, hid_enumerate(), hid_free_enumeration(), hid_open_path(), InitializeNewDevice(), hid_device_info::interface_number, hid_device_info::next, hid_device_info::path, PK_DeviceType_FastUSBDevice, PK_DeviceType_USBDevice, and PK_FastUSBConnectToDevice().
Referenced by PK57i_Connect().
PK_ConnectToDeviceWSerial()
POKEYSDECL sPoKeysDevice * PK_ConnectToDeviceWSerial (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
Definition at line 611 of file PoKeysLibCore.c.
References PK_ConnectToPoKeysDevice().
PK_ConnectToDeviceWSerial_UDP()
POKEYSDECL sPoKeysDevice * PK_ConnectToDeviceWSerial_UDP (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
Definition at line 616 of file PoKeysLibCore.c.
References PK_ConnectToPoKeysDevice().
PK_ConnectToNetworkDevice()
POKEYSDECL sPoKeysDevice * PK_ConnectToNetworkDevice (sPoKeysNetworkDeviceSummary * device)
Definition at line 437 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionParam, sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, InitializeNewDevice(), sPoKeysNetworkDeviceSummary::IPaddress, PK_ConnectionParam_UDP, PK_DeviceType_NetworkDevice, TRUE, and sPoKeysNetworkDeviceSummary::useUDP.
Referenced by PK57i_Connect(), PK_ConnectToPoKeysDevice_Ethernet(), and PK_ConnectToPoKeysDevice_Ethernet_Async().
PK_ConnectToPoKeysDevice()
POKEYSDECL sPoKeysDevice * PK_ConnectToPoKeysDevice (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
Definition at line 587 of file PoKeysLibCore.c.
References PK_ConnectToPoKeysDevice_Ethernet(), and PK_ConnectToPoKeysDevice_USB().
PK_CustomRequest()
POKEYSDECL int32_t PK_CustomRequest (sPoKeysDevice * device, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Send an arbitrary request to the connected device.
The helper fills the device request buffer in the same format as CreateRequest() and immediately transmits it using SendRequest(). It is mainly used for higher level functions that do not require dedicated API calls.
Parameters
device Target device structure.
type Command ID (PK_CMD_* constant).
param1 First command parameter.
param2 Second command parameter.
param3 Third command parameter.
param4 Fourth command parameter.
Returns
Result of SendRequest().
Send an arbitrary request to the connected device.
A convenience wrapper that fills device->request using CreateRequest() semantics and then calls SendRequest().
Parameters
device Target device instance.
type Command ID.
param1 Parameter 1.
param2 Parameter 2.
param3 Parameter 3.
param4 Parameter 4.
Returns
Result of SendRequest().
Definition at line 662 of file PoKeysLibCore.c.
References sPoKeysDevice::request, and SendRequest().
PK_DeviceActivation()
POKEYSDECL int32_t PK_DeviceActivation (sPoKeysDevice * device)
Send activation code to the device (command 0x8F/0x01).
Writes the 8 byte ActivationCode field to unlock optional features. The activated options byte from the response is stored back into the structure.
Parameters
device Target device handle.
Returns
PK_OK on success or PK_ERR_TRANSFER otherwise.
Definition at line 1111 of file PoKeysLibDeviceData.c.
References sPoKeysDevice_Data::ActivatedOptions, sPoKeysDevice_Data::ActivationCode, CreateRequest(), sPoKeysDevice::DeviceData, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DeviceActivationClear()
POKEYSDECL int32_t PK_DeviceActivationClear (sPoKeysDevice * device)
Clear activation settings (command 0x8F/0xFF).
Resets all optional features on the device.
Parameters
device Device handle.
Returns
PK_OK on success or PK_ERR_TRANSFER on communication error.
Definition at line 1125 of file PoKeysLibDeviceData.c.
References sPoKeysDevice_Data::ActivatedOptions, CreateRequest(), sPoKeysDevice::DeviceData, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DeviceDataGet()
POKEYSDECL int32_t PK_DeviceDataGet (sPoKeysDevice * device)
Read device identification and feature set.
Executes command 0x05 which returns device series, type and capability information. The results are decoded into sPoKeysDevice_Info and sPoKeysDevice_Data within device.
Parameters
device Pointer to an initialised PoKeys device structure.
Returns
PK_OK on success or an error code from SendRequest().
Definition at line 290 of file PoKeysLibDeviceData.c.
References sPoKeysDevice_Data::ActivatedOptions, sPoKeysNetworkDeviceInfo::AdditionalNetworkOptions, sPoKeysDevice_Data::BuildDate, CompareName(), sPoKeysDevice::connectionType, CreateRequest(), sPoKeysNetworkDeviceInfo::DefaultGateway, sPoKeysDevice::DeviceData, sPoKeysDevice_Data::deviceIsBootloader, sPoKeysDevice_Data::DeviceLockStatus, sPoKeysDevice_Data::DeviceName, sPoKeysDevice_Data::DeviceType, sPoKeysDevice_Data::DeviceTypeID, sPoKeysDevice_Data::DeviceTypeName, sPoKeysNetworkDeviceInfo::DHCP, sPoKeysDevice_Data::FirmwareVersionMajor, sPoKeysDevice_Data::FirmwareVersionMinor, sPoKeysDevice_Data::FWtype, sPoKeysDevice_Data::HWtype, i, sPoKeysDevice_Info::iAdditionalOptions, sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iConnectionSignal, sPoKeysDevice_Info::iCustomDeviceName, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iFailSafeSettings, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice_Info::iInitOutputsStart, sPoKeysDevice_Info::iJoystickAnalogToDigitalMapping, sPoKeysDevice_Info::iJoystickButtonAxisMapping, sPoKeysDevice_Info::iJoystickHATswitch, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice_Info::iKeyRepeatDelay, sPoKeysDevice_Info::iLCD, sPoKeysDevice_Info::iLoadStatus, sPoKeysDevice_Info::iMacros, sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice_Info::iMatrixKeyboardTriggeredMapping, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysNetworkDeviceInfo::IPAddressCurrent, sPoKeysNetworkDeviceInfo::IPAddressSetup, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPoNET, sPoKeysDevice_Info::iPoTLog27support, sPoKeysDevice_Info::iprot1wire, sPoKeysDevice_Info::iprotI2C, sPoKeysDevice_Info::iPulseEngine, sPoKeysDevice_Info::iPulseEnginev2, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice_Info::iSensorList, sPoKeysDevice_Info::iTriggeredKeyMapping, sPoKeysDevice_Info::iUltraFastEncoders, sPoKeysDevice_Info::iWebInterface, sPoKeysDevice::netDeviceData, PK_DeviceID_27E, PK_DeviceID_27U, PK_DeviceID_56E, PK_DeviceID_56U, PK_DeviceID_57E, PK_DeviceID_57E_v0, PK_DeviceID_57U, PK_DeviceID_57U_v0, PK_DeviceID_Bootloader56E, PK_DeviceID_Bootloader56U, PK_DeviceID_OEM1, PK_DeviceID_PoKeys57CNC, PK_DeviceID_PoKeys57CNCdb25, PK_DeviceID_PoKeys57CNCpro4x25, PK_DeviceID_PoKeys57Utest, PK_DeviceID_SerialReader, PK_DeviceID_X15_02_24, PK_DeviceMask_27, PK_DeviceMask_27E, PK_DeviceMask_27U, PK_DeviceMask_55, PK_DeviceMask_55v1, PK_DeviceMask_55v2, PK_DeviceMask_55v3, PK_DeviceMask_56, PK_DeviceMask_56E, PK_DeviceMask_56U, PK_DeviceMask_57, PK_DeviceMask_57CNC, PK_DeviceMask_57CNCdb25, PK_DeviceMask_57CNCpro4x25, PK_DeviceMask_57E, PK_DeviceMask_57U, PK_DeviceMask_57Utest, PK_DeviceMask_58, PK_DeviceMask_Bootloader, PK_DeviceMask_Bootloader55, PK_DeviceMask_Bootloader56, PK_DeviceMask_Bootloader56E, PK_DeviceMask_Bootloader56U, PK_DeviceMask_Bootloader58, PK_DeviceMask_PoKeys16RF, PK_DeviceMask_PoPLC58, PK_DeviceType_NetworkDevice, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice_Data::ProductID, sPoKeysDevice_Info::PWMinternalFrequency, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysDevice_Data::SecondaryFirmwareVersionMajor, sPoKeysDevice_Data::SecondaryFirmwareVersionMinor, SendRequest(), sPoKeysDevice_Data::SerialNumber, sPoKeysNetworkDeviceInfo::Subnetmask, sPoKeysNetworkDeviceInfo::TCPtimeout, and sPoKeysDevice_Data::UserID.
Referenced by InitializeNewDevice(), and PK_InitializeNewDeviceAsync().
PK_DeviceNameSet()
POKEYSDECL int32_t PK_DeviceNameSet (sPoKeysDevice * device)
Write the device name string (command 0x06/0x01).
The first ten bytes of sPoKeysDevice_Data.DeviceName are sent to the device. They become visible in subsequent identification reads.
Parameters
device Target device handle.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1067 of file PoKeysLibDeviceData.c.
References CreateRequest(), sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceName, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_DigitalCounterClear()
POKEYSDECL int32_t PK_DigitalCounterClear (sPoKeysDevice * device)
Reset all digital counters (command 0x1D).
Parameters
device Pointer to an opened device.
Returns
PK_OK on success or a ::PK_ERR code.
Definition at line 611 of file PoKeysLibIO.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_DigitalCounterGet()
POKEYSDECL int32_t PK_DigitalCounterGet (sPoKeysDevice * device)
Read values of all digital counters (command 0xD8).
Transfers up to 13 counter readings at a time and stores them in the pin structures.
Parameters
device Pointer to an opened device.
Returns
PK_OK on success or a ::PK_ERR code.
Definition at line 552 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysPinData::DigitalCounterValue, i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_IsCounterAvailable(), PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by PoKeysHALComponent::PKIO_Update().
PK_DigitalIOGet()
POKEYSDECL int32_t PK_DigitalIOGet (sPoKeysDevice * device)
Read digital input states (command 0xCC/0).
Fills device->Pins with the current logic levels from the device's digital pins.
Parameters
device Pointer to an opened device structure.
Returns
PK_OK on success or a ::PK_ERR code.
Definition at line 411 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysPinData::DigitalValueGet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by PoKeysHALComponent::PKIO_Update().
PK_DigitalIOGetSingle()
POKEYSDECL int32_t PK_DigitalIOGetSingle (sPoKeysDevice * device, uint8_t pinID, uint8_t * pinValue)
Read a single digital pin state (command 0x30).
Parameters
device Pointer to an opened device.
pinID Pin index to read.
pinValue Receives the logic level.
Returns
PK_OK on success or a ::PK_ERR code.
Definition at line 468 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DigitalIOSet()
POKEYSDECL int32_t PK_DigitalIOSet (sPoKeysDevice * device)
Set digital output states (command 0xCC/1).
Prepares a bit mask from device->Pins and writes new output levels to the device.
Parameters
device Pointer to an opened device structure.
Returns
PK_OK on success or a ::PK_ERR value on failure.
Definition at line 389 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysPinData::DigitalValueSet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysPinData::preventUpdate, sPoKeysDevice::request, and SendRequest().
Referenced by PoKeysHALComponent::PKIO_Update().
PK_DigitalIOSetGet()
POKEYSDECL int32_t PK_DigitalIOSetGet (sPoKeysDevice * device)
Atomically set digital outputs and read inputs (command 0xCC).
Writes output states using subcommand 1 and returns the input bitmap in the response.
Parameters
device Pointer to an opened device.
Returns
PK_OK on success or a ::PK_ERR code.
Definition at line 428 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysPinData::DigitalValueGet, sPoKeysPinData::DigitalValueSet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysPinData::preventUpdate, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DigitalIOSetSingle()
POKEYSDECL int32_t PK_DigitalIOSetSingle (sPoKeysDevice * device, uint8_t pinID, uint8_t pinValue)
Set a single digital output (command 0x40).
Parameters
device Pointer to an opened device.
pinID Pin index to modify.
pinValue 1 to set high, 0 to set low.
Returns
PK_OK on success or a ::PK_ERR code.
Definition at line 455 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DisconnectDevice()
POKEYSDECL void PK_DisconnectDevice (sPoKeysDevice * device)
Definition at line 621 of file PoKeysLibCore.c.
References CleanDevice(), sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, DisconnectFromFastUSBInterface, hid_close(), PK_DeviceType_NetworkDevice, and PK_DisconnectNetworkDevice().
Referenced by PK57i_Connect(), and PK57i_Disconnect().
PK_EasySensorsSetupGet()
POKEYSDECL int32_t PK_EasySensorsSetupGet (sPoKeysDevice * device)
Read EasySensors configuration for all channels (command 0x76).
Parameters
device Target device.
Returns
PK_OK on success or error code.
Definition at line 24 of file PoKeysLibEasySensors.c.
References CreateRequest(), sPoKeysDevice::EasySensors, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysEasySensor::sensorFailsafeConfig, sPoKeysEasySensor::sensorID, sPoKeysEasySensor::sensorReadingID, sPoKeysEasySensor::sensorRefreshPeriod, sPoKeysEasySensor::sensorType, and sPoKeysEasySensor::sensorValue.
PK_EasySensorsSetupSet()
POKEYSDECL int32_t PK_EasySensorsSetupSet (sPoKeysDevice * device)
Write EasySensors configuration (command 0x76 write).
Parameters
device Device containing updated EasySensors structure.
Returns
PK_OK on success or error code.
Definition at line 54 of file PoKeysLibEasySensors.c.
References CreateRequest(), sPoKeysDevice::EasySensors, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), sPoKeysEasySensor::sensorFailsafeConfig, sPoKeysEasySensor::sensorID, sPoKeysEasySensor::sensorReadingID, sPoKeysEasySensor::sensorRefreshPeriod, and sPoKeysEasySensor::sensorType.
PK_EasySensorsValueGetAll()
POKEYSDECL int32_t PK_EasySensorsValueGetAll (sPoKeysDevice * device)
Read all EasySensor values (command 0x77).
Parameters
device Target device.
Returns
PK_OK on success or error code.
Definition at line 83 of file PoKeysLibEasySensors.c.
References CreateRequest(), sPoKeysDevice::EasySensors, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysEasySensor::sensorOKstatus, and sPoKeysEasySensor::sensorValue.
PK_EncoderConfigurationGet()
POKEYSDECL int32_t PK_EncoderConfigurationGet (sPoKeysDevice * device)
Retrieve encoder configuration from the device.
This function downloads all encoder related settings such as basic encoder options, channel mappings and key mapping configuration. Fast and ultra fast encoder options are also retrieved when supported. Obtained values are stored into the provided sPoKeysDevice structure.
Parameters
device Pointer to an initialised PoKeys device structure.
Returns
PK_OK on success or a negative error code on failure.
Definition at line 24 of file PoKeysLibEncoders.c.
References sPoKeysEncoder::channelApin, sPoKeysEncoder::channelBpin, CreateRequest(), sPoKeysEncoder::dirAkeyCode, sPoKeysEncoder::dirAkeyModifier, sPoKeysEncoder::dirBkeyCode, sPoKeysEncoder::dirBkeyModifier, sPoKeysEncoder::encoderOptions, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iUltraFastEncoders, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
Referenced by PKEncoder_Setup().
PK_EncoderConfigurationSet()
POKEYSDECL int32_t PK_EncoderConfigurationSet (sPoKeysDevice * device)
Send encoder configuration to the PoKeys device.
All encoder related parameters stored inside the supplied sPoKeysDevice structure are transmitted to the device. This includes basic encoder options, channel assignments, optional key mappings and fast or ultra fast encoder settings.
Parameters
device Pointer to a configured PoKeys device structure.
Returns
PK_OK on success or a negative error code on failure.
Definition at line 106 of file PoKeysLibEncoders.c.
References sPoKeysEncoder::channelApin, sPoKeysEncoder::channelBpin, CreateRequest(), sPoKeysEncoder::dirAkeyCode, sPoKeysEncoder::dirAkeyModifier, sPoKeysEncoder::dirBkeyCode, sPoKeysEncoder::dirBkeyModifier, sPoKeysEncoder::encoderOptions, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iUltraFastEncoders, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
PK_EncoderValuesGet()
POKEYSDECL int32_t PK_EncoderValuesGet (sPoKeysDevice * device)
Read current encoder values from the PoKeys device.
Depending on the available encoder count, this function issues one or more read commands to obtain the encoder counters. The received values are stored in the respective encoderValue pointers within the sPoKeysDevice structure. When ultra fast encoders are present, test mode values are fetched as well.
Parameters
device Pointer to the PoKeys device structure.
Returns
PK_OK on success or a negative error code on failure.
Definition at line 172 of file PoKeysLibEncoders.c.
References CreateRequest(), sPoKeysPEv2::EncoderIndexCount, sPoKeysDevice::Encoders, sPoKeysPEv2::EncoderTicksPerRotation, sPoKeysEncoder::encoderValue, sPoKeysPEv2::EncoderVelocity, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice::info, sPoKeysDevice_Info::iUltraFastEncoders, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_EncoderValuesSet()
POKEYSDECL int32_t PK_EncoderValuesSet (sPoKeysDevice * device)
Write encoder values to the PoKeys device.
The encoderValue fields of the sPoKeysDevice structure are packaged and transmitted to the device, allowing encoder counters to be preset. Only encoders supported by the connected hardware are updated.
Parameters
device Pointer to the PoKeys device structure.
Returns
PK_OK on success or a negative error code on failure.
Definition at line 230 of file PoKeysLibEncoders.c.
References CreateRequest(), sPoKeysDevice::Encoders, sPoKeysEncoder::encoderValue, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_EnumerateFastUSBDevices()
POKEYSDECL int32_t PK_EnumerateFastUSBDevices (void)
Referenced by PK_EnumerateUSBDevices(), and PK_EnumerateUSBDevicesAsync().
PK_EnumerateNetworkDevices()
POKEYSDECL int32_t PK_EnumerateNetworkDevices (sPoKeysNetworkDeviceSummary * devices, uint32_t timeout)
Convenience wrapper for discovering all network attached PoKeys devices.
Calls PK_SearchNetworkDevices() with serialNumberToFind set to 0 so that all responding PoKeys boards are reported.
Parameters
devices Pointer to an array of sPoKeysNetworkDeviceSummary where discovered devices will be stored.
timeout Discovery timeout in milliseconds.
Returns
Number of detected devices.
Definition at line 210 of file PoKeysLibCoreSockets.c.
References PK_SearchNetworkDevices().
PK_EnumerateUSBDevices()
POKEYSDECL int32_t PK_EnumerateUSBDevices (void)
Enumerate PoKeys USB devices.
Two product identifiers are scanned (0x1001 and 0x1002) under the PoLabs vendor ID 0x1DC3. Interfaces are filtered through PKI_CheckInterface() so that only the communication interface (index 1) is counted for devices using the standard HID protocol. For the older fast USB interface the interface number is -1.
Returns
Number of PoKeys devices detected on the USB bus.
Enumerate PoKeys USB devices.
This function performs the same enumeration as PK_EnumerateUSBDevicesAsync() but in a blocking manner.
Returns
Number of detected devices.
Definition at line 38 of file PoKeysLibCore.c.
References hid_enumerate(), hid_free_enumeration(), hid_device_info::interface_number, hid_device_info::next, PK_EnumerateFastUSBDevices(), and PKI_CheckInterface().
Referenced by PK57i_Connect().
PK_FailsafeSettingsGet()
POKEYSDECL int32_t PK_FailsafeSettingsGet (sPoKeysDevice * device)
Read failsafe configuration from the device (command 0x81).
Populates ::sPK_FailsafeSettings in device with the timeout and peripheral states defined by the PoKeys failsafe command.
Parameters
device Pointer to an opened device structure.
Returns
PK_OK on success or a ::PK_ERR code on failure.
Definition at line 25 of file PoKeysLibFailsafe.c.
References sPoKeysFailsafeSettings::bFailSafeEnabled, sPoKeysFailsafeSettings::bFailSafeIO, sPoKeysFailsafeSettings::bFailSafePeripherals, sPoKeysFailsafeSettings::bFailSafePoExtBus, sPoKeysFailsafeSettings::bFailSafePWM, CreateRequest(), sPoKeysDevice::failsafeSettings, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_FailsafeSettingsSet()
POKEYSDECL int32_t PK_FailsafeSettingsSet (sPoKeysDevice * device)
Write failsafe configuration to the device (command 0x81).
The function sends the content of ::sPK_FailsafeSettings stored in device to the PoKeys unit using operation code 0x01.
Parameters
device Pointer to an opened device structure.
Returns
Result of SendRequest() or PK_ERR_NOT_CONNECTED when device is NULL.
Definition at line 44 of file PoKeysLibFailsafe.c.
References sPoKeysFailsafeSettings::bFailSafeEnabled, sPoKeysFailsafeSettings::bFailSafeIO, sPoKeysFailsafeSettings::bFailSafePeripherals, sPoKeysFailsafeSettings::bFailSafePoExtBus, sPoKeysFailsafeSettings::bFailSafePWM, CreateRequest(), sPoKeysDevice::failsafeSettings, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_GetCurrentDeviceConnectionType()
POKEYSDECL int32_t PK_GetCurrentDeviceConnectionType (sPoKeysDevice * device)
Obtain the active connection type for a device.
The field ::connectionType of the device structure holds the current transport that is used for communication. Possible values are defined by ePK_DeviceConnectionType (for example PK_DeviceType_USBDevice or PK_DeviceType_NetworkDevice).
Parameters
device Pointer to an initialised PoKeys device structure.
Returns
The current connection type constant.
Obtain the active connection type for a device.
This is an inline helper used by async routines to determine whether communication is performed over USB, network or fast USB.
Parameters
device PoKeys device handle.
Returns
Connection type constant from ePK_DeviceConnectionType.
Definition at line 84 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType.
PK_GetDebugValues()
POKEYSDECL int32_t PK_GetDebugValues (sPoKeysDevice * device, int32_t * buffer)
Read internal debug registers (command 0xBB).
Four consecutive requests are issued to retrieve 52 debug integers which are stored into buffer.
Parameters
device Device handle.
buffer Destination array of at least 52 int32_t.
Returns
PK_OK on success or PK_ERR_TRANSFER when communication fails.
Definition at line 1374 of file PoKeysLibDeviceData.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_GetFastUSBEnableStatus()
POKEYSDECL int32_t PK_GetFastUSBEnableStatus (sPoKeysDevice * device, uint32_t * state)
Query fast USB interface status (command 0x07/10).
Parameters
device Device handle.
state Receives 1 if enabled.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1408 of file PoKeysLibDeviceData.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_I2CBusScanGetResults()
POKEYSDECL int32_t PK_I2CBusScanGetResults (sPoKeysDevice * device, uint8_t * status, uint8_t * presentDevices, uint8_t iMaxDevices)
Obtain the results of an I\2C bus scan (command 0xDB/0x31).
After PK_I2CBusScanStart() completes, this helper reads the scan bitmap and stores device presence information into presentDevices.
Parameters
device Handle to an opened PoKeys device.
status Receives the scan status (see ePK_I2C_STATUS).
presentDevices Array that receives one byte per address indicating whether a device acknowledged.
iMaxDevices Maximum number of addresses to report (up to 128).
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 133 of file PoKeysLibI2C.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_I2C_STAT_COMPLETE, PK_I2C_STAT_ERR, PK_I2C_STAT_OK, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_I2CBusScanStart()
POKEYSDECL int32_t PK_I2CBusScanStart (sPoKeysDevice * device)
Begin scanning the I\2C bus for devices (command 0xDB/0x30).
The device searches all 7-bit addresses. Completion is checked with PK_I2CBusScanGetResults().
Parameters
device Handle to an opened PoKeys device.
Returns
PK_OK on command acceptance or PK_ERR_NOT_CONNECTED when device is NULL.
Definition at line 125 of file PoKeysLibI2C.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_I2CGetStatus()
POKEYSDECL int32_t PK_I2CGetStatus (sPoKeysDevice * device, uint8_t * activated)
Query whether the I\2C bus is enabled (command 0xDB/0x02).
Parameters
device Handle to an opened PoKeys device.
activated Pointer that receives the activation state.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 33 of file PoKeysLibI2C.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_I2CReadStart()
POKEYSDECL int32_t PK_I2CReadStart (sPoKeysDevice * device, uint8_t address, uint8_t iDataLength)
Initiate an I\2C read transaction (command 0xDB/0x20).
The device is commanded to read iDataLength bytes from the slave at address. The received data is later obtained with PK_I2CReadStatusGet().
Parameters
device Handle to an opened PoKeys device.
address I\2C slave address.
iDataLength Number of bytes to read (032).
Returns
PK_OK on command acceptance or PK_ERR_NOT_CONNECTED when device is NULL.
Definition at line 85 of file PoKeysLibI2C.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_I2CReadStatusGet()
POKEYSDECL int32_t PK_I2CReadStatusGet (sPoKeysDevice * device, uint8_t * status, uint8_t * iReadBytes, uint8_t * buffer, uint8_t iMaxBufferLength)
Obtain the result of an I\2C read command (command 0xDB/0x21).
After a read has been started with PK_I2CReadStart() or PK_I2CWriteAndReadStart(), this function polls the device for completion and copies the returned bytes into buffer.
Parameters
device Handle to an opened PoKeys device.
status Receives the operation status (see ePK_I2C_STATUS).
iReadBytes Number of bytes actually read on success.
buffer Destination buffer for the received data.
iMaxBufferLength Size of buffer in bytes.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL, PK_ERR_TRANSFER on communication failure or PK_ERR_GENERIC when the device reports more data than fits into 32 bytes.
Definition at line 95 of file PoKeysLibI2C.c.
References CreateRequest(), i, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_I2C_STAT_COMPLETE, PK_I2C_STAT_ERR, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_I2CSetStatus()
POKEYSDECL int32_t PK_I2CSetStatus (sPoKeysDevice * device, uint8_t activated)
Enable or disable the I\2C interface (command 0xDB/0x01).
The PoKeys device keeps the I\2C engine enabled at all times. This helper only sends the activation flag for compatibility with older firmware.
Parameters
device Handle to an opened PoKeys device.
activated Non-zero to enable the bus, zero to disable it.
Returns
PK_OK on success or PK_ERR_NOT_CONNECTED if device is NULL.
Definition at line 25 of file PoKeysLibI2C.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_I2CWriteAndReadStart()
POKEYSDECL int32_t PK_I2CWriteAndReadStart (sPoKeysDevice * device, uint8_t address, uint8_t * buffer, uint8_t iDataLengthWrite, uint8_t iDataLengthRead)
Write data and queue a subsequent read (command 0xDB/0x10).
This combines a write and read phase. Up to 32 bytes are written from buffer and the device is instructed to read iDataLengthRead bytes afterwards. The read data is obtained later with PK_I2CReadStatusGet().
Parameters
device Handle to an opened PoKeys device.
address I\2C slave address.
buffer Data to write.
iDataLengthWrite Number of bytes to write (032).
iDataLengthRead Number of bytes expected to be read back.
Returns
PK_OK on command acceptance or PK_ERR_NOT_CONNECTED when device is NULL.
Definition at line 59 of file PoKeysLibI2C.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_I2CWriteStart()
POKEYSDECL int32_t PK_I2CWriteStart (sPoKeysDevice * device, uint8_t address, uint8_t * buffer, uint8_t iDataLength)
Initiate an I\2C write transaction (command 0xDB/0x10).
Up to 32 bytes from buffer are copied and sent to the device using PK_CMD_I2C_COMMUNICATION with subcommand 0x10.
Parameters
device Handle to an opened PoKeys device.
address 7-bit I\2C slave address.
buffer Data to transmit.
iDataLength Number of bytes to send (032).
Returns
PK_OK on command acceptance or PK_ERR_NOT_CONNECTED when device is NULL.
Definition at line 44 of file PoKeysLibI2C.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_I2CWriteStatusGet()
POKEYSDECL int32_t PK_I2CWriteStatusGet (sPoKeysDevice * device, uint8_t * status)
Retrieve the status of the last I\2C write operation (command 0xDB/0x11).
Parameters
device Handle to an opened PoKeys device.
status Receives the result (see ePK_I2C_STATUS).
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 74 of file PoKeysLibI2C.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_IsCounterAvailable()
POKEYSDECL int32_t PK_IsCounterAvailable (sPoKeysDevice * device, uint8_t pinID)
Check if a pin supports a counter (command 0xC0/0x01).
Queries device capabilities to determine if the specified pin can operate as a digital counter input.
Parameters
device Pointer to an opened device structure.
pinID Index of the pin to test.
Returns
Non-zero if the counter is supported, zero otherwise.
Definition at line 271 of file PoKeysLibIO.c.
References sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceTypeID, and PK_IsCounterAvailableByDevice().
Referenced by InitializeNewDevice(), PK_DigitalCounterGetAsync(), PK_DigitalCounterParse(), PK_InitializeNewDeviceAsync(), and PK_PinCounterConfigurationParse().
PK_IsCounterAvailableByDevice()
POKEYSDECL int32_t PK_IsCounterAvailableByDevice (uint32_t deviceTypeMask, uint8_t pinID)
Check counter support for a device type.
Parameters
deviceTypeMask Device type identifier.
pinID Pin index to check.
Returns
Non-zero if a counter can be used.
Definition at line 293 of file PoKeysLibIO.c.
References PK_DeviceMask_56, PK_DeviceMask_57, PK_DeviceMask_57CNC, PK_DeviceMask_57CNCdb25, PK_DeviceMask_57CNCpro4x25, PK_DeviceMask_Bootloader, and PK_DeviceMask_PoPLC58.
Referenced by PK_CheckPinCapabilityByDevice(), and PK_CheckPinCapabilityByTypeID().
PK_IsCounterAvailableByTypeID()
POKEYSDECL int32_t PK_IsCounterAvailableByTypeID (uint32_t deviceTypeID, uint8_t pinID)
Check counter availability by device ID.
Parameters
deviceTypeID Firmware device identifier.
pinID Pin index to check.
Returns
Non-zero if a counter can be used.
Definition at line 335 of file PoKeysLibIO.c.
References PK_DeviceID_27E, PK_DeviceID_27U, PK_DeviceID_55v1, PK_DeviceID_55v2, PK_DeviceID_55v3, PK_DeviceID_56E, PK_DeviceID_56U, PK_DeviceID_57E, PK_DeviceID_57E_v0, PK_DeviceID_57U, PK_DeviceID_57U_v0, PK_DeviceID_58EU, PK_DeviceID_PoKeys57CNC, PK_DeviceID_PoKeys57CNCpro4x25, and PK_DeviceID_PoPLC58.
PK_LCDChangeMode()
POKEYSDECL int32_t PK_LCDChangeMode (sPoKeysDevice * device, uint8_t mode)
Switch LCD operating mode.
Allows toggling between PK_LCD_MODE_DIRECT and PK_LCD_MODE_BUFFERED by issuing command PK_CMD_LCD_OPERATION with opcode 0x80.
Parameters
device Pointer to an initialized device structure.
mode Desired mode constant.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 114 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDClear()
POKEYSDECL int32_t PK_LCDClear (sPoKeysDevice * device)
Clear the LCD display.
Uses command PK_CMD_LCD_OPERATION with opcode 0x10 to erase the entire screen. Valid only in direct mode.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 136 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDConfigurationGet()
POKEYSDECL int32_t PK_LCDConfigurationGet (sPoKeysDevice * device)
Retrieve LCD configuration from the device.
Sends PK_CMD_LCD_CONFIGURATION with parameter 1 and stores returned parameters in the device's LCD structure.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 24 of file PoKeysLibLCD.c.
References sPoKeysLCD::Columns, sPoKeysLCD::Configuration, CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysLCD::Rows, and SendRequest().
PK_LCDConfigurationSet()
POKEYSDECL int32_t PK_LCDConfigurationSet (sPoKeysDevice * device)
Write LCD configuration to the device.
Transfers mode and size parameters stored in the LCD fields and performs initialisation and screen clear afterwards.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 41 of file PoKeysLibLCD.c.
References sPoKeysLCD::Columns, sPoKeysLCD::Configuration, CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysLCD::Rows, and SendRequest().
PK_LCDDisplayOnOffControl()
POKEYSDECL int32_t PK_LCDDisplayOnOffControl (sPoKeysDevice * device, uint8_t displayOnOff, uint8_t cursorOnOff, uint8_t cursorBlinking)
Control LCD display, cursor and blinking.
Command PK_CMD_LCD_OPERATION with opcode 0x60 configures the display on/off, cursor visibility and blinking options.
Parameters
device Pointer to an initialized device structure.
displayOnOff Non-zero to enable the display.
cursorOnOff Non-zero to show the cursor.
cursorBlinking Non-zero to enable blinking cursor.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 197 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDEntryModeSet()
POKEYSDECL int32_t PK_LCDEntryModeSet (sPoKeysDevice * device, uint8_t cursorMoveDirection, uint8_t displayShift)
Configure the LCD entry mode register.
Uses command PK_CMD_LCD_OPERATION with opcode 0x50 to set cursor movement direction and display shifting.
Parameters
device Pointer to an initialized device structure.
cursorMoveDirection 1 for increment, 0 for decrement.
displayShift Non-zero to shift display.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 185 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDInit()
POKEYSDECL int32_t PK_LCDInit (sPoKeysDevice * device)
Initialise the LCD controller.
Only valid when operating in PK_LCD_MODE_DIRECT mode. Issues command PK_CMD_LCD_OPERATION with opcode 0 to reset the display.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 126 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDMoveCursor()
POKEYSDECL int32_t PK_LCDMoveCursor (sPoKeysDevice * device, uint8_t row, uint8_t column)
Move the LCD cursor to a specific position.
Sends command PK_CMD_LCD_OPERATION with opcode 0x20 where param1 is the column and param2 the row.
Parameters
device Pointer to an initialized device structure.
row Target row number (starting from 0).
column Target column number (starting from 0).
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 146 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDPrint()
POKEYSDECL int32_t PK_LCDPrint (sPoKeysDevice * device, uint8_t * text, uint8_t textLen)
Print a string on the LCD.
In direct mode the text is transmitted using command PK_CMD_LCD_OPERATION with opcode 0x30. The string length is limited to 20 characters.
Parameters
device Pointer to an initialized device structure.
text Buffer containing the characters to display.
textLen Number of characters in text.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 156 of file PoKeysLibLCD.c.
References CreateRequest(), i, sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDPutChar()
POKEYSDECL int32_t PK_LCDPutChar (sPoKeysDevice * device, uint8_t character)
Output a single character on the LCD.
Uses command PK_CMD_LCD_OPERATION with opcode 0x31. Only valid in direct mode.
Parameters
device Pointer to an initialized device structure.
character Character to display.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 174 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDSetCustomCharacters()
POKEYSDECL int32_t PK_LCDSetCustomCharacters (sPoKeysDevice * device)
Upload custom character patterns to the LCD.
Transfers the eight custom character bitmaps stored in sPoKeysLCD::customCharacters using the command PK_CMD_LCD_OPERATION with opcode 0x40.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 92 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysLCD::customCharacters, i, sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
Referenced by Update_LCD().
PK_LCDUpdate()
POKEYSDECL int32_t PK_LCDUpdate (sPoKeysDevice * device)
Update LCD display using buffered lines.
Only lines flagged in sPoKeysLCD::RowRefreshFlags are transferred to the device with command PK_CMD_LCD_OPERATION opcode 0x85.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 62 of file PoKeysLibLCD.c.
References CreateRequest(), i, sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, sPoKeysLCD::line1, sPoKeysLCD::line2, sPoKeysLCD::line3, sPoKeysLCD::line4, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysLCD::RowRefreshFlags, and SendRequest().
Referenced by Update_LCD().
PK_MatrixKBConfigurationGet()
POKEYSDECL int32_t PK_MatrixKBConfigurationGet (sPoKeysDevice * device)
Definition at line 24 of file PoKeysLibMatrixKB.c.
References CreateRequest(), sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice_Info::iMatrixKeyboardTriggeredMapping, sPoKeysDevice::info, sMatrixKeyboard::keyMappingKeyCode, sMatrixKeyboard::keyMappingKeyCodeUp, sMatrixKeyboard::keyMappingKeyModifier, sMatrixKeyboard::keyMappingKeyModifierUp, sMatrixKeyboard::keyMappingTriggeredKey, sMatrixKeyboard::macroMappingOptions, sPoKeysDevice::matrixKB, sMatrixKeyboard::matrixKBcolumnsPins, sMatrixKeyboard::matrixKBconfiguration, sMatrixKeyboard::matrixKBheight, sMatrixKeyboard::matrixKBrowsPins, sMatrixKeyboard::matrixKBScanningDecimation, sMatrixKeyboard::matrixKBwidth, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by Config_MatrixKB(), and Update_MatrixKB().
PK_MatrixKBConfigurationSet()
POKEYSDECL int32_t PK_MatrixKBConfigurationSet (sPoKeysDevice * device)
Definition at line 97 of file PoKeysLibMatrixKB.c.
References CreateRequest(), sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice_Info::iMatrixKeyboardTriggeredMapping, sPoKeysDevice::info, sMatrixKeyboard::keyMappingKeyCode, sMatrixKeyboard::keyMappingKeyCodeUp, sMatrixKeyboard::keyMappingKeyModifier, sMatrixKeyboard::keyMappingKeyModifierUp, sMatrixKeyboard::keyMappingTriggeredKey, sMatrixKeyboard::macroMappingOptions, sPoKeysDevice::matrixKB, sMatrixKeyboard::matrixKBcolumnsPins, sMatrixKeyboard::matrixKBconfiguration, sMatrixKeyboard::matrixKBheight, sMatrixKeyboard::matrixKBrowsPins, sMatrixKeyboard::matrixKBScanningDecimation, sMatrixKeyboard::matrixKBwidth, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_MatrixKBStatusGet()
POKEYSDECL int32_t PK_MatrixKBStatusGet (sPoKeysDevice * device)
Definition at line 202 of file PoKeysLibMatrixKB.c.
References CreateRequest(), sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice::info, sPoKeysDevice::matrixKB, sMatrixKeyboard::matrixKBvalues, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by Update_MatrixKB().
PK_MatrixLEDConfigurationGet()
POKEYSDECL int32_t PK_MatrixLEDConfigurationGet (sPoKeysDevice * device)
Definition at line 40 of file PoKeysLibMatrixLED.c.
References sPoKeysMatrixLED::columns, CreateRequest(), sPoKeysMatrixLED::displayEnabled, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice::MatrixLED, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysMatrixLED::rows, and SendRequest().
PK_MatrixLEDConfigurationSet()
POKEYSDECL int32_t PK_MatrixLEDConfigurationSet (sPoKeysDevice * device)
Definition at line 24 of file PoKeysLibMatrixLED.c.
References sPoKeysMatrixLED::columns, CreateRequest(), sPoKeysMatrixLED::displayEnabled, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice::MatrixLED, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysMatrixLED::rows, and SendRequest().
PK_MatrixLEDUpdate()
POKEYSDECL int32_t PK_MatrixLEDUpdate (sPoKeysDevice * device)
Definition at line 61 of file PoKeysLibMatrixLED.c.
References CreateRequest(), sPoKeysMatrixLED::data, i, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice::MatrixLED, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysMatrixLED::RefreshFlag, sPoKeysDevice::request, and SendRequest().
PK_NetworkConfigurationSet()
POKEYSDECL int32_t PK_NetworkConfigurationSet (sPoKeysDevice * device)
Write Ethernet configuration block (command 0xE0/10).
The network parameters from ::sPoKeysNetworkDevice are encoded and transmitted to the device.
Parameters
device Pointer to the PoKeys device with network data filled.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1085 of file PoKeysLibDeviceData.c.
References sPoKeysNetworkDeviceInfo::AdditionalNetworkOptions, CreateRequest(), sPoKeysNetworkDeviceInfo::DefaultGateway, sPoKeysNetworkDeviceInfo::DHCP, sPoKeysNetworkDeviceInfo::IPAddressCurrent, sPoKeysNetworkDeviceInfo::IPAddressSetup, sPoKeysDevice::netDeviceData, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), sPoKeysNetworkDeviceInfo::Subnetmask, and sPoKeysNetworkDeviceInfo::TCPtimeout.
PK_OEM_Martelli_SetMode()
POKEYSDECL int32_t PK_OEM_Martelli_SetMode (sPoKeysDevice * device, uint8_t mode)
PK_OEM_Martelli_SetRate()
POKEYSDECL int32_t PK_OEM_Martelli_SetRate (sPoKeysDevice * device, uint32_t rate)
PK_OEM_Martelli_SetThreshold()
POKEYSDECL int32_t PK_OEM_Martelli_SetThreshold (sPoKeysDevice * device, uint32_t threshold)
PK_PEv2_AdditionalParametersGet()
POKEYSDECL int32_t PK_PEv2_AdditionalParametersGet (sPoKeysDevice * device)
Read miscellaneous pulse engine parameters.
Executes PEV2_CMD_CONFIGURE_MISC (0x06) with param3=1. The emergency input pin is returned in byte 8 of the response and stored in PEv2.EmergencyInputPin.
Parameters
device Target device.
Returns
PK_OK on success or communication error code.
Definition at line 129 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::EmergencyInputPin, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by PEv2_AdditionalParametersGet(), and PEv2_AdditionalParametersSet().
PK_PEv2_AdditionalParametersSet()
POKEYSDECL int32_t PK_PEv2_AdditionalParametersSet (sPoKeysDevice * device)
Configure miscellaneous pulse engine options.
Uses command PEV2_CMD_CONFIGURE_MISC (0x06) with param1=1. Byte 8 of the request carries the emergency input pin number.
Parameters
device Target device.
Returns
PK_OK on success, otherwise error code.
Definition at line 143 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::EmergencyInputPin, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
Referenced by PEv2_AdditionalParametersSet().
PK_PEv2_AxisConfigurationGet()
POKEYSDECL int32_t PK_PEv2_AxisConfigurationGet (sPoKeysDevice * device)
Retrieve configuration for one axis.
Issues PEV2_CMD_GET_AXIS_CONFIGURATION (0x10). param1 selects the axis and the response returns a 44 byte block describing limits, speeds and filter options which is copied into the PEv2 structure.
Parameters
device PoKeys device instance (uses PEv2.param1).
Returns
PK_OK on success or error code on failure.
Definition at line 157 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxesConfig, sPoKeysPEv2::AxesSwitchConfig, sPoKeysPEv2::AxisEnableOutputPins, sPoKeysPEv2::AxisSignalOptions, CreateRequest(), sPoKeysPEv2::FilterHomeSwitch, sPoKeysPEv2::FilterLimitMSwitch, sPoKeysPEv2::FilterLimitPSwitch, sPoKeysPEv2::FilterProbeInput, sPoKeysPEv2::HomeBackOffDistance, sPoKeysPEv2::HomingAlgorithm, sPoKeysPEv2::HomingReturnSpeed, sPoKeysPEv2::HomingSpeed, sPoKeysPEv2::InvertAxisEnable, sPoKeysPEv2::MaxAcceleration, sPoKeysPEv2::MaxDecceleration, sPoKeysPEv2::MaxSpeed, sPoKeysPEv2::MPGjogDivider, sPoKeysPEv2::MPGjogEncoder, sPoKeysPEv2::MPGjogMultiplier, sPoKeysPEv2::param1, sPoKeysDevice::PEv2, sPoKeysPEv2::PinHomeSwitch, sPoKeysPEv2::PinLimitMSwitch, sPoKeysPEv2::PinLimitPSwitch, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysPEv2::SoftLimitMaximum, and sPoKeysPEv2::SoftLimitMinimum.
Referenced by PoKeysHALComponent::PEv2_AxisConfigurationGet().
PK_PEv2_AxisConfigurationSet()
POKEYSDECL int32_t PK_PEv2_AxisConfigurationSet (sPoKeysDevice * device)
Send configuration data for one axis.
Command PEV2_CMD_SET_AXIS_CONFIGURATION (0x11) writes the same structure returned by PK_PEv2_AxisConfigurationGet. param1 selects the axis and bytes 8 onward contain the configuration fields such as limits and motion parameters.
Parameters
device PoKeys device instance.
Returns
PK_OK on success or error code on failure.
Definition at line 211 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxesConfig, sPoKeysPEv2::AxesSwitchConfig, sPoKeysPEv2::AxisEnableOutputPins, sPoKeysPEv2::AxisSignalOptions, CreateRequest(), sPoKeysPEv2::FilterHomeSwitch, sPoKeysPEv2::FilterLimitMSwitch, sPoKeysPEv2::FilterLimitPSwitch, sPoKeysPEv2::FilterProbeInput, sPoKeysPEv2::HomeBackOffDistance, sPoKeysPEv2::HomingAlgorithm, sPoKeysPEv2::HomingReturnSpeed, sPoKeysPEv2::HomingSpeed, sPoKeysPEv2::InvertAxisEnable, sPoKeysPEv2::MaxAcceleration, sPoKeysPEv2::MaxDecceleration, sPoKeysPEv2::MaxSpeed, sPoKeysPEv2::MPGjogDivider, sPoKeysPEv2::MPGjogEncoder, sPoKeysPEv2::MPGjogMultiplier, sPoKeysPEv2::param1, sPoKeysDevice::PEv2, sPoKeysPEv2::PinHomeSwitch, sPoKeysPEv2::PinLimitMSwitch, sPoKeysPEv2::PinLimitPSwitch, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, sPoKeysDevice::request, SendRequest(), sPoKeysPEv2::SoftLimitMaximum, and sPoKeysPEv2::SoftLimitMinimum.
Referenced by PoKeysHALComponent::PEv2_AxisConfigurationSet().
PK_PEv2_BacklashCompensationSettings_Get()
POKEYSDECL int32_t PK_PEv2_BacklashCompensationSettings_Get (sPoKeysDevice * device)
Retrieve backlash compensation parameters.
Sends PEV2_CMD_GET_BACKLASH_SETTINGS (0x40) and parses the backlash width, acceleration and register values for each axis from the response bytes.
Parameters
device Target device.
Returns
PK_OK on success or communication error.
Definition at line 679 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::BacklashAcceleration, sPoKeysPEv2::BacklashCompensationEnabled, sPoKeysPEv2::BacklashCompensationMaxSpeed, sPoKeysPEv2::BacklashRegister, sPoKeysPEv2::BacklashWidth, CreateRequest(), i, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_BacklashCompensationSettings_Set()
POKEYSDECL int32_t PK_PEv2_BacklashCompensationSettings_Set (sPoKeysDevice * device)
Write backlash compensation parameters.
Command PEV2_CMD_SET_BACKLASH_SETTINGS (0x41) sends the same structure as returned by the getter to configure backlash for each axis.
Parameters
device Target device with values stored in the PEv2 structure.
Returns
PK_OK on success or error code.
Definition at line 702 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::BacklashAcceleration, sPoKeysPEv2::BacklashCompensationEnabled, sPoKeysPEv2::BacklashCompensationMaxSpeed, sPoKeysPEv2::BacklashWidth, CreateRequest(), i, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_BufferClear()
POKEYSDECL int32_t PK_PEv2_BufferClear (sPoKeysDevice * device)
Clear the motion buffer in the device.
Command PEV2_CMD_CLEAR_BUFFER (0xF0) resets the internal motion queue.
Parameters
device Target device.
Returns
Result of SendRequest.
Definition at line 449 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_BufferFill()
POKEYSDECL int32_t PK_PEv2_BufferFill (sPoKeysDevice * device)
Send a portion of the motion buffer (8-bit variant).
Uses command PEV2_CMD_FILL_BUFFER_8BIT (0xFF). param1 holds the number of entries to copy and param2 carries the enable mask. Up to 56 bytes of motion data are placed in bytes 8-63. The response returns the number of accepted entries in byte 2 and refreshes engine status via PK_PEv2_DecodeStatus.
Parameters
device PoKeys device containing the new buffer.
Returns
PK_OK when successful or a communication error.
Definition at line 361 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_BufferFill_16()
POKEYSDECL int32_t PK_PEv2_BufferFill_16 (sPoKeysDevice * device)
Send 16-bit motion buffer entries.
Identical to PK_PEv2_BufferFill but uses the 16-bit buffer command ID 0xFE. Payload layout and response are the same as in the 8-bit version.
Parameters
device PoKeys device containing the new data.
Returns
PK_OK on success or a transfer error.
Definition at line 385 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_BufferFillLarge()
POKEYSDECL int32_t PK_PEv2_BufferFillLarge (sPoKeysDevice * device)
Transfer a large block of 8-bit motion data.
Uses the multipart packet command PK_CMD_MULTIPART_PACKET with subcommand 0xFF. param2 specifies entry count and param3 the axis enable mask. The payload contains 448 bytes of buffer data stored in multiPartData.
Parameters
device Target device.
Returns
PK_OK on success or error code from transfer.
Definition at line 406 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysDevice::multiPartData, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest_multiPart().
PK_PEv2_BufferFillLarge_16()
POKEYSDECL int32_t PK_PEv2_BufferFillLarge_16 (sPoKeysDevice * device)
Large transfer of 16-bit motion data.
Same as PK_PEv2_BufferFillLarge but using subcommand 0xFE for 16-bit entries.
Parameters
device Target device.
Returns
PK_OK on success or communication error.
Definition at line 427 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysDevice::multiPartData, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest_multiPart().
PK_PEv2_ExternalOutputsGet()
POKEYSDECL int32_t PK_PEv2_ExternalOutputsGet (sPoKeysDevice * device)
Read the state of external outputs.
Using PEV2_CMD_SET_OUTPUTS (0x04) with param3=1 the device returns relay and open-collector output states in bytes 3 and 4 of the response which are stored in the PEv2 structure.
Parameters
device Target device.
Returns
PK_OK when data is read successfully, otherwise error code from SendRequest.
Definition at line 333 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::ExternalOCOutputs, sPoKeysPEv2::ExternalRelayOutputs, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by PEv2_ExternalOutputsSet().
PK_PEv2_ExternalOutputsSet()
POKEYSDECL int32_t PK_PEv2_ExternalOutputsSet (sPoKeysDevice * device)
Update relay and open-collector outputs.
Command PEV2_CMD_SET_OUTPUTS (0x04) uses param1 for relay outputs and param2 for open-collector outputs.
Parameters
device Device with desired output states stored in the PEv2 structure.
Returns
Result of SendRequest.
Definition at line 348 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::ExternalOCOutputs, sPoKeysPEv2::ExternalRelayOutputs, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
Referenced by PEv2_ExternalOutputsSet().
PK_PEv2_HomingFinish()
POKEYSDECL int32_t PK_PEv2_HomingFinish (sPoKeysDevice * device)
Finish the homing procedure.
Sends PEV2_CMD_FINISH_HOMING (0x22). param1 sets the new engine state after homing and param2 should be 1 as required by the protocol.
Parameters
device PoKeys device instance.
Returns
Result of SendRequest.
Definition at line 486 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineStateSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_HomingStart()
POKEYSDECL int32_t PK_PEv2_HomingStart (sPoKeysDevice * device)
Begin the homing sequence.
Command PEV2_CMD_START_HOMING (0x21). param1 holds the axis mask and bytes 8-39 carry home offset values for each axis.
Parameters
device Target device with offsets stored in PEv2.HomeOffsets.
Returns
Result of SendRequest.
Definition at line 472 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::HomeOffsets, sPoKeysPEv2::HomingStartMaskSetup, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_InternalDriversConfigurationGet()
POKEYSDECL int32_t PK_PEv2_InternalDriversConfigurationGet (sPoKeysDevice * device)
Read configuration of internal motor drivers.
Command PEV2_CMD_GET_INTERNAL_DRIVERS (0x18) returns step mode and current settings for four integrated drivers.
Parameters
device Target device.
Returns
PK_OK on success or error code.
Definition at line 928 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::InternalDriverCurrentConfig, sPoKeysPEv2::InternalDriverStepConfig, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_InternalDriversConfigurationSet()
POKEYSDECL int32_t PK_PEv2_InternalDriversConfigurationSet (sPoKeysDevice * device)
Set configuration of internal motor drivers.
Uses PEV2_CMD_SET_INTERNAL_DRIVERS (0x19) with step and current settings for the four integrated drivers placed in the request payload.
Parameters
device Device providing new settings via PEv2 fields.
Returns
Result of SendRequest.
Definition at line 948 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::InternalDriverCurrentConfig, sPoKeysPEv2::InternalDriverStepConfig, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PositionSet()
POKEYSDECL int32_t PK_PEv2_PositionSet (sPoKeysDevice * device)
Set current axis positions.
Command PEV2_CMD_SET_AXIS_POSITION (0x03) updates the internal position registers. param2 is a bit mask selecting which axes are affected and bytes 8-39 carry the new 32-bit positions for all axes.
Parameters
device Device containing the new positions in PEv2.PositionSetup.
Returns
PK_OK on success or error code on failure.
Definition at line 265 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::param2, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, sPoKeysPEv2::PositionSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ProbingFinish()
POKEYSDECL int32_t PK_PEv2_ProbingFinish (sPoKeysDevice * device)
Complete the probing cycle and read the result.
Command PEV2_CMD_FINISH_PROBING (0x24) returns the probe position in bytes 8-39 and status bits in byte 40. The engine state is also reset to STOPPED.
Parameters
device Device receiving the probe result.
Returns
PK_OK when the response is valid or an error code.
Definition at line 532 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysPEv2::ProbePosition, sPoKeysPEv2::ProbeStatus, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_ProbingFinishSimple()
POKEYSDECL int32_t PK_PEv2_ProbingFinishSimple (sPoKeysDevice * device)
Finish probing without changing engine state.
Uses PEV2_CMD_FINISH_PROBING (0x24) with param1=1. The probe result is returned like in PK_PEv2_ProbingFinish but the engine state is not reset.
Parameters
device Device receiving the result.
Returns
PK_OK if successful or error code.
Definition at line 549 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysPEv2::ProbePosition, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_ProbingHybridStart()
POKEYSDECL int32_t PK_PEv2_ProbingHybridStart (sPoKeysDevice * device)
Start probing with an external controller.
Uses PEV2_CMD_START_PROBING with param2=1 for the hybrid probing mode. Only the probe input number and polarity are sent in bytes 44-45.
Parameters
device Device configured for probing.
Returns
Result of SendRequest.
Definition at line 517 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ProbeInput, sPoKeysPEv2::ProbeInputPolarity, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ProbingStart()
POKEYSDECL int32_t PK_PEv2_ProbingStart (sPoKeysDevice * device)
Start a probing move.
Command PEV2_CMD_START_PROBING (0x23) uses param1 as axis selection mask. Bytes 8-39 hold maximum probe positions, byte 40 holds probe speed and bytes 44-45 define probe input and polarity.
Parameters
device Device configured with probe parameters.
Returns
Result of SendRequest.
Definition at line 501 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ProbeInput, sPoKeysPEv2::ProbeInputPolarity, sPoKeysPEv2::ProbeMaxPosition, sPoKeysPEv2::ProbeSpeed, sPoKeysPEv2::ProbeStartMaskSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineMove()
POKEYSDECL int32_t PK_PEv2_PulseEngineMove (sPoKeysDevice * device)
Execute a move using reference positions or speeds.
Command PEV2_CMD_MOVE (0x20) accepts eight 32-bit position or speed values located in bytes 8-39 of the request. The values are taken from PEv2.ReferencePositionSpeed.
Parameters
device Active PoKeys device.
Returns
Result of SendRequest.
Definition at line 297 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ReferencePositionSpeed, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineMovePV()
POKEYSDECL int32_t PK_PEv2_PulseEngineMovePV (sPoKeysDevice * device)
Perform a move in position/velocity mode.
Uses command PEV2_CMD_MOVE_PV (0x25). In addition to the 32-bit reference positions, bytes 40-55 of the request include 16-bit velocity ratios derived from ReferenceVelocityPV. param2 carries the enable mask.
Parameters
device Active PoKeys device.
Returns
PK_OK or error from SendRequest.
Definition at line 312 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::param2, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ReferencePositionSpeed, sPoKeysPEv2::ReferenceVelocityPV, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineReboot()
POKEYSDECL int32_t PK_PEv2_PulseEngineReboot (sPoKeysDevice * device)
Reboot the pulse engine firmware.
Issues PEV2_CMD_REBOOT (0x05).
Parameters
device Target device.
Returns
Result of SendRequest.
Definition at line 460 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineSetup()
POKEYSDECL int32_t PK_PEv2_PulseEngineSetup (sPoKeysDevice * device)
Configure the pulse engine parameters.
Uses command PEV2_CMD_SETUP (0x01). The request payload contains enable flags, buffer size and emergency switch polarity in bytes 8-13.
Parameters
device Pointer to the PoKeys device.
Returns
PK_OK on success or an error code on failure.
Definition at line 108 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxisEnabledStatesMask, sPoKeysPEv2::ChargePumpEnabled, CreateRequest(), sPoKeysPEv2::EmergencySwitchPolarity, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineBufferSize, sPoKeysPEv2::PulseEngineEnabled, sPoKeysPEv2::PulseGeneratorType, sPoKeysDevice::request, and SendRequest().
Referenced by PEv2_PulseEngineSetup().
PK_PEv2_PulseEngineStateSet()
POKEYSDECL int32_t PK_PEv2_PulseEngineStateSet (sPoKeysDevice * device)
Change the operating state of the pulse engine.
Sends PEV2_CMD_SET_STATE (0x02). Parameters specify the desired engine state, limit override flag and axis enable mask which are placed in param1, param2 and param3.
Parameters
device Pointer to a PoKeys device with setup values stored in the PEv2 structure.
Returns
PK_OK on success or error code.
Definition at line 285 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxisEnabledMask, CreateRequest(), sPoKeysPEv2::LimitOverrideSetup, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineStateSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_Status2Get()
POKEYSDECL int32_t PK_PEv2_Status2Get (sPoKeysDevice * device)
Obtain extended status information.
Executes command PEV2_CMD_GET_STATUS2 (0x08) of PK_CMD_PULSE_ENGINE_V2. The response provides the count of dedicated limit and home inputs which is stored in sPoKeysPEv2.
Parameters
device Target device.
Returns
PK_OK on success or an error code from communication.
Definition at line 93 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::DedicatedHomeInputs, sPoKeysPEv2::DedicatedLimitNInputs, sPoKeysPEv2::DedicatedLimitPInputs, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by PEv2_Status2Get(), and PoKeysHALComponent::PKPEv2_Setup().
PK_PEv2_StatusGet()
POKEYSDECL int32_t PK_PEv2_StatusGet (sPoKeysDevice * device)
Retrieve pulse engine status.
Sends command PEV2_CMD_GET_STATUS (0x00) under PK_CMD_PULSE_ENGINE_V2. param1 is used as a handshake value and the response updates the sPoKeysPEv2 status structure with axis states, current position and engine info.
Parameters
device Pointer to the PoKeys device.
Returns
PK_OK when successful, error code otherwise.
Definition at line 64 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineActivated, sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, and SendRequest().
Referenced by PEv2_StatusGet(), PoKeysHALComponent::PKPEv2_ReadIniFile(), and PoKeysHALComponent::PKPEv2_Setup().
PK_PEv2_SyncedPWMSetup()
POKEYSDECL int32_t PK_PEv2_SyncedPWMSetup (sPoKeysDevice * device, uint8_t enabled, uint8_t srcAxis, uint8_t dstPWMChannel)
Configure synchronized PWM output.
Command PEV2_CMD_SETUP_SYNCED_PWM (0x0A). The request enables or disables synchronized PWM generation based on an axis position.
Parameters
device Target device.
enabled Non-zero to enable feature.
srcAxis Source axis index (0-based).
dstPWMChannel PWM output channel.
Returns
PK_OK on success or error code.
Definition at line 723 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_SyncOutputsSetup()
POKEYSDECL int32_t PK_PEv2_SyncOutputsSetup (sPoKeysDevice * device)
Configure synchronized digital outputs.
Command PEV2_CMD_SETUP_SYNCED_DIGITAL (0x0B) maps a group of outputs to follow the position of an axis.
Parameters
device Device with mapping information stored in SyncFastOutputsMapping and axis ID in SyncFastOutputsAxisID.
Returns
PK_OK on success or error code.
Definition at line 736 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), sPoKeysPEv2::SyncFastOutputsAxisID, and sPoKeysPEv2::SyncFastOutputsMapping.
PK_PEv2_ThreadingCancel()
POKEYSDECL int32_t PK_PEv2_ThreadingCancel (sPoKeysDevice * device)
Cancel a prepared threading operation.
Command PEV2_CMD_CANCEL_THREADING (0x34) clears any pending trigger preparation.
Parameters
device PoKeys device.
Returns
Result of SendRequest.
Definition at line 617 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingForceTriggerReady()
POKEYSDECL int32_t PK_PEv2_ThreadingForceTriggerReady (sPoKeysDevice * device)
Force trigger ready state.
Command PEV2_CMD_FORCE_TRIGGER_READY (0x31) immediately sets the trigger as ready for threading.
Parameters
device PoKeys device.
Returns
PK_OK on success or error code.
Definition at line 578 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingPrepareForTrigger()
POKEYSDECL int32_t PK_PEv2_ThreadingPrepareForTrigger (sPoKeysDevice * device)
Prepare the spindle threading trigger.
Executes PEV2_CMD_PREPARE_TRIGGER (0x30) which readies the device for the next threading operation.
Parameters
device Target device.
Returns
PK_OK on success or error code from communication.
Definition at line 565 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingRelease()
POKEYSDECL int32_t PK_PEv2_ThreadingRelease (sPoKeysDevice * device)
Release the threading trigger.
Sends PEV2_CMD_RELEASE_TRIGGER (0x33) which aborts waiting for the spindle index.
Parameters
device Target device.
Returns
Result of SendRequest.
Definition at line 604 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingSetup()
POKEYSDECL int32_t PK_PEv2_ThreadingSetup (sPoKeysDevice * device, uint8_t sensorMode, uint16_t ticksPerRevolution, uint16_t tagetSpindleRPM, uint16_t filterGainSpeed, uint16_t filterGainPosition)
Configure spindle threading parameters.
Uses PEV2_CMD_SET_THREADING_PARAMS (0x36). The request provides sensor mode and filter settings in the payload while TriggerIngnoredAxisMask is stored in byte 20.
Parameters
device Target device.
sensorMode Sensor mode selector.
ticksPerRevolution Encoder ticks per spindle revolution.
tagetSpindleRPM Desired spindle speed.
filterGainSpeed Speed filter gain.
filterGainPosition Position filter gain.
Returns
PK_OK on success or error code.
Definition at line 659 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), and sPoKeysPEv2::TriggerIngnoredAxisMask.
PK_PEv2_ThreadingStatusGet()
POKEYSDECL int32_t PK_PEv2_ThreadingStatusGet (sPoKeysDevice * device)
Query the status of a threading operation.
Sends PEV2_CMD_GET_THREADING_STATUS (0x35) which returns various trigger flags along with spindle diagnostic data in the response bytes 8-63.
Parameters
device Target device.
Returns
PK_OK on success or error code.
Definition at line 630 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::DebugValues, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysPEv2::spindleIndexCounter, sPoKeysPEv2::SpindlePositionError, sPoKeysPEv2::SpindleRPM, sPoKeysPEv2::SpindleSpeedEstimate, sPoKeysPEv2::TriggerActive, sPoKeysPEv2::TriggerIngnoredAxisMask, sPoKeysPEv2::TriggerPending, sPoKeysPEv2::TriggerPrepared, and sPoKeysPEv2::TriggerPreparing.
PK_PEv2_ThreadingTrigger()
POKEYSDECL int32_t PK_PEv2_ThreadingTrigger (sPoKeysDevice * device)
Arm the threading trigger.
Executes PEV2_CMD_ARM_TRIGGER (0x32) which waits for the configured spindle index before executing motion.
Parameters
device Target device.
Returns
PK_OK if the command is sent successfully.
Definition at line 591 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PinConfigurationGet()
POKEYSDECL int32_t PK_PinConfigurationGet (sPoKeysDevice * device)
Read pin configuration from the device (command 0xC0).
Populates each element of device->Pins with the current pin function setting and related options.
Parameters
device Pointer to an opened device structure.
Returns
PK_OK on success or a ::PK_ERR code otherwise.
Definition at line 24 of file PoKeysLibIO.c.
References sPoKeysPinData::CounterOptions, CreateRequest(), sPoKeysPinData::DigitalCounterAvailable, sPoKeysPinData::downKeyCodeMacroID, sPoKeysPinData::downKeyModifier, i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iTriggeredKeyMapping, sPoKeysPinData::KeyCodeMacroID, sPoKeysPinData::KeyModifier, sPoKeysPinData::MappingType, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_IsCounterAvailable(), PK_OK, PK_PinCap_digitalInput, PK_PinCap_triggeredInput, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysPinData::upKeyCodeMacroID, and sPoKeysPinData::upKeyModifier.
Referenced by PoKeysHALComponent::PKIO_Setup(), and PoKeysHALComponent::PKIO_Update().
PK_PinConfigurationSet()
POKEYSDECL int32_t PK_PinConfigurationSet (sPoKeysDevice * device)
Write pin configuration to the device (command 0xC0).
Sends the content of device->Pins to update functions, counters and mapping options.
Parameters
device Pointer to an opened device structure.
Returns
PK_OK on success or a ::PK_ERR value on failure.
Definition at line 158 of file PoKeysLibIO.c.
References sPoKeysPinData::CounterOptions, CreateRequest(), sPoKeysPinData::downKeyCodeMacroID, sPoKeysPinData::downKeyModifier, i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iTriggeredKeyMapping, sPoKeysPinData::KeyCodeMacroID, sPoKeysPinData::KeyModifier, sPoKeysPinData::MappingType, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PinCap_digitalInput, PK_PinCap_triggeredInput, sPoKeysDevice::request, SendRequest(), sPoKeysPinData::upKeyCodeMacroID, and sPoKeysPinData::upKeyModifier.
Referenced by PoKeysHALComponent::PKIO_Setup().
PK_PoExtBusGet()
POKEYSDECL int32_t PK_PoExtBusGet (sPoKeysDevice * device)
Definition at line 750 of file PoKeysLibIO.c.
References CreateRequest(), i, sPoKeysDevice::info, sPoKeysDevice_Info::iPoExtBus, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoExtBusData, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoExtBusSet()
POKEYSDECL int32_t PK_PoExtBusSet (sPoKeysDevice * device)
Definition at line 728 of file PoKeysLibIO.c.
References CreateRequest(), i, sPoKeysDevice::info, sPoKeysDevice_Info::iPoExtBus, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoExtBusData, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoILChunkReadMemory()
POKEYSDECL int32_t PK_PoILChunkReadMemory (sPoKeysDevice * device, uint8_t * dest)
Read a set of preconfigured memory chunks.
Definition at line 263 of file PoKeysLibPoIL.c.
References sPoILmemoryChunk::address, sPoILmemoryChunk::chunkLength, CreateRequest(), i, sPoILStatus::monitorChunks, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoIL, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoILChunkReadMemoryInternalAddress()
POKEYSDECL int32_t PK_PoILChunkReadMemoryInternalAddress (sPoKeysDevice * device, uint8_t * dest)
Read memory monitor chunks using internal addresses.
Definition at line 288 of file PoKeysLibPoIL.c.
References sPoILmemoryChunk::address, sPoILmemoryChunk::chunkLength, CreateRequest(), i, sPoILStatus::monitorChunks, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoIL, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoILEraseMemory()
POKEYSDECL int32_t PK_PoILEraseMemory (sPoKeysDevice * device, uint8_t memoryType)
Erase a region of interpreter memory.
Definition at line 253 of file PoKeysLibPoIL.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PoILGetState()
POKEYSDECL int32_t PK_PoILGetState (sPoKeysDevice * device)
Query interpreter status from the device.
Definition at line 55 of file PoKeysLibPoIL.c.
References CreateRequest(), sPoILStatus::dataStack, sPoILStatus::functionStack, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_ParsePoILStateResponse(), sPoKeysDevice::PoIL, sPoKeysDevice::request, SendRequest(), and sPoILStack::stackSize.
PK_PoILReadMemory()
POKEYSDECL int32_t PK_PoILReadMemory (sPoKeysDevice * device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t * dest)
Read a block of interpreter memory.
Definition at line 118 of file PoKeysLibPoIL.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoILReadSharedSlot()
POKEYSDECL int32_t PK_PoILReadSharedSlot (sPoKeysDevice * device, uint16_t firstSlotID, uint16_t slotsNum, int * dest)
Read interpreter shared-slot variables.
Definition at line 194 of file PoKeysLibPoIL.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoILResetCore()
POKEYSDECL int32_t PK_PoILResetCore (sPoKeysDevice * device)
Reset the interpreter core on the device.
Definition at line 94 of file PoKeysLibPoIL.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_ParsePoILStateResponse(), sPoKeysDevice::request, and SendRequest().
PK_PoILSetCoreState()
POKEYSDECL int32_t PK_PoILSetCoreState (sPoKeysDevice * device, uint16_t state)
Request a change of interpreter core state.
Definition at line 70 of file PoKeysLibPoIL.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_ParsePoILStateResponse(), sPoKeysDevice::request, and SendRequest().
PK_PoILSetDebugMode()
POKEYSDECL int32_t PK_PoILSetDebugMode (sPoKeysDevice * device, uint8_t debugMode, uint16_t breakpoint)
Configure interpreter debug mode and breakpoint.
Definition at line 106 of file PoKeysLibPoIL.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_ParsePoILStateResponse(), sPoKeysDevice::request, and SendRequest().
PK_PoILSetMasterEnable()
POKEYSDECL int32_t PK_PoILSetMasterEnable (sPoKeysDevice * device, uint8_t masterEnable)
Enable or disable the interpreter execution engine.
Definition at line 82 of file PoKeysLibPoIL.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_ParsePoILStateResponse(), sPoKeysDevice::request, and SendRequest().
PK_PoILTaskStatus()
POKEYSDECL int32_t PK_PoILTaskStatus (sPoKeysDevice * device)
Retrieve status information for all interpreter tasks.
Definition at line 311 of file PoKeysLibPoIL.c.
References CreateRequest(), i, sPoILStatus::inactiveLoad, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoIL, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoILStatus::taskCount, sPoILTask::taskLoad, sPoILTask::taskPeriod, sPoILTask::taskRealPeriod, sPoILTask::taskRealPeriodFiltered, sPoILStatus::tasks, and sPoILTask::taskStatus.
PK_PoILWriteMemory()
POKEYSDECL int32_t PK_PoILWriteMemory (sPoKeysDevice * device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t * src)
Write a block of interpreter memory.
Definition at line 147 of file PoKeysLibPoIL.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PoILWriteMemory(), sPoKeysDevice::request, and SendRequest().
PK_PoILWriteSharedSlot()
POKEYSDECL int32_t PK_PoILWriteSharedSlot (sPoKeysDevice * device, uint16_t firstSlotID, uint16_t slotsNum, int32_t * src)
Write interpreter shared-slot variables.
Definition at line 223 of file PoKeysLibPoIL.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PoNETGetModuleLight()
POKEYSDECL int32_t PK_PoNETGetModuleLight (sPoKeysDevice * device)
Read the light sensor value previously requested.
Executes PONET_OP_GET_LIGHT_SENSOR with subcommand 0x30 to obtain the measured light value which is stored in sPoNETmodule::lightValue.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL, PK_ERR_TRANSFER on communication failure or PK_ERR_GENERIC when the returned status indicates an error.
Definition at line 118 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::lightValue, sPoNETmodule::moduleID, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoNETGetModuleLightRequest()
POKEYSDECL int32_t PK_PoNETGetModuleLightRequest (sPoKeysDevice * device)
Request the current value of the module's light sensor.
Sends PONET_OP_GET_LIGHT_SENSOR with subcommand 0x10 to trigger the reading of the light sensor. The value can later be read by PK_PoNETGetModuleLight().
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 108 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::moduleID, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, and SendRequest().
PK_PoNETGetModuleSettings()
POKEYSDECL int32_t PK_PoNETGetModuleSettings (sPoKeysDevice * device)
Retrieve basic information about the selected PoNET module.
Sends PONET_OP_GET_MODULE_SETTINGS which returns I\2C address, module type, module size and option flags. The values are stored in the sPoNETmodule structure of device.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 37 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::i2cAddress, sPoNETmodule::moduleID, sPoNETmodule::moduleOptions, sPoNETmodule::moduleSize, sPoNETmodule::moduleType, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoNETGetModuleStatus()
POKEYSDECL int32_t PK_PoNETGetModuleStatus (sPoKeysDevice * device)
Obtain previously requested module status bytes.
After a call to PK_PoNETGetModuleStatusRequest(), this function reads the 16 status bytes from the device using PONET_OP_GET_MODULE_DATA with subcommand 0x30. The bytes are copied to sPoNETmodule::statusIn.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL, PK_ERR_TRANSFER on communication failure or PK_ERR_GENERIC when the response format is invalid.
Definition at line 64 of file PoKeysLibPoNET.c.
References CreateRequest(), PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), and sPoNETmodule::statusIn.
PK_PoNETGetModuleStatusRequest()
POKEYSDECL int32_t PK_PoNETGetModuleStatusRequest (sPoKeysDevice * device)
Request status bytes from the PoNET module.
Executes PONET_OP_GET_MODULE_DATA with subcommand 0x10 which instructs the module to prepare its status information for later retrieval using PK_PoNETGetModuleStatus().
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 54 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::moduleID, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, and SendRequest().
PK_PoNETGetPoNETStatus()
POKEYSDECL int32_t PK_PoNETGetPoNETStatus (sPoKeysDevice * device)
Read overall PoNET bus status.
Issues command PONET_OP_GET_STATUS using PK_CMD_POI2C_COMMUNICATION and stores the returned status byte in sPoNETmodule::PoNETstatus.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 25 of file PoKeysLibPoNET.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoNETmodule::PoNETstatus, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoNETSetModulePWM()
POKEYSDECL int32_t PK_PoNETSetModulePWM (sPoKeysDevice * device)
Set the PWM duty cycle of a PoNET module.
Uses PONET_OP_SET_PWM_VALUE to write the value stored in sPoNETmodule::PWMduty to the module identified by sPoNETmodule::moduleID.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 98 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::moduleID, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoNETmodule::PWMduty, sPoKeysDevice::request, and SendRequest().
PK_PoNETSetModuleStatus()
POKEYSDECL int32_t PK_PoNETSetModuleStatus (sPoKeysDevice * device)
Write output status bytes to the PoNET module.
Transmits the 16 bytes stored in sPoNETmodule::statusOut using PONET_OP_SET_MODULE_DATA.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 80 of file PoKeysLibPoNET.c.
References CreateRequest(), i, sPoNETmodule::moduleID, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, SendRequest(), and sPoNETmodule::statusOut.
PK_PoStep_ConfigurationGet()
POKEYSDECL int32_t PK_PoStep_ConfigurationGet (sPoKeysDevice * device)
Get configuration for external PoStep drivers.
Command PEV2_CMD_SETUP_DRIVER_COMM (0x50) retrieves driver type, I2C address and update flags for each axis.
Parameters
device Target device.
Returns
PK_OK on success or communication error.
Definition at line 750 of file PoKeysLibPulseEngine_v2.c.
References sPoPoStepDriverConfig::AddressI2C, CreateRequest(), sPoKeysPoStepInterface::drivers, sPoPoStepDriverConfig::DriverType, sPoKeysPoStepInterface::EnablePoStepCommunication, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), and sPoPoStepDriverConfig::UpdateConfig.
Referenced by Config_PoStep().
PK_PoStep_ConfigurationSet()
POKEYSDECL int32_t PK_PoStep_ConfigurationSet (sPoKeysDevice * device)
Configure external PoStep drivers.
Sends PEV2_CMD_SETUP_DRIVER_COMM (0x50) with param1=0x10 followed by driver type, address and update flags for each axis.
Parameters
device Device holding configuration in PoSteps.
Returns
PK_OK on success or error code.
Definition at line 773 of file PoKeysLibPulseEngine_v2.c.
References sPoPoStepDriverConfig::AddressI2C, CreateRequest(), sPoKeysPoStepInterface::drivers, sPoPoStepDriverConfig::DriverType, sPoKeysPoStepInterface::EnablePoStepCommunication, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), and sPoPoStepDriverConfig::UpdateConfig.
PK_PoStep_DriverConfigurationGet()
POKEYSDECL int32_t PK_PoStep_DriverConfigurationGet (sPoKeysDevice * device)
Read PoStep driver current and mode settings.
Uses commands PEV2_CMD_DRIVER_CURRENT_PARAMS (0x52) and PEV2_CMD_DRIVER_MODE_PARAMS (0x53) to obtain current limits, driver mode, microstepping and temperature limits.
Parameters
device Target device.
Returns
PK_OK on success or communication error.
Definition at line 831 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoPoStepDriverConfig::Current_FS, sPoPoStepDriverConfig::Current_Idle, sPoPoStepDriverConfig::Current_Overheat, sPoPoStepDriverConfig::DriverMode, sPoKeysPoStepInterface::drivers, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoPoStepDriverConfig::StepMode, and sPoPoStepDriverConfig::TemperatureLimit.
Referenced by Config_PoStep().
PK_PoStep_DriverConfigurationSet()
POKEYSDECL int32_t PK_PoStep_DriverConfigurationSet (sPoKeysDevice * device)
Write PoStep driver current and mode parameters.
Sends PEV2_CMD_DRIVER_CURRENT_PARAMS and PEV2_CMD_DRIVER_MODE_PARAMS with param1=0x10 to update driver settings for all axes.
Parameters
device Device containing new driver parameters.
Returns
PK_OK on success or error code.
Definition at line 870 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoPoStepDriverConfig::Current_FS, sPoPoStepDriverConfig::Current_Idle, sPoPoStepDriverConfig::Current_Overheat, sPoPoStepDriverConfig::DriverMode, sPoKeysPoStepInterface::drivers, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoPoStepDriverConfig::StepMode, and sPoPoStepDriverConfig::TemperatureLimit.
PK_PoStep_StatusGet()
POKEYSDECL int32_t PK_PoStep_StatusGet (sPoKeysDevice * device)
Read status information from PoStep drivers.
Executes PEV2_CMD_GET_DRIVER_STATUS (0x51) which returns voltage, temperature and diagnostic bits for each driver.
Parameters
device Target device.
Returns
PK_OK or error code.
Definition at line 805 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPoStepInterface::drivers, sPoPoStepDriverConfig::DriverStatus, sPoPoStepDriverConfig::FaultStatus, i, sPoPoStepDriverConfig::InputStatus, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoPoStepDriverConfig::SupplyVoltage, sPoPoStepDriverConfig::Temperature, and sPoPoStepDriverConfig::UpdateState.
Referenced by Update_PoStep().
PK_PWMConfigurationGet()
POKEYSDECL int32_t PK_PWMConfigurationGet (sPoKeysDevice * device)
Definition at line 641 of file PoKeysLibIO.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by PoKeysHALComponent::PKIO_Setup(), and PoKeysHALComponent::PKIO_Update().
PK_PWMConfigurationSet()
POKEYSDECL int32_t PK_PWMConfigurationSet (sPoKeysDevice * device)
Definition at line 621 of file PoKeysLibIO.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysDevice::request, and SendRequest().
Referenced by PoKeysHALComponent::PKIO_Setup(), and PoKeysHALComponent::PKIO_Update().
PK_PWMConfigurationSetDirectly()
POKEYSDECL int32_t PK_PWMConfigurationSetDirectly (sPoKeysDevice * device, uint32_t PWMperiod, uint8_t * enabledChannels)
Definition at line 682 of file PoKeysLibIO.c.
References PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_OK, PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
PK_PWMUpdate()
POKEYSDECL int32_t PK_PWMUpdate (sPoKeysDevice * device)
Definition at line 661 of file PoKeysLibIO.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysDevice::request, and SendRequest().
Referenced by PoKeysHALComponent::PKIO_Update().
PK_PWMUpdateDirectly()
POKEYSDECL int32_t PK_PWMUpdateDirectly (sPoKeysDevice * device, uint32_t * dutyCycles)
Definition at line 694 of file PoKeysLibIO.c.
References PK_ERR_NOT_CONNECTED, PK_PWMUpdate(), sPoKeysDevice::PWM, and sPoKeysPWM::PWMduty.
PK_ReadDeviceLog()
POKEYSDECL int32_t PK_ReadDeviceLog (sPoKeysDevice * device, uint16_t * logBuffer, int32_t * logEntries)
Retrieve entries from the device event log (command 0x84).
Parameters
device Device handle.
logBuffer Buffer for up to 27 log words.
logEntries Receives number of valid entries returned.
Returns
PK_OK on success or PK_ERR_TRANSFER otherwise.
Definition at line 1419 of file PoKeysLibDeviceData.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_ReleaseDeviceStructure()
POKEYSDECL void PK_ReleaseDeviceStructure (sPoKeysDevice * device)
Definition at line 223 of file PoKeysLibCore.c.
References CleanDevice().
PK_RTCGet()
POKEYSDECL int32_t PK_RTCGet (sPoKeysDevice * device)
Read the real-time clock values (command 0x83/0x00).
Fills the RTC structure of device with the current date and time.
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success or a PK_ERR code on failure.
Definition at line 24 of file PoKeysLibRTC.c.
References CreateRequest(), sPoKeysRTC::DOM, sPoKeysRTC::DOW, sPoKeysRTC::DOY, sPoKeysRTC::HOUR, sPoKeysRTC::MIN, sPoKeysRTC::MONTH, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysDevice::RTC, sPoKeysRTC::SEC, SendRequest(), and sPoKeysRTC::YEAR.
Referenced by FUNCTION(), and user_mainloop().
PK_RTCSet()
POKEYSDECL int32_t PK_RTCSet (sPoKeysDevice * device)
Set the real-time clock (command 0x83/0x10).
Writes the values from the device RTC structure to the PoKeys module.
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success or a PK_ERR code on failure.
Definition at line 46 of file PoKeysLibRTC.c.
References CreateRequest(), sPoKeysRTC::DOM, sPoKeysRTC::DOW, sPoKeysRTC::DOY, sPoKeysRTC::HOUR, sPoKeysRTC::MIN, sPoKeysRTC::MONTH, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::RTC, sPoKeysRTC::SEC, SendRequest(), and sPoKeysRTC::YEAR.
PK_SaveConfiguration()
POKEYSDECL int32_t PK_SaveConfiguration (sPoKeysDevice * device)
Save current configuration to device flash (command 0x50).
Writes the active settings from RAM to non-volatile memory so that they persist across resets.
Parameters
device PoKeys device handle.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1138 of file PoKeysLibDeviceData.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
Referenced by PEv2_AdditionalParametersSet(), PoKeysHALComponent::PEv2_AxisConfigurationSet(), and PEv2_PulseEngineSetup().
PK_SearchNetworkDevices()
POKEYSDECL int32_t PK_SearchNetworkDevices (sPoKeysNetworkDeviceSummary * devices, uint32_t timeout, uint32_t serialNumberToFind)
Broadcasts a discovery request and collects responses from PoKeys devices.
A UDP packet is sent to every broadcast address returned by GetBroadcastAddresses(). Responses are gathered for up to timeout milliseconds and stored into the provided devices array (maximum 16 entries). If serialNumberToFind is non-zero the function stops early when a matching device is found.
Parameters
devices Array of sPoKeysNetworkDeviceSummary structures for storing discovered devices.
timeout Discovery timeout in milliseconds.
serialNumberToFind Optional serial number to look for (0 = any).
Returns
Number of discovered devices.
Definition at line 215 of file PoKeysLibCoreSockets.c.
References debug_printf, sPoKeysNetworkDeviceSummary::DHCP, sPoKeysNetworkDeviceSummary::FirmwareVersionMajor, sPoKeysNetworkDeviceSummary::FirmwareVersionMinor, GetBroadcastAddresses(), sPoKeysNetworkDeviceSummary::hostIP, sPoKeysNetworkDeviceSummary::HWtype, sPoKeysNetworkDeviceSummary::IPaddress, and sPoKeysNetworkDeviceSummary::SerialNumber.
Referenced by PK_ConnectToPoKeysDevice_Ethernet(), and PK_ConnectToPoKeysDevice_Ethernet_Async().
PK_SetEthernetRetryCountAndTimeout()
POKEYSDECL void PK_SetEthernetRetryCountAndTimeout (sPoKeysDevice * device, uint32_t sendRetries, uint32_t readRetries, uint32_t timeout)
Definition at line 924 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::readRetries, sPoKeysDevice::sendRetries, and sPoKeysDevice::socketTimeout.
PK_SetFastUSBEnableStatus()
POKEYSDECL int32_t PK_SetFastUSBEnableStatus (sPoKeysDevice * device, uint32_t newState)
Enable or disable the fast USB interface (command 0x07).
Parameters
device Device handle.
newState 1 to enable, 0 to disable.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1398 of file PoKeysLibDeviceData.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_SL_AnalogInputGet()
POKEYSDECL uint32_t PK_SL_AnalogInputGet (sPoKeysDevice * device, uint8_t pin)
Definition at line 897 of file PoKeysLibCore.c.
References sPoKeysPinData::AnalogValue, and sPoKeysDevice::Pins.
PK_SL_DigitalInputGet()
POKEYSDECL uint8_t PK_SL_DigitalInputGet (sPoKeysDevice * device, uint8_t pin)
Definition at line 892 of file PoKeysLibCore.c.
References sPoKeysPinData::DigitalValueGet, and sPoKeysDevice::Pins.
PK_SL_DigitalOutputSet()
POKEYSDECL void PK_SL_DigitalOutputSet (sPoKeysDevice * device, uint8_t pin, uint8_t value)
Definition at line 887 of file PoKeysLibCore.c.
References sPoKeysPinData::DigitalValueSet, and sPoKeysDevice::Pins.
PK_SL_EasySensorValueGet()
POKEYSDECL int32_t PK_SL_EasySensorValueGet (sPoKeysDevice * device, uint8_t index)
Return cached sensor value.
Parameters
device Device handle.
index Sensor index.
Returns
Last value read for the sensor or 0 on error.
Definition at line 117 of file PoKeysLibEasySensors.c.
References sPoKeysDevice::EasySensors, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, and sPoKeysEasySensor::sensorValue.
PK_SL_EncoderValueGet()
POKEYSDECL uint32_t PK_SL_EncoderValueGet (sPoKeysDevice * device, uint8_t index)
Definition at line 259 of file PoKeysLibEncoders.c.
References sPoKeysDevice::Encoders, and sPoKeysEncoder::encoderValue.
PK_SL_GetPinFunction()
POKEYSDECL uint8_t PK_SL_GetPinFunction (sPoKeysDevice * device, uint8_t pin)
Definition at line 882 of file PoKeysLibCore.c.
References sPoKeysPinData::PinFunction, and sPoKeysDevice::Pins.
PK_SL_PWM_SetChannelEnabled()
POKEYSDECL int32_t PK_SL_PWM_SetChannelEnabled (sPoKeysDevice * device, uint8_t channel, uint8_t enabled, uint32_t defaultDuty)
Definition at line 711 of file PoKeysLibIO.c.
References PK_ERR_NOT_CONNECTED, PK_PWMConfigurationSet(), sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, and sPoKeysPWM::PWMenabledChannels.
PK_SL_PWM_SetDuty()
POKEYSDECL int32_t PK_SL_PWM_SetDuty (sPoKeysDevice * device, uint8_t channel, uint32_t duty)
Definition at line 720 of file PoKeysLibIO.c.
References PK_ERR_NOT_CONNECTED, PK_OK, sPoKeysDevice::PWM, and sPoKeysPWM::PWMduty.
PK_SL_PWM_SetPeriod()
POKEYSDECL int32_t PK_SL_PWM_SetPeriod (sPoKeysDevice * device, uint32_t PWMperiod)
Definition at line 702 of file PoKeysLibIO.c.
References PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_OK, PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), sPoKeysDevice::PWM, and sPoKeysPWM::PWMperiod.
PK_SL_PWMConfig()
POKEYSDECL uint32_t PK_SL_PWMConfig (sPoKeysDevice * device, uint8_t index)
PK_SL_SetPinFunction()
POKEYSDECL void PK_SL_SetPinFunction (sPoKeysDevice * device, uint8_t pin, uint8_t function)
Definition at line 877 of file PoKeysLibCore.c.
References sPoKeysPinData::PinFunction, and sPoKeysDevice::Pins.
PK_SPIConfigure()
POKEYSDECL int32_t PK_SPIConfigure (sPoKeysDevice * device, uint8_t prescaler, uint8_t frameFormat)
Configure the SPI interface of a PoKeys device (command 0xE5/0x01).
Issues PK_CMD_SPI_COMMUNICATION with subcommand 0x01 to set the SPI clock prescaler and frame format.
Parameters
device Pointer to an initialised device structure.
prescaler SPI clock prescaler value sent to the device.
frameFormat Frame configuration (mode, bit length etc.).
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 24 of file PoKeysLibSPI.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_SPIRead()
POKEYSDECL int32_t PK_SPIRead (sPoKeysDevice * device, uint8_t * buffer, uint8_t iDataLength)
Receive data from the SPI interface (command 0xE5/0x20).
Issues a read request for the specified number of bytes. The returned values are copied into the provided buffer on success.
Parameters
device Pointer to an initialised PoKeys device structure.
buffer Destination buffer for the received bytes.
iDataLength Number of bytes to read (maximum 55).
Returns
PK_OK if the data was read successfully, otherwise a negative ::PK_ERR code.
Definition at line 51 of file PoKeysLibSPI.c.
References CreateRequest(), i, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_SPIWrite()
POKEYSDECL int32_t PK_SPIWrite (sPoKeysDevice * device, uint8_t * buffer, uint8_t iDataLength, uint8_t pinCS)
Transmit data over the SPI interface (command 0xE5/0x10).
Sends a block of up to 55 bytes to the selected chip on the PoKeys device. The chip select line is asserted automatically by the device.
Parameters
device Pointer to an initialised PoKeys device structure.
buffer Data buffer containing bytes to transmit.
iDataLength Number of bytes to send (max 55).
pinCS Chip select pin identifier on the PoKeys device.
Returns
PK_OK on success or a negative ::PK_ERR code when the transfer fails.
Definition at line 34 of file PoKeysLibSPI.c.
References CreateRequest(), i, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_UARTConfigure()
POKEYSDECL int32_t PK_UARTConfigure (sPoKeysDevice * device, uint32_t baudrate, uint8_t format, uint8_t interfaceID)
Configure a UART interface (command 0xDE/0x10).
Sets baud rate and frame format for the selected UART interface on the device.
Parameters
device Opened PoKeys device.
baudrate Desired baud rate.
format Frame format bits.
interfaceID UART interface ID.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 23 of file PoKeysLibUART.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_UARTRead()
POKEYSDECL int32_t PK_UARTRead (sPoKeysDevice * device, uint8_t interfaceID, uint8_t * dataPtr, uint8_t * dataReadLen)
Read data from a UART interface (command 0xDE/0x30).
Requests a block of up to 55 bytes from the specified UART channel. The received byte count is returned via dataReadLen.
Parameters
device Opened PoKeys device.
interfaceID UART interface ID.
dataPtr Destination buffer for received bytes.
dataReadLen Pointer where the byte count is stored.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 73 of file PoKeysLibUART.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_UARTWrite()
POKEYSDECL int32_t PK_UARTWrite (sPoKeysDevice * device, uint8_t interfaceID, uint8_t * dataPtr, uint32_t dataWriteLen)
Write data to the UART interface (command 0xDE/0x20).
Splits the data into 55 byte chunks and sends them to the specified UART interface.
Parameters
device Opened PoKeys device.
interfaceID Target UART interface.
dataPtr Pointer to buffer with bytes to send.
dataWriteLen Number of bytes to transmit.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 34 of file PoKeysLibUART.c.
References CreateRequest(), PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_WS2812_SendLEDdata()
POKEYSDECL int32_t PK_WS2812_SendLEDdata (sPoKeysDevice * device, uint32_t * LEDdata, uint16_t startLED, uint8_t LEDcount)
Send LED data to the WS2812 strip.
Splits the transfer into 18-LED chunks using PK_WS2812_SendLEDdataEx.
Parameters
device Pointer to an initialized device structure.
LEDdata Array of 24-bit color values.
startLED Index of the first LED to update.
LEDcount Number of LEDs to update.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 50 of file PoKeysLibWS2812.c.
References PK_ERR_NOT_CONNECTED, PK_OK, and PK_WS2812_SendLEDdataEx().
PK_WS2812_Update()
POKEYSDECL int32_t PK_WS2812_Update (sPoKeysDevice * device, uint16_t LEDcount, uint8_t updateFlag)
Configure or trigger the WS2812 LED driver.
Parameters
device Pointer to an initialized device structure.
LEDcount Total number of LEDs in the strip.
updateFlag Non-zero to immediately refresh the LED strip.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 23 of file PoKeysLibWS2812.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
Variable Documentation
LastRetryCount
int32_t LastRetryCount extern
Definition at line 685 of file PoKeysLibCore.c.
LastWaitCount
int32_t LastWaitCount extern
Definition at line 686 of file PoKeysLibCore.c.