LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibPoNET.c File Reference
PoKeysLibPoNET.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
Functions
int32_t PK_PoNETGetPoNETStatus (sPoKeysDevice *device)
Read overall PoNET bus status.
int32_t PK_PoNETGetModuleSettings (sPoKeysDevice *device)
Retrieve basic information about the selected PoNET module.
int32_t PK_PoNETGetModuleStatusRequest (sPoKeysDevice *device)
Request status bytes from the PoNET module.
int32_t PK_PoNETGetModuleStatus (sPoKeysDevice *device)
Obtain previously requested module status bytes.
int32_t PK_PoNETSetModuleStatus (sPoKeysDevice *device)
Write output status bytes to the PoNET module.
int32_t PK_PoNETSetModulePWM (sPoKeysDevice *device)
Set the PWM duty cycle of a PoNET module.
int32_t PK_PoNETGetModuleLightRequest (sPoKeysDevice *device)
Request the current value of the module's light sensor.
int32_t PK_PoNETGetModuleLight (sPoKeysDevice *device)
Read the light sensor value previously requested.
Function Documentation
PK_PoNETGetModuleLight()
int32_t PK_PoNETGetModuleLight (sPoKeysDevice * device)
Read the light sensor value previously requested.
Executes PONET_OP_GET_LIGHT_SENSOR with subcommand 0x30 to obtain the measured light value which is stored in sPoNETmodule::lightValue.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL, PK_ERR_TRANSFER on communication failure or PK_ERR_GENERIC when the returned status indicates an error.
Definition at line 205 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::lightValue, sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PONET_OP_GET_LIGHT_SENSOR, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoNETGetModuleLightRequest()
int32_t PK_PoNETGetModuleLightRequest (sPoKeysDevice * device)
Request the current value of the module's light sensor.
Sends PONET_OP_GET_LIGHT_SENSOR with subcommand 0x10 to trigger the reading of the light sensor. The value can later be read by PK_PoNETGetModuleLight().
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 184 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PONET_OP_GET_LIGHT_SENSOR, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, and SendRequest().
PK_PoNETGetModuleSettings()
int32_t PK_PoNETGetModuleSettings (sPoKeysDevice * device)
Retrieve basic information about the selected PoNET module.
Sends PONET_OP_GET_MODULE_SETTINGS which returns I\2C address, module type, module size and option flags. The values are stored in the sPoNETmodule structure of device.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 59 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::i2cAddress, sPoNETmodule::moduleID, sPoNETmodule::moduleOptions, sPoNETmodule::moduleSize, sPoNETmodule::moduleType, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PONET_OP_GET_MODULE_SETTINGS, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoNETGetModuleStatus()
int32_t PK_PoNETGetModuleStatus (sPoKeysDevice * device)
Obtain previously requested module status bytes.
After a call to PK_PoNETGetModuleStatusRequest(), this function reads the 16 status bytes from the device using PONET_OP_GET_MODULE_DATA with subcommand 0x30. The bytes are copied to sPoNETmodule::statusIn.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL, PK_ERR_TRANSFER on communication failure or PK_ERR_GENERIC when the response format is invalid.
Definition at line 109 of file PoKeysLibPoNET.c.
References CreateRequest(), PK_CMD_POI2C_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PONET_OP_GET_MODULE_DATA, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), and sPoNETmodule::statusIn.
PK_PoNETGetModuleStatusRequest()
int32_t PK_PoNETGetModuleStatusRequest (sPoKeysDevice * device)
Request status bytes from the PoNET module.
Executes PONET_OP_GET_MODULE_DATA with subcommand 0x10 which instructs the module to prepare its status information for later retrieval using PK_PoNETGetModuleStatus().
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 87 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PONET_OP_GET_MODULE_DATA, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, and SendRequest().
PK_PoNETGetPoNETStatus()
int32_t PK_PoNETGetPoNETStatus (sPoKeysDevice * device)
Read overall PoNET bus status.
Issues command PONET_OP_GET_STATUS using PK_CMD_POI2C_COMMUNICATION and stores the returned status byte in sPoNETmodule::PoNETstatus.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 36 of file PoKeysLibPoNET.c.
References CreateRequest(), PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PONET_OP_GET_STATUS, sPoKeysDevice::PoNETmodule, sPoNETmodule::PoNETstatus, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoNETSetModulePWM()
int32_t PK_PoNETSetModulePWM (sPoKeysDevice * device)
Set the PWM duty cycle of a PoNET module.
Uses PONET_OP_SET_PWM_VALUE to write the value stored in sPoNETmodule::PWMduty to the module identified by sPoNETmodule::moduleID.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 163 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PONET_OP_SET_PWM_VALUE, sPoKeysDevice::PoNETmodule, sPoNETmodule::PWMduty, sPoKeysDevice::request, and SendRequest().
PK_PoNETSetModuleStatus()
int32_t PK_PoNETSetModuleStatus (sPoKeysDevice * device)
Write output status bytes to the PoNET module.
Transmits the 16 bytes stored in sPoNETmodule::statusOut using PONET_OP_SET_MODULE_DATA.
Parameters
device Pointer to an initialized PoKeys device structure.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 135 of file PoKeysLibPoNET.c.
References CreateRequest(), i, sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PONET_OP_SET_MODULE_DATA, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, SendRequest(), and sPoNETmodule::statusOut.