LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibPulseEngine_v2Async.c File Reference
PoKeysLibPulseEngine_v2Async.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
Functions
async_transaction_t * transaction_find (uint8_t request_id)
Finds an open transaction by its Request ID.
int PK_PEv2_StatusGetAsync (sPoKeysDevice *device)
int PK_PEv2_Status2GetAsync (sPoKeysDevice *device)
int PK_PEv2_PulseEngineSetupAsync (sPoKeysDevice *device)
int PK_PEv2_AdditionalParametersGetAsync (sPoKeysDevice *device)
int PK_PEv2_AdditionalParametersSetAsync (sPoKeysDevice *device)
int PK_PEv2_AxisConfigurationGetAsync (sPoKeysDevice *device)
int PK_PEv2_AxisConfigurationSetAsync (sPoKeysDevice *device)
int PK_PEv2_PulseEngineMovePVAsync (sPoKeysDevice *device)
int PK_PEv2_HomingStartAsync (sPoKeysDevice *device)
int PK_PEv2_ExternalOutputsSetAsync (sPoKeysDevice *device)
Function Documentation
PK_PEv2_AdditionalParametersGetAsync()
int PK_PEv2_AdditionalParametersGetAsync (sPoKeysDevice * device)
Definition at line 152 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsync(), PEV2_CMD_CONFIGURE_MISC, PK_CMD_PULSE_ENGINE_V2, and PK_ERR_NOT_CONNECTED.
PK_PEv2_AdditionalParametersSetAsync()
int PK_PEv2_AdditionalParametersSetAsync (sPoKeysDevice * device)
Definition at line 162 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsyncWithPayload(), sPoKeysPEv2::EmergencyInputPin, sPoKeysDevice::PEv2, PEV2_CMD_CONFIGURE_MISC, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_PEv2_AxisConfigurationGetAsync()
int PK_PEv2_AxisConfigurationGetAsync (sPoKeysDevice * device)
Definition at line 173 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsync(), sPoKeysPEv2::param1, sPoKeysDevice::PEv2, PEV2_CMD_GET_AXIS_CONFIGURATION, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, and PK_ERR_PARAMETER.
PK_PEv2_AxisConfigurationSetAsync()
int PK_PEv2_AxisConfigurationSetAsync (sPoKeysDevice * device)
Definition at line 184 of file PoKeysLibPulseEngine_v2Async.c.
References sPoKeysPEv2::AxesConfig, sPoKeysPEv2::AxesSwitchConfig, sPoKeysPEv2::AxisEnableOutputPins, sPoKeysPEv2::AxisSignalOptions, CreateRequestAsyncWithPayload(), sPoKeysPEv2::FilterHomeSwitch, sPoKeysPEv2::FilterLimitMSwitch, sPoKeysPEv2::FilterLimitPSwitch, sPoKeysPEv2::FilterProbeInput, sPoKeysPEv2::HomeBackOffDistance, sPoKeysPEv2::HomingAlgorithm, sPoKeysPEv2::HomingReturnSpeed, sPoKeysPEv2::HomingSpeed, sPoKeysPEv2::InvertAxisEnable, sPoKeysPEv2::MaxAcceleration, sPoKeysPEv2::MaxDecceleration, sPoKeysPEv2::MaxSpeed, sPoKeysPEv2::MPGjogDivider, sPoKeysPEv2::MPGjogEncoder, sPoKeysPEv2::MPGjogMultiplier, sPoKeysPEv2::param1, sPoKeysDevice::PEv2, PEV2_CMD_SET_AXIS_CONFIGURATION, sPoKeysPEv2::PinHomeSwitch, sPoKeysPEv2::PinLimitMSwitch, sPoKeysPEv2::PinLimitPSwitch, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, SendRequestAsync(), sPoKeysPEv2::SoftLimitMaximum, and sPoKeysPEv2::SoftLimitMinimum.
PK_PEv2_ExternalOutputsSetAsync()
int PK_PEv2_ExternalOutputsSetAsync (sPoKeysDevice * device)
Definition at line 263 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsyncWithPayload(), sPoKeysPEv2::ExternalOCOutputs, sPoKeysPEv2::ExternalRelayOutputs, sPoKeysDevice::PEv2, PEV2_CMD_SET_OUTPUTS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_PEv2_HomingStartAsync()
int PK_PEv2_HomingStartAsync (sPoKeysDevice * device)
Definition at line 252 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsyncWithPayload(), sPoKeysPEv2::param2, sPoKeysDevice::PEv2, PEV2_CMD_START_HOMING, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_PEv2_PulseEngineMovePVAsync()
int PK_PEv2_PulseEngineMovePVAsync (sPoKeysDevice * device)
Definition at line 222 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsyncWithPayload(), i, sPoKeysPEv2::param2, sPoKeysDevice::PEv2, PEV2_CMD_MOVE_PV, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ReferencePositionSpeed, sPoKeysPEv2::ReferenceVelocityPV, and SendRequestAsync().
PK_PEv2_PulseEngineSetupAsync()
int PK_PEv2_PulseEngineSetupAsync (sPoKeysDevice * device)
Definition at line 134 of file PoKeysLibPulseEngine_v2Async.c.
References sPoKeysPEv2::AxisEnabledStatesMask, sPoKeysPEv2::ChargePumpEnabled, CreateRequestAsyncWithPayload(), sPoKeysPEv2::EmergencySwitchPolarity, sPoKeysDevice::PEv2, PEV2_CMD_SETUP, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineBufferSize, sPoKeysPEv2::PulseEngineEnabled, sPoKeysPEv2::PulseGeneratorType, and SendRequestAsync().
PK_PEv2_Status2GetAsync()
int PK_PEv2_Status2GetAsync (sPoKeysDevice * device)
Definition at line 124 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsync(), PEV2_CMD_GET_STATUS2, PK_CMD_PULSE_ENGINE_V2, and PK_ERR_NOT_CONNECTED.
PK_PEv2_StatusGetAsync()
int PK_PEv2_StatusGetAsync (sPoKeysDevice * device)
Definition at line 107 of file PoKeysLibPulseEngine_v2Async.c.
References CreateRequestAsync(), PEV2_CMD_GET_STATUS, PK_CMD_PULSE_ENGINE_V2, and PK_ERR_NOT_CONNECTED.
Referenced by PK_EmergencyStopAllAsync().
transaction_find()
async_transaction_t * transaction_find (uint8_t request_id)
Finds an open transaction by its Request ID.
Parameters
request_id The Request ID to search for.
Returns
Pointer to matching async_transaction_t or NULL if not found.
Definition at line 66 of file PoKeysLibAsync.c.
References i, and MAX_TRANSACTIONS.
Referenced by PK_ReceiveAndDispatch(), and SendRequestAsync().