LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibI2CAsync.c File Reference
PoKeysLibI2CAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
Data Structures
struct I2CAsyncContext
Functions
int PK_I2CSetStatusAsync (sPoKeysDevice *device, uint8_t activated)
int PK_I2CGetStatusAsync (sPoKeysDevice *device, uint8_t *activated)
int PK_I2CWriteStartAsync (sPoKeysDevice *device, uint8_t address, uint8_t *buffer, uint8_t iDataLength)
int PK_I2CWriteAndReadStartAsync (sPoKeysDevice *device, uint8_t address, uint8_t *buffer, uint8_t iDataLengthWrite, uint8_t iDataLengthRead)
int PK_I2CWriteStatusGetAsync (sPoKeysDevice *device, uint8_t *status)
int PK_I2CReadStartAsync (sPoKeysDevice *device, uint8_t address, uint8_t iDataLength)
int PK_I2CReadStatusGetAsync (sPoKeysDevice *device, uint8_t *status, uint8_t *iReadBytes, uint8_t *buffer, uint8_t iMaxBufferLength)
int PK_I2CBusScanStartAsync (sPoKeysDevice *device)
int PK_I2CBusScanGetResultsAsync (sPoKeysDevice *device, uint8_t *status, uint8_t *presentDevices, uint8_t iMaxDevices)
Function Documentation
PK_I2CBusScanGetResultsAsync()
int PK_I2CBusScanGetResultsAsync (sPoKeysDevice * device, uint8_t * status, uint8_t * presentDevices, uint8_t iMaxDevices)
Definition at line 149 of file PoKeysLibI2CAsync.c.
References CreateRequestAsync(), PK_CMD_I2C_COMMUNICATION, and PK_ERR_NOT_CONNECTED.
PK_I2CBusScanStartAsync()
int PK_I2CBusScanStartAsync (sPoKeysDevice * device)
Definition at line 140 of file PoKeysLibI2CAsync.c.
References CreateRequestAsync(), PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_I2CGetStatusAsync()
int PK_I2CGetStatusAsync (sPoKeysDevice * device, uint8_t * activated)
Definition at line 74 of file PoKeysLibI2CAsync.c.
References CreateRequestAsync(), PK_CMD_I2C_COMMUNICATION, and PK_ERR_NOT_CONNECTED.
PK_I2CReadStartAsync()
int PK_I2CReadStartAsync (sPoKeysDevice * device, uint8_t address, uint8_t iDataLength)
Definition at line 116 of file PoKeysLibI2CAsync.c.
References CreateRequestAsync(), PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_I2CReadStatusGetAsync()
int PK_I2CReadStatusGetAsync (sPoKeysDevice * device, uint8_t * status, uint8_t * iReadBytes, uint8_t * buffer, uint8_t iMaxBufferLength)
Definition at line 126 of file PoKeysLibI2CAsync.c.
References CreateRequestAsync(), PK_CMD_I2C_COMMUNICATION, and PK_ERR_NOT_CONNECTED.
PK_I2CSetStatusAsync()
int PK_I2CSetStatusAsync (sPoKeysDevice * device, uint8_t activated)
Definition at line 65 of file PoKeysLibI2CAsync.c.
References CreateRequestAsync(), PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_I2CWriteAndReadStartAsync()
int PK_I2CWriteAndReadStartAsync (sPoKeysDevice * device, uint8_t address, uint8_t * buffer, uint8_t iDataLengthWrite, uint8_t iDataLengthRead)
Definition at line 95 of file PoKeysLibI2CAsync.c.
References CreateRequestAsyncWithPayload(), PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_I2CWriteStartAsync()
int PK_I2CWriteStartAsync (sPoKeysDevice * device, uint8_t address, uint8_t * buffer, uint8_t iDataLength)
Definition at line 85 of file PoKeysLibI2CAsync.c.
References CreateRequestAsyncWithPayload(), PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_I2CWriteStatusGetAsync()
int PK_I2CWriteStatusGetAsync (sPoKeysDevice * device, uint8_t * status)
Definition at line 105 of file PoKeysLibI2CAsync.c.
References CreateRequestAsync(), PK_CMD_I2C_COMMUNICATION, and PK_ERR_NOT_CONNECTED.