LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibRTC.c File Reference
PoKeysLibRTC.c File Reference
Real-time clock access helpers (command 0x83).
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
Functions
int32_t PK_RTCGet (sPoKeysDevice *device)
Read the real-time clock values (command 0x83/0x00).
int32_t PK_RTCSet (sPoKeysDevice *device)
Set the real-time clock (command 0x83/0x10).
Detailed Description
Real-time clock access helpers (command 0x83).
Functions read and write the RTC registers via PK_CMD_RTC_SETTINGS.
Definition in file PoKeysLibRTC.c.
Function Documentation
PK_RTCGet()
int32_t PK_RTCGet (sPoKeysDevice * device)
Read the real-time clock values (command 0x83/0x00).
Fills the RTC structure of device with the current date and time.
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success or a PK_ERR code on failure.
Definition at line 40 of file PoKeysLibRTC.c.
References CreateRequest(), sPoKeysRTC::DOM, sPoKeysRTC::DOW, sPoKeysRTC::DOY, sPoKeysRTC::HOUR, sPoKeysRTC::MIN, sPoKeysRTC::MONTH, PK_CMD_RTC_SETTINGS, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysDevice::RTC, sPoKeysRTC::SEC, SendRequest(), and sPoKeysRTC::YEAR.
Referenced by FUNCTION(), and user_mainloop().
PK_RTCSet()
int32_t PK_RTCSet (sPoKeysDevice * device)
Set the real-time clock (command 0x83/0x10).
Writes the values from the device RTC structure to the PoKeys module.
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success or a PK_ERR code on failure.
Definition at line 71 of file PoKeysLibRTC.c.
References CreateRequest(), sPoKeysRTC::DOM, sPoKeysRTC::DOW, sPoKeysRTC::DOY, sPoKeysRTC::HOUR, sPoKeysRTC::MIN, sPoKeysRTC::MONTH, PK_CMD_RTC_SETTINGS, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::RTC, sPoKeysRTC::SEC, SendRequest(), and sPoKeysRTC::YEAR.