LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibCore.h File Reference
PoKeysLibCore.h File Reference
#include "hidapi.h"
#include <stdio.h>
#include <string.h>
#include "PoKeysLibHal.h"
Macros
#define ConnectToFastUSBInterface(device) NULL;
#define DisconnectFromFastUSBInterface(device) ;
#define SendRequestFastUSB(device) ;
#define SendRequestFastUSB_multiPart(device) ;
Functions
void InitializeNewDevice (sPoKeysDevice *device)
void CleanDevice (sPoKeysDevice *device)
void PK_DisconnectNetworkDevice (sPoKeysDevice *device)
int32_t CreateRequest (uint8_t *request, uint8_t type, uint8_t param1, uint8_t param2, uint8_t param3, uint8_t param4)
Compose a PoKeys request packet.
uint8_t getChecksum (uint8_t *data)
int32_t SendRequest (sPoKeysDevice *device)
Send a request and wait for the device response.
int32_t SendRequest_multiPart (sPoKeysDevice *device)
Send a multipart data transfer.
int32_t SendRequest_NoResponse (sPoKeysDevice *device)
Send a request without waiting for any reply.
int32_t PK_FillPWMPinNumbers (sPoKeysDevice *device)
Populate PWM pin ID table in the device structure.
Macro Definition Documentation
ConnectToFastUSBInterface
#define ConnectToFastUSBInterface (device) NULL;
Definition at line 64 of file PoKeysLibCore.h.
DisconnectFromFastUSBInterface
#define DisconnectFromFastUSBInterface (device) ;
Definition at line 65 of file PoKeysLibCore.h.
SendRequestFastUSB
#define SendRequestFastUSB (device) ;
Definition at line 66 of file PoKeysLibCore.h.
SendRequestFastUSB_multiPart
#define SendRequestFastUSB_multiPart (device) ;
Definition at line 67 of file PoKeysLibCore.h.
Function Documentation
CleanDevice()
void CleanDevice (sPoKeysDevice * device)
Definition at line 187 of file PoKeysLibCore.c.
References sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::MatrixLED, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, sPoKeysDevice::Pins, sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMpinIDs.
Referenced by PK_ConnectToPoKeysDevice_USB(), PK_DisconnectDevice(), and PK_ReleaseDeviceStructure().
CreateRequest()
int32_t CreateRequest (unsigned char * request, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Compose a PoKeys request packet.
Compose a command packet.
Parameters
request 64 byte buffer to populate.
type Command ID (PK_CMD_* constant).
param1 First parameter.
param2 Second parameter.
param3 Third parameter.
param4 Fourth parameter.
Returns
PK_OK on success or PK_ERR_NOT_CONNECTED when request is NULL.
The PoKeys protocol uses 64 byte packets. Bytes 1 to 5 hold the command identifier and up to four parameters. The header byte (0xBB), request ID and checksum are appended by SendRequest().
Parameters
request Pointer to a 64 byte buffer that will contain the command.
type Command ID as defined by pokeys_command_t (PK_CMD_*).
param1 First command parameter.
param2 Second command parameter.
param3 Third command parameter.
param4 Fourth command parameter.
Returns
PK_OK on success or PK_ERR_NOT_CONNECTED when request is NULL.
Compose a PoKeys request packet.
This helper mirrors the synchronous CreateRequest() implementation and prepares a 64 byte packet header according to the protocol.
Parameters
request Buffer that will receive the command bytes.
type Command ID (PK_CMD_* constant).
param1 Parameter 1.
param2 Parameter 2.
param3 Parameter 3.
param4 Parameter 4.
Returns
PK_OK on success or PK_ERR_NOT_CONNECTED when request is NULL.
Definition at line 647 of file PoKeysLibCore.c.
References PK_ERR_NOT_CONNECTED, and PK_OK.
Referenced by PK57i_Update(), PK_1WireBusScanContinue(), PK_1WireBusScanGetResults(), PK_1WireBusScanStart(), PK_1WireBusScanStop(), PK_1WireReadStatusGet(), PK_1WireStatusGet(), PK_1WireStatusSet(), PK_1WireWriteReadStart(), PK_1WireWriteReadStartEx(), PK_AnalogIOGet(), PK_AnalogRCFilterGet(), PK_AnalogRCFilterSet(), PK_CANConfigure(), PK_CANFlush(), PK_CANRead(), PK_CANRegisterFilter(), PK_CANWrite(), PK_ClearConfiguration(), PK_COSMSettingsGet(), PK_COSMSettingsSet(), PK_DeviceActivation(), PK_DeviceActivationClear(), PK_DeviceDataGet(), PK_DeviceNameSet(), PK_DigitalCounterClear(), PK_DigitalCounterGet(), PK_DigitalIOGet(), PK_DigitalIOGetSingle(), PK_DigitalIOSet(), PK_DigitalIOSetGet(), PK_DigitalIOSetSingle(), PK_EasySensorsSetupGet(), PK_EasySensorsSetupSet(), PK_EasySensorsValueGetAll(), PK_EncoderConfigurationGet(), PK_EncoderConfigurationSet(), PK_EncoderValuesGet(), PK_EncoderValuesSet(), PK_FailsafeSettingsGet(), PK_FailsafeSettingsSet(), PK_GetDebugValues(), PK_GetFastUSBEnableStatus(), PK_I2CBusScanGetResults(), PK_I2CBusScanStart(), PK_I2CGetStatus(), PK_I2CReadStart(), PK_I2CReadStatusGet(), PK_I2CSetStatus(), PK_I2CWriteAndReadStart(), PK_I2CWriteStart(), PK_I2CWriteStatusGet(), PK_LCDChangeMode(), PK_LCDClear(), PK_LCDConfigurationGet(), PK_LCDConfigurationSet(), PK_LCDDisplayOnOffControl(), PK_LCDEntryModeSet(), PK_LCDInit(), PK_LCDMoveCursor(), PK_LCDPrint(), PK_LCDPutChar(), PK_LCDSetCustomCharacters(), PK_LCDUpdate(), PK_MatrixKBConfigurationGet(), PK_MatrixKBConfigurationSet(), PK_MatrixKBStatusGet(), PK_MatrixLEDConfigurationGet(), PK_MatrixLEDConfigurationSet(), PK_MatrixLEDUpdate(), PK_NetworkConfigurationSet(), PK_PEv2_AdditionalParametersGet(), PK_PEv2_AdditionalParametersSet(), PK_PEv2_AxisConfigurationGet(), PK_PEv2_AxisConfigurationSet(), PK_PEv2_BacklashCompensationSettings_Get(), PK_PEv2_BacklashCompensationSettings_Set(), PK_PEv2_BufferClear(), PK_PEv2_BufferFill(), PK_PEv2_BufferFill_16(), PK_PEv2_BufferFillLarge(), PK_PEv2_BufferFillLarge_16(), PK_PEv2_ExternalOutputsGet(), PK_PEv2_ExternalOutputsSet(), PK_PEv2_HomingFinish(), PK_PEv2_HomingStart(), PK_PEv2_InternalDriversConfigurationGet(), PK_PEv2_InternalDriversConfigurationSet(), PK_PEv2_PositionSet(), PK_PEv2_ProbingFinish(), PK_PEv2_ProbingFinishSimple(), PK_PEv2_ProbingHybridStart(), PK_PEv2_ProbingStart(), PK_PEv2_PulseEngineMove(), PK_PEv2_PulseEngineMovePV(), PK_PEv2_PulseEngineReboot(), PK_PEv2_PulseEngineSetup(), PK_PEv2_PulseEngineStateSet(), PK_PEv2_Status2Get(), PK_PEv2_StatusGet(), PK_PEv2_SyncedPWMSetup(), PK_PEv2_SyncOutputsSetup(), PK_PEv2_ThreadingCancel(), PK_PEv2_ThreadingForceTriggerReady(), PK_PEv2_ThreadingPrepareForTrigger(), PK_PEv2_ThreadingRelease(), PK_PEv2_ThreadingSetup(), PK_PEv2_ThreadingStatusGet(), PK_PEv2_ThreadingTrigger(), PK_PinConfigurationGet(), PK_PinConfigurationSet(), PK_PoExtBusGet(), PK_PoExtBusSet(), PK_PoILChunkReadMemory(), PK_PoILChunkReadMemoryInternalAddress(), PK_PoILEraseMemory(), PK_PoILGetState(), PK_PoILReadMemory(), PK_PoILReadSharedSlot(), PK_PoILResetCore(), PK_PoILSetCoreState(), PK_PoILSetDebugMode(), PK_PoILSetMasterEnable(), PK_PoILTaskStatus(), PK_PoILWriteMemory(), PK_PoILWriteSharedSlot(), PK_PoNETGetModuleLight(), PK_PoNETGetModuleLightRequest(), PK_PoNETGetModuleSettings(), PK_PoNETGetModuleStatus(), PK_PoNETGetModuleStatusRequest(), PK_PoNETGetPoNETStatus(), PK_PoNETSetModulePWM(), PK_PoNETSetModuleStatus(), PK_PoStep_ConfigurationGet(), PK_PoStep_ConfigurationSet(), PK_PoStep_DriverConfigurationGet(), PK_PoStep_DriverConfigurationSet(), PK_PoStep_StatusGet(), PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), PK_PWMUpdate(), PK_ReadDeviceLog(), PK_RTCGet(), PK_RTCSet(), PK_SaveConfiguration(), PK_SecurityStatusGet(), PK_SetFastUSBEnableStatus(), PK_SPIConfigure(), PK_SPIRead(), PK_SPIWrite(), PK_UARTConfigure(), PK_UARTRead(), PK_UARTWrite(), PK_UserAuthorise(), PK_UserPasswordSet(), PK_WS2812_SendLEDdataEx(), and PK_WS2812_Update().
getChecksum()
uint8_t getChecksum (uint8_t * data)
Definition at line 673 of file PoKeysLibCore.c.
References i.
Referenced by SendEthRequest(), SendEthRequest_NoResponse(), SendEthRequestBig(), SendRequest(), and SendRequest_NoResponse().
InitializeNewDevice()
void InitializeNewDevice (sPoKeysDevice * device)
General pin settings PoKeys55, PoKeys56, PoKeys57 limitations
Pin codes used in PoKeys55 device are 0-based, e.g. pin 1 has pin code of 0, pin 55 has pin code of 54.
Analog input capable pins 43 to 47 have pin codes of 42 to 46.
Analog output capable pin 43 has pin code of 42.
PWM (pulse-width modulation) capable pins 17 to 22 have pin codes of 16-21 (PWM module outputs are in reversed order, e.g. pin 17 (pin coded as 16) is connected to PWM6 output – see specifications below).
PoKeys57CNC device supports PWM output function on 4 pins (pins 18, 20, 21 and 22). Different duty cycles can be assigned to each PWM output however, all outputs share the same PWM period. PWM outputs can be easily amplified using an external transistor and used for control of loads with increased increased current demand - pins with such function embedded are marked as OC (open-collector) in the pinout diagram. PoKeys PWM outputs can also be used to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). PoKeys devices have an in-built PWM module that operates at a fixed clock frequency (25 MHz). Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000)
PoKeys57CNCpro4x25 device supports PWM output function on pins 17 and 20. Pin 17 is wired to 0- 10 V output for spindle control – the output voltage is proportional to the duty cycle of the PWM output. PWM output on pin 20 is located on dedicated connector and can be easily amplified using an external transistor and used for controlling the loads with increased current demand – we offer MOSFET power switch adapter for such purposes in PoLabs online store. The frequency of the generated PWM signal can be changed – for the analog output functionality on pin 17 to operate as designed, a PWM frequency of 20 kHz is suggested. However, if needed, the frequency of PoKeys PWM outputs can be reduced – e.g. to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). In such case, analog output on pin 17 will not be operational. PoKeys devices have a built-in PWM module that operates at a fixed clock frequency of 25 MHz. Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000).
General pin settings PoKeys55, PoKeys56, PoKeys57 limitations
Pin codes used in PoKeys55 device are 0-based, e.g. pin 1 has pin code of 0, pin 55 has pin code of 54.
Analog input capable pins 43 to 47 have pin codes of 42 to 46.
Analog output capable pin 43 has pin code of 42.
PWM (pulse-width modulation) capable pins 17 to 22 have pin codes of 16-21 (PWM module outputs are in reversed order, e.g. pin 17 (pin coded as 16) is connected to PWM6 output – see specifications below).
PoKeys57CNC device supports PWM output function on 4 pins (pins 18, 20, 21 and 22). Different duty cycles can be assigned to each PWM output however, all outputs share the same PWM period. PWM outputs can be easily amplified using an external transistor and used for control of loads with increased increased current demand - pins with such function embedded are marked as OC (open-collector) in the pinout diagram. PoKeys PWM outputs can also be used to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). PoKeys devices have an in-built PWM module that operates at a fixed clock frequency (25 MHz). Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000)
PoKeys57CNCpro4x25 device supports PWM output function on pins 17 and 20. Pin 17 is wired to 0- 10 V output for spindle control – the output voltage is proportional to the duty cycle of the PWM output. PWM output on pin 20 is located on dedicated connector and can be easily amplified using an external transistor and used for controlling the loads with increased current demand – we offer MOSFET power switch adapter for such purposes in PoLabs online store. The frequency of the generated PWM signal can be changed – for the analog output functionality on pin 17 to operate as designed, a PWM frequency of 20 kHz is suggested. However, if needed, the frequency of PoKeys PWM outputs can be reduced – e.g. to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). In such case, analog output on pin 17 will not be operational. PoKeys devices have a built-in PWM module that operates at a fixed clock frequency of 25 MHz. Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000).
Definition at line 89 of file PoKeysLibCore.c.
PK_DisconnectNetworkDevice()
void PK_DisconnectNetworkDevice (sPoKeysDevice * device)
Definition at line 559 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, and PK_DeviceType_NetworkDevice.
PK_FillPWMPinNumbers()
int32_t PK_FillPWMPinNumbers (sPoKeysDevice * device)
Populate PWM pin ID table in the device structure.
Depending on the connected device type the PWM outputs are mapped to different PoKeys pins. This helper fills sPoKeysPWM.PWMpinIDs using hard coded mappings.
Parameters
device Target device handle with populated info block.
Returns
PK_OK on success or PK_ERR_NOT_SUPPORTED when PWM is not available.
Definition at line 1050 of file PoKeysLibDeviceData.c.
References sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceType, sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_DeviceID_PoKeys57CNCdb25, PK_ERR_NOT_SUPPORTED, PK_OK, sPoKeysDevice::PWM, and sPoKeysPWM::PWMpinIDs.
SendRequest()
int32_t SendRequest (sPoKeysDevice * device)
Send a request and wait for the device response.
Send a prepared request and wait for the response.
The function finalises the 64 byte request by prepending the packet header (0xBB), assigning a request ID and calculating the checksum (simple sum of bytes 0–6). The request is transmitted over the currently selected interface. After sending the packet the function waits for a reply with header 0xAA that carries the same request ID and a valid checksum.
Parameters
device Device that holds the prepared request buffer.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Send a request and wait for the device response.
Formats the current request buffer, transmits it over the selected interface and waits for the reply in a blocking loop. Functionally identical to the synchronous version.
Parameters
device Target device instance.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 712 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, getChecksum(), hid_read(), hid_write(), i, LastRetryCount, LastWaitCount, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, RTAPI_MSG_ERR, rtapi_print_msg(), SendEthRequest(), and SendRequestFastUSB.
Referenced by PK57i_Update(), PK_1WireBusScanContinue(), PK_1WireBusScanGetResults(), PK_1WireBusScanStart(), PK_1WireBusScanStop(), PK_1WireReadStatusGet(), PK_1WireStatusGet(), PK_1WireStatusSet(), PK_1WireWriteReadStart(), PK_1WireWriteReadStartEx(), PK_AnalogIOGet(), PK_AnalogRCFilterGet(), PK_AnalogRCFilterSet(), PK_CANConfigure(), PK_CANFlush(), PK_CANRead(), PK_CANRegisterFilter(), PK_CANWrite(), PK_ClearConfiguration(), PK_COSMSettingsGet(), PK_COSMSettingsSet(), PK_CustomRequest(), PK_DeviceActivation(), PK_DeviceActivationClear(), PK_DeviceDataGet(), PK_DeviceNameSet(), PK_DigitalCounterClear(), PK_DigitalCounterGet(), PK_DigitalIOGet(), PK_DigitalIOGetSingle(), PK_DigitalIOSet(), PK_DigitalIOSetGet(), PK_DigitalIOSetSingle(), PK_EasySensorsSetupGet(), PK_EasySensorsSetupSet(), PK_EasySensorsValueGetAll(), PK_EncoderConfigurationGet(), PK_EncoderConfigurationSet(), PK_EncoderValuesGet(), PK_EncoderValuesSet(), PK_FailsafeSettingsGet(), PK_FailsafeSettingsSet(), PK_GetDebugValues(), PK_GetFastUSBEnableStatus(), PK_I2CBusScanGetResults(), PK_I2CBusScanStart(), PK_I2CGetStatus(), PK_I2CReadStart(), PK_I2CReadStatusGet(), PK_I2CSetStatus(), PK_I2CWriteAndReadStart(), PK_I2CWriteStart(), PK_I2CWriteStatusGet(), PK_LCDChangeMode(), PK_LCDClear(), PK_LCDConfigurationGet(), PK_LCDConfigurationSet(), PK_LCDDisplayOnOffControl(), PK_LCDEntryModeSet(), PK_LCDInit(), PK_LCDMoveCursor(), PK_LCDPrint(), PK_LCDPutChar(), PK_LCDSetCustomCharacters(), PK_LCDUpdate(), PK_MatrixKBConfigurationGet(), PK_MatrixKBConfigurationSet(), PK_MatrixKBStatusGet(), PK_MatrixLEDConfigurationGet(), PK_MatrixLEDConfigurationSet(), PK_MatrixLEDUpdate(), PK_NetworkConfigurationSet(), PK_PEv2_AdditionalParametersGet(), PK_PEv2_AdditionalParametersSet(), PK_PEv2_AxisConfigurationGet(), PK_PEv2_AxisConfigurationSet(), PK_PEv2_BacklashCompensationSettings_Get(), PK_PEv2_BacklashCompensationSettings_Set(), PK_PEv2_BufferClear(), PK_PEv2_BufferFill(), PK_PEv2_BufferFill_16(), PK_PEv2_ExternalOutputsGet(), PK_PEv2_ExternalOutputsSet(), PK_PEv2_HomingFinish(), PK_PEv2_HomingStart(), PK_PEv2_InternalDriversConfigurationGet(), PK_PEv2_InternalDriversConfigurationSet(), PK_PEv2_PositionSet(), PK_PEv2_ProbingFinish(), PK_PEv2_ProbingFinishSimple(), PK_PEv2_ProbingHybridStart(), PK_PEv2_ProbingStart(), PK_PEv2_PulseEngineMove(), PK_PEv2_PulseEngineMovePV(), PK_PEv2_PulseEngineReboot(), PK_PEv2_PulseEngineSetup(), PK_PEv2_PulseEngineStateSet(), PK_PEv2_Status2Get(), PK_PEv2_StatusGet(), PK_PEv2_SyncedPWMSetup(), PK_PEv2_SyncOutputsSetup(), PK_PEv2_ThreadingCancel(), PK_PEv2_ThreadingForceTriggerReady(), PK_PEv2_ThreadingPrepareForTrigger(), PK_PEv2_ThreadingRelease(), PK_PEv2_ThreadingSetup(), PK_PEv2_ThreadingStatusGet(), PK_PEv2_ThreadingTrigger(), PK_PinConfigurationGet(), PK_PinConfigurationSet(), PK_PoExtBusGet(), PK_PoExtBusSet(), PK_PoILChunkReadMemory(), PK_PoILChunkReadMemoryInternalAddress(), PK_PoILEraseMemory(), PK_PoILGetState(), PK_PoILReadMemory(), PK_PoILReadSharedSlot(), PK_PoILResetCore(), PK_PoILSetCoreState(), PK_PoILSetDebugMode(), PK_PoILSetMasterEnable(), PK_PoILTaskStatus(), PK_PoILWriteMemory(), PK_PoILWriteSharedSlot(), PK_PoNETGetModuleLight(), PK_PoNETGetModuleLightRequest(), PK_PoNETGetModuleSettings(), PK_PoNETGetModuleStatus(), PK_PoNETGetModuleStatusRequest(), PK_PoNETGetPoNETStatus(), PK_PoNETSetModulePWM(), PK_PoNETSetModuleStatus(), PK_PoStep_ConfigurationGet(), PK_PoStep_ConfigurationSet(), PK_PoStep_DriverConfigurationGet(), PK_PoStep_DriverConfigurationSet(), PK_PoStep_StatusGet(), PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), PK_PWMUpdate(), PK_ReadDeviceLog(), PK_RTCGet(), PK_RTCSet(), PK_SaveConfiguration(), PK_SecurityStatusGet(), PK_SetFastUSBEnableStatus(), PK_SPIConfigure(), PK_SPIRead(), PK_SPIWrite(), PK_UARTConfigure(), PK_UARTRead(), PK_UARTWrite(), PK_UserAuthorise(), PK_UserPasswordSet(), and PK_WS2812_Update().
SendRequest_multiPart()
int32_t SendRequest_multiPart (sPoKeysDevice * device)
Send a multipart data transfer.
Send a multipart (PK_CMD_MULTIPART_PACKET) request.
Large data blocks are transferred using the command PK_CMD_MULTIPART_PACKET. The function delegates the actual transmission to the network or fast USB helpers depending on the device connection type.
The multipart buffer and packet headers must be prepared by the caller in device before invoking this function.
Parameters
device Target device instance.
Returns
PK_OK on success or an error code on failure.
Send a multipart data transfer.
For large data transfers the packet is split into 8 blocks and transmitted using network or fast USB helpers. Behaviour matches the synchronous SendRequest_multiPart() routine.
Parameters
device Device handle containing prepared multipart data.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 690 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, SendEthRequestBig(), and SendRequestFastUSB_multiPart.
Referenced by PK_PEv2_BufferFillLarge(), and PK_PEv2_BufferFillLarge_16().
SendRequest_NoResponse()
int32_t SendRequest_NoResponse (sPoKeysDevice * device)
Send a request without waiting for any reply.
Send a request without waiting for a reply.
The packet formatting is identical to SendRequest() but the function returns immediately after the HID write call. It is typically used with commands that acknowledge through other means (for example PK_CMD_REBOOT_SYSTEM).
Parameters
device Device that holds the prepared request buffer.
Returns
PK_OK on successful USB transfer or PK_ERR_TRANSFER when the packet could not be sent.
Send a request without waiting for any reply.
The request buffer is formatted the same as in SendRequest() but the function returns immediately after sending the packet. Used for commands that do not generate a direct response.
Parameters
device Target device instance.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 811 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, getChecksum(), hid_write(), i, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, sPoKeysDevice::request, sPoKeysDevice::requestID, RTAPI_MSG_ERR, rtapi_print_msg(), and SendEthRequest_NoResponse().
Referenced by PK_WS2812_SendLEDdataEx().