LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibCoreSockets.c File Reference
PoKeysLibCoreSockets.c File Reference
Network transport helpers for PoKeys devices.
#include "PoKeysLibCore.h"
#include <unistd.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include "PoKeysLibHal.h"
Macros
#define debug_printf (void)
Typedefs
typedef unsigned long uint32
Functions
uint32 * GetBroadcastAddresses ()
int32_t PK_EnumerateNetworkDevices (sPoKeysNetworkDeviceSummary *devices, uint32_t timeout)
Convenience wrapper for discovering all network attached PoKeys devices.
int32_t PK_SearchNetworkDevices (sPoKeysNetworkDeviceSummary *devices, uint32_t timeout, uint32_t serialNumberToFind)
Broadcasts a discovery request and collects responses from PoKeys devices.
sPoKeysDevice * PK_ConnectToNetworkDevice (sPoKeysNetworkDeviceSummary *device)
void PK_DisconnectNetworkDevice (sPoKeysDevice *device)
int32_t SendEthRequest (sPoKeysDevice *device)
Sends a single request packet and waits for its 64 byte response.
int32_t SendEthRequest_NoResponse (sPoKeysDevice *device)
Sends a request packet without waiting for a reply.
int32_t SendEthRequestBig (sPoKeysDevice *device)
Sends a multi-part request stored in device->multiPartData.
void PK_SetEthernetRetryCountAndTimeout (sPoKeysDevice *device, uint32_t sendRetries, uint32_t readRetries, uint32_t timeout)
Detailed Description
Network transport helpers for PoKeys devices.
Implements discovery and packet transfer over UDP/TCP as described in the PoKeys protocol specification.
Definition in file PoKeysLibCoreSockets.c.
Macro Definition Documentation
debug_printf
#define debug_printf (void)
Definition at line 57 of file PoKeysLibCoreSockets.c.
Typedef Documentation
uint32
typedef unsigned long uint32
Definition at line 62 of file PoKeysLibCoreSockets.c.
Function Documentation
GetBroadcastAddresses()
uint32 * GetBroadcastAddresses (void)
Definition at line 76 of file PoKeysLibCoreSockets.c.
References hal_malloc(), and i.
PK_ConnectToNetworkDevice()
sPoKeysDevice * PK_ConnectToNetworkDevice (sPoKeysNetworkDeviceSummary * device)
Definition at line 474 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionParam, sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, hal_malloc(), InitializeNewDevice(), sPoKeysNetworkDeviceSummary::IPaddress, PK_ConnectionParam_UDP, PK_DeviceType_NetworkDevice, RTAPI_MSG_ERR, rtapi_print_msg(), TRUE, and sPoKeysNetworkDeviceSummary::useUDP.
Referenced by PK57i_Connect(), PK_ConnectToPoKeysDevice_Ethernet(), and PK_ConnectToPoKeysDevice_Ethernet_Async().
PK_DisconnectNetworkDevice()
void PK_DisconnectNetworkDevice (sPoKeysDevice * device)
Definition at line 601 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, and PK_DeviceType_NetworkDevice.
Referenced by PK_DisconnectDevice().
PK_EnumerateNetworkDevices()
int32_t PK_EnumerateNetworkDevices (sPoKeysNetworkDeviceSummary * devices, uint32_t timeout)
Convenience wrapper for discovering all network attached PoKeys devices.
Calls PK_SearchNetworkDevices() with serialNumberToFind set to 0 so that all responding PoKeys boards are reported.
Parameters
devices Pointer to an array of sPoKeysNetworkDeviceSummary where discovered devices will be stored.
timeout Discovery timeout in milliseconds.
Returns
Number of detected devices.
Definition at line 231 of file PoKeysLibCoreSockets.c.
References PK_SearchNetworkDevices().
PK_SearchNetworkDevices()
int32_t PK_SearchNetworkDevices (sPoKeysNetworkDeviceSummary * devices, uint32_t timeout, uint32_t serialNumberToFind)
Broadcasts a discovery request and collects responses from PoKeys devices.
A UDP packet is sent to every broadcast address returned by GetBroadcastAddresses(). Responses are gathered for up to timeout milliseconds and stored into the provided devices array (maximum 16 entries). If serialNumberToFind is non-zero the function stops early when a matching device is found.
Parameters
devices Array of sPoKeysNetworkDeviceSummary structures for storing discovered devices.
timeout Discovery timeout in milliseconds.
serialNumberToFind Optional serial number to look for (0 = any).
Returns
Number of discovered devices.
Definition at line 252 of file PoKeysLibCoreSockets.c.
References debug_printf, sPoKeysNetworkDeviceSummary::DHCP, sPoKeysNetworkDeviceSummary::FirmwareVersionMajor, sPoKeysNetworkDeviceSummary::FirmwareVersionMinor, GetBroadcastAddresses(), sPoKeysNetworkDeviceSummary::hostIP, sPoKeysNetworkDeviceSummary::HWtype, sPoKeysNetworkDeviceSummary::IPaddress, and sPoKeysNetworkDeviceSummary::SerialNumber.
Referenced by PK_ConnectToPoKeysDevice_Ethernet(), and PK_ConnectToPoKeysDevice_Ethernet_Async().
PK_SetEthernetRetryCountAndTimeout()
void PK_SetEthernetRetryCountAndTimeout (sPoKeysDevice * device, uint32_t sendRetries, uint32_t readRetries, uint32_t timeout)
Definition at line 1008 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::readRetries, sPoKeysDevice::sendRetries, and sPoKeysDevice::socketTimeout.
SendEthRequest()
int32_t SendEthRequest (sPoKeysDevice * device)
Sends a single request packet and waits for its 64 byte response.
The packet contained in device->request is transmitted using either UDP or TCP depending on the connection parameters. The function blocks using select()/recv() until a valid response is received or retries are exhausted.
Parameters
device Pointer to an initialized network sPoKeysDevice.
Returns
PK_OK on success or PK_ERR_TRANSFER on communication failure.
Definition at line 632 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionParam, sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), PK_ConnectionParam_UDP, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::readRetries, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, RTAPI_MSG_ERR, rtapi_print_msg(), sPoKeysDevice::sendRetries, and sPoKeysDevice::socketTimeout.
SendEthRequest_NoResponse()
int32_t SendEthRequest_NoResponse (sPoKeysDevice * device)
Sends a request packet without waiting for a reply.
Only the transmit part of SendEthRequest() is executed. The function returns once the packet is successfully sent or the send retries are exhausted.
Parameters
device Pointer to the target sPoKeysDevice.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 783 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionParam, sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), PK_ConnectionParam_UDP, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, sPoKeysDevice::request, sPoKeysDevice::requestID, and sPoKeysDevice::sendRetries.
SendEthRequestBig()
int32_t SendEthRequestBig (sPoKeysDevice * device)
Sends a multi-part request stored in device->multiPartData.
The data is split into eight packets (64 bytes each) and transmitted sequentially. After sending all parts the function waits for a single response packet. This is used when a request payload exceeds the standard 64 byte size.
Parameters
device Pointer to a connected sPoKeysDevice with a valid multi-part buffer.
Returns
PK_OK on success or PK_ERR_TRANSFER on timeout or communication errors.
Definition at line 854 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionParam, sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), i, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::multiPartData, PK_ConnectionParam_UDP, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::readRetries, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, sPoKeysDevice::sendRetries, and sPoKeysDevice::socketTimeout.