LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/pokeyslib/PoKeysLibIO.c File Reference
PoKeysLibIO.c File Reference
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
Functions
int32_t PK_PinConfigurationGet (sPoKeysDevice *device)
int32_t PK_PinConfigurationSet (sPoKeysDevice *device)
int32_t PK_IsCounterAvailable (sPoKeysDevice *device, uint8_t pinID)
int32_t PK_IsCounterAvailableByDevice (uint32_t deviceTypeMask, uint8_t pinID)
int32_t PK_IsCounterAvailableByTypeID (uint32_t deviceTypeID, uint8_t pinID)
int32_t PK_DigitalIOSet (sPoKeysDevice *device)
int32_t PK_DigitalIOGet (sPoKeysDevice *device)
int32_t PK_DigitalIOSetGet (sPoKeysDevice *device)
int32_t PK_DigitalIOSetSingle (sPoKeysDevice *device, uint8_t pinID, uint8_t pinValue)
int32_t PK_DigitalIOGetSingle (sPoKeysDevice *device, uint8_t pinID, uint8_t *pinValue)
int32_t PK_AnalogIOGet (sPoKeysDevice *device)
int32_t PK_AnalogIOGetAsArray (sPoKeysDevice *device, uint32_t *buffer)
int32_t PK_AnalogRCFilterGet (sPoKeysDevice *device)
int32_t PK_AnalogRCFilterSet (sPoKeysDevice *device)
int32_t PK_DigitalCounterGet (sPoKeysDevice *device)
int32_t PK_DigitalCounterClear (sPoKeysDevice *device)
int32_t PK_PWMConfigurationSet (sPoKeysDevice *device)
int32_t PK_PWMConfigurationGet (sPoKeysDevice *device)
int32_t PK_PWMUpdate (sPoKeysDevice *device)
int32_t PK_PWMConfigurationSetDirectly (sPoKeysDevice *device, uint32_t PWMperiod, uint8_t *enabledChannels)
int32_t PK_PWMUpdateDirectly (sPoKeysDevice *device, uint32_t *dutyCycles)
int32_t PK_SL_PWM_SetPeriod (sPoKeysDevice *device, uint32_t PWMperiod)
int32_t PK_SL_PWM_SetChannelEnabled (sPoKeysDevice *device, uint8_t channel, uint8_t enabled, uint32_t defaultDuty)
int32_t PK_SL_PWM_SetDuty (sPoKeysDevice *device, uint8_t channel, uint32_t duty)
int32_t PK_PoExtBusSet (sPoKeysDevice *device)
int32_t PK_PoExtBusGet (sPoKeysDevice *device)
Function Documentation
PK_AnalogIOGet()
int32_t PK_AnalogIOGet (sPoKeysDevice * device)
Retrieve analog input values from the device.
Values are copied into the sPoKeysDevice::AnalogInput array.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 483 of file PoKeysLibIO.c.
References sPoKeysPinData::AnalogValue, CreateRequest(), i, sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice::info, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_AnalogIOGetAsArray()
int32_t PK_AnalogIOGetAsArray (sPoKeysDevice * device, uint32_t * buffer)
Retrieve analog input values and store them in a user supplied buffer.
Parameters
device Pointer to an initialized device structure.
buffer Destination array of at least seven elements.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 502 of file PoKeysLibIO.c.
References sPoKeysPinData::AnalogValue, i, sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice::info, sPoKeysDevice::Pins, PK_AnalogIOGet(), PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, and PK_OK.
PK_AnalogRCFilterGet()
int32_t PK_AnalogRCFilterGet (sPoKeysDevice * device)
Get current RC filter constant for analog inputs.
Definition at line 522 of file PoKeysLibIO.c.
References sPoKeysOtherPeripherals::AnalogRCFilter, CreateRequest(), sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice::info, sPoKeysDevice::otherPeripherals, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_AnalogRCFilterSet()
int32_t PK_AnalogRCFilterSet (sPoKeysDevice * device)
Set RC filter constant for analog inputs.
Definition at line 536 of file PoKeysLibIO.c.
References sPoKeysOtherPeripherals::AnalogRCFilter, CreateRequest(), sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice::info, sPoKeysDevice::otherPeripherals, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_DigitalCounterClear()
int32_t PK_DigitalCounterClear (sPoKeysDevice * device)
Clear all digital counters on the device.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 611 of file PoKeysLibIO.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_DigitalCounterGet()
int32_t PK_DigitalCounterGet (sPoKeysDevice * device)
Read digital counter values from the device.
Counter values are placed in the sPoKeysDevice::Pins array.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 552 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysPinData::DigitalCounterValue, i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_IsCounterAvailable(), PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DigitalIOGet()
int32_t PK_DigitalIOGet (sPoKeysDevice * device)
Read digital input values from the device.
Input states are stored in the sPoKeysDevice structure.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 411 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysPinData::DigitalValueGet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DigitalIOGetSingle()
int32_t PK_DigitalIOGetSingle (sPoKeysDevice * device, uint8_t pinID, uint8_t * pinValue)
Read the state of a single digital input pin.
Parameters
device Pointer to an initialized device structure.
pinID Pin number to read.
pinValue Pointer that receives the pin state.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 468 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DigitalIOSet()
int32_t PK_DigitalIOSet (sPoKeysDevice * device)
Set digital output values for all pins.
The output values are read from the sPoKeysDevice structure and transferred to the device.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 389 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysPinData::DigitalValueSet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysPinData::preventUpdate, sPoKeysDevice::request, and SendRequest().
PK_DigitalIOSetGet()
int32_t PK_DigitalIOSetGet (sPoKeysDevice * device)
Atomically set digital outputs and read digital inputs.
This helper issues a single command that updates outputs and retrieves input states at the same time.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 428 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysPinData::DigitalValueGet, sPoKeysPinData::DigitalValueSet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysPinData::preventUpdate, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DigitalIOSetSingle()
int32_t PK_DigitalIOSetSingle (sPoKeysDevice * device, uint8_t pinID, uint8_t pinValue)
Change the state of a single digital output pin.
Parameters
device Pointer to an initialized device structure.
pinID Pin number to modify.
pinValue Desired output state (0 or 1).
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 455 of file PoKeysLibIO.c.
References CreateRequest(), sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_IsCounterAvailable()
int32_t PK_IsCounterAvailable (sPoKeysDevice * device, uint8_t pinID)
Check whether a specific pin supports a digital counter.
Parameters
device Pointer to an initialized device structure.
pinID Pin number to query.
Returns
Non-zero if a counter is available, zero otherwise.
Definition at line 271 of file PoKeysLibIO.c.
References sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceTypeID, and PK_IsCounterAvailableByDevice().
PK_IsCounterAvailableByDevice()
int32_t PK_IsCounterAvailableByDevice (uint32_t deviceTypeMask, uint8_t pinID)
Test counter availability for a device type mask.
Parameters
deviceTypeMask Device type mask (see ePK_DeviceTypeMask).
pinID Pin number to query.
Returns
Non-zero if a counter is available, zero otherwise.
Definition at line 293 of file PoKeysLibIO.c.
References PK_DeviceMask_56, PK_DeviceMask_57, PK_DeviceMask_57CNC, PK_DeviceMask_57CNCdb25, PK_DeviceMask_57CNCpro4x25, PK_DeviceMask_Bootloader, and PK_DeviceMask_PoPLC58.
PK_IsCounterAvailableByTypeID()
int32_t PK_IsCounterAvailableByTypeID (uint32_t deviceTypeID, uint8_t pinID)
Test counter availability for a specific device ID.
Parameters
deviceTypeID Device type ID (see ePK_DeviceTypeID).
pinID Pin number to query.
Returns
Non-zero if a counter is available, zero otherwise.
Definition at line 335 of file PoKeysLibIO.c.
References PK_DeviceID_27E, PK_DeviceID_27U, PK_DeviceID_55v1, PK_DeviceID_55v2, PK_DeviceID_55v3, PK_DeviceID_56E, PK_DeviceID_56U, PK_DeviceID_57E, PK_DeviceID_57E_v0, PK_DeviceID_57U, PK_DeviceID_57U_v0, PK_DeviceID_58EU, PK_DeviceID_PoKeys57CNC, PK_DeviceID_PoKeys57CNCpro4x25, and PK_DeviceID_PoPLC58.
PK_PinConfigurationGet()
int32_t PK_PinConfigurationGet (sPoKeysDevice * device)
Retrieve pin configuration from the device.
Populates the sPoKeysDevice structure with the current pin setup.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 24 of file PoKeysLibIO.c.
References sPoKeysPinData::CounterOptions, CreateRequest(), sPoKeysPinData::DigitalCounterAvailable, sPoKeysPinData::downKeyCodeMacroID, sPoKeysPinData::downKeyModifier, i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iTriggeredKeyMapping, sPoKeysPinData::KeyCodeMacroID, sPoKeysPinData::KeyModifier, sPoKeysPinData::MappingType, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_IsCounterAvailable(), PK_OK, PK_PinCap_digitalInput, PK_PinCap_triggeredInput, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysPinData::upKeyCodeMacroID, and sPoKeysPinData::upKeyModifier.
PK_PinConfigurationSet()
int32_t PK_PinConfigurationSet (sPoKeysDevice * device)
Send pin configuration to the device.
The pin configuration is taken from the sPoKeysDevice structure and written back to the connected PoKeys device.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 158 of file PoKeysLibIO.c.
References sPoKeysPinData::CounterOptions, CreateRequest(), sPoKeysPinData::downKeyCodeMacroID, sPoKeysPinData::downKeyModifier, i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iTriggeredKeyMapping, sPoKeysPinData::KeyCodeMacroID, sPoKeysPinData::KeyModifier, sPoKeysPinData::MappingType, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PinCap_digitalInput, PK_PinCap_triggeredInput, sPoKeysDevice::request, SendRequest(), sPoKeysPinData::upKeyCodeMacroID, and sPoKeysPinData::upKeyModifier.
PK_PoExtBusGet()
int32_t PK_PoExtBusGet (sPoKeysDevice * device)
Read current PoExtBus output values from the device.
The values are stored into sPoKeysDevice::PoExtBusData.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 750 of file PoKeysLibIO.c.
References CreateRequest(), i, sPoKeysDevice::info, sPoKeysDevice_Info::iPoExtBus, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoExtBusData, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoExtBusSet()
int32_t PK_PoExtBusSet (sPoKeysDevice * device)
Write values to the PoExtBus expansion bus.
The data bytes are taken from sPoKeysDevice::PoExtBusData.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 728 of file PoKeysLibIO.c.
References CreateRequest(), i, sPoKeysDevice::info, sPoKeysDevice_Info::iPoExtBus, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoExtBusData, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PWMConfigurationGet()
int32_t PK_PWMConfigurationGet (sPoKeysDevice * device)
Read current PWM configuration from the device.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 641 of file PoKeysLibIO.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PWMConfigurationSet()
int32_t PK_PWMConfigurationSet (sPoKeysDevice * device)
Send PWM channel configuration to the device.
Enabled channels, duty cycles and period are taken from the sPoKeysDevice::PWM structure.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 621 of file PoKeysLibIO.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysDevice::request, and SendRequest().
PK_PWMConfigurationSetDirectly()
int32_t PK_PWMConfigurationSetDirectly (sPoKeysDevice * device, uint32_t PWMperiod, uint8_t * enabledChannels)
Convenience helper that sets PWM configuration directly.
Parameters
device Pointer to an initialized device structure.
PWMperiod PWM period in clock ticks.
enabledChannels Array of six flags indicating enabled channels.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 682 of file PoKeysLibIO.c.
References PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_OK, PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
PK_PWMUpdate()
int32_t PK_PWMUpdate (sPoKeysDevice * device)
Update PWM duty cycles without changing the period.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 661 of file PoKeysLibIO.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysDevice::request, and SendRequest().
PK_PWMUpdateDirectly()
int32_t PK_PWMUpdateDirectly (sPoKeysDevice * device, uint32_t * dutyCycles)
Update duty cycles using the provided array of values.
Parameters
device Pointer to an initialized device structure.
dutyCycles Array of six duty cycle values.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 694 of file PoKeysLibIO.c.
References PK_ERR_NOT_CONNECTED, PK_PWMUpdate(), sPoKeysDevice::PWM, and sPoKeysPWM::PWMduty.
PK_SL_PWM_SetChannelEnabled()
int32_t PK_SL_PWM_SetChannelEnabled (sPoKeysDevice * device, uint8_t channel, uint8_t enabled, uint32_t defaultDuty)
Enable or disable a PWM channel in the simple layer API.
Parameters
device Pointer to an initialized device structure.
channel Channel index (05).
enabled Non-zero to enable the channel.
defaultDuty Duty cycle written when enabling the channel.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 711 of file PoKeysLibIO.c.
References PK_ERR_NOT_CONNECTED, PK_PWMConfigurationSet(), sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, and sPoKeysPWM::PWMenabledChannels.
PK_SL_PWM_SetDuty()
int32_t PK_SL_PWM_SetDuty (sPoKeysDevice * device, uint8_t channel, uint32_t duty)
Update duty cycle of a PWM channel in the simple layer API.
Parameters
device Pointer to an initialized device structure.
channel Channel index (05).
duty New duty cycle value.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 720 of file PoKeysLibIO.c.
References PK_ERR_NOT_CONNECTED, PK_OK, sPoKeysDevice::PWM, and sPoKeysPWM::PWMduty.
PK_SL_PWM_SetPeriod()
int32_t PK_SL_PWM_SetPeriod (sPoKeysDevice * device, uint32_t PWMperiod)
Set PWM period using the simple layer API.
Parameters
device Pointer to an initialized device structure.
PWMperiod Desired PWM period in clock ticks.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 702 of file PoKeysLibIO.c.
References PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_OK, PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), sPoKeysDevice::PWM, and sPoKeysPWM::PWMperiod.