LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibRTCAsync.c File Reference
PoKeysLibRTCAsync.c File Reference
Asynchronous RTC (Real Time Clock) access for PoKeys devices.
#include "hal.h"
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
Functions
int export_rtc_pins (const char *prefix, long comp_id, sPoKeysDevice *device)
Exports RTC fields as HAL output pins.
int PK_RTCGetAsync_Process (sPoKeysDevice *device, const uint8_t *response)
Processes the RTC response and fills HAL-safe structure.
int PK_RTCGetAsync (sPoKeysDevice *device)
Starts an asynchronous RTC read from the device.
Detailed Description
Asynchronous RTC (Real Time Clock) access for PoKeys devices.
This file provides an asynchronous, non-blocking method to read RTC data from a PoKeys device using the CreateRequestAsync / SendRequestAsync / PK_ReceiveAndDispatch framework.
Features:
Uses per-transaction response buffers (no global buffers)
Parses RTC fields manually into HAL-safe hal_u32_t variables
Exports RTC fields (sec, min, hour, dow, dom, month, doy, year) as HAL output pins
Fully compatible with LinuxCNC Realtime HAL requirements
Functional Flow:
* [RT Thread]
*    ↓
*    PK_RTCGetAsync(device)
*      ↳ CreateRequestAsync(cmd=0x83, param=0x00, parser=PK_RTCGetAsync_Process)
*
* [Send Loop]
*    ↓
*    SendRequestAsync() sends packet
*
* [Receive Loop]
*    ↓
*    PK_ReceiveAndDispatch() receives packet
*      ↳ Calls PK_RTCGetAsync_Process(device, response)
*          ↳ Parses RTC fields (SEC, MIN, HOUR, etc.)
*          ↳ Fills device->RTC fields
*
* [HAL Pins]
*    ↓
*    HAL pins (rtc_sec, rtc_min, etc.) are now updated automatically.
*
Notes:
target_ptr is NULL because parsing is handled manually in the parser function.
No redundant rtc_response_buffer is needed — mailbox_entry's response_buffer[64] is used directly.
Definition in file PoKeysLibRTCAsync.c.
Function Documentation
export_rtc_pins()
int export_rtc_pins (const char * prefix, long comp_id, sPoKeysDevice * device)
Exports RTC fields as HAL output pins.
Parameters
prefix HAL pin name prefix
comp_id HAL component ID
device Pointer to sPoKeysDevice (contains rtc_data field)
Returns
0 on success, or negative HAL error code
Definition at line 56 of file PoKeysLibRTCAsync.c.
PK_RTCGetAsync()
int PK_RTCGetAsync (sPoKeysDevice * device)
Starts an asynchronous RTC read from the device.
Parameters
device Pointer to PoKeys device
Returns
Request ID on success, negative error code on failure
Definition at line 127 of file PoKeysLibRTCAsync.c.
References CreateRequestAsync(), PK_CMD_RTC_SETTINGS, PK_ERR_NOT_CONNECTED, PK_RTCGetAsync_Process(), RTAPI_MSG_ERR, rtapi_print_msg(), and SendRequestAsync().
Referenced by FUNCTION(), and user_mainloop().
PK_RTCGetAsync_Process()
int PK_RTCGetAsync_Process (sPoKeysDevice * device, const uint8_t * response)
Processes the RTC response and fills HAL-safe structure.
Parameters
device Pointer to PoKeys device
response Pointer to full received UDP packet
Returns
PK_OK on success, PK_ERR otherwise
Definition at line 103 of file PoKeysLibRTCAsync.c.
References sPoKeysRTC::DOM, sPoKeysRTC::DOW, sPoKeysRTC::DOY, sPoKeysRTC::HOUR, sPoKeysRTC::MIN, sPoKeysRTC::MONTH, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::RTC, sPoKeysRTC::SEC, and sPoKeysRTC::YEAR.
Referenced by PK_RTCGetAsync().