LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibMatrixKBAsync.c File Reference
PoKeysLibMatrixKBAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Data Structures
struct MatrixKBAsyncCtx
Functions
int PK_MatrixKBConfigurationGetAsync (sPoKeysDevice *device)
int PK_MatrixKBConfigurationSetAsync (sPoKeysDevice *device)
int PK_MatrixKBStatusGetAsync (sPoKeysDevice *device)
Function Documentation
PK_MatrixKBConfigurationGetAsync()
int PK_MatrixKBConfigurationGetAsync (sPoKeysDevice * device)
Definition at line 85 of file PoKeysLibMatrixKBAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice::info, PK_CMD_MATRIX_KEYBOARD_CFG, and PK_ERR_NOT_CONNECTED.
PK_MatrixKBConfigurationSetAsync()
int PK_MatrixKBConfigurationSetAsync (sPoKeysDevice * device)
Definition at line 125 of file PoKeysLibMatrixKBAsync.c.
References CreateRequestAsyncWithPayload(), sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice_Info::iMatrixKeyboardTriggeredMapping, sPoKeysDevice::info, sMatrixKeyboard::keyMappingKeyCode, sMatrixKeyboard::keyMappingKeyCodeUp, sMatrixKeyboard::keyMappingKeyModifier, sMatrixKeyboard::keyMappingKeyModifierUp, sMatrixKeyboard::keyMappingTriggeredKey, sMatrixKeyboard::macroMappingOptions, sPoKeysDevice::matrixKB, sMatrixKeyboard::matrixKBcolumnsPins, sMatrixKeyboard::matrixKBconfiguration, sMatrixKeyboard::matrixKBheight, sMatrixKeyboard::matrixKBrowsPins, sMatrixKeyboard::matrixKBScanningDecimation, sMatrixKeyboard::matrixKBwidth, PK_CMD_MATRIX_KEYBOARD_CFG, PK_ERR_NOT_CONNECTED, PK_OK, and SendRequestAsync().
PK_MatrixKBStatusGetAsync()
int PK_MatrixKBStatusGetAsync (sPoKeysDevice * device)
Definition at line 232 of file PoKeysLibMatrixKBAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice::info, PK_CMD_MATRIX_KEYBOARD_CFG, PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.