LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibLCDAsync.c File Reference
PoKeysLibLCDAsync.c File Reference
Asynchronous LCD helper functions.
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Functions
int PK_LCDConfigurationGetAsync (sPoKeysDevice *device)
int PK_LCDConfigurationSetAsync (sPoKeysDevice *device)
int PK_LCDUpdateAsync (sPoKeysDevice *device)
int PK_LCDSetCustomCharactersAsync (sPoKeysDevice *device)
Detailed Description
Asynchronous LCD helper functions.
These routines mirror a subset of the blocking LCD API but use the PoKeysLibAsync request queue so that no network operation blocks the caller. Responses are parsed via small callbacks and device state is updated when packets arrive.
This design keeps the realtime thread free from any waiting on UDP traffic and fits the general asynchronous communication model used throughout the PoKeysHal project.
Definition in file PoKeysLibLCDAsync.c.
Function Documentation
PK_LCDConfigurationGetAsync()
int PK_LCDConfigurationGetAsync (sPoKeysDevice * device)
Definition at line 30 of file PoKeysLibLCDAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_CMD_LCD_CONFIGURATION, PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.
PK_LCDConfigurationSetAsync()
int PK_LCDConfigurationSetAsync (sPoKeysDevice * device)
Definition at line 43 of file PoKeysLibLCDAsync.c.
References sPoKeysLCD::Columns, sPoKeysLCD::Configuration, CreateRequestAsync(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, PK_CMD_LCD_CONFIGURATION, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, sPoKeysLCD::Rows, and SendRequestAsync().
PK_LCDSetCustomCharactersAsync()
int PK_LCDSetCustomCharactersAsync (sPoKeysDevice * device)
Definition at line 105 of file PoKeysLibLCDAsync.c.
References CreateRequestAsyncWithPayload(), sPoKeysLCD::customCharacters, sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_OK, and SendRequestAsync().
PK_LCDUpdateAsync()
int PK_LCDUpdateAsync (sPoKeysDevice * device)
Definition at line 76 of file PoKeysLibLCDAsync.c.
References CreateRequestAsyncWithPayload(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, sPoKeysLCD::line1, sPoKeysLCD::line2, sPoKeysLCD::line3, sPoKeysLCD::line4, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_OK, sPoKeysLCD::RowRefreshFlags, and SendRequestAsync().