LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibLCD.c File Reference
PoKeysLibLCD.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
Functions
int32_t PK_LCDConfigurationGet (sPoKeysDevice *device)
Retrieve LCD configuration from the device.
int32_t PK_LCDConfigurationSet (sPoKeysDevice *device)
Write LCD configuration to the device.
int32_t PK_LCDUpdate (sPoKeysDevice *device)
Update LCD display using buffered lines.
int32_t PK_LCDSetCustomCharacters (sPoKeysDevice *device)
Upload custom character patterns to the LCD.
int32_t PK_LCDChangeMode (sPoKeysDevice *device, uint8_t mode)
Switch LCD operating mode.
int32_t PK_LCDInit (sPoKeysDevice *device)
Initialise the LCD controller.
int32_t PK_LCDClear (sPoKeysDevice *device)
Clear the LCD display.
int32_t PK_LCDMoveCursor (sPoKeysDevice *device, uint8_t row, uint8_t column)
Move the LCD cursor to a specific position.
int32_t PK_LCDPrint (sPoKeysDevice *device, uint8_t *text, uint8_t textLen)
Print a string on the LCD.
int32_t PK_LCDPutChar (sPoKeysDevice *device, uint8_t character)
Output a single character on the LCD.
int32_t PK_LCDEntryModeSet (sPoKeysDevice *device, uint8_t cursorMoveDirection, uint8_t displayShift)
Configure the LCD entry mode register.
int32_t PK_LCDDisplayOnOffControl (sPoKeysDevice *device, uint8_t displayOnOff, uint8_t cursorOnOff, uint8_t cursorBlinking)
Control LCD display, cursor and blinking.
Function Documentation
PK_LCDChangeMode()
int32_t PK_LCDChangeMode (sPoKeysDevice * device, uint8_t mode)
Switch LCD operating mode.
Allows toggling between PK_LCD_MODE_DIRECT and PK_LCD_MODE_BUFFERED by issuing command PK_CMD_LCD_OPERATION with opcode 0x80.
Parameters
device Pointer to an initialized device structure.
mode Desired mode constant.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 162 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDClear()
int32_t PK_LCDClear (sPoKeysDevice * device)
Clear the LCD display.
Uses command PK_CMD_LCD_OPERATION with opcode 0x10 to erase the entire screen. Valid only in direct mode.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 203 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDConfigurationGet()
int32_t PK_LCDConfigurationGet (sPoKeysDevice * device)
Retrieve LCD configuration from the device.
Sends PK_CMD_LCD_CONFIGURATION with parameter 1 and stores returned parameters in the device's LCD structure.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 34 of file PoKeysLibLCD.c.
References sPoKeysLCD::Columns, sPoKeysLCD::Configuration, CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, PK_CMD_LCD_CONFIGURATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysLCD::Rows, and SendRequest().
PK_LCDConfigurationSet()
int32_t PK_LCDConfigurationSet (sPoKeysDevice * device)
Write LCD configuration to the device.
Transfers mode and size parameters stored in the LCD fields and performs initialisation and screen clear afterwards.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 60 of file PoKeysLibLCD.c.
References sPoKeysLCD::Columns, sPoKeysLCD::Configuration, CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, PK_CMD_LCD_CONFIGURATION, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysLCD::Rows, and SendRequest().
PK_LCDDisplayOnOffControl()
int32_t PK_LCDDisplayOnOffControl (sPoKeysDevice * device, uint8_t displayOnOff, uint8_t cursorOnOff, uint8_t cursorBlinking)
Control LCD display, cursor and blinking.
Command PK_CMD_LCD_OPERATION with opcode 0x60 configures the display on/off, cursor visibility and blinking options.
Parameters
device Pointer to an initialized device structure.
displayOnOff Non-zero to enable the display.
cursorOnOff Non-zero to show the cursor.
cursorBlinking Non-zero to enable blinking cursor.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 320 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDEntryModeSet()
int32_t PK_LCDEntryModeSet (sPoKeysDevice * device, uint8_t cursorMoveDirection, uint8_t displayShift)
Configure the LCD entry mode register.
Uses command PK_CMD_LCD_OPERATION with opcode 0x50 to set cursor movement direction and display shifting.
Parameters
device Pointer to an initialized device structure.
cursorMoveDirection 1 for increment, 0 for decrement.
displayShift Non-zero to shift display.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 296 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDInit()
int32_t PK_LCDInit (sPoKeysDevice * device)
Initialise the LCD controller.
Only valid when operating in PK_LCD_MODE_DIRECT mode. Issues command PK_CMD_LCD_OPERATION with opcode 0 to reset the display.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 184 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDMoveCursor()
int32_t PK_LCDMoveCursor (sPoKeysDevice * device, uint8_t row, uint8_t column)
Move the LCD cursor to a specific position.
Sends command PK_CMD_LCD_OPERATION with opcode 0x20 where param1 is the column and param2 the row.
Parameters
device Pointer to an initialized device structure.
row Target row number (starting from 0).
column Target column number (starting from 0).
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 224 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDPrint()
int32_t PK_LCDPrint (sPoKeysDevice * device, uint8_t * text, uint8_t textLen)
Print a string on the LCD.
In direct mode the text is transmitted using command PK_CMD_LCD_OPERATION with opcode 0x30. The string length is limited to 20 characters.
Parameters
device Pointer to an initialized device structure.
text Buffer containing the characters to display.
textLen Number of characters in text.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 246 of file PoKeysLibLCD.c.
References CreateRequest(), i, sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDPutChar()
int32_t PK_LCDPutChar (sPoKeysDevice * device, uint8_t character)
Output a single character on the LCD.
Uses command PK_CMD_LCD_OPERATION with opcode 0x31. Only valid in direct mode.
Parameters
device Pointer to an initialized device structure.
character Character to display.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 274 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_LCDSetCustomCharacters()
int32_t PK_LCDSetCustomCharacters (sPoKeysDevice * device)
Upload custom character patterns to the LCD.
Transfers the eight custom character bitmaps stored in sPoKeysLCD::customCharacters using the command PK_CMD_LCD_OPERATION with opcode 0x40.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 130 of file PoKeysLibLCD.c.
References CreateRequest(), sPoKeysLCD::customCharacters, i, sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
Referenced by Update_LCD().
PK_LCDUpdate()
int32_t PK_LCDUpdate (sPoKeysDevice * device)
Update LCD display using buffered lines.
Only lines flagged in sPoKeysLCD::RowRefreshFlags are transferred to the device with command PK_CMD_LCD_OPERATION opcode 0x85.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 90 of file PoKeysLibLCD.c.
References CreateRequest(), i, sPoKeysDevice_Info::iLCD, sPoKeysDevice::info, sPoKeysDevice::LCD, sPoKeysLCD::line1, sPoKeysLCD::line2, sPoKeysLCD::line3, sPoKeysLCD::line4, PK_CMD_LCD_OPERATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysLCD::RowRefreshFlags, and SendRequest().
Referenced by Update_LCD().