LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/pokeyslib/PoKeysLibPoNET.c File Reference
PoKeysLibPoNET.c File Reference
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
Functions
int32_t PK_PoNETGetPoNETStatus (sPoKeysDevice *device)
int32_t PK_PoNETGetModuleSettings (sPoKeysDevice *device)
int32_t PK_PoNETGetModuleStatusRequest (sPoKeysDevice *device)
int32_t PK_PoNETGetModuleStatus (sPoKeysDevice *device)
int32_t PK_PoNETSetModuleStatus (sPoKeysDevice *device)
int32_t PK_PoNETSetModulePWM (sPoKeysDevice *device)
int32_t PK_PoNETGetModuleLightRequest (sPoKeysDevice *device)
int32_t PK_PoNETGetModuleLight (sPoKeysDevice *device)
Function Documentation
PK_PoNETGetModuleLight()
int32_t PK_PoNETGetModuleLight (sPoKeysDevice * device)
Definition at line 118 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::lightValue, sPoNETmodule::moduleID, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoNETGetModuleLightRequest()
int32_t PK_PoNETGetModuleLightRequest (sPoKeysDevice * device)
Definition at line 108 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::moduleID, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, and SendRequest().
PK_PoNETGetModuleSettings()
int32_t PK_PoNETGetModuleSettings (sPoKeysDevice * device)
Definition at line 37 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::i2cAddress, sPoNETmodule::moduleID, sPoNETmodule::moduleOptions, sPoNETmodule::moduleSize, sPoNETmodule::moduleType, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoNETGetModuleStatus()
int32_t PK_PoNETGetModuleStatus (sPoKeysDevice * device)
Definition at line 64 of file PoKeysLibPoNET.c.
References CreateRequest(), PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), and sPoNETmodule::statusIn.
PK_PoNETGetModuleStatusRequest()
int32_t PK_PoNETGetModuleStatusRequest (sPoKeysDevice * device)
Definition at line 54 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::moduleID, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, and SendRequest().
PK_PoNETGetPoNETStatus()
int32_t PK_PoNETGetPoNETStatus (sPoKeysDevice * device)
Definition at line 25 of file PoKeysLibPoNET.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoNETmodule::PoNETstatus, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoNETSetModulePWM()
int32_t PK_PoNETSetModulePWM (sPoKeysDevice * device)
Definition at line 98 of file PoKeysLibPoNET.c.
References CreateRequest(), sPoNETmodule::moduleID, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoNETmodule::PWMduty, sPoKeysDevice::request, and SendRequest().
PK_PoNETSetModuleStatus()
int32_t PK_PoNETSetModuleStatus (sPoKeysDevice * device)
Definition at line 80 of file PoKeysLibPoNET.c.
References CreateRequest(), i, sPoNETmodule::moduleID, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoNETmodule, sPoKeysDevice::request, SendRequest(), and sPoNETmodule::statusOut.