LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeyslib/PoKeysLibCore.h File Reference
PoKeysLibCore.h File Reference
#include "hidapi.h"
#include <stdio.h>
#include <string.h>
#include "PoKeysLib.h"
Macros
#define ConnectToFastUSBInterface(device) NULL;
#define DisconnectFromFastUSBInterface(device) ;
#define SendRequestFastUSB(device) ;
#define SendRequestFastUSB_multiPart(device) ;
Functions
void InitializeNewDevice (sPoKeysDevice *device)
void CleanDevice (sPoKeysDevice *device)
void PK_DisconnectNetworkDevice (sPoKeysDevice *device)
int32_t CreateRequest (uint8_t *request, uint8_t type, uint8_t param1, uint8_t param2, uint8_t param3, uint8_t param4)
uint8_t getChecksum (uint8_t *data)
int32_t SendRequest (sPoKeysDevice *device)
int32_t SendRequest_multiPart (sPoKeysDevice *device)
int32_t SendRequest_NoResponse (sPoKeysDevice *device)
int32_t PK_FillPWMPinNumbers (sPoKeysDevice *device)
Macro Definition Documentation
ConnectToFastUSBInterface
#define ConnectToFastUSBInterface (device) NULL;
Definition at line 50 of file PoKeysLibCore.h.
DisconnectFromFastUSBInterface
#define DisconnectFromFastUSBInterface (device) ;
Definition at line 51 of file PoKeysLibCore.h.
SendRequestFastUSB
#define SendRequestFastUSB (device) ;
Definition at line 52 of file PoKeysLibCore.h.
SendRequestFastUSB_multiPart
#define SendRequestFastUSB_multiPart (device) ;
Definition at line 53 of file PoKeysLibCore.h.
Function Documentation
CleanDevice()
void CleanDevice (sPoKeysDevice * device)
Definition at line 187 of file PoKeysLibCore.c.
References sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::MatrixLED, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, sPoKeysDevice::Pins, sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMpinIDs.
Referenced by PK_ConnectToPoKeysDevice_USB(), PK_DisconnectDevice(), and PK_ReleaseDeviceStructure().
CreateRequest()
int32_t CreateRequest (uint8_t * request, uint8_t type, uint8_t param1, uint8_t param2, uint8_t param3, uint8_t param4)
Definition at line 647 of file PoKeysLibCore.c.
References PK_ERR_NOT_CONNECTED, and PK_OK.
Referenced by PK57i_Update(), PK_1WireBusScanContinue(), PK_1WireBusScanGetResults(), PK_1WireBusScanStart(), PK_1WireBusScanStop(), PK_1WireReadStatusGet(), PK_1WireStatusGet(), PK_1WireStatusSet(), PK_1WireWriteReadStart(), PK_1WireWriteReadStartEx(), PK_AnalogIOGet(), PK_AnalogRCFilterGet(), PK_AnalogRCFilterSet(), PK_CANConfigure(), PK_CANFlush(), PK_CANRead(), PK_CANRegisterFilter(), PK_CANWrite(), PK_ClearConfiguration(), PK_DeviceActivation(), PK_DeviceActivationClear(), PK_DeviceDataGet(), PK_DeviceNameSet(), PK_DigitalCounterClear(), PK_DigitalCounterGet(), PK_DigitalIOGet(), PK_DigitalIOGetSingle(), PK_DigitalIOSet(), PK_DigitalIOSetGet(), PK_DigitalIOSetSingle(), PK_EasySensorsSetupGet(), PK_EasySensorsSetupSet(), PK_EasySensorsValueGetAll(), PK_EncoderConfigurationGet(), PK_EncoderConfigurationSet(), PK_EncoderValuesGet(), PK_EncoderValuesSet(), PK_FailsafeSettingsGet(), PK_FailsafeSettingsSet(), PK_GetDebugValues(), PK_GetFastUSBEnableStatus(), PK_I2CBusScanGetResults(), PK_I2CBusScanStart(), PK_I2CGetStatus(), PK_I2CReadStart(), PK_I2CReadStatusGet(), PK_I2CSetStatus(), PK_I2CWriteAndReadStart(), PK_I2CWriteStart(), PK_I2CWriteStatusGet(), PK_LCDChangeMode(), PK_LCDClear(), PK_LCDConfigurationGet(), PK_LCDConfigurationSet(), PK_LCDDisplayOnOffControl(), PK_LCDEntryModeSet(), PK_LCDInit(), PK_LCDMoveCursor(), PK_LCDPrint(), PK_LCDPutChar(), PK_LCDSetCustomCharacters(), PK_LCDUpdate(), PK_MatrixKBConfigurationGet(), PK_MatrixKBConfigurationSet(), PK_MatrixKBStatusGet(), PK_MatrixLEDConfigurationGet(), PK_MatrixLEDConfigurationSet(), PK_MatrixLEDUpdate(), PK_NetworkConfigurationSet(), PK_PEv2_AdditionalParametersGet(), PK_PEv2_AdditionalParametersSet(), PK_PEv2_AxisConfigurationGet(), PK_PEv2_AxisConfigurationSet(), PK_PEv2_BacklashCompensationSettings_Get(), PK_PEv2_BacklashCompensationSettings_Set(), PK_PEv2_BufferClear(), PK_PEv2_BufferFill(), PK_PEv2_BufferFill_16(), PK_PEv2_BufferFillLarge(), PK_PEv2_BufferFillLarge_16(), PK_PEv2_ExternalOutputsGet(), PK_PEv2_ExternalOutputsSet(), PK_PEv2_HomingFinish(), PK_PEv2_HomingStart(), PK_PEv2_InternalDriversConfigurationGet(), PK_PEv2_InternalDriversConfigurationSet(), PK_PEv2_PositionSet(), PK_PEv2_ProbingFinish(), PK_PEv2_ProbingFinishSimple(), PK_PEv2_ProbingHybridStart(), PK_PEv2_ProbingStart(), PK_PEv2_PulseEngineMove(), PK_PEv2_PulseEngineMovePV(), PK_PEv2_PulseEngineReboot(), PK_PEv2_PulseEngineSetup(), PK_PEv2_PulseEngineStateSet(), PK_PEv2_Status2Get(), PK_PEv2_StatusGet(), PK_PEv2_SyncedPWMSetup(), PK_PEv2_SyncOutputsSetup(), PK_PEv2_ThreadingCancel(), PK_PEv2_ThreadingForceTriggerReady(), PK_PEv2_ThreadingPrepareForTrigger(), PK_PEv2_ThreadingRelease(), PK_PEv2_ThreadingSetup(), PK_PEv2_ThreadingStatusGet(), PK_PEv2_ThreadingTrigger(), PK_PinConfigurationGet(), PK_PinConfigurationSet(), PK_PoExtBusGet(), PK_PoExtBusSet(), PK_PoILChunkReadMemory(), PK_PoILChunkReadMemoryInternalAddress(), PK_PoILEraseMemory(), PK_PoILGetState(), PK_PoILReadMemory(), PK_PoILReadSharedSlot(), PK_PoILResetCore(), PK_PoILSetCoreState(), PK_PoILSetDebugMode(), PK_PoILSetMasterEnable(), PK_PoILTaskStatus(), PK_PoILWriteMemory(), PK_PoILWriteSharedSlot(), PK_PoNETGetModuleLight(), PK_PoNETGetModuleLightRequest(), PK_PoNETGetModuleSettings(), PK_PoNETGetModuleStatus(), PK_PoNETGetModuleStatusRequest(), PK_PoNETGetPoNETStatus(), PK_PoNETSetModulePWM(), PK_PoNETSetModuleStatus(), PK_PoStep_ConfigurationGet(), PK_PoStep_ConfigurationSet(), PK_PoStep_DriverConfigurationGet(), PK_PoStep_DriverConfigurationSet(), PK_PoStep_StatusGet(), PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), PK_PWMUpdate(), PK_ReadDeviceLog(), PK_RTCGet(), PK_RTCSet(), PK_SaveConfiguration(), PK_SetFastUSBEnableStatus(), PK_SPIConfigure(), PK_SPIRead(), PK_SPIWrite(), PK_UARTConfigure(), PK_UARTRead(), PK_UARTWrite(), PK_WS2812_SendLEDdataEx(), and PK_WS2812_Update().
getChecksum()
uint8_t getChecksum (uint8_t * data)
Definition at line 673 of file PoKeysLibCore.c.
References i.
Referenced by SendEthRequest(), SendEthRequest_NoResponse(), SendEthRequestBig(), SendRequest(), and SendRequest_NoResponse().
InitializeNewDevice()
void InitializeNewDevice (sPoKeysDevice * device)
Definition at line 89 of file PoKeysLibCore.c.
References sPoKeysDevice::DeviceData, sPoKeysPinData::DigitalCounterAvailable, sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice::LCD, sPoKeysDevice::matrixKB, sPoKeysDevice::MatrixLED, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, sPoKeysDevice::PEv2, sPoKeysDevice::Pins, PK_DeviceDataGet(), PK_FillPWMPinNumbers(), PK_IsCounterAvailable(), sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMpinIDs, sPoKeysDevice::readRetries, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysDevice::sendRetries, sPoKeysDevice::socketTimeout, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
Referenced by PK_ConnectToDevice(), PK_ConnectToNetworkDevice(), PK_ConnectToPoKeysDevice_Ethernet(), and PK_ConnectToPoKeysDevice_USB().
PK_DisconnectNetworkDevice()
void PK_DisconnectNetworkDevice (sPoKeysDevice * device)
Definition at line 559 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, and PK_DeviceType_NetworkDevice.
Referenced by PK_DisconnectDevice().
PK_FillPWMPinNumbers()
int32_t PK_FillPWMPinNumbers (sPoKeysDevice * device)
Definition at line 1050 of file PoKeysLibDeviceData.c.
References sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceType, sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_DeviceID_PoKeys57CNCdb25, PK_ERR_NOT_SUPPORTED, PK_OK, sPoKeysDevice::PWM, and sPoKeysPWM::PWMpinIDs.
Referenced by InitializeNewDevice().
SendRequest()
int32_t SendRequest (sPoKeysDevice * device)
Definition at line 712 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, getChecksum(), hid_read(), hid_write(), i, LastRetryCount, LastWaitCount, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, SendEthRequest(), and SendRequestFastUSB.
Referenced by PK57i_Update(), PK_1WireBusScanContinue(), PK_1WireBusScanGetResults(), PK_1WireBusScanStart(), PK_1WireBusScanStop(), PK_1WireReadStatusGet(), PK_1WireStatusGet(), PK_1WireStatusSet(), PK_1WireWriteReadStart(), PK_1WireWriteReadStartEx(), PK_AnalogIOGet(), PK_AnalogRCFilterGet(), PK_AnalogRCFilterSet(), PK_CANConfigure(), PK_CANFlush(), PK_CANRead(), PK_CANRegisterFilter(), PK_CANWrite(), PK_ClearConfiguration(), PK_CustomRequest(), PK_DeviceActivation(), PK_DeviceActivationClear(), PK_DeviceDataGet(), PK_DeviceNameSet(), PK_DigitalCounterClear(), PK_DigitalCounterGet(), PK_DigitalIOGet(), PK_DigitalIOGetSingle(), PK_DigitalIOSet(), PK_DigitalIOSetGet(), PK_DigitalIOSetSingle(), PK_EasySensorsSetupGet(), PK_EasySensorsSetupSet(), PK_EasySensorsValueGetAll(), PK_EncoderConfigurationGet(), PK_EncoderConfigurationSet(), PK_EncoderValuesGet(), PK_EncoderValuesSet(), PK_FailsafeSettingsGet(), PK_FailsafeSettingsSet(), PK_GetDebugValues(), PK_GetFastUSBEnableStatus(), PK_I2CBusScanGetResults(), PK_I2CBusScanStart(), PK_I2CGetStatus(), PK_I2CReadStart(), PK_I2CReadStatusGet(), PK_I2CSetStatus(), PK_I2CWriteAndReadStart(), PK_I2CWriteStart(), PK_I2CWriteStatusGet(), PK_LCDChangeMode(), PK_LCDClear(), PK_LCDConfigurationGet(), PK_LCDConfigurationSet(), PK_LCDDisplayOnOffControl(), PK_LCDEntryModeSet(), PK_LCDInit(), PK_LCDMoveCursor(), PK_LCDPrint(), PK_LCDPutChar(), PK_LCDSetCustomCharacters(), PK_LCDUpdate(), PK_MatrixKBConfigurationGet(), PK_MatrixKBConfigurationSet(), PK_MatrixKBStatusGet(), PK_MatrixLEDConfigurationGet(), PK_MatrixLEDConfigurationSet(), PK_MatrixLEDUpdate(), PK_NetworkConfigurationSet(), PK_PEv2_AdditionalParametersGet(), PK_PEv2_AdditionalParametersSet(), PK_PEv2_AxisConfigurationGet(), PK_PEv2_AxisConfigurationSet(), PK_PEv2_BacklashCompensationSettings_Get(), PK_PEv2_BacklashCompensationSettings_Set(), PK_PEv2_BufferClear(), PK_PEv2_BufferFill(), PK_PEv2_BufferFill_16(), PK_PEv2_ExternalOutputsGet(), PK_PEv2_ExternalOutputsSet(), PK_PEv2_HomingFinish(), PK_PEv2_HomingStart(), PK_PEv2_InternalDriversConfigurationGet(), PK_PEv2_InternalDriversConfigurationSet(), PK_PEv2_PositionSet(), PK_PEv2_ProbingFinish(), PK_PEv2_ProbingFinishSimple(), PK_PEv2_ProbingHybridStart(), PK_PEv2_ProbingStart(), PK_PEv2_PulseEngineMove(), PK_PEv2_PulseEngineMovePV(), PK_PEv2_PulseEngineReboot(), PK_PEv2_PulseEngineSetup(), PK_PEv2_PulseEngineStateSet(), PK_PEv2_Status2Get(), PK_PEv2_StatusGet(), PK_PEv2_SyncedPWMSetup(), PK_PEv2_SyncOutputsSetup(), PK_PEv2_ThreadingCancel(), PK_PEv2_ThreadingForceTriggerReady(), PK_PEv2_ThreadingPrepareForTrigger(), PK_PEv2_ThreadingRelease(), PK_PEv2_ThreadingSetup(), PK_PEv2_ThreadingStatusGet(), PK_PEv2_ThreadingTrigger(), PK_PinConfigurationGet(), PK_PinConfigurationSet(), PK_PoExtBusGet(), PK_PoExtBusSet(), PK_PoILChunkReadMemory(), PK_PoILChunkReadMemoryInternalAddress(), PK_PoILEraseMemory(), PK_PoILGetState(), PK_PoILReadMemory(), PK_PoILReadSharedSlot(), PK_PoILResetCore(), PK_PoILSetCoreState(), PK_PoILSetDebugMode(), PK_PoILSetMasterEnable(), PK_PoILTaskStatus(), PK_PoILWriteMemory(), PK_PoILWriteSharedSlot(), PK_PoNETGetModuleLight(), PK_PoNETGetModuleLightRequest(), PK_PoNETGetModuleSettings(), PK_PoNETGetModuleStatus(), PK_PoNETGetModuleStatusRequest(), PK_PoNETGetPoNETStatus(), PK_PoNETSetModulePWM(), PK_PoNETSetModuleStatus(), PK_PoStep_ConfigurationGet(), PK_PoStep_ConfigurationSet(), PK_PoStep_DriverConfigurationGet(), PK_PoStep_DriverConfigurationSet(), PK_PoStep_StatusGet(), PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), PK_PWMUpdate(), PK_ReadDeviceLog(), PK_RTCGet(), PK_RTCSet(), PK_SaveConfiguration(), PK_SetFastUSBEnableStatus(), PK_SPIConfigure(), PK_SPIRead(), PK_SPIWrite(), PK_UARTConfigure(), PK_UARTRead(), PK_UARTWrite(), and PK_WS2812_Update().
SendRequest_multiPart()
int32_t SendRequest_multiPart (sPoKeysDevice * device)
Definition at line 690 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, SendEthRequestBig(), and SendRequestFastUSB_multiPart.
Referenced by PK_PEv2_BufferFillLarge(), and PK_PEv2_BufferFillLarge_16().
SendRequest_NoResponse()
int32_t SendRequest_NoResponse (sPoKeysDevice * device)
Definition at line 811 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, getChecksum(), hid_write(), i, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, sPoKeysDevice::request, sPoKeysDevice::requestID, and SendEthRequest_NoResponse().
Referenced by PK_WS2812_SendLEDdataEx().