LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibPoNETAsync.c File Reference
PoKeysLibPoNETAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Functions
int PK_PoNETGetPoNETStatusAsync (sPoKeysDevice *device)
int PK_PoNETGetModuleSettingsAsync (sPoKeysDevice *device)
int PK_PoNETGetModuleStatusRequestAsync (sPoKeysDevice *device)
int PK_PoNETGetModuleStatusAsync (sPoKeysDevice *device)
int PK_PoNETSetModuleStatusAsync (sPoKeysDevice *device)
int PK_PoNETSetModulePWMAsync (sPoKeysDevice *device)
int PK_PoNETGetModuleLightRequestAsync (sPoKeysDevice *device)
int PK_PoNETGetModuleLightAsync (sPoKeysDevice *device)
Function Documentation
PK_PoNETGetModuleLightAsync()
int PK_PoNETGetModuleLightAsync (sPoKeysDevice * device)
Definition at line 127 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_GET_LIGHT_SENSOR, and sPoKeysDevice::PoNETmodule.
Referenced by PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETGetModuleLightRequestAsync()
int PK_PoNETGetModuleLightRequestAsync (sPoKeysDevice * device)
Definition at line 116 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_GET_LIGHT_SENSOR, sPoKeysDevice::PoNETmodule, and SendRequestAsync().
Referenced by PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETGetModuleSettingsAsync()
int PK_PoNETGetModuleSettingsAsync (sPoKeysDevice * device)
Definition at line 57 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_GET_MODULE_SETTINGS, and sPoKeysDevice::PoNETmodule.
Referenced by PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETGetModuleStatusAsync()
int PK_PoNETGetModuleStatusAsync (sPoKeysDevice * device)
Definition at line 80 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, and PONET_OP_GET_MODULE_DATA.
Referenced by PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETGetModuleStatusRequestAsync()
int PK_PoNETGetModuleStatusRequestAsync (sPoKeysDevice * device)
Definition at line 69 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_GET_MODULE_DATA, sPoKeysDevice::PoNETmodule, and SendRequestAsync().
Referenced by PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETGetPoNETStatusAsync()
int PK_PoNETGetPoNETStatusAsync (sPoKeysDevice * device)
Definition at line 46 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, and PONET_OP_GET_STATUS.
PK_PoNETSetModulePWMAsync()
int PK_PoNETSetModulePWMAsync (sPoKeysDevice * device)
Definition at line 104 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsync(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_SET_PWM_VALUE, sPoKeysDevice::PoNETmodule, sPoNETmodule::PWMduty, and SendRequestAsync().
Referenced by PK_PoNETKbd48CNCBrightnessSetAsync(), and PK_PoNETKbd48CNCUpdateCycleAsync().
PK_PoNETSetModuleStatusAsync()
int PK_PoNETSetModuleStatusAsync (sPoKeysDevice * device)
Definition at line 91 of file PoKeysLibPoNETAsync.c.
References CreateRequestAsyncWithPayload(), sPoNETmodule::moduleID, PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_SET_MODULE_DATA, sPoKeysDevice::PoNETmodule, SendRequestAsync(), and sPoNETmodule::statusOut.
Referenced by PK_PoNETKbd48CNCLEDSetPatternAsync(), and PK_PoNETKbd48CNCUpdateCycleAsync().