LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibSPIAsync.c File Reference
PoKeysLibSPIAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Functions
int PK_SPIConfigureAsync (sPoKeysDevice *device, uint8_t prescaler, uint8_t frameFormat)
Configure the SPI interface asynchronously (command 0xE5/0x01).
int PK_SPIWriteAsync (sPoKeysDevice *device, const uint8_t *buffer, uint8_t dataLength, uint8_t pinCS)
Write data to SPI bus asynchronously (command 0xE5/0x02).
int PK_SPIReadAsync (sPoKeysDevice *device, uint8_t *buffer, uint8_t dataLength)
Read data from SPI bus asynchronously (command 0xE5/0x03).
int PK_SPITransferAsync (sPoKeysDevice *device, const uint8_t *txBuffer, uint8_t *rxBuffer, uint8_t dataLength, uint8_t pinCS)
Perform SPI write/read transaction asynchronously (command 0xE5/0x04).
Function Documentation
PK_SPIConfigureAsync()
int PK_SPIConfigureAsync (sPoKeysDevice * device, uint8_t prescaler, uint8_t frameFormat)
Configure the SPI interface asynchronously (command 0xE5/0x01).
Non-blocking version of PK_SPIConfigure that schedules the request using the async framework.
Parameters
device Pointer to an initialised device structure.
prescaler SPI clock prescaler value.
frameFormat Frame configuration (mode, bit length etc.).
Returns
Request ID on success or negative error code on failure.
Definition at line 27 of file PoKeysLibSPIAsync.c.
References CreateRequestAsync(), PK_CMD_SPI_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_SPIReadAsync()
int PK_SPIReadAsync (sPoKeysDevice * device, uint8_t * buffer, uint8_t dataLength)
Read data from SPI bus asynchronously (command 0xE5/0x03).
Non-blocking version of PK_SPIRead that schedules the read operation. The response data will be available in the device response buffer after PK_ReceiveAndDispatch processes the reply.
Parameters
device Pointer to device structure.
buffer Buffer to receive data (can be NULL for async operation).
dataLength Number of bytes to read.
Returns
Request ID on success or negative error code on failure.
Definition at line 80 of file PoKeysLibSPIAsync.c.
References CreateRequestAsync(), PK_CMD_SPI_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_SPITransferAsync()
int PK_SPITransferAsync (sPoKeysDevice * device, const uint8_t * txBuffer, uint8_t * rxBuffer, uint8_t dataLength, uint8_t pinCS)
Perform SPI write/read transaction asynchronously (command 0xE5/0x04).
Combined write/read operation that transmits data while simultaneously receiving data from the SPI device. This is useful for SPI devices that continuously clock out data during transactions.
Parameters
device Pointer to device structure.
txBuffer Buffer containing data to transmit.
rxBuffer Buffer to receive data (can be NULL for async operation).
dataLength Number of bytes to transfer.
pinCS Chip select pin number.
Returns
Request ID on success or negative error code on failure.
Definition at line 109 of file PoKeysLibSPIAsync.c.
References CreateRequestAsyncWithPayload(), PK_CMD_SPI_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_SPIWriteAsync()
int PK_SPIWriteAsync (sPoKeysDevice * device, const uint8_t * buffer, uint8_t dataLength, uint8_t pinCS)
Write data to SPI bus asynchronously (command 0xE5/0x02).
Non-blocking version of PK_SPIWrite that schedules the write operation using the async framework.
Parameters
device Pointer to device structure.
buffer Data buffer to transmit.
dataLength Number of bytes to transmit (max 54).
pinCS Chip select pin number.
Returns
Request ID on success or negative error code on failure.
Definition at line 53 of file PoKeysLibSPIAsync.c.
References CreateRequestAsyncWithPayload(), PK_CMD_SPI_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, and SendRequestAsync().