LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibPoNETAsyncEnhanced.c File Reference
PoKeysLibPoNETAsyncEnhanced.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Functions
int PK_PoNETKbd48CNCUpdateCycleAsync (sPoKeysDevice *device)
int PK_PoNETKbd48CNCLEDSetPatternAsync (sPoKeysDevice *device, uint8_t pattern[6])
int PK_PoNETKbd48CNCBrightnessSetAsync (sPoKeysDevice *device, uint8_t brightness)
int PK_PoNETDeviceDiscoveryAsync (sPoKeysDevice *device)
int PK_PoNETModuleReinitializeAsync (sPoKeysDevice *device, uint8_t moduleID)
int PK_PoNETKbd48CNCGetButtonStateAsync (sPoKeysDevice *device, uint8_t buttonIndex, bool *pressed)
int PK_PoNETKbd48CNCSetLEDStateAsync (sPoKeysDevice *device, uint8_t ledIndex, bool on)
int PK_PoNETKbd48CNCSetMultipleLEDsAsync (sPoKeysDevice *device, const uint8_t *ledStates)
Function Documentation
PK_PoNETDeviceDiscoveryAsync()
int PK_PoNETDeviceDiscoveryAsync (sPoKeysDevice * device)
Definition at line 87 of file PoKeysLibPoNETAsyncEnhanced.c.
References CreateRequestAsync(), PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_DEVICE_DISCOVERY, and SendRequestAsync().
PK_PoNETKbd48CNCBrightnessSetAsync()
int PK_PoNETKbd48CNCBrightnessSetAsync (sPoKeysDevice * device, uint8_t brightness)
Definition at line 75 of file PoKeysLibPoNETAsyncEnhanced.c.
References PK_ERR_NOT_CONNECTED, PK_PoNETSetModulePWMAsync(), sPoKeysDevice::PoNETmodule, and sPoNETmodule::PWMduty.
PK_PoNETKbd48CNCGetButtonStateAsync()
int PK_PoNETKbd48CNCGetButtonStateAsync (sPoKeysDevice * device, uint8_t buttonIndex, bool * pressed)
Definition at line 134 of file PoKeysLibPoNETAsyncEnhanced.c.
References PK_ERR_GENERIC.
PK_PoNETKbd48CNCLEDSetPatternAsync()
int PK_PoNETKbd48CNCLEDSetPatternAsync (sPoKeysDevice * device, uint8_t pattern[6])
Definition at line 63 of file PoKeysLibPoNETAsyncEnhanced.c.
References PK_ERR_GENERIC, PK_PoNETSetModuleStatusAsync(), sPoKeysDevice::PoNETmodule, and sPoNETmodule::statusOut.
PK_PoNETKbd48CNCSetLEDStateAsync()
int PK_PoNETKbd48CNCSetLEDStateAsync (sPoKeysDevice * device, uint8_t ledIndex, bool on)
Definition at line 156 of file PoKeysLibPoNETAsyncEnhanced.c.
References PK_ERR_GENERIC.
PK_PoNETKbd48CNCSetMultipleLEDsAsync()
int PK_PoNETKbd48CNCSetMultipleLEDsAsync (sPoKeysDevice * device, const uint8_t * ledStates)
Definition at line 179 of file PoKeysLibPoNETAsyncEnhanced.c.
References i, PK_ERR_GENERIC, sPoKeysDevice::PoNETmodule, and sPoNETmodule::statusOut.
PK_PoNETKbd48CNCUpdateCycleAsync()
int PK_PoNETKbd48CNCUpdateCycleAsync (sPoKeysDevice * device)
Definition at line 18 of file PoKeysLibPoNETAsyncEnhanced.c.
References PK_ERR_NOT_CONNECTED, PK_OK, PK_PoNETGetModuleLightAsync(), PK_PoNETGetModuleLightRequestAsync(), PK_PoNETGetModuleSettingsAsync(), PK_PoNETGetModuleStatusAsync(), PK_PoNETGetModuleStatusRequestAsync(), PK_PoNETSetModulePWMAsync(), and PK_PoNETSetModuleStatusAsync().
PK_PoNETModuleReinitializeAsync()
int PK_PoNETModuleReinitializeAsync (sPoKeysDevice * device, uint8_t moduleID)
Definition at line 99 of file PoKeysLibPoNETAsyncEnhanced.c.
References CreateRequestAsync(), PK_CMD_POI2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PONET_OP_REINITIALIZE, and SendRequestAsync().