LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibMatrixLED.c File Reference
PoKeysLibMatrixLED.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
Functions
int32_t PK_MatrixLEDConfigurationSet (sPoKeysDevice *device)
int32_t PK_MatrixLEDConfigurationGet (sPoKeysDevice *device)
int32_t PK_MatrixLEDUpdate (sPoKeysDevice *device)
Function Documentation
PK_MatrixLEDConfigurationGet()
int32_t PK_MatrixLEDConfigurationGet (sPoKeysDevice * device)
Read matrix LED configuration from the device.
Populates the sPoKeysDevice::MatrixLED fields for each available display using PK_CMD_MATRIX_LED_CONFIGURATION with subcommand 1.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 40 of file PoKeysLibMatrixLED.c.
References sPoKeysMatrixLED::columns, CreateRequest(), sPoKeysMatrixLED::displayEnabled, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice::MatrixLED, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysMatrixLED::rows, and SendRequest().
PK_MatrixLEDConfigurationSet()
int32_t PK_MatrixLEDConfigurationSet (sPoKeysDevice * device)
Write the matrix LED configuration to the device.
Enabled displays as well as their row and column counts are taken from the sPoKeysDevice::MatrixLED array and encoded into a PK_CMD_MATRIX_LED_CONFIGURATION request.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 24 of file PoKeysLibMatrixLED.c.
References sPoKeysMatrixLED::columns, CreateRequest(), sPoKeysMatrixLED::displayEnabled, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice::MatrixLED, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysMatrixLED::rows, and SendRequest().
PK_MatrixLEDUpdate()
int32_t PK_MatrixLEDUpdate (sPoKeysDevice * device)
Update matrix LED contents on the device.
For every display that has sPoKeysMatrixLED::RefreshFlag set, the pixel buffer from sPoKeysMatrixLED::data is transmitted via PK_CMD_MATRIX_LED_UPDATE.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 61 of file PoKeysLibMatrixLED.c.
References CreateRequest(), sPoKeysMatrixLED::data, i, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice::MatrixLED, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysMatrixLED::RefreshFlag, sPoKeysDevice::request, and SendRequest().