LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/hal-canon/hal_analog.c File Reference
hal_analog.c File Reference
HAL export and function registration for canonical analog input and output.
#include <hal.h>
#include <rtapi.h>
#include <rtapi_string.h>
#include "hal_canon.h"
Functions
int hal_export_adcin (hal_adcin_t *adcin, const char *prefix, int index, int comp_id)
Export HAL pins and parameters for a canonical analog input channel.
int hal_adcin_applyScaling (hal_adcin_t *adcin, float rawvalue)
int hal_export_adcout (hal_adcout_t *adcout, const char *prefix, int index, int comp_id)
Export HAL pins and parameters for a canonical analog output channel.
hal_float_t hal_adcout_getscaledvalue (hal_adcout_t *adcout)
Detailed Description
HAL export and function registration for canonical analog input and output.
This file provides helper functions to export HAL pins and parameters for analog input (adcin) and output (adcout) channels in compliance with the Canonical Device Interface (CDI) specification.
Functions provided:
hal_export_adcin() – exports value pin and parameters for analog inputs
hal_register_adcin_func() – registers a periodic read function
hal_export_adcout() – exports value, enable, and parameters for analog outputs
hal_register_adcout_func() – registers a write function to apply scaled output
Pin naming follows the canonical format: <prefix>.adcin.<index>.<pin> and <prefix>.adcout.<index>.<pin>
See also
https://linuxcnc.org/docs/html/hal/canonical-devices.html#sec:hal-cdi:analog-in
https://linuxcnc.org/docs/html/hal/canonical-devices.html#sec:hal-cdi:analog-out
Definition in file hal_analog.c.
Function Documentation
hal_adcin_applyScaling()
int hal_adcin_applyScaling (hal_adcin_t * adcin, float rawvalue)
Definition at line 99 of file hal_analog.c.
References hal_adcin_t::hw_offset, hal_adcin_t::offset, hal_adcin_t::scale, and hal_adcin_t::value.
hal_adcout_getscaledvalue()
hal_float_t hal_adcout_getscaledvalue (hal_adcout_t * adcout)
Definition at line 219 of file hal_analog.c.
References hal_adcout_t::enable, hal_float_t, hal_adcout_t::high_limit, hal_adcout_t::hw_offset, hal_adcout_t::low_limit, hal_adcout_t::offset, hal_adcout_t::scale, and hal_adcout_t::value.
Referenced by PK_PWMConfigurationSet(), PK_PWMConfigurationSetAsync(), PK_PWMUpdate(), and PK_PWMUpdateAsync().