LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLib1Wire.c File Reference
PoKeysLib1Wire.c File Reference
Implementation of 1-wire bus operations (command 0xDC).
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
Functions
int32_t PK_1WireStatusSet (sPoKeysDevice *device, uint8_t activated)
Enable or disable the 1-wire bus.
int32_t PK_1WireStatusGet (sPoKeysDevice *device, uint8_t *activated)
Query the 1-wire activation status.
int32_t PK_1WireWriteReadStart (sPoKeysDevice *device, uint8_t WriteCount, uint8_t ReadCount, uint8_t *data)
Start a reset/write/read transaction on the 1-wire bus.
int32_t PK_1WireReadStatusGet (sPoKeysDevice *device, uint8_t *readStatus, uint8_t *ReadCount, uint8_t *data)
Retrieve data from the previous 1-wire read operation.
int32_t PK_1WireWriteReadStartEx (sPoKeysDevice *device, uint8_t pinID, uint8_t WriteCount, uint8_t ReadCount, uint8_t *data)
Start a 1-wire transaction on a specific pin.
int32_t PK_1WireBusScanStart (sPoKeysDevice *device, uint8_t pinID)
Begin scanning the 1-wire bus for devices.
int32_t PK_1WireBusScanGetResults (sPoKeysDevice *device, uint8_t *operationStatus, uint8_t *scanResult, uint8_t *deviceROM)
Obtain status and results of a 1-wire bus scan.
int32_t PK_1WireBusScanContinue (sPoKeysDevice *device)
Continue a previously started 1-wire bus scan.
int32_t PK_1WireBusScanStop (sPoKeysDevice *device)
Stop an ongoing 1-wire bus scan.
Detailed Description
Implementation of 1-wire bus operations (command 0xDC).
Functions in this file control the 1-wire communication bus as defined in the PoKeys protocol specification. They cover activation, data transactions and bus scanning.
Definition in file PoKeysLib1Wire.c.
Function Documentation
PK_1WireBusScanContinue()
int32_t PK_1WireBusScanContinue (sPoKeysDevice * device)
Continue a previously started 1-wire bus scan.
Sends command 0xDC/0x22.
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or an error from SendRequest.
Definition at line 236 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireBusScanGetResults()
int32_t PK_1WireBusScanGetResults (sPoKeysDevice * device, uint8_t * operationStatus, uint8_t * scanResult, uint8_t * deviceROM)
Obtain status and results of a 1-wire bus scan.
Command 0xDC/0x21 returns the current scanning state and the discovered device ROM code when available.
Parameters
device Pointer to an opened PoKeys device.
operationStatus Receives operation status byte.
scanResult Receives scan progress flags.
deviceROM Buffer for the 8 byte device ROM.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 211 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_1WireBusScanStart()
int32_t PK_1WireBusScanStart (sPoKeysDevice * device, uint8_t pinID)
Begin scanning the 1-wire bus for devices.
Issues command 0xDC/0x20 with the selected pin ID.
Parameters
device Pointer to an opened PoKeys device.
pinID PoKeys pin used for the scan.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or an error from SendRequest.
Definition at line 190 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireBusScanStop()
int32_t PK_1WireBusScanStop (sPoKeysDevice * device)
Stop an ongoing 1-wire bus scan.
Uses command 0xDC/0x23 to terminate the scan procedure.
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or an error from SendRequest.
Definition at line 254 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireReadStatusGet()
int32_t PK_1WireReadStatusGet (sPoKeysDevice * device, uint8_t * readStatus, uint8_t * ReadCount, uint8_t * data)
Retrieve data from the previous 1-wire read operation.
Sends command 0xDC/0x11 to obtain the read status and any returned bytes.
Parameters
device Pointer to an opened PoKeys device.
readStatus Operation status: 1 when data is available.
ReadCount Receives the number of bytes returned.
data Buffer that receives the read bytes (up to 16).
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL, PK_ERR_TRANSFER on communication failure or PK_ERR_PARAMETER if the returned byte count is invalid.
Definition at line 119 of file PoKeysLib1Wire.c.
References CreateRequest(), i, PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_1WireStatusGet()
int32_t PK_1WireStatusGet (sPoKeysDevice * device, uint8_t * activated)
Query the 1-wire activation status.
Sends command 0xDC/0x11 which returns the current activation state in the response.
Parameters
device Pointer to an opened PoKeys device.
activated Destination for the activation flag (1 when enabled).
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 65 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_1WireStatusSet()
int32_t PK_1WireStatusSet (sPoKeysDevice * device, uint8_t activated)
Enable or disable the 1-wire bus.
Issues command 0xDC with operation code 0x01 to enable or 0x00 to disable the bus as defined in the protocol specification ("1-wire settings and communication").
Parameters
device Pointer to an opened PoKeys device.
activated Non-zero to activate the bus, zero to deactivate.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED when device is NULL or an error returned by SendRequest (for example PK_ERR_TRANSFER).
Definition at line 46 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireWriteReadStart()
int32_t PK_1WireWriteReadStart (sPoKeysDevice * device, uint8_t WriteCount, uint8_t ReadCount, uint8_t * data)
Start a reset/write/read transaction on the 1-wire bus.
Executes command 0xDC/0x10 ("Start Reset, Write and Read process"). Up to 16 bytes may be written and read in a single transaction.
Parameters
device Pointer to an opened PoKeys device.
WriteCount Number of bytes to write (clamped to 16).
ReadCount Number of bytes to read (clamped to 16).
data Buffer containing bytes to write.
Returns
PK_OK when the command is sent successfully, PK_ERR_NOT_CONNECTED if device is NULL or an error from SendRequest.
Definition at line 89 of file PoKeysLib1Wire.c.
References CreateRequest(), i, PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireWriteReadStartEx()
int32_t PK_1WireWriteReadStartEx (sPoKeysDevice * device, uint8_t pinID, uint8_t WriteCount, uint8_t ReadCount, uint8_t * data)
Start a 1-wire transaction on a specific pin.
Same as PK_1WireWriteReadStart() but allows selecting the 1-wire pin. Uses command 0xDC/0x10 with the pin ID in the third parameter byte.
Parameters
device Pointer to an opened PoKeys device.
pinID PoKeys pin used for 1-wire communication.
WriteCount Number of bytes to write (clamped to 16).
ReadCount Number of bytes to read (clamped to 16).
data Buffer of bytes to send.
Returns
PK_OK when the command is sent, PK_ERR_NOT_CONNECTED if device is NULL or an error from SendRequest.
Definition at line 163 of file PoKeysLib1Wire.c.
References CreateRequest(), i, PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().