LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeyslib/PoKeysLibWS2812.c File Reference
PoKeysLibWS2812.c File Reference
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
Functions
int32_t PK_WS2812_Update (sPoKeysDevice *device, uint16_t LEDcount, uint8_t updateFlag)
int32_t PK_WS2812_SendLEDdataEx (sPoKeysDevice *device, uint32_t *LEDdata, uint16_t LEDoffset, uint16_t startLED, uint8_t LEDcount)
int32_t PK_WS2812_SendLEDdata (sPoKeysDevice *device, uint32_t *LEDdata, uint16_t startLED, uint8_t LEDcount)
Function Documentation
PK_WS2812_SendLEDdata()
int32_t PK_WS2812_SendLEDdata (sPoKeysDevice * device, uint32_t * LEDdata, uint16_t startLED, uint8_t LEDcount)
Send LED color values to the WS2812 strip.
The helper automatically splits larger transfers into 18-LED blocks.
Parameters
device Pointer to an initialized device structure.
LEDdata Array of 24-bit color values.
startLED Index of the first LED to update.
LEDcount Number of LEDs to update.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 50 of file PoKeysLibWS2812.c.
PK_WS2812_SendLEDdataEx()
int32_t PK_WS2812_SendLEDdataEx (sPoKeysDevice * device, uint32_t * LEDdata, uint16_t LEDoffset, uint16_t startLED, uint8_t LEDcount)
Definition at line 33 of file PoKeysLibWS2812.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest_NoResponse().
Referenced by PK_WS2812_SendLEDdata().
PK_WS2812_Update()
int32_t PK_WS2812_Update (sPoKeysDevice * device, uint16_t LEDcount, uint8_t updateFlag)
Configure the WS2812 LED driver and optionally refresh the strip.
Parameters
device Pointer to an initialized device structure.
LEDcount Total number of LEDs in the strip.
updateFlag Non-zero to immediately update the LEDs.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 23 of file PoKeysLibWS2812.c.