LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibDeviceData.c File Reference
PoKeysLibDeviceData.c File Reference
Device information and configuration helpers.
#include <stdlib.h>
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "stdio.h"
Data Structures
struct sPoKeys_PinDescriptor
struct sPoKeys_DeviceDescriptor
Macros
#define MAX_PINS_COUNT 100
#define MAX_CAPS_PER_PIN 20
#define PIN_DI PK_AllPinCap_digitalInput, PK_AllPinCap_keyboardMapping, PK_AllPinCap_triggeredInput
#define PIN_DO PK_AllPinCap_digitalOutput
#define PIN_DIO PK_AllPinCap_digitalInput, PK_AllPinCap_digitalOutput, PK_AllPinCap_keyboardMapping, PK_AllPinCap_triggeredInput
#define CAP(...) { __VA_ARGS__, -1 }
Functions
int32_t CompareName (int8_t *device, int8_t *search)
Compare a device name prefix.
int32_t PK_DeviceDataGet (sPoKeysDevice *device)
Read device identification and feature set.
int32_t PK_FillPWMPinNumbers (sPoKeysDevice *device)
Populate PWM pin ID table in the device structure.
int32_t PK_DeviceNameSet (sPoKeysDevice *device)
Write the device name string (command 0x06/0x01).
int32_t PK_NetworkConfigurationSet (sPoKeysDevice *device)
Write Ethernet configuration block (command 0xE0/10).
int32_t PK_DeviceActivation (sPoKeysDevice *device)
Send activation code to the device (command 0x8F/0x01).
int32_t PK_DeviceActivationClear (sPoKeysDevice *device)
Clear activation settings (command 0x8F/0xFF).
int32_t PK_SaveConfiguration (sPoKeysDevice *device)
Save current configuration to device flash (command 0x50).
int32_t PK_ClearConfiguration (sPoKeysDevice *device)
Reset configuration in device flash (command 0x52).
int32_t PK_CheckPinCapabilityByDevice (uint64_t deviceTypeMask, uint32_t pin, ePK_AllPinCap cap)
Determine if a device class supports a pin capability.
int32_t PK_CheckPinCapabilityByTypeID (uint64_t deviceID, uint32_t pin, ePK_AllPinCap cap)
Check capability for a specific device type ID.
int32_t PK_CheckPinCapability (sPoKeysDevice *device, unsigned int pin, ePK_AllPinCap cap)
Wrapper for PK_CheckPinCapabilityByTypeID() using a device handle.
int32_t PK_CheckPinEnabledCapability (sPoKeysDevice *device, uint32_t pin, ePK_AllPinCap cap)
Check if a capability is enabled on a specific pin.
int32_t PK_GetDebugValues (sPoKeysDevice *device, int32_t *buffer)
Read internal debug registers (command 0xBB).
int32_t PK_SetFastUSBEnableStatus (sPoKeysDevice *device, uint32_t newState)
Enable or disable the fast USB interface (command 0x07).
int32_t PK_GetFastUSBEnableStatus (sPoKeysDevice *device, uint32_t *state)
Query fast USB interface status (command 0x07/10).
int32_t PK_ReadDeviceLog (sPoKeysDevice *device, uint16_t *logBuffer, int32_t *logEntries)
Retrieve entries from the device event log (command 0x84).
Variables
const sPoKeys_DeviceDescriptor deviceDesc []
const sPoKeys_PinCapabilities pinCaps []
Detailed Description
Device information and configuration helpers.
Functions in this module implement commands from the protocol chapter "Device data" such as reading identification, activation and pin capability tables.
Definition in file PoKeysLibDeviceData.c.
Macro Definition Documentation
CAP
#define CAP (...) { __VA_ARGS__, -1 }
Definition at line 68 of file PoKeysLibDeviceData.c.
MAX_CAPS_PER_PIN
#define MAX_CAPS_PER_PIN 20
Definition at line 37 of file PoKeysLibDeviceData.c.
MAX_PINS_COUNT
#define MAX_PINS_COUNT 100
Definition at line 36 of file PoKeysLibDeviceData.c.
PIN_DI
#define PIN_DI PK_AllPinCap_digitalInput, PK_AllPinCap_keyboardMapping, PK_AllPinCap_triggeredInput
Definition at line 64 of file PoKeysLibDeviceData.c.
PIN_DIO
#define PIN_DIO PK_AllPinCap_digitalInput, PK_AllPinCap_digitalOutput, PK_AllPinCap_keyboardMapping, PK_AllPinCap_triggeredInput
Definition at line 66 of file PoKeysLibDeviceData.c.
PIN_DO
#define PIN_DO PK_AllPinCap_digitalOutput
Definition at line 65 of file PoKeysLibDeviceData.c.
Function Documentation
CompareName()
int32_t CompareName (int8_t * device, int8_t * search)
Compare a device name prefix.
Utility used when parsing the identification string returned by the device. Checks if device starts with the contents of search.
Parameters
device Pointer to the device name buffer.
search String to compare against.
Returns
0 when the prefix matches otherwise index of first mismatch.
Definition at line 297 of file PoKeysLibDeviceData.c.
References i.
PK_CheckPinCapability()
int32_t PK_CheckPinCapability (sPoKeysDevice * device, unsigned int pin, ePK_AllPinCap cap)
Wrapper for PK_CheckPinCapabilityByTypeID() using a device handle.
Parameters
device PoKeys device structure.
pin Pin index (0 based).
cap Capability identifier.
Returns
1 if supported, 0 otherwise or negative on error.
Definition at line 1443 of file PoKeysLibDeviceData.c.
References sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceType, PK_CheckPinCapabilityByTypeID(), and PK_ERR_NOT_CONNECTED.
Referenced by PoKeysHALComponent::PKIO_export_pins(), and PoKeysHALComponent::PKIO_Update().
PK_CheckPinCapabilityByDevice()
int32_t PK_CheckPinCapabilityByDevice (uint64_t deviceTypeMask, uint32_t pin, ePK_AllPinCap cap)
Determine if a device class supports a pin capability.
Looks through the static capability table to check whether the given pin on any device matching deviceTypeMask implements capability cap.
Parameters
deviceTypeMask Combination of PK_DeviceMask_* bits.
pin Pin index (0 based).
cap Capability identifier.
Returns
1 if supported, otherwise 0.
Definition at line 1264 of file PoKeysLibDeviceData.c.
References sPoKeys_PinCapabilities::additionalCheck, sPoKeys_PinCapabilities::cap, sPoKeys_PinCapabilities::devTypes, pinCaps, sPoKeys_PinCapabilities::pinEnd, sPoKeys_PinCapabilities::pinStart, PK_AllPinCap_digitalCounter, PK_AllPinCap_fastEncoder1I, PK_AllPinCap_fastEncoder2A, PK_AllPinCap_fastEncoder2B, PK_AllPinCap_fastEncoder2I, PK_AllPinCap_fastEncoder3I, PK_DeviceMask_56, and PK_IsCounterAvailableByDevice().
PK_CheckPinCapabilityByTypeID()
int32_t PK_CheckPinCapabilityByTypeID (uint64_t deviceID, uint32_t pin, ePK_AllPinCap cap)
Check capability for a specific device type ID.
Searches the capability tables for the given deviceID and reports if pin implements capability cap.
Parameters
deviceID Device type identifier (e.g. PK_DeviceID_57E).
pin Pin index (0 based).
cap Capability identifier.
Returns
1 if supported, otherwise 0.
Definition at line 1315 of file PoKeysLibDeviceData.c.
References sPoKeys_PinCapabilities::additionalCheck, sPoKeys_PinCapabilities::cap, deviceDesc, sPoKeys_PinCapabilities::devTypes, pinCaps, sPoKeys_PinCapabilities::pinEnd, sPoKeys_PinCapabilities::pinStart, PK_AllPinCap_digitalCounter, PK_AllPinCap_fastEncoder1I, PK_AllPinCap_fastEncoder2A, PK_AllPinCap_fastEncoder2B, PK_AllPinCap_fastEncoder2I, PK_AllPinCap_fastEncoder3I, PK_DeviceID_27E, PK_DeviceID_27U, PK_DeviceID_55v1, PK_DeviceID_55v2, PK_DeviceID_55v3, PK_DeviceID_56E, PK_DeviceID_56U, PK_DeviceID_57E, PK_DeviceID_57E_v0, PK_DeviceID_57U, PK_DeviceID_57U_v0, PK_DeviceID_58EU, PK_DeviceID_OEM1, PK_DeviceID_PoKeys57CNC, PK_DeviceID_PoKeys57CNCdb25, PK_DeviceID_PoKeys57CNCpro4x25, PK_DeviceID_PoPLC58, PK_DeviceMask_27, PK_DeviceMask_55, PK_DeviceMask_56, PK_DeviceMask_56E, PK_DeviceMask_56U, PK_DeviceMask_57, PK_DeviceMask_57E, PK_DeviceMask_57U, PK_DeviceMask_58, PK_DeviceMask_PoPLC58, and PK_IsCounterAvailableByDevice().
PK_CheckPinEnabledCapability()
int32_t PK_CheckPinEnabledCapability (sPoKeysDevice * device, uint32_t pin, ePK_AllPinCap cap)
Check if a capability is enabled on a specific pin.
Currently a stub that always returns 0.
Definition at line 1499 of file PoKeysLibDeviceData.c.
PK_ClearConfiguration()
int32_t PK_ClearConfiguration (sPoKeysDevice * device)
Reset configuration in device flash (command 0x52).
Erases stored settings, reverting the device to defaults on next reboot.
Parameters
device Device to operate on.
Returns
PK_OK on success or PK_ERR_TRANSFER otherwise.
Definition at line 1242 of file PoKeysLibDeviceData.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_DeviceActivation()
int32_t PK_DeviceActivation (sPoKeysDevice * device)
Send activation code to the device (command 0x8F/0x01).
Writes the 8 byte ActivationCode field to unlock optional features. The activated options byte from the response is stored back into the structure.
Parameters
device Target device handle.
Returns
PK_OK on success or PK_ERR_TRANSFER otherwise.
Definition at line 1179 of file PoKeysLibDeviceData.c.
References sPoKeysDevice_Data::ActivatedOptions, sPoKeysDevice_Data::ActivationCode, CreateRequest(), sPoKeysDevice::DeviceData, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DeviceActivationClear()
int32_t PK_DeviceActivationClear (sPoKeysDevice * device)
Clear activation settings (command 0x8F/0xFF).
Resets all optional features on the device.
Parameters
device Device handle.
Returns
PK_OK on success or PK_ERR_TRANSFER on communication error.
Definition at line 1201 of file PoKeysLibDeviceData.c.
References sPoKeysDevice_Data::ActivatedOptions, CreateRequest(), sPoKeysDevice::DeviceData, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_DeviceDataGet()
int32_t PK_DeviceDataGet (sPoKeysDevice * device)
Read device identification and feature set.
Executes command 0x05 which returns device series, type and capability information. The results are decoded into sPoKeysDevice_Info and sPoKeysDevice_Data within device.
Parameters
device Pointer to an initialised PoKeys device structure.
Returns
PK_OK on success or an error code from SendRequest().
Definition at line 319 of file PoKeysLibDeviceData.c.
References sPoKeysDevice_Data::ActivatedOptions, sPoKeysNetworkDeviceInfo::AdditionalNetworkOptions, sPoKeysDevice_Data::BuildDate, CompareName(), sPoKeysDevice::connectionType, CreateRequest(), sPoKeysNetworkDeviceInfo::DefaultGateway, sPoKeysDevice::DeviceData, sPoKeysDevice_Data::deviceIsBootloader, sPoKeysDevice_Data::DeviceLockStatus, sPoKeysDevice_Data::DeviceName, sPoKeysDevice_Data::DeviceType, sPoKeysDevice_Data::DeviceTypeID, sPoKeysDevice_Data::DeviceTypeName, sPoKeysNetworkDeviceInfo::DHCP, sPoKeysDevice_Data::FirmwareVersionMajor, sPoKeysDevice_Data::FirmwareVersionMinor, sPoKeysDevice_Data::FWtype, hal_malloc(), sPoKeysDevice_Data::HWtype, i, sPoKeysDevice_Info::iAdditionalOptions, sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iConnectionSignal, sPoKeysDevice_Info::iCustomDeviceName, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iFailSafeSettings, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice_Info::iInitOutputsStart, sPoKeysDevice_Info::iJoystickAnalogToDigitalMapping, sPoKeysDevice_Info::iJoystickButtonAxisMapping, sPoKeysDevice_Info::iJoystickHATswitch, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice_Info::iKeyRepeatDelay, sPoKeysDevice_Info::iLCD, sPoKeysDevice_Info::iLoadStatus, sPoKeysDevice_Info::iMacros, sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice_Info::iMatrixKeyboardTriggeredMapping, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysNetworkDeviceInfo::IPAddressCurrent, sPoKeysNetworkDeviceInfo::IPAddressSetup, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPoNET, sPoKeysDevice_Info::iPoTLog27support, sPoKeysDevice_Info::iprot1wire, sPoKeysDevice_Info::iprotI2C, sPoKeysDevice_Info::iPulseEngine, sPoKeysDevice_Info::iPulseEnginev2, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice_Info::iSensorList, sPoKeysDevice_Info::iTriggeredKeyMapping, sPoKeysDevice_Info::iUltraFastEncoders, sPoKeysDevice_Info::iWebInterface, sPoKeysDevice::netDeviceData, PK_DeviceID_27E, PK_DeviceID_27U, PK_DeviceID_56E, PK_DeviceID_56U, PK_DeviceID_57E, PK_DeviceID_57E_v0, PK_DeviceID_57U, PK_DeviceID_57U_v0, PK_DeviceID_Bootloader56E, PK_DeviceID_Bootloader56U, PK_DeviceID_OEM1, PK_DeviceID_PoKeys57CNC, PK_DeviceID_PoKeys57CNCdb25, PK_DeviceID_PoKeys57CNCpro4x25, PK_DeviceID_PoKeys57Utest, PK_DeviceID_SerialReader, PK_DeviceID_X15_02_24, PK_DeviceMask_27, PK_DeviceMask_27E, PK_DeviceMask_27U, PK_DeviceMask_55, PK_DeviceMask_55v1, PK_DeviceMask_55v2, PK_DeviceMask_55v3, PK_DeviceMask_56, PK_DeviceMask_56E, PK_DeviceMask_56U, PK_DeviceMask_57, PK_DeviceMask_57CNC, PK_DeviceMask_57CNCdb25, PK_DeviceMask_57CNCpro4x25, PK_DeviceMask_57E, PK_DeviceMask_57U, PK_DeviceMask_57Utest, PK_DeviceMask_58, PK_DeviceMask_Bootloader, PK_DeviceMask_Bootloader55, PK_DeviceMask_Bootloader56, PK_DeviceMask_Bootloader56E, PK_DeviceMask_Bootloader56U, PK_DeviceMask_Bootloader58, PK_DeviceMask_PoKeys16RF, PK_DeviceMask_PoPLC58, PK_DeviceType_NetworkDevice, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice_Data::ProductID, sPoKeysDevice_Info::PWMinternalFrequency, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysDevice_Data::SecondaryFirmwareVersionMajor, sPoKeysDevice_Data::SecondaryFirmwareVersionMinor, SendRequest(), sPoKeysDevice_Data::SerialNumber, sPoKeysNetworkDeviceInfo::Subnetmask, sPoKeysNetworkDeviceInfo::TCPtimeout, and sPoKeysDevice_Data::UserID.
Referenced by InitializeNewDevice(), and PK_InitializeNewDeviceAsync().
PK_DeviceNameSet()
int32_t PK_DeviceNameSet (sPoKeysDevice * device)
Write the device name string (command 0x06/0x01).
The first ten bytes of sPoKeysDevice_Data.DeviceName are sent to the device. They become visible in subsequent identification reads.
Parameters
device Target device handle.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1116 of file PoKeysLibDeviceData.c.
References CreateRequest(), sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceName, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_FillPWMPinNumbers()
int32_t PK_FillPWMPinNumbers (sPoKeysDevice * device)
Populate PWM pin ID table in the device structure.
Depending on the connected device type the PWM outputs are mapped to different PoKeys pins. This helper fills sPoKeysPWM.PWMpinIDs using hard coded mappings.
Parameters
device Target device handle with populated info block.
Returns
PK_OK on success or PK_ERR_NOT_SUPPORTED when PWM is not available.
Definition at line 1090 of file PoKeysLibDeviceData.c.
References sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceType, sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_DeviceID_PoKeys57CNCdb25, PK_ERR_NOT_SUPPORTED, PK_OK, sPoKeysDevice::PWM, and sPoKeysPWM::PWMpinIDs.
Referenced by InitializeNewDevice(), PK_InitializeNewDeviceAsync(), and PK_PWMGetPinAssignmentsAsync().
PK_GetDebugValues()
int32_t PK_GetDebugValues (sPoKeysDevice * device, int32_t * buffer)
Read internal debug registers (command 0xBB).
Four consecutive requests are issued to retrieve 52 debug integers which are stored into buffer.
Parameters
device Device handle.
buffer Destination array of at least 52 int32_t.
Returns
PK_OK on success or PK_ERR_TRANSFER when communication fails.
Definition at line 1514 of file PoKeysLibDeviceData.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_GetFastUSBEnableStatus()
int32_t PK_GetFastUSBEnableStatus (sPoKeysDevice * device, uint32_t * state)
Query fast USB interface status (command 0x07/10).
Parameters
device Device handle.
state Receives 1 if enabled.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1562 of file PoKeysLibDeviceData.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_NetworkConfigurationSet()
int32_t PK_NetworkConfigurationSet (sPoKeysDevice * device)
Write Ethernet configuration block (command 0xE0/10).
The network parameters from ::sPoKeysNetworkDevice are encoded and transmitted to the device.
Parameters
device Pointer to the PoKeys device with network data filled.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1143 of file PoKeysLibDeviceData.c.
References sPoKeysNetworkDeviceInfo::AdditionalNetworkOptions, CreateRequest(), sPoKeysNetworkDeviceInfo::DefaultGateway, sPoKeysNetworkDeviceInfo::DHCP, sPoKeysNetworkDeviceInfo::IPAddressCurrent, sPoKeysNetworkDeviceInfo::IPAddressSetup, sPoKeysDevice::netDeviceData, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), sPoKeysNetworkDeviceInfo::Subnetmask, and sPoKeysNetworkDeviceInfo::TCPtimeout.
PK_ReadDeviceLog()
int32_t PK_ReadDeviceLog (sPoKeysDevice * device, uint16_t * logBuffer, int32_t * logEntries)
Retrieve entries from the device event log (command 0x84).
Parameters
device Device handle.
logBuffer Buffer for up to 27 log words.
logEntries Receives number of valid entries returned.
Returns
PK_OK on success or PK_ERR_TRANSFER otherwise.
Definition at line 1581 of file PoKeysLibDeviceData.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_SaveConfiguration()
int32_t PK_SaveConfiguration (sPoKeysDevice * device)
Save current configuration to device flash (command 0x50).
Writes the active settings from RAM to non-volatile memory so that they persist across resets.
Parameters
device PoKeys device handle.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1223 of file PoKeysLibDeviceData.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
Referenced by PEv2_AdditionalParametersSet(), PoKeysHALComponent::PEv2_AxisConfigurationSet(), and PEv2_PulseEngineSetup().
PK_SetFastUSBEnableStatus()
int32_t PK_SetFastUSBEnableStatus (sPoKeysDevice * device, uint32_t newState)
Enable or disable the fast USB interface (command 0x07).
Parameters
device Device handle.
newState 1 to enable, 0 to disable.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1545 of file PoKeysLibDeviceData.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
Variable Documentation
deviceDesc
const sPoKeys_DeviceDescriptor deviceDesc[]
Definition at line 70 of file PoKeysLibDeviceData.c.
pinCaps
const sPoKeys_PinCapabilities pinCaps[]
Definition at line 253 of file PoKeysLibDeviceData.c.