LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/pokeyslib/PoKeysLibSPI.c File Reference
PoKeysLibSPI.c File Reference
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
Functions
int32_t PK_SPIConfigure (sPoKeysDevice *device, uint8_t prescaler, uint8_t frameFormat)
int32_t PK_SPIWrite (sPoKeysDevice *device, uint8_t *buffer, uint8_t iDataLength, uint8_t pinCS)
int32_t PK_SPIRead (sPoKeysDevice *device, uint8_t *buffer, uint8_t iDataLength)
Function Documentation
PK_SPIConfigure()
int32_t PK_SPIConfigure (sPoKeysDevice * device, uint8_t prescaler, uint8_t frameFormat)
Definition at line 24 of file PoKeysLibSPI.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_SPIRead()
int32_t PK_SPIRead (sPoKeysDevice * device, uint8_t * buffer, uint8_t iDataLength)
Definition at line 51 of file PoKeysLibSPI.c.
References CreateRequest(), i, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_SPIWrite()
int32_t PK_SPIWrite (sPoKeysDevice * device, uint8_t * buffer, uint8_t iDataLength, uint8_t pinCS)
Definition at line 34 of file PoKeysLibSPI.c.
References CreateRequest(), i, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().