LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibUART.c File Reference
PoKeysLibUART.c File Reference
UART communication helpers (command 0xDE).
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
Functions
int32_t PK_UARTConfigure (sPoKeysDevice *device, uint32_t baudrate, uint8_t format, uint8_t interfaceID)
Configure a UART interface (command 0xDE/0x10).
int32_t PK_UARTWrite (sPoKeysDevice *device, uint8_t interfaceID, uint8_t *dataPtr, uint32_t dataWriteLen)
Write data to the UART interface (command 0xDE/0x20).
int32_t PK_UARTRead (sPoKeysDevice *device, uint8_t interfaceID, uint8_t *dataPtr, uint8_t *dataReadLen)
Read data from a UART interface (command 0xDE/0x30).
Detailed Description
UART communication helpers (command 0xDE).
Functions configure and exchange data via the UART interfaces of a PoKeys device.
Definition in file PoKeysLibUART.c.
Function Documentation
PK_UARTConfigure()
int32_t PK_UARTConfigure (sPoKeysDevice * device, uint32_t baudrate, uint8_t format, uint8_t interfaceID)
Configure a UART interface (command 0xDE/0x10).
Sets baud rate and frame format for the selected UART interface on the device.
Parameters
device Opened PoKeys device.
baudrate Desired baud rate.
format Frame format bits.
interfaceID UART interface ID.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 43 of file PoKeysLibUART.c.
References CreateRequest(), PK_CMD_UART_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_UARTRead()
int32_t PK_UARTRead (sPoKeysDevice * device, uint8_t interfaceID, uint8_t * dataPtr, uint8_t * dataReadLen)
Read data from a UART interface (command 0xDE/0x30).
Requests a block of up to 55 bytes from the specified UART channel. The received byte count is returned via dataReadLen.
Parameters
device Opened PoKeys device.
interfaceID UART interface ID.
dataPtr Destination buffer for received bytes.
dataReadLen Pointer where the byte count is stored.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 117 of file PoKeysLibUART.c.
References CreateRequest(), PK_CMD_UART_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_UARTWrite()
int32_t PK_UARTWrite (sPoKeysDevice * device, uint8_t interfaceID, uint8_t * dataPtr, uint32_t dataWriteLen)
Write data to the UART interface (command 0xDE/0x20).
Splits the data into 55 byte chunks and sends them to the specified UART interface.
Parameters
device Opened PoKeys device.
interfaceID Target UART interface.
dataPtr Pointer to buffer with bytes to send.
dataWriteLen Number of bytes to transmit.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 66 of file PoKeysLibUART.c.
References CreateRequest(), PK_CMD_UART_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().