LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibMatrixKB.c File Reference
PoKeysLibMatrixKB.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
Functions
int32_t PK_MatrixKBConfigurationGet (sPoKeysDevice *device)
int32_t PK_MatrixKBConfigurationSet (sPoKeysDevice *device)
int32_t PK_MatrixKBStatusGet (sPoKeysDevice *device)
Function Documentation
PK_MatrixKBConfigurationGet()
int32_t PK_MatrixKBConfigurationGet (sPoKeysDevice * device)
Read the matrix keyboard configuration and key mapping.
Fields in sMatrixKeyboard within the provided device structure are populated by issuing subcommands of PK_CMD_MATRIX_KEYBOARD_CFG.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 24 of file PoKeysLibMatrixKB.c.
References CreateRequest(), sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice_Info::iMatrixKeyboardTriggeredMapping, sPoKeysDevice::info, sMatrixKeyboard::keyMappingKeyCode, sMatrixKeyboard::keyMappingKeyCodeUp, sMatrixKeyboard::keyMappingKeyModifier, sMatrixKeyboard::keyMappingKeyModifierUp, sMatrixKeyboard::keyMappingTriggeredKey, sMatrixKeyboard::macroMappingOptions, sPoKeysDevice::matrixKB, sMatrixKeyboard::matrixKBcolumnsPins, sMatrixKeyboard::matrixKBconfiguration, sMatrixKeyboard::matrixKBheight, sMatrixKeyboard::matrixKBrowsPins, sMatrixKeyboard::matrixKBScanningDecimation, sMatrixKeyboard::matrixKBwidth, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by Config_MatrixKB(), and Update_MatrixKB().
PK_MatrixKBConfigurationSet()
int32_t PK_MatrixKBConfigurationSet (sPoKeysDevice * device)
Write the current matrix keyboard configuration and key mapping.
Values are taken from the sMatrixKeyboard fields of device and sent using subcommands of PK_CMD_MATRIX_KEYBOARD_CFG.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 97 of file PoKeysLibMatrixKB.c.
References CreateRequest(), sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice_Info::iMatrixKeyboardTriggeredMapping, sPoKeysDevice::info, sMatrixKeyboard::keyMappingKeyCode, sMatrixKeyboard::keyMappingKeyCodeUp, sMatrixKeyboard::keyMappingKeyModifier, sMatrixKeyboard::keyMappingKeyModifierUp, sMatrixKeyboard::keyMappingTriggeredKey, sMatrixKeyboard::macroMappingOptions, sPoKeysDevice::matrixKB, sMatrixKeyboard::matrixKBcolumnsPins, sMatrixKeyboard::matrixKBconfiguration, sMatrixKeyboard::matrixKBheight, sMatrixKeyboard::matrixKBrowsPins, sMatrixKeyboard::matrixKBScanningDecimation, sMatrixKeyboard::matrixKBwidth, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_MatrixKBStatusGet()
int32_t PK_MatrixKBStatusGet (sPoKeysDevice * device)
Retrieve the matrix keyboard key state bitmap.
Updates sMatrixKeyboard::matrixKBvalues with the currently pressed keys using subcommand 20 of PK_CMD_MATRIX_KEYBOARD_CFG.
Parameters
device Pointer to an initialized device structure.
Returns
PK_OK on success or a negative ::PK_ERR code on failure.
Definition at line 202 of file PoKeysLibMatrixKB.c.
References CreateRequest(), sPoKeysDevice_Info::iMatrixKeyboard, sPoKeysDevice::info, sPoKeysDevice::matrixKB, sMatrixKeyboard::matrixKBvalues, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
Referenced by Update_MatrixKB().