LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/pokeyslib/PoKeysLibUART.c File Reference
PoKeysLibUART.c File Reference
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
Functions
int32_t PK_UARTConfigure (sPoKeysDevice *device, uint32_t baudrate, uint8_t format, uint8_t interfaceID)
int32_t PK_UARTWrite (sPoKeysDevice *device, uint8_t interfaceID, uint8_t *dataPtr, uint32_t dataWriteLen)
int32_t PK_UARTRead (sPoKeysDevice *device, uint8_t interfaceID, uint8_t *dataPtr, uint8_t *dataReadLen)
Function Documentation
PK_UARTConfigure()
int32_t PK_UARTConfigure (sPoKeysDevice * device, uint32_t baudrate, uint8_t format, uint8_t interfaceID)
Configure a UART interface.
Issues command PK_CMD_UART_COMMUNICATION with subcommand 0x10. Parameter interfaceID selects the UART port while format contains the serial frame format bits. The desired baud rate value is placed in the request payload.
Parameters
device Target device handle.
baudrate Serial baud rate in bits per second.
format Frame format and options.
interfaceID UART interface index.
Returns
Result code from SendRequest().
Definition at line 23 of file PoKeysLibUART.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_UARTRead()
int32_t PK_UARTRead (sPoKeysDevice * device, uint8_t interfaceID, uint8_t * dataPtr, uint8_t * dataReadLen)
Receive bytes from the selected UART.
Using subcommand 0x30 the device returns the number of available bytes followed by the data itself.
Parameters
device Target device handle.
interfaceID UART interface index.
dataPtr Destination buffer.
dataReadLen Storage for the returned byte count.
Returns
Result code from SendRequest().
Definition at line 73 of file PoKeysLibUART.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_UARTWrite()
int32_t PK_UARTWrite (sPoKeysDevice * device, uint8_t interfaceID, uint8_t * dataPtr, uint32_t dataWriteLen)
Send bytes via the selected UART.
Subcommand 0x20 transmits up to 55 bytes per request and returns the number of bytes written in the response. The helper loops until the full buffer has been sent.
Parameters
device Target device handle.
interfaceID UART interface index.
dataPtr Pointer to the data to transmit.
dataWriteLen Number of bytes to send.
Returns
Result code from SendRequest().
Definition at line 34 of file PoKeysLibUART.c.
References CreateRequest(), PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().