LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibEncoders.c File Reference
PoKeysLibEncoders.c File Reference
Functions for configuring and reading encoder channels.
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
Functions
int32_t PK_EncoderConfigurationGet (sPoKeysDevice *device)
Retrieve encoder configuration from the device.
int32_t PK_EncoderConfigurationSet (sPoKeysDevice *device)
Send encoder configuration to the PoKeys device.
int32_t PK_EncoderValuesGet (sPoKeysDevice *device)
Read current encoder values from the PoKeys device.
int32_t PK_EncoderValuesSet (sPoKeysDevice *device)
Write encoder values to the PoKeys device.
uint32_t PK_SL_EncoderValueGet (sPoKeysDevice *device, uint8_t index)
Detailed Description
Functions for configuring and reading encoder channels.
Definition in file PoKeysLibEncoders.c.
Function Documentation
PK_EncoderConfigurationGet()
int32_t PK_EncoderConfigurationGet (sPoKeysDevice * device)
Retrieve encoder configuration from the device.
This function downloads all encoder related settings such as basic encoder options, channel mappings and key mapping configuration. Fast and ultra fast encoder options are also retrieved when supported. Obtained values are stored into the provided sPoKeysDevice structure.
Parameters
device Pointer to an initialised PoKeys device structure.
Returns
PK_OK on success or a negative error code on failure.
Definition at line 41 of file PoKeysLibEncoders.c.
References sPoKeysEncoder::channelApin, sPoKeysEncoder::channelBpin, CreateRequest(), sPoKeysEncoder::dirAkeyCode, sPoKeysEncoder::dirAkeyModifier, sPoKeysEncoder::dirBkeyCode, sPoKeysEncoder::dirBkeyModifier, sPoKeysEncoder::encoderOptions, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iUltraFastEncoders, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
Referenced by PKEncoder_Setup().
PK_EncoderConfigurationSet()
int32_t PK_EncoderConfigurationSet (sPoKeysDevice * device)
Send encoder configuration to the PoKeys device.
All encoder related parameters stored inside the supplied sPoKeysDevice structure are transmitted to the device. This includes basic encoder options, channel assignments, optional key mappings and fast or ultra fast encoder settings.
Parameters
device Pointer to a configured PoKeys device structure.
Returns
PK_OK on success or a negative error code on failure.
Definition at line 134 of file PoKeysLibEncoders.c.
References sPoKeysEncoder::channelApin, sPoKeysEncoder::channelBpin, CreateRequest(), sPoKeysEncoder::dirAkeyCode, sPoKeysEncoder::dirAkeyModifier, sPoKeysEncoder::dirBkeyCode, sPoKeysEncoder::dirBkeyModifier, sPoKeysEncoder::encoderOptions, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iUltraFastEncoders, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
PK_EncoderValuesGet()
int32_t PK_EncoderValuesGet (sPoKeysDevice * device)
Read current encoder values from the PoKeys device.
Depending on the available encoder count, this function issues one or more read commands to obtain the encoder counters. The received values are stored in the respective encoderValue pointers within the sPoKeysDevice structure. When ultra fast encoders are present, test mode values are fetched as well.
Parameters
device Pointer to the PoKeys device structure.
Returns
PK_OK on success or a negative error code on failure.
Definition at line 211 of file PoKeysLibEncoders.c.
References CreateRequest(), sPoKeysPEv2::EncoderIndexCount, sPoKeysDevice::Encoders, sPoKeysPEv2::EncoderTicksPerRotation, sPoKeysEncoder::encoderValue, sPoKeysPEv2::EncoderVelocity, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice::info, sPoKeysDevice_Info::iUltraFastEncoders, sPoKeysDevice::PEv2, PEV2_CMD_GET_ENCODER_TEST_RESULTS, PK_CMD_PULSE_ENGINE_V2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_EncoderValuesSet()
int32_t PK_EncoderValuesSet (sPoKeysDevice * device)
Write encoder values to the PoKeys device.
The encoderValue fields of the sPoKeysDevice structure are packaged and transmitted to the device, allowing encoder counters to be preset. Only encoders supported by the connected hardware are updated.
Parameters
device Pointer to the PoKeys device structure.
Returns
PK_OK on success or a negative error code on failure.
Definition at line 295 of file PoKeysLibEncoders.c.
References CreateRequest(), sPoKeysDevice::Encoders, sPoKeysEncoder::encoderValue, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_SL_EncoderValueGet()
uint32_t PK_SL_EncoderValueGet (sPoKeysDevice * device, uint8_t index)
Definition at line 334 of file PoKeysLibEncoders.c.
References sPoKeysDevice::Encoders, and sPoKeysEncoder::encoderValue.