LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/hal-canon/hal_canon.h File Reference
hal_canon.h File Reference
Canonical Device Interface definitions and export helpers for LinuxCNC HAL.
#include <hal.h>
#include <rtapi.h>
#include <rtapi_string.h>
Data Structures
struct hal_digin_t
struct hal_digout_t
Register canonical digin read function.
struct hal_adcin_t
Canonical analog input (adcin) structure for HAL.
struct hal_adcout_t
Canonical analog output (adcout) structure for HAL.
struct hal_encoder_t
Canonical encoder interface structure for HAL.
Macros
#define ULAPI
Functions
int hal_export_digin (hal_digin_t *digin, const char *prefix, int index, int comp_id)
Export canonical digin pins & parameter.
int hal_export_digout (hal_digout_t *digout, const char *prefix, int index, int comp_id)
Export canonical digout pins and parameters.
int hal_export_adcin (hal_adcin_t *adcin, const char *prefix, int index, int comp_id)
Export canonical adcin pins and parameters.
int hal_adcin_applyScaling (hal_adcin_t *adcin, float rawvalue)
int hal_export_adcout (hal_adcout_t *adcout, const char *prefix, int index, int comp_id)
Export canonical adcout pins and parameters.
hal_float_t hal_adcout_getscaledvalue (hal_adcout_t *adcout)
int hal_export_encoder (hal_encoder_t *enc, const char *prefix, int index, int comp_id)
Export canonical encoder HAL pins and parameters.
Detailed Description
Canonical Device Interface definitions and export helpers for LinuxCNC HAL.
This header provides data structures and function declarations for implementing canonical HAL interfaces for digital I/O, analog I/O, and encoders as defined by the LinuxCNC Canonical Device Interface (CDI) specification.
It includes:
Struct definitions for each canonical device type (digin, digout, adcin, adcout, encoder)
Export functions to define HAL pins and parameters
Registration functions to link periodic HAL functions (read/write)
Each canonical device follows a consistent naming convention: <prefix>.<interface>.<index>.<pin|parameter|function>
This header is intended to be included in HAL component C files that implement device-specific logic and want to expose a CDI-compliant interface.
See also
https://linuxcnc.org/docs/html/hal/canonical-devices.html
Author
zarfld
Definition in file hal_canon.h.
Macro Definition Documentation
ULAPI
#define ULAPI
Definition at line 38 of file hal_canon.h.
Function Documentation
hal_adcin_applyScaling()
int hal_adcin_applyScaling (hal_adcin_t * adcin, float rawvalue)
Definition at line 99 of file hal_analog.c.
References hal_adcin_t::hw_offset, hal_adcin_t::offset, hal_adcin_t::scale, and hal_adcin_t::value.
hal_adcout_getscaledvalue()
hal_float_t hal_adcout_getscaledvalue (hal_adcout_t * adcout)
Definition at line 219 of file hal_analog.c.
References hal_adcout_t::enable, hal_float_t, hal_adcout_t::high_limit, hal_adcout_t::hw_offset, hal_adcout_t::low_limit, hal_adcout_t::offset, hal_adcout_t::scale, and hal_adcout_t::value.
Referenced by PK_PWMConfigurationSet(), PK_PWMConfigurationSetAsync(), PK_PWMUpdate(), and PK_PWMUpdateAsync().