LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibSecurity.c File Reference
PoKeysLibSecurity.c File Reference
Security and authorisation helpers (commands 0xE1-0xE3).
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Functions
int32_t PK_SecurityStatusGet (sPoKeysDevice *device, uint8_t *level, uint8_t *seed)
Retrieve the device security level (command 0xE1).
int32_t PK_UserAuthorise (sPoKeysDevice *device, uint8_t level, const uint8_t *hash, uint8_t *status)
Authorise user with a password hash (command 0xE2).
int32_t PK_UserPasswordSet (sPoKeysDevice *device, uint8_t defaultLevel, const uint8_t *password)
Set a new user password (command 0xE3).
Detailed Description
Security and authorisation helpers (commands 0xE1-0xE3).
Provides functions for querying security level, authorising users and changing passwords.
Definition in file PoKeysLibSecurity.c.
Function Documentation
PK_SecurityStatusGet()
int32_t PK_SecurityStatusGet (sPoKeysDevice * device, uint8_t * level, uint8_t * seed)
Retrieve the device security level (command 0xE1).
Reads current authorisation level and 32-byte seed used for password hashing.
Parameters
device Pointer to an opened PoKeys device.
level Optional pointer to store the security level.
seed Optional 32-byte buffer for the random seed.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 24 of file PoKeysLibSecurity.c.
References CreateRequest(), PK_CMD_SECURITY_STATUS_GET, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_UserAuthorise()
int32_t PK_UserAuthorise (sPoKeysDevice * device, uint8_t level, const uint8_t * hash, uint8_t * status)
Authorise user with a password hash (command 0xE2).
Sends the SHA1 hash of the password at the requested access level and returns the authorisation result.
Parameters
device Pointer to an opened PoKeys device.
level Requested security level.
hash Pointer to a 20-byte password hash.
status Optional pointer to store the result.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 48 of file PoKeysLibSecurity.c.
References CreateRequest(), PK_CMD_USER_AUTHORISE, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_UserPasswordSet()
int32_t PK_UserPasswordSet (sPoKeysDevice * device, uint8_t defaultLevel, const uint8_t * password)
Set a new user password (command 0xE3).
Stores a SHA1 hash of the password for the selected default security level.
Parameters
device Pointer to an opened PoKeys device.
defaultLevel Level assigned to the password.
password Pointer to 32-byte password hash.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 71 of file PoKeysLibSecurity.c.
References CreateRequest(), PK_CMD_USER_PASSWORD_SET, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().