LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibIOAsync.c File Reference
PoKeysLibIOAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include "hal_canon.h"
Functions
int export_IO_pins (const char *prefix, long comp_id, sPoKeysDevice *device)
int PK_ParsePinFunctionsResponse (sPoKeysDevice *dev, const uint8_t *resp)
Parser for pin function configuration response (CMD 0xC0, param1=0).
int PK_StartPinFunctionsRequestAsync (sPoKeysDevice *dev)
Starts async pin function configuration request (CMD 0xC0, param1=0).
int PK_PinCounterConfigurationParse (sPoKeysDevice *dev, const uint8_t *resp)
Parser for digital counter configuration response (CMD 0xC0, param1=1).
int PK_PinKeyMappingTypeParse (sPoKeysDevice *dev, const uint8_t *resp)
Parser for pin key mapping type response (CMD 0xC1).
int PK_PinKeyMappingCodesParse (sPoKeysDevice *dev, const uint8_t *resp)
Parser for pin key mapping codes response (CMD 0xC2).
int PK_PinKeyMappingModifiersParse (sPoKeysDevice *dev, const uint8_t *resp)
Parser for pin key mapping modifiers response (CMD 0xC3).
int PK_PinTriggeredDownKeyCodeParse (sPoKeysDevice *dev, const uint8_t *resp)
Parser for triggered key down macro ID mapping (CMD 0xD7, param1=11).
int PK_PinTriggeredDownKeyModifierParse (sPoKeysDevice *dev, const uint8_t *resp)
Parser for triggered key down modifiers (CMD 0xD7, param1=12).
int PK_PinTriggeredUpKeyModifierParse (sPoKeysDevice *dev, const uint8_t *resp)
Parser for triggered key up modifiers (CMD 0xD7, param1=14).
int PK_PinTriggeredUpKeyCodeParse (sPoKeysDevice *dev, const uint8_t *resp)
Parser for triggered key up macro IDs (CMD 0xD7, param1=13).
int32_t PK_PinConfigurationGetAsync (sPoKeysDevice *device)
int32_t PK_PinConfigurationSetAsync (sPoKeysDevice *device)
Sets all pin configuration fields asynchronously.
int32_t PK_DigitalIOSetAsync (sPoKeysDevice *device)
Asynchronously sets the digital IO values.
int PK_DigitalIOGetParse (sPoKeysDevice *device, const uint8_t *response)
Parser for digital IO input values (CMD 0xCC, param1=0)
int PK_DigitalIOGetAsync (sPoKeysDevice *device)
Asynchronously requests digital IO input values.
int PK_DigitalIOSetGetAsync (sPoKeysDevice *device)
Combined Set and Get digital IO in one async call.
int PK_AnalogIOParse (sPoKeysDevice *device, const uint8_t *response)
Parser for analog inputs (CMD 0x3A, param1=1).
int PK_AnalogIOGetAsync (sPoKeysDevice *device)
Starts async request for analog inputs (CMD 0x3A, param1=1).
int PK_AnalogRCFilterParse (sPoKeysDevice *device, const uint8_t *response)
Parser for RC analog filter configuration (CMD 0x38).
int PK_AnalogRCFilterGetAsync (sPoKeysDevice *device)
Starts async request for RC analog filter value (CMD 0x38).
int PK_AnalogRCFilterSetAsync (sPoKeysDevice *device)
Starts async command to set RC analog filter (CMD 0x39).
int PK_DigitalCounterParse (sPoKeysDevice *device, const uint8_t *response)
Parser for digital counter values (CMD 0xD8).
int PK_DigitalCounterGetAsync (sPoKeysDevice *device)
Starts async request to get digital counter values (CMD 0xD8).
int PK_DigitalCounterClearAsync (sPoKeysDevice *device)
Starts async request to clear digital counters (CMD 0x1D).
int PK_PWMConfigurationSetAsync (sPoKeysDevice *device)
Starts async command to configure PWM duty cycle and period (CMD 0xCB).
int PK_PWMConfigurationParse (sPoKeysDevice *device, const uint8_t *response)
Parser for reading PWM configuration (CMD 0xCB, param1=0)
int PK_PWMConfigurationGetAsync (sPoKeysDevice *device)
Starts async request to get PWM configuration (CMD 0xCB, param1=0)
int PK_PWMUpdateAsync (sPoKeysDevice *device)
Starts async command to update PWM values only (CMD 0xCB, param1=1, param2=1).
int PK_PWMConfigurationSetDirectlyAsync (sPoKeysDevice *device, uint32_t PWMperiod, uint8_t *enabledChannels)
Set PWM configuration directly with specified parameters (async)
int PK_PWMUpdateDirectlyAsync (sPoKeysDevice *device, uint32_t *dutyCycles)
Update PWM duty cycles directly (async)
int PK_PWMSetSingleChannelAsync (sPoKeysDevice *device, uint8_t channel, uint32_t dutyCycle)
Set single PWM channel duty cycle (async)
int PK_PWMPinAssignmentsParse (sPoKeysDevice *device, const uint8_t *response)
Parser for PWM pin assignments (CMD 0xCB, param1=2)
int PK_PWMGetPinAssignmentsAsync (sPoKeysDevice *device)
Get PWM pin assignments (async)
int PK_DigitalOutputSetSingleAsync (sPoKeysDevice *device, uint8_t pinIndex, uint8_t value)
Set a single digital output pin (async)
int PK_DigitalInputGetSingleAsync (sPoKeysDevice *device, uint8_t pinIndex)
Get a single digital input pin state (async)
int PK_DigitalOutputToggleAsync (sPoKeysDevice *device, uint8_t pinIndex)
Toggle a digital output pin (async)
int parse_PoExtBusGet (sPoKeysDevice *device, const uint8_t *resp)
int PK_PoExtBusSetAsync (sPoKeysDevice *device)
Starts async request to set PoExtBus data (CMD 0xDA).
int PK_PoExtBusGetAsync (sPoKeysDevice *device)
Starts async request to get PoExtBus data (CMD 0xDA, param1=2).
Function Documentation
export_IO_pins()
int export_IO_pins (const char * prefix, long comp_id, sPoKeysDevice * device)
Definition at line 6 of file PoKeysLibIOAsync.c.
parse_PoExtBusGet()
int parse_PoExtBusGet (sPoKeysDevice * device, const uint8_t * resp)
Definition at line 916 of file PoKeysLibIOAsync.c.
References i, sPoKeysDevice::info, sPoKeysDevice_Info::iPoExtBus, PK_OK, and sPoKeysDevice::PoExtBusData.
Referenced by PK_PoExtBusGetAsync(), and PK_PoExtBusSetAsync().
PK_AnalogIOGetAsync()
int PK_AnalogIOGetAsync (sPoKeysDevice * device)
Starts async request for analog inputs (CMD 0x3A, param1=1).
Definition at line 516 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice::info, PK_AnalogIOParse(), PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.
Referenced by PK_IOUpdateCycleAsync().
PK_AnalogIOParse()
int PK_AnalogIOParse (sPoKeysDevice * device, const uint8_t * response)
Parser for analog inputs (CMD 0x3A, param1=1).
Definition at line 501 of file PoKeysLibIOAsync.c.
References sPoKeysDevice::AnalogInput, sPoKeysPinData::AnalogValue, sPoKeysAnalogData::Canon, i, sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, hal_adcin_t::offset, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_ERR_NOT_SUPPORTED, PK_OK, sPoKeysAnalogData::rawvalue, sPoKeysAnalogData::ReferenceVoltage, sPoKeysDevice::response, hal_adcin_t::scale, and hal_adcin_t::value.
Referenced by PK_AnalogIOGetAsync().
PK_AnalogRCFilterGetAsync()
int PK_AnalogRCFilterGetAsync (sPoKeysDevice * device)
Starts async request for RC analog filter value (CMD 0x38).
Definition at line 543 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice::info, PK_AnalogRCFilterParse(), PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.
PK_AnalogRCFilterParse()
int PK_AnalogRCFilterParse (sPoKeysDevice * device, const uint8_t * response)
Parser for RC analog filter configuration (CMD 0x38).
Definition at line 527 of file PoKeysLibIOAsync.c.
References sPoKeysOtherPeripherals::AnalogRCFilter, sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice::info, sPoKeysDevice::otherPeripherals, PK_ERR_GENERIC, PK_ERR_NOT_SUPPORTED, and PK_OK.
Referenced by PK_AnalogRCFilterGetAsync().
PK_AnalogRCFilterSetAsync()
int PK_AnalogRCFilterSetAsync (sPoKeysDevice * device)
Starts async command to set RC analog filter (CMD 0x39).
Definition at line 553 of file PoKeysLibIOAsync.c.
References sPoKeysOtherPeripherals::AnalogRCFilter, CreateRequestAsync(), sPoKeysDevice_Info::iAnalogFiltering, sPoKeysDevice::info, sPoKeysDevice::otherPeripherals, PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.
PK_DigitalCounterClearAsync()
int PK_DigitalCounterClearAsync (sPoKeysDevice * device)
Starts async request to clear digital counters (CMD 0x1D).
Definition at line 607 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), and PK_ERR_NOT_CONNECTED.
PK_DigitalCounterGetAsync()
int PK_DigitalCounterGetAsync (sPoKeysDevice * device)
Starts async request to get digital counter values (CMD 0xD8).
Definition at line 588 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, PK_DigitalCounterParse(), PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_IsCounterAvailable(), and PK_OK.
Referenced by PK_IOUpdateCycleAsync().
PK_DigitalCounterParse()
int PK_DigitalCounterParse (sPoKeysDevice * device, const uint8_t * response)
Parser for digital counter values (CMD 0xD8).
Definition at line 572 of file PoKeysLibIOAsync.c.
References sPoKeysPinData::DigitalCounterValue, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice::info, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_ERR_NOT_SUPPORTED, PK_IsCounterAvailable(), PK_OK, and sPoKeysDevice::request.
Referenced by PK_DigitalCounterGetAsync().
PK_DigitalInputGetSingleAsync()
int PK_DigitalInputGetSingleAsync (sPoKeysDevice * device, uint8_t pinIndex)
Get a single digital input pin state (async)
Reads all digital inputs but provides callback for single pin monitoring.
Parameters
device Target device handle
pinIndex Pin number to monitor
Returns
PK_OK on success, error code on failure
Definition at line 888 of file PoKeysLibIOAsync.c.
References sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, PK_DigitalIOGetAsync(), PK_ERR_GENERIC, and PK_ERR_NOT_CONNECTED.
PK_DigitalIOGetAsync()
int PK_DigitalIOGetAsync (sPoKeysDevice * device)
Asynchronously requests digital IO input values.
Definition at line 465 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), PK_DigitalIOGetParse(), and PK_ERR_NOT_CONNECTED.
Referenced by PK_DigitalInputGetSingleAsync().
PK_DigitalIOGetParse()
int PK_DigitalIOGetParse (sPoKeysDevice * device, const uint8_t * response)
Parser for digital IO input values (CMD 0xCC, param1=0)
Definition at line 453 of file PoKeysLibIOAsync.c.
References sPoKeysPinData::DigitalValueGet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_GENERIC, and PK_OK.
Referenced by PK_DigitalIOGetAsync(), and PK_DigitalIOSetGetAsync().
PK_DigitalIOSetAsync()
int32_t PK_DigitalIOSetAsync (sPoKeysDevice * device)
Asynchronously sets the digital IO values.
Definition at line 427 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysPinData::DigitalValueSet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, sPoKeysPinData::preventUpdate, and sPoKeysDevice::request.
PK_DigitalIOSetGetAsync()
int PK_DigitalIOSetGetAsync (sPoKeysDevice * device)
Combined Set and Get digital IO in one async call.
Definition at line 474 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysPinData::DigitalValueSet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_DigitalIOGetParse(), PK_ERR_NOT_CONNECTED, sPoKeysPinData::preventUpdate, and sPoKeysDevice::request.
Referenced by PK_DigitalOutputSetSingleAsync(), PK_DigitalOutputToggleAsync(), PK_EmergencyStopAllAsync(), and PK_IOUpdateCycleAsync().
PK_DigitalOutputSetSingleAsync()
int PK_DigitalOutputSetSingleAsync (sPoKeysDevice * device, uint8_t pinIndex, uint8_t value)
Set a single digital output pin (async)
Convenience function to set individual digital output without affecting others. Useful for discrete control operations.
Parameters
device Target device handle
pinIndex Pin number (0-based)
value Output state (0 or 1)
Returns
PK_OK on success, error code on failure
Definition at line 868 of file PoKeysLibIOAsync.c.
References sPoKeysPinData::DigitalValueSet, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_DigitalIOSetGetAsync(), PK_ERR_GENERIC, and PK_ERR_NOT_CONNECTED.
PK_DigitalOutputToggleAsync()
int PK_DigitalOutputToggleAsync (sPoKeysDevice * device, uint8_t pinIndex)
Toggle a digital output pin (async)
Convenience function to toggle the state of a digital output pin.
Parameters
device Target device handle
pinIndex Pin number (0-based)
Returns
PK_OK on success, error code on failure
Definition at line 905 of file PoKeysLibIOAsync.c.
References sPoKeysPinData::DigitalValueSet, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_DigitalIOSetGetAsync(), PK_ERR_GENERIC, and PK_ERR_NOT_CONNECTED.
PK_ParsePinFunctionsResponse()
int PK_ParsePinFunctionsResponse (sPoKeysDevice * dev, const uint8_t * resp)
Parser for pin function configuration response (CMD 0xC0, param1=0).
Definition at line 142 of file PoKeysLibIOAsync.c.
References dev, sPoKeysPinData::DigitalValueSet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysPinData::PinCap_invertPin, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_OK, and PK_PinCap_invertPin.
Referenced by PK_PinConfigurationGetAsync(), and PK_StartPinFunctionsRequestAsync().
PK_PinConfigurationGetAsync()
int32_t PK_PinConfigurationGetAsync (sPoKeysDevice * device)
Definition at line 291 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iTriggeredKeyMapping, PK_ERR_NOT_CONNECTED, PK_OK, PK_ParsePinFunctionsResponse(), PK_PinCounterConfigurationParse(), PK_PinKeyMappingCodesParse(), PK_PinKeyMappingModifiersParse(), PK_PinKeyMappingTypeParse(), PK_PinTriggeredDownKeyCodeParse(), PK_PinTriggeredDownKeyModifierParse(), PK_PinTriggeredUpKeyCodeParse(), and PK_PinTriggeredUpKeyModifierParse().
PK_PinConfigurationSetAsync()
int32_t PK_PinConfigurationSetAsync (sPoKeysDevice * device)
Sets all pin configuration fields asynchronously.
Definition at line 342 of file PoKeysLibIOAsync.c.
References sPoKeysPinData::CounterOptions, CreateRequestAsync(), sPoKeysPinData::DigitalValueSet, sPoKeysPinData::downKeyCodeMacroID, sPoKeysPinData::downKeyModifier, i, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iTriggeredKeyMapping, sPoKeysPinData::KeyCodeMacroID, sPoKeysPinData::KeyModifier, sPoKeysPinData::MappingType, sPoKeysPinData::PinCap_invertPin, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_NOT_CONNECTED, PK_OK, PK_PinCap_digitalInput, PK_PinCap_digitalOutput, PK_PinCap_invertPin, PK_PinCap_triggeredInput, sPoKeysPinData::upKeyCodeMacroID, and sPoKeysPinData::upKeyModifier.
PK_PinCounterConfigurationParse()
int PK_PinCounterConfigurationParse (sPoKeysDevice * dev, const uint8_t * resp)
Parser for digital counter configuration response (CMD 0xC0, param1=1).
Definition at line 172 of file PoKeysLibIOAsync.c.
References sPoKeysPinData::CounterOptions, dev, sPoKeysPinData::DigitalCounterAvailable, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_IsCounterAvailable(), and PK_OK.
Referenced by PK_PinConfigurationGetAsync().
PK_PinKeyMappingCodesParse()
int PK_PinKeyMappingCodesParse (sPoKeysDevice * dev, const uint8_t * resp)
Parser for pin key mapping codes response (CMD 0xC2).
Definition at line 203 of file PoKeysLibIOAsync.c.
References dev, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysPinData::KeyCodeMacroID, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_OK, and PK_PinCap_digitalInput.
Referenced by PK_PinConfigurationGetAsync().
PK_PinKeyMappingModifiersParse()
int PK_PinKeyMappingModifiersParse (sPoKeysDevice * dev, const uint8_t * resp)
Parser for pin key mapping modifiers response (CMD 0xC3).
Definition at line 219 of file PoKeysLibIOAsync.c.
References dev, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysPinData::KeyModifier, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_OK, and PK_PinCap_digitalInput.
Referenced by PK_PinConfigurationGetAsync().
PK_PinKeyMappingTypeParse()
int PK_PinKeyMappingTypeParse (sPoKeysDevice * dev, const uint8_t * resp)
Parser for pin key mapping type response (CMD 0xC1).
Definition at line 188 of file PoKeysLibIOAsync.c.
References dev, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysPinData::MappingType, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_OK, and PK_PinCap_digitalInput.
Referenced by PK_PinConfigurationGetAsync().
PK_PinTriggeredDownKeyCodeParse()
int PK_PinTriggeredDownKeyCodeParse (sPoKeysDevice * dev, const uint8_t * resp)
Parser for triggered key down macro ID mapping (CMD 0xD7, param1=11).
Definition at line 234 of file PoKeysLibIOAsync.c.
References dev, sPoKeysPinData::downKeyCodeMacroID, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_OK, and PK_PinCap_triggeredInput.
Referenced by PK_PinConfigurationGetAsync().
PK_PinTriggeredDownKeyModifierParse()
int PK_PinTriggeredDownKeyModifierParse (sPoKeysDevice * dev, const uint8_t * resp)
Parser for triggered key down modifiers (CMD 0xD7, param1=12).
Definition at line 249 of file PoKeysLibIOAsync.c.
References dev, sPoKeysPinData::downKeyModifier, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_OK, and PK_PinCap_triggeredInput.
Referenced by PK_PinConfigurationGetAsync().
PK_PinTriggeredUpKeyCodeParse()
int PK_PinTriggeredUpKeyCodeParse (sPoKeysDevice * dev, const uint8_t * resp)
Parser for triggered key up macro IDs (CMD 0xD7, param1=13).
Definition at line 279 of file PoKeysLibIOAsync.c.
References dev, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_OK, PK_PinCap_triggeredInput, and sPoKeysPinData::upKeyCodeMacroID.
Referenced by PK_PinConfigurationGetAsync().
PK_PinTriggeredUpKeyModifierParse()
int PK_PinTriggeredUpKeyModifierParse (sPoKeysDevice * dev, const uint8_t * resp)
Parser for triggered key up modifiers (CMD 0xD7, param1=14).
Definition at line 264 of file PoKeysLibIOAsync.c.
References dev, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_ERR_GENERIC, PK_OK, PK_PinCap_triggeredInput, and sPoKeysPinData::upKeyModifier.
Referenced by PK_PinConfigurationGetAsync().
PK_PoExtBusGetAsync()
int PK_PoExtBusGetAsync (sPoKeysDevice * device)
Starts async request to get PoExtBus data (CMD 0xDA, param1=2).
Definition at line 950 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), sPoKeysDevice::info, sPoKeysDevice_Info::iPoExtBus, parse_PoExtBusGet(), PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, and sPoKeysDevice::PoExtBusData.
PK_PoExtBusSetAsync()
int PK_PoExtBusSetAsync (sPoKeysDevice * device)
Starts async request to set PoExtBus data (CMD 0xDA).
Definition at line 928 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), i, sPoKeysDevice::info, sPoKeysDevice_Info::iPoExtBus, parse_PoExtBusGet(), PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, and sPoKeysDevice::PoExtBusData.
PK_PWMConfigurationGetAsync()
int PK_PWMConfigurationGetAsync (sPoKeysDevice * device)
Starts async request to get PWM configuration (CMD 0xCB, param1=0)
Definition at line 670 of file PoKeysLibIOAsync.c.
PK_PWMConfigurationParse()
int PK_PWMConfigurationParse (sPoKeysDevice * device, const uint8_t * response)
Parser for reading PWM configuration (CMD 0xCB, param1=0)
Definition at line 647 of file PoKeysLibIOAsync.c.
References PK_ERR_GENERIC, PK_OK, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
Referenced by PK_PWMConfigurationGetAsync().
PK_PWMConfigurationSetAsync()
int PK_PWMConfigurationSetAsync (sPoKeysDevice * device)
Starts async command to configure PWM duty cycle and period (CMD 0xCB).
Definition at line 615 of file PoKeysLibIOAsync.c.
PK_PWMConfigurationSetDirectlyAsync()
int PK_PWMConfigurationSetDirectlyAsync (sPoKeysDevice * device, uint32_t PWMperiod, uint8_t * enabledChannels)
Set PWM configuration directly with specified parameters (async)
Directly configures PWM with given period and enabled channels without using device structure values. Useful for direct control applications.
Parameters
device Target device handle
PWMperiod PWM period value
enabledChannels Array of 6 enabled channel flags (1=enabled, 0=disabled)
Returns
PK_OK on success, error code on failure
Definition at line 719 of file PoKeysLibIOAsync.c.
PK_PWMGetPinAssignmentsAsync()
int PK_PWMGetPinAssignmentsAsync (sPoKeysDevice * device)
Get PWM pin assignments (async)
Retrieves which pins are assigned to PWM outputs. Important for LinuxCNC pin mapping and diagnostics.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 851 of file PoKeysLibIOAsync.c.
PK_PWMPinAssignmentsParse()
int PK_PWMPinAssignmentsParse (sPoKeysDevice * device, const uint8_t * response)
Parser for PWM pin assignments (CMD 0xCB, param1=2)
Definition at line 831 of file PoKeysLibIOAsync.c.
References sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_ERR_GENERIC, PK_OK, sPoKeysDevice::PWM, and sPoKeysPWM::PWMpinIDs.
Referenced by PK_PWMGetPinAssignmentsAsync().
PK_PWMSetSingleChannelAsync()
int PK_PWMSetSingleChannelAsync (sPoKeysDevice * device, uint8_t channel, uint32_t dutyCycle)
Set single PWM channel duty cycle (async)
Updates a single PWM channel without affecting others. Optimized for individual channel control.
Parameters
device Target device handle
channel PWM channel (0-5)
dutyCycle Duty cycle value
Returns
PK_OK on success, error code on failure
Definition at line 795 of file PoKeysLibIOAsync.c.
PK_PWMUpdateAsync()
int PK_PWMUpdateAsync (sPoKeysDevice * device)
Starts async command to update PWM values only (CMD 0xCB, param1=1, param2=1).
Definition at line 680 of file PoKeysLibIOAsync.c.
PK_PWMUpdateDirectlyAsync()
int PK_PWMUpdateDirectlyAsync (sPoKeysDevice * device, uint32_t * dutyCycles)
Update PWM duty cycles directly (async)
Updates PWM duty cycles with provided values without using device structure. Efficient for real-time PWM control applications.
Parameters
device Target device handle
dutyCycles Array of 6 duty cycle values
Returns
PK_OK on success, error code on failure
Definition at line 755 of file PoKeysLibIOAsync.c.
PK_StartPinFunctionsRequestAsync()
int PK_StartPinFunctionsRequestAsync (sPoKeysDevice * dev)
Starts async pin function configuration request (CMD 0xC0, param1=0).
Definition at line 163 of file PoKeysLibIOAsync.c.
References CreateRequestAsync(), dev, PK_ERR_NOT_CONNECTED, and PK_ParsePinFunctionsResponse().