LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/pokeyslib/PoKeysLib1Wire.c File Reference
PoKeysLib1Wire.c File Reference
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
Functions
int32_t PK_1WireStatusSet (sPoKeysDevice *device, uint8_t activated)
int32_t PK_1WireStatusGet (sPoKeysDevice *device, uint8_t *activated)
int32_t PK_1WireWriteReadStart (sPoKeysDevice *device, uint8_t WriteCount, uint8_t ReadCount, uint8_t *data)
int32_t PK_1WireReadStatusGet (sPoKeysDevice *device, uint8_t *readStatus, uint8_t *ReadCount, uint8_t *data)
int32_t PK_1WireWriteReadStartEx (sPoKeysDevice *device, uint8_t pinID, uint8_t WriteCount, uint8_t ReadCount, uint8_t *data)
int32_t PK_1WireBusScanStart (sPoKeysDevice *device, uint8_t pinID)
int32_t PK_1WireBusScanGetResults (sPoKeysDevice *device, uint8_t *operationStatus, uint8_t *scanResult, uint8_t *deviceROM)
int32_t PK_1WireBusScanContinue (sPoKeysDevice *device)
int32_t PK_1WireBusScanStop (sPoKeysDevice *device)
Function Documentation
PK_1WireBusScanContinue()
int32_t PK_1WireBusScanContinue (sPoKeysDevice * device)
Definition at line 129 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireBusScanGetResults()
int32_t PK_1WireBusScanGetResults (sPoKeysDevice * device, uint8_t * operationStatus, uint8_t * scanResult, uint8_t * deviceROM)
Definition at line 113 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_1WireBusScanStart()
int32_t PK_1WireBusScanStart (sPoKeysDevice * device, uint8_t pinID)
Definition at line 105 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireBusScanStop()
int32_t PK_1WireBusScanStop (sPoKeysDevice * device)
Definition at line 138 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireReadStatusGet()
int32_t PK_1WireReadStatusGet (sPoKeysDevice * device, uint8_t * readStatus, uint8_t * ReadCount, uint8_t * data)
Definition at line 59 of file PoKeysLib1Wire.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_1WireStatusGet()
int32_t PK_1WireStatusGet (sPoKeysDevice * device, uint8_t * activated)
Definition at line 32 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_1WireStatusSet()
int32_t PK_1WireStatusSet (sPoKeysDevice * device, uint8_t activated)
Definition at line 24 of file PoKeysLib1Wire.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireWriteReadStart()
int32_t PK_1WireWriteReadStart (sPoKeysDevice * device, uint8_t WriteCount, uint8_t ReadCount, uint8_t * data)
Definition at line 43 of file PoKeysLib1Wire.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_1WireWriteReadStartEx()
int32_t PK_1WireWriteReadStartEx (sPoKeysDevice * device, uint8_t pinID, uint8_t WriteCount, uint8_t ReadCount, uint8_t * data)
Definition at line 88 of file PoKeysLib1Wire.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().