LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibEasySensorsAsync.c File Reference
PoKeysLibEasySensorsAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Data Structures
struct EasySensorAsyncContext
Functions
int PK_EasySensorsSetupGetAsync (sPoKeysDevice *device)
int PK_EasySensorsSetupSetAsync (sPoKeysDevice *device)
int PK_EasySensorsValueGetAllAsync (sPoKeysDevice *device)
Function Documentation
PK_EasySensorsSetupGetAsync()
int PK_EasySensorsSetupGetAsync (sPoKeysDevice * device)
Definition at line 63 of file PoKeysLibEasySensorsAsync.c.
References CreateRequestAsync(), sPoKeysDevice::EasySensors, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, PK_CMD_SENSORS_SETUP_57, PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.
PK_EasySensorsSetupSetAsync()
int PK_EasySensorsSetupSetAsync (sPoKeysDevice * device)
Definition at line 84 of file PoKeysLibEasySensorsAsync.c.
References CreateRequestAsyncWithPayload(), sPoKeysDevice::EasySensors, err, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, PK_CMD_SENSORS_SETUP_57, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_OK, SendRequestAsync(), sPoKeysEasySensor::sensorFailsafeConfig, sPoKeysEasySensor::sensorID, sPoKeysEasySensor::sensorReadingID, sPoKeysEasySensor::sensorRefreshPeriod, and sPoKeysEasySensor::sensorType.
PK_EasySensorsValueGetAllAsync()
int PK_EasySensorsValueGetAllAsync (sPoKeysDevice * device)
Definition at line 107 of file PoKeysLibEasySensorsAsync.c.
References CreateRequestAsync(), i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice::info, PK_CMD_SENSOR_VALUES_READ_57, PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.