LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibCoreAsync.c File Reference
PoKeysLibCoreAsync.c File Reference
Asynchronous variants of core communication helpers.
#include <stdlib.h>
#include <hidapi/hidapi.h>
#include <string.h>
#include "stdio.h"
Data Structures
struct PKUSBEnumerator
Enumerations
enum PK_EnumStage {
ENUM_IDLE , ENUM_ENUMERATING_1001 , ENUM_ENUMERATING_1002 , ENUM_DONE ,
ENUM_IDLE , ENUM_ENUMERATING_1001 , ENUM_ENUMERATING_1002 , ENUM_DONE
}
Functions
int32_t PK_EnumerateUSBDevicesAsync (PKUSBEnumerator *ctx)
Begin or continue asynchronous USB enumeration.
void PK_InitializeNewDeviceAsync (void *device_ptr)
void PK_CleanDeviceAsync (void *device_ptr)
void PK_CloneDeviceStructureAsync (const sPoKeysDevice *original, sPoKeysDevice *destination)
sPoKeysDevice * PK_ConnectToDeviceAsync (uint32_t deviceIndex)
sPoKeysDevice * PK_ConnectToPoKeysDevice_USB_Async (uint32_t serialNumber, uint32_t flags)
sPoKeysDevice * PK_ConnectToPoKeysDevice_Ethernet_Async (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
sPoKeysDevice * PK_ConnectToDeviceWSerial_Async (uint32_t serial, uint32_t timeout_ms)
int32_t PK_EnumerateUSBDevices ()
Enumerate PoKeys USB devices (blocking helper).
int32_t PK_GetCurrentDeviceConnectionType (sPoKeysDevice *device)
Return the currently used connection type.
void InitializeNewDevice (sPoKeysDevice *device)
void CleanDevice (sPoKeysDevice *device)
void PK_ReleaseDeviceStructure (sPoKeysDevice *device)
void PK_CloneDeviceStructure (sPoKeysDevice *original, sPoKeysDevice *destination)
void * PK_FastUSBConnectToDevice (uint32_t deviceIndex)
sPoKeysDevice * PK_ConnectToDevice (uint32_t deviceIndex)
sPoKeysDevice * PK_ConnectToPoKeysDevice_USB (uint32_t serialNumber, uint32_t flags)
sPoKeysDevice * PK_ConnectToPoKeysDevice_Ethernet (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
sPoKeysDevice * PK_ConnectToPoKeysDevice (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
sPoKeysDevice * PK_ConnectToDeviceWSerial (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
sPoKeysDevice * PK_ConnectToDeviceWSerial_UDP (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
void PK_DisconnectDevice (sPoKeysDevice *device)
int32_t CreateRequest (unsigned char *request, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Fill a request buffer with a PoKeys command.
int32_t PK_CustomRequest (sPoKeysDevice *device, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Send a command composed from the provided parameters.
uint8_t getChecksum (uint8_t *data)
int32_t SendRequest_multiPart (sPoKeysDevice *device)
Send a multi-part request buffer.
int32_t SendRequest (sPoKeysDevice *device)
Send a request and wait for a response (async context).
int32_t SendRequest_NoResponse (sPoKeysDevice *device)
Transmit a request without reading any reply.
void PK_SL_SetPinFunction (sPoKeysDevice *device, uint8_t pin, uint8_t function)
uint8_t PK_SL_GetPinFunction (sPoKeysDevice *device, uint8_t pin)
void PK_SL_DigitalOutputSet (sPoKeysDevice *device, uint8_t pin, uint8_t value)
uint8_t PK_SL_DigitalInputGet (sPoKeysDevice *device, uint8_t pin)
uint32_t PK_SL_AnalogInputGet (sPoKeysDevice *device, uint8_t pin)
Variables
int32_t LastRetryCount = 0
int32_t LastWaitCount = 0
Detailed Description
Asynchronous variants of core communication helpers.
This file provides non-blocking versions of the USB enumeration and request sending routines. They adhere to the same packet format as the synchronous functions defined in PoKeysLibCore.c.
Definition in file PoKeysLibCoreAsync.c.
Enumeration Type Documentation
PK_EnumStage
enum PK_EnumStage
Enumerator
ENUM_IDLE
ENUM_ENUMERATING_1001
ENUM_ENUMERATING_1002
ENUM_DONE
ENUM_IDLE
ENUM_ENUMERATING_1001
ENUM_ENUMERATING_1002
ENUM_DONE
Definition at line 15 of file PoKeysLibCoreAsync.c.
Function Documentation
CleanDevice()
void CleanDevice (sPoKeysDevice * device)
Definition at line 660 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::MatrixLED, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, sPoKeysDevice::Pins, sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMpinIDs.
Referenced by PK_ConnectToPoKeysDevice_USB(), PK_DisconnectDevice(), and PK_ReleaseDeviceStructure().
CreateRequest()
int32_t CreateRequest (unsigned char * request, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Fill a request buffer with a PoKeys command.
Compose a PoKeys request packet.
This helper mirrors the synchronous CreateRequest() implementation and prepares a 64 byte packet header according to the protocol.
Parameters
request Buffer that will receive the command bytes.
type Command ID (PK_CMD_* constant).
param1 Parameter 1.
param2 Parameter 2.
param3 Parameter 3.
param4 Parameter 4.
Returns
PK_OK on success or PK_ERR_NOT_CONNECTED when request is NULL.
Definition at line 1089 of file PoKeysLibCoreAsync.c.
References PK_ERR_NOT_CONNECTED, and PK_OK.
getChecksum()
uint8_t getChecksum (uint8_t * data)
Definition at line 1129 of file PoKeysLibCoreAsync.c.
References i.
Referenced by SendRequest(), and SendRequest_NoResponse().
InitializeNewDevice()
void InitializeNewDevice (sPoKeysDevice * device)
General pin settings PoKeys55, PoKeys56, PoKeys57 limitations
Pin codes used in PoKeys55 device are 0-based, e.g. pin 1 has pin code of 0, pin 55 has pin code of 54.
Analog input capable pins 43 to 47 have pin codes of 42 to 46.
Analog output capable pin 43 has pin code of 42.
PWM (pulse-width modulation) capable pins 17 to 22 have pin codes of 16-21 (PWM module outputs are in reversed order, e.g. pin 17 (pin coded as 16) is connected to PWM6 output – see specifications below).
PoKeys57CNC device supports PWM output function on 4 pins (pins 18, 20, 21 and 22). Different duty cycles can be assigned to each PWM output however, all outputs share the same PWM period. PWM outputs can be easily amplified using an external transistor and used for control of loads with increased increased current demand - pins with such function embedded are marked as OC (open-collector) in the pinout diagram. PoKeys PWM outputs can also be used to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). PoKeys devices have an in-built PWM module that operates at a fixed clock frequency (25 MHz). Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000)
PoKeys57CNCpro4x25 device supports PWM output function on pins 17 and 20. Pin 17 is wired to 0- 10 V output for spindle control – the output voltage is proportional to the duty cycle of the PWM output. PWM output on pin 20 is located on dedicated connector and can be easily amplified using an external transistor and used for controlling the loads with increased current demand – we offer MOSFET power switch adapter for such purposes in PoLabs online store. The frequency of the generated PWM signal can be changed – for the analog output functionality on pin 17 to operate as designed, a PWM frequency of 20 kHz is suggested. However, if needed, the frequency of PoKeys PWM outputs can be reduced – e.g. to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). In such case, analog output on pin 17 will not be operational. PoKeys devices have a built-in PWM module that operates at a fixed clock frequency of 25 MHz. Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000).
Definition at line 559 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::AnalogOutput, sPoKeysDevice::DeviceData, sPoKeysPinData::DigitalCounterAvailable, sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, hal_malloc(), i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice::LCD, sPoKeysDevice::matrixKB, sPoKeysDevice::MatrixLED, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, sPoKeysDevice::PEv2, sPoKeysDevice::Pins, PK_DeviceDataGet(), PK_FillPWMPinNumbers(), PK_IsCounterAvailable(), sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMpinIDs, sPoKeysDevice::readRetries, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysDevice::sendRetries, sPoKeysDevice::socketTimeout, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
Referenced by PK_ConnectToDevice(), PK_ConnectToNetworkDeviceAsync(), PK_ConnectToPoKeysDevice_Ethernet(), and PK_ConnectToPoKeysDevice_USB().
PK_CleanDeviceAsync()
void PK_CleanDeviceAsync (void * device_ptr)
Definition at line 183 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::MatrixLED, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, sPoKeysDevice::Pins, sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMpinIDs.
Referenced by PK_ConnectToPoKeysDevice_USB_Async().
PK_CloneDeviceStructure()
void PK_CloneDeviceStructure (sPoKeysDevice * original, sPoKeysDevice * destination)
Definition at line 691 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, sPoKeysDevice::DeviceData, sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, hal_malloc(), sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice::LCD, sPoKeysDevice::matrixKB, sPoKeysDevice::MatrixLED, sPoKeysDevice::netDeviceData, sPoKeysDevice::Pins, sPoKeysDevice::PoExtBusData, sPoKeysDevice::PoIL, sPoKeysDevice::PoNETmodule, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysPWM::PWMpinIDs, sPoKeysDevice::requestID, sPoKeysDevice::RTC, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
PK_CloneDeviceStructureAsync()
void PK_CloneDeviceStructureAsync (const sPoKeysDevice * original, sPoKeysDevice * destination)
Definition at line 215 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, sPoKeysDevice::DeviceData, sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, hal_malloc(), sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice::LCD, sPoKeysDevice::matrixKB, sPoKeysDevice::MatrixLED, sPoKeysDevice::netDeviceData, sPoKeysDevice::Pins, sPoKeysDevice::PoExtBusData, sPoKeysDevice::PoIL, sPoKeysDevice::PoNETmodule, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysPWM::PWMpinIDs, sPoKeysDevice::requestID, sPoKeysDevice::RTC, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
PK_ConnectToDevice()
sPoKeysDevice * PK_ConnectToDevice (uint32_t deviceIndex)
Definition at line 770 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, hal_malloc(), hid_enumerate(), hid_free_enumeration(), hid_open_path(), InitializeNewDevice(), hid_device_info::interface_number, hid_device_info::next, hid_device_info::path, PK_DeviceType_FastUSBDevice, PK_DeviceType_USBDevice, and PK_FastUSBConnectToDevice().
Referenced by PK57i_Connect().
PK_ConnectToDeviceAsync()
sPoKeysDevice * PK_ConnectToDeviceAsync (uint32_t deviceIndex)
Definition at line 271 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, hal_malloc(), hid_enumerate(), hid_free_enumeration(), hid_open_path(), hid_device_info::interface_number, hid_device_info::next, hid_device_info::path, PK_DeviceType_USBDevice, and PK_InitializeNewDeviceAsync().
PK_ConnectToDeviceWSerial()
sPoKeysDevice * PK_ConnectToDeviceWSerial (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
Definition at line 1040 of file PoKeysLibCoreAsync.c.
References PK_ConnectToPoKeysDevice().
PK_ConnectToDeviceWSerial_Async()
sPoKeysDevice * PK_ConnectToDeviceWSerial_Async (uint32_t serial, uint32_t timeout_ms)
Definition at line 455 of file PoKeysLibCoreAsync.c.
PK_ConnectToDeviceWSerial_UDP()
sPoKeysDevice * PK_ConnectToDeviceWSerial_UDP (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
Definition at line 1045 of file PoKeysLibCoreAsync.c.
References PK_ConnectToPoKeysDevice().
PK_ConnectToPoKeysDevice()
sPoKeysDevice * PK_ConnectToPoKeysDevice (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
Definition at line 1020 of file PoKeysLibCoreAsync.c.
References PK_ConnectToPoKeysDevice_Ethernet(), and PK_ConnectToPoKeysDevice_USB().
Referenced by PK_ConnectToDeviceWSerial(), and PK_ConnectToDeviceWSerial_UDP().
PK_ConnectToPoKeysDevice_Ethernet()
sPoKeysDevice * PK_ConnectToPoKeysDevice_Ethernet (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
Definition at line 982 of file PoKeysLibCoreAsync.c.
References hal_malloc(), InitializeNewDevice(), PK_ConnectToNetworkDevice(), PK_SearchNetworkDevices(), and sPoKeysNetworkDeviceSummary::useUDP.
Referenced by PK_ConnectToPoKeysDevice().
PK_ConnectToPoKeysDevice_Ethernet_Async()
sPoKeysDevice * PK_ConnectToPoKeysDevice_Ethernet_Async (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
Definition at line 420 of file PoKeysLibCoreAsync.c.
References hal_malloc(), PK_ConnectToNetworkDevice(), PK_InitializeNewDeviceAsync(), PK_SearchNetworkDevices(), and sPoKeysNetworkDeviceSummary::useUDP.
PK_ConnectToPoKeysDevice_USB()
sPoKeysDevice * PK_ConnectToPoKeysDevice_USB (uint32_t serialNumber, uint32_t flags)
Definition at line 862 of file PoKeysLibCoreAsync.c.
References CleanDevice(), sPoKeysDevice::connectionType, ConnectToFastUSBInterface, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, sPoKeysDevice::DeviceData, hal_malloc(), hid_enumerate(), hid_free_enumeration(), hid_open_path(), InitializeNewDevice(), hid_device_info::interface_number, hid_device_info::next, hid_device_info::path, PK_DeviceType_FastUSBDevice, PK_DeviceType_USBDevice, hid_device_info::serial_number, and sPoKeysDevice_Data::SerialNumber.
Referenced by PK_ConnectToPoKeysDevice().
PK_ConnectToPoKeysDevice_USB_Async()
sPoKeysDevice * PK_ConnectToPoKeysDevice_USB_Async (uint32_t serialNumber, uint32_t flags)
Definition at line 335 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, sPoKeysDevice::DeviceData, hal_malloc(), hid_enumerate(), hid_free_enumeration(), hid_open_path(), PK_CleanDeviceAsync(), PK_DeviceType_USBDevice, PK_InitializeNewDeviceAsync(), and sPoKeysDevice_Data::SerialNumber.
PK_CustomRequest()
int32_t PK_CustomRequest (sPoKeysDevice * device, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Send a command composed from the provided parameters.
Send an arbitrary request to the connected device.
A convenience wrapper that fills device->request using CreateRequest() semantics and then calls SendRequest().
Parameters
device Target device instance.
type Command ID.
param1 Parameter 1.
param2 Parameter 2.
param3 Parameter 3.
param4 Parameter 4.
Returns
Result of SendRequest().
Definition at line 1118 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::request, and SendRequest().
PK_DisconnectDevice()
void PK_DisconnectDevice (sPoKeysDevice * device)
Definition at line 1050 of file PoKeysLibCoreAsync.c.
References CleanDevice(), sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, DisconnectFromFastUSBInterface, hid_close(), PK_DeviceType_NetworkDevice, and PK_DisconnectNetworkDevice().
Referenced by PK57i_Connect(), and PK57i_Disconnect().
PK_EnumerateUSBDevices()
int32_t PK_EnumerateUSBDevices (void)
Enumerate PoKeys USB devices (blocking helper).
Enumerate PoKeys USB devices.
This function performs the same enumeration as PK_EnumerateUSBDevicesAsync() but in a blocking manner.
Returns
Number of detected devices.
Definition at line 510 of file PoKeysLibCoreAsync.c.
References hid_enumerate(), hid_free_enumeration(), hid_device_info::interface_number, hid_device_info::next, PK_EnumerateFastUSBDevices(), and PKI_CheckInterface().
Referenced by PK57i_Connect().
PK_EnumerateUSBDevicesAsync()
int32_t PK_EnumerateUSBDevicesAsync (PKUSBEnumerator * ctx)
Begin or continue asynchronous USB enumeration.
The enumeration context maintains its own state machine. Calling this function repeatedly will progress through device discovery according to the PoKeys protocol. When enumeration completes the function returns the number of detected USB devices.
Parameters
ctx Enumeration context structure. Pass NULL to abort.
Returns
-2 while enumeration is in progress, a non-negative device count on completion or -1 on invalid parameters.
Definition at line 41 of file PoKeysLibCoreAsync.c.
References PKUSBEnumerator::cur_dev, PKUSBEnumerator::devs, ENUM_DONE, ENUM_ENUMERATING_1001, ENUM_ENUMERATING_1002, ENUM_IDLE, hid_enumerate(), hid_free_enumeration(), hid_device_info::interface_number, hid_device_info::next, PKUSBEnumerator::numDevices, PK_EnumerateFastUSBDevices(), PKI_CheckInterface(), and PKUSBEnumerator::state.
PK_FastUSBConnectToDevice()
void * PK_FastUSBConnectToDevice (uint32_t deviceIndex)
Referenced by PK_ConnectToDevice().
PK_GetCurrentDeviceConnectionType()
int32_t PK_GetCurrentDeviceConnectionType (sPoKeysDevice * device)
Return the currently used connection type.
Obtain the active connection type for a device.
This is an inline helper used by async routines to determine whether communication is performed over USB, network or fast USB.
Parameters
device PoKeys device handle.
Returns
Connection type constant from ePK_DeviceConnectionType.
Definition at line 554 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::connectionType.
PK_InitializeNewDeviceAsync()
void PK_InitializeNewDeviceAsync (void * device_ptr)
Definition at line 97 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::AnalogInput, sPoKeysDevice::DeviceData, sPoKeysPinData::DigitalCounterAvailable, sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, hal_malloc(), i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice::LCD, sPoKeysDevice::matrixKB, sPoKeysDevice::MatrixLED, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, sPoKeysDevice::PEv2, sPoKeysDevice::Pins, PK_DeviceDataGet(), PK_FillPWMPinNumbers(), PK_IsCounterAvailable(), sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMpinIDs, sPoKeysDevice::readRetries, sPoKeysDevice::request, sPoKeysDevice::response, RTAPI_MSG_ERR, rtapi_print_msg(), sPoKeysDevice::sendRetries, sPoKeysDevice::socketTimeout, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
Referenced by PK_ConnectToDeviceAsync(), PK_ConnectToPoKeysDevice_Ethernet_Async(), and PK_ConnectToPoKeysDevice_USB_Async().
PK_ReleaseDeviceStructure()
void PK_ReleaseDeviceStructure (sPoKeysDevice * device)
Definition at line 686 of file PoKeysLibCoreAsync.c.
References CleanDevice().
PK_SL_AnalogInputGet()
uint32_t PK_SL_AnalogInputGet (sPoKeysDevice * device, uint8_t pin)
Definition at line 1318 of file PoKeysLibCoreAsync.c.
References sPoKeysPinData::AnalogValue, and sPoKeysDevice::Pins.
PK_SL_DigitalInputGet()
uint8_t PK_SL_DigitalInputGet (sPoKeysDevice * device, uint8_t pin)
Definition at line 1313 of file PoKeysLibCoreAsync.c.
References sPoKeysPinData::DigitalValueGet, and sPoKeysDevice::Pins.
PK_SL_DigitalOutputSet()
void PK_SL_DigitalOutputSet (sPoKeysDevice * device, uint8_t pin, uint8_t value)
Definition at line 1308 of file PoKeysLibCoreAsync.c.
References sPoKeysPinData::DigitalValueSet, and sPoKeysDevice::Pins.
PK_SL_GetPinFunction()
uint8_t PK_SL_GetPinFunction (sPoKeysDevice * device, uint8_t pin)
Definition at line 1303 of file PoKeysLibCoreAsync.c.
References sPoKeysPinData::PinFunction, and sPoKeysDevice::Pins.
PK_SL_SetPinFunction()
void PK_SL_SetPinFunction (sPoKeysDevice * device, uint8_t pin, uint8_t function)
Definition at line 1298 of file PoKeysLibCoreAsync.c.
References sPoKeysPinData::PinFunction, and sPoKeysDevice::Pins.
SendRequest()
int32_t SendRequest (sPoKeysDevice * device)
Send a request and wait for a response (async context).
Send a request and wait for the device response.
Formats the current request buffer, transmits it over the selected interface and waits for the reply in a blocking loop. Functionally identical to the synchronous version.
Parameters
device Target device instance.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1182 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, getChecksum(), hid_read(), hid_write(), LastRetryCount, LastWaitCount, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, SendEthRequest(), and SendRequestFastUSB.
Referenced by PK_CustomRequest().
SendRequest_multiPart()
int32_t SendRequest_multiPart (sPoKeysDevice * device)
Send a multi-part request buffer.
Send a multipart data transfer.
For large data transfers the packet is split into 8 blocks and transmitted using network or fast USB helpers. Behaviour matches the synchronous SendRequest_multiPart() routine.
Parameters
device Device handle containing prepared multipart data.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1154 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::connectionType, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, SendEthRequestBig(), and SendRequestFastUSB_multiPart.
SendRequest_NoResponse()
int32_t SendRequest_NoResponse (sPoKeysDevice * device)
Transmit a request without reading any reply.
Send a request without waiting for any reply.
The request buffer is formatted the same as in SendRequest() but the function returns immediately after sending the packet. Used for commands that do not generate a direct response.
Parameters
device Target device instance.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 1256 of file PoKeysLibCoreAsync.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, getChecksum(), hid_write(), PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, sPoKeysDevice::request, sPoKeysDevice::requestID, and SendEthRequest_NoResponse().
Variable Documentation
LastRetryCount
int32_t LastRetryCount = 0
Definition at line 1141 of file PoKeysLibCoreAsync.c.
Referenced by SendRequest().
LastWaitCount
int32_t LastWaitCount = 0
Definition at line 1142 of file PoKeysLibCoreAsync.c.
Referenced by SendRequest().