LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibAsync.c File Reference
PoKeysLibAsync.c File Reference
#include "PoKeysLibAsync.h"
#include <string.h>
#include <time.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <errno.h>
Functions
uint64_t get_current_time_us (void)
uint8_t next_request_id (void)
async_transaction_t * transaction_alloc (void)
Allocates a new free transaction.
async_transaction_t * transaction_find (uint8_t request_id)
Finds an open transaction by its Request ID.
int CreateRequestAsync (sPoKeysDevice *dev, pokeys_command_t cmd, const uint8_t *params, size_t params_len, void *target_ptr, size_t target_size, int(*parser_func)(sPoKeysDevice *, const uint8_t *))
Prepares an asynchronous request (non-sending).
int CreateRequestAsyncWithPayload (sPoKeysDevice *device, pokeys_command_t cmd, const uint8_t *params, size_t params_len, const void *payload, size_t payload_size, pokeys_response_parser_t parser_func)
Prepares an asynchronous PoKeys request with optional payload data after header.
int SendRequestAsync (sPoKeysDevice *dev, uint8_t request_id)
Sends an asynchronous request that was prepared earlier.
int PK_ReceiveAndDispatch (sPoKeysDevice *dev)
Receives UDP packets and dispatches them to the correct async transaction.
void PK_TimeoutAndRetryCheck (sPoKeysDevice *dev, uint64_t timeout_us)
Enhanced timeout and retry check with exponential backoff and error recovery.
Function Documentation
CreateRequestAsync()
int CreateRequestAsync (sPoKeysDevice * dev, pokeys_command_t cmd, const uint8_t * params, size_t params_len, void * target_ptr, size_t target_size, int(*)(sPoKeysDevice *, const uint8_t *) parser_func)
Prepares an asynchronous request (non-sending).
Parameters
dev Pointer to the PoKeys device (not used directly for building but might be logged or expanded later).
cmd Command to be sent (Operation ID).
params Optional pointer to up to 4 bytes of parameters.
params_len Length of parameters (should be 0-4).
target_ptr Pointer where decoded response data should be written.
target_size Size of the target buffer.
Returns
Request ID on success, negative error code on failure.
Definition at line 94 of file PoKeysLibAsync.c.
References async_transaction_t::command_sent, i, next_request_id(), async_transaction_t::request_buffer, async_transaction_t::request_id, async_transaction_t::response_parser, async_transaction_t::retries_left, async_transaction_t::status, async_transaction_t::target_ptr, async_transaction_t::target_size, async_transaction_t::timestamp_sent, transaction_alloc(), and TRANSACTION_PENDING.
Referenced by PK_1WireBusScanContinueAsync(), PK_1WireBusScanGetResultsAsync(), PK_1WireBusScanStartAsync(), PK_1WireBusScanStopAsync(), PK_1WireReadStatusGetAsync(), PK_1WireStatusGetAsync(), PK_1WireStatusSetAsync(), PK_AnalogIOGetAsync(), PK_AnalogRCFilterGetAsync(), PK_AnalogRCFilterSetAsync(), PK_CANFlushAsync(), PK_CANReadAsync(), PK_COSMSettingsGetAsync(), PK_DeviceAliveCheckAsync(), PK_DeviceDataGetAsync(), PK_DeviceErrorResetAsync(), PK_DeviceErrorStatusAsync(), PK_DeviceLoadStatusAsync(), PK_DigitalCounterClearAsync(), PK_DigitalCounterGetAsync(), PK_DigitalIOGetAsync(), PK_DigitalIOSetAsync(), PK_DigitalIOSetGetAsync(), PK_EasySensorsSetupGetAsync(), PK_EasySensorsValueGetAllAsync(), PK_EncoderConfigurationGetAsync(), PK_EncoderRawValueResetAsync(), PK_EncoderValuesGetAsync(), PK_FailsafeSettingsGetAsync(), PK_I2CBusScanGetResultsAsync(), PK_I2CBusScanStartAsync(), PK_I2CGetStatusAsync(), PK_I2CReadStartAsync(), PK_I2CReadStatusGetAsync(), PK_I2CSetStatusAsync(), PK_I2CWriteStatusGetAsync(), PK_LCDConfigurationGetAsync(), PK_LCDConfigurationSetAsync(), PK_MatrixKBConfigurationGetAsync(), PK_MatrixKBStatusGetAsync(), PK_MatrixLEDConfigurationGetAsync(), PK_MatrixLEDConfigurationSetAsync(), PK_PEv2_AdditionalParametersGetAsync(), PK_PEv2_AxisConfigurationGetAsync(), PK_PEv2_Status2GetAsync(), PK_PEv2_StatusGetAsync(), PK_PinConfigurationGetAsync(), PK_PinConfigurationSetAsync(), PK_PoExtBusGetAsync(), PK_PoExtBusSetAsync(), PK_PoNETDeviceDiscoveryAsync(), PK_PoNETGetModuleLightAsync(), PK_PoNETGetModuleLightRequestAsync(), PK_PoNETGetModuleSettingsAsync(), PK_PoNETGetModuleStatusAsync(), PK_PoNETGetModuleStatusRequestAsync(), PK_PoNETGetPoNETStatusAsync(), PK_PoNETModuleReinitializeAsync(), PK_PoNETSetModulePWMAsync(), PK_PWMConfigurationGetAsync(), PK_PWMConfigurationSetAsync(), PK_PWMConfigurationSetDirectlyAsync(), PK_PWMGetPinAssignmentsAsync(), PK_PWMSetSingleChannelAsync(), PK_PWMUpdateAsync(), PK_PWMUpdateDirectlyAsync(), PK_PWMUpdateSelectedChannelsAsync(), PK_RTCGetAsync(), PK_SecurityStatusGetAsync(), PK_SPIConfigureAsync(), PK_SPIReadAsync(), PK_StartPinFunctionsRequestAsync(), PK_UARTReadAsync(), and PK_WS2812_UpdateAsync().
CreateRequestAsyncWithPayload()
int CreateRequestAsyncWithPayload (sPoKeysDevice * device, pokeys_command_t cmd, const uint8_t * params, size_t params_len, const void * payload, size_t payload_size, pokeys_response_parser_t parser_func)
Prepares an asynchronous PoKeys request with optional payload data after header.
Parameters
device Pointer to PoKeys device
cmd PoKeys command ID (e.g., 0xC4, 0xC5, 0xCE, etc.)
params Optional pointer to up to 4 parameter bytes (NULL if none)
params_len Length of params (max 4 bytes)
payload Optional pointer to payload (e.g., encoder options) to copy starting at byte 8
payload_size Size of payload (must fit into remaining packet space)
parser_func Optional parser function for response (NULL for write-only operations)
Returns
Request ID on success, negative error code on failure
Definition at line 152 of file PoKeysLibAsync.c.
References async_transaction_t::command_sent, i, next_request_id(), async_transaction_t::request_buffer, async_transaction_t::request_id, async_transaction_t::response_parser, async_transaction_t::retries_left, async_transaction_t::status, async_transaction_t::target_ptr, async_transaction_t::target_size, async_transaction_t::timestamp_sent, transaction_alloc(), and TRANSACTION_PENDING.
Referenced by PK_1WireWriteReadStartAsync(), PK_1WireWriteReadStartExAsync(), PK_CANConfigureAsync(), PK_CANRegisterFilterAsync(), PK_CANWriteAsync(), PK_COSMSettingsSetAsync(), PK_EasySensorsSetupSetAsync(), PK_EncoderConfigurationSetAsync(), PK_EncoderValuesSetAsync(), PK_FailsafeSettingsSetAsync(), PK_I2CWriteAndReadStartAsync(), PK_I2CWriteStartAsync(), PK_LCDSetCustomCharactersAsync(), PK_LCDUpdateAsync(), PK_MatrixKBConfigurationSetAsync(), PK_MatrixLEDUpdateAsync(), PK_PEv2_AdditionalParametersSetAsync(), PK_PEv2_AxisConfigurationSetAsync(), PK_PEv2_ExternalOutputsSetAsync(), PK_PEv2_HomingStartAsync(), PK_PEv2_PulseEngineMovePVAsync(), PK_PEv2_PulseEngineSetupAsync(), PK_PoNETSetModuleStatusAsync(), PK_SPITransferAsync(), PK_SPIWriteAsync(), PK_UARTConfigureAsync(), PK_UARTWriteAsync(), PK_UserAuthoriseAsync(), and PK_UserPasswordSetAsync().
get_current_time_us()
uint64_t get_current_time_us (void)
Definition at line 38 of file PoKeysLibAsync.c.
References rtapi_get_time().
Referenced by PK_SearchNetworkDevicesAsync_Process(), PK_TimeoutAndRetryCheck(), and SendRequestAsync().
next_request_id()
uint8_t next_request_id (void)
Definition at line 52 of file PoKeysLibAsync.c.
Referenced by CreateRequestAsync(), and CreateRequestAsyncWithPayload().
PK_ReceiveAndDispatch()
int PK_ReceiveAndDispatch (sPoKeysDevice * dev)
Receives UDP packets and dispatches them to the correct async transaction.
Parameters
dev Pointer to the PoKeys device structure.
Returns
Number of responses processed, or 0 if none.
Definition at line 251 of file PoKeysLibAsync.c.
References dev, sPoKeysDevice::devHandle, async_transaction_t::response_buffer, async_transaction_t::response_parser, async_transaction_t::response_ready, async_transaction_t::status, async_transaction_t::target_ptr, async_transaction_t::target_size, TRANSACTION_COMPLETED, and transaction_find().
Referenced by FUNCTION(), and user_mainloop().
PK_TimeoutAndRetryCheck()
void PK_TimeoutAndRetryCheck (sPoKeysDevice * dev, uint64_t timeout_us)
Enhanced timeout and retry check with exponential backoff and error recovery.
This implementation provides:
Exponential backoff for retries
Better error tracking and recovery
RT-safe operation with minimal overhead
Parameters
dev Pointer to the PoKeys device structure.
timeout_us Base timeout threshold in microseconds per attempt.
Definition at line 313 of file PoKeysLibAsync.c.
References get_current_time_us(), i, and MAX_TRANSACTIONS.
Referenced by FUNCTION(), and user_mainloop().
SendRequestAsync()
int SendRequestAsync (sPoKeysDevice * dev, uint8_t request_id)
Sends an asynchronous request that was prepared earlier.
Parameters
dev Pointer to the PoKeys device structure.
request_id Request ID of the transaction to send.
Returns
0 on success, negative error code on failure.
Definition at line 219 of file PoKeysLibAsync.c.
References dev, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, get_current_time_us(), async_transaction_t::request_buffer, RTAPI_MSG_ERR, rtapi_print_msg(), async_transaction_t::timestamp_sent, and transaction_find().
Referenced by PK_1WireBusScanContinueAsync(), PK_1WireBusScanStartAsync(), PK_1WireBusScanStopAsync(), PK_1WireStatusSetAsync(), PK_1WireWriteReadStartAsync(), PK_1WireWriteReadStartExAsync(), PK_CANConfigureAsync(), PK_CANFlushAsync(), PK_CANRegisterFilterAsync(), PK_CANWriteAsync(), PK_COSMSettingsSetAsync(), PK_EasySensorsSetupSetAsync(), PK_FailsafeSettingsSetAsync(), PK_I2CBusScanStartAsync(), PK_I2CReadStartAsync(), PK_I2CSetStatusAsync(), PK_I2CWriteAndReadStartAsync(), PK_I2CWriteStartAsync(), PK_LCDConfigurationSetAsync(), PK_LCDSetCustomCharactersAsync(), PK_LCDUpdateAsync(), PK_MatrixKBConfigurationSetAsync(), PK_MatrixLEDConfigurationSetAsync(), PK_MatrixLEDUpdateAsync(), PK_PEv2_AdditionalParametersSetAsync(), PK_PEv2_AxisConfigurationSetAsync(), PK_PEv2_ExternalOutputsSetAsync(), PK_PEv2_HomingStartAsync(), PK_PEv2_PulseEngineMovePVAsync(), PK_PEv2_PulseEngineSetupAsync(), PK_PoNETDeviceDiscoveryAsync(), PK_PoNETGetModuleLightRequestAsync(), PK_PoNETGetModuleStatusRequestAsync(), PK_PoNETModuleReinitializeAsync(), PK_PoNETSetModulePWMAsync(), PK_PoNETSetModuleStatusAsync(), PK_RTCGetAsync(), PK_SPIConfigureAsync(), PK_SPIReadAsync(), PK_SPITransferAsync(), PK_SPIWriteAsync(), PK_UARTConfigureAsync(), PK_UARTWriteAsync(), PK_UserPasswordSetAsync(), and PK_WS2812_UpdateAsync().
transaction_alloc()
async_transaction_t * transaction_alloc (void)
Allocates a new free transaction.
Returns
Pointer to an empty async_transaction_t, or NULL if none available.
Definition at line 22 of file PoKeysLibAsync.c.
References i, and MAX_TRANSACTIONS.
Referenced by CreateRequestAsync(), and CreateRequestAsyncWithPayload().
transaction_find()
async_transaction_t * transaction_find (uint8_t request_id)
Finds an open transaction by its Request ID.
Parameters
request_id The Request ID to search for.
Returns
Pointer to matching async_transaction_t or NULL if not found.
Definition at line 66 of file PoKeysLibAsync.c.
References i, and MAX_TRANSACTIONS.
Referenced by PK_ReceiveAndDispatch(), and SendRequestAsync().