LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLib1WireAsync.c File Reference
PoKeysLib1WireAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Data Structures
struct OneWireAsyncContext
Functions
int PK_1WireStatusSetAsync (sPoKeysDevice *device, uint8_t activated)
int PK_1WireStatusGetAsync (sPoKeysDevice *device, uint8_t *activated)
int PK_1WireWriteReadStartAsync (sPoKeysDevice *device, uint8_t WriteCount, uint8_t ReadCount, uint8_t *data)
int PK_1WireWriteReadStartExAsync (sPoKeysDevice *device, uint8_t pinID, uint8_t WriteCount, uint8_t ReadCount, uint8_t *data)
int PK_1WireReadStatusGetAsync (sPoKeysDevice *device, uint8_t *readStatus, uint8_t *ReadCount, uint8_t *data)
int PK_1WireBusScanStartAsync (sPoKeysDevice *device, uint8_t pinID)
int PK_1WireBusScanGetResultsAsync (sPoKeysDevice *device, uint8_t *operationStatus, uint8_t *scanResult, uint8_t *deviceROM)
int PK_1WireBusScanContinueAsync (sPoKeysDevice *device)
int PK_1WireBusScanStopAsync (sPoKeysDevice *device)
Function Documentation
PK_1WireBusScanContinueAsync()
int PK_1WireBusScanContinueAsync (sPoKeysDevice * device)
Definition at line 161 of file PoKeysLib1WireAsync.c.
References CreateRequestAsync(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_1WireBusScanGetResultsAsync()
int PK_1WireBusScanGetResultsAsync (sPoKeysDevice * device, uint8_t * operationStatus, uint8_t * scanResult, uint8_t * deviceROM)
Definition at line 145 of file PoKeysLib1WireAsync.c.
References CreateRequestAsync(), PK_CMD_ONEWIRE_COMMUNICATION, and PK_ERR_NOT_CONNECTED.
PK_1WireBusScanStartAsync()
int PK_1WireBusScanStartAsync (sPoKeysDevice * device, uint8_t pinID)
Definition at line 135 of file PoKeysLib1WireAsync.c.
References CreateRequestAsync(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_1WireBusScanStopAsync()
int PK_1WireBusScanStopAsync (sPoKeysDevice * device)
Definition at line 171 of file PoKeysLib1WireAsync.c.
References CreateRequestAsync(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_1WireReadStatusGetAsync()
int PK_1WireReadStatusGetAsync (sPoKeysDevice * device, uint8_t * readStatus, uint8_t * ReadCount, uint8_t * data)
Definition at line 119 of file PoKeysLib1WireAsync.c.
References CreateRequestAsync(), PK_CMD_ONEWIRE_COMMUNICATION, and PK_ERR_NOT_CONNECTED.
PK_1WireStatusGetAsync()
int PK_1WireStatusGetAsync (sPoKeysDevice * device, uint8_t * activated)
Definition at line 80 of file PoKeysLib1WireAsync.c.
References CreateRequestAsync(), PK_CMD_ONEWIRE_COMMUNICATION, and PK_ERR_NOT_CONNECTED.
PK_1WireStatusSetAsync()
int PK_1WireStatusSetAsync (sPoKeysDevice * device, uint8_t activated)
Definition at line 70 of file PoKeysLib1WireAsync.c.
References CreateRequestAsync(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_1WireWriteReadStartAsync()
int PK_1WireWriteReadStartAsync (sPoKeysDevice * device, uint8_t WriteCount, uint8_t ReadCount, uint8_t * data)
Definition at line 92 of file PoKeysLib1WireAsync.c.
References CreateRequestAsyncWithPayload(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().
PK_1WireWriteReadStartExAsync()
int PK_1WireWriteReadStartExAsync (sPoKeysDevice * device, uint8_t pinID, uint8_t WriteCount, uint8_t ReadCount, uint8_t * data)
Definition at line 105 of file PoKeysLib1WireAsync.c.
References CreateRequestAsyncWithPayload(), PK_CMD_ONEWIRE_COMMUNICATION, PK_ERR_NOT_CONNECTED, and SendRequestAsync().