LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibCOSM.c File Reference
PoKeysLibCOSM.c File Reference
COSM/HTTP reporting configuration (command 0xF7).
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Functions
int32_t PK_COSMSettingsGet (sPoKeysDevice *device)
Read COSM settings from the device (command 0xF7).
int32_t PK_COSMSettingsSet (sPoKeysDevice *device)
Write COSM settings to the device (command 0xF7).
Detailed Description
COSM/HTTP reporting configuration (command 0xF7).
Implements read and write operations for the COSM settings block as defined in the PoKeys protocol specification.
Definition in file PoKeysLibCOSM.c.
Function Documentation
PK_COSMSettingsGet()
int32_t PK_COSMSettingsGet (sPoKeysDevice * device)
Read COSM settings from the device (command 0xF7).
Performs operations 0..5 to retrieve basic parameters and the HTTP header pages into the device->COSM structure.
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 23 of file PoKeysLibCOSM.c.
References sPoKeysDevice::COSM, CreateRequest(), sPoKeysCOSMSettings::lastStatusCode, PK_CMD_COSM_SETTINGS, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysCOSMSettings::requestHeaders, sPoKeysCOSMSettings::requestType, sPoKeysDevice::response, SendRequest(), sPoKeysCOSMSettings::serverIP, sPoKeysCOSMSettings::serverPort, and sPoKeysCOSMSettings::updateRate.
PK_COSMSettingsSet()
int32_t PK_COSMSettingsSet (sPoKeysDevice * device)
Write COSM settings to the device (command 0xF7).
Operations 10..15 are used to send the contents of the device->COSM structure back to the device.
Parameters
device Pointer to an opened PoKeys device.
Returns
PK_OK on success or PK_ERR_* on failure.
Definition at line 57 of file PoKeysLibCOSM.c.
References sPoKeysDevice::COSM, CreateRequest(), PK_CMD_COSM_SETTINGS, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysCOSMSettings::protocolDescription, sPoKeysDevice::request, sPoKeysCOSMSettings::requestHeaders, sPoKeysCOSMSettings::requestType, SendRequest(), sPoKeysCOSMSettings::serverIP, sPoKeysCOSMSettings::serverPort, and sPoKeysCOSMSettings::updateRate.