LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/pokeys_uspace/pokeys_ini.c File Reference
pokeys_ini.c File Reference
#include "pokeys_ini.h"
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
Functions
void tolower_str (char *dst, const char *src, size_t size)
void get_pokeys_ini_path (int device_id, char *buffer, size_t size)
void set_pokeys_ini_path (const char *path)
int ini_read_int (const char *section, const char *key, int default_value)
float ini_read_float (const char *section, const char *key, float default_value)
void ini_read_string (const char *section, const char *key, char *buffer, size_t size, const char *default_value)
void ini_write_int (const char *section, const char *key, int value)
void ini_write_float (const char *section, const char *key, float value)
void ini_write_string (const char *section, const char *key, const char *value)
Variables
uint32_t device_id
bool ApplyIniSettings
Function Documentation
get_pokeys_ini_path()
void get_pokeys_ini_path (int device_id, char * buffer, size_t size)
Definition at line 22 of file pokeys_ini.c.
References device_id.
ini_read_float()
float ini_read_float (const char * section, const char * key, float default_value)
Definition at line 111 of file pokeys_ini.c.
References RTAPI_MSG_DBG, and rtapi_print_msg().
Referenced by PoKeysHALComponent::PKIO_ReadIniFile(), and PoKeysHALComponent::PKPEv2_ReadIniFile().
ini_read_int()
int ini_read_int (const char * section, const char * key, int default_value)
Definition at line 48 of file pokeys_ini.c.
References RTAPI_MSG_DBG, and rtapi_print_msg().
Referenced by PoKeysHALComponent::PKIO_ReadIniFile(), and PoKeysHALComponent::PKPEv2_ReadIniFile().
ini_read_string()
void ini_read_string (const char * section, const char * key, char * buffer, size_t size, const char * default_value)
Definition at line 174 of file pokeys_ini.c.
References RTAPI_MSG_DBG, and rtapi_print_msg().
ini_write_float()
void ini_write_float (const char * section, const char * key, float value)
Definition at line 254 of file pokeys_ini.c.
Referenced by PoKeysHALComponent::PKIO_WriteIniFile(), and PoKeysHALComponent::PKPEv2_WriteIniFile().
ini_write_int()
void ini_write_int (const char * section, const char * key, int value)
Definition at line 245 of file pokeys_ini.c.
Referenced by PoKeysHALComponent::PKIO_WriteIniFile(), and PoKeysHALComponent::PKPEv2_WriteIniFile().
ini_write_string()
void ini_write_string (const char * section, const char * key, const char * value)
Definition at line 263 of file pokeys_ini.c.
set_pokeys_ini_path()
void set_pokeys_ini_path (const char * path)
Definition at line 41 of file pokeys_ini.c.
References RTAPI_MSG_ERR, and rtapi_print_msg().
Referenced by pokeys_read_ini().
tolower_str()
void tolower_str (char * dst, const char * src, size_t size)
Definition at line 14 of file pokeys_ini.c.
References i.
Variable Documentation
ApplyIniSettings
bool ApplyIniSettings extern
Definition at line 277 of file pokeys.c.
device_id
uint32_t device_id extern
Definition at line 276 of file pokeys.c.
Referenced by get_pokeys_ini_path().