LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeyslib/PoKeysLibCoreSockets.c File Reference
PoKeysLibCoreSockets.c File Reference
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
#include <unistd.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
Macros
#define debug_printf (void)
Typedefs
typedef unsigned long uint32
Functions
uint32 * GetBroadcastAddresses ()
int32_t PK_EnumerateNetworkDevices (sPoKeysNetworkDeviceSummary *devices, uint32_t timeout)
int32_t PK_SearchNetworkDevices (sPoKeysNetworkDeviceSummary *devices, uint32_t timeout, uint32_t serialNumberToFind)
sPoKeysDevice * PK_ConnectToNetworkDevice (sPoKeysNetworkDeviceSummary *device)
void PK_DisconnectNetworkDevice (sPoKeysDevice *device)
int32_t SendEthRequest (sPoKeysDevice *device)
int32_t SendEthRequest_NoResponse (sPoKeysDevice *device)
int32_t SendEthRequestBig (sPoKeysDevice *device)
void PK_SetEthernetRetryCountAndTimeout (sPoKeysDevice *device, uint32_t sendRetries, uint32_t readRetries, uint32_t timeout)
Macro Definition Documentation
debug_printf
#define debug_printf (void)
Definition at line 48 of file PoKeysLibCoreSockets.c.
Typedef Documentation
uint32
typedef unsigned long uint32
Definition at line 53 of file PoKeysLibCoreSockets.c.
Function Documentation
GetBroadcastAddresses()
uint32 * GetBroadcastAddresses (void)
Definition at line 67 of file PoKeysLibCoreSockets.c.
References i.
Referenced by PK57i_SearchDevice(), and PK_SearchNetworkDevices().
PK_ConnectToNetworkDevice()
sPoKeysDevice * PK_ConnectToNetworkDevice (sPoKeysNetworkDeviceSummary * device)
Definition at line 437 of file PoKeysLibCoreSockets.c.
PK_DisconnectNetworkDevice()
void PK_DisconnectNetworkDevice (sPoKeysDevice * device)
Definition at line 559 of file PoKeysLibCoreSockets.c.
PK_EnumerateNetworkDevices()
int32_t PK_EnumerateNetworkDevices (sPoKeysNetworkDeviceSummary * devices, uint32_t timeout)
Definition at line 210 of file PoKeysLibCoreSockets.c.
PK_SearchNetworkDevices()
int32_t PK_SearchNetworkDevices (sPoKeysNetworkDeviceSummary * devices, uint32_t timeout, uint32_t serialNumberToFind)
Definition at line 215 of file PoKeysLibCoreSockets.c.
Referenced by PK_EnumerateNetworkDevices().
PK_SetEthernetRetryCountAndTimeout()
void PK_SetEthernetRetryCountAndTimeout (sPoKeysDevice * device, uint32_t sendRetries, uint32_t readRetries, uint32_t timeout)
Definition at line 924 of file PoKeysLibCoreSockets.c.
SendEthRequest()
int32_t SendEthRequest (sPoKeysDevice * device)
Definition at line 580 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionParam, sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), PK_ConnectionParam_UDP, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::readRetries, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, sPoKeysDevice::sendRetries, and sPoKeysDevice::socketTimeout.
Referenced by SendRequest().
SendEthRequest_NoResponse()
int32_t SendEthRequest_NoResponse (sPoKeysDevice * device)
Definition at line 717 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionParam, sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), PK_ConnectionParam_UDP, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, sPoKeysDevice::request, sPoKeysDevice::requestID, and sPoKeysDevice::sendRetries.
Referenced by SendRequest_NoResponse().
SendEthRequestBig()
int32_t SendEthRequestBig (sPoKeysDevice * device)
Definition at line 772 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionParam, sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), i, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::multiPartData, PK_ConnectionParam_UDP, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::readRetries, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, sPoKeysDevice::sendRetries, and sPoKeysDevice::socketTimeout.
Referenced by SendRequest_multiPart().