LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/pokeyslib/PoKeysLibPulseEngine_v2.c File Reference
PoKeysLibPulseEngine_v2.c File Reference
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
Functions
void PK_PEv2_DecodeStatus (sPoKeysDevice *device)
int32_t PK_PEv2_StatusGet (sPoKeysDevice *device)
int32_t PK_PEv2_Status2Get (sPoKeysDevice *device)
int32_t PK_PEv2_PulseEngineSetup (sPoKeysDevice *device)
int32_t PK_PEv2_AdditionalParametersGet (sPoKeysDevice *device)
int32_t PK_PEv2_AdditionalParametersSet (sPoKeysDevice *device)
int32_t PK_PEv2_AxisConfigurationGet (sPoKeysDevice *device)
int32_t PK_PEv2_AxisConfigurationSet (sPoKeysDevice *device)
int32_t PK_PEv2_PositionSet (sPoKeysDevice *device)
int32_t PK_PEv2_PulseEngineStateSet (sPoKeysDevice *device)
int32_t PK_PEv2_PulseEngineMove (sPoKeysDevice *device)
int32_t PK_PEv2_PulseEngineMovePV (sPoKeysDevice *device)
int32_t PK_PEv2_ExternalOutputsGet (sPoKeysDevice *device)
int32_t PK_PEv2_ExternalOutputsSet (sPoKeysDevice *device)
int32_t PK_PEv2_BufferFill (sPoKeysDevice *device)
int32_t PK_PEv2_BufferFill_16 (sPoKeysDevice *device)
int32_t PK_PEv2_BufferFillLarge (sPoKeysDevice *device)
int32_t PK_PEv2_BufferFillLarge_16 (sPoKeysDevice *device)
int32_t PK_PEv2_BufferClear (sPoKeysDevice *device)
int32_t PK_PEv2_PulseEngineReboot (sPoKeysDevice *device)
int32_t PK_PEv2_HomingStart (sPoKeysDevice *device)
int32_t PK_PEv2_HomingFinish (sPoKeysDevice *device)
int32_t PK_PEv2_ProbingStart (sPoKeysDevice *device)
int32_t PK_PEv2_ProbingHybridStart (sPoKeysDevice *device)
int32_t PK_PEv2_ProbingFinish (sPoKeysDevice *device)
int32_t PK_PEv2_ProbingFinishSimple (sPoKeysDevice *device)
int32_t PK_PEv2_ThreadingPrepareForTrigger (sPoKeysDevice *device)
int32_t PK_PEv2_ThreadingForceTriggerReady (sPoKeysDevice *device)
int32_t PK_PEv2_ThreadingTrigger (sPoKeysDevice *device)
int32_t PK_PEv2_ThreadingRelease (sPoKeysDevice *device)
int32_t PK_PEv2_ThreadingCancel (sPoKeysDevice *device)
int32_t PK_PEv2_ThreadingStatusGet (sPoKeysDevice *device)
int32_t PK_PEv2_ThreadingSetup (sPoKeysDevice *device, uint8_t sensorMode, uint16_t ticksPerRevolution, uint16_t tagetSpindleRPM, uint16_t filterGainSpeed, uint16_t filterGainPosition)
int32_t PK_PEv2_BacklashCompensationSettings_Get (sPoKeysDevice *device)
int32_t PK_PEv2_BacklashCompensationSettings_Set (sPoKeysDevice *device)
int32_t PK_PEv2_SyncedPWMSetup (sPoKeysDevice *device, uint8_t enabled, uint8_t srcAxis, uint8_t dstPWMChannel)
int32_t PK_PEv2_SyncOutputsSetup (sPoKeysDevice *device)
int32_t PK_PoStep_ConfigurationGet (sPoKeysDevice *device)
int32_t PK_PoStep_ConfigurationSet (sPoKeysDevice *device)
int32_t PK_PoStep_StatusGet (sPoKeysDevice *device)
int32_t PK_PoStep_DriverConfigurationGet (sPoKeysDevice *device)
int32_t PK_PoStep_DriverConfigurationSet (sPoKeysDevice *device)
int32_t PK_PEv2_InternalDriversConfigurationGet (sPoKeysDevice *device)
int32_t PK_PEv2_InternalDriversConfigurationSet (sPoKeysDevice *device)
Function Documentation
PK_PEv2_AdditionalParametersGet()
int32_t PK_PEv2_AdditionalParametersGet (sPoKeysDevice * device)
Definition at line 129 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::EmergencyInputPin, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_AdditionalParametersSet()
int32_t PK_PEv2_AdditionalParametersSet (sPoKeysDevice * device)
Definition at line 143 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::EmergencyInputPin, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_AxisConfigurationGet()
int32_t PK_PEv2_AxisConfigurationGet (sPoKeysDevice * device)
Definition at line 157 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxesConfig, sPoKeysPEv2::AxesSwitchConfig, sPoKeysPEv2::AxisEnableOutputPins, sPoKeysPEv2::AxisSignalOptions, CreateRequest(), sPoKeysPEv2::FilterHomeSwitch, sPoKeysPEv2::FilterLimitMSwitch, sPoKeysPEv2::FilterLimitPSwitch, sPoKeysPEv2::FilterProbeInput, sPoKeysPEv2::HomeBackOffDistance, sPoKeysPEv2::HomingAlgorithm, sPoKeysPEv2::HomingReturnSpeed, sPoKeysPEv2::HomingSpeed, sPoKeysPEv2::InvertAxisEnable, sPoKeysPEv2::MaxAcceleration, sPoKeysPEv2::MaxDecceleration, sPoKeysPEv2::MaxSpeed, sPoKeysPEv2::MPGjogDivider, sPoKeysPEv2::MPGjogEncoder, sPoKeysPEv2::MPGjogMultiplier, sPoKeysPEv2::param1, sPoKeysDevice::PEv2, sPoKeysPEv2::PinHomeSwitch, sPoKeysPEv2::PinLimitMSwitch, sPoKeysPEv2::PinLimitPSwitch, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysPEv2::SoftLimitMaximum, and sPoKeysPEv2::SoftLimitMinimum.
PK_PEv2_AxisConfigurationSet()
int32_t PK_PEv2_AxisConfigurationSet (sPoKeysDevice * device)
Definition at line 211 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxesConfig, sPoKeysPEv2::AxesSwitchConfig, sPoKeysPEv2::AxisEnableOutputPins, sPoKeysPEv2::AxisSignalOptions, CreateRequest(), sPoKeysPEv2::FilterHomeSwitch, sPoKeysPEv2::FilterLimitMSwitch, sPoKeysPEv2::FilterLimitPSwitch, sPoKeysPEv2::FilterProbeInput, sPoKeysPEv2::HomeBackOffDistance, sPoKeysPEv2::HomingAlgorithm, sPoKeysPEv2::HomingReturnSpeed, sPoKeysPEv2::HomingSpeed, sPoKeysPEv2::InvertAxisEnable, sPoKeysPEv2::MaxAcceleration, sPoKeysPEv2::MaxDecceleration, sPoKeysPEv2::MaxSpeed, sPoKeysPEv2::MPGjogDivider, sPoKeysPEv2::MPGjogEncoder, sPoKeysPEv2::MPGjogMultiplier, sPoKeysPEv2::param1, sPoKeysDevice::PEv2, sPoKeysPEv2::PinHomeSwitch, sPoKeysPEv2::PinLimitMSwitch, sPoKeysPEv2::PinLimitPSwitch, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, sPoKeysDevice::request, SendRequest(), sPoKeysPEv2::SoftLimitMaximum, and sPoKeysPEv2::SoftLimitMinimum.
PK_PEv2_BacklashCompensationSettings_Get()
int32_t PK_PEv2_BacklashCompensationSettings_Get (sPoKeysDevice * device)
Definition at line 679 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::BacklashAcceleration, sPoKeysPEv2::BacklashCompensationEnabled, sPoKeysPEv2::BacklashCompensationMaxSpeed, sPoKeysPEv2::BacklashRegister, sPoKeysPEv2::BacklashWidth, CreateRequest(), i, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_BacklashCompensationSettings_Set()
int32_t PK_PEv2_BacklashCompensationSettings_Set (sPoKeysDevice * device)
Definition at line 702 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::BacklashAcceleration, sPoKeysPEv2::BacklashCompensationEnabled, sPoKeysPEv2::BacklashCompensationMaxSpeed, sPoKeysPEv2::BacklashWidth, CreateRequest(), i, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_BufferClear()
int32_t PK_PEv2_BufferClear (sPoKeysDevice * device)
Definition at line 449 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_BufferFill()
int32_t PK_PEv2_BufferFill (sPoKeysDevice * device)
Definition at line 361 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_BufferFill_16()
int32_t PK_PEv2_BufferFill_16 (sPoKeysDevice * device)
Definition at line 385 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_BufferFillLarge()
int32_t PK_PEv2_BufferFillLarge (sPoKeysDevice * device)
Definition at line 406 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysDevice::multiPartData, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest_multiPart().
PK_PEv2_BufferFillLarge_16()
int32_t PK_PEv2_BufferFillLarge_16 (sPoKeysDevice * device)
Definition at line 427 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::MotionBuffer, sPoKeysPEv2::motionBufferEntriesAccepted, sPoKeysDevice::multiPartData, sPoKeysPEv2::newMotionBufferEntries, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest_multiPart().
PK_PEv2_DecodeStatus()
void PK_PEv2_DecodeStatus (sPoKeysDevice * device)
Definition at line 25 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxesState, sPoKeysPEv2::AxisEnabledStatesMask, sPoKeysPEv2info::bufferDepth, sPoKeysPEv2::ChargePumpEnabled, sPoKeysPEv2::CurrentPosition, sPoKeysPEv2::EmergencySwitchPolarity, sPoKeysPEv2::ErrorInputStatus, sPoKeysPEv2::HomeStatus, sPoKeysPEv2::info, sPoKeysPEv2::LimitOverride, sPoKeysPEv2::LimitStatusN, sPoKeysPEv2::LimitStatusP, sPoKeysPEv2info::maxPulseFrequency, sPoKeysPEv2::MiscInputStatus, sPoKeysPEv2info::nrOfAxes, sPoKeysDevice::PEv2, sPoKeysPEv2::PulseEngineActivated, sPoKeysPEv2::PulseEngineEnabled, sPoKeysPEv2::PulseEngineState, sPoKeysPEv2::PulseGeneratorType, sPoKeysDevice::response, sPoKeysPEv2info::slotTiming, and sPoKeysPEv2::SoftLimitStatus.
PK_PEv2_ExternalOutputsGet()
int32_t PK_PEv2_ExternalOutputsGet (sPoKeysDevice * device)
Definition at line 333 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::ExternalOCOutputs, sPoKeysPEv2::ExternalRelayOutputs, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_ExternalOutputsSet()
int32_t PK_PEv2_ExternalOutputsSet (sPoKeysDevice * device)
Definition at line 348 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::ExternalOCOutputs, sPoKeysPEv2::ExternalRelayOutputs, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_HomingFinish()
int32_t PK_PEv2_HomingFinish (sPoKeysDevice * device)
Definition at line 486 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineStateSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_HomingStart()
int32_t PK_PEv2_HomingStart (sPoKeysDevice * device)
Definition at line 472 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::HomeOffsets, sPoKeysPEv2::HomingStartMaskSetup, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_InternalDriversConfigurationGet()
int32_t PK_PEv2_InternalDriversConfigurationGet (sPoKeysDevice * device)
Definition at line 928 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::InternalDriverCurrentConfig, sPoKeysPEv2::InternalDriverStepConfig, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_InternalDriversConfigurationSet()
int32_t PK_PEv2_InternalDriversConfigurationSet (sPoKeysDevice * device)
Definition at line 948 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::InternalDriverCurrentConfig, sPoKeysPEv2::InternalDriverStepConfig, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PositionSet()
int32_t PK_PEv2_PositionSet (sPoKeysDevice * device)
Definition at line 265 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::param2, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_PARAMETER, sPoKeysPEv2::PositionSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ProbingFinish()
int32_t PK_PEv2_ProbingFinish (sPoKeysDevice * device)
Definition at line 532 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysPEv2::ProbePosition, sPoKeysPEv2::ProbeStatus, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_ProbingFinishSimple()
int32_t PK_PEv2_ProbingFinishSimple (sPoKeysDevice * device)
Definition at line 549 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysPEv2::ProbePosition, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_ProbingHybridStart()
int32_t PK_PEv2_ProbingHybridStart (sPoKeysDevice * device)
Definition at line 517 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ProbeInput, sPoKeysPEv2::ProbeInputPolarity, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ProbingStart()
int32_t PK_PEv2_ProbingStart (sPoKeysDevice * device)
Definition at line 501 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ProbeInput, sPoKeysPEv2::ProbeInputPolarity, sPoKeysPEv2::ProbeMaxPosition, sPoKeysPEv2::ProbeSpeed, sPoKeysPEv2::ProbeStartMaskSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineMove()
int32_t PK_PEv2_PulseEngineMove (sPoKeysDevice * device)
Definition at line 297 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ReferencePositionSpeed, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineMovePV()
int32_t PK_PEv2_PulseEngineMovePV (sPoKeysDevice * device)
Definition at line 312 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), i, sPoKeysPEv2::param2, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::ReferencePositionSpeed, sPoKeysPEv2::ReferenceVelocityPV, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineReboot()
int32_t PK_PEv2_PulseEngineReboot (sPoKeysDevice * device)
Definition at line 460 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineSetup()
int32_t PK_PEv2_PulseEngineSetup (sPoKeysDevice * device)
Definition at line 108 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxisEnabledStatesMask, sPoKeysPEv2::ChargePumpEnabled, CreateRequest(), sPoKeysPEv2::EmergencySwitchPolarity, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineBufferSize, sPoKeysPEv2::PulseEngineEnabled, sPoKeysPEv2::PulseGeneratorType, sPoKeysDevice::request, and SendRequest().
PK_PEv2_PulseEngineStateSet()
int32_t PK_PEv2_PulseEngineStateSet (sPoKeysDevice * device)
Definition at line 285 of file PoKeysLibPulseEngine_v2.c.
References sPoKeysPEv2::AxisEnabledMask, CreateRequest(), sPoKeysPEv2::LimitOverrideSetup, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, sPoKeysPEv2::PulseEngineStateSetup, sPoKeysDevice::request, and SendRequest().
PK_PEv2_Status2Get()
int32_t PK_PEv2_Status2Get (sPoKeysDevice * device)
Definition at line 93 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::DedicatedHomeInputs, sPoKeysPEv2::DedicatedLimitNInputs, sPoKeysPEv2::DedicatedLimitPInputs, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PEv2_StatusGet()
int32_t PK_PEv2_StatusGet (sPoKeysDevice * device)
Definition at line 64 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PEv2_DecodeStatus(), sPoKeysPEv2::PulseEngineActivated, sPoKeysPEv2::PulseEngineEnabled, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, and SendRequest().
PK_PEv2_SyncedPWMSetup()
int32_t PK_PEv2_SyncedPWMSetup (sPoKeysDevice * device, uint8_t enabled, uint8_t srcAxis, uint8_t dstPWMChannel)
Definition at line 723 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_SyncOutputsSetup()
int32_t PK_PEv2_SyncOutputsSetup (sPoKeysDevice * device)
Definition at line 736 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), sPoKeysPEv2::SyncFastOutputsAxisID, and sPoKeysPEv2::SyncFastOutputsMapping.
PK_PEv2_ThreadingCancel()
int32_t PK_PEv2_ThreadingCancel (sPoKeysDevice * device)
Definition at line 617 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingForceTriggerReady()
int32_t PK_PEv2_ThreadingForceTriggerReady (sPoKeysDevice * device)
Definition at line 578 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingPrepareForTrigger()
int32_t PK_PEv2_ThreadingPrepareForTrigger (sPoKeysDevice * device)
Definition at line 565 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingRelease()
int32_t PK_PEv2_ThreadingRelease (sPoKeysDevice * device)
Definition at line 604 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PEv2_ThreadingSetup()
int32_t PK_PEv2_ThreadingSetup (sPoKeysDevice * device, uint8_t sensorMode, uint16_t ticksPerRevolution, uint16_t tagetSpindleRPM, uint16_t filterGainSpeed, uint16_t filterGainPosition)
Definition at line 659 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, SendRequest(), and sPoKeysPEv2::TriggerIngnoredAxisMask.
PK_PEv2_ThreadingStatusGet()
int32_t PK_PEv2_ThreadingStatusGet (sPoKeysDevice * device)
Definition at line 630 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPEv2::DebugValues, sPoKeysDevice::PEv2, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoKeysPEv2::spindleIndexCounter, sPoKeysPEv2::SpindlePositionError, sPoKeysPEv2::SpindleRPM, sPoKeysPEv2::SpindleSpeedEstimate, sPoKeysPEv2::TriggerActive, sPoKeysPEv2::TriggerIngnoredAxisMask, sPoKeysPEv2::TriggerPending, sPoKeysPEv2::TriggerPrepared, and sPoKeysPEv2::TriggerPreparing.
PK_PEv2_ThreadingTrigger()
int32_t PK_PEv2_ThreadingTrigger (sPoKeysDevice * device)
Definition at line 591 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PoStep_ConfigurationGet()
int32_t PK_PoStep_ConfigurationGet (sPoKeysDevice * device)
Definition at line 750 of file PoKeysLibPulseEngine_v2.c.
References sPoPoStepDriverConfig::AddressI2C, CreateRequest(), sPoKeysPoStepInterface::drivers, sPoPoStepDriverConfig::DriverType, sPoKeysPoStepInterface::EnablePoStepCommunication, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), and sPoPoStepDriverConfig::UpdateConfig.
PK_PoStep_ConfigurationSet()
int32_t PK_PoStep_ConfigurationSet (sPoKeysDevice * device)
Definition at line 773 of file PoKeysLibPulseEngine_v2.c.
References sPoPoStepDriverConfig::AddressI2C, CreateRequest(), sPoKeysPoStepInterface::drivers, sPoPoStepDriverConfig::DriverType, sPoKeysPoStepInterface::EnablePoStepCommunication, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), and sPoPoStepDriverConfig::UpdateConfig.
PK_PoStep_DriverConfigurationGet()
int32_t PK_PoStep_DriverConfigurationGet (sPoKeysDevice * device)
Definition at line 831 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoPoStepDriverConfig::Current_FS, sPoPoStepDriverConfig::Current_Idle, sPoPoStepDriverConfig::Current_Overheat, sPoPoStepDriverConfig::DriverMode, sPoKeysPoStepInterface::drivers, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoPoStepDriverConfig::StepMode, and sPoPoStepDriverConfig::TemperatureLimit.
PK_PoStep_DriverConfigurationSet()
int32_t PK_PoStep_DriverConfigurationSet (sPoKeysDevice * device)
Definition at line 870 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoPoStepDriverConfig::Current_FS, sPoPoStepDriverConfig::Current_Idle, sPoPoStepDriverConfig::Current_Overheat, sPoPoStepDriverConfig::DriverMode, sPoKeysPoStepInterface::drivers, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoPoStepDriverConfig::StepMode, and sPoPoStepDriverConfig::TemperatureLimit.
PK_PoStep_StatusGet()
int32_t PK_PoStep_StatusGet (sPoKeysDevice * device)
Definition at line 805 of file PoKeysLibPulseEngine_v2.c.
References CreateRequest(), sPoKeysPoStepInterface::drivers, sPoPoStepDriverConfig::DriverStatus, sPoPoStepDriverConfig::FaultStatus, i, sPoPoStepDriverConfig::InputStatus, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoSteps, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoPoStepDriverConfig::SupplyVoltage, sPoPoStepDriverConfig::Temperature, and sPoPoStepDriverConfig::UpdateState.