LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/experimental/pokeys_async2.c File Reference
pokeys_async2.c File Reference
#include "rtapi.h"
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"
#include <unistd.h>
#include "PoKeysLibHal.h"
Data Structures
struct __comp_state
PoKeys component state.
Macros
#define TRUE (1)
#define FALSE (0)
#define true (1)
#define false (0)
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#define fperiod (period * 1e-9)
#define in(i) (*(__comp_inst->in[i]))
#define ain(i) (*(__comp_inst->ain[i]))
#define err (*__comp_inst->err)
#define devSerial (0+*__comp_inst->devSerial)
#define alive (*__comp_inst->alive)
Functions
RTAPI_MP_INT (count, "number of pokeys_async2")
RTAPI_MP_STRING (names, "names of pokeys_async2")
int rtapi_app_main (void)
void rtapi_app_exit (void)
void user_mainloop (void)
FUNCTION (_)
Variables
struct __comp_state * __comp_first_inst =0
struct __comp_state * __comp_last_inst =0
char * names = ""
sPoKeysDevice * dev =0
int i =0
Macro Definition Documentation
ain
#define ain (i) (*(__comp_inst->ain[i]))
Definition at line 148 of file pokeys_async2.c.
alive
#define alive (*__comp_inst->alive)
Definition at line 154 of file pokeys_async2.c.
devSerial
#define devSerial (0+*__comp_inst->devSerial)
Definition at line 152 of file pokeys_async2.c.
err
#define err (*__comp_inst->err)
Definition at line 150 of file pokeys_async2.c.
EXTRA_CLEANUP
#define EXTRA_CLEANUP () static void extra_cleanup(void)
Definition at line 142 of file pokeys_async2.c.
EXTRA_SETUP
#define EXTRA_SETUP () static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
Definition at line 140 of file pokeys_async2.c.
FALSE
#define FALSE (0)
Definition at line 41 of file pokeys_async2.c.
false
#define false (0)
Definition at line 45 of file pokeys_async2.c.
fperiod
#define fperiod (period * 1e-9)
Definition at line 144 of file pokeys_async2.c.
FUNCTION
#define FUNCTION (name) static void name(struct __comp_state *__comp_inst, long period)
Definition at line 138 of file pokeys_async2.c.
in
#define in (i) (*(__comp_inst->in[i]))
Definition at line 146 of file pokeys_async2.c.
TRUE
#define TRUE (1)
Definition at line 39 of file pokeys_async2.c.
true
#define true (1)
Definition at line 43 of file pokeys_async2.c.
Function Documentation
FUNCTION()
FUNCTION (_)
Definition at line 208 of file pokeys_async2.c.
References PK_OK, PK_ReceiveAndDispatch(), PK_RTCGet(), PK_RTCGetAsync(), PK_TimeoutAndRetryCheck(), RTAPI_MSG_ERR, and rtapi_print_msg().
rtapi_app_exit()
void rtapi_app_exit (void)
Definition at line 133 of file pokeys_async2.c.
References hal_exit().
rtapi_app_main()
int rtapi_app_main (void)
Definition at line 85 of file pokeys_async2.c.
References i.
RTAPI_MP_INT()
RTAPI_MP_INT (count , "number of pokeys_async2")
RTAPI_MP_STRING()
RTAPI_MP_STRING (names , "names of pokeys_async2")
user_mainloop()
void user_mainloop (void)
Definition at line 165 of file pokeys_async2.c.
References alive, FOR_ALL_INSTS, PK_OK, PK_ReceiveAndDispatch(), PK_RTCGet(), PK_RTCGetAsync(), PK_TimeoutAndRetryCheck(), RTAPI_MSG_ERR, and rtapi_print_msg().
Referenced by main().
Variable Documentation
__comp_first_inst
struct __comp_state* __comp_first_inst =0
Definition at line 34 of file pokeys_async2.c.
__comp_last_inst
struct __comp_state * __comp_last_inst =0
Definition at line 34 of file pokeys_async2.c.
dev
sPoKeysDevice* dev =0
Definition at line 162 of file pokeys_async2.c.
i
int i =0
Definition at line 163 of file pokeys_async2.c.
Referenced by rtapi_app_main().
names
char* names = ""
Definition at line 83 of file pokeys_async2.c.