LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibSecurityAsync.c File Reference
PoKeysLibSecurityAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Data Structures
struct SecurityAsyncContext
Functions
int PK_SecurityStatusGetAsync (sPoKeysDevice *device, uint8_t *level, uint8_t *seed)
int PK_UserAuthoriseAsync (sPoKeysDevice *device, uint8_t level, const uint8_t *hash, uint8_t *status)
int PK_UserPasswordSetAsync (sPoKeysDevice *device, uint8_t defaultLevel, const uint8_t *password)
Function Documentation
PK_SecurityStatusGetAsync()
int PK_SecurityStatusGetAsync (sPoKeysDevice * device, uint8_t * level, uint8_t * seed)
Definition at line 36 of file PoKeysLibSecurityAsync.c.
References CreateRequestAsync(), PK_CMD_SECURITY_STATUS_GET, and PK_ERR_NOT_CONNECTED.
PK_UserAuthoriseAsync()
int PK_UserAuthoriseAsync (sPoKeysDevice * device, uint8_t level, const uint8_t * hash, uint8_t * status)
Definition at line 47 of file PoKeysLibSecurityAsync.c.
References CreateRequestAsyncWithPayload(), PK_CMD_USER_AUTHORISE, and PK_ERR_NOT_CONNECTED.
PK_UserPasswordSetAsync()
int PK_UserPasswordSetAsync (sPoKeysDevice * device, uint8_t defaultLevel, const uint8_t * password)
Definition at line 58 of file PoKeysLibSecurityAsync.c.
References CreateRequestAsyncWithPayload(), PK_CMD_USER_PASSWORD_SET, PK_ERR_NOT_CONNECTED, and SendRequestAsync().