LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeyslib/PoKeysLibCore.c File Reference
PoKeysLibCore.c File Reference
#include <stdlib.h>
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibCoreSockets.h"
#include "string.h"
#include "stdio.h"
Functions
int32_t PKI_CheckInterface (struct hid_device_info *devInfo)
int32_t PK_EnumerateUSBDevices ()
int32_t PK_GetCurrentDeviceConnectionType (sPoKeysDevice *device)
void InitializeNewDevice (sPoKeysDevice *device)
void CleanDevice (sPoKeysDevice *device)
void PK_ReleaseDeviceStructure (sPoKeysDevice *device)
void PK_CloneDeviceStructure (sPoKeysDevice *original, sPoKeysDevice *destination)
void * PK_FastUSBConnectToDevice (uint32_t deviceIndex)
sPoKeysDevice * PK_ConnectToDevice (uint32_t deviceIndex)
sPoKeysDevice * PK_ConnectToPoKeysDevice_USB (uint32_t serialNumber, uint32_t flags)
sPoKeysDevice * PK_ConnectToPoKeysDevice_Ethernet (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
sPoKeysDevice * PK_ConnectToPoKeysDevice (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
sPoKeysDevice * PK_ConnectToDeviceWSerial (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
sPoKeysDevice * PK_ConnectToDeviceWSerial_UDP (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
void PK_DisconnectDevice (sPoKeysDevice *device)
int32_t CreateRequest (unsigned char *request, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
int32_t PK_CustomRequest (sPoKeysDevice *device, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
uint8_t getChecksum (uint8_t *data)
int32_t SendRequest_multiPart (sPoKeysDevice *device)
int32_t SendRequest (sPoKeysDevice *device)
int32_t SendRequest_NoResponse (sPoKeysDevice *device)
void PK_SL_SetPinFunction (sPoKeysDevice *device, uint8_t pin, uint8_t function)
uint8_t PK_SL_GetPinFunction (sPoKeysDevice *device, uint8_t pin)
void PK_SL_DigitalOutputSet (sPoKeysDevice *device, uint8_t pin, uint8_t value)
uint8_t PK_SL_DigitalInputGet (sPoKeysDevice *device, uint8_t pin)
uint32_t PK_SL_AnalogInputGet (sPoKeysDevice *device, uint8_t pin)
Variables
int32_t LastRetryCount = 0
int32_t LastWaitCount = 0
Function Documentation
CleanDevice()
void CleanDevice (sPoKeysDevice * device)
Definition at line 187 of file PoKeysLibCore.c.
References sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::MatrixLED, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, sPoKeysDevice::Pins, sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMpinIDs.
Referenced by PK_ConnectToPoKeysDevice_USB(), PK_DisconnectDevice(), and PK_ReleaseDeviceStructure().
CreateRequest()
int32_t CreateRequest (uint8_t * request, uint8_t type, uint8_t param1, uint8_t param2, uint8_t param3, uint8_t param4)
Compose a command packet.
Parameters
request 64 byte buffer to populate.
type Command ID (PK_CMD_* constant).
param1 First parameter.
param2 Second parameter.
param3 Third parameter.
param4 Fourth parameter.
Returns
PK_OK on success or PK_ERR_NOT_CONNECTED when request is NULL.
Definition at line 647 of file PoKeysLibCore.c.
References PK_ERR_NOT_CONNECTED, and PK_OK.
Referenced by PK57i_Update(), PK_1WireBusScanContinue(), PK_1WireBusScanGetResults(), PK_1WireBusScanStart(), PK_1WireBusScanStop(), PK_1WireReadStatusGet(), PK_1WireStatusGet(), PK_1WireStatusSet(), PK_1WireWriteReadStart(), PK_1WireWriteReadStartEx(), PK_AnalogIOGet(), PK_AnalogRCFilterGet(), PK_AnalogRCFilterSet(), PK_CANConfigure(), PK_CANFlush(), PK_CANRead(), PK_CANRegisterFilter(), PK_CANWrite(), PK_ClearConfiguration(), PK_COSMSettingsGet(), PK_COSMSettingsSet(), PK_DeviceActivation(), PK_DeviceActivationClear(), PK_DeviceDataGet(), PK_DeviceNameSet(), PK_DigitalCounterClear(), PK_DigitalCounterGet(), PK_DigitalIOGet(), PK_DigitalIOGetSingle(), PK_DigitalIOSet(), PK_DigitalIOSetGet(), PK_DigitalIOSetSingle(), PK_EasySensorsSetupGet(), PK_EasySensorsSetupSet(), PK_EasySensorsValueGetAll(), PK_EncoderConfigurationGet(), PK_EncoderConfigurationSet(), PK_EncoderValuesGet(), PK_EncoderValuesSet(), PK_FailsafeSettingsGet(), PK_FailsafeSettingsSet(), PK_GetDebugValues(), PK_GetFastUSBEnableStatus(), PK_I2CBusScanGetResults(), PK_I2CBusScanStart(), PK_I2CGetStatus(), PK_I2CReadStart(), PK_I2CReadStatusGet(), PK_I2CSetStatus(), PK_I2CWriteAndReadStart(), PK_I2CWriteStart(), PK_I2CWriteStatusGet(), PK_LCDChangeMode(), PK_LCDClear(), PK_LCDConfigurationGet(), PK_LCDConfigurationSet(), PK_LCDDisplayOnOffControl(), PK_LCDEntryModeSet(), PK_LCDInit(), PK_LCDMoveCursor(), PK_LCDPrint(), PK_LCDPutChar(), PK_LCDSetCustomCharacters(), PK_LCDUpdate(), PK_MatrixKBConfigurationGet(), PK_MatrixKBConfigurationSet(), PK_MatrixKBStatusGet(), PK_MatrixLEDConfigurationGet(), PK_MatrixLEDConfigurationSet(), PK_MatrixLEDUpdate(), PK_NetworkConfigurationSet(), PK_PEv2_AdditionalParametersGet(), PK_PEv2_AdditionalParametersSet(), PK_PEv2_AxisConfigurationGet(), PK_PEv2_AxisConfigurationSet(), PK_PEv2_BacklashCompensationSettings_Get(), PK_PEv2_BacklashCompensationSettings_Set(), PK_PEv2_BufferClear(), PK_PEv2_BufferFill(), PK_PEv2_BufferFill_16(), PK_PEv2_BufferFillLarge(), PK_PEv2_BufferFillLarge_16(), PK_PEv2_ExternalOutputsGet(), PK_PEv2_ExternalOutputsSet(), PK_PEv2_HomingFinish(), PK_PEv2_HomingStart(), PK_PEv2_InternalDriversConfigurationGet(), PK_PEv2_InternalDriversConfigurationSet(), PK_PEv2_PositionSet(), PK_PEv2_ProbingFinish(), PK_PEv2_ProbingFinishSimple(), PK_PEv2_ProbingHybridStart(), PK_PEv2_ProbingStart(), PK_PEv2_PulseEngineMove(), PK_PEv2_PulseEngineMovePV(), PK_PEv2_PulseEngineReboot(), PK_PEv2_PulseEngineSetup(), PK_PEv2_PulseEngineStateSet(), PK_PEv2_Status2Get(), PK_PEv2_StatusGet(), PK_PEv2_SyncedPWMSetup(), PK_PEv2_SyncOutputsSetup(), PK_PEv2_ThreadingCancel(), PK_PEv2_ThreadingForceTriggerReady(), PK_PEv2_ThreadingPrepareForTrigger(), PK_PEv2_ThreadingRelease(), PK_PEv2_ThreadingSetup(), PK_PEv2_ThreadingStatusGet(), PK_PEv2_ThreadingTrigger(), PK_PinConfigurationGet(), PK_PinConfigurationSet(), PK_PoExtBusGet(), PK_PoExtBusSet(), PK_PoILChunkReadMemory(), PK_PoILChunkReadMemoryInternalAddress(), PK_PoILEraseMemory(), PK_PoILGetState(), PK_PoILReadMemory(), PK_PoILReadSharedSlot(), PK_PoILResetCore(), PK_PoILSetCoreState(), PK_PoILSetDebugMode(), PK_PoILSetMasterEnable(), PK_PoILTaskStatus(), PK_PoILWriteMemory(), PK_PoILWriteSharedSlot(), PK_PoNETGetModuleLight(), PK_PoNETGetModuleLightRequest(), PK_PoNETGetModuleSettings(), PK_PoNETGetModuleStatus(), PK_PoNETGetModuleStatusRequest(), PK_PoNETGetPoNETStatus(), PK_PoNETSetModulePWM(), PK_PoNETSetModuleStatus(), PK_PoStep_ConfigurationGet(), PK_PoStep_ConfigurationSet(), PK_PoStep_DriverConfigurationGet(), PK_PoStep_DriverConfigurationSet(), PK_PoStep_StatusGet(), PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), PK_PWMUpdate(), PK_ReadDeviceLog(), PK_RTCGet(), PK_RTCSet(), PK_SaveConfiguration(), PK_SecurityStatusGet(), PK_SetFastUSBEnableStatus(), PK_SPIConfigure(), PK_SPIRead(), PK_SPIWrite(), PK_UARTConfigure(), PK_UARTRead(), PK_UARTWrite(), PK_UserAuthorise(), PK_UserPasswordSet(), PK_WS2812_SendLEDdataEx(), and PK_WS2812_Update().
getChecksum()
uint8_t getChecksum (uint8_t * data)
Definition at line 673 of file PoKeysLibCore.c.
References i.
Referenced by SendEthRequest(), SendEthRequest_NoResponse(), SendEthRequestBig(), SendRequest(), and SendRequest_NoResponse().
InitializeNewDevice()
void InitializeNewDevice (sPoKeysDevice * device)
Definition at line 89 of file PoKeysLibCore.c.
References sPoKeysDevice::DeviceData, sPoKeysPinData::DigitalCounterAvailable, sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice::LCD, sPoKeysDevice::matrixKB, sPoKeysDevice::MatrixLED, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, sPoKeysDevice::PEv2, sPoKeysDevice::Pins, PK_DeviceDataGet(), PK_FillPWMPinNumbers(), PK_IsCounterAvailable(), sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMpinIDs, sPoKeysDevice::readRetries, sPoKeysDevice::request, sPoKeysDevice::response, sPoKeysDevice::sendRetries, sPoKeysDevice::socketTimeout, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
Referenced by PK_ConnectToDevice(), PK_ConnectToNetworkDevice(), PK_ConnectToPoKeysDevice_Ethernet(), and PK_ConnectToPoKeysDevice_USB().
PK_CloneDeviceStructure()
void PK_CloneDeviceStructure (sPoKeysDevice * original, sPoKeysDevice * destination)
Definition at line 228 of file PoKeysLibCore.c.
PK_ConnectToDevice()
sPoKeysDevice * PK_ConnectToDevice (uint32_t deviceIndex)
Definition at line 312 of file PoKeysLibCore.c.
PK_ConnectToDeviceWSerial()
sPoKeysDevice * PK_ConnectToDeviceWSerial (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
Definition at line 611 of file PoKeysLibCore.c.
PK_ConnectToDeviceWSerial_UDP()
sPoKeysDevice * PK_ConnectToDeviceWSerial_UDP (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
Definition at line 616 of file PoKeysLibCore.c.
PK_ConnectToPoKeysDevice()
sPoKeysDevice * PK_ConnectToPoKeysDevice (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
Definition at line 587 of file PoKeysLibCore.c.
Referenced by PK_ConnectToDeviceWSerial(), and PK_ConnectToDeviceWSerial_UDP().
PK_ConnectToPoKeysDevice_Ethernet()
sPoKeysDevice * PK_ConnectToPoKeysDevice_Ethernet (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
Definition at line 541 of file PoKeysLibCore.c.
References InitializeNewDevice(), PK_ConnectToNetworkDevice(), PK_SearchNetworkDevices(), and sPoKeysNetworkDeviceSummary::useUDP.
Referenced by PK_ConnectToPoKeysDevice().
PK_ConnectToPoKeysDevice_USB()
sPoKeysDevice * PK_ConnectToPoKeysDevice_USB (uint32_t serialNumber, uint32_t flags)
Definition at line 413 of file PoKeysLibCore.c.
References CleanDevice(), sPoKeysDevice::connectionType, ConnectToFastUSBInterface, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, sPoKeysDevice::DeviceData, hid_enumerate(), hid_free_enumeration(), hid_open_path(), InitializeNewDevice(), hid_device_info::interface_number, hid_device_info::next, hid_device_info::path, PK_DeviceType_FastUSBDevice, PK_DeviceType_USBDevice, hid_device_info::serial_number, and sPoKeysDevice_Data::SerialNumber.
Referenced by PK_ConnectToPoKeysDevice().
PK_CustomRequest()
int32_t PK_CustomRequest (sPoKeysDevice * device, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Send a custom command to the device.
The parameters are encoded into the request buffer as described for CreateRequest() and the command is executed immediately.
Parameters
device Target device structure.
type Command ID.
param1 First parameter.
param2 Second parameter.
param3 Third parameter.
param4 Fourth parameter.
Returns
Result code from SendRequest().
Definition at line 662 of file PoKeysLibCore.c.
PK_DisconnectDevice()
void PK_DisconnectDevice (sPoKeysDevice * device)
Definition at line 621 of file PoKeysLibCore.c.
PK_EnumerateUSBDevices()
int32_t PK_EnumerateUSBDevices (void)
Enumerate PoKeys USB devices using HIDAPI.
The function scans vendor ID 0x1DC3 and product IDs 0x1001 and 0x1002 and counts interfaces for which PKI_CheckInterface() reports a communication channel.
Returns
Number of PoKeys HID devices detected.
Definition at line 38 of file PoKeysLibCore.c.
PK_FastUSBConnectToDevice()
void * PK_FastUSBConnectToDevice (uint32_t deviceIndex)
Referenced by PK_ConnectToDevice().
PK_GetCurrentDeviceConnectionType()
int32_t PK_GetCurrentDeviceConnectionType (sPoKeysDevice * device)
Get the currently used connection type.
The value returned corresponds to ePK_DeviceConnectionType and indicates whether communication is performed over USB, network or the fast USB interface.
Parameters
device Target device instance.
Returns
Connection type constant.
Definition at line 84 of file PoKeysLibCore.c.
PK_ReleaseDeviceStructure()
void PK_ReleaseDeviceStructure (sPoKeysDevice * device)
Definition at line 223 of file PoKeysLibCore.c.
PK_SL_AnalogInputGet()
uint32_t PK_SL_AnalogInputGet (sPoKeysDevice * device, uint8_t pin)
Definition at line 897 of file PoKeysLibCore.c.
PK_SL_DigitalInputGet()
uint8_t PK_SL_DigitalInputGet (sPoKeysDevice * device, uint8_t pin)
Definition at line 892 of file PoKeysLibCore.c.
PK_SL_DigitalOutputSet()
void PK_SL_DigitalOutputSet (sPoKeysDevice * device, uint8_t pin, uint8_t value)
Definition at line 887 of file PoKeysLibCore.c.
PK_SL_GetPinFunction()
uint8_t PK_SL_GetPinFunction (sPoKeysDevice * device, uint8_t pin)
Definition at line 882 of file PoKeysLibCore.c.
PK_SL_SetPinFunction()
void PK_SL_SetPinFunction (sPoKeysDevice * device, uint8_t pin, uint8_t function)
Definition at line 877 of file PoKeysLibCore.c.
PKI_CheckInterface()
int32_t PKI_CheckInterface (struct hid_device_info * devInfo)
Definition at line 29 of file PoKeysLibCore.c.
References hid_device_info::interface_number.
Referenced by PK_EnumerateUSBDevices(), and PK_EnumerateUSBDevicesAsync().
SendRequest()
int32_t SendRequest (sPoKeysDevice * device)
Send a prepared request and wait for the response.
Definition at line 712 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, getChecksum(), hid_read(), hid_write(), i, LastRetryCount, LastWaitCount, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, SendEthRequest(), and SendRequestFastUSB.
Referenced by PK57i_Update(), PK_1WireBusScanContinue(), PK_1WireBusScanGetResults(), PK_1WireBusScanStart(), PK_1WireBusScanStop(), PK_1WireReadStatusGet(), PK_1WireStatusGet(), PK_1WireStatusSet(), PK_1WireWriteReadStart(), PK_1WireWriteReadStartEx(), PK_AnalogIOGet(), PK_AnalogRCFilterGet(), PK_AnalogRCFilterSet(), PK_CANConfigure(), PK_CANFlush(), PK_CANRead(), PK_CANRegisterFilter(), PK_CANWrite(), PK_ClearConfiguration(), PK_COSMSettingsGet(), PK_COSMSettingsSet(), PK_CustomRequest(), PK_DeviceActivation(), PK_DeviceActivationClear(), PK_DeviceDataGet(), PK_DeviceNameSet(), PK_DigitalCounterClear(), PK_DigitalCounterGet(), PK_DigitalIOGet(), PK_DigitalIOGetSingle(), PK_DigitalIOSet(), PK_DigitalIOSetGet(), PK_DigitalIOSetSingle(), PK_EasySensorsSetupGet(), PK_EasySensorsSetupSet(), PK_EasySensorsValueGetAll(), PK_EncoderConfigurationGet(), PK_EncoderConfigurationSet(), PK_EncoderValuesGet(), PK_EncoderValuesSet(), PK_FailsafeSettingsGet(), PK_FailsafeSettingsSet(), PK_GetDebugValues(), PK_GetFastUSBEnableStatus(), PK_I2CBusScanGetResults(), PK_I2CBusScanStart(), PK_I2CGetStatus(), PK_I2CReadStart(), PK_I2CReadStatusGet(), PK_I2CSetStatus(), PK_I2CWriteAndReadStart(), PK_I2CWriteStart(), PK_I2CWriteStatusGet(), PK_LCDChangeMode(), PK_LCDClear(), PK_LCDConfigurationGet(), PK_LCDConfigurationSet(), PK_LCDDisplayOnOffControl(), PK_LCDEntryModeSet(), PK_LCDInit(), PK_LCDMoveCursor(), PK_LCDPrint(), PK_LCDPutChar(), PK_LCDSetCustomCharacters(), PK_LCDUpdate(), PK_MatrixKBConfigurationGet(), PK_MatrixKBConfigurationSet(), PK_MatrixKBStatusGet(), PK_MatrixLEDConfigurationGet(), PK_MatrixLEDConfigurationSet(), PK_MatrixLEDUpdate(), PK_NetworkConfigurationSet(), PK_PEv2_AdditionalParametersGet(), PK_PEv2_AdditionalParametersSet(), PK_PEv2_AxisConfigurationGet(), PK_PEv2_AxisConfigurationSet(), PK_PEv2_BacklashCompensationSettings_Get(), PK_PEv2_BacklashCompensationSettings_Set(), PK_PEv2_BufferClear(), PK_PEv2_BufferFill(), PK_PEv2_BufferFill_16(), PK_PEv2_ExternalOutputsGet(), PK_PEv2_ExternalOutputsSet(), PK_PEv2_HomingFinish(), PK_PEv2_HomingStart(), PK_PEv2_InternalDriversConfigurationGet(), PK_PEv2_InternalDriversConfigurationSet(), PK_PEv2_PositionSet(), PK_PEv2_ProbingFinish(), PK_PEv2_ProbingFinishSimple(), PK_PEv2_ProbingHybridStart(), PK_PEv2_ProbingStart(), PK_PEv2_PulseEngineMove(), PK_PEv2_PulseEngineMovePV(), PK_PEv2_PulseEngineReboot(), PK_PEv2_PulseEngineSetup(), PK_PEv2_PulseEngineStateSet(), PK_PEv2_Status2Get(), PK_PEv2_StatusGet(), PK_PEv2_SyncedPWMSetup(), PK_PEv2_SyncOutputsSetup(), PK_PEv2_ThreadingCancel(), PK_PEv2_ThreadingForceTriggerReady(), PK_PEv2_ThreadingPrepareForTrigger(), PK_PEv2_ThreadingRelease(), PK_PEv2_ThreadingSetup(), PK_PEv2_ThreadingStatusGet(), PK_PEv2_ThreadingTrigger(), PK_PinConfigurationGet(), PK_PinConfigurationSet(), PK_PoExtBusGet(), PK_PoExtBusSet(), PK_PoILChunkReadMemory(), PK_PoILChunkReadMemoryInternalAddress(), PK_PoILEraseMemory(), PK_PoILGetState(), PK_PoILReadMemory(), PK_PoILReadSharedSlot(), PK_PoILResetCore(), PK_PoILSetCoreState(), PK_PoILSetDebugMode(), PK_PoILSetMasterEnable(), PK_PoILTaskStatus(), PK_PoILWriteMemory(), PK_PoILWriteSharedSlot(), PK_PoNETGetModuleLight(), PK_PoNETGetModuleLightRequest(), PK_PoNETGetModuleSettings(), PK_PoNETGetModuleStatus(), PK_PoNETGetModuleStatusRequest(), PK_PoNETGetPoNETStatus(), PK_PoNETSetModulePWM(), PK_PoNETSetModuleStatus(), PK_PoStep_ConfigurationGet(), PK_PoStep_ConfigurationSet(), PK_PoStep_DriverConfigurationGet(), PK_PoStep_DriverConfigurationSet(), PK_PoStep_StatusGet(), PK_PWMConfigurationGet(), PK_PWMConfigurationSet(), PK_PWMUpdate(), PK_ReadDeviceLog(), PK_RTCGet(), PK_RTCSet(), PK_SaveConfiguration(), PK_SecurityStatusGet(), PK_SetFastUSBEnableStatus(), PK_SPIConfigure(), PK_SPIRead(), PK_SPIWrite(), PK_UARTConfigure(), PK_UARTRead(), PK_UARTWrite(), PK_UserAuthorise(), PK_UserPasswordSet(), and PK_WS2812_Update().
SendRequest_multiPart()
int32_t SendRequest_multiPart (sPoKeysDevice * device)
Send a multipart (PK_CMD_MULTIPART_PACKET) request.
Definition at line 690 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, SendEthRequestBig(), and SendRequestFastUSB_multiPart.
Referenced by PK_PEv2_BufferFillLarge(), and PK_PEv2_BufferFillLarge_16().
SendRequest_NoResponse()
int32_t SendRequest_NoResponse (sPoKeysDevice * device)
Send a request without waiting for a reply.
Definition at line 811 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, getChecksum(), hid_write(), i, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, sPoKeysDevice::request, sPoKeysDevice::requestID, and SendEthRequest_NoResponse().
Referenced by PK_WS2812_SendLEDdataEx().
Variable Documentation
LastRetryCount
int32_t LastRetryCount = 0
Definition at line 685 of file PoKeysLibCore.c.
Referenced by SendRequest().
LastWaitCount
int32_t LastWaitCount = 0
Definition at line 686 of file PoKeysLibCore.c.
Referenced by SendRequest().