LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibPoIL.c File Reference
PoKeysLibPoIL.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
Functions
void PK_ParsePoILStateResponse (sPoKeysDevice *device)
int32_t PK_PoILGetState (sPoKeysDevice *device)
int32_t PK_PoILSetCoreState (sPoKeysDevice *device, uint16_t state)
int32_t PK_PoILSetMasterEnable (sPoKeysDevice *device, uint8_t masterEnable)
int32_t PK_PoILResetCore (sPoKeysDevice *device)
int32_t PK_PoILSetDebugMode (sPoKeysDevice *device, uint8_t debugMode, uint16_t breakpoint)
int32_t PK_PoILReadMemory (sPoKeysDevice *device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t *dest)
int32_t PK_PoILWriteMemory (sPoKeysDevice *device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t *src)
int32_t PK_PoILReadSharedSlot (sPoKeysDevice *device, uint16_t firstSlotID, uint16_t slotsNum, int *dest)
int32_t PK_PoILWriteSharedSlot (sPoKeysDevice *device, uint16_t firstSlotID, uint16_t slotsNum, int32_t *src)
int32_t PK_PoILEraseMemory (sPoKeysDevice *device, uint8_t memoryType)
int32_t PK_PoILChunkReadMemory (sPoKeysDevice *device, uint8_t *dest)
int32_t PK_PoILChunkReadMemoryInternalAddress (sPoKeysDevice *device, uint8_t *dest)
int32_t PK_PoILTaskStatus (sPoKeysDevice *device)
Function Documentation
PK_ParsePoILStateResponse()
void PK_ParsePoILStateResponse (sPoKeysDevice * device)
Decode interpreter state response into the device structure.
The function expects that device->response already holds data returned by the PK_CMD_POIL_OPERATIONS command. It parses the contents and updates the sPoKeysDevice::PoIL fields accordingly.
Parameters
device Pointer to an initialized device structure that received the response.
Definition at line 34 of file PoKeysLibPoIL.c.
References sPoILinfo::CodeMemorySize, sPoILStatus::CoreDebugBreakpoint, sPoILStatus::CoreDebugMode, sPoILStatus::CoreState, sPoILStatus::currentTask, sPoILinfo::DataMemorySize, sPoILStatus::dataStack, sPoILStatus::ExceptionDescription, sPoILStatus::ExceptionLocation, sPoILStatus::ExceptionPC, sPoILStatus::functionStack, sPoILStatus::info, sPoILStatus::MasterEnable, sPoILStatus::PC, sPoKeysDevice::PoIL, sPoKeysDevice::response, sPoILStack::stackPtr, sPoILStatus::STATUS, sPoILStatus::taskCount, sPoILinfo::Version, and sPoILStatus::W.
PK_PoILChunkReadMemory()
int32_t PK_PoILChunkReadMemory (sPoKeysDevice * device, uint8_t * dest)
Read a set of preconfigured memory chunks.
Definition at line 306 of file PoKeysLibPoIL.c.
References sPoILmemoryChunk::address, sPoILmemoryChunk::chunkLength, CreateRequest(), i, sPoILStatus::monitorChunks, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoIL, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoILChunkReadMemoryInternalAddress()
int32_t PK_PoILChunkReadMemoryInternalAddress (sPoKeysDevice * device, uint8_t * dest)
Read memory monitor chunks using internal addresses.
Definition at line 334 of file PoKeysLibPoIL.c.
References sPoILmemoryChunk::address, sPoILmemoryChunk::chunkLength, CreateRequest(), i, sPoILStatus::monitorChunks, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoIL, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoILEraseMemory()
int32_t PK_PoILEraseMemory (sPoKeysDevice * device, uint8_t memoryType)
Erase a region of interpreter memory.
Definition at line 293 of file PoKeysLibPoIL.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().
PK_PoILGetState()
int32_t PK_PoILGetState (sPoKeysDevice * device)
Query interpreter status from the device.
Definition at line 68 of file PoKeysLibPoIL.c.
References CreateRequest(), sPoILStatus::dataStack, sPoILStatus::functionStack, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_ParsePoILStateResponse(), sPoKeysDevice::PoIL, sPoKeysDevice::request, SendRequest(), and sPoILStack::stackSize.
PK_PoILReadMemory()
int32_t PK_PoILReadMemory (sPoKeysDevice * device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t * dest)
Read a block of interpreter memory.
Definition at line 146 of file PoKeysLibPoIL.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoILReadSharedSlot()
int32_t PK_PoILReadSharedSlot (sPoKeysDevice * device, uint16_t firstSlotID, uint16_t slotsNum, int * dest)
Read interpreter shared-slot variables.
Definition at line 228 of file PoKeysLibPoIL.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_PoILResetCore()
int32_t PK_PoILResetCore (sPoKeysDevice * device)
Reset the interpreter core on the device.
Definition at line 116 of file PoKeysLibPoIL.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_ParsePoILStateResponse(), sPoKeysDevice::request, and SendRequest().
PK_PoILSetCoreState()
int32_t PK_PoILSetCoreState (sPoKeysDevice * device, uint16_t state)
Request a change of interpreter core state.
Definition at line 86 of file PoKeysLibPoIL.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_ParsePoILStateResponse(), sPoKeysDevice::request, and SendRequest().
PK_PoILSetDebugMode()
int32_t PK_PoILSetDebugMode (sPoKeysDevice * device, uint8_t debugMode, uint16_t breakpoint)
Configure interpreter debug mode and breakpoint.
Definition at line 131 of file PoKeysLibPoIL.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_ParsePoILStateResponse(), sPoKeysDevice::request, and SendRequest().
PK_PoILSetMasterEnable()
int32_t PK_PoILSetMasterEnable (sPoKeysDevice * device, uint8_t masterEnable)
Enable or disable the interpreter execution engine.
Definition at line 101 of file PoKeysLibPoIL.c.
References CreateRequest(), PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_ParsePoILStateResponse(), sPoKeysDevice::request, and SendRequest().
PK_PoILTaskStatus()
int32_t PK_PoILTaskStatus (sPoKeysDevice * device)
Retrieve status information for all interpreter tasks.
Definition at line 360 of file PoKeysLibPoIL.c.
References CreateRequest(), i, sPoILStatus::inactiveLoad, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::PoIL, sPoKeysDevice::request, sPoKeysDevice::response, SendRequest(), sPoILStatus::taskCount, sPoILTask::taskLoad, sPoILTask::taskPeriod, sPoILTask::taskRealPeriod, sPoILTask::taskRealPeriodFiltered, sPoILStatus::tasks, and sPoILTask::taskStatus.
PK_PoILWriteMemory()
int32_t PK_PoILWriteMemory (sPoKeysDevice * device, uint8_t memoryType, uint16_t address, uint16_t size, uint8_t * src)
Write a block of interpreter memory.
Definition at line 178 of file PoKeysLibPoIL.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, PK_PoILWriteMemory(), sPoKeysDevice::request, and SendRequest().
PK_PoILWriteSharedSlot()
int32_t PK_PoILWriteSharedSlot (sPoKeysDevice * device, uint16_t firstSlotID, uint16_t slotsNum, int32_t * src)
Write interpreter shared-slot variables.
Definition at line 260 of file PoKeysLibPoIL.c.
References CreateRequest(), i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and SendRequest().