LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeyslib/PoKeysLibCore.h File Reference
PoKeysLibCore.h File Reference
#include "hidapi.h"
#include <stdio.h>
#include <string.h>
#include "PoKeysLib.h"
Macros
#define ConnectToFastUSBInterface(device) NULL;
#define DisconnectFromFastUSBInterface(device) ;
#define SendRequestFastUSB(device) ;
#define SendRequestFastUSB_multiPart(device) ;
Functions
void InitializeNewDevice (sPoKeysDevice *device)
void CleanDevice (sPoKeysDevice *device)
void PK_DisconnectNetworkDevice (sPoKeysDevice *device)
int32_t CreateRequest (uint8_t *request, uint8_t type, uint8_t param1, uint8_t param2, uint8_t param3, uint8_t param4)
uint8_t getChecksum (uint8_t *data)
int32_t SendRequest (sPoKeysDevice *device)
int32_t SendRequest_multiPart (sPoKeysDevice *device)
int32_t SendRequest_NoResponse (sPoKeysDevice *device)
int32_t PK_FillPWMPinNumbers (sPoKeysDevice *device)
Macro Definition Documentation
ConnectToFastUSBInterface
#define ConnectToFastUSBInterface (device) NULL;
Definition at line 50 of file PoKeysLibCore.h.
DisconnectFromFastUSBInterface
#define DisconnectFromFastUSBInterface (device) ;
Definition at line 51 of file PoKeysLibCore.h.
SendRequestFastUSB
#define SendRequestFastUSB (device) ;
Definition at line 52 of file PoKeysLibCore.h.
SendRequestFastUSB_multiPart
#define SendRequestFastUSB_multiPart (device) ;
Definition at line 53 of file PoKeysLibCore.h.
Function Documentation
CleanDevice()
void CleanDevice (sPoKeysDevice * device)
Definition at line 187 of file PoKeysLibCore.c.
CreateRequest()
int32_t CreateRequest (uint8_t * request, uint8_t type, uint8_t param1, uint8_t param2, uint8_t param3, uint8_t param4)
Definition at line 647 of file PoKeysLibCore.c.
getChecksum()
uint8_t getChecksum (uint8_t * data)
Definition at line 673 of file PoKeysLibCore.c.
InitializeNewDevice()
void InitializeNewDevice (sPoKeysDevice * device)
Definition at line 89 of file PoKeysLibCore.c.
PK_DisconnectNetworkDevice()
void PK_DisconnectNetworkDevice (sPoKeysDevice * device)
Definition at line 559 of file PoKeysLibCoreSockets.c.
References sPoKeysDevice::connectionType, debug_printf, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, and PK_DeviceType_NetworkDevice.
Referenced by PK_DisconnectDevice().
PK_FillPWMPinNumbers()
int32_t PK_FillPWMPinNumbers (sPoKeysDevice * device)
Definition at line 1050 of file PoKeysLibDeviceData.c.
References sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceType, sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_DeviceID_PoKeys57CNCdb25, PK_ERR_NOT_SUPPORTED, PK_OK, sPoKeysDevice::PWM, and sPoKeysPWM::PWMpinIDs.
Referenced by InitializeNewDevice(), and PK_InitializeNewDeviceAsync().
SendRequest()
int32_t SendRequest (sPoKeysDevice * device)
Definition at line 712 of file PoKeysLibCore.c.
SendRequest_multiPart()
int32_t SendRequest_multiPart (sPoKeysDevice * device)
Definition at line 690 of file PoKeysLibCore.c.
SendRequest_NoResponse()
int32_t SendRequest_NoResponse (sPoKeysDevice * device)
Definition at line 811 of file PoKeysLibCore.c.