LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeyslib/PoKeysLibDevicePoKeys57Industrial.c File Reference
PoKeysLibDevicePoKeys57Industrial.c File Reference
#include <stdlib.h>
#include "PoKeysLib.h"
#include "PoKeysLibCore.h"
#include <unistd.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include "PoKeysLibDevicePoKeys57Industrial.h"
#include "PoKeysLibCoreSockets.h"
#include "string.h"
#include "stdio.h"
Macros
#define debug_printf (void)
Functions
int32_t PK57i_SearchDevice (sPoKeysNetworkDeviceSummary *device, uint32_t timeout)
Perform UDP discovery for a PoKeys57Industrial device.
sPoKeys57Industrial * PK57i_Connect (void)
void PK57i_Disconnect (sPoKeys57Industrial *device)
int32_t PK57i_Update (sPoKeys57Industrial *device, uint8_t resetFaults)
Macro Definition Documentation
debug_printf
#define debug_printf (void)
Definition at line 46 of file PoKeysLibDevicePoKeys57Industrial.c.
Function Documentation
PK57i_Connect()
sPoKeys57Industrial * PK57i_Connect (void)
Connect to a PoKeys57Industrial device (network or USB).
Definition at line 52 of file PoKeysLibDevicePoKeys57Industrial.c.
References sPoKeysDevice::DeviceData, sPoKeys57Industrial::deviceStructure, sPoKeysDevice_Data::DeviceType, i, PK57i_SearchDevice(), PK_ConnectToDevice(), PK_ConnectToNetworkDevice(), PK_DisconnectDevice(), and PK_EnumerateUSBDevices().
PK57i_Disconnect()
void PK57i_Disconnect (sPoKeys57Industrial * device)
Disconnect and release the PoKeys57Industrial handle.
Definition at line 100 of file PoKeysLibDevicePoKeys57Industrial.c.
References sPoKeys57Industrial::deviceStructure, and PK_DisconnectDevice().
Referenced by PK57i_DisconnectAsync().
PK57i_SearchDevice()
int32_t PK57i_SearchDevice (sPoKeysNetworkDeviceSummary * device, uint32_t timeout)
Perform UDP discovery for a PoKeys57Industrial device.
An empty broadcast packet is sent to port 20055 and responses are parsed according to the "Discovery packet format" described in the PoKeys protocol specification. Only devices reporting hardware ID 45 are accepted.
Parameters
device Structure that receives the discovered device details.
timeout Timeout in milliseconds to wait for replies.
Returns
Number of detected boards.
Definition at line 164 of file PoKeysLibDevicePoKeys57Industrial.c.
References debug_printf, sPoKeysNetworkDeviceSummary::DHCP, sPoKeysNetworkDeviceSummary::FirmwareVersionMajor, sPoKeysNetworkDeviceSummary::FirmwareVersionMinor, GetBroadcastAddresses(), sPoKeysNetworkDeviceSummary::hostIP, sPoKeysNetworkDeviceSummary::HWtype, sPoKeysNetworkDeviceSummary::IPaddress, and sPoKeysNetworkDeviceSummary::SerialNumber.
Referenced by PK57i_Connect().
PK57i_Update()
int32_t PK57i_Update (sPoKeys57Industrial * device, uint8_t resetFaults)
Exchange I/O states using command 0x3F.
Definition at line 110 of file PoKeysLibDevicePoKeys57Industrial.c.
References sPoKeys57Industrial::analogInputs, sPoKeys57Industrial::analogOutputs, sPoKeys57Industrial::analogOutputsFault, CreateRequest(), sPoKeys57Industrial::deviceStructure, sPoKeys57Industrial::digitalInputs, sPoKeys57Industrial::digitalOutputs, sPoKeys57Industrial::digitalOutputsEnable, sPoKeys57Industrial::digitalOutputsFault, i, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().