LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibCore.c File Reference
PoKeysLibCore.c File Reference
Core communication helpers for the PoKeys protocol.
#include <stdlib.h>
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibCoreSockets.h"
#include "string.h"
#include "stdio.h"
Functions
int32_t PKI_CheckInterface (struct hid_device_info *devInfo)
Validate HID interface as PoKeys communication channel.
int32_t PK_EnumerateUSBDevices ()
Enumerate PoKeys USB devices.
int32_t PK_GetCurrentDeviceConnectionType (sPoKeysDevice *device)
Obtain the active connection type for a device.
void InitializeNewDevice (sPoKeysDevice *device)
void CleanDevice (sPoKeysDevice *device)
void PK_ReleaseDeviceStructure (sPoKeysDevice *device)
void PK_CloneDeviceStructure (sPoKeysDevice *original, sPoKeysDevice *destination)
void * PK_FastUSBConnectToDevice (uint32_t deviceIndex)
sPoKeysDevice * PK_ConnectToDevice (uint32_t deviceIndex)
sPoKeysDevice * PK_ConnectToPoKeysDevice_USB (uint32_t serialNumber, uint32_t flags)
sPoKeysDevice * PK_ConnectToPoKeysDevice_Ethernet (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
sPoKeysDevice * PK_ConnectToPoKeysDevice (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
sPoKeysDevice * PK_ConnectToDeviceWSerial (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
sPoKeysDevice * PK_ConnectToDeviceWSerial_UDP (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
void PK_DisconnectDevice (sPoKeysDevice *device)
int32_t CreateRequest (unsigned char *request, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Compose a PoKeys request packet.
int32_t PK_CustomRequest (sPoKeysDevice *device, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Send an arbitrary request to the connected device.
uint8_t getChecksum (uint8_t *data)
int32_t SendRequest_multiPart (sPoKeysDevice *device)
Send a multipart data transfer.
int32_t SendRequest (sPoKeysDevice *device)
Send a request and wait for the device response.
int32_t SendRequest_NoResponse (sPoKeysDevice *device)
Send a request without waiting for any reply.
void PK_SL_SetPinFunction (sPoKeysDevice *device, uint8_t pin, uint8_t function)
uint8_t PK_SL_GetPinFunction (sPoKeysDevice *device, uint8_t pin)
void PK_SL_DigitalOutputSet (sPoKeysDevice *device, uint8_t pin, uint8_t value)
uint8_t PK_SL_DigitalInputGet (sPoKeysDevice *device, uint8_t pin)
uint32_t PK_SL_AnalogInputGet (sPoKeysDevice *device, uint8_t pin)
Variables
int32_t LastRetryCount = 0
int32_t LastWaitCount = 0
Detailed Description
Core communication helpers for the PoKeys protocol.
This module implements basic request formatting and transport functions used by almost all higher level commands. It covers USB, fast USB and Ethernet communication as described in the PoKeys protocol specification.
Definition in file PoKeysLibCore.c.
Function Documentation
CleanDevice()
void CleanDevice (sPoKeysDevice * device)
Definition at line 347 of file PoKeysLibCore.c.
References sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::MatrixLED, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, sPoKeysDevice::Pins, sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMpinIDs.
CreateRequest()
int32_t CreateRequest (unsigned char * request, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Compose a PoKeys request packet.
The PoKeys protocol uses 64 byte packets. Bytes 1 to 5 hold the command identifier and up to four parameters. The header byte (0xBB), request ID and checksum are appended by SendRequest().
Parameters
request Pointer to a 64 byte buffer that will contain the command.
type Command ID as defined by pokeys_command_t (PK_CMD_*).
param1 First command parameter.
param2 Second command parameter.
param3 Third command parameter.
param4 Fourth command parameter.
Returns
PK_OK on success or PK_ERR_NOT_CONNECTED when request is NULL.
Definition at line 880 of file PoKeysLibCore.c.
References PK_ERR_NOT_CONNECTED, and PK_OK.
getChecksum()
uint8_t getChecksum (uint8_t * data)
Definition at line 922 of file PoKeysLibCore.c.
References i.
InitializeNewDevice()
void InitializeNewDevice (sPoKeysDevice * device)
General pin settings PoKeys55, PoKeys56, PoKeys57 limitations
Pin codes used in PoKeys55 device are 0-based, e.g. pin 1 has pin code of 0, pin 55 has pin code of 54.
Analog input capable pins 43 to 47 have pin codes of 42 to 46.
Analog output capable pin 43 has pin code of 42.
PWM (pulse-width modulation) capable pins 17 to 22 have pin codes of 16-21 (PWM module outputs are in reversed order, e.g. pin 17 (pin coded as 16) is connected to PWM6 output – see specifications below).
PoKeys57CNC device supports PWM output function on 4 pins (pins 18, 20, 21 and 22). Different duty cycles can be assigned to each PWM output however, all outputs share the same PWM period. PWM outputs can be easily amplified using an external transistor and used for control of loads with increased increased current demand - pins with such function embedded are marked as OC (open-collector) in the pinout diagram. PoKeys PWM outputs can also be used to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). PoKeys devices have an in-built PWM module that operates at a fixed clock frequency (25 MHz). Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000)
PoKeys57CNCpro4x25 device supports PWM output function on pins 17 and 20. Pin 17 is wired to 0- 10 V output for spindle control – the output voltage is proportional to the duty cycle of the PWM output. PWM output on pin 20 is located on dedicated connector and can be easily amplified using an external transistor and used for controlling the loads with increased current demand – we offer MOSFET power switch adapter for such purposes in PoLabs online store. The frequency of the generated PWM signal can be changed – for the analog output functionality on pin 17 to operate as designed, a PWM frequency of 20 kHz is suggested. However, if needed, the frequency of PoKeys PWM outputs can be reduced – e.g. to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). In such case, analog output on pin 17 will not be operational. PoKeys devices have a built-in PWM module that operates at a fixed clock frequency of 25 MHz. Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000).
Definition at line 152 of file PoKeysLibCore.c.
References sPoKeysDevice::AnalogInput, hal_adcout_t::bit_weight, sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceTypeID, sPoKeysPinData::DigitalCounterAvailable, sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, hal_float_t, hal_malloc(), hal_adcout_t::high_limit, hal_adcout_t::hw_offset, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice::LCD, hal_adcout_t::low_limit, sPoKeysDevice::matrixKB, sPoKeysDevice::MatrixLED, sPoKeysPWM::max_Voltage, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, hal_adcout_t::offset, sPoKeysDevice::PEv2, sPoKeysDevice::Pins, PK_DeviceDataGet(), PK_DeviceID_PoKeys57CNC, PK_DeviceID_PoKeys57CNCpro4x25, PK_FillPWMPinNumbers(), PK_IsCounterAvailable(), sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWManalogOutputs, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysPWM::PWMpinIDs, sPoKeysDevice::readRetries, sPoKeysDevice::request, sPoKeysDevice::response, RTAPI_MSG_ERR, rtapi_print_msg(), hal_adcout_t::scale, sPoKeysDevice::sendRetries, sPoKeysDevice::socketTimeout, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
PK_CloneDeviceStructure()
void PK_CloneDeviceStructure (sPoKeysDevice * original, sPoKeysDevice * destination)
Definition at line 389 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, sPoKeysDevice::DeviceData, sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, hal_malloc(), sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice::LCD, sPoKeysDevice::matrixKB, sPoKeysDevice::MatrixLED, sPoKeysDevice::netDeviceData, sPoKeysDevice::Pins, sPoKeysDevice::PoExtBusData, sPoKeysDevice::PoIL, sPoKeysDevice::PoNETmodule, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysPWM::PWMpinIDs, sPoKeysDevice::requestID, RTAPI_MSG_ERR, rtapi_print_msg(), sPoKeysDevice::RTC, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
PK_ConnectToDevice()
sPoKeysDevice * PK_ConnectToDevice (uint32_t deviceIndex)
Definition at line 475 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, hal_malloc(), hid_enumerate(), hid_free_enumeration(), hid_open_path(), InitializeNewDevice(), hid_device_info::interface_number, hid_device_info::next, hid_device_info::path, PK_DeviceType_FastUSBDevice, PK_DeviceType_USBDevice, PK_FastUSBConnectToDevice(), RTAPI_MSG_ERR, and rtapi_print_msg().
PK_ConnectToDeviceWSerial()
sPoKeysDevice * PK_ConnectToDeviceWSerial (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
Definition at line 826 of file PoKeysLibCore.c.
References PK_ConnectToPoKeysDevice().
PK_ConnectToDeviceWSerial_UDP()
sPoKeysDevice * PK_ConnectToDeviceWSerial_UDP (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout)
Definition at line 831 of file PoKeysLibCore.c.
References PK_ConnectToPoKeysDevice().
PK_ConnectToPoKeysDevice()
sPoKeysDevice * PK_ConnectToPoKeysDevice (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
Definition at line 800 of file PoKeysLibCore.c.
References sPoKeysDevice::devHandle2, PK_ConnectToPoKeysDevice_Ethernet(), PK_ConnectToPoKeysDevice_USB(), RTAPI_MSG_ERR, and rtapi_print_msg().
PK_ConnectToPoKeysDevice_Ethernet()
sPoKeysDevice * PK_ConnectToPoKeysDevice_Ethernet (uint32_t serialNumber, uint32_t checkForNetworkDevicesAndTimeout, uint32_t flags)
Definition at line 749 of file PoKeysLibCore.c.
References sPoKeysDevice::devHandle2, hal_malloc(), InitializeNewDevice(), PK_ConnectToNetworkDevice(), PK_SearchNetworkDevices(), RTAPI_MSG_ERR, RTAPI_MSG_INFO, rtapi_print_msg(), and sPoKeysNetworkDeviceSummary::useUDP.
PK_ConnectToPoKeysDevice_USB()
sPoKeysDevice * PK_ConnectToPoKeysDevice_USB (uint32_t serialNumber, uint32_t flags)
Definition at line 597 of file PoKeysLibCore.c.
References CleanDevice(), sPoKeysDevice::connectionType, ConnectToFastUSBInterface, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, sPoKeysDevice::DeviceData, hal_malloc(), hid_enumerate(), hid_free_enumeration(), hid_open_path(), InitializeNewDevice(), hid_device_info::interface_number, hid_device_info::next, hid_device_info::path, PK_DeviceType_FastUSBDevice, PK_DeviceType_USBDevice, RTAPI_MSG_ERR, rtapi_print_msg(), hid_device_info::serial_number, and sPoKeysDevice_Data::SerialNumber.
PK_CustomRequest()
int32_t PK_CustomRequest (sPoKeysDevice * device, unsigned char type, unsigned char param1, unsigned char param2, unsigned char param3, unsigned char param4)
Send an arbitrary request to the connected device.
The helper fills the device request buffer in the same format as CreateRequest() and immediately transmits it using SendRequest(). It is mainly used for higher level functions that do not require dedicated API calls.
Parameters
device Target device structure.
type Command ID (PK_CMD_* constant).
param1 First command parameter.
param2 Second command parameter.
param3 Third command parameter.
param4 Fourth command parameter.
Returns
Result of SendRequest().
Definition at line 911 of file PoKeysLibCore.c.
References sPoKeysDevice::request, and SendRequest().
PK_DisconnectDevice()
void PK_DisconnectDevice (sPoKeysDevice * device)
Definition at line 837 of file PoKeysLibCore.c.
References CleanDevice(), sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, DisconnectFromFastUSBInterface, hid_close(), PK_DeviceType_NetworkDevice, and PK_DisconnectNetworkDevice().
PK_EnumerateUSBDevices()
int32_t PK_EnumerateUSBDevices (void)
Enumerate PoKeys USB devices.
Two product identifiers are scanned (0x1001 and 0x1002) under the PoLabs vendor ID 0x1DC3. Interfaces are filtered through PKI_CheckInterface() so that only the communication interface (index 1) is counted for devices using the standard HID protocol. For the older fast USB interface the interface number is -1.
Returns
Number of PoKeys devices detected on the USB bus.
Definition at line 73 of file PoKeysLibCore.c.
References hid_enumerate(), hid_free_enumeration(), hid_device_info::interface_number, hid_device_info::next, PK_EnumerateFastUSBDevices(), PKI_CheckInterface(), hid_device_info::product_string, RTAPI_MSG_ERR, rtapi_print_msg(), and hid_device_info::serial_number.
PK_FastUSBConnectToDevice()
void * PK_FastUSBConnectToDevice (uint32_t deviceIndex)
PK_GetCurrentDeviceConnectionType()
int32_t PK_GetCurrentDeviceConnectionType (sPoKeysDevice * device)
Obtain the active connection type for a device.
The field ::connectionType of the device structure holds the current transport that is used for communication. Possible values are defined by ePK_DeviceConnectionType (for example PK_DeviceType_USBDevice or PK_DeviceType_NetworkDevice).
Parameters
device Pointer to an initialised PoKeys device structure.
Returns
The current connection type constant.
Definition at line 147 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType.
PK_ReleaseDeviceStructure()
void PK_ReleaseDeviceStructure (sPoKeysDevice * device)
Definition at line 384 of file PoKeysLibCore.c.
References CleanDevice().
PK_SL_AnalogInputGet()
uint32_t PK_SL_AnalogInputGet (sPoKeysDevice * device, uint8_t pin)
Definition at line 1189 of file PoKeysLibCore.c.
References sPoKeysPinData::AnalogValue, and sPoKeysDevice::Pins.
PK_SL_DigitalInputGet()
uint8_t PK_SL_DigitalInputGet (sPoKeysDevice * device, uint8_t pin)
Definition at line 1184 of file PoKeysLibCore.c.
References sPoKeysPinData::DigitalValueGet, and sPoKeysDevice::Pins.
PK_SL_DigitalOutputSet()
void PK_SL_DigitalOutputSet (sPoKeysDevice * device, uint8_t pin, uint8_t value)
Definition at line 1179 of file PoKeysLibCore.c.
References sPoKeysPinData::DigitalValueSet, and sPoKeysDevice::Pins.
PK_SL_GetPinFunction()
uint8_t PK_SL_GetPinFunction (sPoKeysDevice * device, uint8_t pin)
Definition at line 1174 of file PoKeysLibCore.c.
References sPoKeysPinData::PinFunction, and sPoKeysDevice::Pins.
PK_SL_SetPinFunction()
void PK_SL_SetPinFunction (sPoKeysDevice * device, uint8_t pin, uint8_t function)
Definition at line 1169 of file PoKeysLibCore.c.
References sPoKeysPinData::PinFunction, and sPoKeysDevice::Pins.
PKI_CheckInterface()
int32_t PKI_CheckInterface (struct hid_device_info * devInfo)
Validate HID interface as PoKeys communication channel.
The PoKeys USB devices expose multiple HID interfaces. Only the interface with index 1 carries the standard command protocol used by this library. This helper checks the passed HID interface information and reports whether it should be used for communication.
Parameters
devInfo HID device information structure obtained from hid_enumerate().
Returns
1 when the interface number matches the communication interface, otherwise 0.
Definition at line 52 of file PoKeysLibCore.c.
References hid_device_info::interface_number.
SendRequest()
int32_t SendRequest (sPoKeysDevice * device)
Send a request and wait for the device response.
The function finalises the 64 byte request by prepending the packet header (0xBB), assigning a request ID and calculating the checksum (simple sum of bytes 0–6). The request is transmitted over the currently selected interface. After sending the packet the function waits for a reply with header 0xAA that carries the same request ID and a valid checksum.
Parameters
device Device that holds the prepared request buffer.
Returns
PK_OK on success or PK_ERR_TRANSFER on failure.
Definition at line 988 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, getChecksum(), hid_read(), hid_write(), i, LastRetryCount, LastWaitCount, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::requestID, sPoKeysDevice::response, RTAPI_MSG_ERR, rtapi_print_msg(), SendEthRequest(), and SendRequestFastUSB.
SendRequest_multiPart()
int32_t SendRequest_multiPart (sPoKeysDevice * device)
Send a multipart data transfer.
Large data blocks are transferred using the command PK_CMD_MULTIPART_PACKET. The function delegates the actual transmission to the network or fast USB helpers depending on the device connection type.
The multipart buffer and packet headers must be prepared by the caller in device before invoking this function.
Parameters
device Target device instance.
Returns
PK_OK on success or an error code on failure.
Definition at line 953 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, SendEthRequestBig(), and SendRequestFastUSB_multiPart.
SendRequest_NoResponse()
int32_t SendRequest_NoResponse (sPoKeysDevice * device)
Send a request without waiting for any reply.
The packet formatting is identical to SendRequest() but the function returns immediately after the HID write call. It is typically used with commands that acknowledge through other means (for example PK_CMD_REBOOT_SYSTEM).
Parameters
device Device that holds the prepared request buffer.
Returns
PK_OK on successful USB transfer or PK_ERR_TRANSFER when the packet could not be sent.
Definition at line 1102 of file PoKeysLibCore.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, getChecksum(), hid_write(), i, PK_DeviceType_FastUSBDevice, PK_DeviceType_NetworkDevice, PK_ERR_GENERIC, PK_ERR_TRANSFER, sPoKeysDevice::request, sPoKeysDevice::requestID, RTAPI_MSG_ERR, rtapi_print_msg(), and SendEthRequest_NoResponse().
Variable Documentation
LastRetryCount
int32_t LastRetryCount = 0
Definition at line 934 of file PoKeysLibCore.c.
LastWaitCount
int32_t LastWaitCount = 0
Definition at line 935 of file PoKeysLibCore.c.