LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibDeviceStatusAsync.c File Reference
PoKeysLibDeviceStatusAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
#include <sys/time.h>
Functions
int PK_DeviceAliveCheckAsync (sPoKeysDevice *device)
Check if device is alive/responsive (async)
int PK_DeviceLoadStatusAsync (sPoKeysDevice *device)
Get device load status (async)
int PK_DeviceErrorStatusAsync (sPoKeysDevice *device)
Get device error status (async)
int PK_DeviceErrorResetAsync (sPoKeysDevice *device)
Reset device error counters (async)
int PK_DeviceStatusFullAsync (sPoKeysDevice *device)
Comprehensive device status check (async)
int PK_DeviceConnectionQualityAsync (sPoKeysDevice *device, uint8_t *quality)
Check connection quality metrics (async)
int PK_DeviceConnectionFailureAsync (sPoKeysDevice *device)
Handle communication failure (for retry logic)
Function Documentation
PK_DeviceAliveCheckAsync()
int PK_DeviceAliveCheckAsync (sPoKeysDevice * device)
Check if device is alive/responsive (async)
Sends a simple ping command to verify device connectivity. Critical for LinuxCNC HAL to detect communication failures.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 88 of file PoKeysLibDeviceStatusAsync.c.
References CreateRequestAsync(), PK_CMD_READ_DEVICE_DATA, and PK_ERR_NOT_CONNECTED.
Referenced by PK_CommunicationTestAsync(), PK_DeviceStatusFullAsync(), and PK_SystemStatusGetAllAsync().
PK_DeviceConnectionFailureAsync()
int PK_DeviceConnectionFailureAsync (sPoKeysDevice * device)
Handle communication failure (for retry logic)
Should be called when async communication fails to update connection monitoring counters.
Parameters
device Target device handle
Returns
PK_OK always
Definition at line 241 of file PoKeysLibDeviceStatusAsync.c.
References PK_ERR_NOT_CONNECTED.
PK_DeviceConnectionQualityAsync()
int PK_DeviceConnectionQualityAsync (sPoKeysDevice * device, uint8_t * quality)
Check connection quality metrics (async)
Evaluates connection stability based on response times and error rates. Provides quality metrics for adaptive behavior in LinuxCNC.
Parameters
device Target device handle
quality Output pointer for quality percentage (0-100)
Returns
PK_OK on success, error code on failure
Definition at line 199 of file PoKeysLibDeviceStatusAsync.c.
References PK_ERR_GENERIC.
PK_DeviceErrorResetAsync()
int PK_DeviceErrorResetAsync (sPoKeysDevice * device)
Reset device error counters (async)
Clears accumulated error counters and flags. Useful for recovering from transient communication issues.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 146 of file PoKeysLibDeviceStatusAsync.c.
References CreateRequestAsync(), PK_CMD_DEVICE_ERROR_STATUS, and PK_ERR_NOT_CONNECTED.
PK_DeviceErrorStatusAsync()
int PK_DeviceErrorStatusAsync (sPoKeysDevice * device)
Get device error status (async)
Retrieves error flags, communication error count, and last error code. Essential for diagnostic information in LinuxCNC applications.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 128 of file PoKeysLibDeviceStatusAsync.c.
References CreateRequestAsync(), PK_CMD_DEVICE_ERROR_STATUS, and PK_ERR_NOT_CONNECTED.
Referenced by PK_DeviceStatusFullAsync(), and PK_SystemStatusGetAllAsync().
PK_DeviceLoadStatusAsync()
int PK_DeviceLoadStatusAsync (sPoKeysDevice * device)
Get device load status (async)
Retrieves CPU load, USB load, network load, temperature and buffer load. Important for monitoring device performance in real-time applications.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 107 of file PoKeysLibDeviceStatusAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iLoadStatus, sPoKeysDevice::info, PK_CMD_DEVICE_LOAD_STATUS, PK_ERR_NOT_CONNECTED, and PK_ERR_NOT_SUPPORTED.
Referenced by PK_DeviceStatusFullAsync(), and PK_SystemStatusGetAllAsync().
PK_DeviceStatusFullAsync()
int PK_DeviceStatusFullAsync (sPoKeysDevice * device)
Comprehensive device status check (async)
Combines alive check, load status, and error status into a single efficient monitoring function. Ideal for periodic HAL monitoring.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 166 of file PoKeysLibDeviceStatusAsync.c.
References sPoKeysDevice_Info::iLoadStatus, sPoKeysDevice::info, PK_DeviceAliveCheckAsync(), PK_DeviceErrorStatusAsync(), PK_DeviceLoadStatusAsync(), PK_ERR_NOT_CONNECTED, and PK_OK.