LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibPWMAsync.c File Reference
PoKeysLibPWMAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Functions
int PK_PWMConfigurationGetAsync (sPoKeysDevice *device)
Get PWM configuration (async)
int PK_PWMConfigurationSetAsync (sPoKeysDevice *device)
Set PWM configuration (async)
int PK_PWMUpdateAsync (sPoKeysDevice *device)
Update PWM duty cycles (async)
int PK_PWMConfigurationSetDirectlyAsync (sPoKeysDevice *device, uint32_t PWMperiod, uint8_t *enabledChannels)
Set PWM configuration directly (async)
int PK_PWMUpdateDirectlyAsync (sPoKeysDevice *device, uint32_t *dutyCycles)
Update PWM duty cycles directly (async)
int PK_PWMSetSingleChannelAsync (sPoKeysDevice *device, uint8_t channel, uint32_t dutyCycle)
Set single PWM channel duty cycle (async)
int PK_PWMGetPinAssignmentsAsync (sPoKeysDevice *device)
Get PWM pin assignments (async)
Function Documentation
PK_PWMConfigurationGetAsync()
int PK_PWMConfigurationGetAsync (sPoKeysDevice * device)
Get PWM configuration (async)
Starts async request to get PWM configuration (CMD 0xCB, param1=0)
Retrieves current PWM period, enabled channels, and duty cycles. Essential for reading back current PWM state in LinuxCNC.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 56 of file PoKeysLibPWMAsync.c.
References CreateRequestAsync(), sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_CMD_PWM_CONFIGURATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, and PK_PWMConfigurationParse().
PK_PWMConfigurationSetAsync()
int PK_PWMConfigurationSetAsync (sPoKeysDevice * device)
Set PWM configuration (async)
Starts async command to configure PWM duty cycle and period (CMD 0xCB).
Configures PWM period and enabled channels. This is typically done during initialization and when changing PWM frequency.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 79 of file PoKeysLibPWMAsync.c.
References CreateRequestAsync(), hal_adcout_t::enable, hal_adcout_getscaledvalue(), hal_float_t, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, sPoKeysPWM::max_Voltage, PK_CMD_PWM_CONFIGURATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_PARAMETER, sPoKeysDevice::PWM, sPoKeysPWM::PWManalogOutputs, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
Referenced by PK_PWMConfigurationSetDirectlyAsync().
PK_PWMConfigurationSetDirectlyAsync()
int PK_PWMConfigurationSetDirectlyAsync (sPoKeysDevice * device, uint32_t PWMperiod, uint8_t * enabledChannels)
Set PWM configuration directly (async)
Set PWM configuration directly with specified parameters (async)
Convenience function to set PWM period and enabled channels in one call. Useful for initialization sequences.
Parameters
device Target device handle
PWMperiod PWM period in clock ticks
enabledChannels Array of 6 enabled channel flags
Returns
PK_OK on success, error code on failure
Definition at line 154 of file PoKeysLibPWMAsync.c.
References CreateRequestAsync(), i, sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_ERR_GENERIC, PK_ERR_NOT_SUPPORTED, PK_ERR_PARAMETER, PK_PWMConfigurationSetAsync(), sPoKeysDevice::PWM, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
PK_PWMGetPinAssignmentsAsync()
int PK_PWMGetPinAssignmentsAsync (sPoKeysDevice * device)
Get PWM pin assignments (async)
Retrieves which physical pins are assigned to PWM channels. Important for LinuxCNC configuration and diagnostics.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 246 of file PoKeysLibPWMAsync.c.
References CreateRequestAsync(), sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_FillPWMPinNumbers(), PK_OK, and PK_PWMPinAssignmentsParse().
PK_PWMSetSingleChannelAsync()
int PK_PWMSetSingleChannelAsync (sPoKeysDevice * device, uint8_t channel, uint32_t dutyCycle)
Set single PWM channel duty cycle (async)
Updates a single PWM channel without affecting others. Efficient for applications that need to update individual channels.
Parameters
device Target device handle
channel PWM channel number (0-5)
dutyCycle Duty cycle value
Returns
PK_OK on success, error code on failure
Definition at line 210 of file PoKeysLibPWMAsync.c.
References CreateRequestAsync(), sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_CMD_PWM_CONFIGURATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_PARAMETER, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
PK_PWMUpdateAsync()
int PK_PWMUpdateAsync (sPoKeysDevice * device)
Update PWM duty cycles (async)
Starts async command to update PWM values only (CMD 0xCB, param1=1, param2=1).
Updates duty cycles for all PWM channels without changing period. This is the most frequently used PWM function for real-time control.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 117 of file PoKeysLibPWMAsync.c.
References CreateRequestAsync(), hal_adcout_t::enable, hal_adcout_getscaledvalue(), hal_float_t, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, sPoKeysPWM::max_Voltage, PK_CMD_PWM_CONFIGURATION, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_ERR_PARAMETER, sPoKeysDevice::PWM, sPoKeysPWM::PWManalogOutputs, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.
Referenced by PK_EmergencyStopAllAsync(), PK_IOUpdateCycleAsync(), and PK_PWMUpdateDirectlyAsync().
PK_PWMUpdateDirectlyAsync()
int PK_PWMUpdateDirectlyAsync (sPoKeysDevice * device, uint32_t * dutyCycles)
Update PWM duty cycles directly (async)
Convenience function to update duty cycles from an array. Frequently used in LinuxCNC HAL for real-time PWM updates.
Parameters
device Target device handle
dutyCycles Array of 6 duty cycle values
Returns
PK_OK on success, error code on failure
Definition at line 182 of file PoKeysLibPWMAsync.c.
References CreateRequestAsync(), i, sPoKeysDevice::info, sPoKeysDevice_Info::iPWMCount, PK_ERR_GENERIC, PK_ERR_NOT_SUPPORTED, PK_ERR_PARAMETER, PK_PWMUpdateAsync(), sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, and sPoKeysPWM::PWMperiod.