LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibEncodersAsync.c File Reference
PoKeysLibEncodersAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
Data Structures
struct PKEncoderCfgAsyncContext
Enumerations
enum PKEncoderCfgStep {
PK_ENCODERCFG_STEP_NONE , PK_ENCODERCFG_STEP_BASIC_OPTIONS , PK_ENCODERCFG_STEP_CHANNEL_MAPPING , PK_ENCODERCFG_STEP_DIRA_MAPPING ,
PK_ENCODERCFG_STEP_DIRB_MAPPING , PK_ENCODERCFG_STEP_FAST_ENCODERS , PK_ENCODERCFG_STEP_ULTRA_FAST_ENCODERS , PK_ENCODERCFG_STEP_COMPLETE
}
Functions
int export_encoder_pins (const char *prefix, long comp_id, sPoKeysDevice *device)
Exports all encoder HAL pins and parameters for a PoKeys device.
int PK_EncoderOptionsParse (sPoKeysDevice *device, const uint8_t *response)
Parses encoderOptions field and fills HAL encoder parameters.
int PK_FastEncodersOptionsParse (sPoKeysDevice *device, const uint8_t *response)
Parses FastEncodersOptions byte into individual HAL parameters.
int PK_UltraFastEncoderOptionsParse (sPoKeysDevice *device, const uint8_t *response)
int PK_EncoderValuesGetAsync_ProcessPage0 (sPoKeysDevice *device, const uint8_t *response)
int PK_EncoderValuesGetAsync_ProcessPage1 (sPoKeysDevice *device, const uint8_t *response)
int PK_EncoderValuesGetAsync_ProcessPage1_FastOnly (sPoKeysDevice *device, const uint8_t *response)
int PK_EncoderValuesGetAsync_ProcessUltraFast (sPoKeysDevice *device, const uint8_t *response)
int PK_EncoderConfigurationGetAsync (sPoKeysDevice *device)
Starts the asynchronous encoder configuration retrieval.
int PK_EncoderConfigurationSetAsync (sPoKeysDevice *device)
Asynchronously sets the full PoKeys encoder configuration.
int PK_EncoderValuesGetAsync (sPoKeysDevice *device)
Starts asynchronous encoder values retrieval.
int PK_EncoderValuesSetAsync (sPoKeysDevice *device)
Starts asynchronous encoder values set sequence.
int PK_EncoderRawValueResetAsync (sPoKeysDevice *device, uint32_t encoderMask)
Reset encoder raw values asynchronously (command 0x1A).
int PK_EncoderSingleResetAsync (sPoKeysDevice *device, uint8_t encoderIndex)
Reset a single encoder's raw value asynchronously.
int PK_EncoderAllResetAsync (sPoKeysDevice *device)
Reset all encoders' raw values asynchronously.
Enumeration Type Documentation
PKEncoderCfgStep
enum PKEncoderCfgStep
Enumerator
PK_ENCODERCFG_STEP_NONE
PK_ENCODERCFG_STEP_BASIC_OPTIONS
PK_ENCODERCFG_STEP_CHANNEL_MAPPING
PK_ENCODERCFG_STEP_DIRA_MAPPING
PK_ENCODERCFG_STEP_DIRB_MAPPING
PK_ENCODERCFG_STEP_FAST_ENCODERS
PK_ENCODERCFG_STEP_ULTRA_FAST_ENCODERS
PK_ENCODERCFG_STEP_COMPLETE
Definition at line 4 of file PoKeysLibEncodersAsync.c.
Function Documentation
export_encoder_pins()
int export_encoder_pins (const char * prefix, long comp_id, sPoKeysDevice * device)
Exports all encoder HAL pins and parameters for a PoKeys device.
Parameters
prefix HAL naming prefix
comp_id HAL component ID
device Pointer to PoKeys device structure
Returns
0 on success, negative HAL error code
Definition at line 30 of file PoKeysLibEncodersAsync.c.
PK_EncoderAllResetAsync()
int PK_EncoderAllResetAsync (sPoKeysDevice * device)
Reset all encoders' raw values asynchronously.
Convenience wrapper for resetting all available encoders.
Parameters
device Pointer to PoKeys device structure
Returns
PK_OK on success, error code on failure
Definition at line 617 of file PoKeysLibEncodersAsync.c.
References i, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice::info, PK_EncoderRawValueResetAsync(), and PK_ERR_NOT_CONNECTED.
PK_EncoderConfigurationGetAsync()
int PK_EncoderConfigurationGetAsync (sPoKeysDevice * device)
Starts the asynchronous encoder configuration retrieval.
This function issues multiple CreateRequestAsync() calls in sequence, preparing the system for automatic response filling based on target_ptr.
Parameters
device Pointer to the PoKeys device
Returns
PK_OK if successful, PK_ERR otherwise
Definition at line 303 of file PoKeysLibEncodersAsync.c.
References sPoKeysEncoder::channelApin, sPoKeysEncoder::channelBpin, CreateRequestAsync(), sPoKeysEncoder::dirAkeyCode, sPoKeysEncoder::dirAkeyModifier, sPoKeysEncoder::dirBkeyCode, sPoKeysEncoder::dirBkeyModifier, sPoKeysEncoder::encoderOptions, sPoKeysDevice::Encoders, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iUltraFastEncoders, PK_EncoderOptionsParse(), PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_FastEncodersOptionsParse(), PK_OK, and PK_UltraFastEncoderOptionsParse().
PK_EncoderConfigurationSetAsync()
int PK_EncoderConfigurationSetAsync (sPoKeysDevice * device)
Asynchronously sets the full PoKeys encoder configuration.
Prepares asynchronous requests to configure:
Basic encoder options (0xC4)
Encoder channel A/B mappings (0xC5)
Direction A and B key codes and modifiers (0xC6/0xC7)
Fast encoder configuration (0xCE)
Ultra fast encoder configuration and filter (0x1C)
Parameters
device Pointer to PoKeys device structure.
Returns
PK_OK (0) on success, or negative error code.
Definition at line 383 of file PoKeysLibEncodersAsync.c.
References sPoKeysEncoder::channelApin, sPoKeysEncoder::channelBpin, CreateRequestAsyncWithPayload(), sPoKeysEncoder::dirAkeyCode, sPoKeysEncoder::dirAkeyModifier, sPoKeysEncoder::dirBkeyCode, sPoKeysEncoder::dirBkeyModifier, sPoKeysEncoder::encoderOptions, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice_Info::iFastEncoders, sPoKeysDevice_Info::iKeyMapping, sPoKeysDevice::info, sPoKeysDevice_Info::iUltraFastEncoders, PK_ERR_NOT_CONNECTED, PK_ERR_NOT_SUPPORTED, PK_OK, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
PK_EncoderOptionsParse()
int PK_EncoderOptionsParse (sPoKeysDevice * device, const uint8_t * response)
Parses encoderOptions field and fills HAL encoder parameters.
Parameters
device Pointer to PoKeys device
response Full UDP response packet (starts at byte 0)
Returns
PK_OK on success, PK_ERR otherwise
Definition at line 182 of file PoKeysLibEncodersAsync.c.
References sPoKeysEncoder::enable, sPoKeysEncoder::encoderOptions, sPoKeysDevice::Encoders, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice::info, sPoKeysEncoder::keymap_dirA, sPoKeysEncoder::keymap_dirB, sPoKeysEncoder::macro_dirA, sPoKeysEncoder::macro_dirB, PK_ERR_PARAMETER, PK_ERR_TRANSFER, PK_OK, sPoKeysEncoder::x2_sampling, and sPoKeysEncoder::x4_sampling.
Referenced by PK_EncoderConfigurationGetAsync().
PK_EncoderRawValueResetAsync()
int PK_EncoderRawValueResetAsync (sPoKeysDevice * device, uint32_t encoderMask)
Reset encoder raw values asynchronously (command 0x1A).
This function implements the missing encoder reset functionality that exists in the PoKeys protocol but was not previously implemented. This is critical for LinuxCNC compatibility where encoder reset is commonly needed.
Parameters
device Pointer to PoKeys device structure
encoderMask Bitmask specifying which encoders to reset (bit 0 = encoder 0, etc.)
Returns
PK_OK on success, error code on failure
Definition at line 574 of file PoKeysLibEncodersAsync.c.
References CreateRequestAsync(), PK_CMD_ENCODER_RAW_VALUE_RESET, and PK_ERR_NOT_CONNECTED.
Referenced by PK_EncoderAllResetAsync(), and PK_EncoderSingleResetAsync().
PK_EncoderSingleResetAsync()
int PK_EncoderSingleResetAsync (sPoKeysDevice * device, uint8_t encoderIndex)
Reset a single encoder's raw value asynchronously.
Convenience wrapper for resetting a single encoder.
Parameters
device Pointer to PoKeys device structure
encoderIndex Index of encoder to reset (0-based)
Returns
PK_OK on success, error code on failure
Definition at line 600 of file PoKeysLibEncodersAsync.c.
References sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice::info, PK_EncoderRawValueResetAsync(), PK_ERR_GENERIC, and PK_ERR_NOT_CONNECTED.
PK_EncoderValuesGetAsync()
int PK_EncoderValuesGetAsync (sPoKeysDevice * device)
Starts asynchronous encoder values retrieval.
Parameters
device Pointer to PoKeys device
Returns
PK_OK on success, PK_ERR otherwise
Definition at line 477 of file PoKeysLibEncodersAsync.c.
References CreateRequestAsync(), sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice::info, sPoKeysDevice_Info::iUltraFastEncoders, PK_CMD_PULSE_ENGINE_V2, PK_EncoderValuesGetAsync_ProcessPage0(), PK_EncoderValuesGetAsync_ProcessPage1(), PK_EncoderValuesGetAsync_ProcessPage1_FastOnly(), PK_EncoderValuesGetAsync_ProcessUltraFast(), PK_ERR_NOT_CONNECTED, and PK_OK.
Referenced by PK_IOUpdateCycleAsync().
PK_EncoderValuesGetAsync_ProcessPage0()
int PK_EncoderValuesGetAsync_ProcessPage0 (sPoKeysDevice * device, const uint8_t * response)
Definition at line 254 of file PoKeysLibEncodersAsync.c.
References sPoKeysDevice::Encoders, sPoKeysEncoder::encoderValue, i, PK_ERR_TRANSFER, and PK_OK.
Referenced by PK_EncoderValuesGetAsync().
PK_EncoderValuesGetAsync_ProcessPage1()
int PK_EncoderValuesGetAsync_ProcessPage1 (sPoKeysDevice * device, const uint8_t * response)
Definition at line 264 of file PoKeysLibEncodersAsync.c.
References sPoKeysDevice::Encoders, sPoKeysEncoder::encoderValue, i, PK_ERR_TRANSFER, and PK_OK.
Referenced by PK_EncoderValuesGetAsync().
PK_EncoderValuesGetAsync_ProcessPage1_FastOnly()
int PK_EncoderValuesGetAsync_ProcessPage1_FastOnly (sPoKeysDevice * device, const uint8_t * response)
Definition at line 274 of file PoKeysLibEncodersAsync.c.
References sPoKeysDevice::Encoders, sPoKeysEncoder::encoderValue, i, PK_ERR_TRANSFER, and PK_OK.
Referenced by PK_EncoderValuesGetAsync().
PK_EncoderValuesGetAsync_ProcessUltraFast()
int PK_EncoderValuesGetAsync_ProcessUltraFast (sPoKeysDevice * device, const uint8_t * response)
Definition at line 284 of file PoKeysLibEncodersAsync.c.
References sPoKeysPEv2::EncoderIndexCount, sPoKeysPEv2::EncoderTicksPerRotation, sPoKeysPEv2::EncoderVelocity, sPoKeysDevice::PEv2, PK_ERR_TRANSFER, and PK_OK.
Referenced by PK_EncoderValuesGetAsync().
PK_EncoderValuesSetAsync()
int PK_EncoderValuesSetAsync (sPoKeysDevice * device)
Starts asynchronous encoder values set sequence.
Parameters
device Pointer to PoKeys device
Returns
PK_OK on success, PK_ERR otherwise
Definition at line 522 of file PoKeysLibEncodersAsync.c.
References CreateRequestAsyncWithPayload(), sPoKeysDevice::Encoders, sPoKeysEncoder::encoderValue, i, sPoKeysDevice_Info::iBasicEncoderCount, sPoKeysDevice::info, PK_ERR_NOT_CONNECTED, and PK_OK.
PK_FastEncodersOptionsParse()
int PK_FastEncodersOptionsParse (sPoKeysDevice * device, const uint8_t * response)
Parses FastEncodersOptions byte into individual HAL parameters.
Parameters
device Pointer to PoKeys device
response Pointer to received UDP packet
Returns
PK_OK on success, PK_ERR otherwise
Definition at line 216 of file PoKeysLibEncodersAsync.c.
References sPoKeysDevice::FastEncoder_disable_4x, sPoKeysDevice::FastEncoder_enable, sPoKeysDevice::FastEncoder_invert_E1, sPoKeysDevice::FastEncoder_invert_E2, sPoKeysDevice::FastEncoder_invert_E3, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, PK_ERR_TRANSFER, and PK_OK.
Referenced by PK_EncoderConfigurationGetAsync().
PK_UltraFastEncoderOptionsParse()
int PK_UltraFastEncoderOptionsParse (sPoKeysDevice * device, const uint8_t * response)
Definition at line 235 of file PoKeysLibEncodersAsync.c.
References PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::UltraFastEncoder_enable_4x, sPoKeysDevice::UltraFastEncoder_invert_direction, sPoKeysDevice::UltraFastEncoder_signal_mode, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
Referenced by PK_EncoderConfigurationGetAsync().