LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibCoreSocketsAsync.c File Reference
PoKeysLibCoreSocketsAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibCoreSocketsAsync.h"
#include <ifaddrs.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <net/if.h>
#include "hal.h"
Functions
int getChecksum (const uint8_t *buffer)
void InitializeNewDevice (sPoKeysDevice *device)
uint64_t get_current_time_us (void)
uint32_t * GetBroadcastAddressesAsync ()
int PK_SearchNetworkDevicesAsync_Start (sPoKeysNetworkDeviceSummary *devices, uint32_t timeout_ms, uint32_t serialNumberToFind)
Starts asynchronous search for PoKeys devices on the network.
int PK_SearchNetworkDevicesAsync_Process (void)
Processes incoming responses during asynchronous device search.
sPoKeysDevice * PK_ConnectToNetworkDeviceAsync (const sPoKeysNetworkDeviceSummary *device)
Connects to a PoKeys network device asynchronously (UDP only, Linux-only).
void PK_DisconnectNetworkDeviceAsync (sPoKeysDevice *device)
Disconnects from a PoKeys network device asynchronously.
int PK_SendEthRequestAsync (sPoKeysDevice *device)
Sends a PoKeys request packet asynchronously (non-blocking, realtime-safe).
int PK_RecvEthResponseAsync (sPoKeysDevice *device)
Receives a PoKeys response packet asynchronously (non-blocking, realtime-safe).
int PK_SendEthRequestNoResponseAsync (sPoKeysDevice *device)
Sends a PoKeys request packet asynchronously without expecting a response (fire-and-forget).
int PK_SendEthRequestBigAsync (sPoKeysDevice *device)
Sends a large (multi-part) PoKeys request asynchronously (non-blocking).
int PK_RecvEthBigResponseAsync (sPoKeysDevice *device)
Receives the response to a large (multi-part) PoKeys request asynchronously.
Variables
PoKeysDiscoveryContext discoveryCtx
Function Documentation
get_current_time_us()
uint64_t get_current_time_us (void)
Definition at line 38 of file PoKeysLibAsync.c.
References rtapi_get_time().
Referenced by PK_SearchNetworkDevicesAsync_Process(), PK_TimeoutAndRetryCheck(), and SendRequestAsync().
GetBroadcastAddressesAsync()
uint32_t * GetBroadcastAddressesAsync ()
Definition at line 22 of file PoKeysLibCoreSocketsAsync.c.
References hal_malloc().
getChecksum()
int getChecksum (const uint8_t * buffer)
Referenced by PK_RecvEthBigResponseAsync(), PK_RecvEthResponseAsync(), PK_SendEthRequestAsync(), PK_SendEthRequestBigAsync(), and PK_SendEthRequestNoResponseAsync().
InitializeNewDevice()
void InitializeNewDevice (sPoKeysDevice * device)
General pin settings PoKeys55, PoKeys56, PoKeys57 limitations
Pin codes used in PoKeys55 device are 0-based, e.g. pin 1 has pin code of 0, pin 55 has pin code of 54.
Analog input capable pins 43 to 47 have pin codes of 42 to 46.
Analog output capable pin 43 has pin code of 42.
PWM (pulse-width modulation) capable pins 17 to 22 have pin codes of 16-21 (PWM module outputs are in reversed order, e.g. pin 17 (pin coded as 16) is connected to PWM6 output – see specifications below).
PoKeys57CNC device supports PWM output function on 4 pins (pins 18, 20, 21 and 22). Different duty cycles can be assigned to each PWM output however, all outputs share the same PWM period. PWM outputs can be easily amplified using an external transistor and used for control of loads with increased increased current demand - pins with such function embedded are marked as OC (open-collector) in the pinout diagram. PoKeys PWM outputs can also be used to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). PoKeys devices have an in-built PWM module that operates at a fixed clock frequency (25 MHz). Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000)
PoKeys57CNCpro4x25 device supports PWM output function on pins 17 and 20. Pin 17 is wired to 0- 10 V output for spindle control – the output voltage is proportional to the duty cycle of the PWM output. PWM output on pin 20 is located on dedicated connector and can be easily amplified using an external transistor and used for controlling the loads with increased current demand – we offer MOSFET power switch adapter for such purposes in PoLabs online store. The frequency of the generated PWM signal can be changed – for the analog output functionality on pin 17 to operate as designed, a PWM frequency of 20 kHz is suggested. However, if needed, the frequency of PoKeys PWM outputs can be reduced – e.g. to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). In such case, analog output on pin 17 will not be operational. PoKeys devices have a built-in PWM module that operates at a fixed clock frequency of 25 MHz. Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000).
General pin settings PoKeys55, PoKeys56, PoKeys57 limitations
Pin codes used in PoKeys55 device are 0-based, e.g. pin 1 has pin code of 0, pin 55 has pin code of 54.
Analog input capable pins 43 to 47 have pin codes of 42 to 46.
Analog output capable pin 43 has pin code of 42.
PWM (pulse-width modulation) capable pins 17 to 22 have pin codes of 16-21 (PWM module outputs are in reversed order, e.g. pin 17 (pin coded as 16) is connected to PWM6 output – see specifications below).
PoKeys57CNC device supports PWM output function on 4 pins (pins 18, 20, 21 and 22). Different duty cycles can be assigned to each PWM output however, all outputs share the same PWM period. PWM outputs can be easily amplified using an external transistor and used for control of loads with increased increased current demand - pins with such function embedded are marked as OC (open-collector) in the pinout diagram. PoKeys PWM outputs can also be used to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). PoKeys devices have an in-built PWM module that operates at a fixed clock frequency (25 MHz). Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000)
PoKeys57CNCpro4x25 device supports PWM output function on pins 17 and 20. Pin 17 is wired to 0- 10 V output for spindle control – the output voltage is proportional to the duty cycle of the PWM output. PWM output on pin 20 is located on dedicated connector and can be easily amplified using an external transistor and used for controlling the loads with increased current demand – we offer MOSFET power switch adapter for such purposes in PoLabs online store. The frequency of the generated PWM signal can be changed – for the analog output functionality on pin 17 to operate as designed, a PWM frequency of 20 kHz is suggested. However, if needed, the frequency of PoKeys PWM outputs can be reduced – e.g. to drive various R/C servo motors that accept PWM signal with 50 Hz frequency (20 ms PWM period) and duty cycles between 5 and 10 % (1 to 2 ms). In such case, analog output on pin 17 will not be operational. PoKeys devices have a built-in PWM module that operates at a fixed clock frequency of 25 MHz. Both the PWM period and the PWM duty cycles must be expressed as number of module clock cycles (i.e. 20 ms PWM period equates to 0.020 x 25 000 000 = 500 000).
Definition at line 89 of file PoKeysLibCore.c.
References sPoKeysDevice::AnalogInput, sPoKeysDevice::AnalogOutput, hal_adcout_t::bit_weight, sPoKeysDevice::DeviceData, sPoKeysDevice_Data::DeviceTypeID, sPoKeysPinData::DigitalCounterAvailable, sPoKeysDevice::EasySensors, sPoKeysDevice::Encoders, sPoKeysDevice::FastEncodersConfiguration, sPoKeysDevice::FastEncodersOptions, hal_float_t, hal_malloc(), hal_adcout_t::high_limit, hal_adcout_t::hw_offset, i, sPoKeysDevice_Info::iEasySensors, sPoKeysDevice_Info::iEncodersCount, sPoKeysDevice_Info::iMatrixLED, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPoExtBus, sPoKeysDevice_Info::iPWMCount, sPoKeysDevice::LCD, hal_adcout_t::low_limit, sPoKeysDevice::matrixKB, sPoKeysDevice::MatrixLED, sPoKeysPWM::max_Voltage, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::netDeviceData, hal_adcout_t::offset, sPoKeysDevice::PEv2, sPoKeysDevice::Pins, PK_DeviceDataGet(), PK_DeviceID_PoKeys57CNC, PK_DeviceID_PoKeys57CNCpro4x25, PK_FillPWMPinNumbers(), PK_IsCounterAvailable(), sPoKeysDevice::PoExtBusData, sPoKeysDevice::PWM, sPoKeysPWM::PWManalogOutputs, sPoKeysPWM::PWMduty, sPoKeysPWM::PWMenabledChannels, sPoKeysPWM::PWMperiod, sPoKeysPWM::PWMpinIDs, sPoKeysDevice::readRetries, sPoKeysDevice::request, sPoKeysDevice::response, RTAPI_MSG_ERR, rtapi_print_msg(), hal_adcout_t::scale, sPoKeysDevice::sendRetries, sPoKeysDevice::socketTimeout, sPoKeysDevice::UltraFastEncoderConfiguration, sPoKeysDevice::UltraFastEncoderFilter, and sPoKeysDevice::UltraFastEncoderOptions.
Referenced by PK_ConnectToDevice(), PK_ConnectToNetworkDevice(), PK_ConnectToNetworkDeviceAsync(), PK_ConnectToPoKeysDevice_Ethernet(), and PK_ConnectToPoKeysDevice_USB().
PK_ConnectToNetworkDeviceAsync()
sPoKeysDevice * PK_ConnectToNetworkDeviceAsync (const sPoKeysNetworkDeviceSummary * device)
Connects to a PoKeys network device asynchronously (UDP only, Linux-only).
This function creates a non-blocking UDP socket and prepares the connection structure for communicating with the PoKeys device. No blocking calls (like connect or select) are used, ensuring realtime safety.
Parameters
device Pointer to the sPoKeysNetworkDeviceSummary structure containing the device IP address and connection parameters.
Returns
Pointer to an initialized sPoKeysDevice structure on success, or NULL on failure (e.g., memory allocation failure or socket creation error).
Note
Only UDP connections are supported (TCP not implemented here).
Socket is set to non-blocking mode immediately after creation.
All memory allocations use hal_malloc() for realtime safety.
The resulting sPoKeysDevice must be managed and eventually released properly.
@usage After calling PK_SearchNetworkDevicesAsync and finding a device, use this function to establish a realtime-safe UDP connection to it.
See also
PK_SearchNetworkDevicesAsync_Start()
PK_SearchNetworkDevicesAsync_Process()
Definition at line 229 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::connectionParam, sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, hal_malloc(), InitializeNewDevice(), sPoKeysNetworkDeviceSummary::IPaddress, PK_DeviceType_NetworkDevice, and sPoKeysNetworkDeviceSummary::useUDP.
PK_DisconnectNetworkDeviceAsync()
void PK_DisconnectNetworkDeviceAsync (sPoKeysDevice * device)
Disconnects from a PoKeys network device asynchronously.
This function closes the non-blocking UDP socket and releases any allocated memory associated with the device connection.
Parameters
device Pointer to the sPoKeysDevice structure.
Note
This function is non-blocking and safe for use inside a realtime loop.
It ensures that all resources are properly released.
The device structure itself is not freed, only the connection-related resources.
See also
PK_ConnectToNetworkDeviceAsync()
Definition at line 291 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, and PK_DeviceType_NetworkDevice.
PK_RecvEthBigResponseAsync()
int PK_RecvEthBigResponseAsync (sPoKeysDevice * device)
Receives the response to a large (multi-part) PoKeys request asynchronously.
After sending a multi-part request with PK_SendEthRequestBigAsync(), this function checks (non-blocking) if a valid response packet from the device is available.
Verifies packet start byte, request ID match, and checksum integrity.
Parameters
device Pointer to the sPoKeysDevice structure.
Returns
PK_OK if a valid 64-byte response packet was received, PK_ERR_AGAIN if no packet is available yet (socket would block), PK_ERR_TRANSFER if packet received is invalid or corrupted.
Note
Intended for use inside a polling loop after a big request was sent.
No retries or waiting are performed internally (caller should retry if necessary).
This method is realtime-safe and non-blocking.
See also
PK_SendEthRequestBigAsync()
Definition at line 524 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::devHandle, getChecksum(), PK_ERR_AGAIN, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::requestID, and sPoKeysDevice::response.
PK_RecvEthResponseAsync()
int PK_RecvEthResponseAsync (sPoKeysDevice * device)
Receives a PoKeys response packet asynchronously (non-blocking, realtime-safe).
Attempts to read a single UDP packet from the PoKeys device without blocking. Validates the received packet against the expected request ID and checksum. If successful, the response is stored in device->response.
Parameters
device Pointer to the sPoKeysDevice structure.
Returns
PK_OK if a valid response was received, PK_ERR_AGAIN if no data is currently available (non-fatal, try again later), PK_ERR_TRANSFER if an invalid or corrupted response was received, PK_ERR_GENERIC on invalid device handle.
Note
This function should be called periodically after sending a request.
It is non-blocking and safe for use inside a realtime loop.
If PK_ERR_AGAIN is returned, simply continue polling.
See also
PK_SendEthRequestAsync()
Definition at line 369 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::devHandle, getChecksum(), PK_ERR_AGAIN, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::requestID, and sPoKeysDevice::response.
PK_SearchNetworkDevicesAsync_Process()
int PK_SearchNetworkDevicesAsync_Process (void)
Processes incoming responses during asynchronous device search.
This function must be called periodically (e.g., once per realtime cycle) after PK_SearchNetworkDevicesAsync_Start() has been called. It checks for incoming UDP packets without blocking and parses valid device discovery responses.
Returns
PK_OK if no device yet or still waiting, PK_OK_FOUND if a device matching serialNumberToFind was found, PK_ERR_TIMEOUT if the discovery timeout expired, PK_ERR_TRANSFER on receive errors.
Note
This function is realtime-safe (no blocking, no dynamic memory).
Must be called repeatedly until PK_OK_FOUND or PK_ERR_TIMEOUT is returned.
Detected devices are appended to the devices array provided at Start().
After timeout or finding a specific device, the discovery socket is closed automatically.
See also
PK_SearchNetworkDevicesAsync_Start()
Definition at line 139 of file PoKeysLibCoreSocketsAsync.c.
References PoKeysDiscoveryContext::devices, sPoKeysNetworkDeviceSummary::DHCP, discoveryCtx, sPoKeysNetworkDeviceSummary::FirmwareVersionMajor, sPoKeysNetworkDeviceSummary::FirmwareVersionMinor, get_current_time_us(), sPoKeysNetworkDeviceSummary::hostIP, sPoKeysNetworkDeviceSummary::HWtype, sPoKeysNetworkDeviceSummary::IPaddress, PoKeysDiscoveryContext::nrOfDetectedBoards, PK_ERR_SOCKET, PK_ERR_TIMEOUT, PK_ERR_TRANSFER, PK_OK, PK_OK_FOUND, sPoKeysNetworkDeviceSummary::SerialNumber, PoKeysDiscoveryContext::serialNumberToFind, PoKeysDiscoveryContext::start_time_us, PoKeysDiscoveryContext::timeout_us, and PoKeysDiscoveryContext::txSocket.
PK_SearchNetworkDevicesAsync_Start()
int PK_SearchNetworkDevicesAsync_Start (sPoKeysNetworkDeviceSummary * devices, uint32_t timeout_ms, uint32_t serialNumberToFind)
Starts asynchronous search for PoKeys devices on the network.
This function sends a UDP broadcast discovery packet to all available broadcast addresses and initializes an asynchronous search context. It must be followed by regular calls to PK_SearchNetworkDevicesAsync_Process() to receive and process incoming responses.
Parameters
devices Pointer to an array of sPoKeysNetworkDeviceSummary structures to store found devices.
timeout_ms Timeout duration for the discovery process in milliseconds.
serialNumberToFind Optional serial number to stop discovery early if a specific device is found (0 = find all).
Returns
PK_OK on success, PK_ERR_SOCKET on socket creation failure, PK_ERR otherwise.
Note
Must be called once to initiate discovery.
Does not block. Discovery proceeds asynchronously.
Devices will be filled in the provided array as responses are received.
See also
PK_SearchNetworkDevicesAsync_Process()
Definition at line 79 of file PoKeysLibCoreSocketsAsync.c.
PK_SendEthRequestAsync()
int PK_SendEthRequestAsync (sPoKeysDevice * device)
Sends a PoKeys request packet asynchronously (non-blocking, realtime-safe).
Prepares the request buffer (sets command byte, request ID, checksum) and sends it via UDP to the PoKeys device using a non-blocking socket.
Parameters
device Pointer to the sPoKeysDevice structure.
Returns
PK_OK if the request was sent successfully (64 bytes), PK_ERR_TRANSFER if sending failed, PK_ERR_GENERIC on invalid device handle.
Note
This function only performs the sending operation.
Response must be checked separately via PK_RecvEthResponseAsync().
Device must have been previously connected with PK_ConnectToNetworkDeviceAsync().
See also
PK_RecvEthResponseAsync()
Definition at line 329 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and sPoKeysDevice::requestID.
PK_SendEthRequestBigAsync()
int PK_SendEthRequestBigAsync (sPoKeysDevice * device)
Sends a large (multi-part) PoKeys request asynchronously (non-blocking).
This function splits a prepared PoKeys request into 8 × 64-byte segments and sends them as a single 512-byte UDP packet to the target device.
This is typically used for sending larger payloads like motion buffers or extended data.
Parameters
device Pointer to the sPoKeysDevice structure, with valid multiPartData populated.
Returns
PK_OK if the multi-part packet was sent successfully (512 bytes transmitted), PK_ERR_TRANSFER if sending failed, PK_ERR_GENERIC if device or buffers are invalid.
Note
No retries or blocking waits are performed inside this function.
Only works with UDP connections (TCP not supported for multi-part transfers).
Make sure device->multiPartData is filled with 448 bytes of payload data before calling.
See also
PK_RecvEthBigResponseAsync()
Definition at line 472 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), i, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::multiPartData, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and sPoKeysDevice::requestID.
PK_SendEthRequestNoResponseAsync()
int PK_SendEthRequestNoResponseAsync (sPoKeysDevice * device)
Sends a PoKeys request packet asynchronously without expecting a response (fire-and-forget).
Prepares a UDP packet with correct formatting (start byte, request ID, checksum) and sends it once over the network to the PoKeys device. No response is waited for.
This is typically used for operations where the device executes the command without sending a confirmation (e.g., certain control or update commands).
Parameters
device Pointer to the sPoKeysDevice structure.
Returns
PK_OK if the packet was sent successfully (64 bytes transmitted), PK_ERR_TRANSFER if sending failed, PK_ERR_GENERIC if device pointer or connection is invalid.
Note
The socket must be pre-configured and connected via PK_ConnectToNetworkDeviceAsync().
No retries or waiting are done inside this function (caller must handle retries if needed).
Works in realtime-safe LinuxCNC HAL loops (non-blocking sendto()).
@usage
Prepare your device connection first.
Then call PK_SendEthRequestNoResponseAsync() whenever you need to trigger an action without awaiting feedback.
See also
PK_ConnectToNetworkDeviceAsync()
PK_SendEthRequestAsync()
Definition at line 428 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and sPoKeysDevice::requestID.
Variable Documentation
discoveryCtx
PoKeysDiscoveryContext discoveryCtx
Definition at line 20 of file PoKeysLibCoreSocketsAsync.c.
Referenced by PK_SearchNetworkDevicesAsync_Process().