LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibI2C.c File Reference
PoKeysLibI2C.c File Reference
I\2C communication helpers (command 0xDB).
#include "PoKeysLibHal.h"
#include "PoKeysLibCore.h"
#include "PoKeysLibAsync.h"
Functions
int32_t PK_I2CSetStatus (sPoKeysDevice *device, uint8_t activated)
Enable or disable the I\2C interface (command 0xDB/0x01).
int32_t PK_I2CGetStatus (sPoKeysDevice *device, uint8_t *activated)
Query whether the I\2C bus is enabled (command 0xDB/0x02).
int32_t PK_I2CWriteStart (sPoKeysDevice *device, uint8_t address, uint8_t *buffer, uint8_t iDataLength)
Initiate an I\2C write transaction (command 0xDB/0x10).
int32_t PK_I2CWriteAndReadStart (sPoKeysDevice *device, uint8_t address, uint8_t *buffer, uint8_t iDataLengthWrite, uint8_t iDataLengthRead)
Write data and queue a subsequent read (command 0xDB/0x10).
int32_t PK_I2CWriteStatusGet (sPoKeysDevice *device, uint8_t *status)
Retrieve the status of the last I\2C write operation (command 0xDB/0x11).
int32_t PK_I2CReadStart (sPoKeysDevice *device, uint8_t address, uint8_t iDataLength)
Initiate an I\2C read transaction (command 0xDB/0x20).
int32_t PK_I2CReadStatusGet (sPoKeysDevice *device, uint8_t *status, uint8_t *iReadBytes, uint8_t *buffer, uint8_t iMaxBufferLength)
Obtain the result of an I\2C read command (command 0xDB/0x21).
int32_t PK_I2CBusScanStart (sPoKeysDevice *device)
Begin scanning the I\2C bus for devices (command 0xDB/0x30).
int32_t PK_I2CBusScanGetResults (sPoKeysDevice *device, uint8_t *status, uint8_t *presentDevices, uint8_t iMaxDevices)
Obtain the results of an I\2C bus scan (command 0xDB/0x31).
Detailed Description
I\2C communication helpers (command 0xDB).
These functions wrap the PoKeys I\2C command set and transfer data between the host and a connected PoKeys device.
Definition in file PoKeysLibI2C.c.
Function Documentation
PK_I2CBusScanGetResults()
int32_t PK_I2CBusScanGetResults (sPoKeysDevice * device, uint8_t * status, uint8_t * presentDevices, uint8_t iMaxDevices)
Obtain the results of an I\2C bus scan (command 0xDB/0x31).
After PK_I2CBusScanStart() completes, this helper reads the scan bitmap and stores device presence information into presentDevices.
Parameters
device Handle to an opened PoKeys device.
status Receives the scan status (see ePK_I2C_STATUS).
presentDevices Array that receives one byte per address indicating whether a device acknowledged.
iMaxDevices Maximum number of addresses to report (up to 128).
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 249 of file PoKeysLibI2C.c.
References CreateRequest(), i, PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_I2C_STAT_COMPLETE, PK_I2C_STAT_ERR, PK_I2C_STAT_OK, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_I2CBusScanStart()
int32_t PK_I2CBusScanStart (sPoKeysDevice * device)
Begin scanning the I\2C bus for devices (command 0xDB/0x30).
The device searches all 7-bit addresses. Completion is checked with PK_I2CBusScanGetResults().
Parameters
device Handle to an opened PoKeys device.
Returns
PK_OK on command acceptance or PK_ERR_NOT_CONNECTED when device is NULL.
Definition at line 227 of file PoKeysLibI2C.c.
References CreateRequest(), PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_I2CGetStatus()
int32_t PK_I2CGetStatus (sPoKeysDevice * device, uint8_t * activated)
Query whether the I\2C bus is enabled (command 0xDB/0x02).
Parameters
device Handle to an opened PoKeys device.
activated Pointer that receives the activation state.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 60 of file PoKeysLibI2C.c.
References CreateRequest(), PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_I2CReadStart()
int32_t PK_I2CReadStart (sPoKeysDevice * device, uint8_t address, uint8_t iDataLength)
Initiate an I\2C read transaction (command 0xDB/0x20).
The device is commanded to read iDataLength bytes from the slave at address. The received data is later obtained with PK_I2CReadStatusGet().
Parameters
device Handle to an opened PoKeys device.
address I\2C slave address.
iDataLength Number of bytes to read (0–32).
Returns
PK_OK on command acceptance or PK_ERR_NOT_CONNECTED when device is NULL.
Definition at line 161 of file PoKeysLibI2C.c.
References CreateRequest(), PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_I2CReadStatusGet()
int32_t PK_I2CReadStatusGet (sPoKeysDevice * device, uint8_t * status, uint8_t * iReadBytes, uint8_t * buffer, uint8_t iMaxBufferLength)
Obtain the result of an I\2C read command (command 0xDB/0x21).
After a read has been started with PK_I2CReadStart() or PK_I2CWriteAndReadStart(), this function polls the device for completion and copies the returned bytes into buffer.
Parameters
device Handle to an opened PoKeys device.
status Receives the operation status (see ePK_I2C_STATUS).
iReadBytes Number of bytes actually read on success.
buffer Destination buffer for the received data.
iMaxBufferLength Size of buffer in bytes.
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL, PK_ERR_TRANSFER on communication failure or PK_ERR_GENERIC when the device reports more data than fits into 32 bytes.
Definition at line 187 of file PoKeysLibI2C.c.
References CreateRequest(), i, PK_CMD_I2C_COMMUNICATION, PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_I2C_STAT_COMPLETE, PK_I2C_STAT_ERR, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().
PK_I2CSetStatus()
int32_t PK_I2CSetStatus (sPoKeysDevice * device, uint8_t activated)
Enable or disable the I\2C interface (command 0xDB/0x01).
The PoKeys device keeps the I\2C engine enabled at all times. This helper only sends the activation flag for compatibility with older firmware.
Parameters
device Handle to an opened PoKeys device.
activated Non-zero to enable the bus, zero to disable it.
Returns
PK_OK on success or PK_ERR_NOT_CONNECTED if device is NULL.
Definition at line 44 of file PoKeysLibI2C.c.
References CreateRequest(), PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_I2CWriteAndReadStart()
int32_t PK_I2CWriteAndReadStart (sPoKeysDevice * device, uint8_t address, uint8_t * buffer, uint8_t iDataLengthWrite, uint8_t iDataLengthRead)
Write data and queue a subsequent read (command 0xDB/0x10).
This combines a write and read phase. Up to 32 bytes are written from buffer and the device is instructed to read iDataLengthRead bytes afterwards. The read data is obtained later with PK_I2CReadStatusGet().
Parameters
device Handle to an opened PoKeys device.
address I\2C slave address.
buffer Data to write.
iDataLengthWrite Number of bytes to write (0–32).
iDataLengthRead Number of bytes expected to be read back.
Returns
PK_OK on command acceptance or PK_ERR_NOT_CONNECTED when device is NULL.
Definition at line 114 of file PoKeysLibI2C.c.
References CreateRequest(), i, PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_I2CWriteStart()
int32_t PK_I2CWriteStart (sPoKeysDevice * device, uint8_t address, uint8_t * buffer, uint8_t iDataLength)
Initiate an I\2C write transaction (command 0xDB/0x10).
Up to 32 bytes from buffer are copied and sent to the device using PK_CMD_I2C_COMMUNICATION with subcommand 0x10.
Parameters
device Handle to an opened PoKeys device.
address 7-bit I\2C slave address.
buffer Data to transmit.
iDataLength Number of bytes to send (0–32).
Returns
PK_OK on command acceptance or PK_ERR_NOT_CONNECTED when device is NULL.
Definition at line 84 of file PoKeysLibI2C.c.
References CreateRequest(), i, PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, sPoKeysDevice::request, and SendRequest().
PK_I2CWriteStatusGet()
int32_t PK_I2CWriteStatusGet (sPoKeysDevice * device, uint8_t * status)
Retrieve the status of the last I\2C write operation (command 0xDB/0x11).
Parameters
device Handle to an opened PoKeys device.
status Receives the result (see ePK_I2C_STATUS).
Returns
PK_OK on success, PK_ERR_NOT_CONNECTED if device is NULL or PK_ERR_TRANSFER on communication failure.
Definition at line 137 of file PoKeysLibI2C.c.
References CreateRequest(), PK_CMD_I2C_COMMUNICATION, PK_ERR_NOT_CONNECTED, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, sPoKeysDevice::response, and SendRequest().