LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibAdvancedRTAsync.c File Reference
PoKeysLibAdvancedRTAsync.c File Reference
#include "PoKeysLibHal.h"
#include "PoKeysLibAsync.h"
#include <string.h>
Functions
int PK_DigitalOutputSetMultipleAsync (sPoKeysDevice *device, const uint8_t *pinList, const uint8_t *valueList, uint8_t count)
Set multiple digital outputs in a single efficient operation (async)
int PK_DigitalCounterGetSelectedAsync (sPoKeysDevice *device, const uint8_t *pinList, uint8_t count)
Get digital counter values for specific pins only (async)
int PK_PWMUpdateSelectedChannelsAsync (sPoKeysDevice *device, uint8_t channelMask, const uint32_t *dutyCycles)
Set PWM duty cycles for selected channels only (async)
int PK_SystemStatusGetAllAsync (sPoKeysDevice *device)
Get comprehensive system status in one operation (async)
int PK_IOUpdateCycleAsync (sPoKeysDevice *device)
Perform complete IO update cycle (async)
int PK_EmergencyStopAllAsync (sPoKeysDevice *device)
Emergency stop all motion and outputs (async)
int PK_CommunicationTestAsync (sPoKeysDevice *device, uint8_t testCount)
Test device communication and RT timing (async)
Function Documentation
PK_CommunicationTestAsync()
int PK_CommunicationTestAsync (sPoKeysDevice * device, uint8_t testCount)
Test device communication and RT timing (async)
Performs communication test by sending ping commands and measuring response times. Useful for RT system validation.
Parameters
device Target device handle
testCount Number of ping tests to perform
Returns
PK_OK on success, error code on failure
Definition at line 265 of file PoKeysLibAdvancedRTAsync.c.
References i, PK_DeviceAliveCheckAsync(), PK_ERR_GENERIC, PK_ERR_NOT_CONNECTED, and PK_OK.
PK_DigitalCounterGetSelectedAsync()
int PK_DigitalCounterGetSelectedAsync (sPoKeysDevice * device, const uint8_t * pinList, uint8_t count)
Get digital counter values for specific pins only (async)
More efficient than reading all counters when only specific ones are needed.
Parameters
device Target device handle
pinList Array of pin numbers to read
count Number of pins to read
Returns
PK_OK on success, error code on failure
Definition at line 54 of file PoKeysLibAdvancedRTAsync.c.
PK_DigitalOutputSetMultipleAsync()
int PK_DigitalOutputSetMultipleAsync (sPoKeysDevice * device, const uint8_t * pinList, const uint8_t * valueList, uint8_t count)
Set multiple digital outputs in a single efficient operation (async)
Updates only specified pins without affecting others. More efficient than updating all pins when only a few need changes.
Parameters
device Target device handle
pinList Array of pin numbers to update
valueList Array of values corresponding to pins
count Number of pins to update
Returns
PK_OK on success, error code on failure
Definition at line 27 of file PoKeysLibAdvancedRTAsync.c.
PK_EmergencyStopAllAsync()
int PK_EmergencyStopAllAsync (sPoKeysDevice * device)
Emergency stop all motion and outputs (async)
Immediately stops all motion, disables PWM outputs, and sets all digital outputs to safe state. Critical for emergency situations.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 223 of file PoKeysLibAdvancedRTAsync.c.
References sPoKeysPinData::DigitalValueSet, i, sPoKeysDevice::info, sPoKeysDevice_Info::iPinCount, sPoKeysDevice_Info::iPulseEnginev2, sPoKeysDevice::PEv2, sPoKeysPinData::PinFunction, sPoKeysDevice::Pins, PK_DigitalIOSetGetAsync(), PK_ERR_NOT_CONNECTED, PK_OK, PK_PEv2_StatusGetAsync(), PK_PinCap_digitalOutput, PK_PWMUpdateAsync(), sPoKeysPEv2::PulseEngineState, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, and sPoKeysPWM::PWMenabledChannels.
PK_IOUpdateCycleAsync()
int PK_IOUpdateCycleAsync (sPoKeysDevice * device)
Perform complete IO update cycle (async)
Combines all common IO operations into a single efficient batch:
Digital IO set/get
Analog input reading
PWM updates
Counter reading
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 173 of file PoKeysLibAdvancedRTAsync.c.
References i, sPoKeysDevice_Info::iAnalogInputs, sPoKeysDevice_Info::iDigitalCounters, sPoKeysDevice::info, PK_AnalogIOGetAsync(), PK_DigitalCounterGetAsync(), PK_DigitalIOSetGetAsync(), PK_EncoderValuesGetAsync(), PK_ERR_NOT_CONNECTED, PK_OK, PK_PWMUpdateAsync(), sPoKeysDevice::PWM, and sPoKeysPWM::PWMenabledChannels.
PK_PWMUpdateSelectedChannelsAsync()
int PK_PWMUpdateSelectedChannelsAsync (sPoKeysDevice * device, uint8_t channelMask, const uint32_t * dutyCycles)
Set PWM duty cycles for selected channels only (async)
Updates only specified PWM channels without affecting others. Efficient for applications that don't use all 6 PWM channels.
Parameters
device Target device handle
channelMask Bitmask of channels to update (bit 0 = channel 0, etc.)
dutyCycles Array of duty cycle values for enabled channels
Returns
PK_OK on success, error code on failure
Definition at line 83 of file PoKeysLibAdvancedRTAsync.c.
References CreateRequestAsync(), PK_CMD_PWM_CONFIGURATION, PK_ERR_GENERIC, sPoKeysDevice::PWM, sPoKeysPWM::PWMduty, and sPoKeysPWM::PWMperiod.
PK_SystemStatusGetAllAsync()
int PK_SystemStatusGetAllAsync (sPoKeysDevice * device)
Get comprehensive system status in one operation (async)
Combines device status, load monitoring, and connection health into a single efficient async operation for system monitoring.
Parameters
device Target device handle
Returns
PK_OK on success, error code on failure
Definition at line 132 of file PoKeysLibAdvancedRTAsync.c.
References sPoKeysDevice_Info::iLoadStatus, sPoKeysDevice::info, PK_DeviceAliveCheckAsync(), PK_DeviceDataGetAsync(), PK_DeviceErrorStatusAsync(), PK_DeviceLoadStatusAsync(), PK_ERR_NOT_CONNECTED, and PK_OK.