LinuxCNC PoKeysLib-Comp: /home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/external/pokeysHal/PoKeysLibCoreSocketsAsync.h File Reference
PoKeysLibCoreSocketsAsync.h File Reference
#include "PoKeysLibHal.h"
Data Structures
struct PoKeysDiscoveryContext
Macros
#define PK_ERR_SOCKET (-201)
#define PK_ERR_TIMEOUT (-202)
#define PK_ERR_AGAIN (-203)
#define PK_OK_FOUND (201)
Functions
int32_t PK_SearchNetworkDevicesAsync (sPoKeysNetworkDeviceSummary *devices, uint32_t timeout_ms, uint32_t serialNumberToFind)
sPoKeysDevice * PK_ConnectToNetworkDeviceAsync (const sPoKeysNetworkDeviceSummary *device)
Connects to a PoKeys network device asynchronously (UDP only, Linux-only).
int32_t PK_SendEthRequestAsync (sPoKeysDevice *device)
Sends a PoKeys request packet asynchronously (non-blocking, realtime-safe).
int32_t PK_SendEthRequestNoResponseAsync (sPoKeysDevice *device)
Sends a PoKeys request packet asynchronously without expecting a response (fire-and-forget).
int32_t PK_SendEthRequestBigAsync (sPoKeysDevice *device)
Sends a large (multi-part) PoKeys request asynchronously (non-blocking).
int32_t PK_RecvEthBigResponseAsync (sPoKeysDevice *device)
Receives the response to a large (multi-part) PoKeys request asynchronously.
Macro Definition Documentation
PK_ERR_AGAIN
#define PK_ERR_AGAIN (-203)
Definition at line 12 of file PoKeysLibCoreSocketsAsync.h.
PK_ERR_SOCKET
#define PK_ERR_SOCKET (-201)
Definition at line 10 of file PoKeysLibCoreSocketsAsync.h.
PK_ERR_TIMEOUT
#define PK_ERR_TIMEOUT (-202)
Definition at line 11 of file PoKeysLibCoreSocketsAsync.h.
PK_OK_FOUND
#define PK_OK_FOUND (201)
Definition at line 13 of file PoKeysLibCoreSocketsAsync.h.
Function Documentation
PK_ConnectToNetworkDeviceAsync()
sPoKeysDevice * PK_ConnectToNetworkDeviceAsync (const sPoKeysNetworkDeviceSummary * device)
Connects to a PoKeys network device asynchronously (UDP only, Linux-only).
This function creates a non-blocking UDP socket and prepares the connection structure for communicating with the PoKeys device. No blocking calls (like connect or select) are used, ensuring realtime safety.
Parameters
device Pointer to the sPoKeysNetworkDeviceSummary structure containing the device IP address and connection parameters.
Returns
Pointer to an initialized sPoKeysDevice structure on success, or NULL on failure (e.g., memory allocation failure or socket creation error).
Note
Only UDP connections are supported (TCP not implemented here).
Socket is set to non-blocking mode immediately after creation.
All memory allocations use hal_malloc() for realtime safety.
The resulting sPoKeysDevice must be managed and eventually released properly.
@usage After calling PK_SearchNetworkDevicesAsync and finding a device, use this function to establish a realtime-safe UDP connection to it.
See also
PK_SearchNetworkDevicesAsync_Start()
PK_SearchNetworkDevicesAsync_Process()
Definition at line 229 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::connectionParam, sPoKeysDevice::connectionType, sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, hal_malloc(), InitializeNewDevice(), sPoKeysNetworkDeviceSummary::IPaddress, PK_DeviceType_NetworkDevice, and sPoKeysNetworkDeviceSummary::useUDP.
PK_RecvEthBigResponseAsync()
int32_t PK_RecvEthBigResponseAsync (sPoKeysDevice * device)
Receives the response to a large (multi-part) PoKeys request asynchronously.
After sending a multi-part request with PK_SendEthRequestBigAsync(), this function checks (non-blocking) if a valid response packet from the device is available.
Verifies packet start byte, request ID match, and checksum integrity.
Parameters
device Pointer to the sPoKeysDevice structure.
Returns
PK_OK if a valid 64-byte response packet was received, PK_ERR_AGAIN if no packet is available yet (socket would block), PK_ERR_TRANSFER if packet received is invalid or corrupted.
Note
Intended for use inside a polling loop after a big request was sent.
No retries or waiting are performed internally (caller should retry if necessary).
This method is realtime-safe and non-blocking.
See also
PK_SendEthRequestBigAsync()
Definition at line 524 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::devHandle, getChecksum(), PK_ERR_AGAIN, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::requestID, and sPoKeysDevice::response.
PK_SearchNetworkDevicesAsync()
int32_t PK_SearchNetworkDevicesAsync (sPoKeysNetworkDeviceSummary * devices, uint32_t timeout_ms, uint32_t serialNumberToFind)
PK_SendEthRequestAsync()
int32_t PK_SendEthRequestAsync (sPoKeysDevice * device)
Sends a PoKeys request packet asynchronously (non-blocking, realtime-safe).
Prepares the request buffer (sets command byte, request ID, checksum) and sends it via UDP to the PoKeys device using a non-blocking socket.
Parameters
device Pointer to the sPoKeysDevice structure.
Returns
PK_OK if the request was sent successfully (64 bytes), PK_ERR_TRANSFER if sending failed, PK_ERR_GENERIC on invalid device handle.
Note
This function only performs the sending operation.
Response must be checked separately via PK_RecvEthResponseAsync().
Device must have been previously connected with PK_ConnectToNetworkDeviceAsync().
See also
PK_RecvEthResponseAsync()
Definition at line 329 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and sPoKeysDevice::requestID.
PK_SendEthRequestBigAsync()
int32_t PK_SendEthRequestBigAsync (sPoKeysDevice * device)
Sends a large (multi-part) PoKeys request asynchronously (non-blocking).
This function splits a prepared PoKeys request into 8 × 64-byte segments and sends them as a single 512-byte UDP packet to the target device.
This is typically used for sending larger payloads like motion buffers or extended data.
Parameters
device Pointer to the sPoKeysDevice structure, with valid multiPartData populated.
Returns
PK_OK if the multi-part packet was sent successfully (512 bytes transmitted), PK_ERR_TRANSFER if sending failed, PK_ERR_GENERIC if device or buffers are invalid.
Note
No retries or blocking waits are performed inside this function.
Only works with UDP connections (TCP not supported for multi-part transfers).
Make sure device->multiPartData is filled with 448 bytes of payload data before calling.
See also
PK_RecvEthBigResponseAsync()
Definition at line 472 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), i, sPoKeysDevice::multiPartBuffer, sPoKeysDevice::multiPartData, PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and sPoKeysDevice::requestID.
PK_SendEthRequestNoResponseAsync()
int32_t PK_SendEthRequestNoResponseAsync (sPoKeysDevice * device)
Sends a PoKeys request packet asynchronously without expecting a response (fire-and-forget).
Prepares a UDP packet with correct formatting (start byte, request ID, checksum) and sends it once over the network to the PoKeys device. No response is waited for.
This is typically used for operations where the device executes the command without sending a confirmation (e.g., certain control or update commands).
Parameters
device Pointer to the sPoKeysDevice structure.
Returns
PK_OK if the packet was sent successfully (64 bytes transmitted), PK_ERR_TRANSFER if sending failed, PK_ERR_GENERIC if device pointer or connection is invalid.
Note
The socket must be pre-configured and connected via PK_ConnectToNetworkDeviceAsync().
No retries or waiting are done inside this function (caller must handle retries if needed).
Works in realtime-safe LinuxCNC HAL loops (non-blocking sendto()).
@usage
Prepare your device connection first.
Then call PK_SendEthRequestNoResponseAsync() whenever you need to trigger an action without awaiting feedback.
See also
PK_ConnectToNetworkDeviceAsync()
PK_SendEthRequestAsync()
Definition at line 428 of file PoKeysLibCoreSocketsAsync.c.
References sPoKeysDevice::devHandle, sPoKeysDevice::devHandle2, getChecksum(), PK_ERR_GENERIC, PK_ERR_TRANSFER, PK_OK, sPoKeysDevice::request, and sPoKeysDevice::requestID.