LinuxCNC PoKeysLib-Comp: /usr/include/linuxcnc/rtapi.h File Reference
rtapi.h File Reference
#include <stddef.h>
#include <stdarg.h>
#include <spawn.h>
Macros
#define RTAPI_NAME_LEN 31 /* length for module, etc, names */
#define RTAPI_BEGIN_DECLS
#define RTAPI_END_DECLS
#define rtapi_request_region(base, size, name) ((void*)-1)
#define rtapi_release_region(base, size) ((void)0)
Typedefs
typedef void(* rtapi_msg_handler_t) (msg_level_t level, const char *fmt, va_list ap)
Enumerations
enum msg_level_t {
RTAPI_MSG_NONE = 0 , RTAPI_MSG_ERR , RTAPI_MSG_WARN , RTAPI_MSG_INFO ,
RTAPI_MSG_DBG , RTAPI_MSG_ALL
}
Functions
RTAPI_BEGIN_DECLS int rtapi_init (const char *modname)
int rtapi_exit (int module_id)
int rtapi_snprintf (char *buf, unsigned long int size, const char *fmt,...) __attribute__((format(printf
int int rtapi_vsnprintf (char *buf, unsigned long size, const char *fmt, va_list ap)
void rtapi_print (const char *fmt,...) __attribute__((format(printf
void rtapi_print_msg (msg_level_t level, const char *fmt,...) __attribute__((format(printf
void int rtapi_set_msg_level (int level)
int rtapi_get_msg_level (void)
void rtapi_delay (long int nsec)
long int rtapi_delay_max (void)
long long int rtapi_get_time (void)
long long int rtapi_get_clocks (void)
int rtapi_shmem_new (int key, int module_id, unsigned long int size)
int rtapi_shmem_delete (int shmem_id, int module_id)
int rtapi_shmem_getptr (int shmem_id, void **ptr)
int rtapi_fifo_new (int key, int module_id, unsigned long int size, char mode)
int rtapi_fifo_delete (int fifo_id, int module_id)
int rtapi_fifo_read (int fifo_id, char *buf, unsigned long int size)
int rtapi_fifo_write (int fifo_id, char *buf, unsigned long int size)
void rtapi_outb (unsigned char byte, unsigned int port)
unsigned char rtapi_inb (unsigned int port)
long int simple_strtol (const char *nptr, char **endptr, int base)
int rtapi_spawn_as_root (pid_t *pid, const char *path, const posix_spawn_file_actions_t *file_actions, const posix_spawnattr_t *attrp, char *const argv[], char *const envp[])
int rtapi_spawnp_as_root (pid_t *pid, const char *path, const posix_spawn_file_actions_t *file_actions, const posix_spawnattr_t *attrp, char *const argv[], char *const envp[])
int rtapi_is_kernelspace (void)
int rtapi_is_realtime (void)
int rtapi_open_as_root (const char *filename, int mode)
Macro Definition Documentation
RTAPI_BEGIN_DECLS
#define RTAPI_BEGIN_DECLS
Definition at line 78 of file rtapi.h.
RTAPI_END_DECLS
#define RTAPI_END_DECLS
Definition at line 79 of file rtapi.h.
RTAPI_NAME_LEN
#define RTAPI_NAME_LEN 31 /* length for module, etc, names */
RTAPI is a library providing a uniform API for several real time operating systems. As of ver 2.0, RTLinux and RTAI are supported. This file, 'rtapi.h', defines the RTAPI for both realtime and non-realtime code. This is a change from Rev 2, where the non- realtime (user space) API was defined in ulapi.h and used different function names. The symbols RTAPI and ULAPI are used to determine which mode is being compiled, RTAPI for realtime and ULAPI for non-realtime. The API is implemented in files named 'xxx_rtapi.c', where xxx is the RTOS. Copyright (C) 2003 John Kasunich <jmkasunich AT users DOT sourceforge DOT net> Copyright (C) 2003 Paul Corner <paul_c AT users DOT sourceforge DOT net> This library is based on version 1.0, which was released into the public domain by its author, Fred Proctor. Thanks Fred! This library is free software; you can redistribute it and/or modify it under the terms of version 2.1 of the GNU Lesser General Public License as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
THE AUTHORS OF THIS LIBRARY ACCEPT ABSOLUTELY NO LIABILITY FOR ANY HARM OR LOSS RESULTING FROM ITS USE. IT IS EXTREMELY UNWISE TO RELY ON SOFTWARE ALONE FOR SAFETY. Any machinery capable of harming persons must have provisions for completely removing power from all motors, etc, before persons enter any danger area. All machinery must be designed to comply with local and national safety codes, and the authors of this software can not, and do not, take any responsibility for such compliance.
This code was written as part of the EMC HAL project. For more information, go to www.linuxcnc.org.
Definition at line 72 of file rtapi.h.
rtapi_release_region
#define rtapi_release_region (base, size) ((void)0)
Definition at line 711 of file rtapi.h.
rtapi_request_region
#define rtapi_request_region (base, size, name) ((void*)-1)
Definition at line 710 of file rtapi.h.
Typedef Documentation
rtapi_msg_handler_t
typedef void(* rtapi_msg_handler_t) (msg_level_t level, const char *fmt, va_list ap)
'rtapi_get_msg_handler' and 'rtapi_set_msg_handler' access the function pointer used by rtapi_print and rtapi_print_msg. By default, messages appear in the kernel log, but by replacing the handler a user of the rtapi library can send the messages to another destination. Calling rtapi_set_msg_handler with NULL restores the default handler. Call from real-time init/cleanup code only. When called from rtapi_print(), 'level' is RTAPI_MSG_ALL, a level which should not normally be used with rtapi_print_msg().
Definition at line 192 of file rtapi.h.
Enumeration Type Documentation
msg_level_t
enum msg_level_t
'rtapi_print_msg()' prints a printf-style message when the level is less than or equal to the current message level set by rtapi_set_msg_level(). May be called from user, init/cleanup, and realtime code.
Enumerator
RTAPI_MSG_NONE
RTAPI_MSG_ERR
RTAPI_MSG_WARN
RTAPI_MSG_INFO
RTAPI_MSG_DBG
RTAPI_MSG_ALL
Definition at line 162 of file rtapi.h.
Function Documentation
rtapi_delay()
void rtapi_delay (long int nsec)
NOTE: These timing related functions are only available in realtime modules. User processes may not call them! rtapi_delay() is a simple delay. It is intended only for short delays, since it simply loops, wasting CPU cycles. 'nsec' is the desired delay, in nano-seconds. 'rtapi_delay_max() returns the max delay permitted (usually approximately 1/4 of the clock period). Any call to 'rtapi_delay()' requesting a delay longer than the max will delay for the max time only. 'rtapi_delay_max()' should be called before using 'rtapi_delay()' to make sure the required delays can be achieved. The actual resolution of the delay may be as good as one nano-second, or as bad as a several microseconds. May be called from init/cleanup code, and from within realtime tasks.
rtapi_delay_max()
long int rtapi_delay_max (void)
rtapi_exit()
int rtapi_exit (int module_id)
'rtapi_exit()' shuts down and cleans up the RTAPI. It must be called prior to exit by any module that called rtapi_init. 'module_id' is the ID code returned when that module called rtapi_init(). Returns a status code. rtapi_exit() may attempt to clean up any tasks, shared memory, and other resources allocated by the module, but should not be relied on to replace proper cleanup code within the module. Call only from within user or init/cleanup code, not from realtime tasks.
rtapi_fifo_delete()
int rtapi_fifo_delete (int fifo_id, int module_id)
'rtapi_fifo_delete()' is the counterpart to 'rtapi_fifo_new()'. It closes the fifo associated with 'fifo_ID'. 'module_id' is the ID of the calling module. Returns status code. Call only from within user or init/cleanup code, not from realtime tasks.
rtapi_fifo_new()
int rtapi_fifo_new (int key, int module_id, unsigned long int size, char mode)
NOTE: These semaphore related functions are only available in realtime modules. User processes may not call them! Consider the mutex functions listed above instead. 'rtapi_fifo_new()' creates a realtime fifo. 'key' identifies the fifo, all modules wishing to access the same fifo must use the same key. 'module_id' is the ID of the module making the call (see rtapi_init). 'size' is the depth of the fifo. 'mode' is either 'R' or 'W', to request either read or write access to the fifo. On success, it returns a positive integer ID, which is used for subsequent calls dealing with the fifo. On failure, returns a negative error code. Call only from within user or init/cleanup code, not from realtime tasks.
rtapi_fifo_read()
int rtapi_fifo_read (int fifo_id, char * buf, unsigned long int size)
FIFO notes. These comments apply to both read and write functions. A fifo is a character device, an int is typically four bytes long... If less than four bytes are sent to the fifo, expect corrupt data out of the other end ! The RTAI programming manual clearly states that the programmer is responsible for the data format and integrity.
Additional NOTE: IMHO you should be able to write any amount of data to a fifo, from 1 byte up to (and even beyond) the size of the fifo. At a future date, the somewhat peculiar RTAI fifos will be replaced with something that works better. John Kasunich NOTE: The fifo read and write functions operated differently in realtime and user space. The realtime versions do not block, but the userspace ones do. A future version of the RTAPI may defined different names for the blocking and non-blocking functions, but for now, just read the following docs carefully! 'rtapi_fifo_read()' reads data from 'fifo_id'. 'buf' is a buffer for the data, and 'size' is the maximum number of bytes to read. Returns the number of bytes actually read, or -EINVAL. If there is no data in the fifo, it blocks until data appears (or a signal occurs). If 'size' bytes are not available, it will read whatever is available, and return that count (will be greater than zero). If interrupted by a signal or some other error occurs, will return -EINVAL.
rtapi_fifo_write()
int rtapi_fifo_write (int fifo_id, char * buf, unsigned long int size)
'rtapi_fifo_write()' writes data to 'fifo_id'. Up to 'size' bytes are taken from the buffer at 'buf'. Returns the number of bytes actually written, or -EINVAL. If 'size' bytes of space are not available in the fifo, rtapi_fifo_write() may block, or it may write as many bytes as it can and return that count (which may be zero).
rtapi_get_clocks()
long long int rtapi_get_clocks (void)
rtapi_get_clocks returns the current time in CPU clocks. It is fast, since it just reads the TSC in the CPU instead of calling a kernel or RTOS function. Of course, times measured in CPU clocks are not as convenient, but for relative measurements this works fine. Its absolute value means nothing, but it is monotonically increasing* and can be used to schedule future events, or to time the duration of some activity. (* on SMP machines, the two TSC's may get out of sync, so if a task reads the TSC, gets swapped to the other CPU, and reads again, the value may decrease. RTAPI tries to force all RT tasks to run on one CPU.) Returns a 64 bit value. The resolution of the returned value is one CPU clock, which is usually a few nanoseconds to a fraction of a nanosecond. May be called from init/cleanup code, and from within realtime tasks.
Note that longlong math may be poorly supported on some platforms, especially in kernel space. Also note that rtapi_print() will NOT print longlongs. Most time measurements are relative, and should be done like this: deltat = (long int)(end_time - start_time); where end_time and start_time are longlong values returned from rtapi_get_time, and deltat is an ordinary long int (32 bits). This will work for times up to a second or so, depending on the CPU clock frequency. It is best used for millisecond and microsecond scale measurements though.
rtapi_get_msg_level()
int rtapi_get_msg_level (void)
Retrieve the message level set by the last call to rtapi_set_msg_level
rtapi_get_time()
long long int rtapi_get_time (void)
rtapi_get_time returns the current time in nanoseconds. Depending on the RTOS, this may be time since boot, or time since the clock period was set, or some other time. Its absolute value means nothing, but it is monotonically increasing and can be used to schedule future events, or to time the duration of some activity. Returns a 64 bit value. The resolution of the returned value may be as good as one nano-second, or as poor as several microseconds. May be called from init/cleanup code, and from within realtime tasks.
Experience has shown that the implementation of this function in some RTOS/Kernel combinations is horrible. It can take up to several microseconds, which is at least 100 times longer than it should, and perhaps a thousand times longer. Use it only if you MUST have results in seconds instead of clocks, and use it sparingly. See rtapi_get_clocks() instead.
Note that longlong math may be poorly supported on some platforms, especially in kernel space. Also note that rtapi_print() will NOT print longlongs. Most time measurements are relative, and should be done like this: deltat = (long int)(end_time - start_time); where end_time and start_time are longlong values returned from rtapi_get_time, and deltat is an ordinary long int (32 bits). This will work for times up to about 2 seconds.
Referenced by async_dispatcher(), and get_current_time_us().
rtapi_inb()
unsigned char rtapi_inb (unsigned int port)
'rtapi_inb() gets a byte from 'port'. Returns the byte. May be called from init/cleanup code, and from within realtime tasks. Note: This function always returns zero on the simulated RTOS. Note: Many platforms provide an inline inb() that is faster.
rtapi_init()
RTAPI_BEGIN_DECLS int rtapi_init (const char * modname)
'rtapi_init() sets up the RTAPI. It must be called by any module that intends to use the API, before any other RTAPI calls. 'modname' can optionally point to a string that identifies the module. The string will be truncated at RTAPI_NAME_LEN characters. If 'modname' is NULL, the system will assign a name. On success, returns a positive integer module ID, which is used for subsequent calls to rtapi_xxx_new, rtapi_xxx_delete, and rtapi_exit. On failure, returns an error code as defined above. Call only from within user or init/cleanup code, not from realtime tasks.
rtapi_is_kernelspace()
int rtapi_is_kernelspace (void)
rtapi_is_realtime()
int rtapi_is_realtime (void)
rtapi_open_as_root()
int rtapi_open_as_root (const char * filename, int mode)
rtapi_outb()
void rtapi_outb (unsigned char byte, unsigned int port)
NOTE: These interrupt related functions are only available in realtime modules. User processes may not call them! 'rtapi_outb() writes 'byte' to 'port'. May be called from init/cleanup code, and from within realtime tasks. Note: This function does nothing on the simulated RTOS. Note: Many platforms provide an inline outb() that is faster.
rtapi_print()
void rtapi_print (const char * fmt, ...)
'rtapi_print()' prints a printf style message. Depending on the RTOS and whether the program is being compiled for user space or realtime, the message may be printed to stdout, stderr, or to a kernel message log, etc. The calling syntax and format string is similar to printf except that floating point and longlongs are NOT supported in realtime and may not be supported in user space. For some RTOS's, a 80 byte buffer is used, so the format line and arguments should not produce a line more than 80 bytes long. (The buffer is protected against overflow.) Does not block, but can take a fairly long time, depending on the format string and OS. May be called from user, init/cleanup, and realtime code.
rtapi_print_msg()
void rtapi_print_msg (msg_level_t level, const char * fmt, ...)
Referenced by do_home_all(), do_home_joint(), FUNCTION(), get_homing_at_index_search_wait(), get_sequence_synchronized_state(), ini_read_float(), ini_read_int(), ini_read_string(), InitializeNewDevice(), main(), PEv2_AdditionalParametersGet(), PEv2_AdditionalParametersSet(), PoKeysHALComponent::PEv2_AxisConfigurationGet(), PoKeysHALComponent::PEv2_AxisConfigurationSet(), PEv2_ExternalOutputsSet(), PoKeysHALComponent::PEv2_HomingStateSyncedTrigger(), PEv2_PulseEngineSetup(), PEv2_Status2Get(), PEv2_StatusGet(), PK_CloneDeviceStructure(), PK_ConnectToDevice(), PK_ConnectToNetworkDevice(), PK_ConnectToPoKeysDevice(), PK_ConnectToPoKeysDevice_Ethernet(), PK_ConnectToPoKeysDevice_USB(), PK_EnumerateUSBDevices(), PK_InitializeNewDeviceAsync(), PK_RTCGetAsync(), PKEncoder_export_params(), PKEncoder_export_pins(), PKEncoder_Setup(), PKEncoder_Update(), PoKeysHALComponent::PKIO_export_pins(), PoKeysHALComponent::PKIO_ReadIniFile(), PoKeysHALComponent::PKIO_Setup(), PoKeysHALComponent::PKIO_Update(), PoKeysHALComponent::PKPEv2_ReadIniFile(), PoKeysHALComponent::PKPEv2_Setup(), PoKeysHALComponent::PKPEv2_Update(), PKPoExtBus_export_pins(), PKPoExtBus_Update(), PKPoNet_export_pins(), pokeys_read_ini(), SendEthRequest(), SendRequest(), SendRequest_NoResponse(), SendRequestAsync(), set_pokeys_ini_path(), TryConnectToDevice(), and user_mainloop().
rtapi_set_msg_level()
void int rtapi_set_msg_level (int level)
Set the maximum level of message to print. In userspace code, each component has its own independent message level. In realtime code, all components share a single message level. Returns 0 for success or -EINVAL if the level is out of range.
rtapi_shmem_delete()
int rtapi_shmem_delete (int shmem_id, int module_id)
'rtapi_shmem_delete()' frees the shared memory block associated with 'shmem_id'. 'module_id' is the ID of the calling module. Returns a status code. Call only from within user or init/cleanup code, not from realtime tasks.
rtapi_shmem_getptr()
int rtapi_shmem_getptr (int shmem_id, void ** ptr)
'rtapi_shmem_getptr()' sets '*ptr' to point to shared memory block associated with 'shmem_id'. Returns a status code. May be called from user code, init/cleanup code, or realtime tasks.
rtapi_shmem_new()
int rtapi_shmem_new (int key, int module_id, unsigned long int size)
NOTE: These realtime task related functions are only available in realtime modules. User processes may not call them! 'rtapi_shmem_new()' allocates a block of shared memory. 'key' identifies the memory block, and must be non-zero. All modules wishing to access the same memory must use the same key. 'module_id' is the ID of the module that is making the call (see rtapi_init). The block will be at least 'size' bytes, and may be rounded up. Allocating many small blocks may be very wasteful. When a particular block is allocated for the first time, all bytes are zeroed. Subsequent allocations of the same block by other modules or processes will not touch the contents of the block. On success, it returns a positive integer ID, which is used for all subsequent calls dealing with the block. On failure it returns a negative error code. Call only from within user or init/cleanup code, not from realtime tasks.
rtapi_snprintf()
int rtapi_snprintf (char * buf, unsigned long int size, const char * fmt, ...)
'rtapi_snprintf()' works like 'snprintf()' from the normal C library, except that it may not handle long longs. It is provided here because some RTOS kernels don't provide a realtime safe version of the function, and those that do don't provide support for printing doubles. On systems with a good kernel snprintf(), or in user space, this function simply calls the normal snprintf(). May be called from user, init/cleanup, and realtime code.
rtapi_spawn_as_root()
int rtapi_spawn_as_root (pid_t * pid, const char * path, const posix_spawn_file_actions_t * file_actions, const posix_spawnattr_t * attrp, char *const argv[], char *const envp[])
rtapi_spawnp_as_root()
int rtapi_spawnp_as_root (pid_t * pid, const char * path, const posix_spawn_file_actions_t * file_actions, const posix_spawnattr_t * attrp, char *const argv[], char *const envp[])
rtapi_vsnprintf()
int int rtapi_vsnprintf (char * buf, unsigned long size, const char * fmt, va_list args)
'rtapi_vsnprintf()' works like 'vsnprintf()' from the normal C library, except that it doesn't handle long longs. It is provided here because some RTOS kernels don't provide a realtime safe version of the function, and those that do don't provide support for printing doubles. On systems with a good kernel vsnprintf(), or in user space, this function simply calls the normal vsnrintf(). May be called from user, init/cleanup, and realtime code.
vsn_printf - Format a string and place it in a buffer @buf: The buffer to place the result into @size: The size of the buffer, including the trailing null space @fmt: The format string to use @args: Arguments for the format string
Definition at line 269 of file rtapi_vsnprintf.h.
References i, LEFT, PLUS, SPACE, SPECIAL, and ZEROPAD.
simple_strtol()
long int simple_strtol (const char * nptr, char ** endptr, int base)