LinuxCNC PoKeysLib-Comp: PoKeysHALComponent Class Reference
PoKeysHALComponent Class Reference
HAL Component: pokeys
Represents a single PoKeys device and its runtime state.
#include <PoKeysComp.h>
Public Types
enum pokeys_homing_algorithm_t
pokeys_homing_algorithm_t
enum pokeys_home_command_t
Homing command for the axis.
Public Member Functions
int PKIO_export_pins (char *prefix, long extra_arg, int id, all_IO_data_t *Io_data, sPoKeysDevice *dev)
Export HAL pins and parameters for PoKeys analog and digital I/O.
void PKIO_Update (sPoKeysDevice *dev)
Updates PoKeys I/O states from and to hardware.
void PKIO_Setup (sPoKeysDevice *dev)
Initializes the PoKeys digital and analog I/O configuration.
void PKIO_ReadIniFile (sPoKeysDevice *dev)
Reads and applies I/O configuration values for the PoKeys device from the INI file.
void PKIO_WriteIniFile (sPoKeysDevice *dev)
Writes the current PoKeys I/O configuration to the INI file.
int32_t PEv2_HomingStateSyncedTrigger (sPoKeysDevice *dev, int seq, pokeys_home_status_t RequiredState, pokeys_home_status_t NextState)
Triggers a synchronized homing state transition for all axes in a given homing sequence.
int32_t PEv2_AxisConfigurationGet (sPoKeysDevice *dev, int AxisId)
Retrieves and parses the axis configuration from the PoKeys Pulse Engine v2.
int32_t PEv2_AxisConfigurationSet (sPoKeysDevice *dev, int AxisId)
Set the axis configuration of the PoKeys device.
int PEv2_PulseEngineSetup (sPoKeysDevice *dev)
Configures the PulseEngine v2 using current settings.
void PKPEv2_Setup (sPoKeysDevice *dev)
Applies INI-based configuration to PulseEngine and IO.
void PKPEv2_Update (sPoKeysDevice *dev, bool HAL_Machine_On)
Updates PulseEngine feedback and status.
void PKPEv2_ReadIniFile (sPoKeysDevice *dev)
Reads configuration parameters for the PoKeys Pulse Engine v2 from the INI file.
void PKPEv2_WriteIniFile (sPoKeysDevice *dev)
Write the configuration settings to the INI file.
Data Fields
int device_number
Detailed Description
Represents a single PoKeys device and its runtime state.
This class-like structure holds configuration, IO mappings, and PulseEngine data for a single PoKeys device. All functions operating on this structure are considered class methods.
Definition at line 39 of file PoKeysComp.h.
Member Function Documentation
PKPEv2_ReadIniFile()
void PKPEv2_ReadIniFile (sPoKeysDevice * dev)
Reads configuration parameters for the PoKeys Pulse Engine v2 from the INI file.
This function loads all Pulse Engine v2 settings from the [POKEYS] section of the HAL INI file. It initializes general settings like probe, emergency input/output pins, and the state of the pulse engine and charge pump. For each available axis, it loads axis configuration, switch assignments, soft limits, speed parameters, homing algorithms, filter settings, and MPG (manual pulse generator) jogging options.
The values are stored into the shared PEv2_data structure, which is later used during runtime for control and motion logic.
Parameters
dev Pointer to the PoKeys device structure. This provides the number of available axes via dev->PEv2.info.nrOfAxes.
Note
This function should be called once during initialization to prepare the component for correct operation.
INI parameters read include (per axis or globally):
PEv2_ProbeInput, PEv2_EmergencyInputPin, PEv2_ChargePumpEnabled, etc.
Axis-specific: PEv2_AxisEnabled_#, PEv2_AxesConfig_#, PEv2_MaxSpeed_#, PEv2_HomingSpeed_#, PEv2_AxesSwitchConfig_#, etc.
Digital input/output pin assignments and inversion flags
Homing logic and movement constraints
Definition at line 1625 of file PoKeysCompPulseEngine_v2.c.
References dev, sPoKeysPEv2::info, ini_read_float(), ini_read_int(), sPoKeysPEv2info::nrOfAxes, sPoKeysDevice::PEv2, PEv2_data_t::PEv2_AxesConfig, PEv2_data_t::PEv2_AxesSwitchConfig, PEv2_data_t::PEv2_AxisEnabled, PEv2_data_t::PEv2_AxisEnabledMasked, PEv2_data_t::PEv2_AxisInternalPlanner, PEv2_data_t::PEv2_AxisInverted, PEv2_data_t::PEv2_AxisInvertedHome, PEv2_data_t::PEv2_AxisPositionMode, PEv2_data_t::PEv2_AxisSoftLimitEnabled, PEv2_data_t::PEv2_ChargePumpEnabled, PEv2_data, PEv2_data_t::PEv2_digin_Emergency_invert, PEv2_data_t::PEv2_digin_Emergency_Pin, PEv2_data_t::PEv2_digin_Home_Enabled, PEv2_data_t::PEv2_digin_Home_Filter, PEv2_data_t::PEv2_digin_Home_invert, PEv2_data_t::PEv2_digin_Home_OnLimitN, PEv2_data_t::PEv2_digin_Home_OnLimitP, PEv2_data_t::PEv2_digin_Home_Pin, PEv2_data_t::PEv2_digin_LimitN_Enabled, PEv2_data_t::PEv2_digin_LimitN_Filter, PEv2_data_t::PEv2_digin_LimitN_invert, PEv2_data_t::PEv2_digin_LimitN_Pin, PEv2_data_t::PEv2_digin_LimitP_Enabled, PEv2_data_t::PEv2_digin_LimitP_Filter, PEv2_data_t::PEv2_digin_LimitP_invert, PEv2_data_t::PEv2_digin_LimitP_Pin, PEv2_data_t::PEv2_digin_Probe_Filter, PEv2_data_t::PEv2_digin_Probe_invert, PEv2_data_t::PEv2_digin_Probe_Pin, PEv2_data_t::PEv2_digout_AxisEnable_invert, PEv2_data_t::PEv2_digout_AxisEnable_Pin, PEv2_data_t::PEv2_digout_Emergency_Pin, PEv2_data_t::PEv2_HomeAlg_OnHome_ArmEncoder, PEv2_data_t::PEv2_HomeAlg_OnHome_ReducedSpeed, PEv2_data_t::PEv2_HomeAlg_OnHome_RevDirection, PEv2_data_t::PEv2_HomeAlg_OnHome_Stop, PEv2_data_t::PEv2_HomeAlg_OutHome_ArmEncoder, PEv2_data_t::PEv2_HomeAlg_OutHome_ReducedSpeed, PEv2_data_t::PEv2_HomeAlg_OutHome_RevDirection, PEv2_data_t::PEv2_HomeAlg_OutHome_Stop, PEv2_data_t::PEv2_HomeBackOffDistance, PEv2_data_t::PEv2_HomingAlgorithm, PEv2_data_t::PEv2_HomingReturnSpeed, PEv2_data_t::PEv2_HomingSpeed, PEv2_data_t::PEv2_MaxAcceleration, PEv2_data_t::PEv2_MaxDecceleration, PEv2_data_t::PEv2_MaxSpeed, PEv2_data_t::PEv2_MPGjogDivider, PEv2_data_t::PEv2_MPGjogEncoder, PEv2_data_t::PEv2_MPGjogMultiplier, PEv2_data_t::PEv2_PulseEngineEnabled, PEv2_data_t::PEv2_PulseGeneratorType, PEv2_data_t::PEv2_SoftLimitMaximum, PEv2_data_t::PEv2_SoftLimitMinimum, PEv2_data_t::PEv2_stepgen_DEADBAND, PEv2_data_t::PEv2_stepgen_ENCODER_SCALE, PEv2_data_t::PEv2_stepgen_HOME, PEv2_data_t::PEv2_stepgen_HOME_FINAL_VEL, PEv2_data_t::PEv2_stepgen_HOME_IGNORE_LIMITS, PEv2_data_t::PEv2_stepgen_HOME_LATCH_VEL, PEv2_data_t::PEv2_stepgen_HOME_OFFSET, PEv2_data_t::PEv2_stepgen_HOME_SEARCH_VEL, PEv2_data_t::PEv2_stepgen_MAX_LIMIT, PEv2_data_t::PEv2_stepgen_MAX_OUTPUT, PEv2_data_t::PEv2_stepgen_MIN_LIMIT, PEv2_data_t::PEv2_stepgen_STEP_SCALE, PEv2_data_t::PEv2_stepgen_STEPGEN_MAXACCEL, PEv2_data_t::PEv2_stepgen_STEPGEN_MAXVEL, PEv2_data_t::PEv2_stepgen_TYPE, PK_PEv2_StatusGet(), positions_reset_onbootup_done, RTAPI_MSG_ERR, and rtapi_print_msg().
Referenced by pokeys_read_ini().
PKPEv2_WriteIniFile()
void PKPEv2_WriteIniFile (sPoKeysDevice * dev)
Write the configuration settings to the INI file.
Parameters
dev
Definition at line 1893 of file PoKeysCompPulseEngine_v2.c.
References dev, sPoKeysPEv2::info, ini_write_float(), ini_write_int(), sPoKeysPEv2info::nrOfAxes, sPoKeysDevice::PEv2, PEv2_data_t::PEv2_AxesConfig, PEv2_data_t::PEv2_AxesSwitchConfig, PEv2_data_t::PEv2_AxisEnabled, PEv2_data_t::PEv2_AxisEnabledMasked, PEv2_data_t::PEv2_AxisInternalPlanner, PEv2_data_t::PEv2_AxisInverted, PEv2_data_t::PEv2_AxisInvertedHome, PEv2_data_t::PEv2_AxisPositionMode, PEv2_data_t::PEv2_AxisSoftLimitEnabled, PEv2_data_t::PEv2_ChargePumpEnabled, PEv2_data, PEv2_data_t::PEv2_digin_Emergency_invert, PEv2_data_t::PEv2_digin_Emergency_Pin, PEv2_data_t::PEv2_digin_Home_Enabled, PEv2_data_t::PEv2_digin_Home_Filter, PEv2_data_t::PEv2_digin_Home_invert, PEv2_data_t::PEv2_digin_Home_OnLimitN, PEv2_data_t::PEv2_digin_Home_OnLimitP, PEv2_data_t::PEv2_digin_Home_Pin, PEv2_data_t::PEv2_digin_LimitN_Enabled, PEv2_data_t::PEv2_digin_LimitN_Filter, PEv2_data_t::PEv2_digin_LimitN_invert, PEv2_data_t::PEv2_digin_LimitN_Pin, PEv2_data_t::PEv2_digin_LimitP_Enabled, PEv2_data_t::PEv2_digin_LimitP_Filter, PEv2_data_t::PEv2_digin_LimitP_invert, PEv2_data_t::PEv2_digin_LimitP_Pin, PEv2_data_t::PEv2_digin_Probe_Filter, PEv2_data_t::PEv2_digin_Probe_invert, PEv2_data_t::PEv2_digin_Probe_Pin, PEv2_data_t::PEv2_digout_AxisEnable_invert, PEv2_data_t::PEv2_digout_AxisEnable_Pin, PEv2_data_t::PEv2_digout_Emergency_Pin, PEv2_data_t::PEv2_HomeAlg_OnHome_ArmEncoder, PEv2_data_t::PEv2_HomeAlg_OnHome_ReducedSpeed, PEv2_data_t::PEv2_HomeAlg_OnHome_RevDirection, PEv2_data_t::PEv2_HomeAlg_OnHome_Stop, PEv2_data_t::PEv2_HomeAlg_OutHome_ArmEncoder, PEv2_data_t::PEv2_HomeAlg_OutHome_ReducedSpeed, PEv2_data_t::PEv2_HomeAlg_OutHome_RevDirection, PEv2_data_t::PEv2_HomeAlg_OutHome_Stop, PEv2_data_t::PEv2_HomeBackOffDistance, PEv2_data_t::PEv2_HomingAlgorithm, PEv2_data_t::PEv2_HomingReturnSpeed, PEv2_data_t::PEv2_HomingSpeed, PEv2_data_t::PEv2_MaxAcceleration, PEv2_data_t::PEv2_MaxDecceleration, PEv2_data_t::PEv2_MaxSpeed, PEv2_data_t::PEv2_MPGjogDivider, PEv2_data_t::PEv2_MPGjogEncoder, PEv2_data_t::PEv2_MPGjogMultiplier, PEv2_data_t::PEv2_PulseEngineEnabled, PEv2_data_t::PEv2_PulseGeneratorType, PEv2_data_t::PEv2_SoftLimitMaximum, and PEv2_data_t::PEv2_SoftLimitMinimum.
Referenced by pokeys_write_ini().
Field Documentation
device_number
int PoKeysHALComponent::device_number
Definition at line 40 of file PoKeysComp.h.
The documentation for this class was generated from the following files:
/home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/pokeys_uspace/PoKeysComp.h
/home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/pokeys_uspace/PoKeysCompPulseEngine_v2.c
/home/cnc/actions-runner/_work/LinuxCnc_PokeysLibComp/LinuxCnc_PokeysLibComp/pokeys_uspace/PokeysCompPulsEngine_base.c