blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/zarfld/LinuxCnc_PokeysLibComp/issues/new?template=bug_report.md
    about: Report a bug to help us improve
  - name: Feature Request
    url: https://github.com/zarfld/LinuxCnc_PokeysLibComp/issues/new?template=feature_request.md
    about: Suggest a new feature or enhancement
  - name: Documentation Task
    url: https://github.com/zarfld/LinuxCnc_PokeysLibComp/issues/new?template=documentation.md
    about: Contribute to the documentation
  - name: GitHub Discussions
    url: https://github.com/zarfld/LinuxCnc_PokeysLibComp/discussions
    about: Engage in conversations, ask questions, and share ideas
milestones:
  - name: v1.0 release
    description: Milestone for the v1.0 release of the project
    due_on: 2023-12-31T23:59:59Z
  - name: production rollout
    description: Milestone for the production rollout phase
    due_on: 2024-03-31T23:59:59Z
labels:
  - name: in development
    color: '#1d76db'
    description: Issues being handled in the development environment
  - name: in staging
    color: '#e4e669'
    description: Issues being handled in the staging environment
  - name: in production
    color: '#0e8a16'
    description: Issues being handled in the production environment
