name: Clang Static Analyzer

on:
  push:
    branches:
      - main
      - feature/**
      - bugfix/**
      - improvement/**
      - hotfix/**
  pull_request:
    branches:
      - main
      - feature/**
      - bugfix/**
      - improvement/**
      - hotfix/**

jobs:
  format-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Clang-Format
        run: sudo apt install clang-format -y

      - name: Apply Clang-Format
        run: find . -name "*.c" -o -name "*.h" | xargs clang-format -i

      # Auto-commit only on main (post-merge)
      - name: Commit Changes (if needed)
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-format code with clang-format" || echo "Nothing to commit"
          git push origin main

      # Comment formatting issues on PR
      - name: Comment formatting status
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '⚠️ Code formatting failed. Please run `clang-format` locally and push again.'
            })

  analyze:
    runs-on: self-hosted

    steps:
      - name: reinit runner directory
        run: |
          sudo chown -R cnc:cnc /home/cnc/actions-runner
          sudo chown -R cnc:cnc /home/cnc/actions-runner/_work
          chmod -R u+rwx /home/cnc/actions-runner/_work

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Clang
        run: |
          sudo apt-get install -y clang
          sudo apt-get install -y clang-tools

      - name: init submodule
        run: sudo /bin/bash "./prerequisites.sh"

      - name: Run Clang Static Analyzer
        run: |
          mkdir -p build
          cd build
          cmake ..
          sudo scan-build make

      - name: Upload Clang Static Analyzer Report
        uses: actions/upload-artifact@v4
        with:
          name: clang-analyzer-report
          path: build/scan-build
