name: Clang Static Analyzer

on:
  push:
    branches:
      - main
      - feature/**
      - bugfix/**
      - improvement/**
      - hotfix/**
  pull_request:
    branches:
      - main
      - feature/**
      - bugfix/**
      - improvement/**
      - hotfix/**

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Clang
        run: sudo apt-get install -y clang

      - name: Run Clang Static Analyzer
        run: |
          mkdir -p build
          cd build
          cmake ..
          scan-build make

      - name: Upload Clang Static Analyzer Report
        uses: actions/upload-artifact@v3
        with:
          name: clang-analyzer-report
          path: build/scan-build
